const fs = require('fs');
const path = require('path');
const DIR = path.join(__dirname, 'frontend/src/i18n/locales');
const LANGS = ['ko','en','ja','zh','zh-TW','de','th','vi','id'];

// Read inject_reviews_i18n.cjs for keys
const injector = require('./inject_reviews_i18n.cjs');

// Simple approach: find last } of reviews block and insert before it
LANGS.forEach(lang => {
  const file = path.join(DIR, `${lang}.js`);
  let code = fs.readFileSync(file, 'utf8');

  // Skip if already injected
  if (code.includes('tabDashboard:')) {
    console.log(`${lang}: already has tabDashboard, skipping`);
    return;
  }
  
  const revIdx = code.indexOf('reviews:{');
  if (revIdx < 0) {
    console.log(`${lang}: no reviews block`);
    return;
  }
  
  // Find the closing } of reviews: manually scan with depth counter
  let depth = 0;
  let endPos = -1;
  let inString = false;
  let escape = false;
  
  for (let i = revIdx + 8; i < code.length; i++) {
    const ch = code[i];
    
    if (escape) { escape = false; continue; }
    if (ch === '\\' && inString) { escape = true; continue; }
    
    if (inString) {
      if (ch === '"') inString = false;
      continue;
    }
    
    if (ch === '"') { inString = true; continue; }
    if (ch === '{') { depth++; continue; }
    if (ch === '}') {
      if (depth === 0) { endPos = i; break; }
      depth--;
    }
  }
  
  if (endPos < 0) {
    console.log(`${lang}: cannot find end of reviews block`);
    return;
  }
  
  console.log(`${lang}: reviews block ends at ${endPos}, inserting keys...`);
  
  // Read new keys from inject script
  const keysFile = fs.readFileSync(path.join(__dirname, 'inject_reviews_i18n.cjs'), 'utf8');
  
  // Parse the keys for this lang manually
  const langKey = lang === 'zh-TW' ? '"zh-TW"' : lang;
  
  // Just hardcode the insertion for each lang
  const insertions = getInsertions(lang);
  
  code = code.substring(0, endPos) + ',' + insertions + code.substring(endPos);
  fs.writeFileSync(file, code, 'utf8');
  
  // Verify
  try {
    const fn = new Function(code.replace('export default', 'return'));
    const obj = fn();
    const count = obj.reviews ? Object.keys(obj.reviews).length : 0;
    console.log(`  => ${count} reviews keys, guideTitle=${!!obj.reviews?.guideTitle}`);
  } catch (e) {
    console.log(`  => PARSE ERROR: ${e.message.substring(0, 100)}`);
  }
});

function getInsertions(lang) {
  const ALL = {
ko: `tabDashboard:"대시보드",tabFeed:"리뷰 관리",tabTrend:"트렌드",tabSettings:"설정",tabGuide:"가이드",kpiTotalSub2:"연동 채널 합산",kpiAvgRatingSub2:"전 채널 가중 평균",noData:"데이터가 없습니다",close:"닫기",noTrendData:"트렌드 데이터가 없습니다",noTrendDataSub:"리뷰 데이터가 쌓이면 감성 분석 트렌드가 자동으로 표시됩니다.",trendTitle:"감성 분석 트렌드",sentimentBar:"감성 비율 분석",settingsTitle:"리뷰 관리 설정",aiToneLabel:"AI 답변 톤 설정",toneProfessional:"프로페셔널",toneFriendly:"친근한",toneFormal:"격식체",autoEscalateLabel:"자동 에스컬레이션",autoEscalateDesc:"부정 리뷰 1★ 자동 에스컬레이션 활성화",slackWebhookLabel:"Slack 알림 Webhook",slackWebhookSub:"부정 키워드 급증 시 자동 알림을 받을 Slack Webhook URL을 입력하세요.",guideTitle:"리뷰 & UGC 관리 이용 가이드",guideSub:"리뷰 수집부터 AI 감성 분석, 자동 답변, CS 에스컬레이션, 트렌드 모니터링까지 전체 워크플로우를 안내합니다.",guideStepsTitle:"리뷰 관리 6단계",guideStep1Title:"리뷰 수집",guideStep1Desc:"판매 채널에서 리뷰를 자동으로 수집합니다. 연동허브에서 API 키를 등록하면 채널이 자동으로 추가됩니다.",guideStep2Title:"AI 감성 분석",guideStep2Desc:"수집된 리뷰를 AI가 긍정/중립/부정으로 자동 분류합니다. 부정 키워드를 실시간으로 모니터링합니다.",guideStep3Title:"AI 답변 초안",guideStep3Desc:"각 리뷰에 대해 AI가 톤과 맥락에 맞는 답변 초안을 자동 생성합니다.",guideStep4Title:"CS 에스컬레이션",guideStep4Desc:"심각한 부정 리뷰를 CS팀에 자동 에스컬레이션합니다. Slack 알림과 연동됩니다.",guideStep5Title:"트렌드 분석",guideStep5Desc:"시간대별 감성 비율 변화를 추적합니다. 부정 키워드 급증을 자동 감지합니다.",guideStep6Title:"성과 리포트",guideStep6Desc:"채널별 평점, 응답률, 에스컬레이션 처리율을 종합 분석합니다.",guideTabsTitle:"탭별 기능 안내",guideDashName:"대시보드",guideDashDesc:"KPI 요약, 채널별 평점, 부정 키워드 모니터링",guideFeedName:"리뷰 관리",guideFeedDesc:"리뷰 필터링, AI 답변 생성, CS 에스컬레이션",guideTrendName:"트렌드",guideTrendDesc:"감성 비율 분석 및 시계열 트렌드",guideSettingsName:"설정",guideSettingsDesc:"AI 톤 설정, 자동 에스컬레이션, Slack 알림",guideGuideName:"이용 가이드",guideGuideDesc:"리뷰 관리 워크플로우 안내",guideTipsTitle:"팁 & 모범 사례",guideTip1:"부정 리뷰에는 24시간 내 응답하면 고객 만족도가 크게 향상됩니다.",guideTip2:"AI 답변 초안은 반드시 검토 후 발송하세요.",guideTip3:"부정 키워드 Top 5를 주기적으로 확인하여 제품 개선에 활용하세요.",guideTip4:"Slack Webhook을 설정하면 부정 리뷰 급증 시 즉시 알림을 받을 수 있습니다.",guideTip5:"채널별 평점을 비교하여 특정 채널에서 반복되는 불만 사항을 파악하세요."`,
en: `tabDashboard:"Dashboard",tabFeed:"Review Feed",tabTrend:"Trends",tabSettings:"Settings",tabGuide:"Guide",kpiTotalSub2:"Connected channels total",kpiAvgRatingSub2:"Weighted average across all channels",noData:"No data available",close:"Close",noTrendData:"No trend data available",noTrendDataSub:"Sentiment analysis trends will appear automatically as review data accumulates.",trendTitle:"Sentiment Analysis Trends",sentimentBar:"Sentiment Ratio Analysis",settingsTitle:"Review Management Settings",aiToneLabel:"AI Reply Tone",toneProfessional:"Professional",toneFriendly:"Friendly",toneFormal:"Formal",autoEscalateLabel:"Auto Escalation",autoEscalateDesc:"Enable automatic escalation for 1★ negative reviews",slackWebhookLabel:"Slack Notification Webhook",slackWebhookSub:"Enter your Slack Webhook URL to receive alerts when negative keywords spike.",guideTitle:"Reviews & UGC Management Guide",guideSub:"Complete workflow from review collection to AI sentiment analysis, auto-replies, CS escalation, and trend monitoring.",guideStepsTitle:"Review Management 6 Steps",guideStep1Title:"Review Collection",guideStep1Desc:"Automatically collect reviews from sales channels. Channels are auto-added when API keys are registered in the Integration Hub.",guideStep2Title:"AI Sentiment Analysis",guideStep2Desc:"AI automatically classifies reviews as positive/neutral/negative. Negative keywords are monitored in real-time.",guideStep3Title:"AI Reply Drafts",guideStep3Desc:"AI generates context-appropriate reply drafts for each review.",guideStep4Title:"CS Escalation",guideStep4Desc:"Automatically escalate severe negative reviews to the CS team. Integrates with Slack notifications.",guideStep5Title:"Trend Analysis",guideStep5Desc:"Track sentiment ratio changes over time. Auto-detect negative keyword spikes.",guideStep6Title:"Performance Report",guideStep6Desc:"Comprehensive analysis of channel ratings, response rates, and escalation handling.",guideTabsTitle:"Tab Features",guideDashName:"Dashboard",guideDashDesc:"KPI summary, channel ratings, negative keyword monitoring",guideFeedName:"Review Feed",guideFeedDesc:"Review filtering, AI reply generation, CS escalation",guideTrendName:"Trends",guideTrendDesc:"Sentiment ratio analysis and time-series trends",guideSettingsName:"Settings",guideSettingsDesc:"AI tone settings, auto-escalation, Slack alerts",guideGuideName:"User Guide",guideGuideDesc:"Review management workflow guide",guideTipsTitle:"Tips & Best Practices",guideTip1:"Responding to negative reviews within 24 hours significantly improves customer satisfaction.",guideTip2:"Always review AI reply drafts before sending.",guideTip3:"Regularly check Top 5 negative keywords for product improvements.",guideTip4:"Set up Slack Webhook for instant alerts on negative review spikes.",guideTip5:"Compare ratings across channels to identify recurring complaints."`,
ja: `tabDashboard:"ダッシュボード",tabFeed:"レビュー管理",tabTrend:"トレンド",tabSettings:"設定",tabGuide:"ガイド",kpiTotalSub2:"接続チャネル合計",kpiAvgRatingSub2:"全チャネル加重平均",noData:"データがありません",close:"閉じる",noTrendData:"トレンドデータがありません",noTrendDataSub:"レビューデータが蓄積されるとトレンドが表示されます。",trendTitle:"感情分析トレンド",sentimentBar:"感情比率分析",settingsTitle:"レビュー管理設定",aiToneLabel:"AI返信トーン",toneProfessional:"プロフェッショナル",toneFriendly:"フレンドリー",toneFormal:"フォーマル",autoEscalateLabel:"自動エスカレーション",autoEscalateDesc:"1★レビュー自動エスカレーション",slackWebhookLabel:"Slack Webhook",slackWebhookSub:"Slack Webhook URLを入力してください。",guideTitle:"レビュー＆UGC管理ガイド",guideSub:"レビュー収集からAI感情分析、自動返信、CSエスカレーションまでのワークフロー。",guideStepsTitle:"レビュー管理6ステップ",guideStep1Title:"レビュー収集",guideStep1Desc:"販売チャネルからレビューを自動収集します。統合ハブでAPIキーを登録するとチャネルが自動追加されます。",guideStep2Title:"AI感情分析",guideStep2Desc:"AIがレビューをポジティブ/ニュートラル/ネガティブに自動分類します。",guideStep3Title:"AI返信案",guideStep3Desc:"各レビューに対してAIがコンテキストに合った返信案を生成します。",guideStep4Title:"CSエスカレーション",guideStep4Desc:"深刻なネガティブレビューをCSチームに自動エスカレーションします。",guideStep5Title:"トレンド分析",guideStep5Desc:"感情比率変化を時系列で追跡します。",guideStep6Title:"パフォーマンスレポート",guideStep6Desc:"チャネル別評価と応答率を総合分析します。",guideTabsTitle:"タブ機能",guideDashName:"ダッシュボード",guideDashDesc:"KPI要約とチャネル評価",guideFeedName:"レビュー管理",guideFeedDesc:"フィルタリング、AI返信、エスカレーション",guideTrendName:"トレンド",guideTrendDesc:"感情比率分析",guideSettingsName:"設定",guideSettingsDesc:"AIトーン、自動エスカレーション",guideGuideName:"ガイド",guideGuideDesc:"ワークフロー案内",guideTipsTitle:"ヒント",guideTip1:"ネガティブレビューには24時間以内に回答しましょう。",guideTip2:"AI返信案は送信前に必ず確認してください。",guideTip3:"ネガティブキーワードTop5を定期確認してください。",guideTip4:"Slack Webhookで即座にアラートを受けられます。",guideTip5:"チャネル別評価を比較して問題を把握してください。"`,
zh: `tabDashboard:"仪表盘",tabFeed:"评论管理",tabTrend:"趋势",tabSettings:"设置",tabGuide:"指南",kpiTotalSub2:"已连接渠道总计",kpiAvgRatingSub2:"所有渠道加权平均",noData:"暂无数据",close:"关闭",noTrendData:"暂无趋势数据",noTrendDataSub:"评论数据积累后趋势将自动显示。",trendTitle:"情感分析趋势",sentimentBar:"情感比例分析",settingsTitle:"评论管理设置",aiToneLabel:"AI回复语气",toneProfessional:"专业",toneFriendly:"友好",toneFormal:"正式",autoEscalateLabel:"自动升级",autoEscalateDesc:"启用1★差评自动升级",slackWebhookLabel:"Slack Webhook",slackWebhookSub:"输入Slack Webhook URL接收通知。",guideTitle:"评论与UGC管理指南",guideSub:"从评论收集到AI分析的完整工作流程。",guideStepsTitle:"评论管理6步骤",guideStep1Title:"评论收集",guideStep1Desc:"自动从销售渠道收集评论。注册API密钥后渠道自动添加。",guideStep2Title:"AI情感分析",guideStep2Desc:"AI自动将评论分类为正面/中性/负面。",guideStep3Title:"AI回复草稿",guideStep3Desc:"AI为每条评论生成适合语境的回复草稿。",guideStep4Title:"CS升级",guideStep4Desc:"自动将严重差评升级到CS团队。",guideStep5Title:"趋势分析",guideStep5Desc:"追踪情感比例变化。",guideStep6Title:"绩效报告",guideStep6Desc:"综合分析渠道评分和响应率。",guideTabsTitle:"标签功能",guideDashName:"仪表盘",guideDashDesc:"KPI摘要和渠道评分",guideFeedName:"评论管理",guideFeedDesc:"筛选、AI回复、CS升级",guideTrendName:"趋势",guideTrendDesc:"情感比例分析",guideSettingsName:"设置",guideSettingsDesc:"AI语气、自动升级",guideGuideName:"指南",guideGuideDesc:"工作流程指南",guideTipsTitle:"技巧",guideTip1:"24小时内回复差评可提高满意度。",guideTip2:"发送前务必审核AI草稿。",guideTip3:"定期检查负面关键词Top5。",guideTip4:"设置Slack Webhook即时通知。",guideTip5:"比较渠道评分发现问题。"`,
"zh-TW": `tabDashboard:"儀表板",tabFeed:"評論管理",tabTrend:"趨勢",tabSettings:"設定",tabGuide:"指南",kpiTotalSub2:"已連接頻道總計",kpiAvgRatingSub2:"所有頻道加權平均",noData:"暫無資料",close:"關閉",noTrendData:"暫無趨勢資料",noTrendDataSub:"評論資料累積後趨勢將自動顯示。",trendTitle:"情感分析趨勢",sentimentBar:"情感比例分析",settingsTitle:"評論管理設定",aiToneLabel:"AI回覆語氣",toneProfessional:"專業",toneFriendly:"友善",toneFormal:"正式",autoEscalateLabel:"自動升級",autoEscalateDesc:"啟用1★差評自動升級",slackWebhookLabel:"Slack Webhook",slackWebhookSub:"輸入Slack Webhook URL接收通知。",guideTitle:"評論與UGC管理指南",guideSub:"從評論收集到AI分析的完整工作流程。",guideStepsTitle:"評論管理6步驟",guideStep1Title:"評論收集",guideStep1Desc:"自動從銷售頻道收集評論。註冊API金鑰後頻道自動新增。",guideStep2Title:"AI情感分析",guideStep2Desc:"AI自動將評論分類為正面/中性/負面。",guideStep3Title:"AI回覆草稿",guideStep3Desc:"AI為每條評論生成適合語境的回覆草稿。",guideStep4Title:"CS升級",guideStep4Desc:"自動將嚴重差評升級到CS團隊。",guideStep5Title:"趨勢分析",guideStep5Desc:"追蹤情感比例變化。",guideStep6Title:"績效報告",guideStep6Desc:"綜合分析頻道評分和回應率。",guideTabsTitle:"標籤功能",guideDashName:"儀表板",guideDashDesc:"KPI摘要和頻道評分",guideFeedName:"評論管理",guideFeedDesc:"篩選、AI回覆、CS升級",guideTrendName:"趨勢",guideTrendDesc:"情感比例分析",guideSettingsName:"設定",guideSettingsDesc:"AI語氣、自動升級",guideGuideName:"指南",guideGuideDesc:"工作流程指南",guideTipsTitle:"技巧",guideTip1:"24小時內回覆差評可提高滿意度。",guideTip2:"發送前務必審核AI草稿。",guideTip3:"定期檢查負面關鍵字Top5。",guideTip4:"設定Slack Webhook即時通知。",guideTip5:"比較頻道評分發現問題。"`,
de: `tabDashboard:"Dashboard",tabFeed:"Bewertungen",tabTrend:"Trends",tabSettings:"Einstellungen",tabGuide:"Anleitung",kpiTotalSub2:"Verbundene Kanäle gesamt",kpiAvgRatingSub2:"Gewichteter Durchschnitt",noData:"Keine Daten",close:"Schließen",noTrendData:"Keine Trenddaten",noTrendDataSub:"Trends werden automatisch angezeigt.",trendTitle:"Stimmungsanalyse-Trends",sentimentBar:"Stimmungsverhältnis",settingsTitle:"Einstellungen",aiToneLabel:"KI-Antwortton",toneProfessional:"Professionell",toneFriendly:"Freundlich",toneFormal:"Formell",autoEscalateLabel:"Auto-Eskalation",autoEscalateDesc:"1★ Auto-Eskalation aktivieren",slackWebhookLabel:"Slack Webhook",slackWebhookSub:"Slack Webhook-URL eingeben.",guideTitle:"Bewertungs- & UGC-Verwaltungsanleitung",guideSub:"Vollständiger Workflow von Bewertungssammlung bis KI-Analyse.",guideStepsTitle:"6 Schritte",guideStep1Title:"Bewertungssammlung",guideStep1Desc:"Automatische Sammlung aus Verkaufskanälen.",guideStep2Title:"KI-Stimmungsanalyse",guideStep2Desc:"KI klassifiziert automatisch.",guideStep3Title:"KI-Antwortentwürfe",guideStep3Desc:"KI generiert kontextgerechte Entwürfe.",guideStep4Title:"CS-Eskalation",guideStep4Desc:"Automatische Eskalation negativer Bewertungen.",guideStep5Title:"Trendanalyse",guideStep5Desc:"Stimmungsveränderungen verfolgen.",guideStep6Title:"Leistungsbericht",guideStep6Desc:"Umfassende Kanalanalyse.",guideTabsTitle:"Tab-Funktionen",guideDashName:"Dashboard",guideDashDesc:"KPI und Kanalbewertungen",guideFeedName:"Bewertungen",guideFeedDesc:"Filterung und KI-Antworten",guideTrendName:"Trends",guideTrendDesc:"Stimmungsanalyse",guideSettingsName:"Einstellungen",guideSettingsDesc:"KI-Ton und Eskalation",guideGuideName:"Anleitung",guideGuideDesc:"Workflow-Anleitung",guideTipsTitle:"Tipps",guideTip1:"Innerhalb von 24h antworten.",guideTip2:"KI-Entwürfe prüfen.",guideTip3:"Top-5 Keywords prüfen.",guideTip4:"Slack-Webhook einrichten.",guideTip5:"Kanalbewertungen vergleichen."`,
th: `tabDashboard:"แดชบอร์ด",tabFeed:"จัดการรีวิว",tabTrend:"เทรนด์",tabSettings:"การตั้งค่า",tabGuide:"คู่มือ",kpiTotalSub2:"รวมช่องที่เชื่อมต่อ",kpiAvgRatingSub2:"ค่าเฉลี่ยถ่วงน้ำหนัก",noData:"ไม่มีข้อมูล",close:"ปิด",noTrendData:"ไม่มีข้อมูลเทรนด์",noTrendDataSub:"เทรนด์จะแสดงอัตโนมัติเมื่อมีข้อมูล",trendTitle:"เทรนด์การวิเคราะห์",sentimentBar:"สัดส่วนความรู้สึก",settingsTitle:"การตั้งค่า",aiToneLabel:"โทนการตอบ AI",toneProfessional:"มืออาชีพ",toneFriendly:"เป็นกันเอง",toneFormal:"ทางการ",autoEscalateLabel:"ยกระดับอัตโนมัติ",autoEscalateDesc:"เปิดใช้งานยกระดับ 1★",slackWebhookLabel:"Slack Webhook",slackWebhookSub:"ป้อน URL Slack Webhook",guideTitle:"คู่มือจัดการรีวิวและ UGC",guideSub:"เวิร์กโฟลว์ครบวงจรจากการรวบรวมรีวิวถึง AI",guideStepsTitle:"6 ขั้นตอน",guideStep1Title:"รวบรวมรีวิว",guideStep1Desc:"รวบรวมจากช่องทางขายอัตโนมัติ",guideStep2Title:"วิเคราะห์ AI",guideStep2Desc:"AI จัดประเภทรีวิวอัตโนมัติ",guideStep3Title:"ร่างตอบ AI",guideStep3Desc:"AI สร้างร่างตอบที่เหมาะสม",guideStep4Title:"ยกระดับ CS",guideStep4Desc:"ยกระดับรีวิวเชิงลบอัตโนมัติ",guideStep5Title:"วิเคราะห์เทรนด์",guideStep5Desc:"ติดตามการเปลี่ยนแปลงความรู้สึก",guideStep6Title:"รายงาน",guideStep6Desc:"วิเคราะห์คะแนนและอัตราตอบ",guideTabsTitle:"ฟีเจอร์แท็บ",guideDashName:"แดชบอร์ด",guideDashDesc:"สรุป KPI",guideFeedName:"จัดการรีวิว",guideFeedDesc:"กรองและตอบ AI",guideTrendName:"เทรนด์",guideTrendDesc:"วิเคราะห์ความรู้สึก",guideSettingsName:"การตั้งค่า",guideSettingsDesc:"โทน AI ยกระดับอัตโนมัติ",guideGuideName:"คู่มือ",guideGuideDesc:"คู่มือเวิร์กโฟลว์",guideTipsTitle:"เคล็ดลับ",guideTip1:"ตอบรีวิวเชิงลบภายใน 24 ชม.",guideTip2:"ตรวจสอบร่าง AI ก่อนส่ง",guideTip3:"ตรวจสอบคีย์เวิร์ดเชิงลบ Top 5",guideTip4:"ตั้งค่า Slack Webhook",guideTip5:"เปรียบเทียบคะแนนข้ามช่อง"`,
vi: `tabDashboard:"Bảng điều khiển",tabFeed:"Quản lý đánh giá",tabTrend:"Xu hướng",tabSettings:"Cài đặt",tabGuide:"Hướng dẫn",kpiTotalSub2:"Tổng kênh đã kết nối",kpiAvgRatingSub2:"Trung bình có trọng số",noData:"Không có dữ liệu",close:"Đóng",noTrendData:"Không có dữ liệu xu hướng",noTrendDataSub:"Xu hướng sẽ hiển thị tự động khi có dữ liệu.",trendTitle:"Xu hướng phân tích cảm xúc",sentimentBar:"Tỷ lệ cảm xúc",settingsTitle:"Cài đặt quản lý",aiToneLabel:"Giọng văn AI",toneProfessional:"Chuyên nghiệp",toneFriendly:"Thân thiện",toneFormal:"Trang trọng",autoEscalateLabel:"Tự động nâng cấp",autoEscalateDesc:"Bật nâng cấp 1★ tự động",slackWebhookLabel:"Slack Webhook",slackWebhookSub:"Nhập URL Slack Webhook.",guideTitle:"Hướng dẫn quản lý Đánh giá & UGC",guideSub:"Quy trình hoàn chỉnh từ thu thập đến phân tích AI.",guideStepsTitle:"6 Bước",guideStep1Title:"Thu thập đánh giá",guideStep1Desc:"Tự động thu thập từ kênh bán hàng.",guideStep2Title:"Phân tích AI",guideStep2Desc:"AI tự động phân loại đánh giá.",guideStep3Title:"Bản nháp AI",guideStep3Desc:"AI tạo bản nháp phù hợp.",guideStep4Title:"Nâng cấp CS",guideStep4Desc:"Tự động nâng cấp đánh giá tiêu cực.",guideStep5Title:"Phân tích xu hướng",guideStep5Desc:"Theo dõi thay đổi cảm xúc.",guideStep6Title:"Báo cáo",guideStep6Desc:"Phân tích toàn diện kênh.",guideTabsTitle:"Tính năng Tab",guideDashName:"Bảng điều khiển",guideDashDesc:"Tóm tắt KPI",guideFeedName:"Quản lý đánh giá",guideFeedDesc:"Lọc và trả lời AI",guideTrendName:"Xu hướng",guideTrendDesc:"Phân tích cảm xúc",guideSettingsName:"Cài đặt",guideSettingsDesc:"Giọng AI, tự động nâng cấp",guideGuideName:"Hướng dẫn",guideGuideDesc:"Hướng dẫn quy trình",guideTipsTitle:"Mẹo",guideTip1:"Trả lời trong 24 giờ tăng sự hài lòng.",guideTip2:"Luôn kiểm tra bản nháp AI.",guideTip3:"Kiểm tra từ khóa tiêu cực Top 5.",guideTip4:"Thiết lập Slack Webhook.",guideTip5:"So sánh điểm giữa các kênh."`,
id: `tabDashboard:"Dashboard",tabFeed:"Ulasan",tabTrend:"Tren",tabSettings:"Pengaturan",tabGuide:"Panduan",kpiTotalSub2:"Total saluran terhubung",kpiAvgRatingSub2:"Rata-rata tertimbang",noData:"Tidak ada data",close:"Tutup",noTrendData:"Tidak ada data tren",noTrendDataSub:"Tren akan muncul otomatis saat data terakumulasi.",trendTitle:"Tren Analisis Sentimen",sentimentBar:"Rasio Sentimen",settingsTitle:"Pengaturan",aiToneLabel:"Nada AI",toneProfessional:"Profesional",toneFriendly:"Ramah",toneFormal:"Formal",autoEscalateLabel:"Eskalasi Otomatis",autoEscalateDesc:"Aktifkan eskalasi 1★ otomatis",slackWebhookLabel:"Slack Webhook",slackWebhookSub:"Masukkan URL Slack Webhook.",guideTitle:"Panduan Manajemen Ulasan & UGC",guideSub:"Alur kerja lengkap dari pengumpulan hingga analisis AI.",guideStepsTitle:"6 Langkah",guideStep1Title:"Pengumpulan Ulasan",guideStep1Desc:"Kumpulkan otomatis dari saluran penjualan.",guideStep2Title:"Analisis AI",guideStep2Desc:"AI mengelompokkan ulasan secara otomatis.",guideStep3Title:"Draf AI",guideStep3Desc:"AI menghasilkan draf balasan.",guideStep4Title:"Eskalasi CS",guideStep4Desc:"Eskalasi otomatis ulasan negatif.",guideStep5Title:"Analisis Tren",guideStep5Desc:"Lacak perubahan sentimen.",guideStep6Title:"Laporan",guideStep6Desc:"Analisis komprehensif saluran.",guideTabsTitle:"Fitur Tab",guideDashName:"Dashboard",guideDashDesc:"Ringkasan KPI",guideFeedName:"Ulasan",guideFeedDesc:"Filter dan balasan AI",guideTrendName:"Tren",guideTrendDesc:"Analisis sentimen",guideSettingsName:"Pengaturan",guideSettingsDesc:"Nada AI, eskalasi otomatis",guideGuideName:"Panduan",guideGuideDesc:"Panduan alur kerja",guideTipsTitle:"Tips",guideTip1:"Balas dalam 24 jam meningkatkan kepuasan.",guideTip2:"Selalu tinjau draf AI.",guideTip3:"Periksa kata kunci negatif Top 5.",guideTip4:"Atur Slack Webhook.",guideTip5:"Bandingkan peringkat antar saluran."`
  };
  return ALL[lang] || ALL.en;
}
