const fs = require('fs');
const path = require('path');
const DIR = path.join(__dirname, 'frontend/src/i18n/locales');

const NEW_KEYS = {
  ko: {
    ihubLinked: '채널 연동됨',
    ihubAutoDetect: '연동허브에서 자동 감지된 SMS 채널:',
    noHistory: '발송 이력이 없습니다.',
    guideStep1Title: 'API 인증 설정',
    guideStep1Desc: '연동허브에서 SMS 제공자(NHN Cloud, Aligo, CoolSMS 등)의 API 키를 등록하세요. 등록된 API 키는 자동으로 SMS 마케팅 모듈과 동기화됩니다. 인증 설정 탭에서 발신번호를 등록하고 연결 테스트를 수행하세요.',
    guideStep2Title: '메시지 작성',
    guideStep2Desc: '작성 탭에서 수신자 번호를 입력하고 메시지를 작성하세요. 한글 기준 SMS는 90자, LMS는 2,000자까지 가능합니다. 메시지 길이에 따라 자동으로 SMS/LMS가 구분됩니다.',
    guideStep3Title: '템플릿 관리',
    guideStep3Desc: '자주 사용하는 메시지를 템플릿으로 저장하세요. 카테고리(프로모션, 알림, 인증, 트랜잭션)별로 분류하고 #{이름}, #{주문번호} 등의 변수를 삽입할 수 있습니다.',
    guideStep4Title: '캠페인 생성',
    guideStep4Desc: 'CRM 세그먼트를 선택하여 타겟 고객에게 대량 메시지를 보내세요. 예약 발송, 즉시 발송을 선택하고 캠페인별 성과(발송수, 성공률)를 실시간 추적할 수 있습니다.',
    guideStep5Title: '대량 발송',
    guideStep5Desc: '일괄 발송 탭에서 최대 500명의 수신자에게 동시 발송이 가능합니다. 쉼표 또는 줄바꿈으로 수신번호를 구분하세요. 발송 결과는 이력 탭에서 실시간 확인됩니다.',
    guideStep6Title: '통계 & 모니터링',
    guideStep6Desc: '통계 탭에서 월별 발송량, 성공률, 잔여 포인트를 확인하세요. 모든 데이터는 30초마다 실시간 동기화되며, 다른 브라우저 탭과도 자동 동기화됩니다.',
    guideComposeName: '메시지 작성',
    guideComposeDesc: 'SMS/LMS 단건 발송',
    guideBroadcastName: '일괄 발송',
    guideBroadcastDesc: '최대 500명 대량 발송',
    guideTemplatesName: '템플릿 관리',
    guideTemplatesDesc: '자주 사용 메시지 저장',
    guideCampaignsName: '캠페인',
    guideCampaignsDesc: 'CRM 세그먼트 기반 발송',
    guideHistoryName: '발송 이력',
    guideHistoryDesc: '전체 발송 로그 조회',
    guideStatsName: '통계',
    guideStatsDesc: '발송 성과 분석',
    guideAuthName: '인증 설정',
    guideAuthDesc: 'API 키 및 발신번호 관리',
    guideTip1: 'API 키는 연동허브에서 등록하면 SMS 마케팅 모듈에 자동 연동됩니다.',
    guideTip2: '발신번호는 사전 등록이 필요하며, 미등록 번호로는 발송이 불가합니다.',
    guideTip3: '캠페인을 예약 발송으로 설정하면 지정 시간에 자동 발송됩니다.',
    guideTip4: '변수 치환을 활용하면 개인화된 메시지를 대량 발송할 수 있습니다.',
    guideTip5: '보안 모니터링이 활성화되어 해킹 시도가 자동 감지 및 차단됩니다.',
  },
  en: {
    ihubLinked: 'Channels Linked',
    ihubAutoDetect: 'Auto-detected SMS channels from Integration Hub:',
    noHistory: 'No message history found.',
    guideStep1Title: 'API Authentication Setup',
    guideStep1Desc: 'Register your SMS provider API keys (NHN Cloud, Aligo, CoolSMS, etc.) from the Integration Hub. Registered API keys are automatically synced with the SMS Marketing module. Go to Auth Settings to register your sender number and run a connection test.',
    guideStep2Title: 'Compose Messages',
    guideStep2Desc: 'Enter the recipient number and compose your message in the Compose tab. SMS supports up to 90 characters (Korean), while LMS supports up to 2,000 characters. The message type is automatically selected based on length.',
    guideStep3Title: 'Template Management',
    guideStep3Desc: 'Save frequently used messages as templates. Organize by category (Promotion, Notification, Verification, Transaction) and insert variables like #{name}, #{orderNumber} for personalization.',
    guideStep4Title: 'Create Campaigns',
    guideStep4Desc: 'Select CRM segments to target specific customers with bulk messaging. Choose between scheduled or immediate delivery and track campaign performance (sent count, success rate) in real-time.',
    guideStep5Title: 'Bulk Sending',
    guideStep5Desc: 'Send messages to up to 500 recipients simultaneously from the Bulk Send tab. Separate phone numbers with commas or line breaks. Results are tracked in real-time in the History tab.',
    guideStep6Title: 'Statistics & Monitoring',
    guideStep6Desc: 'View monthly send volume, success rates, and remaining balance in the Stats tab. All data is synced in real-time every 30 seconds and auto-synchronized across browser tabs.',
    guideComposeName: 'Compose',
    guideComposeDesc: 'Send individual SMS/LMS',
    guideBroadcastName: 'Bulk Send',
    guideBroadcastDesc: 'Send to up to 500 recipients',
    guideTemplatesName: 'Templates',
    guideTemplatesDesc: 'Save frequently used messages',
    guideCampaignsName: 'Campaigns',
    guideCampaignsDesc: 'CRM segment-based sending',
    guideHistoryName: 'History',
    guideHistoryDesc: 'View all send logs',
    guideStatsName: 'Statistics',
    guideStatsDesc: 'Analyze send performance',
    guideAuthName: 'Auth Settings',
    guideAuthDesc: 'Manage API keys & sender numbers',
    guideTip1: 'API keys registered in the Integration Hub are automatically linked to the SMS Marketing module.',
    guideTip2: 'Sender numbers must be pre-registered; unregistered numbers cannot send messages.',
    guideTip3: 'Campaigns set to scheduled delivery will be sent automatically at the designated time.',
    guideTip4: 'Use variable substitution to send personalized messages in bulk.',
    guideTip5: 'Security monitoring is active — hacking attempts are automatically detected and blocked.',
  },
  ja: {
    ihubLinked: 'チャネル連携済み',
    ihubAutoDetect: '統合ハブから自動検出されたSMSチャネル：',
    noHistory: '送信履歴がありません。',
    guideStep1Title: 'API認証設定',
    guideStep1Desc: '統合ハブからSMSプロバイダー（NHN Cloud、Aligo、CoolSMSなど）のAPIキーを登録してください。登録されたAPIキーはSMSマーケティングモジュールと自動同期されます。認証設定タブで発信番号を登録し、接続テストを実行してください。',
    guideStep2Title: 'メッセージ作成',
    guideStep2Desc: '作成タブで受信者番号を入力し、メッセージを作成してください。SMSは90文字、LMSは2,000文字まで対応しています。メッセージ長により自動的にSMS/LMSが判別されます。',
    guideStep3Title: 'テンプレート管理',
    guideStep3Desc: '頻繁に使用するメッセージをテンプレートとして保存してください。カテゴリ（プロモーション、通知、認証、トランザクション）別に分類し、#{名前}、#{注文番号}などの変数を挿入できます。',
    guideStep4Title: 'キャンペーン作成',
    guideStep4Desc: 'CRMセグメントを選択して特定顧客に一括メッセージを送信してください。予約送信と即時送信を選択し、キャンペーンごとの成果（送信数、成功率）をリアルタイムで追跡できます。',
    guideStep5Title: '一括送信',
    guideStep5Desc: '一括送信タブから最大500人の受信者に同時送信が可能です。電話番号はカンマまたは改行で区切ってください。結果は履歴タブでリアルタイムに確認できます。',
    guideStep6Title: '統計＆モニタリング',
    guideStep6Desc: '統計タブで月別送信量、成功率、残高ポイントを確認してください。全データは30秒ごとにリアルタイム同期され、他のブラウザタブとも自動同期されます。',
    guideComposeName: 'メッセージ作成',
    guideComposeDesc: 'SMS/LMS個別送信',
    guideBroadcastName: '一括送信',
    guideBroadcastDesc: '最大500人に大量送信',
    guideTemplatesName: 'テンプレート管理',
    guideTemplatesDesc: '頻繁使用メッセージの保存',
    guideCampaignsName: 'キャンペーン',
    guideCampaignsDesc: 'CRMセグメント基の送信',
    guideHistoryName: '送信履歴',
    guideHistoryDesc: '全送信ログ照会',
    guideStatsName: '統計',
    guideStatsDesc: '送信成果分析',
    guideAuthName: '認証設定',
    guideAuthDesc: 'APIキー＆発信番号管理',
    guideTip1: '統合ハブで登録したAPIキーはSMSモジュールに自動連携されます。',
    guideTip2: '発信番号は事前登録が必要です。未登録番号では送信できません。',
    guideTip3: 'キャンペーンを予約送信に設定すると、指定時間に自動送信されます。',
    guideTip4: '変数置換を活用すると、パーソナライズされたメッセージを一括送信できます。',
    guideTip5: 'セキュリティモニタリングが有効で、ハッキング試行は自動的に検出・ブロックされます。',
  },
  zh: {
    ihubLinked: '频道已连接',
    ihubAutoDetect: '从集成中心自动检测到的短信频道：',
    noHistory: '暂无发送记录。',
    guideStep1Title: 'API认证设置',
    guideStep1Desc: '从集成中心注册短信提供商（NHN Cloud、Aligo、CoolSMS等）的API密钥。注册的API密钥将自动与短信营销模块同步。在认证设置标签中注册发送号码并执行连接测试。',
    guideStep2Title: '编写消息',
    guideStep2Desc: '在编写标签中输入收件人号码并编写消息。短信支持最多90个字符（韩文），长短信支持最多2,000个字符。消息类型根据长度自动选择。',
    guideStep3Title: '模板管理',
    guideStep3Desc: '将常用消息保存为模板。按类别（促销、通知、验证、交易）分类，并插入#{姓名}、#{订单号}等变量进行个性化。',
    guideStep4Title: '创建营销活动',
    guideStep4Desc: '选择CRM细分群体，向特定客户发送批量消息。选择定时发送或立即发送，实时跟踪活动绩效（发送数、成功率）。',
    guideStep5Title: '批量发送',
    guideStep5Desc: '在批量发送标签中同时向最多500个收件人发送消息。用逗号或换行分隔电话号码。结果在历史标签中实时显示。',
    guideStep6Title: '统计与监控',
    guideStep6Desc: '在统计标签中查看月度发送量、成功率和剩余余额。所有数据每30秒实时同步，并在浏览器标签间自动同步。',
    guideComposeName: '编写消息', guideComposeDesc: '发送单条短信/长短信',
    guideBroadcastName: '批量发送', guideBroadcastDesc: '向最多500人发送',
    guideTemplatesName: '模板管理', guideTemplatesDesc: '保存常用消息',
    guideCampaignsName: '营销活动', guideCampaignsDesc: '基于CRM细分发送',
    guideHistoryName: '发送历史', guideHistoryDesc: '查看所有发送日志',
    guideStatsName: '统计', guideStatsDesc: '分析发送绩效',
    guideAuthName: '认证设置', guideAuthDesc: '管理API密钥和发送号码',
    guideTip1: '在集成中心注册的API密钥会自动连入短信营销模块。',
    guideTip2: '发送号码需预先注册，未注册号码无法发送。',
    guideTip3: '设为定时发送的活动将在指定时间自动发送。',
    guideTip4: '利用变量替换可批量发送个性化消息。',
    guideTip5: '安全监控已启用，黑客攻击尝试将被自动检测和阻止。',
  },
  'zh-TW': {
    ihubLinked: '頻道已連接',
    ihubAutoDetect: '從整合中心自動偵測到的簡訊頻道：',
    noHistory: '暫無發送記錄。',
    guideStep1Title: 'API認證設定',
    guideStep1Desc: '從整合中心註冊簡訊供應商（NHN Cloud、Aligo、CoolSMS等）的API金鑰。註冊的API金鑰將自動與簡訊行銷模組同步。在認證設定標籤中註冊發送號碼並執行連線測試。',
    guideStep2Title: '編寫訊息',
    guideStep2Desc: '在編寫標籤中輸入收件人號碼並編寫訊息。簡訊支援最多90個字元（韓文），長簡訊支援最多2,000個字元。訊息類型根據長度自動選擇。',
    guideStep3Title: '範本管理',
    guideStep3Desc: '將常用訊息儲存為範本。按類別（促銷、通知、驗證、交易）分類，並插入#{姓名}、#{訂單號}等變數進行個人化。',
    guideStep4Title: '建立行銷活動',
    guideStep4Desc: '選擇CRM細分群體，向特定客戶發送大量訊息。選擇排程發送或立即發送，即時追蹤活動績效（發送數、成功率）。',
    guideStep5Title: '批次發送',
    guideStep5Desc: '在批次發送標籤中同時向最多500個收件人發送訊息。用逗號或換行分隔電話號碼。結果在歷史記錄標籤中即時顯示。',
    guideStep6Title: '統計與監控',
    guideStep6Desc: '在統計標籤中查看月度發送量、成功率和剩餘餘額。所有資料每30秒即時同步，並在瀏覽器標籤間自動同步。',
    guideComposeName: '編寫訊息', guideComposeDesc: '發送單條簡訊/長簡訊',
    guideBroadcastName: '批次發送', guideBroadcastDesc: '向最多500人發送',
    guideTemplatesName: '範本管理', guideTemplatesDesc: '儲存常用訊息',
    guideCampaignsName: '行銷活動', guideCampaignsDesc: '基於CRM細分發送',
    guideHistoryName: '發送歷史', guideHistoryDesc: '查看所有發送日誌',
    guideStatsName: '統計', guideStatsDesc: '分析發送績效',
    guideAuthName: '認證設定', guideAuthDesc: '管理API金鑰和發送號碼',
    guideTip1: '在整合中心註冊的API金鑰會自動連入簡訊行銷模組。',
    guideTip2: '發送號碼需預先註冊，未註冊號碼無法發送。',
    guideTip3: '設為排程發送的活動將在指定時間自動發送。',
    guideTip4: '利用變數替換可批次發送個人化訊息。',
    guideTip5: '安全監控已啟用，駭客攻擊嘗試將被自動偵測和阻止。',
  },
  de: {
    ihubLinked: 'Kanäle verbunden',
    ihubAutoDetect: 'Automatisch erkannte SMS-Kanäle aus dem Integration Hub:',
    noHistory: 'Kein Sendeverlauf gefunden.',
    guideStep1Title: 'API-Authentifizierung',
    guideStep1Desc: 'Registrieren Sie Ihre SMS-Anbieter-API-Schlüssel (NHN Cloud, Aligo, CoolSMS usw.) im Integration Hub. Registrierte API-Schlüssel werden automatisch mit dem SMS-Marketing-Modul synchronisiert. Registrieren Sie Ihre Absendernummer und führen Sie einen Verbindungstest durch.',
    guideStep2Title: 'Nachricht verfassen',
    guideStep2Desc: 'Geben Sie die Empfängernummer ein und verfassen Sie Ihre Nachricht im Tab Verfassen. SMS unterstützt bis zu 90 Zeichen (Koreanisch), LMS bis zu 2.000 Zeichen. Der Nachrichtentyp wird automatisch basierend auf der Länge gewählt.',
    guideStep3Title: 'Vorlagenverwaltung',
    guideStep3Desc: 'Speichern Sie häufig verwendete Nachrichten als Vorlagen. Organisieren Sie nach Kategorie (Promotion, Benachrichtigung, Verifizierung, Transaktion) und fügen Sie Variablen wie #{Name}, #{Bestellnummer} ein.',
    guideStep4Title: 'Kampagne erstellen',
    guideStep4Desc: 'Wählen Sie CRM-Segmente, um bestimmte Kunden mit Massennachrichten anzusprechen. Wählen Sie zwischen geplanter oder sofortiger Zustellung und verfolgen Sie die Kampagnenleistung in Echtzeit.',
    guideStep5Title: 'Massenversand',
    guideStep5Desc: 'Senden Sie Nachrichten an bis zu 500 Empfänger gleichzeitig über den Massenversand-Tab. Trennen Sie Telefonnummern mit Kommas oder Zeilenumbrüchen.',
    guideStep6Title: 'Statistiken & Monitoring',
    guideStep6Desc: 'Sehen Sie monatliche Sendevolumen, Erfolgsraten und Restguthaben im Statistik-Tab. Alle Daten werden alle 30 Sekunden in Echtzeit synchronisiert.',
    guideComposeName: 'Verfassen', guideComposeDesc: 'Einzelne SMS/LMS senden',
    guideBroadcastName: 'Massenversand', guideBroadcastDesc: 'An bis zu 500 Empfänger',
    guideTemplatesName: 'Vorlagen', guideTemplatesDesc: 'Häufige Nachrichten speichern',
    guideCampaignsName: 'Kampagnen', guideCampaignsDesc: 'CRM-Segment-basierter Versand',
    guideHistoryName: 'Verlauf', guideHistoryDesc: 'Alle Sendeprotokolle anzeigen',
    guideStatsName: 'Statistiken', guideStatsDesc: 'Sendeleistung analysieren',
    guideAuthName: 'Auth-Einstellungen', guideAuthDesc: 'API-Schlüssel & Absendernummern',
    guideTip1: 'Im Integration Hub registrierte API-Schlüssel werden automatisch verknüpft.',
    guideTip2: 'Absendernummern müssen vorab registriert werden.',
    guideTip3: 'Geplante Kampagnen werden automatisch zur festgelegten Zeit gesendet.',
    guideTip4: 'Nutzen Sie Variablenersetzung für personalisierte Massennachrichten.',
    guideTip5: 'Sicherheitsmonitoring ist aktiv — Hacking-Versuche werden automatisch erkannt.',
  },
  th: {
    ihubLinked: 'เชื่อมต่อแล้ว',
    ihubAutoDetect: 'ช่อง SMS ที่ตรวจพบอัตโนมัติจาก Integration Hub:',
    noHistory: 'ไม่พบประวัติการส่ง',
    guideStep1Title: 'ตั้งค่าการยืนยัน API',
    guideStep1Desc: 'ลงทะเบียน API Key ของผู้ให้บริการ SMS (NHN Cloud, Aligo, CoolSMS เป็นต้น) จาก Integration Hub API Key ที่ลงทะเบียนจะซิงค์กับโมดูล SMS Marketing โดยอัตโนมัติ ลงทะเบียนหมายเลขผู้ส่งและทดสอบการเชื่อมต่อในแท็บตั้งค่าการยืนยัน',
    guideStep2Title: 'เขียนข้อความ',
    guideStep2Desc: 'ป้อนหมายเลขผู้รับและเขียนข้อความในแท็บเขียน SMS รองรับสูงสุด90ตัวอักษร(เกาหลี) LMS สูงสุด2,000ตัวอักษร ระบบจะเลือกประเภทอัตโนมัติตามความยาว',
    guideStep3Title: 'จัดการเทมเพลต',
    guideStep3Desc: 'บันทึกข้อความที่ใช้บ่อยเป็นเทมเพลต จัดหมวดหมู่ (โปรโมชั่น, แจ้งเตือน, ยืนยัน, ธุรกรรม) และแทรกตัวแปรเช่น #{ชื่อ}, #{หมายเลขคำสั่ง}',
    guideStep4Title: 'สร้างแคมเปญ',
    guideStep4Desc: 'เลือกเซ็กเมนต์ CRM เพื่อส่งข้อความแบบกลุ่มไปยังลูกค้าเป้าหมาย เลือกระหว่างส่งตามกำหนดหรือส่งทันที ติดตามประสิทธิภาพแบบเรียลไทม์',
    guideStep5Title: 'ส่งจำนวนมาก',
    guideStep5Desc: 'ส่งข้อความถึงผู้รับสูงสุด500คนพร้อมกันจากแท็บส่งจำนวนมาก แยกหมายเลขด้วยเครื่องหมายจุลภาคหรือขึ้นบรรทัดใหม่',
    guideStep6Title: 'สถิติและการตรวจสอบ',
    guideStep6Desc: 'ดูปริมาณการส่งรายเดือน อัตราความสำเร็จ และยอมเงินคงเหลือ ข้อมูลทั้งหมดซิงค์แบบเรียลไทม์ทุก30วินาทีและซิงค์ข้ามแท็บอัตโนมัติ',
    guideComposeName: 'เขียนข้อความ', guideComposeDesc: 'ส่ง SMS/LMS เดี่ยว',
    guideBroadcastName: 'ส่งจำนวนมาก', guideBroadcastDesc: 'ส่งถึง 500 คน',
    guideTemplatesName: 'เทมเพลต', guideTemplatesDesc: 'บันทึกข้อความที่ใช้บ่อย',
    guideCampaignsName: 'แคมเปญ', guideCampaignsDesc: 'ส่งตาม CRM เซ็กเมนต์',
    guideHistoryName: 'ประวัติ', guideHistoryDesc: 'ดูบันทึกการส่ง',
    guideStatsName: 'สถิติ', guideStatsDesc: 'วิเคราะห์ประสิทธิภาพ',
    guideAuthName: 'ตั้งค่าการยืนยัน', guideAuthDesc: 'จัดการ API Key',
    guideTip1: 'API Key จาก Integration Hub จะเชื่อมกับ SMS โดยอัตโนมัติ',
    guideTip2: 'หมายเลขผู้ส่งต้องลงทะเบียนล่วงหน้า',
    guideTip3: 'แคมเปญที่ตั้งเวลาไว้จะส่งอัตโนมัติตามเวลาที่กำหนด',
    guideTip4: 'ใช้การแทนที่ตัวแปรเพื่อส่งข้อความส่วนตัวจำนวนมาก',
    guideTip5: 'การตรวจสอบความปลอดภัยทำงานอยู่ ป้องกันการแฮก',
  },
  vi: {
    ihubLinked: 'Kênh đã kết nối',
    ihubAutoDetect: 'Các kênh SMS tự động phát hiện từ Integration Hub:',
    noHistory: 'Không tìm thấy lịch sử gửi.',
    guideStep1Title: 'Cài đặt xác thực API',
    guideStep1Desc: 'Đăng ký API key của nhà cung cấp SMS (NHN Cloud, Aligo, CoolSMS v.v.) từ Integration Hub. API key đã đăng ký sẽ tự động đồng bộ với module SMS Marketing. Đăng ký số gửi và chạy kiểm tra kết nối trong tab Cài đặt xác thực.',
    guideStep2Title: 'Soạn tin nhắn',
    guideStep2Desc: 'Nhập số người nhận và soạn tin nhắn trong tab Soạn. SMS hỗ trợ tối đa 90 ký tự (tiếng Hàn), LMS hỗ trợ tối đa 2.000 ký tự. Loại tin nhắn được tự động chọn theo độ dài.',
    guideStep3Title: 'Quản lý mẫu',
    guideStep3Desc: 'Lưu tin nhắn thường dùng làm mẫu. Phân loại theo danh mục (Khuyến mãi, Thông báo, Xác minh, Giao dịch) và chèn biến như #{tên}, #{mãĐơnHàng}.',
    guideStep4Title: 'Tạo chiến dịch',
    guideStep4Desc: 'Chọn phân khúc CRM để gửi tin nhắn hàng loạt cho khách hàng mục tiêu. Chọn gửi theo lịch hoặc gửi ngay và theo dõi hiệu suất chiến dịch theo thời gian thực.',
    guideStep5Title: 'Gửi hàng loạt',
    guideStep5Desc: 'Gửi tin nhắn đến tối đa 500 người nhận cùng lúc từ tab Gửi hàng loạt. Phân cách số điện thoại bằng dấu phẩy hoặc xuống dòng.',
    guideStep6Title: 'Thống kê & Giám sát',
    guideStep6Desc: 'Xem lượng gửi hàng tháng, tỷ lệ thành công và số dư còn lại trong tab Thống kê. Tất cả dữ liệu đồng bộ theo thời gian thực mỗi 30 giây.',
    guideComposeName: 'Soạn tin', guideComposeDesc: 'Gửi SMS/LMS đơn lẻ',
    guideBroadcastName: 'Gửi hàng loạt', guideBroadcastDesc: 'Gửi đến 500 người',
    guideTemplatesName: 'Mẫu tin', guideTemplatesDesc: 'Lưu tin nhắn thường dùng',
    guideCampaignsName: 'Chiến dịch', guideCampaignsDesc: 'Gửi theo phân khúc CRM',
    guideHistoryName: 'Lịch sử', guideHistoryDesc: 'Xem nhật ký gửi',
    guideStatsName: 'Thống kê', guideStatsDesc: 'Phân tích hiệu suất',
    guideAuthName: 'Cài đặt xác thực', guideAuthDesc: 'Quản lý API key',
    guideTip1: 'API key từ Integration Hub tự động liên kết với module SMS.',
    guideTip2: 'Số gửi phải được đăng ký trước, số chưa đăng ký không thể gửi.',
    guideTip3: 'Chiến dịch hẹn giờ sẽ tự động gửi vào thời gian đã chỉ định.',
    guideTip4: 'Sử dụng thay thế biến để gửi tin nhắn cá nhân hóa hàng loạt.',
    guideTip5: 'Giám sát bảo mật đang hoạt động — phát hiện và chặn tấn công tự động.',
  },
  id: {
    ihubLinked: 'Saluran Terhubung',
    ihubAutoDetect: 'Saluran SMS yang terdeteksi otomatis dari Integration Hub:',
    noHistory: 'Tidak ada riwayat pengiriman.',
    guideStep1Title: 'Pengaturan Autentikasi API',
    guideStep1Desc: 'Daftarkan API key penyedia SMS (NHN Cloud, Aligo, CoolSMS dll.) dari Integration Hub. API key terdaftar akan otomatis disinkronkan dengan modul SMS Marketing. Daftarkan nomor pengirim dan jalankan tes koneksi di tab Pengaturan Autentikasi.',
    guideStep2Title: 'Tulis Pesan',
    guideStep2Desc: 'Masukkan nomor penerima dan tulis pesan di tab Tulis. SMS mendukung hingga 90 karakter (Korea), LMS hingga 2.000 karakter. Jenis pesan dipilih otomatis berdasarkan panjang.',
    guideStep3Title: 'Manajemen Template',
    guideStep3Desc: 'Simpan pesan yang sering digunakan sebagai template. Atur berdasarkan kategori (Promosi, Notifikasi, Verifikasi, Transaksi) dan sisipkan variabel seperti #{nama}, #{nomorPesanan}.',
    guideStep4Title: 'Buat Kampanye',
    guideStep4Desc: 'Pilih segmen CRM untuk menargetkan pelanggan tertentu dengan pesan massal. Pilih antara pengiriman terjadwal atau langsung dan lacak kinerja kampanye secara real-time.',
    guideStep5Title: 'Pengiriman Massal',
    guideStep5Desc: 'Kirim pesan ke hingga 500 penerima secara bersamaan dari tab Pengiriman Massal. Pisahkan nomor telepon dengan koma atau baris baru.',
    guideStep6Title: 'Statistik & Pemantauan',
    guideStep6Desc: 'Lihat volume pengiriman bulanan, tingkat keberhasilan, dan saldo tersisa di tab Statistik. Semua data disinkronkan secara real-time setiap 30 detik.',
    guideComposeName: 'Tulis', guideComposeDesc: 'Kirim SMS/LMS individu',
    guideBroadcastName: 'Kirim Massal', guideBroadcastDesc: 'Kirim ke 500 penerima',
    guideTemplatesName: 'Template', guideTemplatesDesc: 'Simpan pesan yang sering',
    guideCampaignsName: 'Kampanye', guideCampaignsDesc: 'Kirim berbasis segmen CRM',
    guideHistoryName: 'Riwayat', guideHistoryDesc: 'Lihat semua log pengiriman',
    guideStatsName: 'Statistik', guideStatsDesc: 'Analisis kinerja pengiriman',
    guideAuthName: 'Pengaturan Auth', guideAuthDesc: 'Kelola API key & nomor pengirim',
    guideTip1: 'API key dari Integration Hub otomatis terhubung ke modul SMS.',
    guideTip2: 'Nomor pengirim harus didaftarkan terlebih dahulu.',
    guideTip3: 'Kampanye terjadwal akan terkirim otomatis pada waktu yang ditentukan.',
    guideTip4: 'Gunakan substitusi variabel untuk pesan personal massal.',
    guideTip5: 'Pemantauan keamanan aktif — percobaan peretasan terdeteksi otomatis.',
  },
};

const FILES = ['ko','en','ja','zh','zh-TW','de','th','vi','id'];

FILES.forEach(lang => {
  const file = path.join(DIR, `${lang}.js`);
  let code = fs.readFileSync(file, 'utf8');
  const keys = NEW_KEYS[lang] || NEW_KEYS.en;
  let added = 0;
  for (const [k, v] of Object.entries(keys)) {
    const fullKey = `sms.${k}`;
    // Check if key already exists
    if (code.includes(`'${k}'`) && code.includes('sms:') || code.match(new RegExp(`['"]${k}['"]\\s*:`))) {
      // Check more precisely if it's inside the sms block
      const smsBlockMatch = code.match(/sms\s*:\s*\{[^}]*\}/s);
      if (smsBlockMatch && smsBlockMatch[0].includes(`'${k}'`)) continue;
    }
    // Find the sms block and add at end
    const smsEndMatch = code.match(/(sms\s*:\s*\{[\s\S]*?)(\n\s*\},?\s*\n)/);
    if (smsEndMatch) {
      const safeVal = v.replace(/'/g, "\\'");
      const insertion = `    '${k}': '${safeVal}',\n`;
      if (!code.includes(`'${k}':`)) {
        code = code.replace(smsEndMatch[0], smsEndMatch[1] + '\n' + insertion + smsEndMatch[2]);
        added++;
      }
    }
  }
  fs.writeFileSync(file, code, 'utf8');
  console.log(`✅ ${lang}: ${added} keys added`);
});

console.log('\n🎉 SMS i18n v2 patch complete!');
