from __future__ import annotations
from dataclasses import dataclass
from typing import Dict, Any, List, Optional

@dataclass
class ExecutionStep:
    step_type: str  # e.g., "UPDATE_BUDGET"
    channel: str
    target_level: str  # campaign|adset|group
    object_id: str
    new_budget: float
    notes: str = ""

@dataclass
class ExecutionPlan:
    channel: str
    account_id: str
    steps: List[ExecutionStep]
    safety: Dict[str, Any]

def detect_structure(channel: str, account_context: Dict[str, Any]) -> Dict[str, Any]:
    """Detects likely budget control level by channel/account hints.
    This is a deterministic, go-to-market safe detector (no ML).
    - Meta: if 'cbo' true -> campaign; else adset
    - Others: default campaign
    """
    ch = channel.lower()
    if ch == "meta":
        cbo = bool(account_context.get("cbo", False))
        return {"budget_level": "campaign" if cbo else "adset", "cbo": cbo}
    if ch in ("tiktok", "google", "naver", "kakao"):
        return {"budget_level": "campaign"}
    return {"budget_level": "campaign"}

def build_safe_plan(channel: str, account_id: str, payload: Dict[str, Any], policy: Dict[str, Any]) -> ExecutionPlan:
    """Build an execution plan with guardrails & idempotency metadata."""
    structure = detect_structure(channel, payload.get("account_context", {}))
    level = payload.get("target_level") or structure["budget_level"]

    # Map object id based on level
    obj_id = payload.get("object_id") or payload.get("campaign_id") or payload.get("adset_id") or ""
    new_budget = float(payload.get("new_budget", 0.0))

    # Safety envelope
    safety = {
        "requires_approval": True,
        "max_change_pct": float(policy.get("max_change_pct", 30)),
        "idempotency_key": payload.get("idempotency_key") or f"{channel}:{account_id}:{obj_id}:{int(new_budget)}",
        "dry_run_recommended": True,
        "detected_budget_level": structure["budget_level"],
    }

    steps = [
        ExecutionStep(
            step_type="UPDATE_DAILY_BUDGET",
            channel=channel.lower(),
            target_level=level,
            object_id=str(obj_id),
            new_budget=new_budget,
            notes="Generated by execution planner; validate channel-specific constraints before enabling AUTO_EXECUTE.",
        )
    ]
    return ExecutionPlan(channel=channel.lower(), account_id=str(account_id), steps=steps, safety=safety)
