const fs=require('fs');
const DIR='src/i18n/locales';

const GUIDE_KEYS={
ko:{guideStep1Title:'캠페인 생성',guideStep1Desc:'AI 오토 마케팅 또는 통합 AI 캠페인 빌더에서 캠페인을 생성합니다. 예산, 타겟 ROAS, 기간을 설정하고 광고 채널을 선택합니다. 생성된 캠페인은 예약됨 상태로 등록되며, 승인 후 활성화됩니다.',guideStep2Title:'캠페인 승인',guideStep2Desc:'예약된 캠페인 카드의 활성화 승인 버튼을 클릭합니다. 승인 모달에서 캠페인 정보를 확인하고 메모를 입력한 후 승인합니다.',guideStep3Title:'실시간 모니터링',guideStep3Desc:'모니터링 탭에서 활성 캠페인의 실시간 KPI를 확인합니다. 소진율, 일일 예산, 전환 수, CPA를 추적합니다.',guideStep4Title:'예산 알림 관리',guideStep4Desc:'예산 소진율 70% 이상 시 자동 알림이 발생합니다. 95% 이상은 자동 일시정지, 85-95%는 경고, 70-85%는 모니터링입니다.',guideStep5Title:'ROI 분석',guideStep5Desc:'ROI 분석 탭에서 캠페인별 ROAS, ROI, 소진 금액을 종합 비교합니다. 상위 3개 캠페인이 하이라이트됩니다.',guideStep6Title:'AI 카피 생성',guideStep6Desc:'AI 카피라이터 탭에서 광고 카피를 자동 생성합니다. 채널과 톤을 선택하고 프롬프트를 입력하면 AI가 헤드라인, 본문, CTA를 생성합니다.',guideTabOverviewName:'캠페인 현황',guideTabOverviewDesc:'전체 캠페인 목록을 카드 형태로 표시합니다. 상태별 필터링, 예산 소진율, ROAS 실적을 한눈에 확인할 수 있습니다.',guideTabAbName:'A/B 테스트',guideTabAbDesc:'이메일 마케팅과 어트리뷰션에서 진행된 A/B 테스트 결과를 통합 조회합니다.',guideTabDetailName:'상세 분석',guideTabDetailDesc:'선택한 캠페인의 KPI 목표 vs 실적, 채널별 예산 배분, 인플루언서 목록을 확인합니다.',guideTabGanttName:'일정 관리',guideTabGanttDesc:'간트 차트로 캠페인 일정을 시각화합니다.',guideTabCrmName:'CRM 채널',guideTabCrmDesc:'이메일과 카카오톡 캠페인 현황을 통합 조회합니다.',guideTabRoiName:'ROI 분석',guideTabRoiDesc:'전체 캠페인 ROI를 종합 분석합니다.',guideTabMonitorName:'실시간 모니터링',guideTabMonitorDesc:'활성 캠페인의 실시간 KPI를 모니터링합니다.',guideTabBudgetName:'예산 알림',guideTabBudgetDesc:'예산 소진율 기준 자동 알림 시스템입니다.',guideTabCopyName:'AI 카피',guideTabCopyDesc:'AI 광고 카피 자동 생성기입니다.',tabCreative:'AI 광고 소재',creativeTitle:'AI 광고 크리에이티브 생성기',creativeSub:'자연어 프롬프트를 입력하면 AI가 내용을 분석하여 캠페인에 맞는 광고 디자인을 자동 생성합니다.',guideTabCreativeName:'AI 광고 소재',guideTabCreativeDesc:'자연어 프롬프트 기반 AI 광고 이미지 생성기입니다.',channelFee:'수수료',channelFeeRate:'수수료율',noFeeData:'수수료 정보 없음'},
en:{guideStep1Title:'Create Campaign',guideStep1Desc:'Create campaigns from AI Auto Marketing or Unified AI Campaign Builder. Set budget, target ROAS, duration, and select ad channels. Campaigns are registered as Scheduled and activated after approval.',guideStep2Title:'Approve Campaign',guideStep2Desc:'Click the Activate Approve button on the scheduled campaign card. Review details in the approval modal and approve.',guideStep3Title:'Real-time Monitoring',guideStep3Desc:'Monitor real-time KPIs of active campaigns. Track burn rate, daily budget, conversions, and CPA.',guideStep4Title:'Budget Alert Management',guideStep4Desc:'Automatic alerts trigger when budget burn exceeds 70%. Above 95% triggers auto-pause, 85-95% triggers warning.',guideStep5Title:'ROI Analysis',guideStep5Desc:'Compare ROAS, ROI, and spend across campaigns in the ROI tab. Top 3 are highlighted.',guideStep6Title:'AI Copy Generation',guideStep6Desc:'Auto-generate ad copy in the AI Copywriter tab. Select channel and tone, enter a prompt.',guideTabOverviewName:'Campaign Overview',guideTabOverviewDesc:'Displays all campaigns as cards with status filtering and budget burn rate.',guideTabAbName:'A/B Testing',guideTabAbDesc:'View integrated A/B test results from Email Marketing and Attribution.',guideTabDetailName:'Detail Analysis',guideTabDetailDesc:'View KPI targets vs actuals, channel budget allocation, and influencer lists.',guideTabGanttName:'Schedule',guideTabGanttDesc:'Visualize campaign schedules with Gantt charts.',guideTabCrmName:'CRM Channels',guideTabCrmDesc:'View Email and KakaoTalk campaign status.',guideTabRoiName:'ROI Analysis',guideTabRoiDesc:'Comprehensive ROI analysis across all campaigns.',guideTabMonitorName:'Real-time Monitor',guideTabMonitorDesc:'Live monitoring of active campaign KPIs.',guideTabBudgetName:'Budget Alerts',guideTabBudgetDesc:'Automatic alert system based on budget burn rate.',guideTabCopyName:'AI Copywriter',guideTabCopyDesc:'AI-powered ad copy generator.',tabCreative:'AI Creative',creativeTitle:'AI Ad Creative Generator',creativeSub:'Enter a natural language prompt and AI will analyze content to auto-generate campaign-specific ad designs.',guideTabCreativeName:'AI Creative',guideTabCreativeDesc:'Natural language prompt-based AI ad image generator with 16 scene types.',channelFee:'Fee',channelFeeRate:'Fee Rate',noFeeData:'No fee data'},
ja:{guideStep1Title:'キャンペーン作成',guideStep1Desc:'AIオートマーケティングからキャンペーンを作成。予算、目標ROAS、期間を設定し広告チャネルを選択します。',guideStep2Title:'キャンペーン承認',guideStep2Desc:'予約済みカードの有効化承認ボタンをクリックして承認します。',guideStep3Title:'リアルタイム監視',guideStep3Desc:'アクティブキャンペーンのKPIをリアルタイム確認。消化率、日次予算、CV数、CPAを追跡。',guideStep4Title:'予算アラート管理',guideStep4Desc:'予算消化率70%以上で自動アラート。95%以上は自動停止。',guideStep5Title:'ROI分析',guideStep5Desc:'キャンペーン別ROAS、ROIを総合比較します。',guideStep6Title:'AIコピー生成',guideStep6Desc:'AIコピーライターで広告コピーを自動生成します。',guideTabOverviewName:'キャンペーン概要',guideTabOverviewDesc:'全キャンペーンをカード形式で表示。',guideTabAbName:'A/Bテスト',guideTabAbDesc:'A/Bテスト結果を統合表示。',guideTabDetailName:'詳細分析',guideTabDetailDesc:'KPI目標vs実績を確認。',guideTabGanttName:'スケジュール',guideTabGanttDesc:'ガントチャートで日程を視覚化。',guideTabCrmName:'CRMチャネル',guideTabCrmDesc:'メールとKakaoTalkの状況確認。',guideTabRoiName:'ROI分析',guideTabRoiDesc:'全キャンペーンROIを総合分析。',guideTabMonitorName:'リアルタイム監視',guideTabMonitorDesc:'アクティブKPIを監視。',guideTabBudgetName:'予算アラート',guideTabBudgetDesc:'消化率基準の自動アラート。',guideTabCopyName:'AIコピー',guideTabCopyDesc:'AI広告コピー生成ツール。',tabCreative:'AI広告素材',creativeTitle:'AI広告クリエイティブ生成',creativeSub:'自然言語プロンプトでAIが広告デザインを自動生成します。',guideTabCreativeName:'AI広告素材',guideTabCreativeDesc:'自然言語プロンプト基盤のAI広告画像生成。',channelFee:'手数料',channelFeeRate:'手数料率',noFeeData:'手数料情報なし'},
zh:{guideStep1Title:'创建活动',guideStep1Desc:'从AI自动营销创建活动。设置预算、目标ROAS和广告渠道。',guideStep2Title:'审批活动',guideStep2Desc:'点击激活审批按钮批准活动。',guideStep3Title:'实时监控',guideStep3Desc:'实时追踪活动KPI。',guideStep4Title:'预算告警管理',guideStep4Desc:'消耗率超70%自动告警。95%以上自动暂停。',guideStep5Title:'ROI分析',guideStep5Desc:'综合比较各活动ROAS和ROI。',guideStep6Title:'AI文案生成',guideStep6Desc:'AI自动生成广告文案。',guideTabOverviewName:'活动概览',guideTabOverviewDesc:'以卡片展示所有活动。',guideTabAbName:'A/B测试',guideTabAbDesc:'统合A/B测试结果。',guideTabDetailName:'详细分析',guideTabDetailDesc:'KPI目标与实际比较。',guideTabGanttName:'日程管理',guideTabGanttDesc:'甘特图可视化日程。',guideTabCrmName:'CRM渠道',guideTabCrmDesc:'邮件和KakaoTalk状况。',guideTabRoiName:'ROI分析',guideTabRoiDesc:'综合分析所有活动ROI。',guideTabMonitorName:'实时监控',guideTabMonitorDesc:'实时监控活动KPI。',guideTabBudgetName:'预算告警',guideTabBudgetDesc:'预算消耗率自动告警。',guideTabCopyName:'AI文案',guideTabCopyDesc:'AI广告文案生成工具。',tabCreative:'AI广告素材',creativeTitle:'AI广告创意生成器',creativeSub:'输入自然语言提示，AI自动生成广告设计。',guideTabCreativeName:'AI广告素材',guideTabCreativeDesc:'基于自然语言的AI广告图像生成器。',channelFee:'手续费',channelFeeRate:'费率',noFeeData:'无费用数据'},
};
GUIDE_KEYS['zh-TW']={guideStep1Title:'建立活動',guideStep1Desc:'從AI自動行銷建立活動。設定預算、目標ROAS和廣告頻道。',guideStep2Title:'核准活動',guideStep2Desc:'點擊啟用核准按鈕批准活動。',guideStep3Title:'即時監控',guideStep3Desc:'即時追蹤活動KPI。',guideStep4Title:'預算警報管理',guideStep4Desc:'消耗率超70%自動警報。',guideStep5Title:'ROI分析',guideStep5Desc:'綜合比較各活動ROAS和ROI。',guideStep6Title:'AI文案生成',guideStep6Desc:'AI自動生成廣告文案。',guideTabOverviewName:'活動概覽',guideTabOverviewDesc:'以卡片展示所有活動。',guideTabAbName:'A/B測試',guideTabAbDesc:'統合A/B測試結果。',guideTabDetailName:'詳細分析',guideTabDetailDesc:'KPI目標與實際比較。',guideTabGanttName:'日程管理',guideTabGanttDesc:'甘特圖視覺化日程。',guideTabCrmName:'CRM頻道',guideTabCrmDesc:'郵件和KakaoTalk狀況。',guideTabRoiName:'ROI分析',guideTabRoiDesc:'綜合分析所有活動ROI。',guideTabMonitorName:'即時監控',guideTabMonitorDesc:'即時監控活動KPI。',guideTabBudgetName:'預算警報',guideTabBudgetDesc:'預算消耗率自動警報。',guideTabCopyName:'AI文案',guideTabCopyDesc:'AI廣告文案生成工具。',tabCreative:'AI廣告素材',creativeTitle:'AI廣告創意生成器',creativeSub:'輸入自然語言提示，AI自動生成廣告設計。',guideTabCreativeName:'AI廣告素材',guideTabCreativeDesc:'基於自然語言的AI廣告影像生成器。',channelFee:'手續費',channelFeeRate:'費率',noFeeData:'無費用資料'};
GUIDE_KEYS.th={guideStep1Title:'สร้างแคมเปญ',guideStep1Desc:'สร้างแคมเปญจาก AI Auto Marketing ตั้งค่างบ เป้า ROAS และช่องทางโฆษณา',guideStep2Title:'อนุมัติแคมเปญ',guideStep2Desc:'คลิกปุ่มเปิดใช้งานบนการ์ดแคมเปญ',guideStep3Title:'ติดตามเรียลไทม์',guideStep3Desc:'ติดตาม KPI แบบเรียลไทม์',guideStep4Title:'จัดการแจ้งเตือนงบ',guideStep4Desc:'แจ้งเตือนอัตโนมัติเมื่อใช้จ่ายเกิน 70%',guideStep5Title:'วิเคราะห์ ROI',guideStep5Desc:'เปรียบเทียบ ROAS และ ROI ทุกแคมเปญ',guideStep6Title:'สร้างสำเนา AI',guideStep6Desc:'สร้างสำเนาโฆษณาด้วย AI อัตโนมัติ',guideTabOverviewName:'ภาพรวมแคมเปญ',guideTabOverviewDesc:'แสดงแคมเปญทั้งหมดเป็นการ์ด',guideTabAbName:'ทดสอบ A/B',guideTabAbDesc:'ดูผลทดสอบ A/B',guideTabDetailName:'วิเคราะห์รายละเอียด',guideTabDetailDesc:'ดูเป้า KPI เทียบกับจริง',guideTabGanttName:'ตารางเวลา',guideTabGanttDesc:'แสดงตารางด้วย Gantt Chart',guideTabCrmName:'ช่อง CRM',guideTabCrmDesc:'ดูสถานะ Email และ KakaoTalk',guideTabRoiName:'วิเคราะห์ ROI',guideTabRoiDesc:'วิเคราะห์ ROI ทุกแคมเปญ',guideTabMonitorName:'มอนิเตอร์เรียลไทม์',guideTabMonitorDesc:'ติดตาม KPI แบบเรียลไทม์',guideTabBudgetName:'แจ้งเตือนงบ',guideTabBudgetDesc:'ระบบแจ้งเตือนอัตโนมัติ',guideTabCopyName:'AI Copywriter',guideTabCopyDesc:'เครื่องมือสร้างสำเนาโฆษณา AI',tabCreative:'AI สื่อโฆษณา',creativeTitle:'เครื่องมือสร้างครีเอทีฟ AI',creativeSub:'ป้อนพรอมต์ภาษาธรรมชาติ AI จะสร้างดีไซน์โฆษณาอัตโนมัติ',guideTabCreativeName:'AI สื่อโฆษณา',guideTabCreativeDesc:'เครื่องมือสร้างภาพโฆษณา AI',channelFee:'ค่าธรรมเนียม',channelFeeRate:'อัตราค่าธรรมเนียม',noFeeData:'ไม่มีข้อมูลค่าธรรมเนียม'};
GUIDE_KEYS.vi={guideStep1Title:'Tao chien dich',guideStep1Desc:'Tao chien dich tu AI Auto Marketing. Dat ngan sach, ROAS muc tieu va kenh quang cao.',guideStep2Title:'Phe duyet chien dich',guideStep2Desc:'Nhan nut Kich hoat tren the chien dich.',guideStep3Title:'Giam sat thoi gian thuc',guideStep3Desc:'Theo doi KPI theo thoi gian thuc.',guideStep4Title:'Quan ly canh bao ngan sach',guideStep4Desc:'Canh bao tu dong khi ty le chi tieu vuot 70%.',guideStep5Title:'Phan tich ROI',guideStep5Desc:'So sanh ROAS va ROI cua tat ca chien dich.',guideStep6Title:'Tao ban sao AI',guideStep6Desc:'Tu dong tao ban sao quang cao bang AI.',guideTabOverviewName:'Tong quan',guideTabOverviewDesc:'Hien thi tat ca chien dich.',guideTabAbName:'Thu nghiem A/B',guideTabAbDesc:'Xem ket qua A/B test.',guideTabDetailName:'Phan tich chi tiet',guideTabDetailDesc:'Xem KPI muc tieu vs thuc te.',guideTabGanttName:'Lich trinh',guideTabGanttDesc:'Truc quan hoa lich trinh bang Gantt.',guideTabCrmName:'Kenh CRM',guideTabCrmDesc:'Xem tinh trang Email va KakaoTalk.',guideTabRoiName:'Phan tich ROI',guideTabRoiDesc:'Phan tich ROI toan dien.',guideTabMonitorName:'Giam sat thoi gian thuc',guideTabMonitorDesc:'Theo doi KPI truc tiep.',guideTabBudgetName:'Canh bao ngan sach',guideTabBudgetDesc:'He thong canh bao tu dong.',guideTabCopyName:'AI Copywriter',guideTabCopyDesc:'Cong cu tao ban sao quang cao AI.',tabCreative:'AI Sang tao',creativeTitle:'Trinh tao quang cao AI',creativeSub:'Nhap prompt ngon ngu tu nhien, AI se tao thiet ke quang cao tu dong.',guideTabCreativeName:'AI Sang tao',guideTabCreativeDesc:'Trinh tao hinh anh quang cao AI.',channelFee:'Phi',channelFeeRate:'Ty le phi',noFeeData:'Khong co du lieu phi'};
GUIDE_KEYS.de={guideStep1Title:'Kampagne erstellen',guideStep1Desc:'Erstellen Sie Kampagnen ueber AI Auto Marketing. Setzen Sie Budget, Ziel-ROAS und Werbekanaele.',guideStep2Title:'Kampagne genehmigen',guideStep2Desc:'Klicken Sie auf Aktivieren auf der geplanten Kampagnenkarte.',guideStep3Title:'Echtzeit-Monitoring',guideStep3Desc:'Ueberwachen Sie KPIs aktiver Kampagnen in Echtzeit.',guideStep4Title:'Budget-Alarm',guideStep4Desc:'Automatische Benachrichtigung bei Verbrauchsrate ueber 70%.',guideStep5Title:'ROI-Analyse',guideStep5Desc:'Vergleichen Sie ROAS und ROI aller Kampagnen.',guideStep6Title:'AI-Copy',guideStep6Desc:'Generieren Sie automatisch Werbetexte mit AI.',guideTabOverviewName:'Kampagnenuebersicht',guideTabOverviewDesc:'Zeigt alle Kampagnen als Karten.',guideTabAbName:'A/B-Tests',guideTabAbDesc:'Integrierte A/B-Testergebnisse.',guideTabDetailName:'Detailanalyse',guideTabDetailDesc:'KPI-Ziele vs Ist-Werte.',guideTabGanttName:'Zeitplan',guideTabGanttDesc:'Gantt-Diagramm Visualisierung.',guideTabCrmName:'CRM-Kanaele',guideTabCrmDesc:'E-Mail und KakaoTalk Status.',guideTabRoiName:'ROI-Analyse',guideTabRoiDesc:'Umfassende ROI-Analyse.',guideTabMonitorName:'Echtzeit-Monitor',guideTabMonitorDesc:'Live-Monitoring der KPIs.',guideTabBudgetName:'Budget-Alarms',guideTabBudgetDesc:'Automatisches Alarmsystem.',guideTabCopyName:'AI-Texter',guideTabCopyDesc:'KI-gestuetzter Werbetexter.',tabCreative:'AI-Werbematerial',creativeTitle:'AI-Werbematerial-Generator',creativeSub:'Geben Sie einen Prompt ein und AI generiert Werbedesigns.',guideTabCreativeName:'AI-Werbematerial',guideTabCreativeDesc:'KI-Bildgenerator mit 16 Szenentypen.',channelFee:'Gebuehr',channelFeeRate:'Gebuehrenrate',noFeeData:'Keine Gebuehrendaten'};
GUIDE_KEYS.fr={guideStep1Title:'Creer une campagne',guideStep1Desc:'Creez des campagnes depuis AI Auto Marketing. Definissez budget, ROAS cible et canaux.',guideStep2Title:'Approuver la campagne',guideStep2Desc:'Cliquez sur Activer sur la carte campagne planifiee.',guideStep3Title:'Surveillance temps reel',guideStep3Desc:'Surveillez les KPI en temps reel.',guideStep4Title:'Gestion alertes budget',guideStep4Desc:'Alerte automatique quand le taux depasse 70%.',guideStep5Title:'Analyse ROI',guideStep5Desc:'Comparez ROAS et ROI de toutes les campagnes.',guideStep6Title:'Generation copies AI',guideStep6Desc:'Generez automatiquement des copies avec AI.',guideTabOverviewName:'Apercu des campagnes',guideTabOverviewDesc:'Affiche toutes les campagnes en cartes.',guideTabAbName:'Tests A/B',guideTabAbDesc:'Resultats A/B integres.',guideTabDetailName:'Analyse detaillee',guideTabDetailDesc:'KPI cibles vs reels.',guideTabGanttName:'Planning',guideTabGanttDesc:'Diagramme de Gantt.',guideTabCrmName:'Canaux CRM',guideTabCrmDesc:'Statut Email et KakaoTalk.',guideTabRoiName:'Analyse ROI',guideTabRoiDesc:'Analyse ROI complete.',guideTabMonitorName:'Surveillance temps reel',guideTabMonitorDesc:'Surveillance en direct.',guideTabBudgetName:'Alertes budget',guideTabBudgetDesc:'Systeme alerte automatique.',guideTabCopyName:'AI Redacteur',guideTabCopyDesc:'Generateur de copies AI.',tabCreative:'AI Creatif',creativeTitle:'Generateur creatif AI',creativeSub:'Entrez un prompt et AI genere des designs publicitaires.',guideTabCreativeName:'AI Creatif',guideTabCreativeDesc:'Generateur images AI avec 16 types de scenes.',channelFee:'Frais',channelFeeRate:'Taux de frais',noFeeData:'Pas de donnees de frais'};
GUIDE_KEYS.es={guideStep1Title:'Crear campana',guideStep1Desc:'Cree campanas desde AI Auto Marketing. Configure presupuesto, ROAS objetivo y canales.',guideStep2Title:'Aprobar campana',guideStep2Desc:'Haga clic en Activar en la tarjeta de campana programada.',guideStep3Title:'Monitoreo en tiempo real',guideStep3Desc:'Monitoree KPIs en tiempo real.',guideStep4Title:'Gestion alertas presupuesto',guideStep4Desc:'Alerta automatica cuando el gasto supera 70%.',guideStep5Title:'Analisis ROI',guideStep5Desc:'Compare ROAS y ROI de todas las campanas.',guideStep6Title:'Generacion copies AI',guideStep6Desc:'Genere copies automaticamente con AI.',guideTabOverviewName:'Resumen campanas',guideTabOverviewDesc:'Muestra campanas como tarjetas.',guideTabAbName:'Pruebas A/B',guideTabAbDesc:'Resultados A/B integrados.',guideTabDetailName:'Analisis detallado',guideTabDetailDesc:'KPI objetivos vs reales.',guideTabGanttName:'Cronograma',guideTabGanttDesc:'Diagrama de Gantt.',guideTabCrmName:'Canales CRM',guideTabCrmDesc:'Estado Email y KakaoTalk.',guideTabRoiName:'Analisis ROI',guideTabRoiDesc:'Analisis ROI completo.',guideTabMonitorName:'Monitor tiempo real',guideTabMonitorDesc:'Monitoreo en vivo.',guideTabBudgetName:'Alertas presupuesto',guideTabBudgetDesc:'Sistema alerta automatica.',guideTabCopyName:'AI Redactor',guideTabCopyDesc:'Generador copies AI.',tabCreative:'AI Creativo',creativeTitle:'Generador creativo AI',creativeSub:'Ingrese un prompt y AI generara disenos publicitarios.',guideTabCreativeName:'AI Creativo',guideTabCreativeDesc:'Generador imagenes AI con 16 tipos de escenas.',channelFee:'Comision',channelFeeRate:'Tasa comision',noFeeData:'Sin datos de comision'};
GUIDE_KEYS.id={guideStep1Title:'Buat Kampanye',guideStep1Desc:'Buat kampanye dari AI Auto Marketing. Atur anggaran, target ROAS dan saluran iklan.',guideStep2Title:'Setujui Kampanye',guideStep2Desc:'Klik tombol Aktifkan pada kartu kampanye terjadwal.',guideStep3Title:'Pemantauan Real-time',guideStep3Desc:'Pantau KPI kampanye aktif secara real-time.',guideStep4Title:'Manajemen Peringatan Anggaran',guideStep4Desc:'Peringatan otomatis saat pengeluaran melebihi 70%.',guideStep5Title:'Analisis ROI',guideStep5Desc:'Bandingkan ROAS dan ROI semua kampanye.',guideStep6Title:'Pembuatan Copy AI',guideStep6Desc:'Buat copy iklan otomatis dengan AI.',guideTabOverviewName:'Ikhtisar Kampanye',guideTabOverviewDesc:'Menampilkan semua kampanye sebagai kartu.',guideTabAbName:'Pengujian A/B',guideTabAbDesc:'Hasil tes A/B terintegrasi.',guideTabDetailName:'Analisis Detail',guideTabDetailDesc:'Target KPI vs aktual.',guideTabGanttName:'Jadwal',guideTabGanttDesc:'Visualisasi jadwal dengan Gantt.',guideTabCrmName:'Saluran CRM',guideTabCrmDesc:'Status Email dan KakaoTalk.',guideTabRoiName:'Analisis ROI',guideTabRoiDesc:'Analisis ROI komprehensif.',guideTabMonitorName:'Monitor Real-time',guideTabMonitorDesc:'Pemantauan KPI langsung.',guideTabBudgetName:'Peringatan Anggaran',guideTabBudgetDesc:'Sistem peringatan otomatis.',guideTabCopyName:'AI Copywriter',guideTabCopyDesc:'Pembuat copy iklan AI.',tabCreative:'AI Kreatif',creativeTitle:'Generator Kreatif AI',creativeSub:'Masukkan prompt bahasa alami dan AI akan menghasilkan desain iklan.',guideTabCreativeName:'AI Kreatif',guideTabCreativeDesc:'Generator gambar iklan AI berbasis prompt.',channelFee:'Biaya',channelFeeRate:'Tarif Biaya',noFeeData:'Tidak ada data biaya'};

const locales=['ko','en','ja','zh','zh-TW','th','vi','de','fr','es','id'];
let ok=0;
for(const lang of locales){
  const f=DIR+'/'+lang+'.js';
  let s=fs.readFileSync(f,'utf8');
  const keys=GUIDE_KEYS[lang]||GUIDE_KEYS.en;
  
  // Find the campaignMgr section boundaries precisely
  const cmStart=s.indexOf('"campaignMgr"');
  if(cmStart===-1){console.log(lang+': ERROR - campaignMgr not found');continue;}
  
  // Find the opening brace of campaignMgr value
  const openBrace=s.indexOf('{',cmStart);
  
  // Count braces to find matching close
  let depth=0,cmEnd=-1;
  for(let i=openBrace;i<s.length;i++){
    if(s[i]==='{')depth++;
    if(s[i]==='}'){depth--;if(depth===0){cmEnd=i;break;}}
  }
  if(cmEnd===-1){console.log(lang+': ERROR - campaignMgr end not found');continue;}
  
  // Insert before the closing brace of campaignMgr
  const inject=','+Object.entries(keys).map(([k,v])=>'"'+k+'":'+JSON.stringify(v)).join(',');
  s=s.slice(0,cmEnd)+inject+s.slice(cmEnd);
  
  fs.writeFileSync(f,s,'utf8');
  
  // Verify
  try{
    delete require.cache[require.resolve('./'+f)];
    const m=require('./'+f).default||require('./'+f);
    const cnt=Object.keys(m.campaignMgr||{}).length;
    console.log(lang+': OK ('+cnt+' keys)');
    ok++;
  }catch(e){
    console.log(lang+': PARSE FAIL - '+e.message.split('\n')[0]);
  }
}
console.log('Done: '+ok+'/'+locales.length);
