/**
 * Hotfix 2: Fix ALL duplicate marketing English fallback blocks in es.js, fr.js, pt.js, ru.js, hi.js
 * These files have duplicate marketing objects at the end that override our translations.
 * Strategy: Replace English strings with native translations across ALL occurrences.
 */
const fs = require('fs');
const path = require('path');
const localeDir = path.join(__dirname, 'src', 'i18n', 'locales');

function fixAll(filePath, fixes) {
  let content = fs.readFileSync(filePath, 'utf8');
  let total = 0;
  for (const [from, to] of Object.entries(fixes)) {
    let c = 0;
    while (content.includes(from)) { content = content.replace(from, to); c++; }
    total += c;
  }
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`✅ ${path.basename(filePath)}: ${total} replacements`);
}

// ES — Spanish
fixAll(path.join(localeDir, 'es.js'), {
  '"autoTitle": "🚀 Marketing Automation Platform"': '"autoTitle": "🚀 Plataforma de Automatización de Marketing"',
  '"autoSub": "Set monthly budget and AI will automatically build optimized strategies for TikTok, Meta, Naver, etc."': '"autoSub": "Establezca el presupuesto mensual y la IA creará automáticamente estrategias optimizadas para TikTok, Meta, Naver, etc."',
  '"budgetSetup": "💰 Monthly Marketing Budget"': '"budgetSetup": "💰 Presupuesto de Marketing Mensual"',
  '"directInput": "Custom Amount (KRW)"': '"directInput": "Monto Personalizado"',
  '"directInput": "Direct Input (KRW)"': '"directInput": "Monto Personalizado"',
  '"campaignPeriod": "Campaign Period"': '"campaignPeriod": "Período de Campaña"',
  '"monthly": "Monthly (1 month)"': '"monthly": "Mensual (1 mes)"',
  '"quarterly": "Quarterly (3 months)"': '"quarterly": "Trimestral (3 meses)"',
  '"halfyear": "Semi-annual (6 months)"': '"halfyear": "Semestral (6 meses)"',
  '"setBudget": "Set Budget:"': '"setBudget": "Presupuesto Establecido:"',
  '"perMonth": "/ month"': '"perMonth": "/ mes"',
  '"categorySelect": "🏷 Select Product Categories (multiple)"': '"categorySelect": "🏷 Seleccione Categorías de Productos (múltiples)"',
  '"categorySelect": "🏷 Product Category (Multiple Selection)"': '"categorySelect": "🏷 Seleccione Categorías de Productos (múltiples)"',
  '"channelSelect": "📡 Select Ad Channels"': '"channelSelect": "📡 Seleccione Canales Publicitarios"',
  '"channelSelect": "📡 Ad Channel Selection"': '"channelSelect": "📡 Seleccione Canales Publicitarios"',
  '"salesChannels": "🌐 Connected Sales Channels"': '"salesChannels": "🌐 Canales de Venta Conectados"',
  '"generateBtn": "🚀 Auto-Generate AI Marketing Strategy"': '"generateBtn": "🚀 Generar Estrategia de Marketing IA Automáticamente"',
  '"generating": "🤖 AI is generating your strategy…"': '"generating": "🤖 La IA está generando su estrategia…"',
  '"needCatChannel": "⚠ Please select a category and ad channel."': '"needCatChannel": "⚠ Seleccione una categoría y canal publicitario."',
  '"previewEmpty": "← First generate an AI strategy in ① Campaign Setup."': '"previewEmpty": "← Primero genere una estrategia IA en ① Configuración de Campaña."',
  '"goSetup": "Go to Setup →"': '"goSetup": "Ir a Configuración →"',
  '"kpiTotal": "Total Budget"': '"kpiTotal": "Presupuesto Total"',
  '"kpiImpressions": "Est. Impressions"': '"kpiImpressions": "Impresiones Estimadas"',
  '"kpiClicks": "Est. Clicks"': '"kpiClicks": "Clics Estimados"',
  '"kpiConversions": "Est. Conversions"': '"kpiConversions": "Conversiones Estimadas"',
  '"kpiRoas": "Est. ROAS"': '"kpiRoas": "ROAS Estimado"',
  '"channelAlloc": "🤖 AI Channel Budget Allocation"': '"channelAlloc": "🤖 Asignación de Presupuesto por Canal IA"',
  '"approvalTitle": "✅ Submit for Approval"': '"approvalTitle": "✅ Enviar para Aprobación"',
  '"submitApproval": "📋 Submit Approval Request"': '"submitApproval": "📋 Enviar Solicitud de Aprobación"',
  '"resetBtn": "↩ Start Over"': '"resetBtn": "↩ Reiniciar"',
  '"budget": "Budget"': '"budget": "Presupuesto"',
  '"goCampaignMgr": "🎯 Campaign Manager →"': '"goCampaignMgr": "🎯 Gestor de Campañas →"',
  '"goHelp": "📚 Help"': '"goHelp": "📚 Ayuda"',
  '"selected": "✓ Selected"': '"selected": "✓ Seleccionado"',
  '"minBudget": "Min."': '"minBudget": "Mín."',
  '"cat_beauty": "Beauty & Cosmetics"': '"cat_beauty": "Belleza y Cosméticos"',
  '"cat_fashion": "Fashion & Apparel"': '"cat_fashion": "Moda y Ropa"',
  '"cat_general": "General Goods"': '"cat_general": "Productos Generales"',
  '"cat_food": "Food & Health"': '"cat_food": "Alimentación y Salud"',
  '"cat_electronics": "Electronics & IT"': '"cat_electronics": "Electrónica y TI"',
  '"cat_sports": "Sports & Leisure"': '"cat_sports": "Deportes y Ocio"',
  '"cat_travel": "Travel & Accommodation"': '"cat_travel": "Viajes y Alojamiento"',
  '"cat_digital": "Digital & Apps"': '"cat_digital": "Digital y Aplicaciones"',
  '"cat_platform": "Platform & Software"': '"cat_platform": "Plataforma y Software"',
  '"cat_overseas_ship": "Shipping Proxy"': '"cat_overseas_ship": "Envío Internacional"',
  '"cat_overseas_buy": "Buying Proxy"': '"cat_overseas_buy": "Agente de Compras"',
  '"guideStartBtn": "Get Started"': '"guideStartBtn": "Empezar Ahora"',
  '"aiHubTitle": "Check AI Marketing Hub First"': '"aiHubTitle": "Consulte el Hub de Marketing IA Primero"',
  '"aiHubBtn": "AI Marketing Hub"': '"aiHubBtn": "Hub de Marketing IA"',
  '"active": "● Active"': '"active": "● Activo"',
  '"inactive": "○ Inactive"': '"inactive": "○ Inactivo"',
  '"connStatusOk": "Connected"': '"connStatusOk": "Conectado"',
  '"connStatusNeed": "API Key Required"': '"connStatusNeed": "Se necesita API Key"',
});

// FR — French
fixAll(path.join(localeDir, 'fr.js'), {
  '"autoTitle": "🚀 Marketing Automation Platform"': '"autoTitle": "🚀 Plateforme d\'Automatisation Marketing"',
  '"autoSub": "Set monthly budget and AI will automatically build optimized strategies for TikTok, Meta, Naver, etc."': '"autoSub": "Définissez le budget mensuel et l\'IA créera automatiquement des stratégies optimisées pour TikTok, Meta, Naver, etc."',
  '"budgetSetup": "💰 Monthly Marketing Budget"': '"budgetSetup": "💰 Budget Marketing Mensuel"',
  '"directInput": "Custom Amount (KRW)"': '"directInput": "Montant Personnalisé"',
  '"directInput": "Direct Input (KRW)"': '"directInput": "Montant Personnalisé"',
  '"campaignPeriod": "Campaign Period"': '"campaignPeriod": "Période de Campagne"',
  '"monthly": "Monthly (1 month)"': '"monthly": "Mensuel (1 mois)"',
  '"quarterly": "Quarterly (3 months)"': '"quarterly": "Trimestriel (3 mois)"',
  '"halfyear": "Semi-annual (6 months)"': '"halfyear": "Semestriel (6 mois)"',
  '"setBudget": "Set Budget:"': '"setBudget": "Budget Défini:"',
  '"perMonth": "/ month"': '"perMonth": "/ mois"',
  '"categorySelect": "🏷 Select Product Categories (multiple)"': '"categorySelect": "🏷 Sélectionnez les Catégories (multiples)"',
  '"categorySelect": "🏷 Product Category (Multiple Selection)"': '"categorySelect": "🏷 Sélectionnez les Catégories (multiples)"',
  '"channelSelect": "📡 Select Ad Channels"': '"channelSelect": "📡 Sélectionnez les Canaux Publicitaires"',
  '"channelSelect": "📡 Ad Channel Selection"': '"channelSelect": "📡 Sélectionnez les Canaux Publicitaires"',
  '"salesChannels": "🌐 Connected Sales Channels"': '"salesChannels": "🌐 Canaux de Vente Connectés"',
  '"generateBtn": "🚀 Auto-Generate AI Marketing Strategy"': '"generateBtn": "🚀 Générer la Stratégie Marketing IA"',
  '"generating": "🤖 AI is generating your strategy…"': '"generating": "🤖 L\'IA génère votre stratégie…"',
  '"needCatChannel": "⚠ Please select a category and ad channel."': '"needCatChannel": "⚠ Veuillez sélectionner une catégorie et un canal."',
  '"previewEmpty": "← First generate an AI strategy in ① Campaign Setup."': '"previewEmpty": "← Générez d\'abord une stratégie IA dans ① Configuration."',
  '"goSetup": "Go to Setup →"': '"goSetup": "Aller à la Configuration →"',
  '"kpiTotal": "Total Budget"': '"kpiTotal": "Budget Total"',
  '"kpiImpressions": "Est. Impressions"': '"kpiImpressions": "Impressions Estimées"',
  '"kpiClicks": "Est. Clicks"': '"kpiClicks": "Clics Estimés"',
  '"kpiConversions": "Est. Conversions"': '"kpiConversions": "Conversions Estimées"',
  '"kpiRoas": "Est. ROAS"': '"kpiRoas": "ROAS Estimé"',
  '"channelAlloc": "🤖 AI Channel Budget Allocation"': '"channelAlloc": "🤖 Allocation Budget par Canal IA"',
  '"approvalTitle": "✅ Submit for Approval"': '"approvalTitle": "✅ Soumettre pour Approbation"',
  '"submitApproval": "📋 Submit Approval Request"': '"submitApproval": "📋 Demande d\'Approbation"',
  '"resetBtn": "↩ Start Over"': '"resetBtn": "↩ Recommencer"',
  '"budget": "Budget"': '"budget": "Budget"',
  '"goCampaignMgr": "🎯 Campaign Manager →"': '"goCampaignMgr": "🎯 Gestionnaire de Campagnes →"',
  '"goHelp": "📚 Help"': '"goHelp": "📚 Aide"',
  '"selected": "✓ Selected"': '"selected": "✓ Sélectionné"',
  '"minBudget": "Min."': '"minBudget": "Min."',
  '"cat_beauty": "Beauty & Cosmetics"': '"cat_beauty": "Beauté et Cosmétiques"',
  '"cat_fashion": "Fashion & Apparel"': '"cat_fashion": "Mode et Vêtements"',
  '"cat_general": "General Goods"': '"cat_general": "Produits Ménagers"',
  '"cat_food": "Food & Health"': '"cat_food": "Alimentation et Santé"',
  '"cat_electronics": "Electronics & IT"': '"cat_electronics": "Électronique et IT"',
  '"cat_sports": "Sports & Leisure"': '"cat_sports": "Sports et Loisirs"',
  '"cat_travel": "Travel & Accommodation"': '"cat_travel": "Voyages et Hébergement"',
  '"cat_digital": "Digital & Apps"': '"cat_digital": "Digital et Applications"',
  '"cat_platform": "Platform & Software"': '"cat_platform": "Plateforme et Logiciels"',
  '"cat_overseas_ship": "Shipping Proxy"': '"cat_overseas_ship": "Expédition Internationale"',
  '"cat_overseas_buy": "Buying Proxy"': '"cat_overseas_buy": "Agent d\'Achat"',
  '"guideStartBtn": "Get Started"': '"guideStartBtn": "Commencer"',
  '"aiHubTitle": "Check AI Marketing Hub First"': '"aiHubTitle": "Consultez d\'abord le Hub Marketing IA"',
  '"aiHubBtn": "AI Marketing Hub"': '"aiHubBtn": "Hub Marketing IA"',
  '"active": "● Active"': '"active": "● Actif"',
  '"inactive": "○ Inactive"': '"inactive": "○ Inactif"',
  '"connStatusOk": "Connected"': '"connStatusOk": "Connecté"',
  '"connStatusNeed": "API Key Required"': '"connStatusNeed": "Clé API requise"',
});

// PT — same duplicate fix
fixAll(path.join(localeDir, 'pt.js'), {
  '"autoTitle": "🚀 Marketing Automation Platform"': '"autoTitle": "🚀 Plataforma de Automação de Marketing"',
  '"autoSub": "Set monthly budget and AI will automatically build optimized strategies for TikTok, Meta, Naver, etc."': '"autoSub": "Defina o orçamento mensal e a IA criará automaticamente estratégias otimizadas para TikTok, Meta, Naver, etc."',
  '"budgetSetup": "💰 Monthly Marketing Budget"': '"budgetSetup": "💰 Orçamento Mensal de Marketing"',
  '"directInput": "Custom Amount (KRW)"': '"directInput": "Valor Personalizado"',
  '"directInput": "Direct Input (KRW)"': '"directInput": "Valor Personalizado"',
  '"campaignPeriod": "Campaign Period"': '"campaignPeriod": "Período da Campanha"',
  '"monthly": "Monthly (1 month)"': '"monthly": "Mensal (1 mês)"',
  '"quarterly": "Quarterly (3 months)"': '"quarterly": "Trimestral (3 meses)"',
  '"halfyear": "Semi-annual (6 months)"': '"halfyear": "Semestral (6 meses)"',
  '"categorySelect": "🏷 Select Product Categories (multiple)"': '"categorySelect": "🏷 Selecione Categorias (múltiplas)"',
  '"categorySelect": "🏷 Product Category (Multiple Selection)"': '"categorySelect": "🏷 Selecione Categorias (múltiplas)"',
  '"channelSelect": "📡 Select Ad Channels"': '"channelSelect": "📡 Selecione Canais de Anúncio"',
  '"channelSelect": "📡 Ad Channel Selection"': '"channelSelect": "📡 Selecione Canais de Anúncio"',
  '"generateBtn": "🚀 Auto-Generate AI Marketing Strategy"': '"generateBtn": "🚀 Gerar Estratégia de Marketing IA"',
  '"generating": "🤖 AI is generating your strategy…"': '"generating": "🤖 IA gerando estratégia…"',
  '"kpiTotal": "Total Budget"': '"kpiTotal": "Orçamento Total"',
  '"channelAlloc": "🤖 AI Channel Budget Allocation"': '"channelAlloc": "🤖 Alocação de Orçamento por Canal IA"',
  '"cat_beauty": "Beauty & Cosmetics"': '"cat_beauty": "Beleza e Cosméticos"',
  '"cat_fashion": "Fashion & Apparel"': '"cat_fashion": "Moda e Vestuário"',
  '"cat_general": "General Goods"': '"cat_general": "Produtos Gerais"',
  '"cat_food": "Food & Health"': '"cat_food": "Alimentos e Saúde"',
  '"cat_electronics": "Electronics & IT"': '"cat_electronics": "Eletrônicos e TI"',
  '"cat_sports": "Sports & Leisure"': '"cat_sports": "Esportes e Lazer"',
  '"cat_travel": "Travel & Accommodation"': '"cat_travel": "Viagem e Hospedagem"',
  '"cat_digital": "Digital & Apps"': '"cat_digital": "Digital e Aplicativos"',
  '"guideStartBtn": "Get Started"': '"guideStartBtn": "Começar Agora"',
  '"aiHubTitle": "Check AI Marketing Hub First"': '"aiHubTitle": "Verifique o Hub de Marketing IA"',
  '"goSetup": "Go to Setup →"': '"goSetup": "Ir para Configuração →"',
  '"budget": "Budget"': '"budget": "Orçamento"',
  '"selected": "✓ Selected"': '"selected": "✓ Selecionado"',
});

// RU — same duplicate fix
fixAll(path.join(localeDir, 'ru.js'), {
  '"autoTitle": "🚀 Marketing Automation Platform"': '"autoTitle": "🚀 Платформа автоматизации маркетинга"',
  '"autoSub": "Set monthly budget and AI will automatically build optimized strategies for TikTok, Meta, Naver, etc."': '"autoSub": "Установите месячный бюджет, и ИИ автоматически создаст оптимизированные стратегии."',
  '"budgetSetup": "💰 Monthly Marketing Budget"': '"budgetSetup": "💰 Ежемесячный маркетинговый бюджет"',
  '"directInput": "Custom Amount (KRW)"': '"directInput": "Произвольная сумма"',
  '"directInput": "Direct Input (KRW)"': '"directInput": "Произвольная сумма"',
  '"campaignPeriod": "Campaign Period"': '"campaignPeriod": "Период кампании"',
  '"monthly": "Monthly (1 month)"': '"monthly": "Ежемесячно (1 месяц)"',
  '"quarterly": "Quarterly (3 months)"': '"quarterly": "Ежеквартально (3 месяца)"',
  '"halfyear": "Semi-annual (6 months)"': '"halfyear": "Полугодовой (6 месяцев)"',
  '"categorySelect": "🏷 Select Product Categories (multiple)"': '"categorySelect": "🏷 Выберите категории товаров"',
  '"categorySelect": "🏷 Product Category (Multiple Selection)"': '"categorySelect": "🏷 Выберите категории товаров"',
  '"channelSelect": "📡 Select Ad Channels"': '"channelSelect": "📡 Выберите рекламные каналы"',
  '"channelSelect": "📡 Ad Channel Selection"': '"channelSelect": "📡 Выберите рекламные каналы"',
  '"generateBtn": "🚀 Auto-Generate AI Marketing Strategy"': '"generateBtn": "🚀 Автоматическая генерация маркетинговой стратегии ИИ"',
  '"generating": "🤖 AI is generating your strategy…"': '"generating": "🤖 ИИ генерирует стратегию…"',
  '"kpiTotal": "Total Budget"': '"kpiTotal": "Общий бюджет"',
  '"channelAlloc": "🤖 AI Channel Budget Allocation"': '"channelAlloc": "🤖 ИИ-распределение бюджета по каналам"',
  '"cat_beauty": "Beauty & Cosmetics"': '"cat_beauty": "Красота и косметика"',
  '"cat_fashion": "Fashion & Apparel"': '"cat_fashion": "Мода и одежда"',
  '"cat_general": "General Goods"': '"cat_general": "Товары для дома"',
  '"cat_food": "Food & Health"': '"cat_food": "Питание и здоровье"',
  '"cat_electronics": "Electronics & IT"': '"cat_electronics": "Электроника и ИТ"',
  '"cat_sports": "Sports & Leisure"': '"cat_sports": "Спорт и отдых"',
  '"cat_travel": "Travel & Accommodation"': '"cat_travel": "Путешествия и проживание"',
  '"cat_digital": "Digital & Apps"': '"cat_digital": "Цифровые продукты и приложения"',
  '"guideStartBtn": "Get Started"': '"guideStartBtn": "Начать"',
  '"aiHubTitle": "Check AI Marketing Hub First"': '"aiHubTitle": "Сначала проверьте ИИ-маркетинговый хаб"',
  '"goSetup": "Go to Setup →"': '"goSetup": "К настройке →"',
  '"budget": "Budget"': '"budget": "Бюджет"',
  '"selected": "✓ Selected"': '"selected": "✓ Выбрано"',
});

// HI — same duplicate fix
fixAll(path.join(localeDir, 'hi.js'), {
  '"autoTitle": "🚀 Marketing Automation Platform"': '"autoTitle": "🚀 मार्केटिंग ऑटोमेशन प्लेटफ़ॉर्म"',
  '"autoSub": "Set monthly budget and AI will automatically build optimized strategies for TikTok, Meta, Naver, etc."': '"autoSub": "मासिक बजट सेट करें और AI स्वचालित रूप से अनुकूलित रणनीतियाँ बनाएगा।"',
  '"budgetSetup": "💰 Monthly Marketing Budget"': '"budgetSetup": "💰 मासिक मार्केटिंग बजट"',
  '"directInput": "Custom Amount (KRW)"': '"directInput": "कस्टम राशि"',
  '"directInput": "Direct Input (KRW)"': '"directInput": "कस्टम राशि"',
  '"campaignPeriod": "Campaign Period"': '"campaignPeriod": "अभियान अवधि"',
  '"monthly": "Monthly (1 month)"': '"monthly": "मासिक (1 महीना)"',
  '"quarterly": "Quarterly (3 months)"': '"quarterly": "त्रैमासिक (3 महीने)"',
  '"halfyear": "Semi-annual (6 months)"': '"halfyear": "अर्धवार्षिक (6 महीने)"',
  '"categorySelect": "🏷 Select Product Categories (multiple)"': '"categorySelect": "🏷 उत्पाद श्रेणियाँ चुनें"',
  '"categorySelect": "🏷 Product Category (Multiple Selection)"': '"categorySelect": "🏷 उत्पाद श्रेणियाँ चुनें"',
  '"channelSelect": "📡 Select Ad Channels"': '"channelSelect": "📡 विज्ञापन चैनल चुनें"',
  '"channelSelect": "📡 Ad Channel Selection"': '"channelSelect": "📡 विज्ञापन चैनल चुनें"',
  '"generateBtn": "🚀 Auto-Generate AI Marketing Strategy"': '"generateBtn": "🚀 AI मार्केटिंग रणनीति स्वतः बनाएं"',
  '"generating": "🤖 AI is generating your strategy…"': '"generating": "🤖 AI रणनीति बना रहा है…"',
  '"kpiTotal": "Total Budget"': '"kpiTotal": "कुल बजट"',
  '"channelAlloc": "🤖 AI Channel Budget Allocation"': '"channelAlloc": "🤖 AI चैनल बजट आवंटन"',
  '"cat_beauty": "Beauty & Cosmetics"': '"cat_beauty": "सौंदर्य और सौंदर्य प्रसाधन"',
  '"cat_fashion": "Fashion & Apparel"': '"cat_fashion": "फैशन और वस्त्र"',
  '"cat_general": "General Goods"': '"cat_general": "सामान्य सामान"',
  '"cat_food": "Food & Health"': '"cat_food": "भोजन और स्वास्थ्य"',
  '"cat_electronics": "Electronics & IT"': '"cat_electronics": "इलेक्ट्रॉनिक्स और IT"',
  '"cat_sports": "Sports & Leisure"': '"cat_sports": "खेल और मनोरंजन"',
  '"cat_travel": "Travel & Accommodation"': '"cat_travel": "यात्रा और आवास"',
  '"cat_digital": "Digital & Apps"': '"cat_digital": "डिजिटल और ऐप्स"',
  '"guideStartBtn": "Get Started"': '"guideStartBtn": "शुरू करें"',
  '"aiHubTitle": "Check AI Marketing Hub First"': '"aiHubTitle": "पहले AI मार्केटिंग हब देखें"',
  '"goSetup": "Go to Setup →"': '"goSetup": "सेटअप पर जाएं →"',
  '"budget": "Budget"': '"budget": "बजट"',
  '"selected": "✓ Selected"': '"selected": "✓ चयनित"',
});

console.log('✅ Hotfix 2 complete: All duplicate English blocks overwritten with native');
