const fs = require('fs');

const BANNER_TRANSLATIONS = {
  ko: {
    "mktLowRoas": "AI 탐지: {{channel}} ROAS {{roas}}x (목표 {{target}}x 미달)",
    "mktRulesActive": "Active 자동룰 {{count}}개 감시 중 · Today {{fired}}회 발동",
    "mktOptimizeNow": "즉시 Budget 최적화 권장",
    "mktHubAction": "AI 허브에서 자동 최적화 →",
    "mktHighRoas": "우수 Channel 감지: {{channel}} ROAS {{roas}}x — Budget 배분 추천",
    "mktHighRoasSub": "AI 허브에서 Budget을 재배분하면 +23% Revenue 예상",
    "mktBudgetAction": "AI Budget 최적화 →",
    "crmChurn": "이탈 위험 고객 {{count}}명 감지 — 자동 재활성화 캠페인 추천",
    "crmVip": "VIP {{count}}명은 전용 특가 발송 추천",
    "crmJourney": "지금 Journey 빌더로 자동 여정 시작",
    "crmJourneyAction": "고객 여정 자동화 →",
    "ordersAiRun": "AI 마케팅 허브 최근 Run: {{title}}",
    "ordersAiSub": "예상 Revenue ₩{{revenue}} · Run시각 {{at}}",
    "ordersCampaignAction": "캠페인 현황 →",
    "pnlLowMargin": "P&L 마진 {{margin}}% — AI 비용 최적화 권장 (목표: 20%+)",
    "pnlLowMarginSub": "Ad Spend/플랫폼수수료 구조 개선으로 마진 개선 가능",
    "pnlAiAction": "AI 최적화 Plan →",
    "pnlHighMargin": "우수 마진 {{margin}}% 달성 — 공격적 Budget 확대 타이밍",
    "pnlHighMarginSub": "AI 허브에서 고수익 Channel Budget 배분을 추천합니다",
    "pnlBudgetAction": "AI Budget 확대 →",
    "kpiRulesActive": "AI 자동화 룰 {{count}}개 실시간 KPI 감시 중",
    "kpiRulesFired": "Today {{count}}회 자동 발동 — 이상 패턴 감지됨",
    "kpiAllNormal": "모든 KPI 정상 범위",
    "kpiRuleAction": "룰 엔진 상세 →",
    "attrAiRun": "AI 허브 Run {{count}}건의 Channel 기여 데이터가 Attribution에 반영됨",
    "attrAiSub": "각 Channel의 실제 기여도를 5가지 모델로 비교 분석하세요",
  },
  en: {
    "mktLowRoas": "AI Detected: {{channel}} ROAS {{roas}}x (below target {{target}}x)",
    "mktRulesActive": "{{count}} active auto-rules monitoring · {{fired}} triggered today",
    "mktOptimizeNow": "Immediate budget optimization recommended",
    "mktHubAction": "Auto-optimize in AI Hub →",
    "mktHighRoas": "High-performing channel detected: {{channel}} ROAS {{roas}}x — Budget increase recommended",
    "mktHighRoasSub": "Reallocating budget in AI Hub could yield +23% revenue",
    "mktBudgetAction": "AI Budget Optimization →",
    "crmChurn": "{{count}} at-risk customers detected — Auto re-engagement campaign recommended",
    "crmVip": "Send exclusive offers to {{count}} VIP customers",
    "crmJourney": "Start automated journey in Journey Builder now",
    "crmJourneyAction": "Automate Customer Journey →",
    "ordersAiRun": "Recent AI Marketing Hub Run: {{title}}",
    "ordersAiSub": "Estimated Revenue ₩{{revenue}} · Executed at {{at}}",
    "ordersCampaignAction": "Campaign Status →",
    "pnlLowMargin": "P&L Margin {{margin}}% — AI cost optimization recommended (target: 20%+)",
    "pnlLowMarginSub": "Margin improvement possible by optimizing ad spend/platform fees",
    "pnlAiAction": "AI Optimization Plan →",
    "pnlHighMargin": "Excellent margin {{margin}}% achieved — Time for aggressive budget expansion",
    "pnlHighMarginSub": "AI Hub recommends allocating budget to high-revenue channels",
    "pnlBudgetAction": "AI Budget Expansion →",
    "kpiRulesActive": "{{count}} AI automation rules monitoring KPIs in real-time",
    "kpiRulesFired": "{{count}} auto-triggered today — Anomaly pattern detected",
    "kpiAllNormal": "All KPIs within normal range",
    "kpiRuleAction": "Rule Engine Details →",
    "attrAiRun": "AI Hub Run: {{count}} channel attribution data reflected in Attribution",
    "attrAiSub": "Compare actual channel contribution with 5 attribution models",
  },
  ja: {
    "mktLowRoas": "AI検出: {{channel}} ROAS {{roas}}x (目標 {{target}}x 未達)",
    "mktRulesActive": "Active自動ルール {{count}}個監視中 · Today {{fired}}回発動",
    "mktOptimizeNow": "即時Budget最適化を推奨",
    "mktHubAction": "AIハブで自動最適化 →",
    "mktHighRoas": "高ROAS Channel検出: {{channel}} ROAS {{roas}}x — Budget増額推奨",
    "mktHighRoasSub": "AIハブでBudget再配分すると、+23% Revenue見込み",
    "mktBudgetAction": "AI Budget最適化 →",
    "crmChurn": "離脱リスク顧客{{count}}名検出 — 自動再アクティブ化キャンペーン推奨",
    "crmVip": "VIP {{count}}名に限定特典送信を推奨",
    "crmJourney": "今すぐJourneyビルダーで自動化開始",
    "crmJourneyAction": "顧客ジャーニー自動化 →",
    "ordersAiRun": "AIマーケティングハブ最近Run: {{title}}",
    "ordersAiSub": "予想Revenue ₩{{revenue}} · Run時刻 {{at}}",
    "ordersCampaignAction": "キャンペーン状況 →",
    "pnlLowMargin": "P&Lマージン{{margin}}% — AIコスト最適化推奨 (目標: 20%+)",
    "pnlLowMarginSub": "広告費/プラットフォーム手数料の改善でマージン改善可能",
    "pnlAiAction": "AI最適化プラン →",
    "pnlHighMargin": "優秀マージン{{margin}}%達成 — 積極的Budget拡大タイミング",
    "pnlHighMarginSub": "AIハブで高収益ChannelへのBudget配分を推奨",
    "pnlBudgetAction": "AI Budget拡大 →",
    "kpiRulesActive": "AI自動化ルール{{count}}個がKPIをリアルタイム監視中",
    "kpiRulesFired": "Today {{count}}回自動発動 — 異常パターン検出",
    "kpiAllNormal": "全KPI正常範囲",
    "kpiRuleAction": "ルールエンジン詳細 →",
    "attrAiRun": "AIハブ Run {{count}}件のChannel貢献データがAttributionに反映",
    "attrAiSub": "各Channelの実際の貢献度を5つのモデルで比較分析してください",
  },
  zh: {
    "mktLowRoas": "AI检测: {{channel}} ROAS {{roas}}x (低于目标 {{target}}x)",
    "mktRulesActive": "{{count}}个自动规则监控中 · 今日触发{{fired}}次",
    "mktOptimizeNow": "建议立即优化预算",
    "mktHubAction": "在AI中心自动优化 →",
    "mktHighRoas": "检测到优质渠道: {{channel}} ROAS {{roas}}x — 建议增加预算",
    "mktHighRoasSub": "在AI中心重新分配预算，预计收益增加23%",
    "mktBudgetAction": "AI预算优化 →",
    "crmChurn": "检测到{{count}}名流失风险客户 — 建议自动再激活活动",
    "crmVip": "建议向{{count}}名VIP客户发送专属优惠",
    "crmJourney": "立即在旅程构建器中开始自动旅程",
    "crmJourneyAction": "客户旅程自动化 →",
    "ordersAiRun": "AI营销中心最近运行: {{title}}",
    "ordersAiSub": "预计收益 ₩{{revenue}} · 运行时间 {{at}}",
    "ordersCampaignAction": "广告活动状态 →",
    "pnlLowMargin": "P&L利润率 {{margin}}% — 建议AI成本优化 (目标: 20%+)",
    "pnlLowMarginSub": "通过优化广告费用/平台佣金结构可改善利润率",
    "pnlAiAction": "AI优化方案 →",
    "pnlHighMargin": "实现优秀利润率 {{margin}}% — 是积极扩大预算的好时机",
    "pnlHighMarginSub": "AI中心建议向高收益渠道分配预算",
    "pnlBudgetAction": "扩大AI预算 →",
    "kpiRulesActive": "{{count}}个AI自动化规则正在实时监控KPI",
    "kpiRulesFired": "今日自动触发{{count}}次 — 检测到异常模式",
    "kpiAllNormal": "所有KPI在正常范围内",
    "kpiRuleAction": "规则引擎详情 →",
    "attrAiRun": "AI中心 运行{{count}}次渠道贡献数据已反映在归因分析中",
    "attrAiSub": "用5种归因模型比较各渠道的实际贡献度",
  },
  de: {
    "mktLowRoas": "KI erkannt: {{channel}} ROAS {{roas}}x (unter Ziel {{target}}x)",
    "mktRulesActive": "{{count}} aktive Auto-Regeln überwachen · {{fired}}x heute ausgelöst",
    "mktOptimizeNow": "Sofortige Budget-Optimierung empfohlen",
    "mktHubAction": "Im KI-Hub automatisch optimieren →",
    "mktHighRoas": "Leistungsstarken Channel entdeckt: {{channel}} ROAS {{roas}}x — Budget-Erhöhung empfohlen",
    "mktHighRoasSub": "Budget-Umverteilung im KI-Hub könnte +23% Umsatz bringen",
    "mktBudgetAction": "KI-Budget-Optimierung →",
    "crmChurn": "{{count}} abwanderungsgefährdete Kunden erkannt — Automatische Reaktivierungskampagne empfohlen",
    "crmVip": "Exklusive Angebote an {{count}} VIP-Kunden senden empfohlen",
    "crmJourney": "Jetzt automatisierte Reise im Journey-Builder starten",
    "crmJourneyAction": "Customer Journey automatisieren →",
    "ordersAiRun": "Letzter KI-Marketing-Hub-Lauf: {{title}}",
    "ordersAiSub": "Geschätzter Umsatz ₩{{revenue}} · Ausgeführt um {{at}}",
    "ordersCampaignAction": "Kampagnenstatus →",
    "pnlLowMargin": "P&L-Marge {{margin}}% — KI-Kostenoptimierung empfohlen (Ziel: 20%+)",
    "pnlLowMarginSub": "Margenverbesserung durch Optimierung der Werbeausgaben/Plattformgebühren möglich",
    "pnlAiAction": "KI-Optimierungsplan →",
    "pnlHighMargin": "Ausgezeichnete Marge {{margin}}% erreicht — Zeit für aggressive Budget-Ausweitung",
    "pnlHighMarginSub": "KI-Hub empfiehlt Budget-Zuweisung für ertragstarke Channels",
    "pnlBudgetAction": "KI-Budget-Ausweitung →",
    "kpiRulesActive": "{{count}} KI-Automatisierungsregeln überwachen KPIs in Echtzeit",
    "kpiRulesFired": "{{count}}x heute automatisch ausgelöst — Anomaliemuster erkannt",
    "kpiAllNormal": "Alle KPIs im normalen Bereich",
    "kpiRuleAction": "Regelmotor-Details →",
    "attrAiRun": "KI-Hub-Lauf: {{count}} Channel-Zuordnungsdaten in Attribution übernommen",
    "attrAiSub": "Echte Channel-Beiträge mit 5 Attribution-Modellen vergleichen",
  },
  th: {
    "mktLowRoas": "AI ตรวจพบ: {{channel}} ROAS {{roas}}x (ต่ำกว่าเป้าหมาย {{target}}x)",
    "mktRulesActive": "{{count}} กฎอัตโนมัติที่ใช้งาน · ทริกเกอร์ {{fired}} ครั้งวันนี้",
    "mktOptimizeNow": "แนะนำให้เพิ่มประสิทธิภาพงบประมาณทันที",
    "mktHubAction": "เพิ่มประสิทธิภาพอัตโนมัติใน AI Hub →",
    "mktHighRoas": "ตรวจพบช่องทางประสิทธิภาพสูง: {{channel}} ROAS {{roas}}x — แนะนำเพิ่มงบประมาณ",
    "mktHighRoasSub": "การจัดสรรงบใหม่ใน AI Hub คาดว่าจะเพิ่มรายได้ +23%",
    "mktBudgetAction": "เพิ่มประสิทธิภาพงบประมาณ AI →",
    "crmChurn": "ตรวจพบลูกค้าเสี่ยงหลุด {{count}} คน — แนะนำแคมเปญดึงกลับอัตโนมัติ",
    "crmVip": "แนะนำส่งข้อเสนอพิเศษให้ลูกค้า VIP {{count}} คน",
    "crmJourney": "เริ่มการเดินทางอัตโนมัติใน Journey Builder ตอนนี้",
    "crmJourneyAction": "ทำให้ Customer Journey อัตโนมัติ →",
    "ordersAiRun": "การรัน AI Marketing Hub ล่าสุด: {{title}}",
    "ordersAiSub": "รายได้ที่คาดการณ์ ₩{{revenue}} · เวลารัน {{at}}",
    "ordersCampaignAction": "สถานะแคมเปญ →",
    "pnlLowMargin": "อัตรากำไร P&L {{margin}}% — แนะนำให้ AI เพิ่มประสิทธิภาพต้นทุน (เป้าหมาย: 20%+)",
    "pnlLowMarginSub": "สามารถปรับปรุงอัตรากำไรได้โดยการเพิ่มประสิทธิภาพค่าโฆษณา/ค่าธรรมเนียมแพลตฟอร์ม",
    "pnlAiAction": "แผน AI เพิ่มประสิทธิภาพ →",
    "pnlHighMargin": "บรรลุอัตรากำไรยอดเยี่ยม {{margin}}% — ถึงเวลาขยายงบประมาณอย่างรุกรัน",
    "pnlHighMarginSub": "AI Hub แนะนำการจัดสรรงบประมาณให้ช่องทางที่มีรายได้สูง",
    "pnlBudgetAction": "ขยายงบประมาณ AI →",
    "kpiRulesActive": "{{count}} กฎ AI อัตโนมัติกำลังตรวจสอบ KPI แบบเรียลไทม์",
    "kpiRulesFired": "ทริกเกอร์อัตโนมัติ {{count}} ครั้งวันนี้ — ตรวจพบรูปแบบผิดปกติ",
    "kpiAllNormal": "KPI ทั้งหมดอยู่ในช่วงปกติ",
    "kpiRuleAction": "รายละเอียด Rule Engine →",
    "attrAiRun": "AI Hub รัน{{count}}ครั้ง: ข้อมูลการระบุแหล่งที่มาของช่องทางสะท้อนใน Attribution",
    "attrAiSub": "เปรียบเทียบการมีส่วนร่วมจริงของช่องทางด้วย 5 โมเดลการระบุแหล่งที่มา",
  },
  vi: {
    "mktLowRoas": "AI phát hiện: {{channel}} ROAS {{roas}}x (dưới mục tiêu {{target}}x)",
    "mktRulesActive": "{{count}} quy tắc tự động đang giám sát · kích hoạt {{fired}} lần hôm nay",
    "mktOptimizeNow": "Khuyến nghị tối ưu hóa ngân sách ngay lập tức",
    "mktHubAction": "Tự động tối ưu tại AI Hub →",
    "mktHighRoas": "Phát hiện kênh hiệu suất cao: {{channel}} ROAS {{roas}}x — Khuyến nghị tăng ngân sách",
    "mktHighRoasSub": "Phân bổ lại ngân sách trong AI Hub có thể tăng doanh thu +23%",
    "mktBudgetAction": "Tối ưu Ngân sách AI →",
    "crmChurn": "Phát hiện {{count}} khách hàng có nguy cơ rời bỏ — Khuyến nghị chiến dịch tái kích hoạt tự động",
    "crmVip": "Khuyến nghị gửi ưu đãi độc quyền cho {{count}} khách hàng VIP",
    "crmJourney": "Bắt đầu hành trình tự động trong Journey Builder ngay",
    "crmJourneyAction": "Tự động hóa Hành trình Khách hàng →",
    "ordersAiRun": "AI Marketing Hub chạy gần đây: {{title}}",
    "ordersAiSub": "Doanh thu ước tính ₩{{revenue}} · Thực thi lúc {{at}}",
    "ordersCampaignAction": "Trạng thái Chiến dịch →",
    "pnlLowMargin": "Biên lợi nhuận P&L {{margin}}% — Khuyến nghị AI tối ưu chi phí (mục tiêu: 20%+)",
    "pnlLowMarginSub": "Có thể cải thiện biên lợi nhuận bằng cách tối ưu chi phí quảng cáo/phí nền tảng",
    "pnlAiAction": "Kế hoạch Tối ưu AI →",
    "pnlHighMargin": "Đạt biên lợi nhuận xuất sắc {{margin}}% — Thời điểm mở rộng ngân sách mạnh mẽ",
    "pnlHighMarginSub": "AI Hub khuyến nghị phân bổ ngân sách cho các kênh doanh thu cao",
    "pnlBudgetAction": "Mở rộng Ngân sách AI →",
    "kpiRulesActive": "{{count}} quy tắc tự động AI đang giám sát KPI theo thời gian thực",
    "kpiRulesFired": "Tự động kích hoạt {{count}} lần hôm nay — Phát hiện mô hình bất thường",
    "kpiAllNormal": "Tất cả KPI trong phạm vi bình thường",
    "kpiRuleAction": "Chi tiết Rule Engine →",
    "attrAiRun": "AI Hub chạy {{count}} lần: dữ liệu đóng góp kênh được phản ánh trong Attribution",
    "attrAiSub": "So sánh đóng góp thực của kênh với 5 mô hình quy kết",
  },
  id: {
    "mktLowRoas": "AI Terdeteksi: {{channel}} ROAS {{roas}}x (di bawah target {{target}}x)",
    "mktRulesActive": "{{count}} aturan otomatis aktif · dipicu {{fired}} kali hari ini",
    "mktOptimizeNow": "Optimisasi anggaran segera direkomendasikan",
    "mktHubAction": "Optimisasi otomatis di AI Hub →",
    "mktHighRoas": "Saluran berkinerja tinggi terdeteksi: {{channel}} ROAS {{roas}}x — Peningkatan anggaran direkomendasikan",
    "mktHighRoasSub": "Realokasi anggaran di AI Hub dapat menghasilkan +23% pendapatan",
    "mktBudgetAction": "Optimisasi Anggaran AI →",
    "crmChurn": "{{count}} pelanggan berisiko churn terdeteksi — Kampanye reaktivasi otomatis direkomendasikan",
    "crmVip": "Kirim penawaran eksklusif ke {{count}} pelanggan VIP",
    "crmJourney": "Mulai perjalanan otomatis di Journey Builder sekarang",
    "crmJourneyAction": "Otomatisasi Perjalanan Pelanggan →",
    "ordersAiRun": "AI Marketing Hub Run terbaru: {{title}}",
    "ordersAiSub": "Estimasi Pendapatan ₩{{revenue}} · Dijalankan pada {{at}}",
    "ordersCampaignAction": "Status Kampanye →",
    "pnlLowMargin": "Margin P&L {{margin}}% — Optimisasi biaya AI direkomendasikan (target: 20%+)",
    "pnlLowMarginSub": "Peningkatan margin mungkin dengan mengoptimalkan biaya iklan/biaya platform",
    "pnlAiAction": "Rencana Optimisasi AI →",
    "pnlHighMargin": "Margin luar biasa {{margin}}% tercapai — Waktu untuk ekspansi anggaran agresif",
    "pnlHighMarginSub": "AI Hub merekomendasikan alokasi anggaran ke saluran pendapatan tinggi",
    "pnlBudgetAction": "Ekspansi Anggaran AI →",
    "kpiRulesActive": "{{count}} aturan otomasi AI memantau KPI secara real-time",
    "kpiRulesFired": "Dipicu otomatis {{count}} kali hari ini — Pola anomali terdeteksi",
    "kpiAllNormal": "Semua KPI dalam rentang normal",
    "kpiRuleAction": "Detail Rule Engine →",
    "attrAiRun": "AI Hub Run: data atribusi {{count}} saluran tercermin dalam Attribution",
    "attrAiSub": "Bandingkan kontribusi saluran nyata dengan 5 model atribusi",
  },
  'zh-TW': {
    "mktLowRoas": "AI偵測: {{channel}} ROAS {{roas}}x (低於目標 {{target}}x)",
    "mktRulesActive": "{{count}}個自動規則監控中 · 今日觸發{{fired}}次",
    "mktOptimizeNow": "建議立即優化預算",
    "mktHubAction": "在AI中心自動優化 →",
    "mktHighRoas": "偵測到高效渠道: {{channel}} ROAS {{roas}}x — 建議增加預算",
    "mktHighRoasSub": "在AI中心重新分配預算，預計收益增加23%",
    "mktBudgetAction": "AI預算優化 →",
    "crmChurn": "偵測到{{count}}名流失風險客戶 — 建議自動再激活活動",
    "crmVip": "建議向{{count}}名VIP客戶發送專屬優惠",
    "crmJourney": "立即在旅程構建器中開始自動旅程",
    "crmJourneyAction": "客戶旅程自動化 →",
    "ordersAiRun": "AI行銷中心最近運行: {{title}}",
    "ordersAiSub": "預計收益 ₩{{revenue}} · 運行時間 {{at}}",
    "ordersCampaignAction": "廣告活動狀態 →",
    "pnlLowMargin": "P&L利潤率 {{margin}}% — 建議AI成本優化 (目標: 20%+)",
    "pnlLowMarginSub": "透過優化廣告費用/平台佣金結構可改善利潤率",
    "pnlAiAction": "AI優化方案 →",
    "pnlHighMargin": "實現優秀利潤率 {{margin}}% — 是積極擴大預算的好時機",
    "pnlHighMarginSub": "AI中心建議向高收益渠道分配預算",
    "pnlBudgetAction": "擴大AI預算 →",
    "kpiRulesActive": "{{count}}個AI自動化規則正在實時監控KPI",
    "kpiRulesFired": "今日自動觸發{{count}}次 — 偵測到異常模式",
    "kpiAllNormal": "所有KPI在正常範圍內",
    "kpiRuleAction": "規則引擎詳情 →",
    "attrAiRun": "AI中心 運行{{count}}次渠道貢獻資料已反映在歸因分析中",
    "attrAiSub": "用5種歸因模型比較各渠道的實際貢獻度",
  },
};

const LOCALE_FILES = {
  ko: 'src/i18n/locales/ko.js',
  en: 'src/i18n/locales/en.js',
  ja: 'src/i18n/locales/ja.js',
  zh: 'src/i18n/locales/zh.js',
  de: 'src/i18n/locales/de.js',
  th: 'src/i18n/locales/th.js',
  vi: 'src/i18n/locales/vi.js',
  id: 'src/i18n/locales/id.js',
  'zh-TW': 'src/i18n/locales/zh-TW.js',
};

const VAR_NAMES = {
  ko:'ko', en:'en', ja:'ja', zh:'zh', de:'de', th:'th', vi:'vi', id:'id', 'zh-TW':'zhTW'
};

for (const [lang, trans] of Object.entries(BANNER_TRANSLATIONS)) {
  const fp = LOCALE_FILES[lang];
  const v = VAR_NAMES[lang];
  if (!fp || !fs.existsSync(fp)) continue;
  
  let c = fs.readFileSync(fp, 'utf8');
  
  // Check which keys are missing
  const missingEntries = Object.entries(trans).filter(([key]) => {
    return !c.includes('"'+key+'"') && !c.includes("'"+key+"'");
  });
  
  if (missingEntries.length > 0) {
    // Add as banner Object.assign before export default
    const patch = `\n${v}.banner = Object.assign(${v}.banner || {}, {\n` +
      missingEntries.map(([k, val]) => `    "${k}": "${val.replace(/"/g, '\\"')}"`).join(',\n') +
      '\n});\n';
    
    const expIdx = c.lastIndexOf(`\nexport default ${v}`);
    if (expIdx >= 0) {
      c = c.slice(0, expIdx) + patch + c.slice(expIdx);
      fs.writeFileSync(fp, c, 'utf8');
      console.log(`✅ ${lang}: ${missingEntries.length} banner keys added`);
    } else {
      console.log(`❌ ${lang}: export not found`);
    }
  } else {
    console.log(`⏭ ${lang}: all banner keys already present`);
  }
}
console.log('Done!');
