const fs = require('fs');

function appendTranslations() {
    const koPath = 'd:/project/GeniegoROI/frontend/src/i18n/locales/ko.js';
    const enPath = 'd:/project/GeniegoROI/frontend/src/i18n/locales/en.js';

    let koContent = fs.readFileSync(koPath, 'utf8');
    let enContent = fs.readFileSync(enPath, 'utf8');

    koContent = koContent.replace(/export default ko;[\s\n]*$/, '');
    enContent = enContent.replace(/export default en;[\s\n]*$/, '');

    const koMap = {
        "heroDesc": "어드밴스드 채널 KPI 관리 및 다면 평가",
        "achieved": "달성",
        "brandAwareness": "브랜드 인지도 강화",
        "brandAwarenessDesc": "노출, 도달, 브랜드 검색량 증대 목표",
        "webTraffic": "웹사이트 트래픽 극대화",
        "webTrafficDesc": "방문자 수 증대 및 세션 체류시간 확보 목표",
        "inquiriesPurchases": "문의 및 구매 전환 집중",
        "inquiriesPurchasesDesc": "CPA, 구매 전환율 최적화, 매출 증대",
        "bizGoalSetting": "1. 비즈니스 목표 설정",
        "selected": "✔ 선택됨",
        "clickSelect": "클릭하여 선택",
        "selectedGoals": "선택된 목표",
        "pleaseSelectGoal": "목표를 선택해 주세요.",
        "roleCaptureIntent": "고객 의도 포착 및 전환",
        "descCaptureIntent": "구매 의도가 높은 사용자를 타겟하여 직접적인 전환 발생",
        "roleBrandReach": "브랜드 도달 및 숏폼 인게이지먼트",
        "descBrandReach": "시각적 콘텐츠를 통한 잠재 고객 발굴 및 초기 인지도 형성",
        "roleInfoTrust": "정보 제공 및 신뢰도 구축",
        "pageViews": "페이지 뷰",
        "visitors": "방문자 수",
        "searchTraffic": "검색 유입",
        "descInfoTrust": "리뷰 및 전문 지식을 통한 고객 신뢰 획득 및 SEO 유입",
        "roleCustRel": "고객 관계 및 커뮤니티 육성",
        "postViews": "게시글 조회 수",
        "comments": "댓글/반응 수",
        "inquiries": "고객 문의 수",
        "newMembers": "신규 가입 수",
        "descCustRel": "기존 고객의 충성도 유지 및 자연스러운 입소문(UGC) 유도",
        "channelRoleDef": "2. 채널별 역할 정의",
        "coreKpis": "핵심 측정 지표",
        "hintCtr": "광고 클릭 비율",
        "hintConvRate": "방문자 대비 전환 비율",
        "hintCpa": "1회 전환(구매/문의)당 비용",
        "hintRoas": "광고비 대비 매출액 비율",
        "hintCpc": "1회 클릭당 비용",
        "targetSetup": "3. 채널별 개별 KPI 목표 설정",
        "snsKpiOverview": "SNS 매체 종합 성과",
        "allChannels": "모든 채널 합산",
        "snsKpiByChannel": "채널별 SNS KPI 상세",
        "contentKpi": "콘텐츠 채널 성과 (블로그/카페)",
        "contentImpressions": "콘텐츠 노출 규모",
        "siteTraffic": "사이트 트래픽 규모",
        "avgTime": "평균 체류 시간",
        "contentEngage": "콘텐츠 몰입도",
        "seoImpact": "검색엔진 최적화 유입",
        "monthlyTrend": "최근 14일 트렌드",
        "communityKpi": "커뮤니티 성과 및 가입자 지표",
        "contentInterest": "콘텐츠 관심도",
        "communityAct": "활성화 요인",
        "interestConv": "관심 전환율",
        "communityGrowth": "커뮤니티 성장률",
        "descCtr": "높을수록 광고 클릭 효율 좋음",
        "descConvRate": "최종 전환의 퍼센티지",
        "descCpa": "낮을수록 획득 비용 효율적",
        "descRoas": "광고비 투자 수익 배율",
        "descCpc": "클릭당 적정 비용",
        "targetVsActuals": "KPI 목표 대비 실제 달성률 추적",
        "overallAchieve": "종합 달성도 요약",
        "achievedOk": "목표 달성 완료",
        "belowTarget": "목표 미달성 (대응 필요)",
        "chkEff": "적정 효율",
        "chkCostPerf": "가성비 관리 필요",
        "chkImprove": "전환율 리스크",
        "monitorAi": "성과 모니터링 & AI 진단",
        "claudeAiTitle": "Claude AI KPI 심층 분석 리포트",
        "claudeAiDesc": "현재 집계된 모든 데이터를 종합하여 강점과 개선점을 리포트합니다.",
        "weeklyAi": "주간 요약 생성",
        "monthlyAi": "월간 요약 생성",
        "aiAnalyzing": "Claude AI가 다면 분석을 진행 중입니다...",
        "runAi": "AI 리포트 실행하기",
        "aiSummary": "AI 종합 요약",
        "strengths": "주요 강점 (Strengths)",
        "weaknesses": "취약점/리스크 (Weaknesses)",
        "improveRecs": "개선 권고사항",
        "weeklyAdTrend": "주간 주요 트렌드 (실시간 반영)",
        "checklist": "담당자 체크리스트",
        "aiHistoryList": "최근 AI 생성 기록 (최대 5건)",
        "noHistory": "아직 생성된 AI 리포트 기록이 없습니다.",
        "tabGoals": "목표 설정",
        "tabRoles": "채널 역할",
        "tabSetup": "세부 KPI 설정",
        "tabSns": "SNS KPI 심층 진단",
        "tabContent": "콘텐츠 KPI 집중",
        "tabCommunity": "커뮤니티 진단",
        "tabTargets": "목표 달성도 추적",
        "tabMonitor": "모니터링 & AI"
    };

    const enMap = {
        "heroDesc": "Advanced Channel KPI Management and Evaluation",
        "achieved": "Achieved",
        "brandAwareness": "Brand Awareness",
        "brandAwarenessDesc": "Maximize impressions, reach, and brand searches",
        "webTraffic": "Maximize Web Traffic",
        "webTrafficDesc": "Increase visitors and ensure longer session durations",
        "inquiriesPurchases": "Inquiries & Purchases Focus",
        "inquiriesPurchasesDesc": "Optimize CPA, Conversion Rate, and Revenue",
        "bizGoalSetting": "1. Business Goal Setting",
        "selected": "✔ Selected",
        "clickSelect": "Click to select",
        "selectedGoals": "Selected Goals",
        "pleaseSelectGoal": "Please select a goal.",
        "roleCaptureIntent": "Capture Intent & Convert",
        "descCaptureIntent": "Target high-intent users for direct conversions",
        "roleBrandReach": "Brand Reach & Engagement",
        "descBrandReach": "Discover prospects and build early awareness via visual content",
        "roleInfoTrust": "Provide Info & Build Trust",
        "pageViews": "Page Views",
        "visitors": "Visitors",
        "searchTraffic": "Search Traffic",
        "descInfoTrust": "Gain trust via reviews/knowledge and organic SEO",
        "roleCustRel": "Customer Relations & Community",
        "postViews": "Post Views",
        "comments": "Comments / Reactions",
        "inquiries": "Customer Inquiries",
        "newMembers": "New Members",
        "descCustRel": "Retain loyalty and induce organic Word-of-Mouth (UGC)",
        "channelRoleDef": "2. Channel Role Definition",
        "coreKpis": "Core Kpis",
        "hintCtr": "Ad Click Through Rate",
        "hintConvRate": "Conversion ratio per Visitors",
        "hintCpa": "Cost per Acquisition",
        "hintRoas": "Return on Ad Spend Ratio",
        "hintCpc": "Cost per Click",
        "targetSetup": "3. Setup Target KPI Per Channel",
        "snsKpiOverview": "SNS Total Performance",
        "allChannels": "All Channels Blended",
        "snsKpiByChannel": "SNS KPI Detail by Channel",
        "contentKpi": "Content Channel Perf. (Blog/Cafe)",
        "contentImpressions": "Content Impressions Volume",
        "siteTraffic": "Site Traffic Volume",
        "avgTime": "Avg. Duration Time",
        "contentEngage": "Content Engagement",
        "seoImpact": "SEO Organic Impact",
        "monthlyTrend": "Last 14 Days Trend",
        "communityKpi": "Community & Subscribers",
        "contentInterest": "Content Interest",
        "communityAct": "Community Activity",
        "interestConv": "Interest Conv.",
        "communityGrowth": "Community Growth",
        "descCtr": "Higher means Ad efficiency is good",
        "descConvRate": "Percentage of final purchase/action",
        "descCpa": "Lower is cost efficient",
        "descRoas": "Ad Investment ROI Multiplier",
        "descCpc": "Optimized Cost per Click",
        "targetVsActuals": "KPI Goal vs Actual Tracker",
        "overallAchieve": "Overall Milestone",
        "achievedOk": "Target Reached (OK)",
        "belowTarget": "Underperforming (Review Needed)",
        "chkEff": "Opt. Effic",
        "chkCostPerf": "Cost Focus Needed",
        "chkImprove": "Conv. Risk",
        "monitorAi": "Performance Monitor & AI",
        "claudeAiTitle": "Claude AI Depth Analysis Report",
        "claudeAiDesc": "Reviews all compiled data and reports on strengths and aspects needing improvement.",
        "weeklyAi": "Weekly AI Summary",
        "monthlyAi": "Monthly AI Summary",
        "aiAnalyzing": "Claude AI is running multi-dimensional analysis...",
        "runAi": "Run AI Report",
        "aiSummary": "AI Overall Summary",
        "strengths": "Main Strengths",
        "weaknesses": "Weaknesses/Risks",
        "improveRecs": "Improvement Recs.",
        "weeklyAdTrend": "Weekly Key Ad Trends",
        "checklist": "Manager Checklist",
        "aiHistoryList": "Recent AI Generated Reports (Max 5)",
        "noHistory": "No AI reports generated yet.",
        "tabGoals": "Set Goals",
        "tabRoles": "Channel Roles",
        "tabSetup": "Setup Targets",
        "tabSns": "SNS Depth",
        "tabContent": "Contents Depth",
        "tabCommunity": "Community Depth",
        "tabTargets": "Goal Trackers",
        "tabMonitor": "Monitor & AI"
    };

    const koAppend = '\\nko.channelKpi = ' + JSON.stringify(koMap, null, 4) + ';\\n\\nexport default ko;\\n';
    const enAppend = '\\nen.channelKpi = ' + JSON.stringify(enMap, null, 4) + ';\\n\\nexport default en;\\n';

    fs.writeFileSync(koPath, koContent + koAppend);
    fs.writeFileSync(enPath, enContent + enAppend);

    console.log("ChannelKpi translations safely added to locales.");
}

appendTranslations();
