// Supply Chain Builder - Phase 1: Generate i18n keys
const fs=require('fs');const P='src/i18n/locales/';
const KEYS={
pageTitle:'공급망 관리',pageSub:'공급망·물류 네트워크 최적화 및 실시간 모니터링',
tabTimeline:'공급 타임라인',tabSuppliers:'공급업체 관리',tabInventory:'재고 현황',
tabPO:'발주 관리',tabLeadTime:'리드타임 분석',tabRisk:'리스크 감지',
tabLandedCost:'원가 분석',tabGuide:'이용 가이드',
loading:'로딩 중...',noData:'데이터가 없습니다.',
kpiLines:'공급라인',kpiSuppliers:'공급업체',kpiHighRisk:'고위험',kpiAvgLead:'평균 리드타임',kpiTotalCost:'총 비용',kpiOnTime:'정시 납품률',
productName:'제품명',supplier:'공급업체',labelSku:'SKU',leadTime:'리드타임',days:'일',
country:'국가',category:'카테고리',delayRate:'지연율',contact:'연락처',reliability:'신뢰도',orderCount:'주문수',
addLine:'라인 추가',addSupplier:'공급업체 추가',register:'등록',cancel:'취소',confirmDelete:'삭제하시겠습니까?',
normal:'정상',highRisk:'고위험',supplyRisk:'공급 리스크',
contactSupplier:'공급업체 연락',altSupplierSearch:'대체 공급업체 검색',slackNotify:'Slack 알림',
autoRiskRules:'자동 리스크 규칙',addRule:'규칙 추가',ruleName:'규칙명',ruleAction:'조치',noRisk:'감지된 리스크가 없습니다.',
invTotal:'전체 재고',invTransit:'운송 중',invWarehouse:'창고',invSupplier:'공급업체',invQty:'수량',invStatus:'상태',invLocation:'위치',invUpdated:'업데이트',
tabPOTitle:'발주 관리',poCreate:'발주 생성',poSelectSupplier:'공급업체 선택',poUnitCost:'단가',poTotalCost:'총액',poNotes:'비고',poDate:'날짜',
poStatusDraft:'초안',poStatusPending:'승인 대기',poStatusApproved:'승인됨',poStatusShipped:'배송됨',poStatusReceived:'수령됨',poStatusCancelled:'취소됨',
lcProductCost:'제품 원가',lcShipping:'운송비',lcCustoms:'관세',lcInsurance:'보험료',lcHandling:'취급비',lcOther:'기타 비용',lcCalculate:'계산하기',lcResult:'분석 결과',lcDesc:'수입 제품의 총 착지 원가를 계산합니다.',
securityAlert:'보안 위협 감지',securityDesc:'악성 입력이 차단되었습니다.',securityDismiss:'확인 및 차단',
totalPO:'총 발주액',
guideTitle:'공급망 관리 이용 가이드',guideSub:'이 가이드를 따라하면 초보자도 공급망 관리 시스템을 완벽하게 활용할 수 있습니다.',
guideStepsTitle:'단계별 상세 가이드',guideTipsTitle:'전문가 팁',guideTabsTitle:'탭별 기능 안내',
guideBeginnerBadge:'초보자 가이드',guideTimeBadge:'10분 소요',guideLangBadge:'12개국 언어',
guideWhereToStart:'어디서 시작하나요?',
guideWhereToStartDesc:'1. 공급업체 관리 탭에서 거래처를 등록합니다. 2. 공급 타임라인 탭에서 공급 라인을 생성합니다. 3. 발주 관리 탭에서 발주서를 작성합니다. 4. 재고 현황 탭에서 재고를 모니터링합니다. 5. 리스크 감지 탭에서 자동 알림 규칙을 설정합니다.',
guideStep1Title:'공급업체 등록',guideStep1Desc:'공급업체 관리 탭에서 거래처 정보(회사명, 국가, 카테고리, 리드타임, 연락처)를 입력하여 공급업체를 등록합니다.',
guideStep2Title:'공급 라인 생성',guideStep2Desc:'공급 타임라인 탭에서 제품별 공급 라인을 생성하고 각 단계(발주→생산→검수→출하→운송→입고)를 추적합니다.',
guideStep3Title:'발주서 작성',guideStep3Desc:'발주 관리 탭에서 공급업체를 선택하고 제품, 수량, 단가를 입력하여 발주서를 생성합니다.',
guideStep4Title:'재고 모니터링',guideStep4Desc:'재고 현황 탭에서 전체 재고, 운송 중, 창고, 공급업체별 재고 수량을 실시간으로 확인합니다.',
guideStep5Title:'리드타임 분석',guideStep5Desc:'리드타임 분석 탭에서 각 공급 라인의 단계별 소요 시간과 지연율을 분석합니다.',
guideStep6Title:'리스크 감지 설정',guideStep6Desc:'리스크 감지 탭에서 고위험 공급 라인을 확인하고 자동 알림 규칙(지연 시 Slack 알림 등)을 설정합니다.',
guideStep7Title:'원가 분석 활용',guideStep7Desc:'원가 분석 탭에서 제품원가, 운송비, 관세, 보험료 등을 입력하여 총 착지 원가를 계산합니다.',
guideStep8Title:'공급업체 평가',guideStep8Desc:'공급업체의 신뢰도, 지연율, 주문 수를 기반으로 공급업체 성과를 평가하고 대체 업체를 검토합니다.',
guideStep9Title:'실시간 동기화 확인',guideStep9Desc:'모든 변경사항은 실시간으로 동기화됩니다. 발주 생성 시 재고 현황과 공급 타임라인이 자동 업데이트됩니다.',
guideStep10Title:'대시보드 종합 확인',guideStep10Desc:'대시보드의 KPI 카드(공급라인 수, 공급업체 수, 고위험 수, 평균 리드타임, 총 비용, 정시 납품률)를 정기적으로 확인합니다.',
guideStep11Title:'리스크 대응 프로세스',guideStep11Desc:'고위험 공급 라인 감지 시: ① 공급업체 연락 → ② 대체 공급업체 검색 → ③ Slack 팀 알림 → ④ 발주 조정 순서로 대응합니다.',
guideStep12Title:'원가 최적화 전략',guideStep12Desc:'정기적으로 원가 분석을 실행하여 운송비, 관세 비율을 비교하고 최적 물류 경로와 통관 전략을 수립합니다.',
guideStep13Title:'기간별 데이터 조회',guideStep13Desc:'타임라인, 재고, 발주 탭에서 기간 선택 기능을 사용하여 특정 기간의 데이터를 필터링하고 트렌드를 분석합니다.',
guideStep14Title:'보안 관리',guideStep14Desc:'시스템은 모든 입력에 대해 XSS, SQL Injection 등 보안 위협을 자동 감지하고 차단합니다. 보안 알림 발생 시 즉시 확인하세요.',
guideStep15Title:'최종 점검 및 루틴화',guideStep15Desc:'매주 월요일: KPI 확인 → 고위험 리뷰 → 발주 현황 점검 → 원가 분석. 이 루틴을 습관화하면 공급망 운영 효율이 극대화됩니다.',
guideTip1:'공급업체 신뢰도가 85% 미만이면 대체 공급업체를 반드시 확보해 두세요.',
guideTip2:'리드타임이 14일 이상인 라인은 안전 재고 수준을 높여야 합니다.',
guideTip3:'원가 분석 시 관세와 보험료를 누락하면 실제 원가와 큰 차이가 발생합니다.',
guideTip4:'고위험 라인이 3개 이상이면 공급망 다변화 전략을 즉시 검토하세요.',
guideTip5:'정시 납품률 95% 이상을 목표로 관리하면 재고 부족 리스크를 최소화할 수 있습니다.',
guideTabTimelineDesc:'공급 라인별 단계(발주→생산→검수→출하→운송→입고) 추적 및 진행 상태를 시각적으로 관리합니다.',
guideTabSuppliersDesc:'공급업체 등록, 평가(신뢰도/지연율), 연락처 관리를 수행합니다.',
guideTabInventoryDesc:'전체 재고를 위치별(창고/운송중/공급업체)로 분류하여 실시간 모니터링합니다.',
guideTabPODesc:'발주서 생성, 상태 추적(초안→승인→배송→수령), 비용 관리를 수행합니다.',
guideTabLeadTimeDesc:'공급 라인별 리드타임과 단계별 소요 시간을 분석합니다.',
guideTabRiskDesc:'고위험 공급 라인 감지, 자동 알림 규칙 설정, 대응 조치를 관리합니다.',
guideTabLandedCostDesc:'수입 제품의 제품원가+운송비+관세+보험료+취급비를 합산한 총 착지 원가를 계산합니다.',
guideTabGuideDesc:'초보자를 위한 상세 이용 가이드, 탭별 기능 설명, 전문가 팁을 제공합니다.',
guideReadyTitle:'준비 완료! 공급망 관리를 시작하세요',
guideReadyDesc:'위의 공급업체 관리 탭으로 이동하여 첫 공급업체를 등록해 보세요.',
guideFaqTitle:'자주 묻는 질문',
guideFaq1Q:'데이터가 표시되지 않습니다',guideFaq1A:'먼저 공급업체 관리 탭에서 공급업체를 등록하고, 공급 타임라인에서 공급 라인을 생성해야 합니다.',
guideFaq2Q:'리스크 감지가 작동하지 않습니다',guideFaq2A:'리스크 감지는 공급 라인의 risk 속성이 "high"로 설정된 경우에만 표시됩니다. 라인 추가 시 위험도를 설정하세요.',
guideFaq3Q:'발주서 상태를 변경하려면?',guideFaq3A:'현재 발주서 상태는 생성 시 자동으로 "초안"으로 설정됩니다. API를 통해 상태를 변경할 수 있습니다.',
guideFaq4Q:'원가 분석 결과가 0원입니다',guideFaq4A:'원가 분석 탭에서 각 비용 항목에 금액을 입력한 후 "계산하기" 버튼을 클릭해야 결과가 표시됩니다.',
guideFaq5Q:'실시간 동기화가 되지 않습니다',guideFaq5A:'시스템은 30초 간격으로 자동 동기화됩니다. 즉시 반영이 필요하면 페이지를 새로고침하세요.',
periodLabel:'기간',periodFrom:'시작일',periodTo:'종료일',
};
console.log('Korean keys generated:',Object.keys(KEYS).length);
// Write to a JSON for use by the main injector
fs.writeFileSync('sc_i18n_ko.json',JSON.stringify(KEYS,null,2),'utf8');
console.log('Done: sc_i18n_ko.json');
