const fs=require('fs'),p=require('path');
const D=p.join(__dirname,'src','i18n','locales');
const L={
en:{csFilterAll:'All',csStatusApproved:'Approved',csStatusReview:'In Review',csStatusActive:'Active',csConv:'Conv.',csUseCampaign:'Use in Campaign',csAiGenTitle:'AI Creative Generator',csAiGenDesc:'Select category and channel, and AI will auto-generate optimized ad creatives.',csStartFromSetup:'Start from Campaign Setup',csTypeCarousel:'Carousel Ad',csTypeCarouselDesc:'Multi-image slide composition',csTypeVideo:'Video Ad',csTypeVideoDesc:'15-60s short-form auto-creation',csTypeBanner:'Banner Ad',csTypeBannerDesc:'Responsive display banner',csTypeStory:'Story Ad',csTypeStoryDesc:'9:16 vertical fullscreen',csTypeShopping:'Shopping Ad',csTypeShoppingDesc:'Product feed DPA creative',csTypeMessage:'Message Ad',csTypeMessageDesc:'KakaoTalk·LINE templates',csPerfAvgCtr:'Avg CTR',csPerfAvgConv:'Avg Conv Rate',csPerfTotalConv:'Total Conversions',csPerfEffScore:'Creative Efficiency',csPerfTable:'Creative Performance Table',csColName:'Creative',csColFormat:'Format',csColPlatform:'Platform',csColStatus:'Status',csAiOptTitle:'AI Creative Optimization',csAiOpt1:'Video CTR is 1.5x higher than carousel. Increase video ratio.',csAiOpt2:'TikTok short-form has highest conversion. Create more 15s content.',csAiOpt3:'Creatives older than 2 weeks show ad fatigue. Replace them.',csBrandTitle:'Brand Asset Management',csBrandDesc:'Consistent creative management per brand guidelines',csUploadAsset:'Upload Asset',csPreview:'Preview',csDownload:'Download',csBrandCheck:'Brand Consistency Check',csColorComp:'Color Compliance',csFontComp:'Font Consistency',csLogoComp:'Logo Usage',csGuideViolation:'Guideline Violations',csUnitCount:'',csLastSync:'Last sync: just now',csFmtCarousel:'Carousel',csFmtVideo:'Video',csFmtBanner:'Banner',csFmtShort:'Short-form'},
ja:{csFilterAll:'全体',csStatusApproved:'承認',csStatusReview:'審査中',csStatusActive:'有効',csConv:'転換',csUseCampaign:'キャンペーンに活用',csAiGenTitle:'AIクリエイティブ生成',csAiGenDesc:'カテゴリとチャネルを選択すると、AIが最適な広告素材を自動生成します。',csStartFromSetup:'キャンペーン設定から開始',csTypeCarousel:'カルーセル広告',csTypeCarouselDesc:'複数画像のスライド構成',csTypeVideo:'動画広告',csTypeVideoDesc:'15～60秒ショート動画の自動制作',csTypeBanner:'バナー広告',csTypeBannerDesc:'レスポンシブディスプレイバナー',csTypeStory:'ストーリー広告',csTypeStoryDesc:'9:16縦型フルスクリーン',csTypeShopping:'ショッピング広告',csTypeShoppingDesc:'商品フィードDPA素材',csTypeMessage:'メッセージ広告',csTypeMessageDesc:'KakaoTalk·LINEテンプレート',csPerfAvgCtr:'平均CTR',csPerfAvgConv:'平均転換率',csPerfTotalConv:'総転換数',csPerfEffScore:'素材効率スコア',csPerfTable:'素材別パフォーマンス',csColName:'素材名',csColFormat:'フォーマット',csColPlatform:'プラットフォーム',csColStatus:'状態',csAiOptTitle:'AI素材最適化提案',csAiOpt1:'動画のCTRがカルーセルの1.5倍です。動画比率を拡大してください。',csAiOpt2:'TikTokショート素材の転換率が最高です。15秒以内の素材を追加制作してください。',csAiOpt3:'2週間以上の素材は広告疲労が上昇します。新しいクリエイティブに交換してください。',csBrandTitle:'ブランドアセット管理',csBrandDesc:'ブランドガイドラインに沿った一貫した素材管理',csUploadAsset:'アセットアップロード',csPreview:'プレビュー',csDownload:'ダウンロード',csBrandCheck:'ブランド一貫性検査',csColorComp:'カラー準拠率',csFontComp:'フォント一貫性',csLogoComp:'ロゴ使用準拠',csGuideViolation:'ガイドライン違反',csUnitCount:'件',csLastSync:'最終同期: たった今',csFmtCarousel:'カルーセル',csFmtVideo:'動画',csFmtBanner:'バナー',csFmtShort:'ショート'},
zh:{csFilterAll:'全部',csStatusApproved:'已批准',csStatusReview:'审核中',csStatusActive:'活跃',csConv:'转化',csUseCampaign:'用于活动',csAiGenTitle:'AI创意生成',csAiGenDesc:'选择类别和渠道，AI将自动生成最佳广告素材。',csStartFromSetup:'从活动设置开始',csTypeCarousel:'轮播广告',csTypeCarouselDesc:'多图滑动组合',csTypeVideo:'视频广告',csTypeVideoDesc:'15-60秒短视频自动制作',csTypeBanner:'横幅广告',csTypeBannerDesc:'响应式展示横幅',csTypeStory:'故事广告',csTypeStoryDesc:'9:16竖屏全屏素材',csTypeShopping:'购物广告',csTypeShoppingDesc:'商品信息流DPA素材',csTypeMessage:'消息广告',csTypeMessageDesc:'KakaoTalk·LINE模板',csPerfAvgCtr:'平均CTR',csPerfAvgConv:'平均转化率',csPerfTotalConv:'总转化数',csPerfEffScore:'素材效率分',csPerfTable:'素材效果表',csColName:'素材名',csColFormat:'格式',csColPlatform:'平台',csColStatus:'状态',csAiOptTitle:'AI素材优化建议',csAiOpt1:'视频CTR是轮播的1.5倍，请增加视频比例。',csAiOpt2:'TikTok短视频转化率最高，请制作更多15秒素材。',csAiOpt3:'超过2周的素材会产生疲劳，请更换新创意。',csBrandTitle:'品牌资产管理',csBrandDesc:'按品牌指南统一管理素材',csUploadAsset:'上传资产',csPreview:'预览',csDownload:'下载',csBrandCheck:'品牌一致性检查',csColorComp:'色彩合规率',csFontComp:'字体一致性',csLogoComp:'Logo使用合规',csGuideViolation:'违规项',csUnitCount:'项',csLastSync:'最后同步: 刚刚',csFmtCarousel:'轮播',csFmtVideo:'视频',csFmtBanner:'横幅',csFmtShort:'短视频'},
'zh-TW':{csFilterAll:'全部',csStatusApproved:'已核准',csStatusReview:'審核中',csStatusActive:'啟用',csConv:'轉換',csUseCampaign:'用於活動',csAiGenTitle:'AI創意生成',csAiGenDesc:'選擇類別和頻道，AI將自動生成最佳廣告素材。',csStartFromSetup:'從活動設定開始',csTypeCarousel:'輪播廣告',csTypeCarouselDesc:'多圖滑動組合',csTypeVideo:'影片廣告',csTypeVideoDesc:'15-60秒短影片自動製作',csTypeBanner:'橫幅廣告',csTypeBannerDesc:'響應式展示橫幅',csTypeStory:'限時動態廣告',csTypeStoryDesc:'9:16直式全螢幕素材',csTypeShopping:'購物廣告',csTypeShoppingDesc:'商品動態廣告素材',csTypeMessage:'訊息廣告',csTypeMessageDesc:'KakaoTalk·LINE範本',csPerfAvgCtr:'平均CTR',csPerfAvgConv:'平均轉換率',csPerfTotalConv:'總轉換數',csPerfEffScore:'素材效率分',csPerfTable:'素材績效表',csColName:'素材名',csColFormat:'格式',csColPlatform:'平台',csColStatus:'狀態',csAiOptTitle:'AI素材最佳化建議',csAiOpt1:'影片CTR是輪播的1.5倍，請增加影片比例。',csAiOpt2:'TikTok短影片轉換率最高，請製作更多15秒素材。',csAiOpt3:'超過2週的素材會產生疲勞，請更換新創意。',csBrandTitle:'品牌資產管理',csBrandDesc:'依品牌指南統一管理素材',csUploadAsset:'上傳資產',csPreview:'預覽',csDownload:'下載',csBrandCheck:'品牌一致性檢查',csColorComp:'色彩合規率',csFontComp:'字型一致性',csLogoComp:'Logo使用合規',csGuideViolation:'違規項',csUnitCount:'項',csLastSync:'最後同步: 剛剛',csFmtCarousel:'輪播',csFmtVideo:'影片',csFmtBanner:'橫幅',csFmtShort:'短影片'}
};
for(const[lang,keys]of Object.entries(L)){
  const f=p.join(D,lang+'.js');let c=fs.readFileSync(f,'utf8');
  if(c.includes('"csFilterAll"')){console.log('[SKIP]'+lang);continue;}
  const a=c.indexOf('"csSystemOk"');
  if(a===-1){
    const b=c.indexOf('"csTabGallery"');
    if(b===-1){console.log('[NO ANCHOR]'+lang);continue;}
    const line=c.lastIndexOf('\n',b);
    const ins=Object.entries(keys).map(([k,v])=>`    "${k}": "${v.replace(/"/g,'\\"')}"`).join(',\n')+',\n';
    c=c.slice(0,line+1)+ins+c.slice(line+1);
  } else {
    const eol=c.indexOf('\n',a);
    const ins=',\n'+Object.entries(keys).map(([k,v])=>`    "${k}": "${v.replace(/"/g,'\\"')}"`).join(',\n');
    c=c.slice(0,eol)+ins+c.slice(eol);
  }
  fs.writeFileSync(f,c,'utf8');
  console.log('[OK]'+lang+': '+Object.keys(keys).length);
}
