const fs=require('fs'),p=require('path');
const D=p.join(__dirname,'src','i18n','locales');
const L={
de:{csFilterAll:'Alle',csStatusApproved:'Genehmigt',csStatusReview:'In Prüfung',csStatusActive:'Aktiv',csConv:'Konv.',csUseCampaign:'Für Kampagne nutzen',csAiGenTitle:'AI Kreativ-Generator',csAiGenDesc:'Wählen Sie Kategorie und Kanal, AI generiert optimale Werbemittel.',csStartFromSetup:'Von Kampagnen-Setup starten',csTypeCarousel:'Karussell-Anzeige',csTypeCarouselDesc:'Multi-Bild-Slide-Komposition',csTypeVideo:'Video-Anzeige',csTypeVideoDesc:'15-60s Kurzform Auto-Erstellung',csTypeBanner:'Banner-Anzeige',csTypeBannerDesc:'Responsive Display-Banner',csTypeStory:'Story-Anzeige',csTypeStoryDesc:'9:16 vertikaler Vollbildschirm',csTypeShopping:'Shopping-Anzeige',csTypeShoppingDesc:'Produkt-Feed DPA',csTypeMessage:'Nachrichten-Anzeige',csTypeMessageDesc:'KakaoTalk·LINE Vorlagen',csPerfAvgCtr:'Durchschn. CTR',csPerfAvgConv:'Durchschn. Konv.-Rate',csPerfTotalConv:'Gesamtkonversionen',csPerfEffScore:'Kreativ-Effizienz',csPerfTable:'Kreativ-Performance-Tabelle',csColName:'Kreativ',csColFormat:'Format',csColPlatform:'Plattform',csColStatus:'Status',csAiOptTitle:'AI Kreativ-Optimierung',csAiOpt1:'Video-CTR ist 1,5x höher als Karussell. Videoanteil erhöhen.',csAiOpt2:'TikTok Kurzform hat höchste Konversion. Mehr 15s Inhalte erstellen.',csAiOpt3:'Kreative über 2 Wochen zeigen Ermüdung. Bitte ersetzen.',csBrandTitle:'Marken-Asset-Verwaltung',csBrandDesc:'Konsistentes Kreativ-Management nach Markenrichtlinien',csUploadAsset:'Asset hochladen',csPreview:'Vorschau',csDownload:'Download',csBrandCheck:'Markenkonsistenz-Prüfung',csColorComp:'Farbkonformität',csFontComp:'Schriftkonsistenz',csLogoComp:'Logo-Nutzung',csGuideViolation:'Richtlinienverstöße',csUnitCount:'',csLastSync:'Letzte Sync: gerade eben',csFmtCarousel:'Karussell',csFmtVideo:'Video',csFmtBanner:'Banner',csFmtShort:'Kurzform'},
id:{csFilterAll:'Semua',csStatusApproved:'Disetujui',csStatusReview:'Dalam Tinjauan',csStatusActive:'Aktif',csConv:'Konversi',csUseCampaign:'Gunakan di Kampanye',csAiGenTitle:'Generator Kreatif AI',csAiGenDesc:'Pilih kategori dan saluran, AI akan otomatis menghasilkan materi iklan optimal.',csStartFromSetup:'Mulai dari Pengaturan Kampanye',csTypeCarousel:'Iklan Carousel',csTypeCarouselDesc:'Komposisi slide multi-gambar',csTypeVideo:'Iklan Video',csTypeVideoDesc:'Pembuatan otomatis video pendek 15-60 detik',csTypeBanner:'Iklan Banner',csTypeBannerDesc:'Banner display responsif',csTypeStory:'Iklan Story',csTypeStoryDesc:'9:16 layar penuh vertikal',csTypeShopping:'Iklan Belanja',csTypeShoppingDesc:'Materi DPA berbasis feed produk',csTypeMessage:'Iklan Pesan',csTypeMessageDesc:'Template KakaoTalk·LINE',csPerfAvgCtr:'Rata-rata CTR',csPerfAvgConv:'Rata-rata Tingkat Konversi',csPerfTotalConv:'Total Konversi',csPerfEffScore:'Skor Efisiensi Kreatif',csPerfTable:'Tabel Performa Kreatif',csColName:'Kreatif',csColFormat:'Format',csColPlatform:'Platform',csColStatus:'Status',csAiOptTitle:'Optimasi Kreatif AI',csAiOpt1:'CTR video 1,5x lebih tinggi dari carousel. Tingkatkan rasio video.',csAiOpt2:'Video pendek TikTok memiliki konversi tertinggi. Buat lebih banyak konten 15 detik.',csAiOpt3:'Kreatif lebih dari 2 minggu menunjukkan kelelahan iklan. Ganti dengan yang baru.',csBrandTitle:'Manajemen Aset Merek',csBrandDesc:'Manajemen kreatif konsisten sesuai pedoman merek',csUploadAsset:'Unggah Aset',csPreview:'Pratinjau',csDownload:'Unduh',csBrandCheck:'Pemeriksaan Konsistensi Merek',csColorComp:'Kepatuhan Warna',csFontComp:'Konsistensi Font',csLogoComp:'Penggunaan Logo',csGuideViolation:'Pelanggaran Pedoman',csUnitCount:'',csLastSync:'Sinkronisasi terakhir: baru saja',csFmtCarousel:'Carousel',csFmtVideo:'Video',csFmtBanner:'Banner',csFmtShort:'Short-form'},
th:{csFilterAll:'ทั้งหมด',csStatusApproved:'อนุมัติ',csStatusReview:'กำลังตรวจสอบ',csStatusActive:'ใช้งาน',csConv:'การแปลง',csUseCampaign:'ใช้ในแคมเปญ',csAiGenTitle:'AI สร้างครีเอทีฟ',csAiGenDesc:'เลือกหมวดหมู่และช่องทาง AI จะสร้างสื่อโฆษณาที่เหมาะสมโดยอัตโนมัติ',csStartFromSetup:'เริ่มจากการตั้งค่าแคมเปญ',csTypeCarousel:'โฆษณาแบบหมุน',csTypeCarouselDesc:'การจัดวางภาพหลายภาพแบบสไลด์',csTypeVideo:'โฆษณาวิดีโอ',csTypeVideoDesc:'สร้างวิดีโอสั้น 15-60 วินาทีอัตโนมัติ',csTypeBanner:'โฆษณาแบนเนอร์',csTypeBannerDesc:'แบนเนอร์ดิสเพลย์แบบตอบสนอง',csTypeStory:'โฆษณาสตอรี่',csTypeStoryDesc:'แนวตั้ง 9:16 เต็มจอ',csTypeShopping:'โฆษณาช้อปปิ้ง',csTypeShoppingDesc:'สื่อ DPA จากฟีดสินค้า',csTypeMessage:'โฆษณาข้อความ',csTypeMessageDesc:'เทมเพลต KakaoTalk·LINE',csPerfAvgCtr:'CTR เฉลี่ย',csPerfAvgConv:'อัตราการแปลงเฉลี่ย',csPerfTotalConv:'การแปลงทั้งหมด',csPerfEffScore:'คะแนนประสิทธิภาพครีเอทีฟ',csPerfTable:'ตารางประสิทธิภาพครีเอทีฟ',csColName:'ครีเอทีฟ',csColFormat:'รูปแบบ',csColPlatform:'แพลตฟอร์ม',csColStatus:'สถานะ',csAiOptTitle:'การเพิ่มประสิทธิภาพครีเอทีฟ AI',csAiOpt1:'CTR ของวิดีโอสูงกว่าแบบหมุน 1.5 เท่า เพิ่มสัดส่วนวิดีโอ',csAiOpt2:'วิดีโอสั้น TikTok มีการแปลงสูงสุด สร้างเนื้อหา 15 วินาทีเพิ่ม',csAiOpt3:'ครีเอทีฟที่เก่ากว่า 2 สัปดาห์เกิดความเบื่อหน่าย ควรเปลี่ยนใหม่',csBrandTitle:'การจัดการสินทรัพย์แบรนด์',csBrandDesc:'การจัดการครีเอทีฟที่สอดคล้องตามแนวทางแบรนด์',csUploadAsset:'อัปโหลดสินทรัพย์',csPreview:'ดูตัวอย่าง',csDownload:'ดาวน์โหลด',csBrandCheck:'ตรวจสอบความสอดคล้องของแบรนด์',csColorComp:'การปฏิบัติตามสี',csFontComp:'ความสอดคล้องของฟอนต์',csLogoComp:'การใช้โลโก้',csGuideViolation:'การละเมิดแนวทาง',csUnitCount:'รายการ',csLastSync:'ซิงค์ล่าสุด: เมื่อสักครู่',csFmtCarousel:'แบบหมุน',csFmtVideo:'วิดีโอ',csFmtBanner:'แบนเนอร์',csFmtShort:'สั้น'},
vi:{csFilterAll:'Tất cả',csStatusApproved:'Đã duyệt',csStatusReview:'Đang xem xét',csStatusActive:'Đang hoạt động',csConv:'Chuyển đổi',csUseCampaign:'Dùng cho chiến dịch',csAiGenTitle:'Tạo sáng tạo AI',csAiGenDesc:'Chọn danh mục và kênh, AI sẽ tự động tạo tài liệu quảng cáo tối ưu.',csStartFromSetup:'Bắt đầu từ cài đặt chiến dịch',csTypeCarousel:'Quảng cáo băng chuyền',csTypeCarouselDesc:'Bố cục trượt nhiều hình ảnh',csTypeVideo:'Quảng cáo video',csTypeVideoDesc:'Tạo tự động video ngắn 15-60 giây',csTypeBanner:'Quảng cáo banner',csTypeBannerDesc:'Banner hiển thị đáp ứng',csTypeStory:'Quảng cáo story',csTypeStoryDesc:'Toàn màn hình dọc 9:16',csTypeShopping:'Quảng cáo mua sắm',csTypeShoppingDesc:'Tài liệu DPA từ nguồn sản phẩm',csTypeMessage:'Quảng cáo tin nhắn',csTypeMessageDesc:'Mẫu KakaoTalk·LINE',csPerfAvgCtr:'CTR trung bình',csPerfAvgConv:'Tỷ lệ chuyển đổi TB',csPerfTotalConv:'Tổng chuyển đổi',csPerfEffScore:'Điểm hiệu quả sáng tạo',csPerfTable:'Bảng hiệu suất sáng tạo',csColName:'Sáng tạo',csColFormat:'Định dạng',csColPlatform:'Nền tảng',csColStatus:'Trạng thái',csAiOptTitle:'Tối ưu sáng tạo AI',csAiOpt1:'CTR video cao gấp 1,5 lần so với băng chuyền. Tăng tỷ lệ video.',csAiOpt2:'Video ngắn TikTok có tỷ lệ chuyển đổi cao nhất. Tạo thêm nội dung 15 giây.',csAiOpt3:'Sáng tạo hơn 2 tuần bị mệt mỏi quảng cáo. Hãy thay thế.',csBrandTitle:'Quản lý tài sản thương hiệu',csBrandDesc:'Quản lý sáng tạo nhất quán theo hướng dẫn thương hiệu',csUploadAsset:'Tải lên tài sản',csPreview:'Xem trước',csDownload:'Tải xuống',csBrandCheck:'Kiểm tra tính nhất quán thương hiệu',csColorComp:'Tuân thủ màu sắc',csFontComp:'Nhất quán phông chữ',csLogoComp:'Sử dụng logo',csGuideViolation:'Vi phạm hướng dẫn',csUnitCount:'',csLastSync:'Đồng bộ gần nhất: vừa xong',csFmtCarousel:'Băng chuyền',csFmtVideo:'Video',csFmtBanner:'Banner',csFmtShort:'Ngắn'}
};
for(const[lang,keys]of Object.entries(L)){
  const f=p.join(D,lang+'.js');let c=fs.readFileSync(f,'utf8');
  if(c.includes('"csFilterAll"')){console.log('[SKIP]'+lang);continue;}
  const a=c.indexOf('"csSystemOk"');
  if(a===-1){const b=c.indexOf('"csTabGallery"');if(b===-1){console.log('[NO]'+lang);continue;}const line=c.lastIndexOf('\n',b);const ins=Object.entries(keys).map(([k,v])=>`    "${k}": "${v.replace(/"/g,'\\"')}"`).join(',\n')+',\n';c=c.slice(0,line+1)+ins+c.slice(line+1);}
  else{const eol=c.indexOf('\n',a);const ins=',\n'+Object.entries(keys).map(([k,v])=>`    "${k}": "${v.replace(/"/g,'\\"')}"`).join(',\n');c=c.slice(0,eol)+ins+c.slice(eol);}
  fs.writeFileSync(f,c,'utf8');console.log('[OK]'+lang+': '+Object.keys(keys).length);
}
