const fs = require('fs');
let c = fs.readFileSync('src/pages/InfluencerUGC.jsx', 'utf8');

const replacements = [
  // Creator names
  ['테크 언박싱', 'Tech Unboxing'],
  ['데일리 가젯', 'Daily Gadget'],
  ['테크바이브', 'TechVibe'],
  ['뷰티 테크 지나', 'Beauty Tech Jina'],
  ['IT 꿀팁 박해진', 'IT Tips Haejin'],
  // Content titles (in content array)
  ['WH-1000XM5 리뷰', 'WH-1000XM5 Review'],
  ['RGB 키보드 비교', 'RGB Keyboard Comparison'],
  ['4K 웹캠 언박싱', '4K Webcam Unboxing'],
  ['홈오피스 셋업', 'Home Office Setup'],
  ['노이캔 헤드폰 챌린지', 'Noise-Cancelling Headphone Challenge'],
  ['USB허브 꿀팁', 'USB Hub Tips'],
  ['뷰티 디바이스 언박싱', 'Beauty Device Unboxing'],
  ['키보드 10종 비교 리뷰', '10 Keyboard Comparison Review'],
  ['마우스 추천 영상', 'Mouse Recommendation Video'],
  // Region data
  ["{ region: '서울'", "{ region: 'Seoul'"],
  ["{ region: '경기'", "{ region: 'Gyeonggi'"],
  ["{ region: '부산'", "{ region: 'Busan'"],
  ["{ region: '대전'", "{ region: 'Daejeon'"],
  ["{ region: '인천'", "{ region: 'Incheon'"],
  ["'서울/경기': 62", "'Seoul/Gyeonggi': 62"],
  ["'부산/경남': 16", "'Busan/Gyeongnam': 16"],
  ["'기타': 22", "'Other': 22"],
  // Mock reviews (same as ReviewsUGC) 
  ['노이즈캔슬링 헤드폰 XM5', 'Noise-Cancelling Headphones XM5'],
  ['RGB 기계식 키보드 MX', 'RGB Mechanical Keyboard MX'],
  ['USB4 7포트 허브 Pro', 'USB4 7-Port Hub Pro'],
  ['게이밍 마우스 Pro X', 'Gaming Mouse Pro X'],
  ['포터블 충전기 20K', 'Portable Charger 20K'],
  ['음질이 정말 훌륭합니다. 노이즈캔슬링 최고!', 'Exceptional sound quality. Best noise cancelling!'],
  ['타건감 좋고 RGB도 예쁜. 배송 빠름.', 'Great typing feel and beautiful RGB. Fast delivery.'],
  ['4K 모니터 연결 시 화면 꺜박임 발생. AS 대기 중.', 'Screen flickering when connecting 4K monitor. Waiting for support.'],
  ['그립감은 좋은데 DPI 소프트웨어가 불안정함.', 'Good grip but DPI software is unstable.'],
  ['박스 훼손된 쇼로 배송. 환불 요청 중.', 'Package arrived damaged. Refund requested.'],
  ['사무실에서 쓰기 딩 좋은 키보드. 소음도 적당.', 'Perfect for office use. Just the right amount of noise.'],
  ['PD 45W 지원으로 노트북까지 빠르게 충전됨.', 'PD 45W support charges even laptops quickly.'],
  ['클릭 반응이 두달 만에 이상해짘. 내구성 문제 의심.', 'Click response started failing after 2 months. Possible durability issue.'],
  ["category: \"음질\"", 'category: "Sound Quality"'],
  ["category: \"타건감\"", 'category: "Typing Feel"'],
  ["category: \"호환성\"", 'category: "Compatibility"'],
  ["category: \"소프트웨어\"", 'category: "Software"'],
  ["category: \"배송\"", 'category: "Shipping"'],
  ["category: \"소음\"", 'category: "Noise Level"'],
  ["category: \"성능\"", 'category: "Performance"'],
  ["category: \"내구성\"", 'category: "Durability"'],
  // Neg keywords in InfluencerUGC
  ['배송 지연', 'Shipping Delay'],
  ['호환성 문제', 'Compatibility Issue'],
  ['내구성', 'Durability'],
  ['소프트웨어 버그', 'Software Bug'],
  ['AS 불만', 'Support Complaint'],
  // Sentiment labels
  ['const SENTIMENT_LABEL = { positive: "긍정", neutral: "중립", negative: "부정" };', 'const SENTIMENT_LABEL = { positive: "Positive", neutral: "Neutral", negative: "Negative" };'],
  // Tab comment headers
  ['TAB 1: 크리에이터 정체성 통합', 'TAB 1: Creator Identity Integration'],
  ['TAB 2: 계약 관리', 'TAB 2: Contract Management'],
  ['TAB 3: 정산 관리 + 자동 검증', 'TAB 3: Settlement Management + Auto Verification'],
  ['TAB 4: ROI 랭킹 + 콘텐츠 재활용', 'TAB 4: ROI Ranking + Content Reuse'],
  // IdentityTab UI
  ['총 크리에이터', 'Total Creators'],
  ['중복 의심', 'Duplicate Suspected'],
  ['다중 이메일/핸들', 'Multiple Email/Handle'],
  ['미인증 채널', 'Unverified Channels'],
  ['연결된 플랫폼', 'Connected Platforms'],
  ['⚠ 중복/변형 핸들 감지 —', '⚠ Duplicate/variant handle detected —'],
  ['검토 필요', 'Review Required'],
  ['⚠ 중복의심', '⚠ Duplicate Suspected'],
  ['▲ 접기', '▲ Collapse'],
  ['▼ 채널 상세', '▼ Channel Details'],
  ['🔗 통합 처리', '🔗 Merge'],
  ['✓ 인증', '✓ Verified'],
  ['미인증', 'Unverified'],
  ['통합 이메일 목록', 'Unified Email List'],
  ['⚠ 이메일 2개 이상 — 동일인 여부 확인 필요', '⚠ Multiple emails detected — please verify same person'],
  // ContractTab UI
  ['계약 활성', 'Active Contracts'],
  ['e-Sign 대기', 'e-Sign Pending'],
  ['화이트리스트 만료 임박', 'Whitelist Expiring Soon'],
  ['90일 이내', 'Within 90 days'],
  ['화이트리스트 만료됨', 'Whitelist Expired'],
  ['화이트리스트', 'Whitelist'],
  ['e-Sign 아직 미완료 (계약 발효 불가)', '— e-Sign not completed yet (contract not effective)'],
  ['서명 요청 재발송', 'Resend Signature Request'],
  ['화이트리스트 만료 (', 'Whitelist expired ('],
  [') · 광고 집행 즉시 중단 필요', ') · Stop ad execution immediately'],
  ['권리 갱신', 'Renew Rights'],
  ['📋 계약 목록', '📋 Contract List'],
  ['크리에이터', 'Creator'],
  ['계약 유형', 'Contract Type'],
  ['고정 단가', 'Fixed Fee'],
  ['성과 요율', 'Performance Rate'],
  ['권리 범위', 'Rights Scope'],
  ['계약 기간', 'Contract Period'],
  ['📣 광고 전환(Whitelisting) 가능 구간', '📣 Ad Conversion (Whitelisting) Window'],
  ['화이트리스트 허용 기간 내 광고 집행 가능 크리에이터 · 만료 전 적극 활용 권장', 'Creators available for ad execution within whitelist period · Active use before expiry recommended'],
  ['만료됨', 'Expired'],
  ['일 남음', ' days left'],
  ['까지', ' until'],
  ['📝 계약 상세 —', '📝 Contract Details —'],
  ['계약 기준 합계', 'Contract Total'],
  ['성과 지급 (', 'Performance Payment ('],
  ['없음', 'None'],
  ['허용', 'Allowed'],
  ['고정', 'Fixed'],
  ['성과형', 'Performance'],
  ['고정+성과', 'Fixed+Perf'],
  ['✓ 서명완료', '✓ Signed'],
  ['⏳ 대기', '⏳ Pending'],
  ['✗ 거절', '✗ Rejected'],
  ['상세', 'Details'],
  ['닫기', 'Close'],
  ['📄 계약서 다운로드', '📄 Download Contract'],
  // SettleTab UI
  ['총 지급 예정', 'Total Payable'],
  ['미지급', 'Unpaid'],
  ['과지급 탐지', 'Overpayment Detected'],
  ['이상 건수 합계', 'Total Anomalies'],
  ['const STATUS_LABEL = { paid: "완료", partial: "일부지급", unpaid: "미지급", overpaid: "과지급" };',
   'const STATUS_LABEL = { paid: "Paid", partial: "Partial", unpaid: "Unpaid", overpaid: "Overpaid" };'],
  ['🟣 과지급', '🟣 Overpaid'],
  ['🔴 미지급/부분', '🔴 Unpaid/Partial'],
  ['계약 기준', 'Per contract'],
  ['실지급', 'Actual Paid'],
  ['차이', 'Difference'],
  ['환수 처리', 'Recover'],
  ['추가 지급', 'Pay Remaining'],
  ['📋 정산 명세 (자동 검증)', '📋 Settlement Details (Auto-verified)'],
  ['정산 기간', 'Period'],
  ['계약 기준금', 'Contract Amount'],
  ['실지급액', 'Actual Paid'],
  ['차이 (과/미)', 'Diff (Over/Under)'],
  ['상태', 'Status'],
  ['증빙 서류', 'Documents'],
  ['미첨부', 'No docs'],
  ['일치', 'Match'],
  ['정산서', 'Statement'],
  ['💰 정산서 —', '💰 Settlement —'],
  ['계약 금액 (고정)', 'Contract Amount (Fixed)'],
  ['사업소득세 (3.3%)', 'Business Income Tax (3.3%)'],
  ['지방소득세 (0.33%)', 'Local Income Tax (0.33%)'],
  ['실 지급액', 'Net Payable'],
  ['실지급 ', 'Paid: '],
  ['계약기준 ', 'Contract: '],
  ['✓ 정상', '✓ Match'],
  ['⚠ 과지급', '⚠ Overpaid'],
  ['⚠ 미지급/부분지급', '⚠ Unpaid/Partial'],
  ['첨부 서류:', 'Documents:'],
  ['📥 정산서 다운로드', '📥 Download Settlement'],
  // ROITab UI
  ['🏆 크리에이터 ROI 랭킹', '🏆 Creator ROI Ranking'],
  ['누적 조회', 'Total Views'],
  ['기여 주문', 'Attributed Orders'],
  ['기여 매출', 'Attributed Revenue'],
  ['계약비용', 'Contract Cost'],
  ['조회→주문', 'View→Order'],
  ['뷰/건', ' views/order'],
  ['👁 고조회 ↓매출', '👁 High View ↓Sales'],
  ['👁 고조회 / 저매출 케이스 분리 분석', '👁 High Views / Low Sales Case Analysis'],
  ['조회수 200K↑ · 주문 50건↓ — 콘텐츠 최적화 또는 랜딩 페이지 개선 필요', 'Views 200K+ · Orders <50 — Content optimization or landing page improvement needed'],
  ['조회수', 'Views'],
  ['주문', 'Orders'],
  ['전환율', 'Conv. Rate'],
  ['🔄 콘텐츠 재활용 최적 후보 추천 (Ads / Product Page)', '🔄 Content Reuse Best Candidates (Ads / Product Page)'],
  ['참여율 5%↑ + 주문 50건↑ 콘텐츠 · 화이트리스트 상태 포함', 'Engagement 5%+ and 50+ orders · Including whitelist status'],
  ['참여율', 'Engagement'],
  ['📣 광고 집행 가능', '📣 Ad Ready'],
  ['🚫 권리 확인 필요', '🚫 Check Rights'],
  // Main page tab labels and hero
  ['📊 인플루언서 UGC 마케팅', '📊 Influencer & UGC Marketing'],
  ['크리에이터 정체성', 'Creator Identity'],
  ['계약 관리', 'Contracts'],
  ['정산 관리', 'Settlement'],
  ['ROI/재활용', 'ROI/Reuse'],
  ['UGC 리뷰', 'UGC Reviews'],
  // Helper labels in demographics
  ['서울', 'Seoul'],
  ['경기', 'Gyeonggi'],
  ['부산', 'Busan'],
  ['대전', 'Daejeon'],
  ['인천', 'Incheon'],
];

for (const [from, to] of replacements) {
  c = c.split(from).join(to);
}

fs.writeFileSync('src/pages/InfluencerUGC.jsx', c, 'utf8');
console.log('InfluencerUGC.jsx done, size:', c.length);
