const fs=require('fs'),path=require('path'),DIR=path.join(__dirname,'src','i18n','locales');
// Fix tabCreative and tabGuide + AI guide steps for all languages
const FIXES={
es:{tabCreative:"Creativo",tabGuide:"Guía de Uso",aiGuideStep1Title:"Seleccionar Plataforma",aiGuideStep1Desc:"Entre en la pestaña AI Design y seleccione la plataforma destino.",aiGuideStep2Title:"Elegir Tema",aiGuideStep2Desc:"Seleccione un tema creativo acorde a sus objetivos de campaña.",aiGuideStep3Title:"Escribir Contenido",aiGuideStep3Desc:"Ingrese titular, subtítulo, prompt IA y texto del botón CTA.",aiGuideStep4Title:"Configurar Interactivo",aiGuideStep4Desc:"Seleccione tipos de anuncios interactivos como ruleta o raspadita.",aiGuideStep5Title:"Establecer Período",aiGuideStep5Desc:"Configure fecha de inicio, fin y zona horaria para campañas limitadas.",aiGuideStep6Title:"Generar Creativo",aiGuideStep6Desc:"Revise el resumen y haga clic en Generar.",aiGuideStep7Title:"Vista Previa",aiGuideStep7Desc:"Revise el creativo generado en la vista previa.",aiGuideStep8Title:"Descargar",aiGuideStep8Desc:"Descargue como archivo PNG.",aiGuideStep9Title:"Iterar y Refinar",aiGuideStep9Desc:"Modifique y regenere si es necesario.",aiGuideStep10Title:"Desplegar",aiGuideStep10Desc:"Suba los creativos a las plataformas publicitarias.",guideStep1Title:"Conectar Canales",guideStep1Desc:"Conecte sus canales publicitarios en el Hub de Integración.",guideStep2Title:"Configurar Campañas",guideStep2Desc:"Configure campañas con objetivos y presupuesto.",guideStep3Title:"Monitorear Rendimiento",guideStep3Desc:"Revise métricas de rendimiento en tiempo real.",guideStep4Title:"Optimizar ROAS",guideStep4Desc:"Analice ROAS y optimice la distribución de presupuesto.",guideStep5Title:"Análisis Creativo",guideStep5Desc:"Compare el rendimiento de diferentes creativos.",guideStep6Title:"Reportes",guideStep6Desc:"Genere reportes detallados de rendimiento.",guideTip1:"ROAS superior a 2.0x indica buena rentabilidad.",guideTip2:"Revise la tasa de liquidación efectiva regularmente.",guideTip3:"Enfoque presupuesto en SKUs con margen superior al 20%.",guideTip4:"Optimice creativos según rendimiento por canal.",guideTip5:"Monitoree la retención de cohorte D+90."},
fr:{tabCreative:"Créatif",tabGuide:"Guide",aiGuideStep1Title:"Sélectionner la Plateforme",aiGuideStep1Desc:"Entrez dans l'onglet AI Design et choisissez la plateforme cible.",aiGuideStep2Title:"Choisir le Thème",aiGuideStep2Desc:"Sélectionnez un thème créatif adapté à vos objectifs.",aiGuideStep3Title:"Rédiger le Contenu",aiGuideStep3Desc:"Saisissez le titre, sous-titre, prompt IA et texte CTA.",aiGuideStep4Title:"Paramétrer l'Interactif",aiGuideStep4Desc:"Choisissez les types d'annonces interactives.",aiGuideStep5Title:"Définir la Période",aiGuideStep5Desc:"Configurez les dates et le fuseau horaire.",aiGuideStep6Title:"Générer",aiGuideStep6Desc:"Vérifiez et cliquez sur Générer.",aiGuideStep7Title:"Aperçu",aiGuideStep7Desc:"Consultez le créatif généré.",aiGuideStep8Title:"Télécharger",aiGuideStep8Desc:"Téléchargez en PNG.",aiGuideStep9Title:"Itérer",aiGuideStep9Desc:"Modifiez et régénérez si nécessaire.",aiGuideStep10Title:"Déployer",aiGuideStep10Desc:"Uploadez sur les plateformes publicitaires.",guideStep1Title:"Connecter les Canaux",guideStep1Desc:"Connectez vos canaux dans le Hub d'intégration.",guideStep2Title:"Configurer les Campagnes",guideStep2Desc:"Configurez avec objectifs et budget.",guideStep3Title:"Suivre la Performance",guideStep3Desc:"Consultez les métriques en temps réel.",guideStep4Title:"Optimiser le ROAS",guideStep4Desc:"Analysez et optimisez la distribution budgétaire.",guideStep5Title:"Analyse Créative",guideStep5Desc:"Comparez les performances des créatifs.",guideStep6Title:"Rapports",guideStep6Desc:"Générez des rapports détaillés.",guideTip1:"Un ROAS supérieur à 2.0x est bon.",guideTip2:"Vérifiez régulièrement le taux de règlement.",guideTip3:"Concentrez le budget sur les SKUs à marge élevée.",guideTip4:"Optimisez par canal.",guideTip5:"Surveillez la rétention à D+90."},
de:{tabCreative:"Kreativ",tabGuide:"Anleitung",aiGuideStep1Title:"Plattform wählen",aiGuideStep1Desc:"Wählen Sie die Zielplattform im AI Design Tab.",aiGuideStep2Title:"Thema wählen",aiGuideStep2Desc:"Wählen Sie ein Kreativthema.",aiGuideStep3Title:"Inhalt erstellen",aiGuideStep3Desc:"Geben Sie Titel, Untertitel, KI-Prompt und CTA ein.",aiGuideStep4Title:"Interaktiv einstellen",aiGuideStep4Desc:"Wählen Sie interaktive Anzeigentypen.",aiGuideStep5Title:"Zeitraum festlegen",aiGuideStep5Desc:"Konfigurieren Sie Daten und Zeitzone.",aiGuideStep6Title:"Generieren",aiGuideStep6Desc:"Überprüfen und Klicken Sie auf Generieren.",aiGuideStep7Title:"Vorschau",aiGuideStep7Desc:"Überprüfen Sie das generierte Kreativ.",aiGuideStep8Title:"Herunterladen",aiGuideStep8Desc:"Als PNG herunterladen.",aiGuideStep9Title:"Iterieren",aiGuideStep9Desc:"Ändern und neu generieren.",aiGuideStep10Title:"Bereitstellen",aiGuideStep10Desc:"Auf Werbeplattformen hochladen.",guideStep1Title:"Kanäle verbinden",guideStep1Desc:"Verbinden Sie Ihre Kanäle im Integrations-Hub.",guideStep2Title:"Kampagnen einrichten",guideStep2Desc:"Konfigurieren Sie Ziele und Budget.",guideStep3Title:"Leistung überwachen",guideStep3Desc:"Echtzeit-Metriken überprüfen.",guideStep4Title:"ROAS optimieren",guideStep4Desc:"Budget-Verteilung analysieren.",guideStep5Title:"Kreativ-Analyse",guideStep5Desc:"Kreativ-Performance vergleichen.",guideStep6Title:"Berichte",guideStep6Desc:"Detaillierte Berichte erstellen.",guideTip1:"ROAS über 2.0x ist gut.",guideTip2:"Effektive Abrechnungsrate prüfen.",guideTip3:"Budget auf SKUs mit hoher Marge konzentrieren.",guideTip4:"Pro Kanal optimieren.",guideTip5:"D+90 Retention überwachen."},
ar:{tabCreative:"الإبداعي",tabGuide:"دليل الاستخدام",aiGuideStep1Title:"اختيار المنصة",aiGuideStep1Desc:"ادخل إلى تبويب التصميم بالذكاء الاصطناعي واختر المنصة المستهدفة من بين 14 منصة.",aiGuideStep2Title:"اختيار الموضوع",aiGuideStep2Desc:"اختر موضوعاً إبداعياً يتناسب مع أهداف حملتك من بين 10 مواضيع.",aiGuideStep3Title:"كتابة المحتوى",aiGuideStep3Desc:"أدخل العنوان والعنوان الفرعي ووصف الصورة وزر الدعوة للإجراء.",aiGuideStep4Title:"إعداد التفاعل",aiGuideStep4Desc:"اختر أنواع الإعلانات التفاعلية مثل عجلة الحظ وبطاقات الكشط.",aiGuideStep5Title:"تحديد الفترة الزمنية",aiGuideStep5Desc:"حدد تاريخ البداية والنهاية والمنطقة الزمنية للحملات المحدودة.",aiGuideStep6Title:"إنشاء الإبداع",aiGuideStep6Desc:"راجع الملخص وانقر على زر الإنشاء.",aiGuideStep7Title:"معاينة النتائج",aiGuideStep7Desc:"راجع الإبداع المنشأ في المعاينة.",aiGuideStep8Title:"التحميل",aiGuideStep8Desc:"حمّل كملف PNG.",aiGuideStep9Title:"التكرار والتحسين",aiGuideStep9Desc:"عدّل وأعد الإنشاء حسب الحاجة. يمكنك مقارنة الإصدارات السابقة.",aiGuideStep10Title:"النشر والاستخدام",aiGuideStep10Desc:"ارفع الإبداعات إلى منصات الإعلانات مثل Meta وGoogle وTikTok.",guideStep1Title:"ربط القنوات",guideStep1Desc:"اربط قنواتك الإعلانية في مركز التكامل.",guideStep2Title:"إعداد الحملات",guideStep2Desc:"أنشئ حملات بأهداف وميزانية محددة.",guideStep3Title:"مراقبة الأداء",guideStep3Desc:"راجع مقاييس الأداء في الوقت الفعلي.",guideStep4Title:"تحسين ROAS",guideStep4Desc:"حلل وحسّن توزيع الميزانية.",guideStep5Title:"تحليل الإبداع",guideStep5Desc:"قارن أداء الإبداعات المختلفة.",guideStep6Title:"التقارير",guideStep6Desc:"أنشئ تقارير مفصلة عن الأداء.",guideTip1:"عائد الإنفاق الإعلاني أعلى من 2.0x يدل على ربحية جيدة.",guideTip2:"راجع معدل التسوية الفعلي بانتظام.",guideTip3:"ركّز الميزانية على المنتجات ذات الهامش العالي.",guideTip4:"حسّن الإبداعات حسب أداء كل قناة.",guideTip5:"راقب نسبة الاحتفاظ في اليوم 90."},
th:{tabCreative:"ครีเอทีฟ",tabGuide:"คู่มือ",aiGuideStep1Title:"เลือกแพลตฟอร์ม",aiGuideStep1Desc:"เลือกแพลตฟอร์มเป้าหมายจาก 14 แพลตฟอร์ม",aiGuideStep2Title:"เลือกธีม",aiGuideStep2Desc:"เลือกธีมครีเอทีฟที่เหมาะกับแคมเปญ",aiGuideStep3Title:"เขียนเนื้อหา",aiGuideStep3Desc:"ใส่หัวข้อ คำบรรยาย พรอมต์ AI และปุ่ม CTA",aiGuideStep4Title:"ตั้งค่าอินเตอร์แอคทีฟ",aiGuideStep4Desc:"เลือกประเภทโฆษณาเชิงโต้ตอบ",aiGuideStep5Title:"กำหนดช่วงเวลา",aiGuideStep5Desc:"ตั้งวันเริ่มต้น วันสิ้นสุด และเขตเวลา",aiGuideStep6Title:"สร้างครีเอทีฟ",aiGuideStep6Desc:"ตรวจสอบและคลิกสร้าง",aiGuideStep7Title:"ดูตัวอย่าง",aiGuideStep7Desc:"ตรวจสอบผลงานที่สร้างขึ้น",aiGuideStep8Title:"ดาวน์โหลด",aiGuideStep8Desc:"ดาวน์โหลดเป็นไฟล์ PNG",aiGuideStep9Title:"ปรับปรุง",aiGuideStep9Desc:"แก้ไขและสร้างใหม่ตามต้องการ",aiGuideStep10Title:"เผยแพร่",aiGuideStep10Desc:"อัปโหลดไปยังแพลตฟอร์มโฆษณา",guideStep1Title:"เชื่อมต่อช่องทาง",guideStep1Desc:"เชื่อมต่อช่องทางในศูนย์การเชื่อมต่อ",guideStep2Title:"ตั้งค่าแคมเปญ",guideStep2Desc:"กำหนดเป้าหมายและงบประมาณ",guideStep3Title:"ติดตามผล",guideStep3Desc:"ดูตัวชี้วัดแบบเรียลไทม์",guideStep4Title:"เพิ่มประสิทธิภาพ ROAS",guideStep4Desc:"วิเคราะห์และปรับการกระจายงบ",guideStep5Title:"วิเคราะห์ครีเอทีฟ",guideStep5Desc:"เปรียบเทียบประสิทธิภาพครีเอทีฟ",guideStep6Title:"รายงาน",guideStep6Desc:"สร้างรายงานโดยละเอียด",guideTip1:"ROAS มากกว่า 2.0x ถือว่าดี",guideTip2:"ตรวจสอบอัตราการชำระเงินจริง",guideTip3:"เน้นงบไปที่ SKU ที่มีกำไรสูง",guideTip4:"ปรับแต่งตามช่องทาง",guideTip5:"ติดตามการรักษาลูกค้า D+90"},
vi:{tabCreative:"Sáng tạo",tabGuide:"Hướng dẫn",aiGuideStep1Title:"Chọn nền tảng",aiGuideStep1Desc:"Chọn nền tảng mục tiêu từ 14 nền tảng.",aiGuideStep2Title:"Chọn chủ đề",aiGuideStep2Desc:"Chọn chủ đề sáng tạo phù hợp.",aiGuideStep3Title:"Viết nội dung",aiGuideStep3Desc:"Nhập tiêu đề, mô tả, prompt AI và nút CTA.",aiGuideStep4Title:"Cài đặt tương tác",aiGuideStep4Desc:"Chọn loại quảng cáo tương tác.",aiGuideStep5Title:"Đặt thời gian",aiGuideStep5Desc:"Cấu hình ngày bắt đầu, kết thúc và múi giờ.",aiGuideStep6Title:"Tạo sáng tạo",aiGuideStep6Desc:"Xem lại và nhấn Tạo.",aiGuideStep7Title:"Xem trước",aiGuideStep7Desc:"Kiểm tra kết quả.",aiGuideStep8Title:"Tải xuống",aiGuideStep8Desc:"Tải về dạng PNG.",aiGuideStep9Title:"Cải thiện",aiGuideStep9Desc:"Chỉnh sửa và tạo lại.",aiGuideStep10Title:"Triển khai",aiGuideStep10Desc:"Tải lên các nền tảng quảng cáo."},
id:{tabCreative:"Kreatif",tabGuide:"Panduan",aiGuideStep1Title:"Pilih Platform",aiGuideStep1Desc:"Pilih platform target dari 14 platform.",aiGuideStep2Title:"Pilih Tema",aiGuideStep2Desc:"Pilih tema kreatif yang sesuai.",aiGuideStep3Title:"Tulis Konten",aiGuideStep3Desc:"Masukkan judul, deskripsi, prompt AI dan tombol CTA.",aiGuideStep4Title:"Atur Interaktif",aiGuideStep4Desc:"Pilih jenis iklan interaktif.",aiGuideStep5Title:"Atur Periode",aiGuideStep5Desc:"Konfigurasikan tanggal dan zona waktu.",aiGuideStep6Title:"Buat Kreatif",aiGuideStep6Desc:"Tinjau dan klik Buat.",aiGuideStep7Title:"Pratinjau",aiGuideStep7Desc:"Periksa hasil yang dibuat.",aiGuideStep8Title:"Unduh",aiGuideStep8Desc:"Unduh sebagai PNG.",aiGuideStep9Title:"Iterasi",aiGuideStep9Desc:"Ubah dan buat ulang.",aiGuideStep10Title:"Deploy",aiGuideStep10Desc:"Unggah ke platform iklan."},
pt:{tabCreative:"Criativo",tabGuide:"Guia",aiGuideStep1Title:"Selecionar Plataforma",aiGuideStep1Desc:"Escolha a plataforma alvo entre 14 opções.",aiGuideStep2Title:"Escolher Tema",aiGuideStep2Desc:"Selecione um tema criativo adequado.",aiGuideStep3Title:"Escrever Conteúdo",aiGuideStep3Desc:"Insira título, subtítulo, prompt IA e botão CTA.",aiGuideStep4Title:"Configurar Interativo",aiGuideStep4Desc:"Escolha tipos de anúncios interativos.",aiGuideStep5Title:"Definir Período",aiGuideStep5Desc:"Configure datas e fuso horário.",aiGuideStep6Title:"Gerar Criativo",aiGuideStep6Desc:"Revise e clique em Gerar.",aiGuideStep7Title:"Pré-visualizar",aiGuideStep7Desc:"Verifique o resultado.",aiGuideStep8Title:"Baixar",aiGuideStep8Desc:"Baixe como PNG.",aiGuideStep9Title:"Iterar",aiGuideStep9Desc:"Modifique e regenere.",aiGuideStep10Title:"Implantar",aiGuideStep10Desc:"Envie para plataformas de anúncios."},
ru:{tabCreative:"Креатив",tabGuide:"Руководство",aiGuideStep1Title:"Выбор платформы",aiGuideStep1Desc:"Выберите целевую платформу из 14 вариантов.",aiGuideStep2Title:"Выбор темы",aiGuideStep2Desc:"Выберите тему креатива.",aiGuideStep3Title:"Создание контента",aiGuideStep3Desc:"Введите заголовок, подзаголовок, промпт и CTA.",aiGuideStep4Title:"Настройка интерактива",aiGuideStep4Desc:"Выберите тип интерактивной рекламы.",aiGuideStep5Title:"Установка периода",aiGuideStep5Desc:"Настройте даты и часовой пояс.",aiGuideStep6Title:"Генерация",aiGuideStep6Desc:"Проверьте и нажмите Генерировать.",aiGuideStep7Title:"Предпросмотр",aiGuideStep7Desc:"Проверьте результат.",aiGuideStep8Title:"Скачать",aiGuideStep8Desc:"Скачайте в формате PNG.",aiGuideStep9Title:"Итерация",aiGuideStep9Desc:"Измените и пересоздайте.",aiGuideStep10Title:"Развертывание",aiGuideStep10Desc:"Загрузите на рекламные платформы."},
hi:{tabCreative:"क्रिएटिव",tabGuide:"गाइड",aiGuideStep1Title:"प्लेटफ़ॉर्म चुनें",aiGuideStep1Desc:"14 प्लेटफ़ॉर्म में से लक्ष्य प्लेटफ़ॉर्म चुनें।",aiGuideStep2Title:"थीम चुनें",aiGuideStep2Desc:"उपयुक्त क्रिएटिव थीम चुनें।",aiGuideStep3Title:"सामग्री लिखें",aiGuideStep3Desc:"शीर्षक, विवरण, AI प्रॉम्प्ट और CTA दर्ज करें।",aiGuideStep4Title:"इंटरैक्टिव सेट करें",aiGuideStep4Desc:"इंटरैक्टिव विज्ञापन प्रकार चुनें।",aiGuideStep5Title:"अवधि निर्धारित करें",aiGuideStep5Desc:"तारीख और टाइमज़ोन कॉन्फ़िगर करें।",aiGuideStep6Title:"बनाएं",aiGuideStep6Desc:"समीक्षा करें और बनाएं पर क्लिक करें।",aiGuideStep7Title:"पूर्वावलोकन",aiGuideStep7Desc:"परिणाम की जांच करें।",aiGuideStep8Title:"डाउनलोड",aiGuideStep8Desc:"PNG के रूप में डाउनलोड करें।",aiGuideStep9Title:"पुनरावृत्ति",aiGuideStep9Desc:"संशोधित करें और पुनः बनाएं।",aiGuideStep10Title:"तैनात करें",aiGuideStep10Desc:"विज्ञापन प्लेटफ़ॉर्म पर अपलोड करें।"},
"zh-TW":{tabCreative:"創意",tabGuide:"使用指南",aiGuideStep1Title:"選擇平台",aiGuideStep1Desc:"從14個平台中選擇目標平台。",aiGuideStep2Title:"選擇主題",aiGuideStep2Desc:"選擇合適的創意主題。",aiGuideStep3Title:"撰寫內容",aiGuideStep3Desc:"輸入標題、副標題、AI提示詞和CTA按鈕。",aiGuideStep4Title:"設置互動",aiGuideStep4Desc:"選擇互動廣告類型。",aiGuideStep5Title:"設定期間",aiGuideStep5Desc:"配置開始和結束日期及時區。",aiGuideStep6Title:"生成創意",aiGuideStep6Desc:"確認後點擊生成。",aiGuideStep7Title:"預覽結果",aiGuideStep7Desc:"檢查生成的創意。",aiGuideStep8Title:"下載",aiGuideStep8Desc:"下載為PNG檔案。",aiGuideStep9Title:"迭代修改",aiGuideStep9Desc:"修改後重新生成。",aiGuideStep10Title:"部署使用",aiGuideStep10Desc:"上傳到廣告平台。"},
};
const LANGS=Object.keys(FIXES);
let total=0;
LANGS.forEach(lang=>{
  const file=path.join(DIR,lang+'.js');
  if(!fs.existsSync(file))return;
  let src=fs.readFileSync(file,'utf8');
  // Find marketing namespace
  const mktMatch=src.match(/"marketing"\s*:\s*\{/);
  if(!mktMatch){console.log('skip '+lang);return;}
  const mktStart=mktMatch.index+mktMatch[0].length;
  let depth=1,pos=mktStart;
  while(depth>0&&pos<src.length){if(src[pos]==='{')depth++;if(src[pos]==='}')depth--;pos++;}
  const mktEnd=pos-1;
  let mktContent=src.substring(mktStart,mktEnd);
  let cnt=0;
  const keys=FIXES[lang];
  Object.entries(keys).forEach(([k,v])=>{
    const esc=v.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/'/g,"\\'");
    // Replace ALL occurrences of this key in marketing namespace
    const pattern='"'+k+'":"';
    let idx=mktContent.indexOf(pattern);
    if(idx!==-1){
      // Find end of value
      const valStart=idx+pattern.length;
      let valEnd=valStart;
      while(valEnd<mktContent.length&&mktContent[valEnd]!=='"')valEnd++;
      const oldVal=mktContent.substring(valStart,valEnd);
      if(oldVal!==esc){
        mktContent=mktContent.substring(0,valStart)+esc+mktContent.substring(valEnd);
        cnt++;
      }
    } else {
      mktContent='"'+k+'":"'+esc+'",'+mktContent;
      cnt++;
    }
  });
  if(cnt>0){
    src=src.substring(0,mktStart)+mktContent+src.substring(mktEnd);
    fs.writeFileSync(file,src,'utf8');
    console.log('✅ '+lang+': '+cnt);
    total+=cnt;
  }
});
console.log('🎯 Total: '+total);
