const fs = require('fs');
let c = fs.readFileSync('src/pages/CatalogSync.jsx', 'utf8');

const replacements = [
  // Channel names
  ['Naver 스마트스토어', 'Naver Smart Store'],
  ['11번가', '11Street'],
  ['G마켓', 'Gmarket'],
  ['카카오커머스', 'Kakao Commerce'],
  ['위메프', 'WeMakePrice'],
  ['인터파크', 'Interpark'],
  ['롯데ON', 'Lotte ON'],
  ['자사몰', 'Own Mall'],
  // Region labels
  ['"국내"', '"Domestic"'],
  ["'국내'", "'Domestic'"],
  ['region: "국내"', 'region: "Domestic"'],
  ['region: "글로벌"', 'region: "Global"'],
  ['region: "일본"', 'region: "Japan"'],
  ['region: "동남아"', 'region: "SE Asia"'],
  ['region: "유럽"', 'region: "Europe"'],
  ['region: "기타"', 'region: "Other"'],
  // Product names in mock data
  ['무선 노이즈캔슬링 헤드폰', 'Wireless Noise-Cancelling Headphones'],
  ['RGB 기계식 키보드', 'RGB Mechanical Keyboard'],
  ['USB-C 7포트 허브', 'USB-C 7-Port Hub'],
  ['에르고 마우스', 'Ergo Mouse'],
  ['급속충전기', 'Fast Charger'],
  // Spec strings
  ['노이즈캔슬링/BT 5.2', 'Noise-Cancelling / BT 5.2'],
  ['TKL/청축스위치', 'TKL / Blue Switch'],
  ['USB4 Gen2/60W PD', 'USB4 Gen2 / 60W PD'],
  ['4K 30fps/범용', '4K 30fps / Universal'],
  ['에르고/무선', 'Ergo / Wireless'],
  ['GaN/USB-C', 'GaN / USB-C'],
  // Unit strings
  ['"개"', '"pcs"'],
  ['"대"', '"unit"'],
  // Category strings in product data
  ['"전자/음향"', '"Electronics/Audio"'],
  ['"전자/입력장치"', '"Electronics/Input"'],
  ['"전자/주변기기"', '"Electronics/Peripherals"'],
  ['"전자/카메라"', '"Electronics/Camera"'],
  ['"전자/충전"', '"Electronics/Charging"'],
  // lastSync
  ['시간 전', 'h ago'],
  // Status labels
  ['정상', 'Normal'],
  ['주의', 'Warning'],
  ['오류', 'Error'],
  // statusLabel function
  ['const statusLabel = s => s === "ok" ? "정상" : s === "warn" ? "주의" : "오류";',
   'const statusLabel = s => s === "ok" ? "Normal" : s === "warn" ? "Warning" : "Error";'],
  // Unit type labels
  ['ea (낱개)', 'ea (unit)'],
  ['Box (박스)', 'Box'],
  ['PL (파렛트)', 'PL (Pallet)'],
  ['낱개 단위로 등록', 'Register as individual units'],
  ['1Box = N ea 입력', 'Enter 1 Box = N ea'],
  ['1PL = N Box = M ea', '1 PL = N Box = M ea'],
  // Demo Banner
  ['데모 모드', 'Demo Mode'],
  ['실제 채널 API 호출 없이 시뮬레이션됩니다. 유료 플랜에서 실연동 가능합니다.', 'Simulated without real channel API calls. Live integration available on paid plans.'],
  // Product Register Modal
  ['📦 상품 등록', '📦 Register Product'],
  ['▸ 기본 정보', '▸ Basic Info'],
  ['상품명 *', 'Product Name *'],
  ['상품명 입력', 'Enter product name'],
  ['SKU 코드', 'SKU Code'],
  ['카테고리 선택 *', 'Select Category *'],
  ['규격 / Spec', 'Spec / Dimensions'],
  ['예: 100x200x50mm, 1kg', 'e.g. 100x200x50mm, 1kg'],
  ['▸ 단위 선택 *', '▸ Unit Selection *'],
  ['📦 Box 단위 상세', '📦 Box Unit Details'],
  ['1 Box 당 수량 (ea) *', 'Qty per Box (ea) *'],
  ['예: 12', 'e.g. 12'],
  ['📦📦 파렛트(PL) 단위 상세', '📦📦 Pallet (PL) Unit Details'],
  ['1 PL 당 Box 수량 *', 'Box Qty per PL *'],
  ['예: 40', 'e.g. 40'],
  ['▸ 상품 이미지 등록', '▸ Product Image'],
  ['클릭하여 이미지 업로드 (JPG, PNG, WEBP)', 'Click to upload image (JPG, PNG, WEBP)'],
  ['✕ 이미지 제거', '✕ Remove Image'],
  ['▸ 가격', '▸ Pricing'],
  ['판매가 (₩)', 'Sale Price (₩)'],
  ['정가/비교가 (₩)', 'Compare Price (₩)'],
  ['▸ 원가 구성', '▸ Cost Structure'],
  ['매입원가 (₩)', 'Purchase Cost (₩)'],
  ['입·출고비 (₩)', 'Inbound/Outbound Fee (₩)'],
  ['보관비 (₩)', 'Storage Fee (₩)'],
  ['기본작업비 (₩)', 'Handling Fee (₩)'],
  ['배송비 (₩)', 'Shipping Fee (₩)'],
  ['상품원가 (자동계산)', 'Product Cost (auto-calc)'],
  ['▸ 초기 재고', '▸ Initial Stock'],
  ['재고 수량 (', 'Stock Qty ('],
  ['취소', 'Cancel'],
  ['💾 저장', '💾 Save'],
  ['상품명과 카테고리를 입력해주세요.', 'Please enter product name and category.'],
  ['1Box당 ea 수량을 입력해주세요.', 'Please enter qty per Box.'],
  ['1Box당 ea, 1PL당 Box 수량을 모두 입력해주세요.', 'Please enter both qty per Box and Box per PL.'],
  // BulkRegisterModal
  ['📡 채널 상품 등록', '📡 Register Products to Channel'],
  ['채널 선택', 'Select Channel'],
  ['판매가 설정', 'Set Price'],
  ['승인 & 등록', 'Approve & Register'],
  ['채널 상품 등록', 'Channel Product Registration'],
  ['✅ 채널 등록', '✅ Register to Channel'],
  ['선택 채널에 판매 등록/활성화', 'Register/activate sales on selected channels'],
  ['⛔ 채널 해제', '⛔ Unregister Channel'],
  ['선택 채널에서 상품 비활성화', 'Deactivate product on selected channels'],
  ['📡 대상 채널 선택', '📡 Select Target Channels'],
  ['전체 선택', 'Select All'],
  ['전체 해제', 'Deselect All'],
  ['개 채널 선택됨', ' channels selected'],
  ['수수료', 'Commission'],
  ['세금', 'Tax'],
  ['💰 채널별 추천 판매가 설정', '💰 Set Recommended Price per Channel'],
  ['채널', 'Channel'],
  ['세금(VAT)', 'Tax (VAT)'],
  ['이익율(%)', 'Margin (%)'],
  ['상품원가', 'Product Cost'],
  ['💰 추천 판매가', '💰 Recommended Price'],
  ['직접입력', 'Override'],
  ['실마진', 'Actual Margin'],
  ['💡 추천판매가 공식:', '💡 Recommended Price Formula:'],
  ['상품원가 ÷ (1 - 수수료율 - 세금율 - 이익율)', 'Product Cost ÷ (1 - Commission - Tax - Margin)'],
  ['노란색으로 표시된 가격은 직접 입력된 값입니다.', 'Prices shown in yellow are manually entered.'],
  ['← 이전', '← Back'],
  ['다음: 판매가 설정 →', 'Next: Set Price →'],
  ['다음: 승인 & 등록 →', 'Next: Approve & Register →'],
  ['개 상품 해제', ' products unregistered'],
  ['✅ 최종 확인 & 관리자 승인', '✅ Final Review & Manager Approval'],
  ['📋 채널별 최종 판매가 요약', '📋 Final Price Summary by Channel'],
  ['수수료+세금', 'Commission+Tax'],
  ['예상이익', 'Est. Profit'],
  ['판매가', 'Sale Price'],
  ['✍️ 관리자 승인:', '✍️ Manager Approval:'],
  ['개 채널에', ' channels with'],
  ['개 상품을 등록합니다', ' products will be registered'],
  ['승인 후 전체 또는 선택 채널에 판매 등록이 진행됩니다.', 'After approval, sales registration will proceed on selected channels.'],
  ['채널 등록 완료!', 'channel registration complete!'],
  ['(데모)', '(Demo)'],
  ['⏳ 등록 중...', '⏳ Registering...'],
  ['🚀 ', '🚀 '],
  ['개 채널 등록 실행', ' channels — execute registration'],
  // BulkPriceModal
  ['💰 채널별 가격 일괄 변경', '💰 Bulk Price Change by Channel'],
  ['가격 변경 유형', 'Price Change Type'],
  ['% 할인', '% Off'],
  ['% 인상', '% Increase'],
  ['고정가 변경', 'Fixed Price Change'],
  ['20% 이상 인하는 채널 정책 위반 가능성이 있습니다.', 'More than 20% discount may violate channel policies.'],
  ['50% 이상 인상은 판매 감소로 이어질 수 있습니다.', 'More than 50% increase may reduce sales.'],
  ['채널별 최소/최대가 범위를 초과할 수 있습니다.', 'Fixed price may exceed channel min/max limits.'],
  ['변경 전', 'Before'],
  ['변경 후', 'After'],
  ['채널 적용 예시', 'Channel Application Preview'],
  ['가격 일괄 변경', 'Apply Bulk Price Change'],
  // Channel Budget section
  ['💰 채널별 예산 배분 & 소진율', '💰 Channel Budget Allocation & Burn Rate'],
  ['📊 채널별 상세 성과표', '📊 Channel Performance Details'],
  // Job list
  ['전체 동기화', 'Full Sync'],
  ['증분 동기화', 'Incremental Sync'],
  ['완료', 'Done'],
  ['실행 중', 'Running'],
  ['대기 중', 'Pending'],
  ['오류 발생', 'Error'],
  ['소요시간', 'Duration'],
  // Sync tab
  ['📡 채널 동기화', '📡 Channel Sync'],
  ['동기화 설정', 'Sync Settings'],
  ['동기화 범위', 'Sync Scope'],
  ['동기화 이력', 'Sync History'],
  // Status labels
  ['정상 등록', 'Registered'],
  ['미등록', 'Not Registered'],
  // Main page header
  ['📦 카탈로그 & 채널 동기화', '📦 Catalog & Channel Sync'],
  ['채널별 상품 등록·해제 · 가격·재고 실시간 동기화 · AI 최적화 판매가 추천', 'Channel product registration · Real-time price & inventory sync · AI optimized pricing'],
  // filter/tabs
  ['전체 상품', 'All Products'],
  ['오류 상품', 'Error Products'],
  ['미동기화', 'Not Synced'],
  // Table headers
  ['상품명', 'Product Name'],
  ['등록 채널', 'Registered Channels'],
  ['마지막 동기화', 'Last Sync'],
  ['동기화 미등록', 'Not Synced'],
  ['미등록 상태', 'Unregistered'],
  // Buttons
  ['상품 등록', 'Add Product'],
  ['채널 등록', 'Register to Channel'],
  ['가격 변경', 'Change Price'],
  ['전체 동기화 실행', 'Run Full Sync'],
  ['선택 동기화', 'Sync Selected'],
  // Sort
  ['이름순', 'By Name'],
  ['재고순', 'By Stock'],
  // Demo feature strings
  ['카탈로그 동기화', 'Catalog Sync'],
  ['가격·재고 일괄 변경', 'Bulk Price/Stock Change'],
  // Console warnings
  ['일부 채널 writeback 실패:', 'Some channels writeback failed:'],
  ['writeback 오류:', 'writeback error:'],
];

for (const [from, to] of replacements) {
  c = c.split(from).join(to);
}

fs.writeFileSync('src/pages/CatalogSync.jsx', c, 'utf8');
console.log('CatalogSync.jsx done, size:', c.length);
