const fs=require('fs'),path=require('path'),dir=path.join(__dirname,'src/i18n/locales');
// Common visible keys for remaining languages
const base={wmsHeroTitle:1,wmsHeroDesc:1,wmsAssetValue:1,tabWarehouse:1,tabWarehouseDesc:1,tabInOut:1,tabInOutDesc:1,tabInventory:1,tabInventoryDesc:1,tabReceiving:1,tabReceivingDesc:1,tabPicking:1,tabPickingDesc:1,tabLot:1,tabLotDesc:1,tabReplenishment:1,tabReplenishmentDesc:1,tabCarrier:1,tabCarrierDesc:1,tabCombine:1,tabCombineDesc:1,tabTracking:1,tabTrackingDesc:1,tabAudit:1,tabAuditDesc:1,tabInvoice:1,tabInvoiceDesc:1,tabBundle:1,tabBundleDesc:1,tabGuide:1,tabGuideDesc:1,tabSupplier:1,tabSupplierDesc:1,invTableTitle:1,invColSku:1,invColProduct:1,invColTotal:1,invColSafe:1,invColStatus:1,invColCost:1,invColValue:1,invColAdj:1,invSearchPh:1,invLowOnly:1,invNoResult:1,invNormal:1,invLow:1,invOutOfStock:1,invTotalStock:1,whListTitle:1,whAddBtn:1,whCancelBtn:1,whSaveBtn:1,ioFilterAll:1,ioFilterInbound:1,ioFilterOutbound:1,csvImportBtn:1,exportCsvBtn:1,exportExcelBtn:1,pickAll:1,pickPending:1,pickShipped:1,guideHeroTitle:1,guideQuickStart:1};
const T={
'zh-TW':{wmsHeroTitle:"WMS 倉庫統一管理",wmsHeroDesc:"倉庫註冊·出入庫·庫存管理·捆綁·快遞/特快·商業發票管理",wmsAssetValue:"庫存資產總值",tabWarehouse:"WMS 倉庫",tabInOut:"出入庫",tabInventory:"庫存狀況",tabReceiving:"入庫驗收",tabPicking:"揀貨/包裝",tabLot:"批次/保質期",tabReplenishment:"自動採購",tabCarrier:"運輸公司",tabCombine:"合併包裝",tabTracking:"物流追蹤",tabAudit:"庫存盤點",tabInvoice:"發票",tabBundle:"捆綁/BOM",tabGuide:"使用指南",tabSupplier:"供應商",invTableTitle:"SKU別倉庫庫存現況",invColProduct:"商品名",invColTotal:"合計",invColSafe:"安全庫存",invColStatus:"狀態",invColCost:"成本",invColValue:"庫存價值",invColAdj:"調整",invSearchPh:"搜索SKU或商品名...",invLowOnly:"僅顯示低庫存",invNoResult:"無搜索結果",invNormal:"正常",invLow:"低庫存",invOutOfStock:"缺貨",invTotalStock:"總庫存",whListTitle:"倉庫列表",whAddBtn:"+ 新增倉庫",whCancelBtn:"取消",whSaveBtn:"儲存",ioFilterAll:"全部",ioFilterInbound:"入庫",ioFilterOutbound:"出庫",csvImportBtn:"CSV匯入",exportCsvBtn:"匯出CSV",exportExcelBtn:"匯出Excel",pickAll:"全部",pickPending:"待處理",pickShipped:"已出貨",guideHeroTitle:"WMS倉庫管理完全指南",guideQuickStart:"快速開始"},
de:{wmsHeroTitle:"WMS Lagerverwaltung",wmsHeroDesc:"Lagerverwaltung · Ein-/Ausgang · Bestand · Bündel · Versand · Rechnungen",wmsAssetValue:"Gesamtbestandswert",tabWarehouse:"WMS Lager",tabInOut:"Ein-/Ausgang",tabInventory:"Bestandsstatus",tabReceiving:"Wareneingang",tabPicking:"Kommissionierung",tabLot:"Charge/MHD",tabReplenishment:"Nachbestellung",tabCarrier:"Spediteure",tabCombine:"Zusammenpackung",tabTracking:"Sendungsverfolgung",tabAudit:"Inventur",tabInvoice:"Rechnung",tabBundle:"Bündel/BOM",tabGuide:"Anleitung",tabSupplier:"Lieferanten",invTableTitle:"SKU-Bestandsübersicht",invColProduct:"Produktname",invColTotal:"Gesamt",invColSafe:"Sicherheitsbestand",invColStatus:"Status",invColCost:"Kosten",invColValue:"Bestandswert",invColAdj:"Anpassung",invSearchPh:"SKU oder Produkt suchen...",invLowOnly:"Nur Niedrigbestand",invNoResult:"Keine Ergebnisse",invNormal:"Normal",invLow:"Niedrig",invOutOfStock:"Ausverkauft",invTotalStock:"Gesamtbestand",whListTitle:"Lagerliste",whAddBtn:"+ Lager hinzufügen",whCancelBtn:"Abbrechen",whSaveBtn:"Speichern",ioFilterAll:"Alle",ioFilterInbound:"Eingang",ioFilterOutbound:"Ausgang",csvImportBtn:"CSV-Import",exportCsvBtn:"CSV exportieren",exportExcelBtn:"Excel exportieren",pickAll:"Alle",pickPending:"Ausstehend",pickShipped:"Versendet",guideHeroTitle:"WMS Lagerverwaltung - Leitfaden",guideQuickStart:"Schnellstart"},
th:{wmsHeroTitle:"WMS การจัดการคลังสินค้า",wmsHeroDesc:"ลงทะเบียนคลัง·รับ-จ่าย·สต็อก·มัดรวม·ขนส่ง·ใบกำกับ",wmsAssetValue:"มูลค่าสินค้าคงคลังทั้งหมด",tabWarehouse:"คลังสินค้า WMS",tabInOut:"รับ-จ่าย",tabInventory:"สถานะสต็อก",tabReceiving:"รับสินค้า",tabPicking:"หยิบ/แพ็ค",tabLot:"ล็อต/วันหมดอายุ",tabReplenishment:"สั่งซื้ออัตโนมัติ",tabCarrier:"ผู้ขนส่ง",tabCombine:"รวมพัสดุ",tabTracking:"ติดตามการจัดส่ง",tabAudit:"ตรวจนับสต็อก",tabInvoice:"ใบกำกับ",tabBundle:"มัดรวม/BOM",tabGuide:"คู่มือ",tabSupplier:"ซัพพลายเออร์",invTableTitle:"สถานะสต็อกตาม SKU",invColProduct:"ชื่อสินค้า",invColTotal:"รวม",invColSafe:"สต็อกปลอดภัย",invColStatus:"สถานะ",invColCost:"ต้นทุน",invColValue:"มูลค่าสต็อก",invColAdj:"ปรับ",invSearchPh:"ค้นหา SKU หรือสินค้า...",invLowOnly:"แสดงเฉพาะสต็อกต่ำ",invNoResult:"ไม่พบผลลัพธ์",invNormal:"ปกติ",invLow:"ต่ำ",invOutOfStock:"หมดสต็อก",invTotalStock:"สต็อกทั้งหมด",whListTitle:"รายการคลัง",whAddBtn:"+ เพิ่มคลัง",whCancelBtn:"ยกเลิก",whSaveBtn:"บันทึก",ioFilterAll:"ทั้งหมด",ioFilterInbound:"รับเข้า",ioFilterOutbound:"จ่ายออก",csvImportBtn:"นำเข้า CSV",exportCsvBtn:"ส่งออก CSV",exportExcelBtn:"ส่งออก Excel",guideHeroTitle:"คู่มือ WMS ฉบับสมบูรณ์",guideQuickStart:"เริ่มต้นอย่างรวดเร็ว"},
vi:{wmsHeroTitle:"Quản lý Kho WMS Tổng hợp",wmsHeroDesc:"Đăng ký kho · Xuất nhập · Tồn kho · Gói · Vận chuyển · Hóa đơn",wmsAssetValue:"Tổng giá trị tồn kho",tabWarehouse:"Kho WMS",tabInOut:"Xuất nhập",tabInventory:"Tình trạng tồn kho",tabReceiving:"Nhận hàng",tabPicking:"Lấy hàng/Đóng gói",tabLot:"Lô/Hạn sử dụng",tabReplenishment:"Đặt hàng tự động",tabCarrier:"Đơn vị vận chuyển",tabCombine:"Gộp kiện",tabTracking:"Theo dõi vận chuyển",tabAudit:"Kiểm kê",tabInvoice:"Hóa đơn",tabBundle:"Gói/BOM",tabGuide:"Hướng dẫn",tabSupplier:"Nhà cung cấp",invTableTitle:"Tình trạng tồn kho theo SKU",invColProduct:"Tên sản phẩm",invColTotal:"Tổng",invColSafe:"Tồn kho an toàn",invColStatus:"Trạng thái",invColCost:"Giá vốn",invColValue:"Giá trị tồn",invColAdj:"Điều chỉnh",invSearchPh:"Tìm SKU hoặc sản phẩm...",invLowOnly:"Chỉ hiển thị tồn thấp",invNoResult:"Không có kết quả",invNormal:"Bình thường",invLow:"Thấp",invOutOfStock:"Hết hàng",invTotalStock:"Tổng tồn kho",whListTitle:"Danh sách kho",whAddBtn:"+ Thêm kho",whCancelBtn:"Hủy",whSaveBtn:"Lưu",ioFilterAll:"Tất cả",ioFilterInbound:"Nhập kho",ioFilterOutbound:"Xuất kho",csvImportBtn:"Nhập CSV",exportCsvBtn:"Xuất CSV",exportExcelBtn:"Xuất Excel",guideHeroTitle:"Hướng dẫn Quản lý Kho WMS",guideQuickStart:"Bắt đầu nhanh"},
id:{wmsHeroTitle:"Manajemen Gudang WMS Terpadu",wmsHeroDesc:"Registrasi gudang · Keluar masuk · Stok · Bundel · Pengiriman · Faktur",wmsAssetValue:"Total Nilai Aset Persediaan",tabWarehouse:"Gudang WMS",tabInOut:"Keluar/Masuk",tabInventory:"Status Stok",tabReceiving:"Penerimaan",tabPicking:"Pick & Pack",tabLot:"Lot/Kedaluwarsa",tabReplenishment:"Auto PO",tabCarrier:"Ekspedisi",tabCombine:"Gabung Paket",tabTracking:"Lacak Pengiriman",tabAudit:"Stock Opname",tabInvoice:"Faktur",tabBundle:"Bundel/BOM",tabGuide:"Panduan",tabSupplier:"Pemasok",invTableTitle:"Status Stok per SKU",invColProduct:"Nama Produk",invColTotal:"Total",invColSafe:"Stok Aman",invColStatus:"Status",invColCost:"Biaya",invColValue:"Nilai Stok",invColAdj:"Sesuaikan",invSearchPh:"Cari SKU atau produk...",invLowOnly:"Hanya stok rendah",invNoResult:"Tidak ada hasil",invNormal:"Normal",invLow:"Rendah",invOutOfStock:"Habis",invTotalStock:"Total Stok",whListTitle:"Daftar Gudang",whAddBtn:"+ Tambah Gudang",whCancelBtn:"Batal",whSaveBtn:"Simpan",ioFilterAll:"Semua",ioFilterInbound:"Masuk",ioFilterOutbound:"Keluar",csvImportBtn:"Impor CSV",exportCsvBtn:"Ekspor CSV",exportExcelBtn:"Ekspor Excel",guideHeroTitle:"Panduan Lengkap WMS",guideQuickStart:"Mulai Cepat"},
es:{wmsHeroTitle:"Gestión Unificada de Almacén WMS",wmsHeroDesc:"Registro de almacén · Entrada/Salida · Inventario · Paquetes · Envío · Facturas",wmsAssetValue:"Valor Total del Inventario",tabWarehouse:"Almacén WMS",tabInOut:"Entrada/Salida",tabInventory:"Estado del Inventario",tabReceiving:"Recepción",tabPicking:"Picking/Empaque",tabLot:"Lote/Caducidad",tabReplenishment:"Pedido Automático",tabCarrier:"Transportistas",tabCombine:"Empaque Combinado",tabTracking:"Seguimiento",tabAudit:"Auditoría de Inventario",tabInvoice:"Factura",tabBundle:"Paquete/BOM",tabGuide:"Guía",tabSupplier:"Proveedores",invTableTitle:"Estado de Inventario por SKU",invColProduct:"Producto",invColTotal:"Total",invColSafe:"Stock de Seguridad",invColStatus:"Estado",invColCost:"Costo",invColValue:"Valor del Stock",invColAdj:"Ajuste",invSearchPh:"Buscar SKU o producto...",invLowOnly:"Solo stock bajo",invNoResult:"Sin resultados",invNormal:"Normal",invLow:"Bajo",invOutOfStock:"Agotado",invTotalStock:"Stock Total",whListTitle:"Lista de Almacenes",whAddBtn:"+ Agregar Almacén",whCancelBtn:"Cancelar",whSaveBtn:"Guardar",ioFilterAll:"Todo",ioFilterInbound:"Entrada",ioFilterOutbound:"Salida",csvImportBtn:"Importar CSV",exportCsvBtn:"Exportar CSV",exportExcelBtn:"Exportar Excel",guideHeroTitle:"Guía Completa de WMS",guideQuickStart:"Inicio Rápido"},
fr:{wmsHeroTitle:"Gestion Unifiée d'Entrepôt WMS",wmsHeroDesc:"Enregistrement · Entrée/Sortie · Stock · Lots · Expédition · Factures",wmsAssetValue:"Valeur Totale des Stocks",tabWarehouse:"Entrepôt WMS",tabInOut:"Entrée/Sortie",tabInventory:"État des Stocks",tabReceiving:"Réception",tabPicking:"Préparation/Emballage",tabLot:"Lot/Date Limite",tabReplenishment:"Réappro. Auto",tabCarrier:"Transporteurs",tabCombine:"Regroupement",tabTracking:"Suivi",tabAudit:"Inventaire",tabInvoice:"Facture",tabBundle:"Kit/BOM",tabGuide:"Guide",tabSupplier:"Fournisseurs",invTableTitle:"État des Stocks par SKU",invColProduct:"Produit",invColTotal:"Total",invColSafe:"Stock de Sécurité",invColStatus:"Statut",invColCost:"Coût",invColValue:"Valeur du Stock",invColAdj:"Ajustement",invSearchPh:"Rechercher SKU ou produit...",invLowOnly:"Stock bas uniquement",invNoResult:"Aucun résultat",invNormal:"Normal",invLow:"Bas",invOutOfStock:"Rupture",invTotalStock:"Stock Total",whListTitle:"Liste des Entrepôts",whAddBtn:"+ Ajouter Entrepôt",whCancelBtn:"Annuler",whSaveBtn:"Enregistrer",ioFilterAll:"Tout",ioFilterInbound:"Entrée",ioFilterOutbound:"Sortie",csvImportBtn:"Importer CSV",exportCsvBtn:"Exporter CSV",exportExcelBtn:"Exporter Excel",guideHeroTitle:"Guide Complet WMS",guideQuickStart:"Démarrage Rapide"},
pt:{wmsHeroTitle:"Gestão Unificada de Armazém WMS",wmsHeroDesc:"Registro · Entrada/Saída · Estoque · Pacotes · Envio · Faturas",wmsAssetValue:"Valor Total do Estoque",tabWarehouse:"Armazém WMS",tabInOut:"Entrada/Saída",tabInventory:"Status do Estoque",tabReceiving:"Recebimento",tabPicking:"Separação/Embalagem",tabLot:"Lote/Validade",tabReplenishment:"Pedido Automático",tabCarrier:"Transportadoras",tabCombine:"Embalagem Combinada",tabTracking:"Rastreamento",tabAudit:"Inventário",tabInvoice:"Fatura",tabBundle:"Kit/BOM",tabGuide:"Guia",tabSupplier:"Fornecedores",invTableTitle:"Status do Estoque por SKU",invColProduct:"Produto",invColTotal:"Total",invColSafe:"Estoque de Segurança",invColStatus:"Status",invColCost:"Custo",invColValue:"Valor do Estoque",invColAdj:"Ajuste",invSearchPh:"Buscar SKU ou produto...",invLowOnly:"Apenas estoque baixo",invNoResult:"Nenhum resultado",invNormal:"Normal",invLow:"Baixo",invOutOfStock:"Esgotado",invTotalStock:"Estoque Total",whListTitle:"Lista de Armazéns",whAddBtn:"+ Adicionar Armazém",whCancelBtn:"Cancelar",whSaveBtn:"Salvar",ioFilterAll:"Todos",ioFilterInbound:"Entrada",ioFilterOutbound:"Saída",csvImportBtn:"Importar CSV",exportCsvBtn:"Exportar CSV",exportExcelBtn:"Exportar Excel",guideHeroTitle:"Guia Completo WMS",guideQuickStart:"Início Rápido"},
ru:{wmsHeroTitle:"Единое Управление Складом WMS",wmsHeroDesc:"Регистрация склада · Приход/Расход · Запасы · Комплекты · Доставка · Счета",wmsAssetValue:"Общая Стоимость Запасов",tabWarehouse:"Склад WMS",tabInOut:"Приход/Расход",tabInventory:"Состояние Запасов",tabReceiving:"Приёмка",tabPicking:"Комплектация/Упаковка",tabLot:"Партия/Срок Годности",tabReplenishment:"Автозаказ",tabCarrier:"Перевозчики",tabCombine:"Объединение",tabTracking:"Отслеживание",tabAudit:"Инвентаризация",tabInvoice:"Счёт-фактура",tabBundle:"Комплект/BOM",tabGuide:"Руководство",tabSupplier:"Поставщики",invTableTitle:"Состояние Запасов по SKU",invColProduct:"Товар",invColTotal:"Итого",invColSafe:"Безопасный Запас",invColStatus:"Статус",invColCost:"Стоимость",invColValue:"Стоимость Запасов",invColAdj:"Корректировка",invSearchPh:"Поиск SKU или товара...",invLowOnly:"Только низкий запас",invNoResult:"Нет результатов",invNormal:"Норма",invLow:"Низкий",invOutOfStock:"Нет в наличии",invTotalStock:"Общий Запас",whListTitle:"Список Складов",whAddBtn:"+ Добавить Склад",whCancelBtn:"Отмена",whSaveBtn:"Сохранить",ioFilterAll:"Все",ioFilterInbound:"Приход",ioFilterOutbound:"Расход",csvImportBtn:"Импорт CSV",exportCsvBtn:"Экспорт CSV",exportExcelBtn:"Экспорт Excel",guideHeroTitle:"Полное Руководство WMS",guideQuickStart:"Быстрый Старт"},
ar:{wmsHeroTitle:"إدارة المستودعات الموحدة WMS",wmsHeroDesc:"تسجيل المستودع · الوارد/الصادر · المخزون · الحزم · الشحن · الفواتير",wmsAssetValue:"إجمالي قيمة المخزون",tabWarehouse:"مستودع WMS",tabInOut:"وارد/صادر",tabInventory:"حالة المخزون",tabReceiving:"استلام",tabPicking:"التقاط/تعبئة",tabLot:"دفعة/تاريخ الانتهاء",tabReplenishment:"طلب تلقائي",tabCarrier:"شركات الشحن",tabCombine:"دمج الشحنات",tabTracking:"تتبع الشحن",tabAudit:"جرد المخزون",tabInvoice:"فاتورة",tabBundle:"حزمة/BOM",tabGuide:"دليل",tabSupplier:"الموردون",invTableTitle:"حالة المخزون حسب SKU",invColProduct:"المنتج",invColTotal:"الإجمالي",invColSafe:"مخزون الأمان",invColStatus:"الحالة",invColCost:"التكلفة",invColValue:"قيمة المخزون",invColAdj:"تعديل",invSearchPh:"بحث SKU أو منتج...",invLowOnly:"المخزون المنخفض فقط",invNoResult:"لا توجد نتائج",invNormal:"عادي",invLow:"منخفض",invOutOfStock:"نفد المخزون",invTotalStock:"إجمالي المخزون",whListTitle:"قائمة المستودعات",whAddBtn:"+ إضافة مستودع",whCancelBtn:"إلغاء",whSaveBtn:"حفظ",ioFilterAll:"الكل",ioFilterInbound:"وارد",ioFilterOutbound:"صادر",csvImportBtn:"استيراد CSV",exportCsvBtn:"تصدير CSV",exportExcelBtn:"تصدير Excel",guideHeroTitle:"دليل إدارة المستودعات الشامل",guideQuickStart:"البدء السريع"},
hi:{wmsHeroTitle:"WMS वेयरहाउस एकीकृत प्रबंधन",wmsHeroDesc:"गोदाम पंजीकरण · आवक/जावक · स्टॉक · बंडल · शिपिंग · चालान",wmsAssetValue:"कुल इन्वेंटरी मूल्य",tabWarehouse:"WMS गोदाम",tabInOut:"आवक/जावक",tabInventory:"स्टॉक स्थिति",tabReceiving:"माल प्राप्ति",tabPicking:"पिकिंग/पैकिंग",tabLot:"लॉट/समाप्ति तिथि",tabReplenishment:"ऑटो ऑर्डर",tabCarrier:"वाहक",tabCombine:"संयुक्त पैकेजिंग",tabTracking:"शिपमेंट ट्रैकिंग",tabAudit:"स्टॉक ऑडिट",tabInvoice:"चालान",tabBundle:"बंडल/BOM",tabGuide:"गाइड",tabSupplier:"आपूर्तिकर्ता",invTableTitle:"SKU द्वारा स्टॉक स्थिति",invColProduct:"उत्पाद",invColTotal:"कुल",invColSafe:"सुरक्षित स्टॉक",invColStatus:"स्थिति",invColCost:"लागत",invColValue:"स्टॉक मूल्य",invColAdj:"समायोजन",invSearchPh:"SKU या उत्पाद खोजें...",invLowOnly:"केवल कम स्टॉक",invNoResult:"कोई परिणाम नहीं",invNormal:"सामान्य",invLow:"कम",invOutOfStock:"स्टॉक में नहीं",invTotalStock:"कुल स्टॉक",whListTitle:"गोदाम सूची",whAddBtn:"+ गोदाम जोड़ें",whCancelBtn:"रद्द करें",whSaveBtn:"सहेजें",ioFilterAll:"सभी",ioFilterInbound:"आवक",ioFilterOutbound:"जावक",csvImportBtn:"CSV आयात",exportCsvBtn:"CSV निर्यात",exportExcelBtn:"Excel निर्यात",guideHeroTitle:"WMS गोदाम प्रबंधन गाइड",guideQuickStart:"त्वरित शुरुआत"}
};
const files=fs.readdirSync(dir).filter(f=>f.endsWith('.js'));
let count=0;
for(const file of files){
  const lang=file.replace('.js','');
  const native=T[lang];
  if(!native)continue;
  const fp=path.join(dir,file);
  let src=fs.readFileSync(fp,'utf8');
  delete require.cache[require.resolve(fp)];
  const mod=require(fp);
  const obj=mod.default||mod;
  if(!obj.wms){console.log(`SKIP ${lang}`);continue;}
  const merged={...obj.wms,...native};
  const wmsStart=src.indexOf('"wms"');
  if(wmsStart===-1)continue;
  const braceStart=src.indexOf('{',wmsStart+5);
  let depth=1,pos=braceStart+1;
  while(depth>0&&pos<src.length){if(src[pos]==='{')depth++;else if(src[pos]==='}')depth--;pos++;}
  src=src.slice(0,wmsStart)+'"wms":'+JSON.stringify(merged)+src.slice(pos);
  fs.writeFileSync(fp,src,'utf8');
  console.log(`OK ${lang}: ${Object.keys(native).length} keys`);
  count++;
}
console.log(`Done: ${count} files`);
