/**
 * fix_dash_marketing_keys.cjs — Fix remaining English fallback dash keys in 5 locale files
 * Targets: es, fr, pt, ru, hi
 */
const fs = require('fs');
const path = require('path');

const LOCALES_DIR = path.join(__dirname, 'src', 'i18n', 'locales');

// Key-value pairs that need to be translated from English to each language
const FIXES = {
  es: {
    '"totalRev": "Total Revenue"': '"totalRev": "Ingresos Totales"',
    '"totalSpend": "Total Spend"': '"totalSpend": "Gasto Total"',
    '"blendedRoas": "Blended ROAS"': '"blendedRoas": "ROAS Combinado"',
    '"activeCh": "Active Channels"': '"activeCh": "Canales Activos"',
    '"totalClicks": "Total Clicks"': '"totalClicks": "Clics Totales"',
    '"avgCtr": "Avg CTR"': '"avgCtr": "CTR Promedio"',
    '"allChSummary": "All Channel Summary"': '"allChSummary": "Resumen de Todos los Canales"',
    '"allChSummary": "ALL CHANNEL SUMMARY"': '"allChSummary": "Resumen de Todos los Canales"',
    '"chTrend": "Channel Trend"': '"chTrend": "Tendencia del Canal"',
    '"chPerfSumm": "Channel Performance Summary"': '"chPerfSumm": "Resumen de Rendimiento del Canal"',
    '"clickChannelHint": "Click a channel card': '"clickChannelHint": "Haga clic en un canal',
    '"noChannelData": "No channel data"': '"noChannelData": "Sin datos de canal"',
    '"connectChannels": "Connect ad channels': '"connectChannels": "Conecte canales de anuncios',
    '"noTrendData": "No trend data"': '"noTrendData": "Sin datos de tendencia"',
    '"chName": "Channel"': '"chName": "Canal"',
    '"chName": "CHANNEL"': '"chName": "Canal"',
    '"rev": "Revenue"': '"rev": "Ingresos"',
    '"rev": "Rev"': '"rev": "Ingresos"',
    '"spendBudget": "Spend"': '"spendBudget": "Gasto"',
    '"adSpend": "Ad Spend"': '"adSpend": "Gasto Publicitario"',
    '"impressions": "Impressions"': '"impressions": "Impresiones"',
    '"reach": "Reach"': '"reach": "Alcance"',
    '"frequency": "Frequency"': '"frequency": "Frecuencia"',
    '"clicks": "Clicks"': '"clicks": "Clics"',
    '"sessions": "Sessions"': '"sessions": "Sesiones"',
    '"bounceRate": "Bounce Rate"': '"bounceRate": "Tasa de Rebote"',
    '"signups": "Signups"': '"signups": "Registros"',
    '"netProfit": "Net Profit"': '"netProfit": "Beneficio Neto"',
    '"convRate": "Conv. Rate"': '"convRate": "Tasa de Conv."',
    '"convRate": "Conv."': '"convRate": "Conv."',
    '"female": "Female"': '"female": "Femenino"',
    '"male": "Male"': '"male": "Masculino"',
  },
  fr: {
    '"totalRev": "Total Revenue"': '"totalRev": "Revenu Total"',
    '"totalSpend": "Total Spend"': '"totalSpend": "Dépense Totale"',
    '"blendedRoas": "Blended ROAS"': '"blendedRoas": "ROAS Combiné"',
    '"activeCh": "Active Channels"': '"activeCh": "Canaux Actifs"',
    '"totalClicks": "Total Clicks"': '"totalClicks": "Clics Totaux"',
    '"avgCtr": "Avg CTR"': '"avgCtr": "CTR Moyen"',
    '"allChSummary": "All Channel Summary"': '"allChSummary": "Résumé de Tous les Canaux"',
    '"allChSummary": "ALL CHANNEL SUMMARY"': '"allChSummary": "Résumé de Tous les Canaux"',
    '"chTrend": "Channel Trend"': '"chTrend": "Tendance du Canal"',
    '"chPerfSumm": "Channel Performance Summary"': '"chPerfSumm": "Résumé des Performances du Canal"',
    '"clickChannelHint": "Click a channel card': '"clickChannelHint": "Cliquez sur un canal',
    '"noChannelData": "No channel data"': '"noChannelData": "Aucune donnée de canal"',
    '"connectChannels": "Connect ad channels': '"connectChannels": "Connectez les canaux publicitaires',
    '"noTrendData": "No trend data"': '"noTrendData": "Aucune donnée de tendance"',
    '"chName": "Channel"': '"chName": "Canal"',
    '"chName": "CHANNEL"': '"chName": "Canal"',
    '"rev": "Revenue"': '"rev": "Revenu"',
    '"rev": "Rev"': '"rev": "Revenu"',
    '"spendBudget": "Spend"': '"spendBudget": "Dépense"',
    '"adSpend": "Ad Spend"': '"adSpend": "Dépense Publicitaire"',
    '"impressions": "Impressions"': '"impressions": "Impressions"',
    '"reach": "Reach"': '"reach": "Portée"',
    '"frequency": "Frequency"': '"frequency": "Fréquence"',
    '"clicks": "Clicks"': '"clicks": "Clics"',
    '"sessions": "Sessions"': '"sessions": "Sessions"',
    '"bounceRate": "Bounce Rate"': '"bounceRate": "Taux de Rebond"',
    '"signups": "Signups"': '"signups": "Inscriptions"',
    '"netProfit": "Net Profit"': '"netProfit": "Bénéfice Net"',
    '"convRate": "Conv. Rate"': '"convRate": "Taux de Conv."',
    '"female": "Female"': '"female": "Femme"',
    '"male": "Male"': '"male": "Homme"',
  },
  pt: {
    '"totalRev": "Total Revenue"': '"totalRev": "Receita Total"',
    '"totalSpend": "Total Spend"': '"totalSpend": "Gasto Total"',
    '"blendedRoas": "Blended ROAS"': '"blendedRoas": "ROAS Combinado"',
    '"activeCh": "Active Channels"': '"activeCh": "Canais Ativos"',
    '"totalClicks": "Total Clicks"': '"totalClicks": "Cliques Totais"',
    '"avgCtr": "Avg CTR"': '"avgCtr": "CTR Médio"',
    '"allChSummary": "All Channel Summary"': '"allChSummary": "Resumo de Todos os Canais"',
    '"allChSummary": "ALL CHANNEL SUMMARY"': '"allChSummary": "Resumo de Todos os Canais"',
    '"chTrend": "Channel Trend"': '"chTrend": "Tendência do Canal"',
    '"chPerfSumm": "Channel Performance Summary"': '"chPerfSumm": "Resumo de Desempenho do Canal"',
    '"clickChannelHint": "Click a channel card': '"clickChannelHint": "Clique em um canal',
    '"noChannelData": "No channel data"': '"noChannelData": "Sem dados de canal"',
    '"connectChannels": "Connect ad channels': '"connectChannels": "Conecte canais de anúncio',
    '"noTrendData": "No trend data"': '"noTrendData": "Sem dados de tendência"',
    '"chName": "Channel"': '"chName": "Canal"',
    '"chName": "CHANNEL"': '"chName": "Canal"',
    '"rev": "Revenue"': '"rev": "Receita"',
    '"rev": "Rev"': '"rev": "Receita"',
    '"spendBudget": "Spend"': '"spendBudget": "Gasto"',
    '"adSpend": "Ad Spend"': '"adSpend": "Gasto em Anúncios"',
    '"impressions": "Impressions"': '"impressions": "Impressões"',
    '"reach": "Reach"': '"reach": "Alcance"',
    '"frequency": "Frequency"': '"frequency": "Frequência"',
    '"clicks": "Clicks"': '"clicks": "Cliques"',
    '"sessions": "Sessions"': '"sessions": "Sessões"',
    '"bounceRate": "Bounce Rate"': '"bounceRate": "Taxa de Rejeição"',
    '"signups": "Signups"': '"signups": "Cadastros"',
    '"netProfit": "Net Profit"': '"netProfit": "Lucro Líquido"',
    '"convRate": "Conv. Rate"': '"convRate": "Taxa de Conv."',
    '"female": "Female"': '"female": "Feminino"',
    '"male": "Male"': '"male": "Masculino"',
  },
  ru: {
    '"totalRev": "Total Revenue"': '"totalRev": "Общий доход"',
    '"totalSpend": "Total Spend"': '"totalSpend": "Общий расход"',
    '"blendedRoas": "Blended ROAS"': '"blendedRoas": "Средний ROAS"',
    '"activeCh": "Active Channels"': '"activeCh": "Активные каналы"',
    '"totalClicks": "Total Clicks"': '"totalClicks": "Всего кликов"',
    '"avgCtr": "Avg CTR"': '"avgCtr": "Средний CTR"',
    '"allChSummary": "All Channel Summary"': '"allChSummary": "Сводка по всем каналам"',
    '"allChSummary": "ALL CHANNEL SUMMARY"': '"allChSummary": "Сводка по всем каналам"',
    '"chTrend": "Channel Trend"': '"chTrend": "Тренд канала"',
    '"chPerfSumm": "Channel Performance Summary"': '"chPerfSumm": "Сводка эффективности каналов"',
    '"clickChannelHint": "Click a channel card': '"clickChannelHint": "Нажмите на канал',
    '"noChannelData": "No channel data"': '"noChannelData": "Нет данных по каналам"',
    '"connectChannels": "Connect ad channels': '"connectChannels": "Подключите рекламные каналы',
    '"noTrendData": "No trend data"': '"noTrendData": "Нет данных по трендам"',
    '"chName": "Channel"': '"chName": "Канал"',
    '"chName": "CHANNEL"': '"chName": "Канал"',
    '"rev": "Revenue"': '"rev": "Доход"',
    '"rev": "Rev"': '"rev": "Доход"',
    '"spendBudget": "Spend"': '"spendBudget": "Расход"',
    '"adSpend": "Ad Spend"': '"adSpend": "Рекламный расход"',
    '"impressions": "Impressions"': '"impressions": "Показы"',
    '"reach": "Reach"': '"reach": "Охват"',
    '"frequency": "Frequency"': '"frequency": "Частота"',
    '"clicks": "Clicks"': '"clicks": "Клики"',
    '"sessions": "Sessions"': '"sessions": "Сессии"',
    '"bounceRate": "Bounce Rate"': '"bounceRate": "Показатель отказов"',
    '"signups": "Signups"': '"signups": "Регистрации"',
    '"netProfit": "Net Profit"': '"netProfit": "Чистая прибыль"',
    '"convRate": "Conv. Rate"': '"convRate": "Конв."',
    '"female": "Female"': '"female": "Женский"',
    '"male": "Male"': '"male": "Мужской"',
  },
  hi: {
    '"totalRev": "Total Revenue"': '"totalRev": "कुल राजस्व"',
    '"totalSpend": "Total Spend"': '"totalSpend": "कुल खर्च"',
    '"blendedRoas": "Blended ROAS"': '"blendedRoas": "मिश्रित ROAS"',
    '"activeCh": "Active Channels"': '"activeCh": "सक्रिय चैनल"',
    '"totalClicks": "Total Clicks"': '"totalClicks": "कुल क्लिक"',
    '"avgCtr": "Avg CTR"': '"avgCtr": "औसत CTR"',
    '"allChSummary": "All Channel Summary"': '"allChSummary": "सभी चैनलों का सारांश"',
    '"allChSummary": "ALL CHANNEL SUMMARY"': '"allChSummary": "सभी चैनलों का सारांश"',
    '"chTrend": "Channel Trend"': '"chTrend": "चैनल रुझान"',
    '"chPerfSumm": "Channel Performance Summary"': '"chPerfSumm": "चैनल प्रदर्शन सारांश"',
    '"clickChannelHint": "Click a channel card': '"clickChannelHint": "चैनल कार्ड पर क्लिक करें',
    '"noChannelData": "No channel data"': '"noChannelData": "कोई चैनल डेटा नहीं"',
    '"connectChannels": "Connect ad channels': '"connectChannels": "विज्ञापन चैनल जोड़ें',
    '"noTrendData": "No trend data"': '"noTrendData": "कोई रुझान डेटा नहीं"',
    '"chName": "Channel"': '"chName": "चैनल"',
    '"chName": "CHANNEL"': '"chName": "चैनल"',
    '"rev": "Revenue"': '"rev": "राजस्व"',
    '"rev": "Rev"': '"rev": "राजस्व"',
    '"spendBudget": "Spend"': '"spendBudget": "खर्च"',
    '"adSpend": "Ad Spend"': '"adSpend": "विज्ञापन खर्च"',
    '"impressions": "Impressions"': '"impressions": "इंप्रेशन"',
    '"reach": "Reach"': '"reach": "पहुंच"',
    '"frequency": "Frequency"': '"frequency": "आवृत्ति"',
    '"clicks": "Clicks"': '"clicks": "क्लिक"',
    '"sessions": "Sessions"': '"sessions": "सत्र"',
    '"bounceRate": "Bounce Rate"': '"bounceRate": "बाउंस दर"',
    '"signups": "Signups"': '"signups": "साइनअप"',
    '"netProfit": "Net Profit"': '"netProfit": "शुद्ध लाभ"',
    '"convRate": "Conv. Rate"': '"convRate": "रूपांतरण"',
    '"female": "Female"': '"female": "महिला"',
    '"male": "Male"': '"male": "पुरुष"',
  },
};

for (const [lang, replacements] of Object.entries(FIXES)) {
  const filePath = path.join(LOCALES_DIR, `${lang}.js`);
  let content = fs.readFileSync(filePath, 'utf8');
  let count = 0;
  
  for (const [from, to] of Object.entries(replacements)) {
    const idx = content.indexOf(from);
    if (idx !== -1) {
      content = content.split(from).join(to);
      count++;
    }
  }
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`[OK] ${lang}.js — ${count} replacements`);
}

console.log('\nDone!');
