const fs=require('fs'),path=require('path'),D=path.join(__dirname,'src/i18n/locales');
function a(l,t){const f=path.join(D,l+'.js'),c=fs.readFileSync(f,'utf8'),m=c.match(/export\s+default\s+(\{[\s\S]*\})\s*;?\s*$/),o=eval('('+m[1]+')');if(!o.gNav)o.gNav={};Object.assign(o.gNav,t);fs.writeFileSync(f,'export default '+JSON.stringify(o)+'\n');console.log(l+':'+Object.keys(t).length+' gNav keys');}

// Thai sidebar labels
a('th',{commerceLabel:'คอมเมิร์ซและโลจิสติกส์',crmLabel:'CRM จัดการลูกค้า',feedbackLabel:'ความคิดเห็น',helpLabel:'ช่วยเหลือ',pricingLabel:'ราคา',settlementsLabel:'การเงินและชำระ',returnsPortalLabel:'พอร์ทัลคืนสินค้า',supplyChainLabel:'ซัพพลายเชน',priceOptLabel:'ปรับราคา',wmsLabel:'จัดการ WMS',orderHubLabel:'ศูนย์รวมคำสั่งซื้อ',catalogLabel:'ซิงค์แคตตาล็อก',omniChannelLabel:'ออมนิชาแนล',channelKpiLabel:'KPI ช่องทาง',attributionLabel:'การวิเคราะห์สื่อ',accountPerformanceLabel:'ประสิทธิภาพบัญชี',budgetTrackerLabel:'ติดตามงบประมาณ',adPerformanceLabel:'ประสิทธิภาพโฆษณา',journeyBuilderLabel:'สร้างเส้นทางลูกค้า',campaignManagerLabel:'จัดการแคมเปญ',autoMarketingLabel:'การตลาด AI อัตโนมัติ',rollupLabel:'สรุปรวม',dashboardLabel:'แดชบอร์ด',memberTools:'เครื่องมือสมาชิก',adminSystem:'ระบบจัดการ',budgetTracker:'ติดตามงบประมาณ',accountPerformance:'ประสิทธิภาพบัญชี',aiBudgetAllocator:'จัดสรรงบ AI'});

// Arabic sidebar labels  
a('ar',{commerceLabel:'التجارة والخدمات اللوجستية',crmLabel:'إدارة العملاء CRM',feedbackLabel:'التعليقات',helpLabel:'المساعدة',pricingLabel:'التسعير',settlementsLabel:'المالية والتسويات',returnsPortalLabel:'بوابة المرتجعات',supplyChainLabel:'سلسلة التوريد',priceOptLabel:'تحسين الأسعار',wmsLabel:'إدارة المستودعات WMS',orderHubLabel:'مركز الطلبات',catalogLabel:'مزامنة الكتالوج',omniChannelLabel:'القناة الشاملة',channelKpiLabel:'مؤشرات القناة',attributionLabel:'تحليل وسائل الإعلام',accountPerformanceLabel:'أداء الحساب',budgetTrackerLabel:'تتبع الميزانية',adPerformanceLabel:'أداء الإعلانات',journeyBuilderLabel:'بناء رحلة العميل',campaignManagerLabel:'إدارة الحملات',autoMarketingLabel:'التسويق الآلي بالذكاء',rollupLabel:'التقرير الموحد',dashboardLabel:'لوحة المعلومات',memberTools:'أدوات الأعضاء',adminSystem:'إدارة النظام',budgetTracker:'تتبع الميزانية',accountPerformance:'أداء الحساب',aiBudgetAllocator:'تخصيص الميزانية بالذكاء'});

// Hindi sidebar labels
a('hi',{commerceLabel:'कॉमर्स और लॉजिस्टिक्स',crmLabel:'CRM ग्राहक प्रबंधन',feedbackLabel:'प्रतिक्रिया',helpLabel:'सहायता',pricingLabel:'मूल्य निर्धारण',settlementsLabel:'वित्त और निपटान',returnsPortalLabel:'रिटर्न पोर्टल',supplyChainLabel:'आपूर्ति श्रृंखला',priceOptLabel:'मूल्य अनुकूलन',wmsLabel:'WMS प्रबंधन',orderHubLabel:'ऑर्डर हब',catalogLabel:'कैटलॉग सिंक',omniChannelLabel:'ऑम्नीचैनल',channelKpiLabel:'चैनल KPI',attributionLabel:'मीडिया विश्लेषण',accountPerformanceLabel:'खाता प्रदर्शन',budgetTrackerLabel:'बजट ट्रैकर',adPerformanceLabel:'विज्ञापन प्रदर्शन',journeyBuilderLabel:'ग्राहक यात्रा निर्माता',campaignManagerLabel:'अभियान प्रबंधक',autoMarketingLabel:'AI ऑटो मार्केटिंग',rollupLabel:'रोलअप सारांश',dashboardLabel:'डैशबोर्ड',memberTools:'सदस्य उपकरण',adminSystem:'सिस्टम प्रबंधन',budgetTracker:'बजट ट्रैकर',accountPerformance:'खाता प्रदर्शन',aiBudgetAllocator:'AI बजट आवंटक'});

// Vietnamese sidebar labels
a('vi',{commerceLabel:'Thương mại và Logistics',crmLabel:'Quản lý khách hàng CRM',feedbackLabel:'Phản hồi',helpLabel:'Trợ giúp',pricingLabel:'Định giá',settlementsLabel:'Tài chính và Thanh toán',returnsPortalLabel:'Cổng trả hàng',supplyChainLabel:'Chuỗi cung ứng',priceOptLabel:'Tối ưu giá',wmsLabel:'Quản lý WMS',orderHubLabel:'Trung tâm đơn hàng',catalogLabel:'Đồng bộ danh mục',omniChannelLabel:'Kênh tổng hợp',channelKpiLabel:'KPI Kênh',attributionLabel:'Phân tích phương tiện',accountPerformanceLabel:'Hiệu suất tài khoản',budgetTrackerLabel:'Theo dõi ngân sách',adPerformanceLabel:'Hiệu suất quảng cáo',journeyBuilderLabel:'Xây dựng hành trình',campaignManagerLabel:'Quản lý chiến dịch',autoMarketingLabel:'Marketing AI tự động',rollupLabel:'Tổng hợp',dashboardLabel:'Bảng điều khiển',memberTools:'Công cụ thành viên',adminSystem:'Quản lý hệ thống',budgetTracker:'Theo dõi ngân sách',accountPerformance:'Hiệu suất tài khoản',aiBudgetAllocator:'Phân bổ ngân sách AI'});

// Indonesian sidebar labels
a('id',{commerceLabel:'Perdagangan dan Logistik',crmLabel:'Manajemen Pelanggan CRM',feedbackLabel:'Umpan balik',helpLabel:'Bantuan',pricingLabel:'Harga',settlementsLabel:'Keuangan dan Penyelesaian',returnsPortalLabel:'Portal Retur',supplyChainLabel:'Rantai Pasokan',priceOptLabel:'Optimasi Harga',wmsLabel:'Manajemen WMS',orderHubLabel:'Pusat Pesanan',catalogLabel:'Sinkronisasi Katalog',omniChannelLabel:'Omni Channel',channelKpiLabel:'KPI Saluran',attributionLabel:'Analisis Media',accountPerformanceLabel:'Performa Akun',budgetTrackerLabel:'Pelacak Anggaran',adPerformanceLabel:'Performa Iklan',journeyBuilderLabel:'Pembangun Perjalanan',campaignManagerLabel:'Manajer Kampanye',autoMarketingLabel:'Pemasaran AI Otomatis',rollupLabel:'Ringkasan',dashboardLabel:'Dasbor',memberTools:'Alat Anggota',adminSystem:'Manajemen Sistem',budgetTracker:'Pelacak Anggaran',accountPerformance:'Performa Akun',aiBudgetAllocator:'Alokasi Anggaran AI'});

console.log('Done! All sidebar labels fixed.');
