const fs=require('fs');
const DIR='src/i18n/locales/';
const NAV={
ko:{home:"홈 대시보드",dashboardLabel:"종합 대시보드",rollupLabel:"롤업 뷰",aiMarketing:"AI 마케팅",autoMarketingLabel:"자동화 전략",campaignManagerLabel:"캠페인 관리",journeyBuilderLabel:"여정 빌더",adAnalytics:"광고 및 채널 분석",adPerformanceLabel:"광고성과",budgetTrackerLabel:"예산 관리",accountPerformanceLabel:"어카운트 성과",attributionLabel:"어트리뷰션",channelKpiLabel:"채널 KPI",graphScoreLabel:"그래프 스코어",crmLabel:"고객/CRM",crmMainLabel:"CRM 대시보드",kakaoChannelLabel:"카카오 비즈니스",emailMarketingLabel:"이메일 마케팅",smsMarketingLabel:"SMS 마케팅",influencerLabel:"인플루언서",contentCalendarLabel:"콘텐츠 캘린더",reviewsUgcLabel:"리뷰 및 UGC",webPopupLabel:"웹 팝업",commerceLabel:"커머스 및 물류",omniChannelLabel:"옴니 채널",catalogLabel:"카탈로그 동기화",orderHubLabel:"주문 허브",wmsLabel:"WMS 재고관리",priceOptLabel:"최적 가격 설정",supplyChainLabel:"공급망 관리",returnsPortalLabel:"반품 포털",analytics:"성과 및 리포팅",performanceHubLabel:"퍼포먼스 인사이트",pnlLabel:"P&L 손익",aiInsightsLabel:"AI 인사이트",reportBuilderLabel:"리포트 빌더",dataProductLabel:"데이터 프로덕트",automation:"자동화 및 AI 규칙",aiRuleEngineLabel:"AI 룰 엔진",approvalsLabel:"결재 센터",writebackLabel:"데이터 라이트백",data:"데이터 및 수집",dataSchemaLabel:"데이터 스키마",dataTrustLabel:"데이터 신뢰성",finance:"재무 및 정산",reconciliationLabel:"정산 대조",settlementsLabel:"결제 내역",pricingLabel:"플랜 및 업그레이드",auditLogLabel:"보안 감사 로그",memberTools:"멤버 구성원 도구",workspaceLabel:"워크스페이스 설정",operationsLabel:"운영 실행 목록",caseStudyLabel:"성공 사례",helpLabel:"플랫폼 가이드",feedbackLabel:"의견/피드백",developerHubLabel:"개발자 포털",adminSystem:"관리자 시스템",platformEnvLabel:"관리자 환경",dbSchemaLabel:"DB 어드민",paymentPgLabel:"게이트웨이 관리",integrationHubLabel:"연동 허브",onboardingLabel:"온보딩 맵"},
en:{home:"Home",dashboardLabel:"Dashboard",rollupLabel:"Rollup View",aiMarketing:"AI Marketing",autoMarketingLabel:"Auto Strategy",campaignManagerLabel:"Campaign Manager",journeyBuilderLabel:"Journey Builder",adAnalytics:"Ad & Channel Analytics",adPerformanceLabel:"Ad Performance",budgetTrackerLabel:"Budget Tracker",accountPerformanceLabel:"Account Performance",attributionLabel:"Attribution",channelKpiLabel:"Channel KPI",graphScoreLabel:"Graph Score",crmLabel:"CRM",crmMainLabel:"CRM Dashboard",kakaoChannelLabel:"Kakao Business",emailMarketingLabel:"Email Marketing",smsMarketingLabel:"SMS Marketing",influencerLabel:"Influencer",contentCalendarLabel:"Content Calendar",reviewsUgcLabel:"Reviews & UGC",webPopupLabel:"Web Popup",commerceLabel:"Commerce & Logistics",omniChannelLabel:"Omni Channel",catalogLabel:"Catalog Sync",orderHubLabel:"Order Hub",wmsLabel:"WMS Inventory",priceOptLabel:"Price Optimization",supplyChainLabel:"Supply Chain",returnsPortalLabel:"Returns Portal",analytics:"Analytics & Reporting",performanceHubLabel:"Performance Hub",pnlLabel:"P&L",aiInsightsLabel:"AI Insights",reportBuilderLabel:"Report Builder",dataProductLabel:"Data Product",automation:"Automation & AI Rules",aiRuleEngineLabel:"AI Rule Engine",approvalsLabel:"Approvals",writebackLabel:"Writeback",data:"Data & Collection",dataSchemaLabel:"Data Schema",dataTrustLabel:"Data Trust",finance:"Finance & Settlement",reconciliationLabel:"Reconciliation",settlementsLabel:"Settlements",pricingLabel:"Plans & Upgrade",auditLogLabel:"Audit Log",memberTools:"Team Tools",workspaceLabel:"Workspace",operationsLabel:"Operations",caseStudyLabel:"Case Studies",helpLabel:"Platform Guide",feedbackLabel:"Feedback",developerHubLabel:"Developer Hub",adminSystem:"Admin System",platformEnvLabel:"Admin Settings",dbSchemaLabel:"DB Admin",paymentPgLabel:"Payment Gateway",integrationHubLabel:"Integration Hub",onboardingLabel:"Onboarding"},
ja:{home:"ホーム",dashboardLabel:"ダッシュボード",rollupLabel:"ロールアップ",aiMarketing:"AIマーケティング",autoMarketingLabel:"自動化戦略",campaignManagerLabel:"キャンペーン管理",journeyBuilderLabel:"ジャーニービルダー",adAnalytics:"広告・チャネル分析",adPerformanceLabel:"広告成果",budgetTrackerLabel:"予算管理",accountPerformanceLabel:"アカウント成果",attributionLabel:"アトリビューション",channelKpiLabel:"チャネルKPI",graphScoreLabel:"グラフスコア",crmLabel:"CRM",crmMainLabel:"CRMダッシュボード",kakaoChannelLabel:"カカオビジネス",emailMarketingLabel:"メールマーケティング",smsMarketingLabel:"SMSマーケティング",influencerLabel:"インフルエンサー",contentCalendarLabel:"コンテンツカレンダー",reviewsUgcLabel:"レビュー＆UGC",webPopupLabel:"Webポップアップ",commerceLabel:"コマース・物流",omniChannelLabel:"オムニチャネル",catalogLabel:"カタログ同期",orderHubLabel:"注文ハブ",wmsLabel:"WMS在庫管理",priceOptLabel:"価格最適化",supplyChainLabel:"サプライチェーン",returnsPortalLabel:"返品ポータル",analytics:"分析・レポート",performanceHubLabel:"パフォーマンス",pnlLabel:"P&L損益",aiInsightsLabel:"AIインサイト",reportBuilderLabel:"レポートビルダー",dataProductLabel:"データプロダクト",automation:"自動化・AIルール",aiRuleEngineLabel:"AIルールエンジン",approvalsLabel:"承認センター",writebackLabel:"ライトバック",data:"データ・収集",dataSchemaLabel:"データスキーマ",dataTrustLabel:"データ信頼性",finance:"財務・精算",reconciliationLabel:"精算照合",settlementsLabel:"決済履歴",pricingLabel:"プラン・アップグレード",auditLogLabel:"監査ログ",memberTools:"メンバーツール",workspaceLabel:"ワークスペース",operationsLabel:"運営実行",caseStudyLabel:"成功事例",helpLabel:"ガイド",feedbackLabel:"フィードバック",developerHubLabel:"開発者ポータル",adminSystem:"管理者システム",platformEnvLabel:"管理者設定",dbSchemaLabel:"DB管理",paymentPgLabel:"PG管理",integrationHubLabel:"連携ハブ",onboardingLabel:"オンボーディング"},
zh:{home:"首页",dashboardLabel:"综合仪表盘",rollupLabel:"汇总视图",aiMarketing:"AI营销",autoMarketingLabel:"自动化策略",campaignManagerLabel:"活动管理",journeyBuilderLabel:"旅程构建",adAnalytics:"广告与渠道分析",adPerformanceLabel:"广告效果",budgetTrackerLabel:"预算管理",accountPerformanceLabel:"账户绩效",attributionLabel:"归因分析",channelKpiLabel:"渠道KPI",graphScoreLabel:"图谱评分",crmLabel:"CRM",crmMainLabel:"CRM仪表盘",kakaoChannelLabel:"Kakao商务",emailMarketingLabel:"邮件营销",smsMarketingLabel:"短信营销",influencerLabel:"达人管理",contentCalendarLabel:"内容日历",reviewsUgcLabel:"评论与UGC",webPopupLabel:"网页弹窗",commerceLabel:"电商与物流",omniChannelLabel:"全渠道",catalogLabel:"目录同步",orderHubLabel:"订单中心",wmsLabel:"WMS库存",priceOptLabel:"价格优化",supplyChainLabel:"供应链",returnsPortalLabel:"退货门户",analytics:"分析与报表",performanceHubLabel:"绩效中心",pnlLabel:"损益表",aiInsightsLabel:"AI洞察",reportBuilderLabel:"报表构建",dataProductLabel:"数据产品",automation:"自动化与AI规则",aiRuleEngineLabel:"AI规则引擎",approvalsLabel:"审批中心",writebackLabel:"数据回写",data:"数据与采集",dataSchemaLabel:"数据模式",dataTrustLabel:"数据可信度",finance:"财务与结算",reconciliationLabel:"对账",settlementsLabel:"结算记录",pricingLabel:"套餐升级",auditLogLabel:"审计日志",memberTools:"团队工具",workspaceLabel:"工作区",operationsLabel:"运营执行",caseStudyLabel:"成功案例",helpLabel:"平台指南",feedbackLabel:"反馈",developerHubLabel:"开发者门户",adminSystem:"管理系统",platformEnvLabel:"管理设置",dbSchemaLabel:"DB管理",paymentPgLabel:"支付网关",integrationHubLabel:"集成中心",onboardingLabel:"引导"},
};
NAV["zh-TW"]={...NAV.zh,home:"首頁",dashboardLabel:"綜合儀表板",rollupLabel:"匯總視圖",commerceLabel:"電商與物流",catalogLabel:"目錄同步",orderHubLabel:"訂單中心",supplyChainLabel:"供應鏈",returnsPortalLabel:"退貨門戶",analytics:"分析與報表",pricingLabel:"方案升級",auditLogLabel:"稽核日誌"};
NAV.de={...NAV.en,home:"Startseite",dashboardLabel:"Dashboard",aiMarketing:"AI-Marketing",adAnalytics:"Werbeanalyse",crmLabel:"Kundenmanagement",commerceLabel:"Handel & Logistik",analytics:"Analyse & Berichte",automation:"Automatisierung",data:"Daten & Erfassung",finance:"Finanzen & Abrechnung",memberTools:"Team-Tools",adminSystem:"Verwaltung"};
NAV.fr={...NAV.en,home:"Accueil",dashboardLabel:"Tableau de bord",aiMarketing:"Marketing IA",adAnalytics:"Analyse pub",crmLabel:"Gestion clients",commerceLabel:"Commerce & Logistique",analytics:"Analyse & Rapports",automation:"Automatisation",data:"Données & Collecte",finance:"Finances & Règlement",memberTools:"Outils d'équipe",adminSystem:"Administration"};
NAV.es={...NAV.en,home:"Inicio",dashboardLabel:"Panel de control",aiMarketing:"Marketing IA",adAnalytics:"Análisis de anuncios",crmLabel:"Gestión de clientes",commerceLabel:"Comercio y Logística",analytics:"Análisis e Informes",automation:"Automatización",data:"Datos y Recolección",finance:"Finanzas y Liquidación",memberTools:"Herramientas de equipo",adminSystem:"Administración"};
NAV.th={...NAV.en,home:"หน้าแรก",dashboardLabel:"แดชบอร์ด",aiMarketing:"การตลาด AI",crmLabel:"CRM",commerceLabel:"อีคอมเมิร์ซ",analytics:"การวิเคราะห์",automation:"ระบบอัตโนมัติ",data:"ข้อมูล",finance:"การเงิน",memberTools:"เครื่องมือทีม",adminSystem:"ระบบผู้ดูแล"};
NAV.vi={...NAV.en,home:"Trang chủ",dashboardLabel:"Bảng điều khiển",aiMarketing:"Marketing AI",crmLabel:"CRM",commerceLabel:"Thương mại & Logistics",analytics:"Phân tích & Báo cáo",automation:"Tự động hoá",data:"Dữ liệu",finance:"Tài chính",memberTools:"Công cụ nhóm",adminSystem:"Quản trị"};
NAV.id={...NAV.en,home:"Beranda",dashboardLabel:"Dasbor",aiMarketing:"Pemasaran AI",crmLabel:"CRM",commerceLabel:"Perdagangan & Logistik",analytics:"Analitik & Laporan",automation:"Otomatisasi",data:"Data & Koleksi",finance:"Keuangan",memberTools:"Alat Tim",adminSystem:"Administrasi"};
NAV.pt={...NAV.en,home:"Início",commerceLabel:"Comércio e Logística",analytics:"Análise e Relatórios",adminSystem:"Administração"};
NAV.ru={...NAV.en,home:"Главная",commerceLabel:"Торговля и логистика",analytics:"Аналитика и отчёты",adminSystem:"Администрирование"};
NAV.ar={...NAV.en,home:"الرئيسية",commerceLabel:"التجارة والخدمات اللوجستية",analytics:"التحليلات والتقارير",adminSystem:"الإدارة"};
NAV.hi={...NAV.en,home:"होम",commerceLabel:"वाणिज्य और रसद",analytics:"विश्लेषण और रिपोर्ट",adminSystem:"प्रशासन"};

const LANGS=['ko','en','ja','zh','zh-TW','de','th','vi','id','fr','es','pt','ru','ar','hi'];
LANGS.forEach(lang=>{
  const p=DIR+lang+'.js';
  let src=fs.readFileSync(p,'utf8');
  const nav=NAV[lang]||NAV.en;
  // Build gNav assignment
  const pairs=Object.entries(nav).map(([k,v])=>`    ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(',\n');
  const block=`\n// ── gNav sidebar labels (auto-injected) ──\n${lang==='zh-TW'?'zhTW':lang}.gNav = Object.assign(${lang==='zh-TW'?'zhTW':lang}.gNav || {}, {\n${pairs}\n});\n`;
  // Remove any existing gNav injection block first
  src=src.replace(/\n\/\/ ── gNav sidebar labels[\s\S]*?\}\);\n/g,'');
  // Find the last line before export (or end of file)
  const exportMatch=src.match(/export\s+default\s+/);
  if(exportMatch){
    src=src.slice(0,exportMatch.index)+block+'\n'+src.slice(exportMatch.index);
  } else {
    src+=block;
  }
  fs.writeFileSync(p,src);
  console.log(lang+': injected '+Object.keys(nav).length+' gNav keys');
});
