// Inject missing gNav keys DIRECTLY into the gNav object (not via Object.assign)
const fs=require('fs');
const DIR='src/i18n/locales/';
const NAV={
ko:{dashboardLabel:"종합 대시보드",rollupLabel:"롤업 뷰",autoMarketingLabel:"자동화 전략",campaignManagerLabel:"캠페인 관리",journeyBuilderLabel:"여정 빌더",adPerformanceLabel:"광고성과",budgetTrackerLabel:"예산 관리",accountPerformanceLabel:"어카운트 성과",attributionLabel:"어트리뷰션",channelKpiLabel:"채널 KPI",graphScoreLabel:"그래프 스코어",crmLabel:"고객/CRM",crmMainLabel:"CRM 대시보드",kakaoChannelLabel:"카카오 비즈니스",emailMarketingLabel:"이메일 마케팅",smsMarketingLabel:"SMS 마케팅",influencerLabel:"인플루언서",contentCalendarLabel:"콘텐츠 캘린더",reviewsUgcLabel:"리뷰 및 UGC",webPopupLabel:"웹 팝업",commerceLabel:"커머스 및 물류",omniChannelLabel:"옴니 채널",catalogLabel:"카탈로그 동기화",orderHubLabel:"주문 허브",wmsLabel:"WMS 재고관리",priceOptLabel:"최적 가격 설정",supplyChainLabel:"공급망 관리",returnsPortalLabel:"반품 포털",performanceHubLabel:"퍼포먼스 인사이트",pnlLabel:"P&L 손익",aiInsightsLabel:"AI 인사이트",reportBuilderLabel:"리포트 빌더",dataProductLabel:"데이터 프로덕트",aiRuleEngineLabel:"AI 룰 엔진",approvalsLabel:"결재 센터",writebackLabel:"데이터 라이트백",dataSchemaLabel:"데이터 스키마",dataTrustLabel:"데이터 신뢰성",reconciliationLabel:"정산 대조",settlementsLabel:"결제 내역",pricingLabel:"플랜 및 업그레이드",auditLogLabel:"보안 감사 로그",workspaceLabel:"워크스페이스 설정",operationsLabel:"운영 실행 목록",caseStudyLabel:"성공 사례",helpLabel:"플랫폼 가이드",feedbackLabel:"의견/피드백",developerHubLabel:"개발자 포털",adminSystem:"관리자 시스템",platformEnvLabel:"관리자 환경",dbSchemaLabel:"DB 어드민",paymentPgLabel:"게이트웨이 관리",integrationHubLabel:"연동 허브",onboardingLabel:"온보딩 맵"},
en:{dashboardLabel:"Dashboard",rollupLabel:"Rollup View",autoMarketingLabel:"Auto Strategy",campaignManagerLabel:"Campaign Manager",journeyBuilderLabel:"Journey Builder",adPerformanceLabel:"Ad Performance",budgetTrackerLabel:"Budget Tracker",accountPerformanceLabel:"Account Performance",attributionLabel:"Attribution",channelKpiLabel:"Channel KPI",graphScoreLabel:"Graph Score",crmLabel:"CRM",crmMainLabel:"CRM Dashboard",kakaoChannelLabel:"Kakao Business",emailMarketingLabel:"Email Marketing",smsMarketingLabel:"SMS Marketing",influencerLabel:"Influencer",contentCalendarLabel:"Content Calendar",reviewsUgcLabel:"Reviews & UGC",webPopupLabel:"Web Popup",commerceLabel:"Commerce & Logistics",omniChannelLabel:"Omni Channel",catalogLabel:"Catalog Sync",orderHubLabel:"Order Hub",wmsLabel:"WMS Inventory",priceOptLabel:"Price Optimization",supplyChainLabel:"Supply Chain",returnsPortalLabel:"Returns Portal",performanceHubLabel:"Performance Hub",pnlLabel:"P&L",aiInsightsLabel:"AI Insights",reportBuilderLabel:"Report Builder",dataProductLabel:"Data Product",aiRuleEngineLabel:"AI Rule Engine",approvalsLabel:"Approvals",writebackLabel:"Writeback",dataSchemaLabel:"Data Schema",dataTrustLabel:"Data Trust",reconciliationLabel:"Reconciliation",settlementsLabel:"Settlements",pricingLabel:"Plans & Upgrade",auditLogLabel:"Audit Log",workspaceLabel:"Workspace",operationsLabel:"Operations",caseStudyLabel:"Case Studies",helpLabel:"Platform Guide",feedbackLabel:"Feedback",developerHubLabel:"Developer Hub",adminSystem:"Admin System",platformEnvLabel:"Admin Settings",dbSchemaLabel:"DB Admin",paymentPgLabel:"Payment Gateway",integrationHubLabel:"Integration Hub",onboardingLabel:"Onboarding"},
ja:{dashboardLabel:"ダッシュボード",rollupLabel:"ロールアップ",autoMarketingLabel:"自動化戦略",campaignManagerLabel:"キャンペーン管理",journeyBuilderLabel:"ジャーニービルダー",adPerformanceLabel:"広告成果",budgetTrackerLabel:"予算管理",accountPerformanceLabel:"アカウント成果",attributionLabel:"アトリビューション",channelKpiLabel:"チャネルKPI",graphScoreLabel:"グラフスコア",crmLabel:"CRM",crmMainLabel:"CRMダッシュボード",kakaoChannelLabel:"カカオビジネス",emailMarketingLabel:"メールマーケティング",smsMarketingLabel:"SMSマーケティング",influencerLabel:"インフルエンサー",contentCalendarLabel:"コンテンツカレンダー",reviewsUgcLabel:"レビュー＆UGC",webPopupLabel:"Webポップアップ",commerceLabel:"コマース・物流",omniChannelLabel:"オムニチャネル",catalogLabel:"カタログ同期",orderHubLabel:"注文ハブ",wmsLabel:"WMS在庫管理",priceOptLabel:"価格最適化",supplyChainLabel:"サプライチェーン",returnsPortalLabel:"返品ポータル",performanceHubLabel:"パフォーマンス",pnlLabel:"P&L損益",aiInsightsLabel:"AIインサイト",reportBuilderLabel:"レポートビルダー",dataProductLabel:"データプロダクト",aiRuleEngineLabel:"AIルールエンジン",approvalsLabel:"承認センター",writebackLabel:"ライトバック",dataSchemaLabel:"データスキーマ",dataTrustLabel:"データ信頼性",reconciliationLabel:"精算照合",settlementsLabel:"決済履歴",pricingLabel:"プラン",auditLogLabel:"監査ログ",workspaceLabel:"ワークスペース",operationsLabel:"運営実行",caseStudyLabel:"成功事例",helpLabel:"ガイド",feedbackLabel:"フィードバック",developerHubLabel:"開発者ポータル",adminSystem:"管理者システム",platformEnvLabel:"管理者設定",dbSchemaLabel:"DB管理",paymentPgLabel:"PG管理",integrationHubLabel:"連携ハブ",onboardingLabel:"オンボーディング"},
zh:{dashboardLabel:"综合仪表盘",rollupLabel:"汇总视图",autoMarketingLabel:"自动化策略",campaignManagerLabel:"活动管理",journeyBuilderLabel:"旅程构建",adPerformanceLabel:"广告效果",budgetTrackerLabel:"预算管理",accountPerformanceLabel:"账户绩效",attributionLabel:"归因分析",channelKpiLabel:"渠道KPI",graphScoreLabel:"图谱评分",crmLabel:"CRM",crmMainLabel:"CRM仪表盘",kakaoChannelLabel:"Kakao商务",emailMarketingLabel:"邮件营销",smsMarketingLabel:"短信营销",influencerLabel:"达人管理",contentCalendarLabel:"内容日历",reviewsUgcLabel:"评论与UGC",webPopupLabel:"网页弹窗",commerceLabel:"电商与物流",omniChannelLabel:"全渠道",catalogLabel:"目录同步",orderHubLabel:"订单中心",wmsLabel:"WMS库存",priceOptLabel:"价格优化",supplyChainLabel:"供应链",returnsPortalLabel:"退货门户",performanceHubLabel:"绩效中心",pnlLabel:"损益表",aiInsightsLabel:"AI洞察",reportBuilderLabel:"报表构建",dataProductLabel:"数据产品",aiRuleEngineLabel:"AI规则引擎",approvalsLabel:"审批中心",writebackLabel:"数据回写",dataSchemaLabel:"数据模式",dataTrustLabel:"数据可信度",reconciliationLabel:"对账",settlementsLabel:"结算记录",pricingLabel:"套餐升级",auditLogLabel:"审计日志",workspaceLabel:"工作区",operationsLabel:"运营执行",caseStudyLabel:"成功案例",helpLabel:"平台指南",feedbackLabel:"反馈",developerHubLabel:"开发者门户",adminSystem:"管理系统",platformEnvLabel:"管理设置",dbSchemaLabel:"DB管理",paymentPgLabel:"支付网关",integrationHubLabel:"集成中心",onboardingLabel:"引导"},
th:{dashboardLabel:"แดชบอร์ด",rollupLabel:"สรุปภาพรวม",autoMarketingLabel:"กลยุทธ์อัตโนมัติ",campaignManagerLabel:"จัดการแคมเปญ",journeyBuilderLabel:"ตัวสร้างเส้นทาง",adPerformanceLabel:"ผลลัพธ์โฆษณา",budgetTrackerLabel:"ติดตามงบ",accountPerformanceLabel:"ผลลัพธ์บัญชี",attributionLabel:"การระบุแหล่งที่มา",channelKpiLabel:"KPI ช่องทาง",graphScoreLabel:"คะแนนกราฟ",crmLabel:"CRM",crmMainLabel:"แดชบอร์ด CRM",kakaoChannelLabel:"Kakao ธุรกิจ",emailMarketingLabel:"อีเมลมาร์เก็ตติ้ง",smsMarketingLabel:"SMS มาร์เก็ตติ้ง",influencerLabel:"อินฟลูเอนเซอร์",contentCalendarLabel:"ปฏิทินเนื้อหา",reviewsUgcLabel:"รีวิวและ UGC",webPopupLabel:"เว็บป๊อปอัป",commerceLabel:"อีคอมเมิร์ซและโลจิสติกส์",omniChannelLabel:"ออมนิแชนเนล",catalogLabel:"ซิงค์แคตตาล็อก",orderHubLabel:"ศูนย์คำสั่งซื้อ",wmsLabel:"WMS คลังสินค้า",priceOptLabel:"การเพิ่มประสิทธิภาพราคา",supplyChainLabel:"ซัพพลายเชน",returnsPortalLabel:"พอร์ทัลคืนสินค้า",performanceHubLabel:"ศูนย์ประสิทธิภาพ",pnlLabel:"กำไรขาดทุน",aiInsightsLabel:"AI Insights",reportBuilderLabel:"ตัวสร้างรายงาน",dataProductLabel:"ผลิตภัณฑ์ข้อมูล",aiRuleEngineLabel:"AI Rule Engine",approvalsLabel:"ศูนย์อนุมัติ",writebackLabel:"เขียนกลับ",dataSchemaLabel:"สคีมาข้อมูล",dataTrustLabel:"ความน่าเชื่อถือ",reconciliationLabel:"กระทบยอด",settlementsLabel:"การชำระเงิน",pricingLabel:"แผนและอัปเกรด",auditLogLabel:"บันทึกตรวจสอบ",workspaceLabel:"เวิร์กสเปซ",operationsLabel:"ดำเนินการ",caseStudyLabel:"กรณีศึกษา",helpLabel:"คู่มือ",feedbackLabel:"ข้อเสนอแนะ",developerHubLabel:"ศูนย์นักพัฒนา",adminSystem:"ระบบผู้ดูแล",platformEnvLabel:"การตั้งค่าผู้ดูแล",dbSchemaLabel:"DB Admin",paymentPgLabel:"เกตเวย์ชำระเงิน",integrationHubLabel:"ศูนย์เชื่อมต่อ",onboardingLabel:"ออนบอร์ดดิ้ง"},
vi:{dashboardLabel:"Bảng điều khiển",rollupLabel:"Tổng hợp",autoMarketingLabel:"Chiến lược tự động",campaignManagerLabel:"Quản lý chiến dịch",journeyBuilderLabel:"Xây dựng hành trình",adPerformanceLabel:"Hiệu suất quảng cáo",budgetTrackerLabel:"Theo dõi ngân sách",accountPerformanceLabel:"Hiệu suất tài khoản",attributionLabel:"Phân bổ",channelKpiLabel:"KPI kênh",graphScoreLabel:"Điểm đồ thị",crmLabel:"CRM",crmMainLabel:"Bảng điều khiển CRM",kakaoChannelLabel:"Kakao Business",emailMarketingLabel:"Email Marketing",smsMarketingLabel:"SMS Marketing",influencerLabel:"Influencer",contentCalendarLabel:"Lịch nội dung",reviewsUgcLabel:"Đánh giá & UGC",webPopupLabel:"Web Popup",commerceLabel:"Thương mại & Logistics",omniChannelLabel:"Đa kênh",catalogLabel:"Đồng bộ danh mục",orderHubLabel:"Trung tâm đơn hàng",wmsLabel:"WMS Kho",priceOptLabel:"Tối ưu giá",supplyChainLabel:"Chuỗi cung ứng",returnsPortalLabel:"Cổng hoàn trả",performanceHubLabel:"Trung tâm hiệu suất",pnlLabel:"Lãi lỗ",aiInsightsLabel:"AI Insights",reportBuilderLabel:"Tạo báo cáo",dataProductLabel:"Sản phẩm dữ liệu",aiRuleEngineLabel:"AI Rule Engine",approvalsLabel:"Phê duyệt",writebackLabel:"Ghi lại",dataSchemaLabel:"Lược đồ dữ liệu",dataTrustLabel:"Độ tin cậy",reconciliationLabel:"Đối soát",settlementsLabel:"Thanh toán",pricingLabel:"Gói & Nâng cấp",auditLogLabel:"Nhật ký kiểm toán",workspaceLabel:"Không gian làm việc",operationsLabel:"Vận hành",caseStudyLabel:"Nghiên cứu điển hình",helpLabel:"Hướng dẫn",feedbackLabel:"Phản hồi",developerHubLabel:"Cổng nhà phát triển",adminSystem:"Quản trị",platformEnvLabel:"Cài đặt quản trị",dbSchemaLabel:"DB Admin",paymentPgLabel:"Cổng thanh toán",integrationHubLabel:"Trung tâm tích hợp",onboardingLabel:"Hướng dẫn sử dụng"},
id:{dashboardLabel:"Dasbor",rollupLabel:"Ringkasan",autoMarketingLabel:"Strategi Otomatis",campaignManagerLabel:"Manajer Kampanye",journeyBuilderLabel:"Pembuat Perjalanan",adPerformanceLabel:"Performa Iklan",budgetTrackerLabel:"Pelacak Anggaran",accountPerformanceLabel:"Performa Akun",attributionLabel:"Atribusi",channelKpiLabel:"KPI Saluran",graphScoreLabel:"Skor Grafik",crmLabel:"CRM",crmMainLabel:"Dasbor CRM",kakaoChannelLabel:"Kakao Bisnis",emailMarketingLabel:"Email Marketing",smsMarketingLabel:"SMS Marketing",influencerLabel:"Influencer",contentCalendarLabel:"Kalender Konten",reviewsUgcLabel:"Ulasan & UGC",webPopupLabel:"Web Popup",commerceLabel:"Perdagangan & Logistik",omniChannelLabel:"Omni Channel",catalogLabel:"Sinkronisasi Katalog",orderHubLabel:"Pusat Pesanan",wmsLabel:"WMS Inventaris",priceOptLabel:"Optimasi Harga",supplyChainLabel:"Rantai Pasok",returnsPortalLabel:"Portal Pengembalian",performanceHubLabel:"Pusat Performa",pnlLabel:"Laba Rugi",aiInsightsLabel:"AI Insights",reportBuilderLabel:"Pembuat Laporan",dataProductLabel:"Produk Data",aiRuleEngineLabel:"AI Rule Engine",approvalsLabel:"Persetujuan",writebackLabel:"Tulis Balik",dataSchemaLabel:"Skema Data",dataTrustLabel:"Kepercayaan Data",reconciliationLabel:"Rekonsiliasi",settlementsLabel:"Penyelesaian",pricingLabel:"Paket & Upgrade",auditLogLabel:"Log Audit",workspaceLabel:"Ruang Kerja",operationsLabel:"Operasi",caseStudyLabel:"Studi Kasus",helpLabel:"Panduan",feedbackLabel:"Masukan",developerHubLabel:"Portal Pengembang",adminSystem:"Administrasi",platformEnvLabel:"Pengaturan Admin",dbSchemaLabel:"DB Admin",paymentPgLabel:"Gateway Pembayaran",integrationHubLabel:"Pusat Integrasi",onboardingLabel:"Onboarding"},
};
NAV["zh-TW"]={...NAV.zh,dashboardLabel:"綜合儀表板",rollupLabel:"匯總視圖",commerceLabel:"電商與物流",catalogLabel:"目錄同步",orderHubLabel:"訂單中心",supplyChainLabel:"供應鏈",returnsPortalLabel:"退貨門戶",pricingLabel:"方案升級",auditLogLabel:"稽核日誌"};
NAV.de={...NAV.en,dashboardLabel:"Dashboard",autoMarketingLabel:"Automatisierung",campaignManagerLabel:"Kampagnenmanager",crmLabel:"Kundenmanagement",commerceLabel:"Handel & Logistik",supplyChainLabel:"Lieferkette",adminSystem:"Verwaltung"};
NAV.fr={...NAV.en,dashboardLabel:"Tableau de bord",crmLabel:"Gestion clients",commerceLabel:"Commerce & Logistique",supplyChainLabel:"Chaîne d'approvisionnement",adminSystem:"Administration"};
NAV.es={...NAV.en,dashboardLabel:"Panel de control",crmLabel:"Gestión de clientes",commerceLabel:"Comercio y Logística",supplyChainLabel:"Cadena de Suministro",adminSystem:"Administración"};
NAV.pt={...NAV.en,commerceLabel:"Comércio e Logística",supplyChainLabel:"Cadeia de Suprimentos",adminSystem:"Administração"};
NAV.ru={...NAV.en,commerceLabel:"Торговля и логистика",supplyChainLabel:"Цепочка поставок",adminSystem:"Администрирование"};
NAV.ar={...NAV.en,commerceLabel:"التجارة والخدمات اللوجستية",supplyChainLabel:"سلسلة التوريد",adminSystem:"الإدارة"};
NAV.hi={...NAV.en,commerceLabel:"वाणिज्य और रसद",supplyChainLabel:"आपूर्ति श्रृंखला",adminSystem:"प्रशासन"};

const LANGS=['ko','en','ja','zh','zh-TW','de','th','vi','id','fr','es','pt','ru','ar','hi'];
LANGS.forEach(lang=>{
  const p=DIR+lang+'.js';
  let src=fs.readFileSync(p,'utf8');
  const nav=NAV[lang]||NAV.en;
  // Remove old Object.assign block
  src=src.replace(/\n\/\/ ── gNav sidebar labels[\s\S]*?\}\);\n/g,'');
  // Find the closing brace of gNav object and inject keys before it
  const varName=lang==='zh-TW'?'zhTW':lang;
  // Pattern: varName.gNav = { ... }  OR  gNav: { ... }
  // Find last key in gNav section - look for the gNav closing brace
  const gNavStart=src.indexOf(varName+'.gNav');
  if(gNavStart<0){
    // Try inline: gNav: {
    const inlineStart=src.indexOf('gNav:');
    if(inlineStart>=0){
      // Find the closing } of gNav
      let depth=0,i=src.indexOf('{',inlineStart);
      for(;i<src.length;i++){
        if(src[i]==='{')depth++;
        if(src[i]==='}')depth--;
        if(depth===0)break;
      }
      // Insert new keys before closing }
      const pairs=Object.entries(nav).map(([k,v])=>`        ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(',\n');
      src=src.substring(0,i)+',\n'+pairs+'\n    '+src.substring(i);
    }
  } else {
    // Object.assign pattern - find closing });
    let depth=0,i=src.indexOf('{',gNavStart);
    for(;i<src.length;i++){
      if(src[i]==='{')depth++;
      if(src[i]==='}')depth--;
      if(depth===0)break;
    }
    const pairs=Object.entries(nav).map(([k,v])=>`    ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(',\n');
    src=src.substring(0,i)+',\n'+pairs+'\n'+src.substring(i);
  }
  fs.writeFileSync(p,src);
  console.log(lang+': injected '+Object.keys(nav).length+' keys into gNav');
});
