// Generate full sidebarI18n.js with complete translations for all 15 languages
const fs=require('fs');
const K=['home','dashboardLabel','rollupLabel','aiMarketing','autoMarketingLabel','campaignManagerLabel','journeyBuilderLabel','adAnalytics','adPerformanceLabel','budgetTrackerLabel','accountPerformanceLabel','attributionLabel','channelKpiLabel','graphScoreLabel','crmLabel','crmMainLabel','kakaoChannelLabel','emailMarketingLabel','smsMarketingLabel','influencerLabel','contentCalendarLabel','reviewsUgcLabel','webPopupLabel','commerceLabel','omniChannelLabel','catalogLabel','orderHubLabel','wmsLabel','priceOptLabel','supplyChainLabel','returnsPortalLabel','analytics','performanceHubLabel','pnlLabel','aiInsightsLabel','reportBuilderLabel','dataProductLabel','automation','aiRuleEngineLabel','approvalsLabel','writebackLabel','onboardingLabel','data','integrationHubLabel','dataSchemaLabel','dataTrustLabel','finance','settlementsLabel','reconciliationLabel','pricingLabel','auditLogLabel','memberTools','workspaceLabel','operationsLabel','caseStudyLabel','helpLabel','feedbackLabel','developerHubLabel','adminSystem','platformEnvLabel','dbSchemaLabel','paymentPgLabel'];
const T={
ko:["홈 대시보드","종합 대시보드","롤업 뷰","AI 마케팅","자동화 전략","캠페인 관리","여정 빌더","광고 및 채널 분석","광고성과","예산 관리","어카운트 성과","어트리뷰션","채널 KPI","그래프 스코어","고객/CRM","CRM 대시보드","카카오 비즈니스","이메일 마케팅","SMS 마케팅","인플루언서","콘텐츠 캘린더","리뷰 및 UGC","웹 팝업","커머스 및 물류","옴니 채널","카탈로그 동기화","주문 허브","WMS 재고관리","최적 가격 설정","공급망 관리","반품 포털","성과 및 리포팅","퍼포먼스 인사이트","P&L 손익","AI 인사이트","리포트 빌더","데이터 프로덕트","자동화 및 AI 규칙","AI 룰 엔진","결재 센터","데이터 라이트백","온보딩 맵","데이터 및 수집","연동 허브","데이터 스키마","데이터 신뢰성","재무 및 정산","결제 내역","정산 대조","플랜 및 업그레이드","보안 감사 로그","멤버 구성원 도구","워크스페이스 설정","운영 실행 목록","성공 사례","플랫폼 가이드","의견/피드백","개발자 포털","관리자 시스템","관리자 환경","DB 어드민","게이트웨이 관리"],
en:["Home","Dashboard","Rollup View","AI Marketing","Auto Strategy","Campaign Manager","Journey Builder","Ad & Channel Analytics","Ad Performance","Budget Tracker","Account Performance","Attribution","Channel KPI","Graph Score","CRM","CRM Dashboard","Kakao Business","Email Marketing","SMS Marketing","Influencer","Content Calendar","Reviews & UGC","Web Popup","Commerce & Logistics","Omni Channel","Catalog Sync","Order Hub","WMS Inventory","Price Optimization","Supply Chain","Returns Portal","Analytics & Reporting","Performance Hub","P&L","AI Insights","Report Builder","Data Product","Automation & AI Rules","AI Rule Engine","Approvals","Writeback","Onboarding","Data & Collection","Integration Hub","Data Schema","Data Trust","Finance & Settlement","Settlements","Reconciliation","Plans & Upgrade","Audit Log","Team Tools","Workspace","Operations","Case Studies","Platform Guide","Feedback","Developer Hub","Admin System","Admin Settings","DB Admin","Payment Gateway"],
ja:["ホーム","ダッシュボード","ロールアップ","AIマーケティング","自動化戦略","キャンペーン管理","ジャーニービルダー","広告・チャネル分析","広告成果","予算管理","アカウント成果","アトリビューション","チャネルKPI","グラフスコア","CRM","CRMダッシュボード","カカオビジネス","メールマーケティング","SMSマーケティング","インフルエンサー","コンテンツカレンダー","レビュー＆UGC","Webポップアップ","コマース・物流","オムニチャネル","カタログ同期","注文ハブ","WMS在庫管理","価格最適化","サプライチェーン","返品ポータル","分析・レポート","パフォーマンス","P&L損益","AIインサイト","レポートビルダー","データプロダクト","自動化・AIルール","AIルールエンジン","承認センター","ライトバック","オンボーディング","データ・収集","連携ハブ","データスキーマ","データ信頼性","財務・精算","決済履歴","精算照合","プラン","監査ログ","メンバーツール","ワークスペース","運営実行","成功事例","ガイド","フィードバック","開発者ポータル","管理者システム","管理者設定","DB管理","PG管理"],
zh:["首页","综合仪表盘","汇总视图","AI营销","自动化策略","活动管理","旅程构建","广告与渠道分析","广告效果","预算管理","账户绩效","归因分析","渠道KPI","图谱评分","CRM客户管理","CRM仪表盘","Kakao商务","邮件营销","短信营销","达人管理","内容日历","评论与UGC","网页弹窗","电商与物流","全渠道","目录同步","订单中心","WMS库存","价格优化","供应链","退货门户","分析与报表","绩效中心","损益表","AI洞察","报表构建","数据产品","自动化与AI规则","AI规则引擎","审批中心","数据回写","引导","数据与采集","集成中心","数据模式","数据可信度","财务与结算","结算记录","对账","套餐升级","审计日志","团队工具","工作区","运营执行","成功案例","平台指南","反馈","开发者门户","管理系统","管理设置","DB管理","支付网关"],
"zh-TW":["首頁","綜合儀表板","匯總視圖","AI行銷","自動化策略","活動管理","旅程建構","廣告與頻道分析","廣告效果","預算管理","帳戶績效","歸因分析","頻道KPI","圖譜評分","CRM客戶管理","CRM儀表板","Kakao商務","電郵行銷","簡訊行銷","網紅管理","內容日曆","評論與UGC","網頁彈窗","電商與物流","全通路","目錄同步","訂單中心","WMS庫存","價格優化","供應鏈","退貨入口","分析與報表","績效中心","損益表","AI洞察","報表建構","資料產品","自動化與AI規則","AI規則引擎","審批中心","資料回寫","引導","資料與採集","整合中心","資料模式","資料可信度","財務與結算","結算紀錄","對帳","方案升級","稽核日誌","團隊工具","工作區","營運執行","成功案例","平台指南","回饋","開發者入口","管理系統","管理設定","DB管理","支付閘道"],
de:["Startseite","Dashboard","Rollup-Ansicht","KI-Marketing","Auto-Strategie","Kampagnenmanager","Journey Builder","Anzeigen & Kanal-Analyse","Anzeigenleistung","Budgettracker","Kontoleistung","Attribution","Kanal-KPI","Graphscore","Kundenmanagement","CRM-Dashboard","Kakao Business","E-Mail-Marketing","SMS-Marketing","Influencer","Inhaltskalender","Bewertungen & UGC","Web-Popup","Handel & Logistik","Omni-Kanal","Katalogsync","Bestellzentrale","WMS-Bestand","Preisoptimierung","Lieferkette","Retouren-Portal","Analyse & Berichte","Performance-Hub","GuV","KI-Einblicke","Berichtersteller","Datenprodukt","Automatisierung & KI","KI-Regelwerk","Genehmigungen","Rückschreibung","Onboarding","Daten & Erfassung","Integrations-Hub","Datenschema","Datenvertrauen","Finanzen & Abrechnung","Zahlungen","Abstimmung","Pläne & Upgrade","Prüfprotokoll","Team-Tools","Arbeitsbereich","Betrieb","Fallstudien","Plattform-Guide","Feedback","Entwickler-Hub","Verwaltung","Admin-Einstellungen","DB-Admin","Zahlungs-Gateway"],
fr:["Accueil","Tableau de bord","Vue consolidée","Marketing IA","Stratégie auto","Gestion campagnes","Parcours client","Analyse pub & canaux","Performance pub","Suivi budget","Performance compte","Attribution","KPI canal","Score graphe","Gestion clients","Tableau CRM","Kakao Business","Email marketing","SMS marketing","Influenceur","Calendrier contenu","Avis & UGC","Popup web","Commerce & Logistique","Omnicanal","Sync catalogue","Centre commandes","WMS stocks","Optimisation prix","Chaîne d'approv.","Portail retours","Analyses & Rapports","Hub performance","P&L","Insights IA","Créateur rapports","Produit données","Automatisation & IA","Moteur règles IA","Approbations","Réécriture","Intégration","Données & Collecte","Hub intégration","Schéma données","Confiance données","Finances & Règlement","Règlements","Rapprochement","Plans & Upgrade","Journal audit","Outils équipe","Espace travail","Opérations","Études de cas","Guide plateforme","Commentaires","Hub développeur","Administration","Paramètres admin","Admin BD","Passerelle paiement"],
es:["Inicio","Panel de control","Vista resumen","Marketing IA","Estrategia auto","Gestor campañas","Constructor viajes","Análisis anuncios","Rendimiento ads","Rastreador presup.","Rendimiento cuenta","Atribución","KPI canal","Puntuación grafo","Gestión clientes","Panel CRM","Kakao Business","Email marketing","SMS marketing","Influencer","Calendario contenido","Reseñas & UGC","Popup web","Comercio & Logística","Omnicanal","Sync catálogo","Centro pedidos","WMS inventario","Optimización precios","Cadena de Suministro","Portal devoluciones","Análisis e Informes","Hub rendimiento","P&L","Insights IA","Creador informes","Producto datos","Automatización & IA","Motor reglas IA","Aprobaciones","Reescritura","Incorporación","Datos & Recolección","Hub integración","Esquema datos","Confianza datos","Finanzas & Liquidación","Liquidaciones","Conciliación","Planes & Upgrade","Registro auditoría","Herramientas equipo","Espacio trabajo","Operaciones","Casos de éxito","Guía plataforma","Comentarios","Hub desarrollador","Administración","Config. admin","Admin BD","Pasarela de pago"],
pt:["Início","Painel","Visão consolidada","Marketing IA","Estratégia auto","Gestor campanhas","Construtor jornadas","Análise anúncios","Desempenho ads","Rastreador orçamento","Desempenho conta","Atribuição","KPI canal","Pontuação grafo","Gestão clientes","Painel CRM","Kakao Business","Email marketing","SMS marketing","Influenciador","Calendário conteúdo","Avaliações & UGC","Popup web","Comércio & Logística","Omnicanal","Sync catálogo","Central pedidos","WMS estoque","Otimização preços","Cadeia de Suprimentos","Portal devoluções","Análise & Relatórios","Hub desempenho","P&L","Insights IA","Criador relatórios","Produto dados","Automação & IA","Motor regras IA","Aprovações","Reescrita","Integração","Dados & Coleta","Hub integração","Esquema dados","Confiança dados","Finanças & Liquidação","Liquidações","Conciliação","Planos & Upgrade","Log auditoria","Ferramentas equipe","Espaço trabalho","Operações","Casos de sucesso","Guia plataforma","Feedback","Hub desenvolvedor","Administração","Config. admin","Admin BD","Gateway pagamento"],
ru:["Главная","Дашборд","Сводный вид","ИИ-маркетинг","Авто-стратегия","Менеджер кампаний","Построитель путей","Анализ рекламы","Эффективность рекл.","Бюджет-трекер","Эффект. аккаунта","Атрибуция","KPI каналов","Граф-оценка","CRM","Дашборд CRM","Kakao Business","Email-маркетинг","SMS-маркетинг","Инфлюенсеры","Календарь контента","Отзывы и UGC","Веб-попап","Торговля и логистика","Омниканал","Синхр. каталога","Центр заказов","WMS-склад","Оптимизация цен","Цепочка поставок","Портал возвратов","Аналитика и отчёты","Хаб показателей","P&L","ИИ-аналитика","Конструктор отчётов","Продукт данных","Автоматизация и ИИ","Движок правил ИИ","Согласования","Обратная запись","Онбординг","Данные и сбор","Хаб интеграции","Схема данных","Доверие данных","Финансы и расчёты","Расчёты","Сверка","Планы и апгрейд","Журнал аудита","Инструменты команды","Рабочее простр.","Операции","Кейсы","Руководство","Обратная связь","Хаб разработчика","Администрирование","Настройки админа","Админ БД","Платёжный шлюз"],
ar:["الرئيسية","لوحة المعلومات","العرض الموحد","تسويق ذكي","استراتيجية تلقائية","مدير الحملات","منشئ الرحلات","تحليل الإعلانات","أداء الإعلانات","تتبع الميزانية","أداء الحساب","الإسناد","مؤشرات القناة","تقييم الرسم","إدارة العملاء","لوحة CRM","Kakao أعمال","تسويق بريدي","تسويق SMS","المؤثرون","تقويم المحتوى","المراجعات و UGC","نافذة منبثقة","التجارة والخدمات","قناة شاملة","مزامنة الكتالوج","مركز الطلبات","مستودعات WMS","تحسين الأسعار","سلسلة التوريد","بوابة المرتجعات","التحليلات والتقارير","مركز الأداء","الأرباح والخسائر","تحليلات ذكية","منشئ التقارير","منتج البيانات","الأتمتة والذكاء","محرك القواعد","الموافقات","إعادة الكتابة","التهيئة","البيانات والجمع","مركز التكامل","مخطط البيانات","ثقة البيانات","المالية والتسوية","التسويات","المطابقة","الخطط والترقية","سجل المراجعة","أدوات الفريق","مساحة العمل","العمليات","دراسات حالة","دليل المنصة","التعليقات","مركز المطورين","الإدارة","إعدادات المسؤول","إدارة قاعدة البيانات","بوابة الدفع"],
hi:["होम","डैशबोर्ड","रोलअप व्यू","AI मार्केटिंग","ऑटो रणनीति","अभियान प्रबंधक","जर्नी बिल्डर","विज्ञापन विश्लेषण","विज्ञापन प्रदर्शन","बजट ट्रैकर","खाता प्रदर्शन","एट्रिब्यूशन","चैनल KPI","ग्राफ स्कोर","CRM","CRM डैशबोर्ड","Kakao बिज़नेस","ईमेल मार्केटिंग","SMS मार्केटिंग","इन्फ्लुएंसर","सामग्री कैलेंडर","समीक्षा और UGC","वेब पॉपअप","वाणिज्य और रसद","ऑम्नी चैनल","कैटलॉग सिंक","ऑर्डर हब","WMS इन्वेंटरी","मूल्य अनुकूलन","आपूर्ति श्रृंखला","रिटर्न पोर्टल","विश्लेषण और रिपोर्ट","प्रदर्शन हब","लाभ-हानि","AI अंतर्दृष्टि","रिपोर्ट बिल्डर","डेटा प्रोडक्ट","स्वचालन और AI","AI नियम इंजन","अनुमोदन","राइटबैक","ऑनबोर्डिंग","डेटा और संग्रह","एकीकरण हब","डेटा स्कीमा","डेटा विश्वसनीयता","वित्त और निपटान","भुगतान","समाधान","योजनाएँ और अपग्रेड","ऑडिट लॉग","टीम टूल्स","कार्यक्षेत्र","संचालन","केस स्टडीज़","प्लेटफ़ॉर्म गाइड","प्रतिक्रिया","डेवलपर हब","प्रशासन","व्यवस्थापक सेटिंग","DB एडमिन","भुगतान गेटवे"],
th:["หน้าแรก","แดชบอร์ด","สรุปภาพรวม","การตลาด AI","กลยุทธ์อัตโนมัติ","จัดการแคมเปญ","ตัวสร้างเส้นทาง","วิเคราะห์โฆษณา","ผลลัพธ์โฆษณา","ติดตามงบ","ผลลัพธ์บัญชี","การระบุแหล่งที่มา","KPI ช่องทาง","คะแนนกราฟ","CRM","แดชบอร์ด CRM","Kakao ธุรกิจ","อีเมลมาร์เก็ตติ้ง","SMS มาร์เก็ตติ้ง","อินฟลูเอนเซอร์","ปฏิทินเนื้อหา","รีวิวและ UGC","เว็บป๊อปอัป","อีคอมเมิร์ซและโลจิสติกส์","ออมนิแชนเนล","ซิงค์แคตตาล็อก","ศูนย์คำสั่งซื้อ","WMS คลังสินค้า","เพิ่มประสิทธิภาพราคา","ซัพพลายเชน","พอร์ทัลคืนสินค้า","การวิเคราะห์และรายงาน","ศูนย์ประสิทธิภาพ","กำไรขาดทุน","AI Insights","ตัวสร้างรายงาน","ผลิตภัณฑ์ข้อมูล","ระบบอัตโนมัติและ AI","เครื่องมือกฎ AI","การอนุมัติ","เขียนกลับ","ออนบอร์ดดิ้ง","ข้อมูลและการรวบรวม","ศูนย์เชื่อมต่อ","สคีมาข้อมูล","ความน่าเชื่อถือข้อมูล","การเงินและการชำระ","การชำระเงิน","กระทบยอด","แผนและอัปเกรด","บันทึกตรวจสอบ","เครื่องมือทีม","พื้นที่ทำงาน","การดำเนินงาน","กรณีศึกษา","คู่มือแพลตฟอร์ม","ข้อเสนอแนะ","ศูนย์นักพัฒนา","ระบบผู้ดูแล","การตั้งค่าผู้ดูแล","DB Admin","เกตเวย์ชำระเงิน"],
vi:["Trang chủ","Bảng điều khiển","Tổng hợp","Marketing AI","Chiến lược tự động","Quản lý chiến dịch","Xây dựng hành trình","Phân tích quảng cáo","Hiệu suất QC","Theo dõi ngân sách","Hiệu suất tài khoản","Phân bổ","KPI kênh","Điểm đồ thị","CRM","Bảng điều khiển CRM","Kakao Business","Email Marketing","SMS Marketing","Influencer","Lịch nội dung","Đánh giá & UGC","Web Popup","Thương mại & Logistics","Đa kênh","Đồng bộ danh mục","Trung tâm đơn hàng","WMS Kho","Tối ưu giá","Chuỗi cung ứng","Cổng hoàn trả","Phân tích & Báo cáo","Trung tâm hiệu suất","Lãi lỗ","AI Insights","Tạo báo cáo","Sản phẩm dữ liệu","Tự động hoá & AI","Công cụ quy tắc AI","Phê duyệt","Ghi lại","Hướng dẫn","Dữ liệu & Thu thập","Trung tâm tích hợp","Lược đồ dữ liệu","Độ tin cậy dữ liệu","Tài chính & Thanh toán","Thanh toán","Đối soát","Gói & Nâng cấp","Nhật ký kiểm toán","Công cụ nhóm","Không gian làm việc","Vận hành","Nghiên cứu điển hình","Hướng dẫn nền tảng","Phản hồi","Cổng nhà phát triển","Quản trị","Cài đặt quản trị","DB Admin","Cổng thanh toán"],
id:["Beranda","Dasbor","Ringkasan","Pemasaran AI","Strategi Otomatis","Manajer Kampanye","Pembuat Perjalanan","Analisis Iklan","Performa Iklan","Pelacak Anggaran","Performa Akun","Atribusi","KPI Saluran","Skor Grafik","CRM","Dasbor CRM","Kakao Bisnis","Email Marketing","SMS Marketing","Influencer","Kalender Konten","Ulasan & UGC","Web Popup","Perdagangan & Logistik","Omni Channel","Sinkronisasi Katalog","Pusat Pesanan","WMS Inventaris","Optimasi Harga","Rantai Pasok","Portal Pengembalian","Analitik & Laporan","Pusat Performa","Laba Rugi","AI Insights","Pembuat Laporan","Produk Data","Otomatisasi & AI","Mesin Aturan AI","Persetujuan","Tulis Balik","Onboarding","Data & Koleksi","Pusat Integrasi","Skema Data","Kepercayaan Data","Keuangan & Penyelesaian","Penyelesaian","Rekonsiliasi","Paket & Upgrade","Log Audit","Alat Tim","Ruang Kerja","Operasi","Studi Kasus","Panduan Platform","Masukan","Portal Pengembang","Administrasi","Pengaturan Admin","DB Admin","Gateway Pembayaran"],
};
let out='const D={\n';
Object.entries(T).forEach(([lang,vals])=>{
  out+=JSON.stringify(lang)+':{';
  vals.forEach((v,i)=>{out+=JSON.stringify(K[i])+':'+JSON.stringify(v);if(i<vals.length-1)out+=',';});
  out+='},\n';
});
out+='};\nexport default D;\n';
fs.writeFileSync('src/layout/sidebarI18n.js',out);
console.log('sidebarI18n.js written');
