const fs=require('fs');
// All priceOpt keys used in PriceOpt.jsx with translations for 4 core + 11 secondary languages
const K=["loading","regProduct","elasticityData","items","optAdoption","avgMargin","avgRecPrice","channelResult","recentHistory","currentPrice","optimalPrice","expectedMargin","noAnalysis","refresh","excelUploadSuccess","imgMaxSize","productName","category","spec","unit","purchaseCost","ioFee","storageFee","workFee","shippingFee","productCostAuto","targetMarginRate","baseSalePrice","qtyPerBox","boxesPerPallet","initialStockUnits","excelEmptyFile","excelUploadResult","excelSuccess","excelFail","excelUploadError","excelUploading","excelBulkUpload","excelDownload","excelTemplate","tabProducts","productImageTitle","imgDragDrop","imgMaxLabel","categorySelect","boxPalletTitle","unitBox","unitEach","unitPallet","stockInputTitle","stockInputType","inputByEach","inputByBox","inputByPallet","stockQtyInput","totalUnits","totalBoxes","totalPallets","costBreakdown","saveProduct","regProducts","specLabel","costLabel","marginLabel","basePriceLabel","noProducts","calcParams","labelSku","labelChannel","allUnified","currentSalePrice","stockQty","calculating","calcOptimal","costPrice","minApplyPrice","expectedQty","unitPcs","stockLow","premiumSuggest","stockHigh","clearanceSuggest","invalidPriceList","simFailed","scenarioSim","testPriceList","runSim","totalProfit","totalBudget","runChannelMix","unifiedROI","allocPct","execBudget","expectedReturn","expectedProfit","pastSimulations","minPriceAlert","minPriceAlertSuffix","promoEventReg","tabCalendar","tabScenario","statusScheduled","statusDraft","promoSaved","register","dsIntegration","activeRules","todayChanges","avgMarginImprove","autoRules","ruleActive","ruleInactive","ruleStop","ruleActivate","changeHistory","labelTime","feeChName","feeCommission","feeTax","feeTotal","feeRegion","channelFeeTitle","channelFeeSub","feeReadOnlyNote","feeDomestic","feeGlobal","feeTipTitle","feeTipDesc","guideTabSummaryDesc","guideTabProductsDesc","guideTabOptimizeDesc","guideTabScenarioDesc","guideTabMixDesc","guideTabRepricerDesc","guideTabCompetitorDesc","guideTabCalendarDesc","guideTabFeeDesc","guideTabGuideDesc","guideTitle","guideSub","guideStepsTitle","guideTabsTitle","guideTipsTitle","tabSummary","tabOptimize","tabMix","tabRepricer","tabCompetitor","tabChannelFee","tabGuide","pageTitle","pageSub","badgeChannelUnit","badgeRealtimeSync","badgeSecurityActive","secBannerBlocked","secBannerDismiss","catElecAudio","catElecInput","catElecAccessory","catElecCamera","catElecCharging","catFashionClothing","catFashionShoes","catBeautySkin","catBeautyMakeup","catFoodHealth","catHomeKitchen","catSportsGear","catBooksStationery","catToysHobbies","unitDevice","unitBottle","unitSet"];
const T={
ko:["로딩 중...","등록 제품","탄력성 데이터","건","최적화 적용","평균 마진","평균 권장가","채널별 결과","최근 내역","현재가","최적가","기대 마진","분석 없음","새로고침","등록 완료","이미지 최대 5MB","제품명","카테고리","규격","단위","매입가","입출고비","보관비","작업비","배송비","제품 원가(자동)","목표 마진율","기준 판매가","박스당 수량","팔렛당 박스","초기 재고","빈 파일","업로드 결과","성공","실패","업로드 오류","업로드 중...","엑셀 일괄 등록","엑셀 다운로드","엑셀 템플릿","제품 등록","제품 이미지","드래그 앤 드롭","최대","카테고리 선택","박스/팔렛","박스","개","팔렛","재고 입력","입력 방식","개수 입력","박스 입력","팔렛 입력","수량 입력","총 개수","총 박스","총 팔렛","원가 항목","제품 저장","등록 제품","규격","원가","마진","기준가","등록된 제품 없음","계산 조건","SKU","채널","전체 통합","현재 판매가","재고수량","계산 중...","최적가 계산","매입원가","최저 적용가","예상 판매량","개","재고 부족","프리미엄 제안","재고 과다","재고 정리 제안","가격 목록 오류","시뮬레이션 실패","시나리오 시뮬레이션","테스트 가격","시뮬레이션 실행","총 이익","총 예산","채널 믹스 실행","통합 ROI","비율","집행 예산","기대 수익","기대 이익","과거 시뮬레이션","최저가 알림","이하입니다","프로모션 등록","프로모션 캘린더","시나리오","예정","임시","저장됨","등록","DS 연동","활성 규칙","오늘 변동","평균 마진 개선","자동 규칙","활성","비활성","중지","활성화","변경 이력","시간","채널","수수료","세금","합계","지역","채널 수수료","채널별 수수료율 상세","읽기 전용","국내","글로벌","수수료 팁","수수료는 채널별로 다릅니다","요약 대시보드","제품 등록 관리","AI 최적가 계산","시나리오 시뮬레이션","채널 믹스 최적화","자동 가격 규칙","경쟁사 모니터링","프로모션 캘린더","채널별 수수료","이용 가이드","최적 가격 설정 가이드","가격 최적화 시스템 완벽 가이드","단계별 가이드","탭 가이드","전문가 팁","요약","최적화","채널 믹스","자동 가격","경쟁사 분석","채널 수수료","이용 가이드","최적 가격 설정","실시간 가격 최적화 및 채널별 마진 분석","채널 통합","실시간 동기화","보안 활성","보안 위반 차단","닫기","오디오/스피커","키보드/마우스","케이스/보호필름","카메라/액션캠","충전기/케이블","의류/패션잡화","신발/스니커즈","스킨케어","메이크업","건강식품","주방용품","스포츠용품","문구/도서","장난감/취미","기기","병/개","세트"],
en:["Loading...","Products","Elasticity Data","items","Opt Adoption","Avg Margin","Avg Rec Price","Channel Results","Recent History","Current Price","Optimal Price","Expected Margin","No analysis","Refresh","Registered","Image max 5MB","Product Name","Category","Spec","Unit","Purchase Cost","IO Fee","Storage Fee","Work Fee","Shipping Fee","Product Cost(auto)","Target Margin","Base Sale Price","Qty/Box","Boxes/Pallet","Initial Stock","Empty file","Upload result","Success","Fail","Upload error","Uploading...","Excel Bulk Upload","Excel Download","Excel Template","Product Reg","Product Image","Drag & Drop","Max","Select category","Box/Pallet","Box","EA","Pallet","Stock Input","Input Type","By Each","By Box","By Pallet","Qty Input","Total Units","Total Boxes","Total Pallets","Cost Breakdown","Save Product","Registered Products","Spec","Cost","Margin","Base Price","No products","Calc Params","SKU","Channel","All Unified","Current Sale Price","Stock Qty","Calculating...","Calc Optimal","Cost Price","Min Apply Price","Expected Qty","pcs","Low Stock","Premium Suggest","High Stock","Clearance Suggest","Invalid price list","Sim failed","Scenario Sim","Test Prices","Run Sim","Total Profit","Total Budget","Run Channel Mix","Unified ROI","Alloc %","Exec Budget","Expected Return","Expected Profit","Past Simulations","Min price alert","or below","Promo Registration","Promo Calendar","Scenario","Scheduled","Draft","Saved","Register","DS Integration","Active Rules","Today Changes","Avg Margin Improve","Auto Rules","Active","Inactive","Stop","Activate","Change History","Time","Channel","Commission","Tax","Total","Region","Channel Fees","Channel fee rates detail","Read only","Domestic","Global","Fee Tips","Fees vary by channel","Summary dashboard","Product registration","AI optimal price calc","Scenario simulation","Channel mix optimization","Auto pricing rules","Competitor monitoring","Promo calendar","Channel fees","User guide","Price Optimization Guide","Complete pricing guide","Step-by-Step","Tab Guide","Expert Tips","Summary","Optimize","Channel Mix","Auto Price","Competitor","Channel Fees","Guide","Price Optimization","Real-time price optimization & margin analysis","Channel Unit","Realtime Sync","Security Active","Security violation blocked","Dismiss","Audio/Speakers","Keyboard/Mouse","Cases/Films","Camera/Action Cam","Chargers/Cables","Clothing/Fashion","Shoes/Sneakers","Skincare","Makeup","Health Foods","Kitchen","Sports Gear","Stationery/Books","Toys/Hobbies","Device","Bottle","Set"],
ja:["読み込み中...","登録製品","弾力性データ","件","最適化適用","平均マージン","平均推奨価格","チャネル別結果","最近の履歴","現在価格","最適価格","期待マージン","分析なし","更新","登録完了","画像最大5MB","製品名","カテゴリ","規格","単位","仕入価格","入出庫費","保管費","作業費","送料","製品原価(自動)","目標マージン率","基準販売価格","箱あたり数量","パレットあたり箱数","初期在庫","空ファイル","アップロード結果","成功","失敗","アップロードエラー","アップロード中...","Excel一括登録","Excelダウンロード","Excelテンプレート","製品登録","製品画像","ドラッグ＆ドロップ","最大","カテゴリ選択","箱/パレット","箱","個","パレット","在庫入力","入力方法","個数入力","箱入力","パレット入力","数量入力","総個数","総箱数","総パレット","原価内訳","製品保存","登録製品","規格","原価","マージン","基準価格","製品なし","計算条件","SKU","チャネル","全統合","現在販売価格","在庫数量","計算中...","最適価格計算","仕入原価","最低適用価格","予想販売量","個","在庫不足","プレミアム提案","在庫過多","在庫整理提案","価格リストエラー","シミュレーション失敗","シナリオシミュレーション","テスト価格","シミュレーション実行","総利益","総予算","チャネルミックス実行","統合ROI","配分率","執行予算","期待リターン","期待利益","過去のシミュレーション","最低価格アラート","以下です","プロモ登録","プロモカレンダー","シナリオ","予定","下書き","保存済","登録","DS連携","有効ルール","本日変動","平均マージン改善","自動ルール","有効","無効","停止","有効化","変更履歴","時間","チャネル","手数料","税金","合計","地域","チャネル手数料","チャネル別手数料率の詳細","読み取り専用","国内","グローバル","手数料のヒント","手数料はチャネルによって異なります","要約ダッシュボード","製品登録管理","AI最適価格計算","シナリオシミュレーション","チャネルミックス最適化","自動価格ルール","競合モニタリング","プロモカレンダー","チャネル手数料","ご利用ガイド","価格最適化ガイド","価格最適化システム完全ガイド","ステップガイド","タブガイド","専門家のヒント","要約","最適化","チャネルミックス","自動価格","競合分析","チャネル手数料","ガイド","価格最適化","リアルタイム価格最適化とマージン分析","チャネル統合","リアルタイム同期","セキュリティ有効","セキュリティ違反ブロック","閉じる","オーディオ/スピーカー","キーボード/マウス","ケース/フィルム","カメラ/アクションカム","充電器/ケーブル","衣類/ファッション","靴/スニーカー","スキンケア","メイクアップ","健康食品","キッチン用品","スポーツ用品","文具/書籍","玩具/ホビー","デバイス","ボトル","セット"],
zh:["加载中...","注册产品","弹性数据","条","优化应用","平均利润","平均建议价","渠道结果","最近记录","当前价格","最优价格","预期利润","无分析","刷新","注册完成","图片最大5MB","产品名称","类别","规格","单位","采购价","出入库费","仓储费","工时费","运费","产品成本(自动)","目标利润率","基准售价","每箱数量","每托箱数","初始库存","空文件","上传结果","成功","失败","上传错误","上传中...","Excel批量上传","Excel下载","Excel模板","产品注册","产品图片","拖放上传","最大","选择类别","箱/托","箱","个","托","库存输入","输入方式","按个数","按箱","按托","数量输入","总数量","总箱数","总托数","成本明细","保存产品","注册产品","规格","成本","利润","基准价","无产品","计算参数","SKU","渠道","全部统一","当前售价","库存数量","计算中...","计算最优价","采购成本","最低适用价","预期销量","个","库存不足","溢价建议","库存过多","清仓建议","价格列表错误","模拟失败","场景模拟","测试价格","运行模拟","总利润","总预算","运行渠道组合","统一ROI","比例","执行预算","预期回报","预期利润","历史模拟","最低价提醒","以下","促销注册","促销日历","场景","已计划","草稿","已保存","注册","DS集成","活跃规则","今日变动","平均利润改善","自动规则","活跃","非活跃","停止","激活","变更历史","时间","渠道","佣金","税费","合计","地区","渠道费用","渠道费率详情","只读","国内","全球","费用提示","费率因渠道而异","概览仪表盘","产品注册管理","AI最优价计算","场景模拟","渠道组合优化","自动定价规则","竞品监控","促销日历","渠道费用","使用指南","价格优化指南","价格优化系统完整指南","分步指南","标签指南","专家提示","概览","优化","渠道组合","自动定价","竞品分析","渠道费用","指南","价格优化","实时价格优化与渠道利润分析","渠道统一","实时同步","安全激活","安全违规已阻止","关闭","音频/音箱","键盘/鼠标","壳/膜","相机/运动相机","充电器/线缆","服装/时尚","鞋/运动鞋","护肤","彩妆","健康食品","厨房用品","运动器材","文具/图书","玩具/爱好","设备","瓶","套"],
de:["Laden...","Produkte","Elastizitätsdaten","Stk","Opt. Anwendung","Ø Marge","Ø Empf. Preis","Kanalergebnisse","Letzte Einträge","Aktueller Preis","Optimaler Preis","Erwart. Marge","Keine Analyse","Aktualisieren","Registriert","Bild max 5MB","Produktname","Kategorie","Spezifikation","Einheit","Einkaufspreis","Ein-/Auslagerung","Lagergebühr","Arbeitsgebühr","Versandkosten","Produktkosten(auto)","Zielmarge","Basisverkaufspreis","Stk/Karton","Kartons/Palette","Anfangsbestand","Leere Datei","Upload-Ergebnis","Erfolg","Fehler","Upload-Fehler","Hochladen...","Excel Massenupload","Excel Download","Excel Vorlage","Produktreg.","Produktbild","Drag & Drop","Max","Kategorie wählen","Karton/Palette","Karton","Stk","Palette","Bestandseingabe","Eingabeart","Nach Stück","Nach Karton","Nach Palette","Menge eingeben","Gesamt Stk","Gesamt Kartons","Gesamt Paletten","Kostenaufschlüsselung","Produkt speichern","Registrierte Produkte","Spez.","Kosten","Marge","Basispreis","Keine Produkte","Berechnungsparameter","SKU","Kanal","Alle vereint","Aktueller VP","Bestandsmenge","Berechne...","Optimal berechnen","Einkaufspreis","Min. Anwendungspreis","Erwart. Menge","Stk","Geringer Bestand","Premium-Vorschlag","Hoher Bestand","Räumungsvorschlag","Ungültige Preisliste","Simulation fehlg.","Szenario-Simulation","Testpreise","Simulation starten","Gesamtgewinn","Gesamtbudget","Kanalmix starten","Gesamt-ROI","Anteil %","Exec Budget","Erwart. Rendite","Erwart. Gewinn","Vergangene Sim.","Mindestpreis-Alarm","oder darunter","Promo-Registrierung","Promo-Kalender","Szenario","Geplant","Entwurf","Gespeichert","Registrieren","DS-Integration","Aktive Regeln","Änderungen heute","Ø Margenverbesserung","Auto-Regeln","Aktiv","Inaktiv","Stopp","Aktivieren","Änderungsverlauf","Zeit","Kanal","Provision","Steuer","Gesamt","Region","Kanalgebühren","Kanalgebühren Details","Nur lesen","Inland","Global","Gebühren-Tipps","Gebühren variieren je Kanal","Übersicht-Dashboard","Produktregistrierung","KI-Optimalpreis","Szenario-Simulation","Kanalmix-Optimierung","Auto-Preisregeln","Wettbewerberüberwachung","Promo-Kalender","Kanalgebühren","Benutzerhandbuch","Preisoptimierungs-Guide","Vollständiger Preisoptimierungs-Guide","Schritt für Schritt","Tab-Guide","Expertentipps","Übersicht","Optimierung","Kanalmix","Auto-Preis","Wettbewerber","Kanalgebühren","Guide","Preisoptimierung","Echtzeit-Preisoptimierung & Margenanalyse","Kanaleinheit","Echtzeit-Sync","Sicherheit aktiv","Sicherheitsverstoß blockiert","Schließen","Audio/Lautsprecher","Tastatur/Maus","Hüllen/Folien","Kamera/Actioncam","Ladegeräte/Kabel","Kleidung/Mode","Schuhe/Sneaker","Hautpflege","Make-up","Gesundheit","Küche","Sportartikel","Schreibwaren/Bücher","Spielzeug/Hobby","Gerät","Flasche","Set"],
fr:["Chargement...","Produits","Données élasticité","articles","Opt. appliquée","Marge moy.","Prix reco. moy.","Résultats canal","Historique récent","Prix actuel","Prix optimal","Marge attendue","Pas d'analyse","Actualiser","Enregistré","Image max 5Mo","Nom produit","Catégorie","Spécification","Unité","Prix d'achat","Frais E/S","Frais stockage","Frais travail","Frais livraison","Coût produit(auto)","Marge cible","Prix de vente base","Qté/carton","Cartons/palette","Stock initial","Fichier vide","Résultat upload","Succès","Échec","Erreur upload","Upload en cours...","Upload Excel en masse","Télécharger Excel","Modèle Excel","Enreg. produit","Image produit","Glisser-déposer","Max","Choisir catégorie","Carton/Palette","Carton","Unité","Palette","Saisie stock","Type saisie","Par unité","Par carton","Par palette","Saisie quantité","Total unités","Total cartons","Total palettes","Détail coûts","Enregistrer produit","Produits enregistrés","Spéc.","Coût","Marge","Prix base","Aucun produit","Paramètres calcul","SKU","Canal","Tout unifié","Prix vente actuel","Qté stock","Calcul en cours...","Calculer optimal","Prix coût","Prix min. applicable","Qté attendue","pcs","Stock faible","Suggestion premium","Stock élevé","Suggestion liquidation","Liste prix invalide","Simulation échouée","Simulation scénario","Prix test","Lancer simulation","Profit total","Budget total","Lancer mix canal","ROI unifié","% alloc.","Budget exec","Retour attendu","Profit attendu","Simulations passées","Alerte prix min","ou moins","Enreg. promo","Calendrier promo","Scénario","Planifié","Brouillon","Enregistré","Enregistrer","Intégration DS","Règles actives","Changements aujourd'hui","Amélioration marge moy.","Règles auto","Actif","Inactif","Arrêt","Activer","Historique modif.","Heure","Canal","Commission","Taxe","Total","Région","Frais de canal","Détail des frais par canal","Lecture seule","National","Global","Conseils frais","Les frais varient selon le canal","Tableau de bord","Enregistrement produits","Calcul prix optimal IA","Simulation scénario","Optimisation mix canal","Règles auto tarification","Veille concurrentielle","Calendrier promo","Frais de canal","Guide d'utilisation","Guide Optimisation Prix","Guide complet d'optimisation des prix","Étape par étape","Guide onglets","Conseils experts","Résumé","Optimiser","Mix Canal","Prix Auto","Concurrence","Frais Canal","Guide","Optimisation des Prix","Optimisation des prix en temps réel","Unité canal","Sync temps réel","Sécurité active","Violation sécurité bloquée","Fermer","Audio/Enceintes","Clavier/Souris","Coques/Films","Caméra/Action Cam","Chargeurs/Câbles","Vêtements/Mode","Chaussures/Sneakers","Soins peau","Maquillage","Aliments santé","Cuisine","Sports","Papeterie/Livres","Jouets/Loisirs","Appareil","Bouteille","Ensemble"],
};
T.es=T.en.slice();T.pt=T.en.slice();T.ru=T.en.slice();T.ar=T.en.slice();T.hi=T.en.slice();
T.th=T.en.slice();T.vi=T.en.slice();T.id=T.en.slice();T["zh-TW"]=T.zh.slice();
// Override key fields for secondary langs
const ov={
es:{0:"Cargando...",136:"Optimización de Precios",137:"Optimización de precios en tiempo real"},
pt:{0:"Carregando...",136:"Otimização de Preços",137:"Otimização de preços em tempo real"},
ru:{0:"Загрузка...",136:"Оптимизация цен",137:"Оптимизация цен в реальном времени"},
ar:{0:"جارٍ التحميل...",136:"تحسين الأسعار",137:"تحسين الأسعار في الوقت الفعلي"},
hi:{0:"लोड हो रहा है...",136:"मूल्य अनुकूलन",137:"वास्तविक समय मूल्य अनुकूलन"},
th:{0:"กำลังโหลด...",136:"เพิ่มประสิทธิภาพราคา",137:"การเพิ่มประสิทธิภาพราคาแบบเรียลไทม์"},
vi:{0:"Đang tải...",136:"Tối ưu Giá",137:"Tối ưu giá thời gian thực"},
id:{0:"Memuat...",136:"Optimasi Harga",137:"Optimasi harga real-time"},
"zh-TW":{0:"載入中..."},
};
Object.entries(ov).forEach(([lang,patches])=>{
  Object.entries(patches).forEach(([i,v])=>{T[lang][parseInt(i)]=v;});
});

let out='const D={\n';
Object.entries(T).forEach(([lang,vals])=>{
  out+=JSON.stringify(lang)+':{';
  vals.forEach((v,i)=>{out+=JSON.stringify(K[i])+':'+JSON.stringify(v);if(i<vals.length-1)out+=',';});
  out+='},\n';
});
out+='};\nexport default D;\n';
fs.writeFileSync('src/pages/poI18n.js',out);
console.log('poI18n.js written: '+Object.keys(T).length+' langs, '+K.length+' keys');
