// Merge missing dash keys into locale files
// Strategy: Read existing dash/dashTabs/dashPeriod, add missing keys with translations
const fs=require('fs'),p=require('path');
const dir=p.resolve(__dirname,'src/i18n/locales');

// Translations per language for dash.* keys (only non-English ones)
const T={
ar:{totalRev:'إجمالي الإيرادات',totalSpend:'إجمالي الإنفاق',blendedRoas:'ROAS المدمج',activeCh:'القنوات النشطة',totalClicks:'إجمالي النقرات',avgCtr:'متوسط CTR',noChannelData:'لا توجد بيانات قنوات',connectChannels:'اربط قنوات الإعلانات لعرض البيانات',allChSummary:'ملخص جميع القنوات',chTrend:'اتجاه القنوات',chPerfSumm:'ملخص أداء القنوات',noTrendData:'لا توجد بيانات اتجاه',clickChannelHint:'انقر على بطاقة قناة ← تحليل 5 أقسام',spendDistribution:'توزيع الإنفاق',adSpend:'إنفاق الإعلانات',adRev:'إيرادات الإعلانات',netProfit:'صافي الربح',impressions:'مرات الظهور',reach:'الوصول',frequency:'التكرار',clicks:'النقرات',videoViews:'مشاهدات الفيديو',avgViewTime:'متوسط وقت المشاهدة',sessions:'الجلسات',bounceRate:'معدل الارتداد',avgDuration:'متوسط المدة',convCount:'التحويلات',convRate:'معدل التحويل',purchaseCount:'المشتريات',signups:'التسجيلات',cartAdds:'إضافات السلة',rev:'الإيرادات',orders:'الطلبات',securityAlert:'تنبيه أمني',threatsDetected:'تهديدات مكتشفة',securityMonitor:'مراقب الأمان',noSecurityIssues:'لا مشاكل أمنية',protected:'محمي',blocked:'محظور',enforced:'مطبق',secureStatus:'آمن',liveActivity:'النشاط المباشر',noActivity:'لا نشاط',all:'الكل',warnings:'تحذيرات',info:'معلومات',vsYesterday:'مقابل أمس',channelMix:'مزيج إيرادات القنوات',crossModuleSummary:'ملخص عبر الوحدات',moduleShortcuts:'اختصارات الوحدات',activeCampaigns:'الحملات النشطة',aiAdAnal:'🤖 تحليل إعلانات AI',channelPerf:'📊 أداء القنوات',fiveSectionAnalysis:'تحليل 5 أقسام',reachAwareness:'1. الوصول والوعي',engagement2:'2. التفاعل',traffic2:'3. حركة المرور',conv2:'4. التحويل',revRoi2:'5. الإيرادات وROI',chDetailTable:'جدول تفاصيل القنوات',chName:'القناة',achvRate:'نسبة التحقيق',realTimeBlendedRoas:'ROAS المدمج الفوري',convFunnel:'قمع التحويل',genderDist:'توزيع الجنس/العمر',regDist:'التوزيع الإقليمي'},
de:{totalRev:'Gesamtumsatz',totalSpend:'Gesamtausgaben',blendedRoas:'Gemischter ROAS',activeCh:'Aktive Kanäle',totalClicks:'Gesamtklicks',avgCtr:'Durchschn. CTR',noChannelData:'Keine Kanaldaten',connectChannels:'Verbinden Sie Werbekanäle',allChSummary:'Gesamtkanalübersicht',chTrend:'Kanaltrend',chPerfSumm:'Kanalleistungsübersicht',noTrendData:'Keine Trenddaten',clickChannelHint:'Kanalkarte klicken → 5-Sektionen-Analyse',spendDistribution:'Ausgabenverteilung',adSpend:'Werbeausgaben',adRev:'Werbeeinnahmen',netProfit:'Nettogewinn',impressions:'Impressionen',reach:'Reichweite',frequency:'Häufigkeit',clicks:'Klicks',videoViews:'Videoaufrufe',avgViewTime:'Durchschn. Ansichtszeit',sessions:'Sitzungen',bounceRate:'Absprungrate',avgDuration:'Durchschn. Dauer',convCount:'Konversionen',convRate:'Konversionsrate',purchaseCount:'Käufe',signups:'Anmeldungen',cartAdds:'Warenkorb',rev:'Umsatz',orders:'Bestellungen',securityAlert:'Sicherheitswarnung',threatsDetected:'Bedrohungen erkannt',securityMonitor:'Sicherheitsmonitor',noSecurityIssues:'Keine Sicherheitsprobleme',protected:'Geschützt',blocked:'Blockiert',enforced:'Durchgesetzt',secureStatus:'Sicher',liveActivity:'Live-Aktivität',noActivity:'Keine Aktivität',all:'Alle',warnings:'Warnungen',info:'Info',vsYesterday:'ggü. Gestern',channelMix:'Kanal-Umsatzmix',aiAdAnal:'🤖 KI-Anzeigenanalyse',channelPerf:'📊 Kanalleistung',fiveSectionAnalysis:'5-Sektionen-Analyse',reachAwareness:'1. Reichweite',engagement2:'2. Engagement',traffic2:'3. Traffic',conv2:'4. Konversion',revRoi2:'5. Umsatz & ROI',chDetailTable:'Kanaldetailtabelle',chName:'Kanal',realTimeBlendedRoas:'Echtzeit-ROAS',convFunnel:'Konversionstrichter',genderDist:'Geschlecht/Alter',regDist:'Regionale Verteilung'},
zh:{totalRev:'总收入',totalSpend:'总支出',blendedRoas:'综合ROAS',activeCh:'活跃渠道',totalClicks:'总点击',avgCtr:'平均CTR',noChannelData:'暂无渠道数据',connectChannels:'连接广告渠道以查看数据',allChSummary:'全渠道摘要',chTrend:'渠道趋势',chPerfSumm:'渠道绩效摘要',noTrendData:'暂无趋势数据',clickChannelHint:'点击渠道卡片→5区分析',spendDistribution:'支出分布',adSpend:'广告支出',adRev:'广告收入',netProfit:'净利润',impressions:'曝光',reach:'覆盖',frequency:'频次',clicks:'点击',videoViews:'视频播放',sessions:'会话',bounceRate:'跳出率',avgDuration:'平均时长',convCount:'转化数',convRate:'转化率',purchaseCount:'购买数',signups:'注册',cartAdds:'加购',rev:'收入',orders:'订单',securityAlert:'安全警报',threatsDetected:'检测到威胁',securityMonitor:'安全监控',noSecurityIssues:'无安全问题',protected:'已保护',blocked:'已拦截',enforced:'已执行',secureStatus:'安全',liveActivity:'实时活动',noActivity:'无活动',all:'全部',warnings:'警告',info:'信息',vsYesterday:'较昨日',channelMix:'渠道收入组合',aiAdAnal:'🤖 AI广告分析',fiveSectionAnalysis:'5区分析',reachAwareness:'1. 覆盖与认知',engagement2:'2. 互动',traffic2:'3. 流量',conv2:'4. 转化',revRoi2:'5. 收入与ROI',chDetailTable:'渠道明细表',chName:'渠道',realTimeBlendedRoas:'实时综合ROAS',convFunnel:'转化漏斗',genderDist:'性别/年龄分布',regDist:'地区分布'},
th:{totalRev:'รายได้รวม',totalSpend:'ค่าใช้จ่ายรวม',blendedRoas:'ROAS รวม',activeCh:'ช่องทางที่ใช้งาน',totalClicks:'คลิกทั้งหมด',avgCtr:'CTR เฉลี่ย',noChannelData:'ไม่มีข้อมูลช่องทาง',connectChannels:'เชื่อมต่อช่องทางโฆษณา',allChSummary:'สรุปทุกช่องทาง',chTrend:'แนวโน้มช่องทาง',chPerfSumm:'สรุปผลช่องทาง',noTrendData:'ไม่มีข้อมูลแนวโน้ม',adSpend:'ค่าโฆษณา',adRev:'รายได้โฆษณา',netProfit:'กำไรสุทธิ',impressions:'การแสดงผล',reach:'การเข้าถึง',clicks:'คลิก',sessions:'เซสชัน',bounceRate:'อัตราตีกลับ',convCount:'การแปลง',convRate:'อัตราการแปลง',rev:'รายได้',orders:'คำสั่งซื้อ',securityAlert:'แจ้งเตือนความปลอดภัย',securityMonitor:'ตัวตรวจสอบความปลอดภัย',liveActivity:'กิจกรรมสด',all:'ทั้งหมด',warnings:'คำเตือน',vsYesterday:'เทียบกับเมื่อวาน',aiAdAnal:'🤖 วิเคราะห์โฆษณา AI',fiveSectionAnalysis:'วิเคราะห์ 5 ส่วน'},
vi:{totalRev:'Tổng doanh thu',totalSpend:'Tổng chi tiêu',blendedRoas:'ROAS tổng hợp',activeCh:'Kênh hoạt động',totalClicks:'Tổng nhấp',avgCtr:'CTR trung bình',noChannelData:'Không có dữ liệu kênh',connectChannels:'Kết nối kênh quảng cáo',allChSummary:'Tổng hợp các kênh',chTrend:'Xu hướng kênh',chPerfSumm:'Tóm tắt hiệu suất kênh',noTrendData:'Không có dữ liệu xu hướng',adSpend:'Chi phí quảng cáo',adRev:'Doanh thu quảng cáo',netProfit:'Lợi nhuận ròng',impressions:'Lượt hiển thị',reach:'Tiếp cận',clicks:'Nhấp',sessions:'Phiên',bounceRate:'Tỷ lệ thoát',convCount:'Chuyển đổi',convRate:'Tỷ lệ chuyển đổi',rev:'Doanh thu',orders:'Đơn hàng',securityAlert:'Cảnh báo bảo mật',securityMonitor:'Giám sát bảo mật',liveActivity:'Hoạt động trực tiếp',all:'Tất cả',warnings:'Cảnh báo',vsYesterday:'so với hôm qua',aiAdAnal:'🤖 Phân tích quảng cáo AI',fiveSectionAnalysis:'Phân tích 5 phần'},
id:{totalRev:'Total Pendapatan',totalSpend:'Total Pengeluaran',blendedRoas:'ROAS Gabungan',activeCh:'Saluran Aktif',totalClicks:'Total Klik',avgCtr:'CTR Rata-rata',noChannelData:'Tidak ada data saluran',connectChannels:'Hubungkan saluran iklan',allChSummary:'Ringkasan Semua Saluran',chTrend:'Tren Saluran',chPerfSumm:'Ringkasan Kinerja Saluran',noTrendData:'Tidak ada data tren',adSpend:'Belanja Iklan',adRev:'Pendapatan Iklan',netProfit:'Laba Bersih',impressions:'Tayangan',reach:'Jangkauan',clicks:'Klik',sessions:'Sesi',bounceRate:'Rasio Pentalan',convCount:'Konversi',convRate:'Rasio Konversi',rev:'Pendapatan',orders:'Pesanan',securityAlert:'Peringatan Keamanan',securityMonitor:'Monitor Keamanan',liveActivity:'Aktivitas Langsung',all:'Semua',warnings:'Peringatan',vsYesterday:'vs Kemarin',aiAdAnal:'🤖 Analisis Iklan AI',fiveSectionAnalysis:'Analisis 5 Bagian'},
es:{totalRev:'Ingresos Totales',totalSpend:'Gasto Total',blendedRoas:'ROAS Combinado',activeCh:'Canales Activos',totalClicks:'Clics Totales',avgCtr:'CTR Promedio',noChannelData:'Sin datos de canales',connectChannels:'Conecte canales de anuncios',allChSummary:'Resumen de Canales',chTrend:'Tendencia de Canales',chPerfSumm:'Resumen de Rendimiento',noTrendData:'Sin datos de tendencia',adSpend:'Gasto Publicitario',adRev:'Ingresos Publicitarios',netProfit:'Beneficio Neto',impressions:'Impresiones',reach:'Alcance',clicks:'Clics',sessions:'Sesiones',bounceRate:'Tasa de Rebote',convCount:'Conversiones',convRate:'Tasa de Conversión',rev:'Ingresos',orders:'Pedidos',securityAlert:'Alerta de Seguridad',securityMonitor:'Monitor de Seguridad',liveActivity:'Actividad en Vivo',all:'Todo',warnings:'Advertencias',vsYesterday:'vs Ayer',aiAdAnal:'🤖 Análisis de Anuncios IA',fiveSectionAnalysis:'Análisis de 5 Secciones'},
fr:{totalRev:'Revenus Totaux',totalSpend:'Dépenses Totales',blendedRoas:'ROAS Combiné',activeCh:'Canaux Actifs',totalClicks:'Clics Totaux',avgCtr:'CTR Moyen',noChannelData:'Aucune donnée de canal',connectChannels:'Connectez les canaux publicitaires',allChSummary:'Résumé des Canaux',chTrend:'Tendance des Canaux',chPerfSumm:'Résumé des Performances',noTrendData:'Aucune donnée de tendance',adSpend:'Dépenses Publicitaires',adRev:'Revenus Publicitaires',netProfit:'Bénéfice Net',impressions:'Impressions',reach:'Portée',clicks:'Clics',sessions:'Sessions',bounceRate:'Taux de Rebond',convCount:'Conversions',convRate:'Taux de Conversion',rev:'Revenus',orders:'Commandes',securityAlert:'Alerte de Sécurité',securityMonitor:'Moniteur de Sécurité',liveActivity:'Activité en Direct',all:'Tout',warnings:'Avertissements',vsYesterday:'vs Hier',aiAdAnal:'🤖 Analyse Publicitaire IA',fiveSectionAnalysis:'Analyse en 5 Sections'},
pt:{totalRev:'Receita Total',totalSpend:'Gasto Total',blendedRoas:'ROAS Combinado',activeCh:'Canais Ativos',totalClicks:'Cliques Totais',avgCtr:'CTR Médio',noChannelData:'Sem dados de canais',connectChannels:'Conecte canais de anúncios',allChSummary:'Resumo dos Canais',chTrend:'Tendência dos Canais',chPerfSumm:'Resumo de Desempenho',noTrendData:'Sem dados de tendência',adSpend:'Gasto com Anúncios',adRev:'Receita de Anúncios',netProfit:'Lucro Líquido',impressions:'Impressões',reach:'Alcance',clicks:'Cliques',sessions:'Sessões',bounceRate:'Taxa de Rejeição',convCount:'Conversões',convRate:'Taxa de Conversão',rev:'Receita',orders:'Pedidos',securityAlert:'Alerta de Segurança',securityMonitor:'Monitor de Segurança',liveActivity:'Atividade ao Vivo',all:'Tudo',warnings:'Avisos',vsYesterday:'vs Ontem',aiAdAnal:'🤖 Análise de Anúncios IA',fiveSectionAnalysis:'Análise de 5 Seções'},
ru:{totalRev:'Общий доход',totalSpend:'Общие расходы',blendedRoas:'Общий ROAS',activeCh:'Активные каналы',totalClicks:'Всего кликов',avgCtr:'Средний CTR',noChannelData:'Нет данных каналов',connectChannels:'Подключите рекламные каналы',allChSummary:'Сводка по каналам',chTrend:'Тренд каналов',chPerfSumm:'Сводка эффективности',noTrendData:'Нет данных тренда',adSpend:'Рекламные расходы',adRev:'Рекламный доход',netProfit:'Чистая прибыль',impressions:'Показы',reach:'Охват',clicks:'Клики',sessions:'Сессии',bounceRate:'Показатель отказов',convCount:'Конверсии',convRate:'Коэфф. конверсии',rev:'Доход',orders:'Заказы',securityAlert:'Предупреждение безопасности',securityMonitor:'Монитор безопасности',liveActivity:'Активность в реальном времени',all:'Все',warnings:'Предупреждения',vsYesterday:'vs Вчера',aiAdAnal:'🤖 ИИ-анализ рекламы',fiveSectionAnalysis:'5-секционный анализ'},
hi:{totalRev:'कुल राजस्व',totalSpend:'कुल खर्च',blendedRoas:'मिश्रित ROAS',activeCh:'सक्रिय चैनल',totalClicks:'कुल क्लिक',avgCtr:'औसत CTR',noChannelData:'कोई चैनल डेटा नहीं',connectChannels:'विज्ञापन चैनल कनेक्ट करें',allChSummary:'सभी चैनल सारांश',chTrend:'चैनल ट्रेंड',chPerfSumm:'चैनल प्रदर्शन सारांश',noTrendData:'कोई ट्रेंड डेटा नहीं',adSpend:'विज्ञापन खर्च',adRev:'विज्ञापन राजस्व',netProfit:'शुद्ध लाभ',impressions:'इंप्रेशन',reach:'पहुंच',clicks:'क्लिक',sessions:'सत्र',bounceRate:'बाउंस दर',convCount:'रूपांतरण',convRate:'रूपांतरण दर',rev:'राजस्व',orders:'ऑर्डर',securityAlert:'सुरक्षा चेतावनी',securityMonitor:'सुरक्षा मॉनिटर',liveActivity:'लाइव गतिविधि',all:'सभी',warnings:'चेतावनियां',vsYesterday:'कल की तुलना',aiAdAnal:'🤖 AI विज्ञापन विश्लेषण',fiveSectionAnalysis:'5-सेक्शन विश्लेषण'},
'zh-TW':{totalRev:'總收入',totalSpend:'總支出',blendedRoas:'綜合ROAS',activeCh:'活躍頻道',totalClicks:'總點擊',avgCtr:'平均CTR',noChannelData:'暫無頻道資料',connectChannels:'連接廣告頻道以查看資料',allChSummary:'全頻道摘要',chTrend:'頻道趨勢',chPerfSumm:'頻道績效摘要',noTrendData:'暫無趨勢資料',adSpend:'廣告支出',adRev:'廣告收入',netProfit:'淨利潤',impressions:'曝光',reach:'觸及',clicks:'點擊',sessions:'工作階段',bounceRate:'跳出率',convCount:'轉換',convRate:'轉換率',rev:'收入',orders:'訂單',securityAlert:'安全警報',securityMonitor:'安全監控',liveActivity:'即時活動',all:'全部',warnings:'警告',vsYesterday:'較昨日',aiAdAnal:'🤖 AI廣告分析',fiveSectionAnalysis:'5區分析'}
};

for(const[lang,newKeys]of Object.entries(T)){
  const fp=p.join(dir,lang+'.js');
  if(!fs.existsSync(fp)){console.log('SKIP '+lang);continue;}
  let src=fs.readFileSync(fp,'utf8');
  
  // Find the "dash": { ... } block and add missing keys
  const dashMatch=src.match(/"dash"\s*:\s*\{/);
  if(!dashMatch){console.log(`${lang}: no dash block`);continue;}
  
  const insertPos=dashMatch.index+dashMatch[0].length;
  let additions='';
  for(const[k,v]of Object.entries(newKeys)){
    // Check if key already exists in dash block
    const keyPattern=new RegExp(`"${k}"\\s*:`);
    // Only check in a reasonable range after "dash": {
    const searchRange=src.substring(insertPos,insertPos+5000);
    if(!keyPattern.test(searchRange)){
      additions+=`\n    "${k}": ${JSON.stringify(v)},`;
    }
  }
  
  if(additions){
    src=src.substring(0,insertPos)+additions+src.substring(insertPos);
    fs.writeFileSync(fp,src,'utf8');
    console.log(`✅ ${lang}.js: ${additions.split('\n').length-1} keys added`);
  } else {
    console.log(`⏭ ${lang}.js: all keys exist`);
  }
}
console.log('Done!');
