const fs=require('fs'),p=require('path');
const dir=p.resolve(__dirname,'src/i18n/locales');
const T={
fr:{guideFullTitle:'📋 Guide Complet — Du Début à la Fin',guideFullSub:'Guide étape par étape du flux complet de la plateforme.',guidePhaseA:'Phase A — Préparation',guidePhaseB:'Phase B — Conception de Campagne',guidePhaseC:'Phase C — Stratégie IA & Créatifs',guidePhaseD:'Phase D — Exécution & Suivi',guidePhaseE:'Phase E — Optimisation & Clôture',
gf1Title:'Connexion & Vérification',gf1Desc:'Connectez-vous et naviguez vers "Marketing IA → Stratégie Auto" dans la barre latérale.',
gf2Title:'Connecter les Canaux API',gf2Desc:'Enregistrez les clés API pour Meta, Google, Naver dans le Hub d\'Intégration.',
gf3Title:'Examiner les KPI du Tableau de Bord',gf3Desc:'Vérifiez les KPI actuels, campagnes actives et ROAS par canal.',
gf4Title:'Définir le Budget Mensuel',gf4Desc:'Dans l\'onglet "② Configuration", sélectionnez votre budget publicitaire mensuel.',
gf5Title:'Sélectionner les Catégories',gf5Desc:'Choisissez parmi 11 catégories. La sélection multiple permet l\'analyse croisée.',
gf6Title:'Choisir les Canaux Publicitaires',gf6Desc:'L\'IA recommande les combinaisons optimales basées sur catégorie + budget.',
gf7Title:'Définir Cible & Période',gf7Desc:'Configurez le nom, la période d\'exécution et le public cible de la campagne.',
gf8Title:'Simulation de Stratégie IA',gf8Desc:'Cliquez "Générer Stratégie IA" pour le calcul automatique par canal.',
gf9Title:'Créer les Visuels Publicitaires',gf9Desc:'Dans "① Studio Créatif", l\'IA génère automatiquement des visuels optimisés par canal.',
gf10Title:'Aperçu & Ajustement',gf10Desc:'Dans "③ Aperçu IA", examinez les allocations et KPI estimés par canal.',
gf11Title:'Soumettre pour Approbation',gf11Desc:'Finalisez et cliquez "Demander l\'Approbation". Vérifiez budget et ROAS avant envoi.',
gf12Title:'Suivi dans le Gestionnaire',gf12Desc:'Les campagnes soumises sont suivies en temps réel. Surveillez le statut.',
gf13Title:'Optimisation Automatique IA',gf13Desc:'L\'IA réalloue automatiquement le budget des canaux faibles vers les performants.',
gf14Title:'Analyser les Rapports',gf14Desc:'Après la campagne, analysez ROAS, CPA, CTR par canal. L\'IA suggère des améliorations.',
gf15Title:'Itérer la Prochaine Campagne',gf15Desc:'Ajustez budget/catégories/canaux pour une nouvelle campagne. L\'apprentissage IA s\'améliore.',
guideTabGuideName:'📖 Guide Utilisateur',guideTabGuideDesc:'Guide étape par étape des fonctionnalités et du flux complet.',
guideTip6:'Comparez les canaux recommandés par l\'IA avec vos sélections manuelles.',
guideTip7:'Soumettez toujours pour approbation avant exécution pour éviter les dépassements.',
csTitle:'Studio Créatif',csSubtitle:'Concevoir et gérer les visuels publicitaires multi-plateformes',
csTabGallery:'Galerie',csTabCreateNew:'Créer',csTabPerformance:'Performance',csTabBrandAssets:'Actifs de Marque',
csKpiCreatives:'Créatifs',csKpiFormats:'Formats',csKpiApproved:'Approuvés',csKpiTopCtr:'Meilleur CTR',
csFeatMultiFormat:'Export multi-format',csFeatAiCopy:'Générateur de texte IA',csFeatPerfAnalytics:'Analyse de performance',csFeatBrandCheck:'Vérification de cohérence de marque',
csSystemOk:'Système opérationnel',autoTab1:'① Studio Créatif'},
th:{guideFullTitle:'📋 คู่มือฉบับสมบูรณ์ — ตั้งแต่ต้นจนจบ',guideFullSub:'คู่มือทีละขั้นตอนสำหรับแพลตฟอร์มการตลาดอัตโนมัติ AI',guidePhaseA:'เฟส A — เตรียมเริ่มต้น',guidePhaseB:'เฟส B — ออกแบบแคมเปญ',guidePhaseC:'เฟส C — กลยุทธ์ AI และสร้างสรรค์',guidePhaseD:'เฟส D — ดำเนินการและติดตาม',guidePhaseE:'เฟส E — เพิ่มประสิทธิภาพและสรุป',
gf1Title:'เข้าสู่ระบบและตรวจสอบ',gf1Desc:'เข้าสู่ระบบและไปที่ "การตลาด AI → กลยุทธ์อัตโนมัติ" จากแถบด้านข้าง',
gf2Title:'เชื่อมต่อช่อง API',gf2Desc:'ลงทะเบียน API Key สำหรับ Meta, Google, Naver ในศูนย์การรวม',
gf3Title:'ตรวจสอบ KPI แดชบอร์ด',gf3Desc:'ตรวจสอบ KPI ปัจจุบัน แคมเปญที่ใช้งาน และ ROAS ต่อช่อง',
gf4Title:'ตั้งงบประมาณรายเดือน',gf4Desc:'ในแท็บ "②ตั้งค่าแคมเปญ" เลือกหรือป้อนงบโฆษณารายเดือน',
gf5Title:'เลือกหมวดหมู่สินค้า',gf5Desc:'เลือกจาก 11 หมวดหมู่ การเลือกหลายรายการช่วยวิเคราะห์ข้ามกลุ่ม',
gf6Title:'เลือกช่องโฆษณา',gf6Desc:'AI แนะนำการรวมช่องที่เหมาะสมที่สุดตามหมวดหมู่+งบประมาณ',
gf7Title:'ตั้งเป้าหมายและระยะเวลา',gf7Desc:'กำหนดชื่อแคมเปญ ระยะเวลาดำเนินการ และกลุ่มเป้าหมาย',
gf8Title:'จำลองกลยุทธ์ AI',gf8Desc:'คลิก "สร้างกลยุทธ์ AI" เพื่อคำนวณการจัดสรรงบอัตโนมัติ',
gf9Title:'สร้างชิ้นงานโฆษณา',gf9Desc:'ในแท็บ "①สตูดิโอสร้างสรรค์" AI สร้างชิ้นงานที่เพิ่มประสิทธิภาพอัตโนมัติ',
gf10Title:'ดูตัวอย่างและปรับกลยุทธ์',gf10Desc:'ในแท็บ "③ดูตัวอย่าง AI" ตรวจสอบการจัดสรรและ KPI ที่คาดการณ์',
gf11Title:'ส่งขออนุมัติ',gf11Desc:'สรุปกลยุทธ์และคลิก "ขออนุมัติ" ตรวจสอบงบ ROAS และช่องก่อนส่ง',
gf12Title:'ติดตามในตัวจัดการแคมเปญ',gf12Desc:'แคมเปญที่ส่งจะถูกติดตามแบบเรียลไทม์ ติดตามสถานะ',
gf13Title:'AI ปรับแต่งอัตโนมัติ',gf13Desc:'AI วิเคราะห์ข้อมูลแบบเรียลไทม์และจัดสรรงบใหม่อัตโนมัติ',
gf14Title:'วิเคราะห์รายงานผลลัพธ์',gf14Desc:'หลังแคมเปญ วิเคราะห์ ROAS, CPA, CTR ต่อช่อง AI แนะนำการปรับปรุง',
gf15Title:'ทำซ้ำแคมเปญถัดไป',gf15Desc:'ปรับงบ/หมวดหมู่/ช่องตามผลวิเคราะห์ การเรียนรู้ AI ดีขึ้นทุกรอบ',
guideTabGuideName:'📖 คู่มือการใช้งาน',guideTabGuideDesc:'คู่มือทีละขั้นตอนของฟีเจอร์และเวิร์กโฟลว์ทั้งหมด',
guideTip6:'เปรียบเทียบช่องที่ AI แนะนำกับที่เลือกเองเพื่อหาส่วนผสมที่ดีที่สุด',
guideTip7:'ส่งขออนุมัติก่อนดำเนินการเสมอเพื่อป้องกันงบเกิน',
csTitle:'สตูดิโอสร้างสรรค์',csSubtitle:'ออกแบบและจัดการชิ้นงานโฆษณาข้ามแพลตฟอร์ม',
csTabGallery:'แกลเลอรี',csTabCreateNew:'สร้างใหม่',csTabPerformance:'ประสิทธิภาพ',csTabBrandAssets:'แบรนด์แอสเซท',
csKpiCreatives:'ชิ้นงาน',csKpiFormats:'รูปแบบ',csKpiApproved:'อนุมัติแล้ว',csKpiTopCtr:'CTR สูงสุด',
csFeatMultiFormat:'ส่งออกหลายรูปแบบ',csFeatAiCopy:'AI สร้างข้อความ',csFeatPerfAnalytics:'วิเคราะห์ประสิทธิภาพ',csFeatBrandCheck:'ตรวจสอบความสอดคล้องแบรนด์',
csSystemOk:'ระบบทำงานปกติ',autoTab1:'① สตูดิโอสร้างสรรค์'},
vi:{guideFullTitle:'📋 Hướng Dẫn Đầy Đủ — Từ Đầu Đến Cuối',guideFullSub:'Hướng dẫn từng bước quy trình marketing AI tự động hóa.',guidePhaseA:'Giai đoạn A — Chuẩn Bị',guidePhaseB:'Giai đoạn B — Thiết Kế Chiến Dịch',guidePhaseC:'Giai đoạn C — Chiến Lược AI & Sáng Tạo',guidePhaseD:'Giai đoạn D — Thực Hiện & Giám Sát',guidePhaseE:'Giai đoạn E — Tối Ưu & Hoàn Tất',
gf1Title:'Đăng Nhập & Kiểm Tra',gf1Desc:'Đăng nhập và điều hướng đến "Marketing AI → Chiến lược tự động".',
gf2Title:'Kết Nối Kênh API',gf2Desc:'Đăng ký API Key cho Meta, Google, Naver trong Trung tâm tích hợp.',
gf3Title:'Xem KPI Dashboard',gf3Desc:'Kiểm tra KPI hiện tại, chiến dịch đang hoạt động và ROAS theo kênh.',
gf4Title:'Đặt Ngân Sách Hàng Tháng',gf4Desc:'Trong tab "②Thiết lập chiến dịch", chọn hoặc nhập ngân sách quảng cáo.',
gf5Title:'Chọn Danh Mục Sản Phẩm',gf5Desc:'Chọn từ 11 danh mục. Chọn nhiều giúp phân tích chéo chính xác hơn.',
gf6Title:'Chọn Kênh Quảng Cáo',gf6Desc:'AI đề xuất tổ hợp kênh tối ưu dựa trên danh mục + ngân sách.',
gf7Title:'Đặt Mục Tiêu & Thời Gian',gf7Desc:'Cấu hình tên chiến dịch, thời gian thực hiện và đối tượng mục tiêu.',
gf8Title:'Mô Phỏng Chiến Lược AI',gf8Desc:'Nhấp "Tạo chiến lược AI" để tự động tính phân bổ ngân sách theo kênh.',
gf9Title:'Tạo Nội Dung Quảng Cáo',gf9Desc:'Trong tab "①Studio sáng tạo", AI tự động tạo nội dung tối ưu cho mỗi kênh.',
gf10Title:'Xem Trước & Điều Chỉnh',gf10Desc:'Trong tab "③Xem trước AI", xem phân bổ và KPI dự kiến theo kênh.',
gf11Title:'Gửi Phê Duyệt',gf11Desc:'Hoàn tất chiến lược và nhấp "Yêu cầu phê duyệt". Kiểm tra trước khi gửi.',
gf12Title:'Giám Sát Trong Trình Quản Lý',gf12Desc:'Chiến dịch được theo dõi thời gian thực. Giám sát trạng thái.',
gf13Title:'AI Tự Động Tối Ưu',gf13Desc:'AI phân tích dữ liệu thời gian thực và tái phân bổ ngân sách tự động.',
gf14Title:'Phân Tích Báo Cáo',gf14Desc:'Sau chiến dịch, phân tích ROAS, CPA, CTR theo kênh. AI đề xuất cải thiện.',
gf15Title:'Lặp Lại Chiến Dịch Tiếp',gf15Desc:'Điều chỉnh ngân sách/danh mục/kênh để tạo chiến dịch mới. AI học tốt hơn mỗi lần.',
guideTabGuideName:'📖 Hướng Dẫn Sử Dụng',guideTabGuideDesc:'Hướng dẫn từng bước về tính năng và quy trình đầy đủ.',
guideTip6:'So sánh kênh AI đề xuất với lựa chọn thủ công để tìm tổ hợp tối ưu.',
guideTip7:'Luôn gửi phê duyệt quản lý trước khi thực hiện để tránh vượt ngân sách.',
csTitle:'Studio Sáng Tạo',csSubtitle:'Thiết kế và quản lý nội dung quảng cáo đa nền tảng',
csTabGallery:'Thư Viện',csTabCreateNew:'Tạo Mới',csTabPerformance:'Hiệu Suất',csTabBrandAssets:'Tài Sản Thương Hiệu',
csKpiCreatives:'Sáng tạo',csKpiFormats:'Định dạng',csKpiApproved:'Đã duyệt',csKpiTopCtr:'CTR cao nhất',
csFeatMultiFormat:'Xuất đa định dạng',csFeatAiCopy:'AI tạo bản sao',csFeatPerfAnalytics:'Phân tích hiệu suất',csFeatBrandCheck:'Kiểm tra tính nhất quán thương hiệu',
csSystemOk:'Hệ thống hoạt động bình thường',autoTab1:'① Studio Sáng Tạo'},
id:{guideFullTitle:'📋 Panduan Lengkap — Dari Awal Hingga Akhir',guideFullSub:'Panduan langkah demi langkah alur kerja platform otomasi pemasaran AI.',guidePhaseA:'Fase A — Persiapan Awal',guidePhaseB:'Fase B — Desain Kampanye',guidePhaseC:'Fase C — Strategi AI & Kreatif',guidePhaseD:'Fase D — Eksekusi & Pemantauan',guidePhaseE:'Fase E — Optimalisasi & Penyelesaian',
gf1Title:'Login & Verifikasi',gf1Desc:'Login dan navigasi ke "Pemasaran AI → Strategi Otomatis" dari sidebar.',
gf2Title:'Hubungkan Channel API',gf2Desc:'Daftarkan API Key untuk Meta, Google, Naver di Hub Integrasi.',
gf3Title:'Tinjau KPI Dashboard',gf3Desc:'Periksa KPI saat ini, kampanye aktif, dan ROAS per channel.',
gf4Title:'Atur Anggaran Bulanan',gf4Desc:'Di tab "②Pengaturan Kampanye", pilih atau masukkan anggaran iklan bulanan.',
gf5Title:'Pilih Kategori Produk',gf5Desc:'Pilih dari 11 kategori. Pilihan ganda memungkinkan analisis silang.',
gf6Title:'Pilih Channel Iklan',gf6Desc:'AI merekomendasikan kombinasi channel optimal berdasarkan kategori + anggaran.',
gf7Title:'Atur Target & Periode',gf7Desc:'Konfigurasi nama kampanye, periode eksekusi, dan audiens target.',
gf8Title:'Simulasi Strategi AI',gf8Desc:'Klik "Buat Strategi AI" untuk menghitung alokasi anggaran otomatis per channel.',
gf9Title:'Buat Materi Iklan',gf9Desc:'Di tab "①Studio Kreatif", AI membuat materi iklan yang dioptimalkan per channel.',
gf10Title:'Pratinjau & Sesuaikan',gf10Desc:'Di tab "③Pratinjau AI", tinjau alokasi dan KPI per channel.',
gf11Title:'Kirim untuk Persetujuan',gf11Desc:'Finalisasi strategi dan klik "Minta Persetujuan". Periksa sebelum mengirim.',
gf12Title:'Pantau di Manajer Kampanye',gf12Desc:'Kampanye dilacak secara real-time. Pantau status kampanye.',
gf13Title:'Optimalisasi Otomatis AI',gf13Desc:'AI menganalisis data real-time dan mengalokasikan ulang anggaran secara otomatis.',
gf14Title:'Analisis Laporan Kinerja',gf14Desc:'Setelah kampanye, analisis ROAS, CPA, CTR per channel. AI menyarankan perbaikan.',
gf15Title:'Iterasi Kampanye Berikutnya',gf15Desc:'Sesuaikan anggaran/kategori/channel untuk kampanye baru. Pembelajaran AI meningkat.',
guideTabGuideName:'📖 Panduan Pengguna',guideTabGuideDesc:'Panduan langkah demi langkah fitur platform dan alur kerja lengkap.',
guideTip6:'Bandingkan channel rekomendasi AI dengan pilihan manual untuk menemukan campuran optimal.',
guideTip7:'Selalu kirim untuk persetujuan manajer sebelum eksekusi untuk mencegah pembengkakan anggaran.',
csTitle:'Studio Kreatif',csSubtitle:'Desain dan kelola materi iklan lintas platform',
csTabGallery:'Galeri',csTabCreateNew:'Buat Baru',csTabPerformance:'Kinerja',csTabBrandAssets:'Aset Merek',
csKpiCreatives:'Kreatif',csKpiFormats:'Format',csKpiApproved:'Disetujui',csKpiTopCtr:'CTR Tertinggi',
csFeatMultiFormat:'Ekspor multi-format',csFeatAiCopy:'Generator salinan AI',csFeatPerfAnalytics:'Analisis kinerja',csFeatBrandCheck:'Pemeriksaan konsistensi merek',
csSystemOk:'Sistem beroperasi normal',autoTab1:'① Studio Kreatif'},
};
function inject(lang,keys){const fp=p.join(dir,lang+'.js');let src=fs.readFileSync(fp,'utf8');const ni=src.indexOf('"marketing"');if(ni<0)return console.log(lang+': skip');const bi=src.indexOf('{',ni);let a='';const bl=src.substring(ni,Math.min(src.length,ni+50000));for(const[k,v]of Object.entries(keys)){if(!new RegExp(`"${k}"\\s*:`).test(bl))a+=`\n    "${k}": ${JSON.stringify(v)},`;}if(a){src=src.substring(0,bi+1)+a+src.substring(bi+1);fs.writeFileSync(fp,src,'utf8');console.log(`✅ ${lang}: ${a.split('\n').filter(l=>l.trim()).length} keys`);}else console.log(`⏭ ${lang}: exists`);}
for(const[l,k]of Object.entries(T))inject(l,k);
console.log('Batch 4 done!');
