const fs = require('fs');
const path = require('path');
const DIR = path.join(__dirname, 'src/i18n/locales');
const LANGS = ['ko','en','ja','zh','zh-TW','de','th','vi','id'];

const keys = {
  ko: {
    abPageTitle:"AI 마케팅 예산 배분",abPageSub:"데이터 기반 초지능 예산 배분 엔진 — 예측 AI 모델로 ROAS를 극대화하세요",
    abBtnGuide:"이용 가이드",abConnectedChannels:"연동된 광고 채널",
    abInputTitle:"총 마케팅 예산 입력",abInputDesc:"AI가 과거 전환 데이터, 채널별 수확체감 곡선, 실시간 시장 포화도를 분석하여 최적 배분을 추천합니다.",abInputPlaceholder:"예: 100,000,000",
    abBtnProcessing:"분석 중...",abBtnGenerate:"AI 플랜 생성",abMinBudget:"최소 100,000 이상의 예산을 입력해주세요.",
    abStep1:"과거 ROAS와 CAC 데이터 분석 중...",abStep2:"실시간 채널 리스크와 포화도 평가 중...",abStep3:"예측 LTV 모델 적용 중...",abStep4:"채널별 수확체감 곡선 산출 중...",abStep5:"최적 예산 배분 확정 중...",
    abKpiTotal:"최적화된 총 예산",abKpiRoas:"예상 통합 ROAS",abKpiRevenue:"예상 추가 매출",
    abChartDist:"예산 배분",abChartRoas:"채널별 예상 ROAS",abExpectedRoas:"예상 ROAS",abProjectedCac:"예상 CAC",abCacVsPast:"CAC 변동",
    abOfTotal:"전체 예산 비율",abRationaleTitle:"AI 분석 근거 및 정량화",
    abReasonMetaTitle:"일관된 확장성 및 유사타겟 매칭",abReasonMeta:"Meta는 알고리즘의 우수한 LTV 예측 덕분에 배분됩니다. 수확체감점이 다른 채널보다 높아 더 큰 예산을 흡수하면서도 ROAS를 유지합니다.",
    abReasonGoogleTitle:"높은 구매 의도 포착",abReasonGoogle:"Google Search는 퍼널 하단의 네트 역할을 합니다. 브랜드 키워드와 높은 의도 키워드 전환을 포착하여 높은 전환율을 보장합니다.",
    abReasonTiktokTitle:"바이럴 잠재력 및 낮은 CPM",abReasonTiktok:"TikTok은 저 CPM으로 공격적인 신규 오디언스 확보를 주도합니다. 상위 퍼널 고려도 생성에 필수적입니다.",
    abReasonYoutubeTitle:"브랜드 인지도 및 리마케팅",abReasonYoutube:"브랜드 인지도와 멀티터치 기여도를 지원합니다. 비디오 리마케팅은 전체 캠페인 전환 속도를 증가시킵니다.",
    abReasonNaverTitle:"국내 검색 점유율",abReasonNaver:"한국 시장에서 네이버 검색 광고는 높은 구매 의도 트래픽을 확보하는 핵심 채널입니다.",
    abReasonKakaoTitle:"카카오 생태계 활용",abReasonKakao:"카카오톡 메시지 및 카카오 모먼트를 통해 높은 도달률과 전환율을 달성합니다.",
    abOptTip:"AI 최적화 팁",abOptTipText:"크리에이티브를 14일마다 갱신하여 광고 피로도를 방지하고 예상 CAC를 유지하세요.",
    abBtnDownload:"리포트 다운로드 (PDF)",abBtnApply:"캠페인에 적용 & 전파",
    abGuideTitle:"AI 예산배분 이용 가이드",abGuideSub:"AI가 어떻게 최적 예산을 배분하는지, 결과를 어떻게 활용하는지 안내합니다.",
    abGuideStepsTitle:"AI 예산배분 6단계",
    abGuideStep1Title:"예산 입력",abGuideStep1Desc:"총 마케팅 예산을 입력합니다. 최소 100,000 이상이 필요합니다.",
    abGuideStep2Title:"AI 분석 실행",abGuideStep2Desc:"'AI 플랜 생성' 버튼을 클릭하면 5단계 AI 분석이 시작됩니다.",
    abGuideStep3Title:"결과 KPI 확인",abGuideStep3Desc:"최적화된 예산, 통합 ROAS, 예상 매출을 KPI 카드에서 확인합니다.",
    abGuideStep4Title:"채널별 배분 확인",abGuideStep4Desc:"파이 차트에서 채널별 비율, 바 차트에서 ROAS를 확인합니다.",
    abGuideStep5Title:"AI 근거 검토",abGuideStep5Desc:"각 채널별 AI 배분 근거와 CAC 변동을 상세히 검토합니다.",
    abGuideStep6Title:"캠페인 적용",abGuideStep6Desc:"'캠페인에 적용' 버튼으로 AI 추천을 실제 캠페인에 전파합니다.",
    abGuideTipsTitle:"유용한 팁",
    abGuideTip1:"예산 규모에 따라 AI가 채널 수와 비율을 자동으로 조정합니다.",
    abGuideTip2:"연동허브에서 API 키를 등록하면 해당 채널이 자동으로 배분 대상에 포함됩니다.",
    abGuideTip3:"크리에이티브를 정기적으로 갱신하여 광고 피로도를 방지하세요.",
    abGuideTip4:"CAC 변동이 상승세이면 타겟팅 또는 소재 전략을 재검토하세요.",
    abGuideTip5:"결과는 실시간 동기화되어 예산 플래너와 캠페인 매니저에 즉시 반영됩니다.",
  },
  en: {
    abPageTitle:"AI Marketing Budget Allocator",abPageSub:"Data-driven intelligent budget allocation engine — Maximize ROAS with predictive AI models",
    abBtnGuide:"Guide",abConnectedChannels:"Connected Ad Channels",
    abInputTitle:"Enter Total Marketing Budget",abInputDesc:"Our AI evaluates historical conversion data, cross-channel diminishing returns, and real-time market saturation to recommend the optimal allocation.",abInputPlaceholder:"e.g. 100,000,000",
    abBtnProcessing:"Processing...",abBtnGenerate:"Generate AI Plan",abMinBudget:"Please enter at least 100,000 for total budget.",
    abStep1:"Analyzing historical ROAS and CAC data...",abStep2:"Evaluating channel risk and saturation...",abStep3:"Applying predictive LTV models...",abStep4:"Determining diminishing returns curve...",abStep5:"Finalizing optimal distribution...",
    abKpiTotal:"Total Optimized Budget",abKpiRoas:"Expected Blended ROAS",abKpiRevenue:"Projected Incremental Revenue",
    abChartDist:"Budget Distribution",abChartRoas:"Predicted ROAS per Channel",abExpectedRoas:"Expected ROAS",abProjectedCac:"Projected CAC",abCacVsPast:"CAC vs Past",
    abOfTotal:"of Total Budget",abRationaleTitle:"AI Rationale & Quantification",
    abReasonMetaTitle:"Consistent Scale & Lookalike Matching",abReasonMeta:"Meta is allocated due to its algorithm's superior LTV prediction. The diminishing return point is higher, meaning it absorbs larger budgets while maintaining ROAS.",
    abReasonGoogleTitle:"High Intent Capture",abReasonGoogle:"Google Search acts as a net for the bottom of the funnel, capturing branded and high-intent keyword conversions.",
    abReasonTiktokTitle:"Viral Potential & Lower CPM",abReasonTiktok:"TikTok drives aggressive new audience acquisition at significantly lower CPM, essential for top-of-funnel consideration.",
    abReasonYoutubeTitle:"Brand Awareness & Remarketing",abReasonYoutube:"Ensures strong brand awareness and multi-touch attribution support. Video remarketing increases conversion velocity.",
    abReasonNaverTitle:"Domestic Search Share",abReasonNaver:"Naver Search Ads capture high-intent traffic in the Korean market.",
    abReasonKakaoTitle:"Kakao Ecosystem",abReasonKakao:"Achieves high reach and conversion through KakaoTalk messaging and Kakao Moment.",
    abOptTip:"AI Optimization Tip",abOptTipText:"Refresh creatives every 14 days to avoid ad fatigue and maintain projected CAC.",
    abBtnDownload:"Download Report (PDF)",abBtnApply:"Apply to Campaigns & Broadcast",
    abGuideTitle:"AI Budget Allocator Guide",abGuideSub:"Learn how AI optimizes your budget allocation and how to use the results.",
    abGuideStepsTitle:"6 Steps",
    abGuideStep1Title:"Enter Budget",abGuideStep1Desc:"Enter your total marketing budget (minimum 100,000).",
    abGuideStep2Title:"Run AI Analysis",abGuideStep2Desc:"Click 'Generate AI Plan' to start 5-step AI analysis.",
    abGuideStep3Title:"Review KPIs",abGuideStep3Desc:"Check optimized budget, blended ROAS, and projected revenue.",
    abGuideStep4Title:"Channel Allocation",abGuideStep4Desc:"Review pie chart for ratios and bar chart for ROAS.",
    abGuideStep5Title:"AI Rationale",abGuideStep5Desc:"Review detailed AI reasoning and CAC trends per channel.",
    abGuideStep6Title:"Apply to Campaigns",abGuideStep6Desc:"Click 'Apply' to broadcast AI recommendations to campaigns.",
    abGuideTipsTitle:"Useful Tips",
    abGuideTip1:"AI automatically adjusts channel count and ratios based on budget size.",
    abGuideTip2:"API keys from Integration Hub auto-include channels in allocation.",
    abGuideTip3:"Refresh creatives regularly to prevent ad fatigue.",
    abGuideTip4:"Rising CAC trend means review targeting or creative strategy.",
    abGuideTip5:"Results sync in real-time to Budget Planner and Campaign Manager.",
  },
  ja: {abPageTitle:"AI予算配分エンジン",abPageSub:"データ駆動型AI予算配分",abBtnGuide:"ガイド",abConnectedChannels:"連携チャネル",abInputTitle:"総予算を入力",abInputDesc:"AIが最適配分を推奨",abInputPlaceholder:"例: 100,000,000",abBtnProcessing:"分析中...",abBtnGenerate:"AIプラン生成",abMinBudget:"100,000以上入力してください",abStep1:"ROAS・CACデータ分析中...",abStep2:"チャネルリスク評価中...",abStep3:"LTVモデル適用中...",abStep4:"逓減曲線算出中...",abStep5:"最適配分確定中...",abKpiTotal:"最適化予算",abKpiRoas:"統合ROAS",abKpiRevenue:"予測売上",abChartDist:"予算配分",abChartRoas:"チャネル別ROAS",abExpectedRoas:"予測ROAS",abProjectedCac:"予測CAC",abCacVsPast:"CAC変動",abOfTotal:"全体比率",abRationaleTitle:"AI分析根拠",abReasonMetaTitle:"安定拡張",abReasonMeta:"MetaのLTV予測により配分",abReasonGoogleTitle:"高意図検索",abReasonGoogle:"検索コンバージョン確保",abReasonTiktokTitle:"バイラル・低CPM",abReasonTiktok:"低CPMで新規獲得",abReasonYoutubeTitle:"認知＆リマケ",abReasonYoutube:"ブランド認知と動画リマケ",abReasonNaverTitle:"国内検索",abReasonNaver:"ネイバー検索広告",abReasonKakaoTitle:"カカオ",abReasonKakao:"カカオトーク活用",abOptTip:"最適化ヒント",abOptTipText:"14日ごとにクリエイティブ更新",abBtnDownload:"レポートDL",abBtnApply:"キャンペーンに適用",abGuideTitle:"AI予算配分ガイド",abGuideSub:"AIの配分方法と活用法",abGuideStepsTitle:"6ステップ",abGuideStep1Title:"予算入力",abGuideStep1Desc:"総予算を入力",abGuideStep2Title:"AI分析",abGuideStep2Desc:"分析開始",abGuideStep3Title:"KPI確認",abGuideStep3Desc:"結果を確認",abGuideStep4Title:"配分確認",abGuideStep4Desc:"チャート確認",abGuideStep5Title:"根拠確認",abGuideStep5Desc:"AI根拠を確認",abGuideStep6Title:"適用",abGuideStep6Desc:"キャンペーンに反映",abGuideTipsTitle:"ヒント",abGuideTip1:"予算規模に応じて自動調整",abGuideTip2:"APIキー登録で自動対象化",abGuideTip3:"定期的にクリエイティブ更新",abGuideTip4:"CAC上昇はターゲティング見直し",abGuideTip5:"リアルタイム同期",noData:"データなし"},
  zh: {abPageTitle:"AI预算分配引擎",abPageSub:"数据驱动AI预算分配",abBtnGuide:"指南",abConnectedChannels:"已连接渠道",abInputTitle:"输入总预算",abInputDesc:"AI推荐最优分配",abInputPlaceholder:"例: 100,000,000",abBtnProcessing:"分析中...",abBtnGenerate:"生成AI方案",abMinBudget:"请输入至少100,000",abStep1:"分析ROAS和CAC...",abStep2:"评估渠道风险...",abStep3:"应用LTV模型...",abStep4:"计算递减曲线...",abStep5:"确定最优分配...",abKpiTotal:"优化总预算",abKpiRoas:"综合ROAS",abKpiRevenue:"预测收入",abChartDist:"预算分配",abChartRoas:"渠道ROAS",abExpectedRoas:"预期ROAS",abProjectedCac:"预测CAC",abCacVsPast:"CAC变动",abOfTotal:"总预算占比",abRationaleTitle:"AI分析依据",abReasonMetaTitle:"稳定扩展",abReasonMeta:"Meta LTV预测分配",abReasonGoogleTitle:"高意图搜索",abReasonGoogle:"搜索转化",abReasonTiktokTitle:"病毒传播+低CPM",abReasonTiktok:"低CPM获客",abReasonYoutubeTitle:"品牌+再营销",abReasonYoutube:"品牌认知",abReasonNaverTitle:"本土搜索",abReasonNaver:"Naver搜索",abReasonKakaoTitle:"Kakao生态",abReasonKakao:"KakaoTalk",abOptTip:"优化提示",abOptTipText:"每14天更新素材",abBtnDownload:"下载报告",abBtnApply:"应用到活动",abGuideTitle:"AI预算分配指南",abGuideSub:"AI分配方法",abGuideStepsTitle:"6步骤",abGuideStep1Title:"输入预算",abGuideStep1Desc:"输入总额",abGuideStep2Title:"AI分析",abGuideStep2Desc:"开始分析",abGuideStep3Title:"查看KPI",abGuideStep3Desc:"确认结果",abGuideStep4Title:"分配查看",abGuideStep4Desc:"图表确认",abGuideStep5Title:"依据检查",abGuideStep5Desc:"AI依据",abGuideStep6Title:"应用",abGuideStep6Desc:"反映到活动",abGuideTipsTitle:"技巧",abGuideTip1:"自动调整",abGuideTip2:"API自动纳入",abGuideTip3:"定期更新素材",abGuideTip4:"CAC上升需检查",abGuideTip5:"实时同步",noData:"暂无"},
  "zh-TW": {abPageTitle:"AI預算分配引擎",abPageSub:"數據驅動預算分配",abBtnGuide:"指南",abConnectedChannels:"已連接頻道",abInputTitle:"輸入總預算",abInputDesc:"AI推薦最優分配",abInputPlaceholder:"例: 100,000,000",abBtnProcessing:"分析中...",abBtnGenerate:"生成AI方案",abMinBudget:"請輸入至少100,000",abStep1:"分析ROAS和CAC...",abStep2:"評估風險...",abStep3:"應用LTV...",abStep4:"計算曲線...",abStep5:"確定分配...",abKpiTotal:"優化預算",abKpiRoas:"綜合ROAS",abKpiRevenue:"預測收入",abChartDist:"預算分配",abChartRoas:"頻道ROAS",abExpectedRoas:"預期ROAS",abProjectedCac:"預測CAC",abCacVsPast:"CAC變動",abOfTotal:"總預算占比",abRationaleTitle:"AI分析依據",abReasonMetaTitle:"穩定擴展",abReasonMeta:"Meta分配",abReasonGoogleTitle:"高意圖",abReasonGoogle:"搜索轉化",abReasonTiktokTitle:"低CPM",abReasonTiktok:"新獲客",abReasonYoutubeTitle:"品牌",abReasonYoutube:"認知",abReasonNaverTitle:"本土",abReasonNaver:"Naver",abReasonKakaoTitle:"Kakao",abReasonKakao:"KakaoTalk",abOptTip:"優化提示",abOptTipText:"14天更新素材",abBtnDownload:"下載報告",abBtnApply:"應用",abGuideTitle:"AI預算指南",abGuideSub:"分配方法",abGuideStepsTitle:"6步",abGuideStep1Title:"輸入",abGuideStep1Desc:"輸入預算",abGuideStep2Title:"分析",abGuideStep2Desc:"開始",abGuideStep3Title:"KPI",abGuideStep3Desc:"確認",abGuideStep4Title:"分配",abGuideStep4Desc:"圖表",abGuideStep5Title:"依據",abGuideStep5Desc:"AI依據",abGuideStep6Title:"應用",abGuideStep6Desc:"反映",abGuideTipsTitle:"技巧",abGuideTip1:"自動調整",abGuideTip2:"API自動納入",abGuideTip3:"更新素材",abGuideTip4:"CAC異常檢查",abGuideTip5:"即時同步",noData:"無數據"},
  de: {abPageTitle:"AI-Budgetzuweisung",abPageSub:"Datengesteuerte AI-Zuweisung",abBtnGuide:"Anleitung",abConnectedChannels:"Verbundene Kanäle",abInputTitle:"Gesamtbudget eingeben",abInputDesc:"AI empfiehlt optimale Verteilung",abInputPlaceholder:"z.B. 100.000.000",abBtnProcessing:"Wird analysiert...",abBtnGenerate:"AI-Plan erstellen",abMinBudget:"Mindestens 100.000 erforderlich",abStep1:"ROAS/CAC analysieren...",abStep2:"Kanalrisiko bewerten...",abStep3:"LTV-Modell anwenden...",abStep4:"Grenzerträge berechnen...",abStep5:"Zuweisung finalisieren...",abKpiTotal:"Optimiertes Budget",abKpiRoas:"Gesamt-ROAS",abKpiRevenue:"Progn. Umsatz",abChartDist:"Budgetverteilung",abChartRoas:"ROAS pro Kanal",abExpectedRoas:"Erw. ROAS",abProjectedCac:"Progn. CAC",abCacVsPast:"CAC-Änderung",abOfTotal:"des Gesamtbudgets",abRationaleTitle:"AI-Begründung",abReasonMetaTitle:"Skalierung",abReasonMeta:"Meta-Zuweisung",abReasonGoogleTitle:"Such-Intent",abReasonGoogle:"Suchkonversion",abReasonTiktokTitle:"Viral+CPM",abReasonTiktok:"Neukundengewinnung",abReasonYoutubeTitle:"Marke",abReasonYoutube:"Markenbekanntheit",abReasonNaverTitle:"Lokal",abReasonNaver:"Naver",abReasonKakaoTitle:"Kakao",abReasonKakao:"KakaoTalk",abOptTip:"Optimierungstipp",abOptTipText:"Creatives alle 14 Tage erneuern",abBtnDownload:"Bericht herunterladen",abBtnApply:"Auf Kampagnen anwenden",abGuideTitle:"AI-Budget-Anleitung",abGuideSub:"Budgetverteilungs-Guide",abGuideStepsTitle:"6 Schritte",abGuideStep1Title:"Budget eingeben",abGuideStep1Desc:"Gesamtbudget",abGuideStep2Title:"AI-Analyse",abGuideStep2Desc:"Analyse starten",abGuideStep3Title:"KPIs prüfen",abGuideStep3Desc:"Ergebnisse",abGuideStep4Title:"Verteilung",abGuideStep4Desc:"Diagramme",abGuideStep5Title:"Begründung",abGuideStep5Desc:"AI-Details",abGuideStep6Title:"Anwenden",abGuideStep6Desc:"Kampagnen",abGuideTipsTitle:"Tipps",abGuideTip1:"Automatische Anpassung",abGuideTip2:"API-Kanäle automatisch",abGuideTip3:"Creatives erneuern",abGuideTip4:"CAC-Anstieg prüfen",abGuideTip5:"Echtzeit-Sync",noData:"Keine Daten"},
  th: {abPageTitle:"AI จัดสรรงบ",abPageSub:"จัดสรรงบอัจฉริยะ",abBtnGuide:"คู่มือ",abConnectedChannels:"ช่องทางที่เชื่อมต่อ",abInputTitle:"ใส่งบรวม",abInputDesc:"AI แนะนำการจัดสรร",abInputPlaceholder:"เช่น 100,000,000",abBtnProcessing:"กำลังวิเคราะห์...",abBtnGenerate:"สร้างแผน AI",abMinBudget:"กรุณาใส่อย่างน้อย 100,000",abStep1:"วิเคราะห์ ROAS...",abStep2:"ประเมินความเสี่ยง...",abStep3:"ใช้โมเดล LTV...",abStep4:"คำนวณเส้นโค้ง...",abStep5:"สรุปการจัดสรร...",abKpiTotal:"งบรวม",abKpiRoas:"ROAS รวม",abKpiRevenue:"รายได้คาด",abChartDist:"การจัดสรร",abChartRoas:"ROAS ช่องทาง",abExpectedRoas:"ROAS คาด",abProjectedCac:"CAC คาด",abCacVsPast:"CAC เปลี่ยน",abOfTotal:"ของงบทั้งหมด",abRationaleTitle:"เหตุผล AI",abReasonMetaTitle:"ขยายมั่นคง",abReasonMeta:"Meta",abReasonGoogleTitle:"ค้นหาสูง",abReasonGoogle:"Google",abReasonTiktokTitle:"ไวรัล+CPMต่ำ",abReasonTiktok:"TikTok",abReasonYoutubeTitle:"แบรนด์",abReasonYoutube:"YouTube",abReasonNaverTitle:"ท้องถิ่น",abReasonNaver:"Naver",abReasonKakaoTitle:"Kakao",abReasonKakao:"KakaoTalk",abOptTip:"เทคนิค",abOptTipText:"เปลี่ยนครีเอทีฟทุก 14 วัน",abBtnDownload:"ดาวน์โหลด",abBtnApply:"นำไปใช้",abGuideTitle:"คู่มือ AI",abGuideSub:"การใช้งาน",abGuideStepsTitle:"6 ขั้นตอน",abGuideStep1Title:"ใส่งบ",abGuideStep1Desc:"ใส่จำนวน",abGuideStep2Title:"วิเคราะห์",abGuideStep2Desc:"เริ่ม",abGuideStep3Title:"ดู KPI",abGuideStep3Desc:"ผลลัพธ์",abGuideStep4Title:"จัดสรร",abGuideStep4Desc:"กราฟ",abGuideStep5Title:"เหตุผล",abGuideStep5Desc:"AI",abGuideStep6Title:"นำใช้",abGuideStep6Desc:"แคมเปญ",abGuideTipsTitle:"เทคนิค",abGuideTip1:"ปรับอัตโนมัติ",abGuideTip2:"API อัตโนมัติ",abGuideTip3:"เปลี่ยนครีเอทีฟ",abGuideTip4:"CAC สูงตรวจสอบ",abGuideTip5:"ซิงค์เรียลไทม์",noData:"ไม่มี"},
  vi: {abPageTitle:"AI Phân bổ ngân sách",abPageSub:"Phân bổ thông minh",abBtnGuide:"Hướng dẫn",abConnectedChannels:"Kênh đã kết nối",abInputTitle:"Nhập tổng ngân sách",abInputDesc:"AI đề xuất phân bổ tối ưu",abInputPlaceholder:"VD: 100,000,000",abBtnProcessing:"Đang phân tích...",abBtnGenerate:"Tạo kế hoạch AI",abMinBudget:"Vui lòng nhập ít nhất 100,000",abStep1:"Phân tích ROAS...",abStep2:"Đánh giá rủi ro...",abStep3:"Áp dụng LTV...",abStep4:"Tính đường cong...",abStep5:"Hoàn tất phân bổ...",abKpiTotal:"Ngân sách tối ưu",abKpiRoas:"ROAS tổng",abKpiRevenue:"Doanh thu dự kiến",abChartDist:"Phân bổ",abChartRoas:"ROAS kênh",abExpectedRoas:"ROAS kỳ vọng",abProjectedCac:"CAC dự kiến",abCacVsPast:"CAC thay đổi",abOfTotal:"trong tổng",abRationaleTitle:"Phân tích AI",abReasonMetaTitle:"Mở rộng ổn định",abReasonMeta:"Meta",abReasonGoogleTitle:"Tìm kiếm cao",abReasonGoogle:"Google",abReasonTiktokTitle:"Viral+CPM thấp",abReasonTiktok:"TikTok",abReasonYoutubeTitle:"Thương hiệu",abReasonYoutube:"YouTube",abReasonNaverTitle:"Tìm kiếm nội địa",abReasonNaver:"Naver",abReasonKakaoTitle:"Kakao",abReasonKakao:"KakaoTalk",abOptTip:"Mẹo AI",abOptTipText:"Đổi mới quảng cáo mỗi 14 ngày",abBtnDownload:"Tải báo cáo",abBtnApply:"Áp dụng",abGuideTitle:"Hướng dẫn AI",abGuideSub:"Cách phân bổ",abGuideStepsTitle:"6 bước",abGuideStep1Title:"Nhập ngân sách",abGuideStep1Desc:"Nhập tổng",abGuideStep2Title:"Phân tích",abGuideStep2Desc:"Bắt đầu",abGuideStep3Title:"Xem KPI",abGuideStep3Desc:"Kết quả",abGuideStep4Title:"Phân bổ",abGuideStep4Desc:"Biểu đồ",abGuideStep5Title:"Lý do",abGuideStep5Desc:"AI",abGuideStep6Title:"Áp dụng",abGuideStep6Desc:"Chiến dịch",abGuideTipsTitle:"Mẹo",abGuideTip1:"Tự động điều chỉnh",abGuideTip2:"API tự động",abGuideTip3:"Đổi mới quảng cáo",abGuideTip4:"CAC tăng xem lại",abGuideTip5:"Đồng bộ real-time",noData:"Không có"},
  id: {abPageTitle:"AI Alokasi Anggaran",abPageSub:"Alokasi cerdas",abBtnGuide:"Panduan",abConnectedChannels:"Saluran Terhubung",abInputTitle:"Masukkan Total Anggaran",abInputDesc:"AI merekomendasikan alokasi optimal",abInputPlaceholder:"Contoh: 100.000.000",abBtnProcessing:"Menganalisis...",abBtnGenerate:"Buat Rencana AI",abMinBudget:"Masukkan minimal 100.000",abStep1:"Analisis ROAS...",abStep2:"Evaluasi risiko...",abStep3:"Terapkan LTV...",abStep4:"Hitung kurva...",abStep5:"Finalisasi alokasi...",abKpiTotal:"Total Optimal",abKpiRoas:"ROAS Total",abKpiRevenue:"Pendapatan",abChartDist:"Distribusi",abChartRoas:"ROAS Saluran",abExpectedRoas:"ROAS Harapan",abProjectedCac:"CAC Proyeksi",abCacVsPast:"Perubahan CAC",abOfTotal:"dari total",abRationaleTitle:"Analisis AI",abReasonMetaTitle:"Skalabilitas",abReasonMeta:"Meta",abReasonGoogleTitle:"Intent Tinggi",abReasonGoogle:"Google",abReasonTiktokTitle:"Viral+CPM Rendah",abReasonTiktok:"TikTok",abReasonYoutubeTitle:"Brand",abReasonYoutube:"YouTube",abReasonNaverTitle:"Lokal",abReasonNaver:"Naver",abReasonKakaoTitle:"Kakao",abReasonKakao:"KakaoTalk",abOptTip:"Tips AI",abOptTipText:"Perbarui kreatif setiap 14 hari",abBtnDownload:"Unduh Laporan",abBtnApply:"Terapkan",abGuideTitle:"Panduan AI",abGuideSub:"Cara alokasi",abGuideStepsTitle:"6 Langkah",abGuideStep1Title:"Input anggaran",abGuideStep1Desc:"Masukkan total",abGuideStep2Title:"Analisis",abGuideStep2Desc:"Mulai",abGuideStep3Title:"Lihat KPI",abGuideStep3Desc:"Hasil",abGuideStep4Title:"Alokasi",abGuideStep4Desc:"Grafik",abGuideStep5Title:"Alasan",abGuideStep5Desc:"AI",abGuideStep6Title:"Terapkan",abGuideStep6Desc:"Kampanye",abGuideTipsTitle:"Tips",abGuideTip1:"Penyesuaian otomatis",abGuideTip2:"API otomatis",abGuideTip3:"Perbarui kreatif",abGuideTip4:"CAC naik periksa",abGuideTip5:"Sinkronisasi real-time",noData:"Tidak ada"},
};

LANGS.forEach(lang => {
  const fp = path.join(DIR, `${lang}.js`);
  if (!fs.existsSync(fp)) return;
  const raw = fs.readFileSync(fp, 'utf8');
  const obj = JSON.parse(raw.replace(/^export\s+default\s+/, '').replace(/;\s*$/, ''));
  if (!obj.marketing) obj.marketing = {};
  const k = keys[lang] || keys.en;
  Object.assign(obj.marketing, k);
  fs.writeFileSync(fp, 'export default ' + JSON.stringify(obj) + ';', 'utf8');
  console.log(`✅ [${lang}] AI budget: ${Object.keys(k).length} keys`);
});
console.log('\n🎉 AI Budget Allocator i18n complete!');
