const fs=require('fs'),p=require('path');
const dir=p.resolve(__dirname,'src/i18n/locales');
const D={
ru:{dash:{achvRate:'Достижение',activeCh:'Активные каналы',adRev:'Рекламный доход',adSpend:'Рекламные расходы',ageDist:'Распределение по возрасту',aiAdAnal:'🤖 ИИ-анализ рекламы',allChSummary:'Сводка по каналам',avgCtr:'Средний CTR',avgDuration:'Средняя длительность',avgRoas:'Общий ROAS',avgViewTime:'Среднее время просмотра',blendedRoas:'Общий ROAS',bounceRate:'Показатель отказов',cartAdds:'Добавления в корзину',channelMix:'Микс доходов',channelPerf:'📊 Эффективность',chCount:'Активные каналы',chDetailTable:'Таблица каналов',chIntelTitle:'Аналитика каналов',chName:'Канал',chPerfSumm:'Сводка эффективности',chRoas:'ROAS по каналам',chTrend:'Тренд каналов',clickChannelHint:'Нажмите карточку → 5-секционный анализ',clicks:'Клики',connectChannels:'Подключите рекламные каналы',conv2:'4. Конверсия',convCount:'Конверсии',convFunnel:'Воронка конверсии',convRate:'Коэфф. конверсии',dismiss:'Отклонить',engagement2:'2. Вовлечённость',fiveSectionAnalysis:'5-секционный анализ',frequency:'Частота',genderDist:'Пол/Возраст',grossMargin:'Валовая маржа',impressions:'Показы',liveActivity:'Активность',netProfit:'Чистая прибыль',noChannelData:'Нет данных каналов',noTrendData:'Нет данных тренда',orders:'Заказы',purchaseCount:'Покупки',reach:'Охват',reachAwareness:'1. Охват',realTimeBlendedRoas:'ROAS в реальном времени',regDist:'Региональное распределение',rev:'Доход',revRoi2:'5. Доход & ROI',securityAlert:'Предупреждение безопасности',sessions:'Сессии',signups:'Регистрации',spendDistribution:'Распределение расходов',threatsDetected:'угрозы обнаружены',totalClicks:'Всего кликов',totalRev:'Общий доход',totalSpend:'Общие расходы',traffic2:'3. Трафик',videoViews:'Просмотры видео',vsYesterday:'vs Вчера'},dashboard:{adSpend:'Рекламные расходы',avgOrder:'AOV',convRateLbl:'Коэфф. конверсии',grossRevenue:'Общий доход',netROAS:'Чистый ROAS',totalOrders:'Всего заказов'},dashPeriod:{today:'Сегодня','7d':'7 дней','14d':'14 дней','30d':'30 дней','90d':'90 дней',custom:'Пользовательский',customRange:'Пользовательский диапазон',startDate:'Начало',endDate:'Конец',apply:'Применить'}},
hi:{dash:{achvRate:'उपलब्धि',activeCh:'सक्रिय चैनल',adRev:'विज्ञापन राजस्व',adSpend:'विज्ञापन खर्च',ageDist:'आयु वितरण',aiAdAnal:'🤖 AI विज्ञापन विश्लेषण',allChSummary:'सभी चैनल सारांश',avgCtr:'औसत CTR',avgDuration:'औसत अवधि',avgRoas:'मिश्रित ROAS',avgViewTime:'औसत देखने का समय',blendedRoas:'मिश्रित ROAS',bounceRate:'बाउंस दर',cartAdds:'कार्ट में जोड़ें',channelMix:'चैनल मिक्स',channelPerf:'📊 प्रदर्शन',chCount:'सक्रिय चैनल',chDetailTable:'चैनल विवरण',chIntelTitle:'चैनल इंटेलिजेंस',chName:'चैनल',chPerfSumm:'प्रदर्शन सारांश',chRoas:'चैनल-वार ROAS',chTrend:'चैनल ट्रेंड',clickChannelHint:'कार्ड क्लिक करें → 5-सेक्शन विश्लेषण',clicks:'क्लिक',connectChannels:'विज्ञापन चैनल कनेक्ट करें',conv2:'4. रूपांतरण',convCount:'रूपांतरण',convFunnel:'रूपांतरण फ़नल',convRate:'रूपांतरण दर',dismiss:'खारिज करें',engagement2:'2. सहभागिता',fiveSectionAnalysis:'5-सेक्शन विश्लेषण',frequency:'आवृत्ति',genderDist:'लिंग/आयु वितरण',grossMargin:'सकल मार्जिन',impressions:'इंप्रेशन',liveActivity:'लाइव गतिविधि',netProfit:'शुद्ध लाभ',noChannelData:'कोई चैनल डेटा नहीं',noTrendData:'कोई ट्रेंड डेटा नहीं',orders:'ऑर्डर',purchaseCount:'खरीद',reach:'पहुंच',reachAwareness:'1. पहुंच',realTimeBlendedRoas:'रियल-टाइम ROAS',regDist:'क्षेत्रीय वितरण',rev:'राजस्व',revRoi2:'5. राजस्व & ROI',securityAlert:'सुरक्षा चेतावनी',sessions:'सत्र',signups:'पंजीकरण',spendDistribution:'खर्च वितरण',threatsDetected:'खतरे पाए गए',totalClicks:'कुल क्लिक',totalRev:'कुल राजस्व',totalSpend:'कुल खर्च',traffic2:'3. ट्रैफ़िक',videoViews:'वीडियो दृश्य',vsYesterday:'कल की तुलना'},dashboard:{adSpend:'विज्ञापन खर्च',avgOrder:'AOV',convRateLbl:'रूपांतरण दर',grossRevenue:'कुल राजस्व',netROAS:'शुद्ध ROAS',totalOrders:'कुल ऑर्डर'},dashPeriod:{today:'आज','7d':'7 दिन','14d':'14 दिन','30d':'30 दिन','90d':'90 दिन',custom:'कस्टम',customRange:'कस्टम रेंज',startDate:'प्रारंभ तिथि',endDate:'अंतिम तिथि',apply:'लागू करें'}},
'zh-TW':{dash:{achvRate:'達成率',activeCh:'活躍頻道',adRev:'廣告收入',adSpend:'廣告支出',ageDist:'年齡分佈',aiAdAnal:'🤖 AI廣告分析',allChSummary:'全頻道摘要',avgCtr:'平均CTR',avgDuration:'平均時長',avgRoas:'綜合ROAS',avgViewTime:'平均觀看時間',blendedRoas:'綜合ROAS',bounceRate:'跳出率',cartAdds:'加入購物車',channelMix:'頻道收入組合',channelPerf:'📊 頻道績效',chCount:'活躍頻道',chDetailTable:'頻道明細表',chIntelTitle:'頻道情報',chName:'頻道',chPerfSumm:'頻道績效摘要',chRoas:'各頻道ROAS',chTrend:'頻道趨勢',clickChannelHint:'點擊卡片→5區分析',clicks:'點擊',connectChannels:'連接廣告頻道',conv2:'4. 轉換',convCount:'轉換數',convFunnel:'轉換漏斗',convRate:'轉換率',dismiss:'關閉',engagement2:'2. 互動',fiveSectionAnalysis:'5區分析',frequency:'頻次',genderDist:'性別/年齡分佈',grossMargin:'毛利率',impressions:'曝光',liveActivity:'即時活動',netProfit:'淨利潤',noChannelData:'暫無頻道資料',noTrendData:'暫無趨勢資料',orders:'訂單',purchaseCount:'購買數',reach:'觸及',reachAwareness:'1. 觸及與認知',realTimeBlendedRoas:'即時ROAS',regDist:'地區分佈',rev:'收入',revRoi2:'5. 收入與ROI',securityAlert:'安全警報',sessions:'工作階段',signups:'註冊',spendDistribution:'支出分佈',threatsDetected:'偵測到威脅',totalClicks:'總點擊',totalRev:'總收入',totalSpend:'總支出',traffic2:'3. 流量',videoViews:'影片觀看',vsYesterday:'較昨日'},dashboard:{adSpend:'廣告支出',avgOrder:'AOV',convRateLbl:'轉換率',grossRevenue:'總收入',netROAS:'淨ROAS',totalOrders:'總訂單'},dashPeriod:{today:'今天','7d':'7天','14d':'14天','30d':'30天','90d':'90天',custom:'自訂',customRange:'自訂範圍',startDate:'開始日期',endDate:'結束日期',apply:'套用'}},
ja:{dash:{achvRate:'達成率',activeCh:'アクティブチャネル',adRev:'広告収益',adSpend:'広告費',ageDist:'年齢分布',aiAdAnal:'🤖 AI広告分析',allChSummary:'全チャネルサマリー',avgCtr:'平均CTR',avgDuration:'平均滞在時間',avgRoas:'統合ROAS',avgViewTime:'平均視聴時間',blendedRoas:'統合ROAS',bounceRate:'直帰率',cartAdds:'カート追加',channelMix:'チャネル売上ミックス',channelPerf:'📊 チャネル成果',chCount:'アクティブチャネル',chDetailTable:'チャネル詳細テーブル',chIntelTitle:'チャネルインテリジェンス',chName:'チャネル',chPerfSumm:'チャネルパフォーマンスサマリー',chRoas:'チャネル別ROAS',chTrend:'チャネルトレンド',clickChannelHint:'チャネルカードクリック→5セクション分析',clicks:'クリック',connectChannels:'広告チャネルを接続',conv2:'4. コンバージョン',convCount:'コンバージョン数',convFunnel:'コンバージョンファネル',convRate:'コンバージョン率',dismiss:'無視',engagement2:'2. エンゲージメント',fiveSectionAnalysis:'5セクション分析',frequency:'フリークエンシー',genderDist:'性別・年齢分布',grossMargin:'粗利益率',impressions:'インプレッション',liveActivity:'リアルタイム活動',netProfit:'純利益',noChannelData:'チャネルデータなし',noTrendData:'トレンドデータなし',orders:'注文数',purchaseCount:'購入数',reach:'リーチ',reachAwareness:'1. リーチ＆認知',realTimeBlendedRoas:'リアルタイム統合ROAS',regDist:'地域分布',rev:'売上',revRoi2:'5. 売上＆ROI',securityAlert:'セキュリティ警告',sessions:'セッション',signups:'登録数',spendDistribution:'広告費配分',threatsDetected:'脅威検出',totalClicks:'総クリック数',totalRev:'総売上',totalSpend:'総広告費',traffic2:'3. トラフィック',videoViews:'動画再生',vsYesterday:'前日比'},dashboard:{adSpend:'広告費',avgOrder:'AOV',convRateLbl:'コンバージョン率',grossRevenue:'総売上',netROAS:'純ROAS',totalOrders:'総注文数'},dashPeriod:{today:'今日','7d':'7日','14d':'14日','30d':'30日','90d':'90日',custom:'カスタム',customRange:'期間指定',startDate:'開始日',endDate:'終了日',apply:'適用'}},
th:{dash:{achvRate:'ความสำเร็จ',activeCh:'ช่องทางที่ใช้งาน',adRev:'รายได้โฆษณา',adSpend:'ค่าโฆษณา',aiAdAnal:'🤖 วิเคราะห์โฆษณา AI',allChSummary:'สรุปทุกช่องทาง',avgCtr:'CTR เฉลี่ย',avgDuration:'ระยะเวลาเฉลี่ย',blendedRoas:'ROAS รวม',bounceRate:'อัตราตีกลับ',channelPerf:'📊 ผลงาน',chCount:'ช่องทางที่ใช้งาน',chName:'ช่องทาง',chPerfSumm:'สรุปผลช่องทาง',chTrend:'แนวโน้มช่องทาง',clicks:'คลิก',connectChannels:'เชื่อมต่อช่องทางโฆษณา',convCount:'การแปลง',convRate:'อัตราการแปลง',fiveSectionAnalysis:'วิเคราะห์ 5 ส่วน',impressions:'การแสดงผล',liveActivity:'กิจกรรมสด',netProfit:'กำไรสุทธิ',noChannelData:'ไม่มีข้อมูลช่องทาง',noTrendData:'ไม่มีข้อมูลแนวโน้ม',orders:'คำสั่งซื้อ',reach:'การเข้าถึง',rev:'รายได้',securityAlert:'แจ้งเตือนความปลอดภัย',sessions:'เซสชัน',totalClicks:'คลิกทั้งหมด',totalRev:'รายได้รวม',totalSpend:'ค่าใช้จ่ายรวม',vsYesterday:'เทียบกับเมื่อวาน'},dashboard:{adSpend:'ค่าโฆษณา',avgOrder:'AOV',convRateLbl:'อัตราการแปลง',grossRevenue:'รายได้รวม',netROAS:'ROAS สุทธิ',totalOrders:'คำสั่งซื้อทั้งหมด'},dashPeriod:{today:'วันนี้','7d':'7 วัน','14d':'14 วัน','30d':'30 วัน','90d':'90 วัน',custom:'กำหนดเอง',customRange:'ช่วงเวลาที่กำหนด',startDate:'วันเริ่มต้น',endDate:'วันสิ้นสุด',apply:'ใช้งาน'}},
vi:{dash:{achvRate:'Đạt được',activeCh:'Kênh hoạt động',adRev:'Doanh thu quảng cáo',adSpend:'Chi phí quảng cáo',aiAdAnal:'🤖 Phân tích quảng cáo AI',allChSummary:'Tổng hợp các kênh',avgCtr:'CTR trung bình',avgDuration:'Thời lượng TB',blendedRoas:'ROAS tổng hợp',bounceRate:'Tỷ lệ thoát',channelPerf:'📊 Hiệu suất',chCount:'Kênh hoạt động',chName:'Kênh',chPerfSumm:'Tóm tắt hiệu suất',chTrend:'Xu hướng kênh',clicks:'Nhấp',connectChannels:'Kết nối kênh quảng cáo',convCount:'Chuyển đổi',convRate:'Tỷ lệ chuyển đổi',fiveSectionAnalysis:'Phân tích 5 phần',impressions:'Lượt hiển thị',liveActivity:'Hoạt động trực tiếp',netProfit:'Lợi nhuận ròng',noChannelData:'Không có dữ liệu kênh',noTrendData:'Không có dữ liệu xu hướng',orders:'Đơn hàng',reach:'Tiếp cận',rev:'Doanh thu',securityAlert:'Cảnh báo bảo mật',sessions:'Phiên',totalClicks:'Tổng nhấp',totalRev:'Tổng doanh thu',totalSpend:'Tổng chi tiêu',vsYesterday:'so với hôm qua'},dashboard:{adSpend:'Chi phí quảng cáo',avgOrder:'AOV',convRateLbl:'Tỷ lệ chuyển đổi',grossRevenue:'Tổng doanh thu',netROAS:'ROAS ròng',totalOrders:'Tổng đơn hàng'},dashPeriod:{today:'Hôm nay','7d':'7 ngày','14d':'14 ngày','30d':'30 ngày','90d':'90 ngày',custom:'Tùy chỉnh',customRange:'Khoảng tùy chỉnh',startDate:'Ngày bắt đầu',endDate:'Ngày kết thúc',apply:'Áp dụng'}},
id:{dash:{achvRate:'Pencapaian',activeCh:'Saluran Aktif',adRev:'Pendapatan Iklan',adSpend:'Belanja Iklan',aiAdAnal:'🤖 Analisis Iklan AI',allChSummary:'Ringkasan Semua Saluran',avgCtr:'CTR Rata-rata',avgDuration:'Durasi Rata-rata',blendedRoas:'ROAS Gabungan',bounceRate:'Rasio Pentalan',channelPerf:'📊 Kinerja',chCount:'Saluran Aktif',chName:'Saluran',chPerfSumm:'Ringkasan Kinerja',chTrend:'Tren Saluran',clicks:'Klik',connectChannels:'Hubungkan saluran iklan',convCount:'Konversi',convRate:'Rasio Konversi',fiveSectionAnalysis:'Analisis 5 Bagian',impressions:'Tayangan',liveActivity:'Aktivitas Langsung',netProfit:'Laba Bersih',noChannelData:'Tidak ada data saluran',noTrendData:'Tidak ada data tren',orders:'Pesanan',reach:'Jangkauan',rev:'Pendapatan',securityAlert:'Peringatan Keamanan',sessions:'Sesi',totalClicks:'Total Klik',totalRev:'Total Pendapatan',totalSpend:'Total Pengeluaran',vsYesterday:'vs Kemarin'},dashboard:{adSpend:'Belanja Iklan',avgOrder:'AOV',convRateLbl:'Rasio Konversi',grossRevenue:'Total Pendapatan',netROAS:'ROAS Bersih',totalOrders:'Total Pesanan'},dashPeriod:{today:'Hari ini','7d':'7 Hari','14d':'14 Hari','30d':'30 Hari','90d':'90 Hari',custom:'Kustom',customRange:'Rentang Kustom',startDate:'Tanggal Mulai',endDate:'Tanggal Akhir',apply:'Terapkan'}},
};
function inject(lang,data){
  const fp=p.join(dir,lang+'.js');
  if(!fs.existsSync(fp))return;
  let src=fs.readFileSync(fp,'utf8'),count=0;
  for(const[ns,keys]of Object.entries(data)){
    const nsIdx=src.indexOf(`"${ns}"`);
    if(nsIdx<0){const ei=src.lastIndexOf('export default');if(ei>0){src=src.slice(0,ei)+`"${ns}":${JSON.stringify(keys,null,2)},\n`+src.slice(ei);count+=Object.keys(keys).length;}continue;}
    for(const[k,v]of Object.entries(keys)){
      const block=src.substring(nsIdx,Math.min(src.length,nsIdx+15000));
      const m=block.match(new RegExp(`"${k}"\\s*:\\s*"([^"]*)"`));
      if(m){const old=m[0],nw=`"${k}": ${JSON.stringify(v)}`;const pos=src.indexOf(old,nsIdx);if(pos>=0&&m[1]!==v){src=src.substring(0,pos)+nw+src.substring(pos+old.length);count++;}}
      else{const bi=src.indexOf('{',nsIdx);if(bi>0){src=src.substring(0,bi+1)+`\n    "${k}": ${JSON.stringify(v)},`+src.substring(bi+1);count++;}}
    }
  }
  fs.writeFileSync(fp,src,'utf8');
  console.log(`✅ ${lang}: ${count} keys`);
}
for(const[l,d]of Object.entries(D))inject(l,d);
console.log('Done!');
