const fs=require('fs'),vm=require('vm');
const dir='src/i18n/locales';
const langs=fs.readdirSync(dir).filter(f=>f.endsWith('.js')&&f!=='ko.js');

const inject={
dashGuide:{title:"Dashboard Usage Guide",desc:"Learn all Dashboard features step by step.",badgeBeginner:"Beginner Guide",badgeTime:"5 min read",badgeLang:"15 Languages",whereStart:"Where do I start?",step1:"Click \"Dashboard\" from the left menu.",step2:"Check overview KPIs.",step3:"Click sub-tabs for detailed analysis.",step4:"Review security banner.",stepsTitle:"Getting Started — 6 Steps",step1Title:"Select Tab",step1Desc:"Choose an analysis category from the tab bar.",step2Title:"Check KPI Cards",step2Desc:"Review key metrics in the KPI cards.",step3Title:"Analyze Charts",step3Desc:"Use trend charts and channel graphs.",step4Title:"Use Date Filter",step4Desc:"Change date range to analyze specific periods.",step5Title:"Export Data",step5Desc:"Download data as Excel.",step6Title:"Check Alerts",step6Desc:"Review latest alerts in the activity feed."},
marketing:{guideTitle:"Auto Marketing Guide",guideSub:"AI-powered marketing automation platform guide.",guideStepsTitle:"Getting Started — 6 Steps",guideStep1Title:"Set Budget",guideStep1Desc:"Set monthly ad budget and channel allocation.",guideStep2Title:"Create Campaign",guideStep2Desc:"Create AI-optimized campaigns.",guideStep3Title:"Set Targeting",guideStep3Desc:"Configure precision targeting with AI segments.",guideStep4Title:"Create Assets",guideStep4Desc:"Auto-generate ad creatives with AI tools.",guideStep5Title:"Monitor Performance",guideStep5Desc:"Track campaign performance in real-time.",guideStep6Title:"Optimize",guideStep6Desc:"Auto-optimize budget and bids with AI.",guideTabsTitle:"Tab Features",guideTipsTitle:"Tips",guideTip1:"Review budget weekly to maximize efficiency.",guideTip2:"Use A/B testing to find best creatives.",guideTip3:"Leverage AI-recommended segments.",guideTip4:"Check performance reports regularly.",guideTip5:"Plan seasonal campaigns ahead.",guideStartBtn:"Get Started",autoTab1:"① Campaign Setup",autoTab2:"③ Campaign Config",autoTab3:"③ AI Strategy Preview",autoTab4:"Usage Guide"},
campMgr:{guideTitle:"Campaign Manager Guide",guideSub:"AI marketing campaign creation, execution & analysis guide.",guideStepsTitle:"Getting Started — 6 Steps",guideStep1Title:"Create Campaign",guideStep1Desc:"Click New Campaign button.",guideStep2Title:"Set Goals",guideStep2Desc:"Set campaign KPI targets.",guideStep3Title:"Allocate Budget",guideStep3Desc:"Distribute budget by channel.",guideStep4Title:"Set Schedule",guideStep4Desc:"Set start and end dates.",guideStep5Title:"Analyze Results",guideStep5Desc:"Monitor campaign performance in real-time.",guideStep6Title:"A/B Test",guideStep6Desc:"Test variables to find optimal strategy.",guideTabsTitle:"Tab Features",guideTipsTitle:"Tips",tabGuide:"Usage Guide"},
jb:{guideTitle:"Journey Builder Guide",guideSub:"AI-powered customer journey design & analysis guide.",guideStepsTitle:"Getting Started — 6 Steps",guideStep1Title:"Create Journey",guideStep1Desc:"Create a new customer journey scenario.",guideStep2Title:"Set Triggers",guideStep2Desc:"Configure journey trigger events.",guideStep3Title:"Add Steps",guideStep3Desc:"Add email, SMS, push action steps.",guideStep4Title:"Set Conditions",guideStep4Desc:"Configure branching conditions.",guideStep5Title:"Test Run",guideStep5Desc:"Validate journey flow with simulation.",guideStep6Title:"Analyze",guideStep6Desc:"Analyze conversion rates by journey.",guideTabsTitle:"Tab Features",guideTipsTitle:"Tips",tabGuide:"Usage Guide"},
adPerf:{tabAdStatus:"Ad Status",tabCreative:"Creative",tabCompare:"Compare",tabAiDesign:"AI Design",tabGuide:"Guide",guideTitle:"Ad Performance Guide",guideSub:"AI-powered unified ad performance analysis guide.",guideStepsTitle:"Getting Started — 6 Steps",guideStep1Title:"Set Period",guideStep1Desc:"Set analysis date range.",guideStep2Title:"Check KPIs",guideStep2Desc:"Review spend, impressions, clicks, CTR, ROAS.",guideStep3Title:"Compare Channels",guideStep3Desc:"Compare channel performance.",guideStep4Title:"Analyze Creatives",guideStep4Desc:"Analyze asset performance.",guideStep5Title:"AI Recommendations",guideStep5Desc:"Review AI optimization suggestions.",guideStep6Title:"Generate Report",guideStep6Desc:"Export analysis results as report.",guideTabsTitle:"Tab Features",guideTipsTitle:"Tips"},
acctPerf:{tabDashboard:"Visual Dashboard",tabDrilldown:"Tree Analysis",tabGuide:"Guide",guideTitle:"Account Performance Guide",guideSub:"Team/Account Budget Dashboard & Meta Ads Hierarchy guide.",guideWhereToStart:"Where do I start?",guideWhereToStartDesc:"Select Account Performance from the left menu.",guideStepsTitle:"Getting Started — 6 Steps",guideStep1Title:"Access Dashboard",guideStep1Desc:"Navigate to Account Performance.",guideStep2Title:"Set Period",guideStep2Desc:"Set analysis date range.",guideStep3Title:"Check Budget",guideStep3Desc:"Review team/account budget status.",guideStep4Title:"Drill Down",guideStep4Desc:"Analyze ad hierarchy with tree structure.",guideStep5Title:"Compare",guideStep5Desc:"Compare performance by period.",guideStep6Title:"Export",guideStep6Desc:"Export data to Excel.",guideTabsTitle:"Tab Features",guideTabDashboardName:"Visual Dashboard",guideTabDashboardDesc:"Visualize overall budget and performance.",guideTabDrilldownName:"Tree Analysis",guideTabDrilldownDesc:"Detailed analysis by ad hierarchy.",guideTipsTitle:"Tips",guideTip1:"Check burn rate weekly.",guideTip2:"Adjust underperforming campaigns.",guideTip3:"Use hierarchy analysis to find issues.",guideFaqTitle:"FAQ",guideFaq1Q:"No data showing.",guideFaq1A:"Check Meta Ads account connection.",guideFaq2Q:"Can't set dates.",guideFaq2A:"Ensure start date is before end date.",guideReadyTitle:"Ready to start?",guideReadyDesc:"Select Account Performance from the left menu."},
channelKpiPage:{tabGoals:"KPI Goals",tabRoles:"Roles",tabSetup:"Setup",tabSns:"SNS",tabContent:"Content",tabCommunity:"Community",tabTargets:"Targets",tabMonitor:"Monitor",tabGuide:"Guide",guideTitle:"Channel KPI Guide",guideSub:"Advanced channel KPI management guide.",guideStepsTitle:"Getting Started",guideTabsTitle:"Tab Features",guideTipsTitle:"Tips",guideTip1:"Set KPI goals quarterly.",guideTip2:"Assign channel roles clearly.",guideTip3:"Weekly monitoring for early detection.",guideTip4:"Link content performance with KPIs.",guideTip5:"Check community engagement regularly."},
crm:{tabCust:"Customers",tabAiSeg:"AI Segments",tabManSeg:"Manual Segments",tabRfm:"RFM Analysis",tabGuide:"Guide",guideTitle:"CRM Guide",guideSub:"Customer data, AI segmentation & RFM analysis guide.",guideStepsTitle:"Getting Started",guideTabsTitle:"Tab Features",guideTipsTitle:"Tips",guideTip1:"Update customer data regularly.",guideTip2:"Use AI segments for precision targeting.",guideTip3:"Identify VIP customers with RFM.",guideTip4:"Run retention campaigns for at-risk customers.",guideTip5:"Provide personalized offers per segment."},
omniChannel:{tabChannels:"Channels",tabProducts:"Products",tabOrders:"Orders",tabInventory:"Inventory",tabOverview:"Overview",tabGuide:"Guide",tabChannelsDesc:"Channel management",tabProductsDesc:"Product management",tabOrdersDesc:"Order management",tabInventoryDesc:"Inventory sync",tabOverviewDesc:"Overview dashboard",tabGuideDesc:"Usage guide",guideTitle:"Omni-Channel Guide",guideSub:"Multi-channel unified management guide.",guideStepsTitle:"Getting Started",guideTabsTitle:"Tab Features",guideTipsTitle:"Tips",guideStep:"Step",guideTip:"Tip",guideDashName:"Overview",guideDashDesc:"View all channel status.",guideFeedName:"Product Feed",guideFeedDesc:"Manage product feeds.",guideTrendName:"Trends",guideTrendDesc:"Analyze sales trends.",guideSettingsName:"Settings",guideSettingsDesc:"Manage channel settings.",guideGuideName:"Guide",guideGuideDesc:"View detailed guide."},
attrData:{tabMtaLabel:"MTA",tabMtaDesc:"Multi-Touch Attribution",tabShapleyLabel:"Shapley",tabShapleyDesc:"Shapley contribution",tabMmmLabel:"MMM",tabMmmDesc:"Marketing Mix Modeling",tabMarkovLabel:"Markov",tabMarkovDesc:"Markov Chain",tabAbLabel:"A/B Test",tabAbDesc:"A/B Testing",tabCohortLabel:"Cohort",tabCohortDesc:"Cohort Analysis",tabLtvLabel:"LTV",tabLtvDesc:"Customer Lifetime Value",tabAnomalyLabel:"Anomaly",tabAnomalyDesc:"Anomaly Detection",tabCompareLabel:"Compare",tabCompareDesc:"Model Comparison",tabGuideLabel:"Guide",tabGuideDesc:"Usage Guide",modelCompareTable:"Model Comparison",guideTitle:"Attribution Guide",guideSub:"Channel contribution analysis with various attribution models.",guideBeginnerBadge:"Beginner",guideTimeBadge:"5 min",guideLangBadge:"15 Languages",guideWhereToStart:"Where to start?",guideWhereToStartDesc:"Select Attribution from the left menu.",guideStepsTitle:"Getting Started",guideTabsTitle:"Tab Features",guideTipsTitle:"Tips",guideTip1:"Cross-validate with MTA and MMM.",guideTip2:"Use Shapley for fair contribution.",guideTip3:"Understand patterns with Cohort.",guideTip4:"Manage data quality with Anomaly.",guideTip5:"Select optimal model with Compare.",guideFaqTitle:"FAQ",guideFaq1Q:"Which model?",guideFaq1A:"MTA for few channels, MMM for many.",guideFaq2Q:"Not enough data.",guideFaq2A:"Need at least 30 days of data.",guideReadyTitle:"Ready?",guideReadyDesc:"Select Attribution from the menu."},
budgetTracker:{tabOverview:"Overview",tabAllocation:"Allocation",tabBurnRate:"Burn Rate",tabAlerts:"Alerts",tabGuide:"Guide",guideTitle:"Budget Tracker Guide",guideSub:"Real-time ad budget tracking guide."},
catalogSync:{tabCatalog:"Catalog",tabSyncRun:"Sync Run",tabCategoryMapping:"Category Map",tabStockPolicy:"Stock Policy",tabHistory:"History",tabGuide:"Guide",tabPriceRules:"Price Rules",guideTitle:"Catalog Sync Guide",guideOverviewDesc:"Multi-channel catalog sync guide.",guideStepsTitle:"Steps",guideTabsTitle:"Tabs",guideTipsTitle:"Tips",selectChannelStep:"Select Channel",setPriceStep:"Set Price",approveRegisterStep:"Approve & Register",guideStep:"Step",guideTip:"Tip",guideTips:"Tips"},
orderHub:{tabOverview:"Overview",tabOrders:"Orders",tabClaims:"Claims",tabDelivery:"Delivery",tabSettlement:"Settlement",tabIntl:"International",tabB2B:"B2B",tabSettings:"Settings",tabRouting:"Routing",tabGuide:"Guide",guideTitle:"Order Hub Guide",guideSub:"Unified order management guide.",guideTipsTitle:"Tips",guideStep:"Step",guideTip:"Tip",intlShipGuide:"International Shipping Guide"},
webPopup:{guideTitle:"Web Popup Guide",guideSub:"Web popup marketing tool guide.",guideStepsTitle:"Steps",guideTabsTitle:"Tabs",guideTipsTitle:"Tips",guideStep:"Step",guideTip:"Tip"}
};

for(const file of langs){
  const p=dir+'/'+file;
  const c=fs.readFileSync(p,'utf8');
  const code=c.replace(/^export\s+default\s+/,'M.e=');
  const M={e:null};
  try{vm.runInNewContext(code,{M});}catch(e){console.log('❌ '+file);continue;}
  const d=M.e;
  for(const[k,v]of Object.entries(inject)){
    if(typeof v==='object'){d[k]={...(d[k]||{}),...v};}else{d[k]=v;}
  }
  const out=`export default ${JSON.stringify(d,null,2)};\n`;
  fs.writeFileSync(p,out,'utf8');
  console.log('✅ '+file+': '+Object.keys(d).length+' sections');
}
