/**
 * Inject CampaignManager + JourneyBuilder i18n keys into all locale files.
 * Run: node inject_i18n_keys.cjs
 */
const fs = require('fs');
const path = require('path');

const LOCALES_DIR = path.join(__dirname, 'src/i18n/locales');

// ═══════════════════════════════════════════════════════════
// CampaignManager keys
// ═══════════════════════════════════════════════════════════
const campMgr = {
  ko: {title:'캠페인 관리',sub:'AI 마케팅 캠페인 생성·실행·성과 분석',tabOverview:'대시보드',tabList:'캠페인 목록',tabAnalytics:'성과 분석',tabABTest:'A/B 테스트',kpiActive:'진행 중',kpiTotal:'전체',kpiBudget:'총 예산',kpiAvgRoas:'평균 ROAS',colName:'캠페인명',colStatus:'상태',colBudget:'예산',colSpent:'집행액',colRoas:'ROAS',colChannels:'채널',colCreated:'생성일',colActions:'관리',filterAll:'전체',filterActive:'진행 중',filterPaused:'일시 중지',filterDraft:'초안',filterEnded:'종료',filterPending:'승인 대기',noData:'등록된 캠페인이 없습니다.',goAutoMkt:'새 캠페인 생성',searchPh:'캠페인 검색...',close:'닫기',pause:'일시 중지',resume:'재개',save:'저장',cancel:'취소',edit:'편집',delete:'삭제',duplicate:'복제',confirmDelete:'이 캠페인을 영구 삭제하시겠습니까?',impressions:'노출수',clicks:'클릭수',conversions:'전환수',roas:'ROAS',channels:'채널',source:'소스',topPerformer:'Top 캠페인',byChannel:'채널별 분포',byStatus:'상태 분포',budgetUtil:'예산 소진율',budgetOverview:'예산 배분 현황',roasRanking:'ROAS 순위',campaignPerf:'캠페인별 성과',funnelAnalysis:'퍼널 분석',statusActive:'진행 중',statusPaused:'일시 중지',statusDraft:'초안',statusEnded:'종료',statusPending:'승인 대기',editCampaign:'캠페인 편집',campName:'캠페인명',campBudget:'예산 (₩)',campStatus:'상태',abTestTitle:'A/B 테스트 관리',abTestCreate:'새 A/B 테스트 생성',abTestName:'테스트명',abBaseline:'기준 캠페인 (A)',abVariant:'변형 캠페인 (B)',abConfidence:'신뢰도',abWinner:'승자',abNoTest:'등록된 A/B 테스트가 없습니다.',abStart:'테스트 시작',totalBudget:'총 예산',totalSpent:'총 집행액'},
  en: {title:'Campaign Manager',sub:'Create, execute, and analyze AI marketing campaigns',tabOverview:'Dashboard',tabList:'Campaign List',tabAnalytics:'Analytics',tabABTest:'A/B Test',kpiActive:'Active',kpiTotal:'Total',kpiBudget:'Total Budget',kpiAvgRoas:'Avg ROAS',colName:'Campaign',colStatus:'Status',colBudget:'Budget',colSpent:'Spend',colRoas:'ROAS',colChannels:'Channels',colCreated:'Created',colActions:'Actions',filterAll:'All',filterActive:'Active',filterPaused:'Paused',filterDraft:'Draft',filterEnded:'Ended',filterPending:'Pending',noData:'No campaigns registered.',goAutoMkt:'Create Campaign',searchPh:'Search campaigns...',close:'Close',pause:'Pause',resume:'Resume',save:'Save',cancel:'Cancel',edit:'Edit',delete:'Delete',duplicate:'Duplicate',confirmDelete:'Permanently delete this campaign?',impressions:'Impressions',clicks:'Clicks',conversions:'Conversions',roas:'ROAS',channels:'Channels',source:'Source',topPerformer:'Top Campaign',byChannel:'By Channel',byStatus:'By Status',budgetUtil:'Budget Utilization',budgetOverview:'Budget Overview',roasRanking:'ROAS Ranking',campaignPerf:'Campaign Performance',funnelAnalysis:'Funnel Analysis',statusActive:'Active',statusPaused:'Paused',statusDraft:'Draft',statusEnded:'Ended',statusPending:'Pending',editCampaign:'Edit Campaign',campName:'Campaign Name',campBudget:'Budget (₩)',campStatus:'Status',abTestTitle:'A/B Test Manager',abTestCreate:'Create A/B Test',abTestName:'Test Name',abBaseline:'Baseline (A)',abVariant:'Variant (B)',abConfidence:'Confidence',abWinner:'Winner',abNoTest:'No A/B tests registered.',abStart:'Start Test',totalBudget:'Total Budget',totalSpent:'Total Spent'},
  ja: {title:'キャンペーン管理',sub:'AIマーケティングキャンペーンの作成・実行・分析',tabOverview:'ダッシュボード',tabList:'キャンペーン一覧',tabAnalytics:'分析',tabABTest:'A/Bテスト',kpiActive:'実行中',kpiTotal:'全体',kpiBudget:'総予算',kpiAvgRoas:'平均ROAS',colName:'キャンペーン名',colStatus:'ステータス',colBudget:'予算',colSpent:'支出',colRoas:'ROAS',colChannels:'チャネル',colCreated:'作成日',colActions:'操作',filterAll:'全て',filterActive:'実行中',filterPaused:'一時停止',filterDraft:'下書き',filterEnded:'終了',filterPending:'承認待ち',noData:'登録されたキャンペーンはありません。',goAutoMkt:'キャンペーン作成',searchPh:'キャンペーン検索...',close:'閉じる',pause:'一時停止',resume:'再開',save:'保存',cancel:'キャンセル',edit:'編集',delete:'削除',duplicate:'複製',confirmDelete:'このキャンペーンを完全に削除しますか？',impressions:'表示回数',clicks:'クリック数',conversions:'コンバージョン',roas:'ROAS',channels:'チャネル',source:'ソース',topPerformer:'トップキャンペーン',byChannel:'チャネル別',byStatus:'ステータス別',budgetUtil:'予算消化率',budgetOverview:'予算配分状況',roasRanking:'ROASランキング',campaignPerf:'キャンペーン別成果',funnelAnalysis:'ファネル分析',statusActive:'実行中',statusPaused:'一時停止',statusDraft:'下書き',statusEnded:'終了',statusPending:'承認待ち',editCampaign:'キャンペーン編集',campName:'キャンペーン名',campBudget:'予算（₩）',campStatus:'ステータス',abTestTitle:'A/Bテスト管理',abTestCreate:'新規A/Bテスト作成',abTestName:'テスト名',abBaseline:'ベースライン (A)',abVariant:'バリアント (B)',abConfidence:'信頼度',abWinner:'勝者',abNoTest:'登録されたA/Bテストはありません。',abStart:'テスト開始',totalBudget:'総予算',totalSpent:'総支出額'},
  zh: {title:'营销活动管理',sub:'AI营销活动的创建、执行与分析',tabOverview:'仪表盘',tabList:'活动列表',tabAnalytics:'分析',tabABTest:'A/B测试',kpiActive:'进行中',kpiTotal:'总计',kpiBudget:'总预算',kpiAvgRoas:'平均ROAS',colName:'活动名称',colStatus:'状态',colBudget:'预算',colSpent:'花费',colRoas:'ROAS',colChannels:'渠道',colCreated:'创建日期',colActions:'操作',filterAll:'全部',filterActive:'进行中',filterPaused:'已暂停',filterDraft:'草稿',filterEnded:'已结束',filterPending:'待审批',noData:'暂无营销活动。',goAutoMkt:'创建活动',searchPh:'搜索活动...',close:'关闭',pause:'暂停',resume:'恢复',save:'保存',cancel:'取消',edit:'编辑',delete:'删除',duplicate:'复制',confirmDelete:'确定要永久删除此活动吗？',impressions:'曝光量',clicks:'点击量',conversions:'转化量',roas:'ROAS',channels:'渠道',source:'来源',topPerformer:'最佳活动',byChannel:'按渠道',byStatus:'按状态',budgetUtil:'预算使用率',budgetOverview:'预算分配概览',roasRanking:'ROAS排名',campaignPerf:'活动表现',funnelAnalysis:'漏斗分析',statusActive:'进行中',statusPaused:'已暂停',statusDraft:'草稿',statusEnded:'已结束',statusPending:'待审批',editCampaign:'编辑活动',campName:'活动名称',campBudget:'预算（₩）',campStatus:'状态',abTestTitle:'A/B测试管理',abTestCreate:'创建A/B测试',abTestName:'测试名称',abBaseline:'基准组 (A)',abVariant:'变体组 (B)',abConfidence:'置信度',abWinner:'胜出方',abNoTest:'暂无A/B测试。',abStart:'开始测试',totalBudget:'总预算',totalSpent:'总花费'},
  'zh-TW': {title:'行銷活動管理',sub:'AI行銷活動的建立、執行與分析',tabOverview:'儀表板',tabList:'活動列表',tabAnalytics:'分析',tabABTest:'A/B測試',kpiActive:'進行中',kpiTotal:'總計',kpiBudget:'總預算',kpiAvgRoas:'平均ROAS',colName:'活動名稱',colStatus:'狀態',colBudget:'預算',colSpent:'花費',colRoas:'ROAS',colChannels:'頻道',colCreated:'建立日期',colActions:'操作',filterAll:'全部',filterActive:'進行中',filterPaused:'已暫停',filterDraft:'草稿',filterEnded:'已結束',filterPending:'待審批',noData:'尚無行銷活動。',goAutoMkt:'建立活動',searchPh:'搜尋活動...',close:'關閉',pause:'暫停',resume:'恢復',save:'儲存',cancel:'取消',edit:'編輯',delete:'刪除',duplicate:'複製',confirmDelete:'確定要永久刪除此活動嗎？',impressions:'曝光數',clicks:'點擊數',conversions:'轉換數',roas:'ROAS',channels:'頻道',source:'來源',topPerformer:'最佳活動',byChannel:'依頻道',byStatus:'依狀態',budgetUtil:'預算使用率',budgetOverview:'預算分配概覽',roasRanking:'ROAS排名',campaignPerf:'活動表現',funnelAnalysis:'漏斗分析',statusActive:'進行中',statusPaused:'已暫停',statusDraft:'草稿',statusEnded:'已結束',statusPending:'待審批',editCampaign:'編輯活動',campName:'活動名稱',campBudget:'預算（₩）',campStatus:'狀態',abTestTitle:'A/B測試管理',abTestCreate:'建立A/B測試',abTestName:'測試名稱',abBaseline:'基準組 (A)',abVariant:'變體組 (B)',abConfidence:'信賴度',abWinner:'勝出方',abNoTest:'尚無A/B測試。',abStart:'開始測試',totalBudget:'總預算',totalSpent:'總花費'},
  es: {title:'Gestor de Campañas',sub:'Cree, ejecute y analice campañas de marketing con IA',tabOverview:'Panel',tabList:'Lista de campañas',tabAnalytics:'Análisis',tabABTest:'Test A/B',kpiActive:'Activas',kpiTotal:'Total',kpiBudget:'Presupuesto total',kpiAvgRoas:'ROAS promedio',colName:'Campaña',colStatus:'Estado',colBudget:'Presupuesto',colSpent:'Gasto',colRoas:'ROAS',colChannels:'Canales',colCreated:'Creada',colActions:'Acciones',filterAll:'Todas',filterActive:'Activas',filterPaused:'Pausadas',filterDraft:'Borrador',filterEnded:'Finalizadas',filterPending:'Pendientes',noData:'No hay campañas registradas.',goAutoMkt:'Crear campaña',searchPh:'Buscar campañas...',close:'Cerrar',pause:'Pausar',resume:'Reanudar',save:'Guardar',cancel:'Cancelar',edit:'Editar',delete:'Eliminar',duplicate:'Duplicar',confirmDelete:'¿Eliminar permanentemente esta campaña?',impressions:'Impresiones',clicks:'Clics',conversions:'Conversiones',roas:'ROAS',channels:'Canales',source:'Fuente',topPerformer:'Mejor campaña',byChannel:'Por canal',byStatus:'Por estado',budgetUtil:'Uso del presupuesto',budgetOverview:'Distribución del presupuesto',roasRanking:'Ranking ROAS',campaignPerf:'Rendimiento',funnelAnalysis:'Análisis de embudo',statusActive:'Activa',statusPaused:'Pausada',statusDraft:'Borrador',statusEnded:'Finalizada',statusPending:'Pendiente',editCampaign:'Editar campaña',campName:'Nombre de campaña',campBudget:'Presupuesto (₩)',campStatus:'Estado',abTestTitle:'Gestión de Test A/B',abTestCreate:'Crear test A/B',abTestName:'Nombre del test',abBaseline:'Línea base (A)',abVariant:'Variante (B)',abConfidence:'Confianza',abWinner:'Ganador',abNoTest:'No hay tests A/B registrados.',abStart:'Iniciar test',totalBudget:'Presupuesto total',totalSpent:'Gasto total'},
  fr: {title:'Gestionnaire de campagnes',sub:'Créez, exécutez et analysez vos campagnes marketing IA',tabOverview:'Tableau de bord',tabList:'Liste des campagnes',tabAnalytics:'Analyses',tabABTest:'Test A/B',kpiActive:'En cours',kpiTotal:'Total',kpiBudget:'Budget total',kpiAvgRoas:'ROAS moyen',colName:'Campagne',colStatus:'Statut',colBudget:'Budget',colSpent:'Dépense',colRoas:'ROAS',colChannels:'Canaux',colCreated:'Créée le',colActions:'Actions',filterAll:'Toutes',filterActive:'En cours',filterPaused:'En pause',filterDraft:'Brouillon',filterEnded:'Terminées',filterPending:'En attente',noData:'Aucune campagne enregistrée.',goAutoMkt:'Créer une campagne',searchPh:'Rechercher...',close:'Fermer',pause:'Mettre en pause',resume:'Reprendre',save:'Enregistrer',cancel:'Annuler',edit:'Modifier',delete:'Supprimer',duplicate:'Dupliquer',confirmDelete:'Supprimer définitivement cette campagne ?',impressions:'Impressions',clicks:'Clics',conversions:'Conversions',roas:'ROAS',channels:'Canaux',source:'Source',topPerformer:'Meilleure campagne',byChannel:'Par canal',byStatus:'Par statut',budgetUtil:'Utilisation du budget',budgetOverview:'Répartition du budget',roasRanking:'Classement ROAS',campaignPerf:'Performances',funnelAnalysis:'Analyse de l\'entonnoir',statusActive:'En cours',statusPaused:'En pause',statusDraft:'Brouillon',statusEnded:'Terminée',statusPending:'En attente',editCampaign:'Modifier la campagne',campName:'Nom de la campagne',campBudget:'Budget (₩)',campStatus:'Statut',abTestTitle:'Gestion des tests A/B',abTestCreate:'Créer un test A/B',abTestName:'Nom du test',abBaseline:'Référence (A)',abVariant:'Variante (B)',abConfidence:'Confiance',abWinner:'Gagnant',abNoTest:'Aucun test A/B enregistré.',abStart:'Lancer le test',totalBudget:'Budget total',totalSpent:'Dépenses totales'},
  de: {title:'Kampagnenmanager',sub:'AI-Marketingkampagnen erstellen, ausführen und analysieren',tabOverview:'Dashboard',tabList:'Kampagnenliste',tabAnalytics:'Analyse',tabABTest:'A/B-Test',kpiActive:'Aktiv',kpiTotal:'Gesamt',kpiBudget:'Gesamtbudget',kpiAvgRoas:'Ø ROAS',colName:'Kampagne',colStatus:'Status',colBudget:'Budget',colSpent:'Ausgaben',colRoas:'ROAS',colChannels:'Kanäle',colCreated:'Erstellt',colActions:'Aktionen',filterAll:'Alle',filterActive:'Aktiv',filterPaused:'Pausiert',filterDraft:'Entwurf',filterEnded:'Beendet',filterPending:'Ausstehend',noData:'Keine Kampagnen vorhanden.',goAutoMkt:'Kampagne erstellen',searchPh:'Kampagnen suchen...',close:'Schließen',pause:'Pausieren',resume:'Fortsetzen',save:'Speichern',cancel:'Abbrechen',edit:'Bearbeiten',delete:'Löschen',duplicate:'Duplizieren',confirmDelete:'Diese Kampagne unwiderruflich löschen?',impressions:'Impressionen',clicks:'Klicks',conversions:'Conversions',roas:'ROAS',channels:'Kanäle',source:'Quelle',topPerformer:'Top-Kampagne',byChannel:'Nach Kanal',byStatus:'Nach Status',budgetUtil:'Budgetauslastung',budgetOverview:'Budgetverteilung',roasRanking:'ROAS-Ranking',campaignPerf:'Kampagnenleistung',funnelAnalysis:'Trichteranalyse',statusActive:'Aktiv',statusPaused:'Pausiert',statusDraft:'Entwurf',statusEnded:'Beendet',statusPending:'Ausstehend',editCampaign:'Kampagne bearbeiten',campName:'Kampagnenname',campBudget:'Budget (₩)',campStatus:'Status',abTestTitle:'A/B-Test-Verwaltung',abTestCreate:'Neuen A/B-Test erstellen',abTestName:'Testname',abBaseline:'Basislinie (A)',abVariant:'Variante (B)',abConfidence:'Vertrauen',abWinner:'Gewinner',abNoTest:'Keine A/B-Tests vorhanden.',abStart:'Test starten',totalBudget:'Gesamtbudget',totalSpent:'Gesamtausgaben'},
  pt: {title:'Gestor de Campanhas',sub:'Crie, execute e analise campanhas de marketing com IA',tabOverview:'Painel',tabList:'Lista de campanhas',tabAnalytics:'Análise',tabABTest:'Teste A/B',kpiActive:'Ativas',kpiTotal:'Total',kpiBudget:'Orçamento total',kpiAvgRoas:'ROAS médio',colName:'Campanha',colStatus:'Status',colBudget:'Orçamento',colSpent:'Gasto',colRoas:'ROAS',colChannels:'Canais',colCreated:'Criada em',colActions:'Ações',filterAll:'Todas',filterActive:'Ativas',filterPaused:'Pausadas',filterDraft:'Rascunho',filterEnded:'Encerradas',filterPending:'Pendentes',noData:'Nenhuma campanha registrada.',goAutoMkt:'Criar campanha',searchPh:'Pesquisar campanhas...',close:'Fechar',pause:'Pausar',resume:'Retomar',save:'Salvar',cancel:'Cancelar',edit:'Editar',delete:'Excluir',duplicate:'Duplicar',confirmDelete:'Excluir permanentemente esta campanha?',impressions:'Impressões',clicks:'Cliques',conversions:'Conversões',roas:'ROAS',channels:'Canais',source:'Fonte',topPerformer:'Melhor campanha',byChannel:'Por canal',byStatus:'Por status',budgetUtil:'Uso do orçamento',budgetOverview:'Distribuição do orçamento',roasRanking:'Ranking ROAS',campaignPerf:'Desempenho',funnelAnalysis:'Análise de funil',statusActive:'Ativa',statusPaused:'Pausada',statusDraft:'Rascunho',statusEnded:'Encerrada',statusPending:'Pendente',editCampaign:'Editar campanha',campName:'Nome da campanha',campBudget:'Orçamento (₩)',campStatus:'Status',abTestTitle:'Gestão de Testes A/B',abTestCreate:'Criar teste A/B',abTestName:'Nome do teste',abBaseline:'Base (A)',abVariant:'Variante (B)',abConfidence:'Confiança',abWinner:'Vencedor',abNoTest:'Nenhum teste A/B registrado.',abStart:'Iniciar teste',totalBudget:'Orçamento total',totalSpent:'Gasto total'},
  ru: {title:'Управление кампаниями',sub:'Создание, запуск и анализ AI-маркетинговых кампаний',tabOverview:'Дашборд',tabList:'Список кампаний',tabAnalytics:'Аналитика',tabABTest:'A/B-тест',kpiActive:'Активных',kpiTotal:'Всего',kpiBudget:'Общий бюджет',kpiAvgRoas:'Сред. ROAS',colName:'Кампания',colStatus:'Статус',colBudget:'Бюджет',colSpent:'Расход',colRoas:'ROAS',colChannels:'Каналы',colCreated:'Создана',colActions:'Действия',filterAll:'Все',filterActive:'Активные',filterPaused:'На паузе',filterDraft:'Черновик',filterEnded:'Завершённые',filterPending:'На рассмотрении',noData:'Кампании не зарегистрированы.',goAutoMkt:'Создать кампанию',searchPh:'Поиск кампаний...',close:'Закрыть',pause:'Пауза',resume:'Возобновить',save:'Сохранить',cancel:'Отмена',edit:'Редактировать',delete:'Удалить',duplicate:'Дублировать',confirmDelete:'Удалить эту кампанию безвозвратно?',impressions:'Показы',clicks:'Клики',conversions:'Конверсии',roas:'ROAS',channels:'Каналы',source:'Источник',topPerformer:'Лучшая кампания',byChannel:'По каналам',byStatus:'По статусу',budgetUtil:'Использование бюджета',budgetOverview:'Распределение бюджета',roasRanking:'Рейтинг ROAS',campaignPerf:'Эффективность',funnelAnalysis:'Анализ воронки',statusActive:'Активна',statusPaused:'На паузе',statusDraft:'Черновик',statusEnded:'Завершена',statusPending:'На рассмотрении',editCampaign:'Редактировать кампанию',campName:'Название кампании',campBudget:'Бюджет (₩)',campStatus:'Статус',abTestTitle:'Управление A/B-тестами',abTestCreate:'Создать A/B-тест',abTestName:'Название теста',abBaseline:'Базовый (A)',abVariant:'Вариант (B)',abConfidence:'Достоверность',abWinner:'Победитель',abNoTest:'A/B-тесты не зарегистрированы.',abStart:'Начать тест',totalBudget:'Общий бюджет',totalSpent:'Общий расход'},
  ar: {title:'إدارة الحملات',sub:'إنشاء وتنفيذ وتحليل حملات التسويق بالذكاء الاصطناعي',tabOverview:'لوحة المعلومات',tabList:'قائمة الحملات',tabAnalytics:'التحليلات',tabABTest:'اختبار A/B',kpiActive:'نشطة',kpiTotal:'الإجمالي',kpiBudget:'إجمالي الميزانية',kpiAvgRoas:'متوسط ROAS',colName:'الحملة',colStatus:'الحالة',colBudget:'الميزانية',colSpent:'المصروف',colRoas:'ROAS',colChannels:'القنوات',colCreated:'تاريخ الإنشاء',colActions:'إجراءات',filterAll:'الكل',filterActive:'نشطة',filterPaused:'متوقفة مؤقتاً',filterDraft:'مسودة',filterEnded:'منتهية',filterPending:'قيد المراجعة',noData:'لا توجد حملات مسجلة.',goAutoMkt:'إنشاء حملة',searchPh:'البحث عن حملات...',close:'إغلاق',pause:'إيقاف مؤقت',resume:'استئناف',save:'حفظ',cancel:'إلغاء',edit:'تعديل',delete:'حذف',duplicate:'نسخ',confirmDelete:'هل تريد حذف هذه الحملة نهائياً؟',impressions:'مرات الظهور',clicks:'النقرات',conversions:'التحويلات',roas:'ROAS',channels:'القنوات',source:'المصدر',topPerformer:'أفضل حملة',byChannel:'حسب القناة',byStatus:'حسب الحالة',budgetUtil:'استخدام الميزانية',budgetOverview:'توزيع الميزانية',roasRanking:'ترتيب ROAS',campaignPerf:'أداء الحملات',funnelAnalysis:'تحليل القمع',statusActive:'نشطة',statusPaused:'متوقفة',statusDraft:'مسودة',statusEnded:'منتهية',statusPending:'قيد المراجعة',editCampaign:'تعديل الحملة',campName:'اسم الحملة',campBudget:'الميزانية (₩)',campStatus:'الحالة',abTestTitle:'إدارة اختبارات A/B',abTestCreate:'إنشاء اختبار A/B',abTestName:'اسم الاختبار',abBaseline:'المرجع (A)',abVariant:'البديل (B)',abConfidence:'الموثوقية',abWinner:'الفائز',abNoTest:'لا توجد اختبارات A/B.',abStart:'بدء الاختبار',totalBudget:'إجمالي الميزانية',totalSpent:'إجمالي الإنفاق',dir:'rtl'},
  vi: {title:'Quản lý chiến dịch',sub:'Tạo, thực thi và phân tích chiến dịch marketing AI',tabOverview:'Tổng quan',tabList:'Danh sách chiến dịch',tabAnalytics:'Phân tích',tabABTest:'A/B Test',kpiActive:'Đang chạy',kpiTotal:'Tổng cộng',kpiBudget:'Tổng ngân sách',kpiAvgRoas:'ROAS TB',colName:'Chiến dịch',colStatus:'Trạng thái',colBudget:'Ngân sách',colSpent:'Chi tiêu',colRoas:'ROAS',colChannels:'Kênh',colCreated:'Ngày tạo',colActions:'Thao tác',filterAll:'Tất cả',filterActive:'Đang chạy',filterPaused:'Tạm dừng',filterDraft:'Nháp',filterEnded:'Kết thúc',filterPending:'Chờ duyệt',noData:'Chưa có chiến dịch nào.',goAutoMkt:'Tạo chiến dịch',searchPh:'Tìm chiến dịch...',close:'Đóng',pause:'Tạm dừng',resume:'Tiếp tục',save:'Lưu',cancel:'Hủy',edit:'Sửa',delete:'Xóa',duplicate:'Nhân bản',confirmDelete:'Xóa vĩnh viễn chiến dịch này?',impressions:'Lượt hiển thị',clicks:'Lượt nhấp',conversions:'Chuyển đổi',roas:'ROAS',channels:'Kênh',source:'Nguồn',topPerformer:'Chiến dịch tốt nhất',byChannel:'Theo kênh',byStatus:'Theo trạng thái',budgetUtil:'Tỷ lệ sử dụng ngân sách',budgetOverview:'Phân bổ ngân sách',roasRanking:'Xếp hạng ROAS',campaignPerf:'Hiệu suất chiến dịch',funnelAnalysis:'Phân tích phễu',statusActive:'Đang chạy',statusPaused:'Tạm dừng',statusDraft:'Nháp',statusEnded:'Kết thúc',statusPending:'Chờ duyệt',editCampaign:'Sửa chiến dịch',campName:'Tên chiến dịch',campBudget:'Ngân sách (₩)',campStatus:'Trạng thái',abTestTitle:'Quản lý A/B Test',abTestCreate:'Tạo A/B Test',abTestName:'Tên test',abBaseline:'Cơ sở (A)',abVariant:'Biến thể (B)',abConfidence:'Độ tin cậy',abWinner:'Chiến thắng',abNoTest:'Chưa có A/B Test nào.',abStart:'Bắt đầu test',totalBudget:'Tổng ngân sách',totalSpent:'Tổng chi tiêu'},
  th: {title:'จัดการแคมเปญ',sub:'สร้าง ดำเนินการ และวิเคราะห์แคมเปญการตลาด AI',tabOverview:'แดชบอร์ด',tabList:'รายการแคมเปญ',tabAnalytics:'วิเคราะห์',tabABTest:'ทดสอบ A/B',kpiActive:'กำลังดำเนินการ',kpiTotal:'ทั้งหมด',kpiBudget:'งบประมาณรวม',kpiAvgRoas:'ROAS เฉลี่ย',colName:'แคมเปญ',colStatus:'สถานะ',colBudget:'งบประมาณ',colSpent:'ใช้จ่าย',colRoas:'ROAS',colChannels:'ช่องทาง',colCreated:'สร้างเมื่อ',colActions:'ดำเนินการ',filterAll:'ทั้งหมด',filterActive:'กำลังดำเนินการ',filterPaused:'หยุดชั่วคราว',filterDraft:'แบบร่าง',filterEnded:'สิ้นสุด',filterPending:'รอการอนุมัติ',noData:'ยังไม่มีแคมเปญ',goAutoMkt:'สร้างแคมเปญ',searchPh:'ค้นหาแคมเปญ...',close:'ปิด',pause:'หยุดชั่วคราว',resume:'ดำเนินการต่อ',save:'บันทึก',cancel:'ยกเลิก',edit:'แก้ไข',delete:'ลบ',duplicate:'สำเนา',confirmDelete:'ลบแคมเปญนี้อย่างถาวร?',impressions:'จำนวนการแสดงผล',clicks:'คลิก',conversions:'การแปลง',roas:'ROAS',channels:'ช่องทาง',source:'แหล่งที่มา',topPerformer:'แคมเปญยอดเยี่ยม',byChannel:'ตามช่องทาง',byStatus:'ตามสถานะ',budgetUtil:'การใช้งบประมาณ',budgetOverview:'ภาพรวมงบประมาณ',roasRanking:'อันดับ ROAS',campaignPerf:'ผลงานแคมเปญ',funnelAnalysis:'วิเคราะห์กรวย',statusActive:'กำลังดำเนินการ',statusPaused:'หยุดชั่วคราว',statusDraft:'แบบร่าง',statusEnded:'สิ้นสุด',statusPending:'รอการอนุมัติ',editCampaign:'แก้ไขแคมเปญ',campName:'ชื่อแคมเปญ',campBudget:'งบประมาณ (₩)',campStatus:'สถานะ',abTestTitle:'จัดการทดสอบ A/B',abTestCreate:'สร้างทดสอบ A/B',abTestName:'ชื่อทดสอบ',abBaseline:'ฐาน (A)',abVariant:'ตัวแปร (B)',abConfidence:'ความเชื่อมั่น',abWinner:'ผู้ชนะ',abNoTest:'ยังไม่มีทดสอบ A/B',abStart:'เริ่มทดสอบ',totalBudget:'งบประมาณรวม',totalSpent:'ใช้จ่ายรวม'},
  id: {title:'Manajer Kampanye',sub:'Buat, jalankan, dan analisis kampanye pemasaran AI',tabOverview:'Dasbor',tabList:'Daftar Kampanye',tabAnalytics:'Analitik',tabABTest:'Tes A/B',kpiActive:'Aktif',kpiTotal:'Total',kpiBudget:'Total Anggaran',kpiAvgRoas:'Rata-rata ROAS',colName:'Kampanye',colStatus:'Status',colBudget:'Anggaran',colSpent:'Pengeluaran',colRoas:'ROAS',colChannels:'Saluran',colCreated:'Dibuat',colActions:'Aksi',filterAll:'Semua',filterActive:'Aktif',filterPaused:'Dijeda',filterDraft:'Draf',filterEnded:'Selesai',filterPending:'Menunggu',noData:'Belum ada kampanye terdaftar.',goAutoMkt:'Buat Kampanye',searchPh:'Cari kampanye...',close:'Tutup',pause:'Jeda',resume:'Lanjutkan',save:'Simpan',cancel:'Batal',edit:'Edit',delete:'Hapus',duplicate:'Duplikat',confirmDelete:'Hapus kampanye ini secara permanen?',impressions:'Tayangan',clicks:'Klik',conversions:'Konversi',roas:'ROAS',channels:'Saluran',source:'Sumber',topPerformer:'Kampanye Terbaik',byChannel:'Per Saluran',byStatus:'Per Status',budgetUtil:'Pemanfaatan Anggaran',budgetOverview:'Distribusi Anggaran',roasRanking:'Peringkat ROAS',campaignPerf:'Performa Kampanye',funnelAnalysis:'Analisis Funnel',statusActive:'Aktif',statusPaused:'Dijeda',statusDraft:'Draf',statusEnded:'Selesai',statusPending:'Menunggu',editCampaign:'Edit Kampanye',campName:'Nama Kampanye',campBudget:'Anggaran (₩)',campStatus:'Status',abTestTitle:'Manajer Tes A/B',abTestCreate:'Buat Tes A/B',abTestName:'Nama Tes',abBaseline:'Dasar (A)',abVariant:'Varian (B)',abConfidence:'Kepercayaan',abWinner:'Pemenang',abNoTest:'Belum ada tes A/B.',abStart:'Mulai Tes',totalBudget:'Total Anggaran',totalSpent:'Total Pengeluaran'},
  hi: {title:'अभियान प्रबंधक',sub:'AI मार्केटिंग अभियान बनाएं, चलाएं और विश्लेषण करें',tabOverview:'डैशबोर्ड',tabList:'अभियान सूची',tabAnalytics:'विश्लेषण',tabABTest:'A/B परीक्षण',kpiActive:'सक्रिय',kpiTotal:'कुल',kpiBudget:'कुल बजट',kpiAvgRoas:'औसत ROAS',colName:'अभियान',colStatus:'स्थिति',colBudget:'बजट',colSpent:'खर्च',colRoas:'ROAS',colChannels:'चैनल',colCreated:'बनाया गया',colActions:'कार्रवाई',filterAll:'सभी',filterActive:'सक्रिय',filterPaused:'रुके हुए',filterDraft:'ड्राफ्ट',filterEnded:'समाप्त',filterPending:'लंबित',noData:'कोई अभियान पंजीकृत नहीं है।',goAutoMkt:'अभियान बनाएं',searchPh:'अभियान खोजें...',close:'बंद करें',pause:'रोकें',resume:'फिर शुरू करें',save:'सहेजें',cancel:'रद्द करें',edit:'संपादित करें',delete:'हटाएं',duplicate:'डुप्लिकेट',confirmDelete:'इस अभियान को स्थायी रूप से हटाएं?',impressions:'इंप्रेशन',clicks:'क्लिक',conversions:'कन्वर्शन',roas:'ROAS',channels:'चैनल',source:'स्रोत',topPerformer:'शीर्ष अभियान',byChannel:'चैनल अनुसार',byStatus:'स्थिति अनुसार',budgetUtil:'बजट उपयोग',budgetOverview:'बजट वितरण',roasRanking:'ROAS रैंकिंग',campaignPerf:'अभियान प्रदर्शन',funnelAnalysis:'फ़नल विश्लेषण',statusActive:'सक्रिय',statusPaused:'रुका हुआ',statusDraft:'ड्राफ्ट',statusEnded:'समाप्त',statusPending:'लंबित',editCampaign:'अभियान संपादित करें',campName:'अभियान नाम',campBudget:'बजट (₩)',campStatus:'स्थिति',abTestTitle:'A/B परीक्षण प्रबंधन',abTestCreate:'A/B परीक्षण बनाएं',abTestName:'परीक्षण नाम',abBaseline:'आधारभूत (A)',abVariant:'वैरिएंट (B)',abConfidence:'विश्वसनीयता',abWinner:'विजेता',abNoTest:'कोई A/B परीक्षण नहीं।',abStart:'परीक्षण शुरू करें',totalBudget:'कुल बजट',totalSpent:'कुल खर्च'},
};

// ═══════════════════════════════════════════════════════════
// JourneyBuilder keys
// ═══════════════════════════════════════════════════════════
const jb = {
  ko: {title:'고객 여정 빌더',sub:'AI 기반 자동화 고객 여정 설계·실행·분석',tabBuilder:'여정 빌더',tabList:'여정 목록',tabLogs:'실행 로그',tabAnalytics:'분석',createJourney:'새 여정 생성',journeyName:'여정 이름',triggerType:'트리거 유형',triggerSignup:'회원가입',triggerPurchase:'구매 완료',triggerAbandon:'장바구니 이탈',triggerChurn:'이탈 위험',triggerSegment:'세그먼트 진입',triggerManual:'수동 실행',targetSegment:'대상 세그먼트',channels:'채널',email:'이메일',kakao:'카카오',sms:'SMS',push:'푸시',line:'LINE',delayLabel:'대기 시간',delayNone:'즉시',delay1h:'1시간',delay1d:'1일',delay3d:'3일',delay7d:'7일',save:'저장',cancel:'취소',run:'실행',edit:'편집',delete:'삭제',duplicate:'복제',close:'닫기',statusDraft:'초안',statusActive:'활성',statusPaused:'일시 중지',statusCompleted:'완료',totalJourneys:'전체 여정',activeJourneys:'활성 여정',totalExecutions:'총 실행',totalEntered:'총 진입',totalCompleted:'총 완료',avgCompletion:'평균 완료율',totalEmails:'이메일 발송',totalKakao:'카카오 발송',totalRevenue:'총 매출',recentLogs:'최근 트리거 로그',executionHistory:'여정 실행 이력',noData:'등록된 여정이 없습니다.',noLogs:'실행 로그가 없습니다.',confirmDelete:'이 여정을 영구 삭제하시겠습니까?',flowPreview:'흐름 미리보기',stepTrigger:'트리거',stepDelay:'대기',stepAction:'액션',stepEnd:'종료',byTrigger:'트리거별 분포',byChannel:'채널별 분포',completionRate:'완료율 추이',goAutoMkt:'AI 오토마케팅',goCRM:'CRM'},
  en: {title:'Customer Journey Builder',sub:'Design, execute, and analyze automated customer journeys with AI',tabBuilder:'Journey Builder',tabList:'Journey List',tabLogs:'Execution Logs',tabAnalytics:'Analytics',createJourney:'Create Journey',journeyName:'Journey Name',triggerType:'Trigger Type',triggerSignup:'Sign Up',triggerPurchase:'Purchase Complete',triggerAbandon:'Cart Abandonment',triggerChurn:'Churn Risk',triggerSegment:'Segment Entry',triggerManual:'Manual',targetSegment:'Target Segment',channels:'Channels',email:'Email',kakao:'Kakao',sms:'SMS',push:'Push',line:'LINE',delayLabel:'Delay',delayNone:'Immediate',delay1h:'1 Hour',delay1d:'1 Day',delay3d:'3 Days',delay7d:'7 Days',save:'Save',cancel:'Cancel',run:'Run',edit:'Edit',delete:'Delete',duplicate:'Duplicate',close:'Close',statusDraft:'Draft',statusActive:'Active',statusPaused:'Paused',statusCompleted:'Completed',totalJourneys:'Total Journeys',activeJourneys:'Active Journeys',totalExecutions:'Total Executions',totalEntered:'Total Entered',totalCompleted:'Total Completed',avgCompletion:'Avg Completion',totalEmails:'Emails Sent',totalKakao:'Kakao Sent',totalRevenue:'Total Revenue',recentLogs:'Recent Trigger Logs',executionHistory:'Execution History',noData:'No journeys registered.',noLogs:'No execution logs.',confirmDelete:'Permanently delete this journey?',flowPreview:'Flow Preview',stepTrigger:'Trigger',stepDelay:'Delay',stepAction:'Action',stepEnd:'End',byTrigger:'By Trigger',byChannel:'By Channel',completionRate:'Completion Rate Trend',goAutoMkt:'AI Auto Marketing',goCRM:'CRM'},
  ja: {title:'カスタマージャーニービルダー',sub:'AI基盤の自動化カスタマージャーニーの設計・実行・分析',tabBuilder:'ジャーニービルダー',tabList:'ジャーニー一覧',tabLogs:'実行ログ',tabAnalytics:'分析',createJourney:'新規ジャーニー作成',journeyName:'ジャーニー名',triggerType:'トリガー種別',triggerSignup:'会員登録',triggerPurchase:'購入完了',triggerAbandon:'カート離脱',triggerChurn:'離脱リスク',triggerSegment:'セグメント参入',triggerManual:'手動実行',targetSegment:'対象セグメント',channels:'チャネル',email:'メール',kakao:'カカオ',sms:'SMS',push:'プッシュ',line:'LINE',delayLabel:'待機時間',delayNone:'即時',delay1h:'1時間',delay1d:'1日',delay3d:'3日',delay7d:'7日',save:'保存',cancel:'キャンセル',run:'実行',edit:'編集',delete:'削除',duplicate:'複製',close:'閉じる',statusDraft:'下書き',statusActive:'アクティブ',statusPaused:'一時停止',statusCompleted:'完了',totalJourneys:'全ジャーニー',activeJourneys:'アクティブ',totalExecutions:'総実行回数',totalEntered:'総参入数',totalCompleted:'総完了数',avgCompletion:'平均完了率',totalEmails:'メール送信数',totalKakao:'カカオ送信数',totalRevenue:'総売上',recentLogs:'最近のトリガーログ',executionHistory:'実行履歴',noData:'登録済みジャーニーはありません。',noLogs:'実行ログはありません。',confirmDelete:'このジャーニーを完全に削除しますか？',flowPreview:'フロープレビュー',stepTrigger:'トリガー',stepDelay:'待機',stepAction:'アクション',stepEnd:'終了',byTrigger:'トリガー別',byChannel:'チャネル別',completionRate:'完了率推移',goAutoMkt:'AIオートマーケティング',goCRM:'CRM'},
  zh: {title:'客户旅程构建器',sub:'基于AI的自动化客户旅程设计、执行与分析',tabBuilder:'旅程构建器',tabList:'旅程列表',tabLogs:'执行日志',tabAnalytics:'分析',createJourney:'创建旅程',journeyName:'旅程名称',triggerType:'触发类型',triggerSignup:'注册',triggerPurchase:'购买完成',triggerAbandon:'购物车放弃',triggerChurn:'流失风险',triggerSegment:'分群进入',triggerManual:'手动执行',targetSegment:'目标分群',channels:'渠道',email:'邮件',kakao:'Kakao',sms:'短信',push:'推送',line:'LINE',delayLabel:'等待时间',delayNone:'立即',delay1h:'1小时',delay1d:'1天',delay3d:'3天',delay7d:'7天',save:'保存',cancel:'取消',run:'执行',edit:'编辑',delete:'删除',duplicate:'复制',close:'关闭',statusDraft:'草稿',statusActive:'活跃',statusPaused:'已暂停',statusCompleted:'已完成',totalJourneys:'全部旅程',activeJourneys:'活跃旅程',totalExecutions:'总执行次数',totalEntered:'总进入数',totalCompleted:'总完成数',avgCompletion:'平均完成率',totalEmails:'邮件发送数',totalKakao:'Kakao发送数',totalRevenue:'总收入',recentLogs:'最近触发日志',executionHistory:'执行历史',noData:'暂无旅程。',noLogs:'暂无执行日志。',confirmDelete:'确定要永久删除此旅程吗？',flowPreview:'流程预览',stepTrigger:'触发',stepDelay:'等待',stepAction:'动作',stepEnd:'结束',byTrigger:'按触发类型',byChannel:'按渠道',completionRate:'完成率趋势',goAutoMkt:'AI自动营销',goCRM:'CRM'},
  'zh-TW': {title:'客戶旅程建構器',sub:'基於AI的自動化客戶旅程設計、執行與分析',tabBuilder:'旅程建構器',tabList:'旅程列表',tabLogs:'執行日誌',tabAnalytics:'分析',createJourney:'建立旅程',journeyName:'旅程名稱',triggerType:'觸發類型',triggerSignup:'註冊',triggerPurchase:'購買完成',triggerAbandon:'購物車放棄',triggerChurn:'流失風險',triggerSegment:'分群進入',triggerManual:'手動執行',targetSegment:'目標分群',channels:'頻道',email:'電子郵件',kakao:'Kakao',sms:'簡訊',push:'推播',line:'LINE',delayLabel:'等待時間',delayNone:'立即',delay1h:'1小時',delay1d:'1天',delay3d:'3天',delay7d:'7天',save:'儲存',cancel:'取消',run:'執行',edit:'編輯',delete:'刪除',duplicate:'複製',close:'關閉',statusDraft:'草稿',statusActive:'啟用中',statusPaused:'已暫停',statusCompleted:'已完成',totalJourneys:'全部旅程',activeJourneys:'啟用中旅程',totalExecutions:'總執行次數',totalEntered:'總進入數',totalCompleted:'總完成數',avgCompletion:'平均完成率',totalEmails:'郵件發送數',totalKakao:'Kakao發送數',totalRevenue:'總營收',recentLogs:'最近觸發日誌',executionHistory:'執行歷史',noData:'尚無旅程。',noLogs:'尚無執行日誌。',confirmDelete:'確定要永久刪除此旅程嗎？',flowPreview:'流程預覽',stepTrigger:'觸發',stepDelay:'等待',stepAction:'動作',stepEnd:'結束',byTrigger:'依觸發類型',byChannel:'依頻道',completionRate:'完成率趨勢',goAutoMkt:'AI自動行銷',goCRM:'CRM'},
  es: {title:'Constructor de Recorridos',sub:'Diseñe, ejecute y analice recorridos automatizados del cliente con IA',tabBuilder:'Constructor',tabList:'Lista',tabLogs:'Registros',tabAnalytics:'Análisis',createJourney:'Crear recorrido',journeyName:'Nombre del recorrido',triggerType:'Tipo de disparador',triggerSignup:'Registro',triggerPurchase:'Compra completada',triggerAbandon:'Carrito abandonado',triggerChurn:'Riesgo de abandono',triggerSegment:'Entrada a segmento',triggerManual:'Manual',targetSegment:'Segmento objetivo',channels:'Canales',email:'Correo electrónico',kakao:'Kakao',sms:'SMS',push:'Push',line:'LINE',delayLabel:'Retraso',delayNone:'Inmediato',delay1h:'1 hora',delay1d:'1 día',delay3d:'3 días',delay7d:'7 días',save:'Guardar',cancel:'Cancelar',run:'Ejecutar',edit:'Editar',delete:'Eliminar',duplicate:'Duplicar',close:'Cerrar',statusDraft:'Borrador',statusActive:'Activo',statusPaused:'Pausado',statusCompleted:'Completado',totalJourneys:'Total recorridos',activeJourneys:'Recorridos activos',totalExecutions:'Total ejecuciones',totalEntered:'Total ingresados',totalCompleted:'Total completados',avgCompletion:'Tasa de finalización',totalEmails:'Correos enviados',totalKakao:'Kakao enviados',totalRevenue:'Ingresos totales',recentLogs:'Registros recientes',executionHistory:'Historial de ejecución',noData:'No hay recorridos registrados.',noLogs:'No hay registros de ejecución.',confirmDelete:'¿Eliminar este recorrido permanentemente?',flowPreview:'Vista previa del flujo',stepTrigger:'Disparador',stepDelay:'Espera',stepAction:'Acción',stepEnd:'Fin',byTrigger:'Por disparador',byChannel:'Por canal',completionRate:'Tendencia de finalización',goAutoMkt:'AI Auto Marketing',goCRM:'CRM'},
  fr: {title:'Constructeur de parcours',sub:'Concevez, exécutez et analysez des parcours clients automatisés par IA',tabBuilder:'Constructeur',tabList:'Liste',tabLogs:'Journaux',tabAnalytics:'Analyses',createJourney:'Créer un parcours',journeyName:'Nom du parcours',triggerType:'Type de déclencheur',triggerSignup:'Inscription',triggerPurchase:'Achat effectué',triggerAbandon:'Abandon de panier',triggerChurn:'Risque de désabonnement',triggerSegment:'Entrée dans le segment',triggerManual:'Manuel',targetSegment:'Segment cible',channels:'Canaux',email:'E-mail',kakao:'Kakao',sms:'SMS',push:'Push',line:'LINE',delayLabel:'Délai',delayNone:'Immédiat',delay1h:'1 heure',delay1d:'1 jour',delay3d:'3 jours',delay7d:'7 jours',save:'Enregistrer',cancel:'Annuler',run:'Exécuter',edit:'Modifier',delete:'Supprimer',duplicate:'Dupliquer',close:'Fermer',statusDraft:'Brouillon',statusActive:'Actif',statusPaused:'En pause',statusCompleted:'Terminé',totalJourneys:'Total des parcours',activeJourneys:'Parcours actifs',totalExecutions:'Total des exécutions',totalEntered:'Total entrés',totalCompleted:'Total terminés',avgCompletion:'Taux moyen d\'achèvement',totalEmails:'E-mails envoyés',totalKakao:'Kakao envoyés',totalRevenue:'Revenus totaux',recentLogs:'Journaux récents',executionHistory:'Historique d\'exécution',noData:'Aucun parcours enregistré.',noLogs:'Aucun journal d\'exécution.',confirmDelete:'Supprimer définitivement ce parcours ?',flowPreview:'Aperçu du flux',stepTrigger:'Déclencheur',stepDelay:'Attente',stepAction:'Action',stepEnd:'Fin',byTrigger:'Par déclencheur',byChannel:'Par canal',completionRate:'Tendance du taux d\'achèvement',goAutoMkt:'AI Auto Marketing',goCRM:'CRM'},
  de: {title:'Journey-Builder',sub:'AI-gestützte Kundenreisen entwerfen, ausführen und analysieren',tabBuilder:'Builder',tabList:'Liste',tabLogs:'Ausführungsprotokolle',tabAnalytics:'Analyse',createJourney:'Journey erstellen',journeyName:'Journey-Name',triggerType:'Auslöser-Typ',triggerSignup:'Registrierung',triggerPurchase:'Kauf abgeschlossen',triggerAbandon:'Warenkorbabbruch',triggerChurn:'Abwanderungsrisiko',triggerSegment:'Segmenteintritt',triggerManual:'Manuell',targetSegment:'Zielsegment',channels:'Kanäle',email:'E-Mail',kakao:'Kakao',sms:'SMS',push:'Push',line:'LINE',delayLabel:'Verzögerung',delayNone:'Sofort',delay1h:'1 Stunde',delay1d:'1 Tag',delay3d:'3 Tage',delay7d:'7 Tage',save:'Speichern',cancel:'Abbrechen',run:'Ausführen',edit:'Bearbeiten',delete:'Löschen',duplicate:'Duplizieren',close:'Schließen',statusDraft:'Entwurf',statusActive:'Aktiv',statusPaused:'Pausiert',statusCompleted:'Abgeschlossen',totalJourneys:'Gesamt Journeys',activeJourneys:'Aktive Journeys',totalExecutions:'Gesamtausführungen',totalEntered:'Gesamt eingetreten',totalCompleted:'Gesamt abgeschlossen',avgCompletion:'Ø Abschlussrate',totalEmails:'E-Mails gesendet',totalKakao:'Kakao gesendet',totalRevenue:'Gesamtumsatz',recentLogs:'Aktuelle Trigger-Protokolle',executionHistory:'Ausführungsverlauf',noData:'Keine Journeys vorhanden.',noLogs:'Keine Ausführungsprotokolle.',confirmDelete:'Diese Journey unwiderruflich löschen?',flowPreview:'Flussvorschau',stepTrigger:'Auslöser',stepDelay:'Warten',stepAction:'Aktion',stepEnd:'Ende',byTrigger:'Nach Auslöser',byChannel:'Nach Kanal',completionRate:'Abschlussrate-Trend',goAutoMkt:'AI Auto Marketing',goCRM:'CRM'},
  pt: {title:'Construtor de Jornadas',sub:'Projete, execute e analise jornadas automatizadas do cliente com IA',tabBuilder:'Construtor',tabList:'Lista',tabLogs:'Logs de Execução',tabAnalytics:'Análise',createJourney:'Criar Jornada',journeyName:'Nome da Jornada',triggerType:'Tipo de Gatilho',triggerSignup:'Cadastro',triggerPurchase:'Compra Concluída',triggerAbandon:'Carrinho Abandonado',triggerChurn:'Risco de Churn',triggerSegment:'Entrada no Segmento',triggerManual:'Manual',targetSegment:'Segmento Alvo',channels:'Canais',email:'E-mail',kakao:'Kakao',sms:'SMS',push:'Push',line:'LINE',delayLabel:'Atraso',delayNone:'Imediato',delay1h:'1 Hora',delay1d:'1 Dia',delay3d:'3 Dias',delay7d:'7 Dias',save:'Salvar',cancel:'Cancelar',run:'Executar',edit:'Editar',delete:'Excluir',duplicate:'Duplicar',close:'Fechar',statusDraft:'Rascunho',statusActive:'Ativo',statusPaused:'Pausado',statusCompleted:'Concluído',totalJourneys:'Total de Jornadas',activeJourneys:'Jornadas Ativas',totalExecutions:'Total de Execuções',totalEntered:'Total de Entradas',totalCompleted:'Total Concluídos',avgCompletion:'Taxa Média de Conclusão',totalEmails:'E-mails Enviados',totalKakao:'Kakao Enviados',totalRevenue:'Receita Total',recentLogs:'Logs Recentes',executionHistory:'Histórico de Execução',noData:'Nenhuma jornada registrada.',noLogs:'Nenhum log de execução.',confirmDelete:'Excluir esta jornada permanentemente?',flowPreview:'Pré-visualização do Fluxo',stepTrigger:'Gatilho',stepDelay:'Espera',stepAction:'Ação',stepEnd:'Fim',byTrigger:'Por Gatilho',byChannel:'Por Canal',completionRate:'Tendência de Conclusão',goAutoMkt:'AI Auto Marketing',goCRM:'CRM'},
  ru: {title:'Конструктор путей клиента',sub:'Проектирование, запуск и анализ автоматизированных клиентских путей на основе ИИ',tabBuilder:'Конструктор',tabList:'Список',tabLogs:'Журнал выполнения',tabAnalytics:'Аналитика',createJourney:'Создать путь',journeyName:'Название пути',triggerType:'Тип триггера',triggerSignup:'Регистрация',triggerPurchase:'Покупка совершена',triggerAbandon:'Брошенная корзина',triggerChurn:'Риск оттока',triggerSegment:'Вход в сегмент',triggerManual:'Вручную',targetSegment:'Целевой сегмент',channels:'Каналы',email:'Email',kakao:'Kakao',sms:'SMS',push:'Push',line:'LINE',delayLabel:'Задержка',delayNone:'Сразу',delay1h:'1 час',delay1d:'1 день',delay3d:'3 дня',delay7d:'7 дней',save:'Сохранить',cancel:'Отмена',run:'Запустить',edit:'Редактировать',delete:'Удалить',duplicate:'Дублировать',close:'Закрыть',statusDraft:'Черновик',statusActive:'Активен',statusPaused:'На паузе',statusCompleted:'Завершён',totalJourneys:'Всего путей',activeJourneys:'Активных путей',totalExecutions:'Всего запусков',totalEntered:'Всего вошедших',totalCompleted:'Всего завершивших',avgCompletion:'Средняя завершаемость',totalEmails:'Email отправлено',totalKakao:'Kakao отправлено',totalRevenue:'Общий доход',recentLogs:'Последние триггеры',executionHistory:'История выполнения',noData:'Нет зарегистрированных путей.',noLogs:'Нет журналов выполнения.',confirmDelete:'Удалить этот путь безвозвратно?',flowPreview:'Предварительный просмотр',stepTrigger:'Триггер',stepDelay:'Ожидание',stepAction:'Действие',stepEnd:'Конец',byTrigger:'По триггерам',byChannel:'По каналам',completionRate:'Динамика завершаемости',goAutoMkt:'AI Автомаркетинг',goCRM:'CRM'},
  ar: {title:'منشئ رحلة العميل',sub:'تصميم وتنفيذ وتحليل رحلات العملاء الآلية بالذكاء الاصطناعي',tabBuilder:'المنشئ',tabList:'القائمة',tabLogs:'سجلات التنفيذ',tabAnalytics:'التحليلات',createJourney:'إنشاء رحلة',journeyName:'اسم الرحلة',triggerType:'نوع المُشغّل',triggerSignup:'تسجيل',triggerPurchase:'اكتمال الشراء',triggerAbandon:'سلة مهجورة',triggerChurn:'خطر الانسحاب',triggerSegment:'دخول الشريحة',triggerManual:'يدوي',targetSegment:'الشريحة المستهدفة',channels:'القنوات',email:'البريد الإلكتروني',kakao:'كاكاو',sms:'رسائل نصية',push:'إشعارات',line:'LINE',delayLabel:'التأخير',delayNone:'فوري',delay1h:'ساعة واحدة',delay1d:'يوم واحد',delay3d:'3 أيام',delay7d:'7 أيام',save:'حفظ',cancel:'إلغاء',run:'تشغيل',edit:'تعديل',delete:'حذف',duplicate:'نسخ',close:'إغلاق',statusDraft:'مسودة',statusActive:'نشط',statusPaused:'متوقف مؤقتاً',statusCompleted:'مكتمل',totalJourneys:'إجمالي الرحلات',activeJourneys:'الرحلات النشطة',totalExecutions:'إجمالي التنفيذات',totalEntered:'إجمالي الداخلين',totalCompleted:'إجمالي المكتملين',avgCompletion:'متوسط الإكمال',totalEmails:'رسائل بريد مرسلة',totalKakao:'رسائل كاكاو مرسلة',totalRevenue:'إجمالي الإيرادات',recentLogs:'سجلات المُشغّلات الأخيرة',executionHistory:'سجل التنفيذ',noData:'لا توجد رحلات مسجلة.',noLogs:'لا توجد سجلات تنفيذ.',confirmDelete:'هل تريد حذف هذه الرحلة نهائياً؟',flowPreview:'معاينة التدفق',stepTrigger:'مُشغّل',stepDelay:'انتظار',stepAction:'إجراء',stepEnd:'نهاية',byTrigger:'حسب المُشغّل',byChannel:'حسب القناة',completionRate:'اتجاه معدل الإكمال',goAutoMkt:'التسويق الآلي',goCRM:'CRM',dir:'rtl'},
  vi: {title:'Xây dựng hành trình khách hàng',sub:'Thiết kế, thực thi và phân tích hành trình khách hàng tự động bằng AI',tabBuilder:'Xây dựng',tabList:'Danh sách',tabLogs:'Nhật ký',tabAnalytics:'Phân tích',createJourney:'Tạo hành trình',journeyName:'Tên hành trình',triggerType:'Loại kích hoạt',triggerSignup:'Đăng ký',triggerPurchase:'Hoàn tất mua hàng',triggerAbandon:'Bỏ giỏ hàng',triggerChurn:'Nguy cơ rời bỏ',triggerSegment:'Vào phân khúc',triggerManual:'Thủ công',targetSegment:'Phân khúc mục tiêu',channels:'Kênh',email:'Email',kakao:'Kakao',sms:'SMS',push:'Thông báo đẩy',line:'LINE',delayLabel:'Thời gian chờ',delayNone:'Ngay lập tức',delay1h:'1 giờ',delay1d:'1 ngày',delay3d:'3 ngày',delay7d:'7 ngày',save:'Lưu',cancel:'Hủy',run:'Chạy',edit:'Sửa',delete:'Xóa',duplicate:'Nhân bản',close:'Đóng',statusDraft:'Nháp',statusActive:'Hoạt động',statusPaused:'Tạm dừng',statusCompleted:'Hoàn thành',totalJourneys:'Tổng hành trình',activeJourneys:'Đang hoạt động',totalExecutions:'Tổng lần chạy',totalEntered:'Tổng đã vào',totalCompleted:'Tổng hoàn thành',avgCompletion:'Tỷ lệ hoàn thành TB',totalEmails:'Email đã gửi',totalKakao:'Kakao đã gửi',totalRevenue:'Tổng doanh thu',recentLogs:'Nhật ký gần đây',executionHistory:'Lịch sử thực thi',noData:'Chưa có hành trình nào.',noLogs:'Chưa có nhật ký thực thi.',confirmDelete:'Xóa vĩnh viễn hành trình này?',flowPreview:'Xem trước luồng',stepTrigger:'Kích hoạt',stepDelay:'Chờ',stepAction:'Hành động',stepEnd:'Kết thúc',byTrigger:'Theo kích hoạt',byChannel:'Theo kênh',completionRate:'Xu hướng hoàn thành',goAutoMkt:'AI Auto Marketing',goCRM:'CRM'},
  th: {title:'ตัวสร้างเส้นทางลูกค้า',sub:'ออกแบบ ดำเนินการ และวิเคราะห์เส้นทางลูกค้าอัตโนมัติด้วย AI',tabBuilder:'ตัวสร้าง',tabList:'รายการ',tabLogs:'บันทึกการทำงาน',tabAnalytics:'วิเคราะห์',createJourney:'สร้างเส้นทาง',journeyName:'ชื่อเส้นทาง',triggerType:'ประเภททริกเกอร์',triggerSignup:'สมัครสมาชิก',triggerPurchase:'ซื้อเสร็จสมบูรณ์',triggerAbandon:'ละทิ้งรถเข็น',triggerChurn:'ความเสี่ยงการสูญเสีย',triggerSegment:'เข้าเซ็กเมนต์',triggerManual:'ด้วยตนเอง',targetSegment:'เซ็กเมนต์เป้าหมาย',channels:'ช่องทาง',email:'อีเมล',kakao:'Kakao',sms:'SMS',push:'Push',line:'LINE',delayLabel:'เวลารอ',delayNone:'ทันที',delay1h:'1 ชั่วโมง',delay1d:'1 วัน',delay3d:'3 วัน',delay7d:'7 วัน',save:'บันทึก',cancel:'ยกเลิก',run:'เรียกใช้',edit:'แก้ไข',delete:'ลบ',duplicate:'สำเนา',close:'ปิด',statusDraft:'แบบร่าง',statusActive:'ใช้งานอยู่',statusPaused:'หยุดชั่วคราว',statusCompleted:'เสร็จสิ้น',totalJourneys:'เส้นทางทั้งหมด',activeJourneys:'ใช้งานอยู่',totalExecutions:'การทำงานทั้งหมด',totalEntered:'เข้าทั้งหมด',totalCompleted:'เสร็จทั้งหมด',avgCompletion:'อัตราเสร็จเฉลี่ย',totalEmails:'อีเมลที่ส่ง',totalKakao:'Kakao ที่ส่ง',totalRevenue:'รายได้รวม',recentLogs:'บันทึกล่าสุด',executionHistory:'ประวัติการทำงาน',noData:'ยังไม่มีเส้นทาง',noLogs:'ยังไม่มีบันทึก',confirmDelete:'ลบเส้นทางนี้ถาวร?',flowPreview:'ดูตัวอย่างโฟลว์',stepTrigger:'ทริกเกอร์',stepDelay:'รอ',stepAction:'การดำเนินการ',stepEnd:'สิ้นสุด',byTrigger:'ตามทริกเกอร์',byChannel:'ตามช่องทาง',completionRate:'แนวโน้มอัตราเสร็จ',goAutoMkt:'AI Auto Marketing',goCRM:'CRM'},
  id: {title:'Pembuat Perjalanan Pelanggan',sub:'Rancang, jalankan, dan analisis perjalanan pelanggan otomatis dengan AI',tabBuilder:'Pembuat',tabList:'Daftar',tabLogs:'Log Eksekusi',tabAnalytics:'Analitik',createJourney:'Buat Perjalanan',journeyName:'Nama Perjalanan',triggerType:'Jenis Pemicu',triggerSignup:'Pendaftaran',triggerPurchase:'Pembelian Selesai',triggerAbandon:'Keranjang Ditinggalkan',triggerChurn:'Risiko Churn',triggerSegment:'Masuk Segmen',triggerManual:'Manual',targetSegment:'Segmen Target',channels:'Saluran',email:'Email',kakao:'Kakao',sms:'SMS',push:'Push',line:'LINE',delayLabel:'Penundaan',delayNone:'Segera',delay1h:'1 Jam',delay1d:'1 Hari',delay3d:'3 Hari',delay7d:'7 Hari',save:'Simpan',cancel:'Batal',run:'Jalankan',edit:'Edit',delete:'Hapus',duplicate:'Duplikat',close:'Tutup',statusDraft:'Draf',statusActive:'Aktif',statusPaused:'Dijeda',statusCompleted:'Selesai',totalJourneys:'Total Perjalanan',activeJourneys:'Perjalanan Aktif',totalExecutions:'Total Eksekusi',totalEntered:'Total Masuk',totalCompleted:'Total Selesai',avgCompletion:'Rata-rata Penyelesaian',totalEmails:'Email Terkirim',totalKakao:'Kakao Terkirim',totalRevenue:'Total Pendapatan',recentLogs:'Log Pemicu Terbaru',executionHistory:'Riwayat Eksekusi',noData:'Belum ada perjalanan.',noLogs:'Belum ada log eksekusi.',confirmDelete:'Hapus perjalanan ini secara permanen?',flowPreview:'Pratinjau Alur',stepTrigger:'Pemicu',stepDelay:'Tunggu',stepAction:'Aksi',stepEnd:'Akhir',byTrigger:'Per Pemicu',byChannel:'Per Saluran',completionRate:'Tren Penyelesaian',goAutoMkt:'AI Auto Marketing',goCRM:'CRM'},
  hi: {title:'ग्राहक यात्रा बिल्डर',sub:'AI-संचालित स्वचालित ग्राहक यात्रा डिज़ाइन, निष्पादन और विश्लेषण',tabBuilder:'बिल्डर',tabList:'सूची',tabLogs:'निष्पादन लॉग',tabAnalytics:'विश्लेषण',createJourney:'यात्रा बनाएं',journeyName:'यात्रा का नाम',triggerType:'ट्रिगर प्रकार',triggerSignup:'साइन अप',triggerPurchase:'खरीदारी पूरी',triggerAbandon:'कार्ट परित्याग',triggerChurn:'छोड़ने का जोखिम',triggerSegment:'सेगमेंट प्रवेश',triggerManual:'मैनुअल',targetSegment:'लक्ष्य सेगमेंट',channels:'चैनल',email:'ईमेल',kakao:'काकाओ',sms:'SMS',push:'पुश',line:'LINE',delayLabel:'विलंब',delayNone:'तुरंत',delay1h:'1 घंटा',delay1d:'1 दिन',delay3d:'3 दिन',delay7d:'7 दिन',save:'सहेजें',cancel:'रद्द करें',run:'चलाएं',edit:'संपादित करें',delete:'हटाएं',duplicate:'डुप्लिकेट',close:'बंद करें',statusDraft:'ड्राफ्ट',statusActive:'सक्रिय',statusPaused:'रुका हुआ',statusCompleted:'पूर्ण',totalJourneys:'कुल यात्राएं',activeJourneys:'सक्रिय यात्राएं',totalExecutions:'कुल निष्पादन',totalEntered:'कुल प्रवेश',totalCompleted:'कुल पूर्ण',avgCompletion:'औसत पूर्णता',totalEmails:'ईमेल भेजे गए',totalKakao:'काकाओ भेजे गए',totalRevenue:'कुल राजस्व',recentLogs:'हालिया ट्रिगर लॉग',executionHistory:'निष्पादन इतिहास',noData:'कोई यात्रा पंजीकृत नहीं है।',noLogs:'कोई निष्पादन लॉग नहीं।',confirmDelete:'इस यात्रा को स्थायी रूप से हटाएं?',flowPreview:'फ़्लो पूर्वावलोकन',stepTrigger:'ट्रिगर',stepDelay:'प्रतीक्षा',stepAction:'कार्रवाई',stepEnd:'अंत',byTrigger:'ट्रिगर अनुसार',byChannel:'चैनल अनुसार',completionRate:'पूर्णता दर रुझान',goAutoMkt:'AI ऑटो मार्केटिंग',goCRM:'CRM'},
};

// ═══════════════════════════════════════════════════════════
// Process each locale file
// ═══════════════════════════════════════════════════════════
const langCodes = ['ko','en','ja','zh','zh-TW','es','fr','de','pt','ru','ar','vi','th','id','hi'];

let successCount = 0;
let errorCount = 0;

for (const code of langCodes) {
  const fileName = code + '.js';
  const filePath = path.join(LOCALES_DIR, fileName);
  
  if (!fs.existsSync(filePath)) {
    console.log(`⚠️ SKIP: ${fileName} not found`);
    errorCount++;
    continue;
  }

  try {
    let content = fs.readFileSync(filePath, 'utf-8');
    
    // Parse the JSON from the file (format: export default {...})
    const jsonMatch = content.match(/export\s+default\s+(\{[\s\S]*\})\s*;?\s*$/);
    if (!jsonMatch) {
      console.log(`⚠️ SKIP: ${fileName} - cannot parse`);
      errorCount++;
      continue;
    }

    let obj;
    try {
      obj = JSON.parse(jsonMatch[1]);
    } catch (e) {
      // Try eval for possible trailing commas etc.
      obj = (new Function('return ' + jsonMatch[1]))();
    }

    // Inject campMgr keys
    const cCode = code === 'zh-TW' ? 'zh-TW' : code;
    const cmKeys = campMgr[cCode] || campMgr['en']; // fallback to en
    if (!obj.campMgr) obj.campMgr = {};
    Object.assign(obj.campMgr, cmKeys);

    // Inject jb keys
    const jbKeys = jb[cCode] || jb['en'];
    if (!obj.jb) obj.jb = {};
    Object.assign(obj.jb, jbKeys);

    // Write back
    const newContent = 'export default ' + JSON.stringify(obj) + ';\n';
    fs.writeFileSync(filePath, newContent, 'utf-8');
    
    const cmCount = Object.keys(cmKeys).length;
    const jbCount = Object.keys(jbKeys).length;
    console.log(`✅ ${fileName}: +${cmCount} campMgr keys, +${jbCount} jb keys`);
    successCount++;
  } catch (e) {
    console.log(`❌ ERROR: ${fileName} - ${e.message}`);
    errorCount++;
  }
}

console.log(`\n═══ Done: ${successCount} success, ${errorCount} errors ═══`);
