const fs = require('fs');
const path = require('path');
const LOCALES_DIR = path.join(__dirname, 'src/i18n/locales');
const LOCALE_FILES = ['ko','en','ja','zh','zh-TW','de','th','vi','id'];

const guideKeys = {
  ko: {
    tabGuide:"📖 이용 가이드",
    guideTitle:"AI 오토 마케팅 이용 가이드", guideSub:"AI 기반 예산 배분, 채널 추천, 크리에이티브 생성까지 마케팅 자동화의 모든 것을 안내합니다.", guideStartBtn:"지금 바로 시작하기",
    guideStepsTitle:"마케팅 자동화 6단계",
    guideStep1Title:"예산 설정", guideStep1Desc:"월간 광고 예산을 설정합니다. 프리셋 버튼 또는 직접 입력으로 빠르게 설정할 수 있습니다.",
    guideStep2Title:"카테고리 선택", guideStep2Desc:"뷰티, 패션, 전자기기 등 상품 카테고리를 선택하면 AI가 최적 채널을 추천합니다.",
    guideStep3Title:"채널 자동 추천", guideStep3Desc:"카테고리와 예산에 맞는 광고 채널을 AI가 자동으로 추천합니다. 수동 변경도 가능합니다.",
    guideStep4Title:"AI 시뮬레이션", guideStep4Desc:"생성 버튼을 클릭하면 예상 노출수, 클릭수, 전환수, ROAS를 시뮬레이션합니다.",
    guideStep5Title:"예산 배분 조정", guideStep5Desc:"프리뷰 탭에서 채널별 예산 배분을 슬라이더로 세밀하게 조정할 수 있습니다.",
    guideStep6Title:"캠페인 제출", guideStep6Desc:"최종 확인 후 관리자 승인을 거쳐 캠페인을 실행합니다. 캠페인 매니저에서 추적 가능합니다.",
    guideTabsTitle:"탭별 상세 안내",
    guideTabCreativeName:"크리에이티브 스튜디오", guideTabCreativeDesc:"AI가 카테고리에 맞는 광고 소재(텍스트, 이미지, 비디오)를 자동 생성합니다. 생성된 소재를 캠페인 설정에 바로 적용할 수 있습니다.",
    guideTabSetupName:"캠페인 설정", guideTabSetupDesc:"예산, 카테고리, 광고 채널을 설정하고 AI 추천을 받습니다. 연동허브에서 API 키를 등록하면 더 많은 채널을 사용할 수 있습니다.",
    guideTabPreviewName:"AI 시뮬레이션 결과", guideTabPreviewDesc:"채널별 예산 배분, 예상 노출/클릭/전환수, ROAS를 미리보기합니다. 배분 비율 조정 후 캠페인을 제출합니다.",
    guideTipsTitle:"유용한 팁",
    guideTip1:"카테고리를 선택하면 AI가 자동으로 최적 채널을 추천합니다. 수동으로 변경하면 AI 추천이 해제됩니다.",
    guideTip2:"연동허브에서 API 키를 등록하면 해당 채널이 자동으로 활성화됩니다.",
    guideTip3:"크리에이티브 스튜디오에서 생성한 소재는 캠페인 설정에 자동 연동됩니다.",
    guideTip4:"프리뷰 탭에서 채널별 배분 금액을 조정하면 ROAS 예측이 실시간 갱신됩니다.",
    guideTip5:"제출된 캠페인은 캠페인 매니저에서 승인 상태를 추적하고 성과를 모니터링할 수 있습니다.",
  },
  en: {
    tabGuide:"📖 Guide",
    guideTitle:"AI Auto Marketing Guide", guideSub:"Learn how to automate marketing with AI-powered budget allocation, channel recommendations, and creative generation.", guideStartBtn:"Get Started Now",
    guideStepsTitle:"6 Steps to Automate Marketing",
    guideStep1Title:"Set Budget", guideStep1Desc:"Set your monthly ad budget using preset buttons or direct input.",
    guideStep2Title:"Select Category", guideStep2Desc:"Choose product categories like beauty, fashion, electronics and AI will recommend optimal channels.",
    guideStep3Title:"AI Channel Recommendation", guideStep3Desc:"AI automatically recommends ad channels based on your category and budget. Manual changes are also supported.",
    guideStep4Title:"AI Simulation", guideStep4Desc:"Click generate to simulate estimated impressions, clicks, conversions, and ROAS.",
    guideStep5Title:"Adjust Allocation", guideStep5Desc:"Fine-tune channel budget allocation with sliders in the Preview tab.",
    guideStep6Title:"Submit Campaign", guideStep6Desc:"After final review, submit for manager approval to launch. Track in Campaign Manager.",
    guideTabsTitle:"Tab-by-Tab Guide",
    guideTabCreativeName:"Creative Studio", guideTabCreativeDesc:"AI generates ad creatives (text, image, video) for your categories. Apply generated assets directly to campaign settings.",
    guideTabSetupName:"Campaign Setup", guideTabSetupDesc:"Configure budget, categories, and ad channels with AI recommendations. Register API keys in Integration Hub for more channels.",
    guideTabPreviewName:"AI Simulation Results", guideTabPreviewDesc:"Preview channel budget allocation, estimated metrics, and ROAS. Adjust ratios before submitting the campaign.",
    guideTipsTitle:"Useful Tips",
    guideTip1:"Selecting categories triggers automatic AI channel recommendations. Manual changes disable AI mode.",
    guideTip2:"Register API keys in Integration Hub to automatically activate channels.",
    guideTip3:"Creatives from Studio are auto-synced to campaign settings.",
    guideTip4:"Adjusting channel allocation in Preview updates ROAS predictions in real-time.",
    guideTip5:"Track approval status and monitor performance in Campaign Manager.",
  },
  ja: {
    tabGuide:"📖 ガイド",
    guideTitle:"AI自動マーケティングガイド", guideSub:"AI予算配分、チャネル推薦、クリエイティブ生成の使い方をご案内します。", guideStartBtn:"今すぐ開始",
    guideStepsTitle:"マーケティング自動化6ステップ",
    guideStep1Title:"予算設定", guideStep1Desc:"月間広告予算を設定します。",
    guideStep2Title:"カテゴリ選択", guideStep2Desc:"商品カテゴリを選択するとAIが最適チャネルを推薦します。",
    guideStep3Title:"AIチャネル推薦", guideStep3Desc:"カテゴリと予算に基づいてAIがチャネルを自動推薦します。",
    guideStep4Title:"AIシミュレーション", guideStep4Desc:"予想インプレッション、クリック、コンバージョン、ROASをシミュレーション。",
    guideStep5Title:"配分調整", guideStep5Desc:"プレビュータブでチャネル別予算配分を調整できます。",
    guideStep6Title:"キャンペーン提出", guideStep6Desc:"確認後、管理者承認を経てキャンペーンを実行します。",
    guideTabsTitle:"タブ別ガイド",
    guideTabCreativeName:"クリエイティブスタジオ", guideTabCreativeDesc:"AIがカテゴリに合った広告素材を自動生成します。",
    guideTabSetupName:"キャンペーン設定", guideTabSetupDesc:"予算、カテゴリ、広告チャネルを設定しAI推薦を受けます。",
    guideTabPreviewName:"シミュレーション結果", guideTabPreviewDesc:"チャネル別予算配分と予想指標をプレビューします。",
    guideTipsTitle:"役立つヒント",
    guideTip1:"カテゴリ選択でAIが自動チャネル推薦します。",guideTip2:"連携ハブでAPIキーを登録するとチャネルが有効化されます。",guideTip3:"スタジオの素材はキャンペーン設定に自動連携されます。",guideTip4:"配分調整でROAS予測がリアルタイム更新されます。",guideTip5:"キャンペーンマネージャーで承認状況と成果を追跡できます。",
  },
  zh: {
    tabGuide:"📖 使用指南",
    guideTitle:"AI自动营销指南", guideSub:"了解AI预算分配、渠道推荐和创意素材生成的使用方法。", guideStartBtn:"立即开始",
    guideStepsTitle:"营销自动化6步",
    guideStep1Title:"设置预算", guideStep1Desc:"设置月度广告预算。",
    guideStep2Title:"选择类别", guideStep2Desc:"选择商品类别后AI推荐最优渠道。",
    guideStep3Title:"AI渠道推荐", guideStep3Desc:"AI根据类别和预算自动推荐渠道。",
    guideStep4Title:"AI模拟", guideStep4Desc:"模拟预估曝光量、点击量、转化量和ROAS。",
    guideStep5Title:"调整分配", guideStep5Desc:"在预览中调整渠道预算分配。",
    guideStep6Title:"提交广告活动", guideStep6Desc:"确认后提交管理员审批。",
    guideTabsTitle:"标签页说明",
    guideTabCreativeName:"创意工作室", guideTabCreativeDesc:"AI自动生成广告素材。",
    guideTabSetupName:"活动设置", guideTabSetupDesc:"设置预算、类别和渠道。",
    guideTabPreviewName:"模拟结果", guideTabPreviewDesc:"预览渠道分配和预估指标。",
    guideTipsTitle:"实用技巧",
    guideTip1:"选择类别会触发AI自动推荐。",guideTip2:"注册API密钥自动激活渠道。",guideTip3:"工作室素材自动同步到设置。",guideTip4:"调整分配实时更新ROAS。",guideTip5:"在活动管理器中跟踪状态。",
  },
  "zh-TW": {
    tabGuide:"📖 使用指南",
    guideTitle:"AI自動行銷指南", guideSub:"了解AI預算分配、通路推薦和創意素材的使用方法。", guideStartBtn:"立即開始",
    guideStepsTitle:"行銷自動化6步",
    guideStep1Title:"設定預算", guideStep1Desc:"設定月度廣告預算。",
    guideStep2Title:"選擇類別", guideStep2Desc:"選擇商品類別後AI推薦最佳通路。",
    guideStep3Title:"AI通路推薦", guideStep3Desc:"AI根據類別和預算自動推薦。",
    guideStep4Title:"AI模擬", guideStep4Desc:"模擬預估曝光、點擊、轉換和ROAS。",
    guideStep5Title:"調整分配", guideStep5Desc:"在預覽中調整通路預算分配。",
    guideStep6Title:"提交廣告活動", guideStep6Desc:"確認後提交管理員審批。",
    guideTabsTitle:"標籤頁說明",
    guideTabCreativeName:"創意工作室", guideTabCreativeDesc:"AI自動生成廣告素材。",
    guideTabSetupName:"活動設定", guideTabSetupDesc:"設定預算、類別和通路。",
    guideTabPreviewName:"模擬結果", guideTabPreviewDesc:"預覽通路分配和預估指標。",
    guideTipsTitle:"實用技巧",
    guideTip1:"選擇類別觸發AI推薦。",guideTip2:"註冊API金鑰自動啟用通路。",guideTip3:"工作室素材自動同步。",guideTip4:"調整分配即時更新ROAS。",guideTip5:"在活動管理器追蹤狀態。",
  },
  de: {
    tabGuide:"📖 Anleitung",
    guideTitle:"AI Auto-Marketing Anleitung", guideSub:"Erfahren Sie, wie AI Budgetverteilung und Kanalempfehlungen automatisiert.", guideStartBtn:"Jetzt starten",
    guideStepsTitle:"6 Schritte zur Automatisierung",
    guideStep1Title:"Budget festlegen", guideStep1Desc:"Monatliches Werbebudget festlegen.",
    guideStep2Title:"Kategorie wahlen", guideStep2Desc:"Wahlen Sie Produktkategorien fur AI-Empfehlungen.",
    guideStep3Title:"AI-Kanalempfehlung", guideStep3Desc:"AI empfiehlt Kanale basierend auf Kategorie und Budget.",
    guideStep4Title:"AI-Simulation", guideStep4Desc:"Simulieren Sie Impressionen, Klicks und ROAS.",
    guideStep5Title:"Verteilung anpassen", guideStep5Desc:"Budgetverteilung im Vorschau-Tab anpassen.",
    guideStep6Title:"Kampagne einreichen", guideStep6Desc:"Nach Prufung zur Genehmigung einreichen.",
    guideTabsTitle:"Tab-Ubersicht",
    guideTabCreativeName:"Kreativstudio", guideTabCreativeDesc:"AI generiert Werbematerialien.",
    guideTabSetupName:"Kampagnen-Setup", guideTabSetupDesc:"Budget und Kanale konfigurieren.",
    guideTabPreviewName:"Simulationsergebnisse", guideTabPreviewDesc:"Vorschau der Verteilung.",
    guideTipsTitle:"Tipps",
    guideTip1:"Kategorieauswahl aktiviert AI-Empfehlungen.",guideTip2:"API-Schlussel registrieren fur mehr Kanale.",guideTip3:"Studio-Kreative werden automatisch synchronisiert.",guideTip4:"Verteilungsanderungen aktualisieren ROAS sofort.",guideTip5:"Kampagnenstatus im Manager verfolgen.",
  },
  th: {
    tabGuide:"📖 คู่มือ",
    guideTitle:"คู่มือ AI ออโต้มาร์เก็ตติ้ง", guideSub:"เรียนรู้การใช้ AI จัดสรรงบและแนะนำช่องทาง", guideStartBtn:"เริ่มเลย",
    guideStepsTitle:"6 ขั้นตอน",
    guideStep1Title:"ตั้งงบ", guideStep1Desc:"กำหนดงบโฆษณารายเดือน",
    guideStep2Title:"เลือกหมวด", guideStep2Desc:"เลือกหมวดสินค้าเพื่อรับคำแนะนำ",
    guideStep3Title:"AI แนะนำช่องทาง", guideStep3Desc:"AI แนะนำช่องทางจากหมวดและงบ",
    guideStep4Title:"จำลอง AI", guideStep4Desc:"จำลองผลลัพธ์ที่คาดการณ์",
    guideStep5Title:"ปรับการกระจาย", guideStep5Desc:"ปรับงบต่อช่องทาง",
    guideStep6Title:"ส่งแคมเปญ", guideStep6Desc:"ส่งเพื่อขออนุมัติ",
    guideTabsTitle:"คำอธิบายแท็บ",
    guideTabCreativeName:"สตูดิโอ", guideTabCreativeDesc:"AI สร้างสื่อโฆษณาอัตโนมัติ",
    guideTabSetupName:"ตั้งค่า", guideTabSetupDesc:"ตั้งงบ หมวด ช่องทาง",
    guideTabPreviewName:"ผลจำลอง", guideTabPreviewDesc:"ดูตัวอย่างผลลัพธ์",
    guideTipsTitle:"เคล็ดลับ",
    guideTip1:"เลือกหมวดเพื่อรับคำแนะนำ AI",guideTip2:"ลงทะเบียน API เพื่อเปิดช่องทาง",guideTip3:"สื่อจากสตูดิโอซิงค์อัตโนมัติ",guideTip4:"ปรับงบอัปเดต ROAS ทันที",guideTip5:"ติดตามสถานะในตัวจัดการ",
  },
  vi: {
    tabGuide:"📖 Hướng dẫn",
    guideTitle:"Hướng dẫn AI Marketing tự động", guideSub:"Tìm hiểu cách sử dụng AI phân bổ ngân sách và đề xuất kênh.", guideStartBtn:"Bắt đầu ngay",
    guideStepsTitle:"6 bước tự động hóa",
    guideStep1Title:"Đặt ngân sách", guideStep1Desc:"Đặt ngân sách quảng cáo hàng tháng.",
    guideStep2Title:"Chọn danh mục", guideStep2Desc:"Chọn danh mục sản phẩm để nhận đề xuất AI.",
    guideStep3Title:"AI đề xuất kênh", guideStep3Desc:"AI tự động đề xuất kênh phù hợp.",
    guideStep4Title:"Mô phỏng AI", guideStep4Desc:"Mô phỏng số liệu dự kiến.",
    guideStep5Title:"Điều chỉnh phân bổ", guideStep5Desc:"Điều chỉnh ngân sách mỗi kênh.",
    guideStep6Title:"Gửi chiến dịch", guideStep6Desc:"Gửi để phê duyệt.",
    guideTabsTitle:"Hướng dẫn từng tab",
    guideTabCreativeName:"Studio sáng tạo", guideTabCreativeDesc:"AI tạo tài liệu quảng cáo.",
    guideTabSetupName:"Thiết lập", guideTabSetupDesc:"Cấu hình ngân sách và kênh.",
    guideTabPreviewName:"Kết quả mô phỏng", guideTabPreviewDesc:"Xem trước phân bổ.",
    guideTipsTitle:"Mẹo hữu ích",
    guideTip1:"Chọn danh mục kích hoạt đề xuất AI.",guideTip2:"Đăng ký API để mở kênh.",guideTip3:"Tài liệu từ Studio đồng bộ tự động.",guideTip4:"Điều chỉnh phân bổ cập nhật ROAS ngay.",guideTip5:"Theo dõi trạng thái trong quản lý chiến dịch.",
  },
  id: {
    tabGuide:"📖 Panduan",
    guideTitle:"Panduan AI Auto Marketing", guideSub:"Pelajari cara menggunakan AI untuk alokasi anggaran dan rekomendasi saluran.", guideStartBtn:"Mulai Sekarang",
    guideStepsTitle:"6 Langkah Otomatisasi",
    guideStep1Title:"Atur Anggaran", guideStep1Desc:"Tetapkan anggaran iklan bulanan.",
    guideStep2Title:"Pilih Kategori", guideStep2Desc:"Pilih kategori produk untuk rekomendasi AI.",
    guideStep3Title:"Rekomendasi AI", guideStep3Desc:"AI merekomendasikan saluran berdasarkan kategori dan anggaran.",
    guideStep4Title:"Simulasi AI", guideStep4Desc:"Simulasikan metrik perkiraan.",
    guideStep5Title:"Sesuaikan Alokasi", guideStep5Desc:"Sesuaikan anggaran per saluran.",
    guideStep6Title:"Kirim Kampanye", guideStep6Desc:"Kirim untuk persetujuan.",
    guideTabsTitle:"Panduan per Tab",
    guideTabCreativeName:"Studio Kreatif", guideTabCreativeDesc:"AI menghasilkan materi iklan.",
    guideTabSetupName:"Pengaturan", guideTabSetupDesc:"Konfigurasi anggaran dan saluran.",
    guideTabPreviewName:"Hasil Simulasi", guideTabPreviewDesc:"Pratinjau alokasi.",
    guideTipsTitle:"Tips",
    guideTip1:"Pilih kategori untuk rekomendasi AI.",guideTip2:"Daftar API untuk mengaktifkan saluran.",guideTip3:"Materi dari Studio disinkronkan otomatis.",guideTip4:"Sesuaikan alokasi memperbarui ROAS langsung.",guideTip5:"Lacak status di manajer kampanye.",
  }
};

LOCALE_FILES.forEach(lang => {
  const filePath = path.join(LOCALES_DIR, `${lang}.js`);
  if (!fs.existsSync(filePath)) return;
  const raw = fs.readFileSync(filePath, 'utf8');
  const objStr = raw.replace(/^export\s+default\s+/, '').replace(/;\s*$/, '');
  try {
    const obj = JSON.parse(objStr);
    if (!obj.marketing) obj.marketing = {};
    const keys = guideKeys[lang] || guideKeys.en;
    Object.assign(obj.marketing, keys);
    fs.writeFileSync(filePath, 'export default ' + JSON.stringify(obj) + ';', 'utf8');
    console.log(`✅ [${lang}] marketing guide: ${Object.keys(keys).length} keys`);
  } catch (e) {
    console.log(`❌ [${lang}] ${e.message.substring(0, 80)}`);
  }
});
console.log('\n🎉 Marketing guide i18n complete!');
