const fs=require('fs'),p=require('path');
const dir=p.resolve(__dirname,'src/i18n/locales');
const D={
es:{dash:{achvRate:'Logro',activeCh:'Canales Activos',adRev:'Ingresos Publicitarios',adSpend:'Gasto Publicitario',ageDist:'Distribución por Edad',aiAdAnal:'🤖 Análisis IA',allChSummary:'Resumen de Canales',avgCtr:'CTR Promedio',avgDuration:'Duración Promedio',avgRoas:'ROAS Combinado',avgViewTime:'Tiempo Promedio',blendedRoas:'ROAS Combinado',bounceRate:'Tasa de Rebote',cartAdds:'Añadidos al Carrito',channelMix:'Mix de Ingresos',channelPerf:'📊 Rendimiento',chCount:'Canales Activos',chDetailTable:'Tabla de Canales',chIntelTitle:'Inteligencia de Canal',chName:'Canal',chPerfSumm:'Resumen de Rendimiento',chRoas:'ROAS por Canal',chTrend:'Tendencia de Canales',clickChannelHint:'Clic en tarjeta → análisis 5 secciones',clicks:'Clics',connectChannels:'Conecte canales de anuncios',conv2:'4. Conversión',convCount:'Conversiones',convFunnel:'Embudo de Conversión',convRate:'Tasa de Conversión',dismiss:'Descartar',engagement2:'2. Engagement',fiveSectionAnalysis:'Análisis 5 Secciones',frequency:'Frecuencia',genderDist:'Distribución Género/Edad',grossMargin:'Margen Bruto',impressions:'Impresiones',liveActivity:'Actividad en Vivo',netProfit:'Beneficio Neto',noChannelData:'Sin datos de canales',noTrendData:'Sin datos de tendencia',orders:'Pedidos',purchaseCount:'Compras',reach:'Alcance',reachAwareness:'1. Alcance',realTimeBlendedRoas:'ROAS Combinado en Tiempo Real',regDist:'Distribución Regional',rev:'Ingresos',revRoi2:'5. Ingresos & ROI',securityAlert:'Alerta de Seguridad',sessions:'Sesiones',signups:'Registros',spendDistribution:'Distribución de Gasto',threatsDetected:'amenazas detectadas',totalClicks:'Clics Totales',totalRev:'Ingresos Totales',totalSpend:'Gasto Total',traffic2:'3. Tráfico',videoViews:'Vistas de Video',vsYesterday:'vs Ayer'},dashboard:{adSpend:'Gasto Publicitario',avgOrder:'AOV',convRateLbl:'Tasa de Conversión',grossRevenue:'Ingresos Totales',netROAS:'ROAS Neto',totalOrders:'Pedidos Totales'},dashPeriod:{today:'Hoy','7d':'7 Días','14d':'14 Días','30d':'30 Días','90d':'90 Días',custom:'Personalizado',customRange:'Rango Personalizado',startDate:'Fecha Inicio',endDate:'Fecha Fin',apply:'Aplicar'}},
fr:{dash:{achvRate:'Réalisation',activeCh:'Canaux Actifs',adRev:'Revenus Publicitaires',adSpend:'Dépenses Publicitaires',ageDist:'Distribution par Âge',aiAdAnal:'🤖 Analyse IA',allChSummary:'Résumé des Canaux',avgCtr:'CTR Moyen',avgDuration:'Durée Moyenne',avgRoas:'ROAS Combiné',avgViewTime:'Temps Moyen',blendedRoas:'ROAS Combiné',bounceRate:'Taux de Rebond',cartAdds:'Ajouts Panier',channelMix:'Mix de Revenus',channelPerf:'📊 Performance',chCount:'Canaux Actifs',chDetailTable:'Tableau des Canaux',chIntelTitle:'Intelligence Canal',chName:'Canal',chPerfSumm:'Résumé Performance',chRoas:'ROAS par Canal',chTrend:'Tendance des Canaux',clickChannelHint:'Cliquez sur une carte → analyse 5 sections',clicks:'Clics',connectChannels:'Connectez les canaux publicitaires',conv2:'4. Conversion',convCount:'Conversions',convFunnel:'Entonnoir de Conversion',convRate:'Taux de Conversion',dismiss:'Ignorer',engagement2:'2. Engagement',fiveSectionAnalysis:'Analyse 5 Sections',frequency:'Fréquence',genderDist:'Distribution Genre/Âge',grossMargin:'Marge Brute',impressions:'Impressions',liveActivity:'Activité en Direct',netProfit:'Bénéfice Net',noChannelData:'Aucune donnée de canal',noTrendData:'Aucune donnée de tendance',orders:'Commandes',purchaseCount:'Achats',reach:'Portée',reachAwareness:'1. Portée',realTimeBlendedRoas:'ROAS Combiné Temps Réel',regDist:'Distribution Régionale',rev:'Revenus',revRoi2:'5. Revenus & ROI',securityAlert:'Alerte de Sécurité',sessions:'Sessions',signups:'Inscriptions',spendDistribution:'Distribution Dépenses',threatsDetected:'menaces détectées',totalClicks:'Clics Totaux',totalRev:'Revenus Totaux',totalSpend:'Dépenses Totales',traffic2:'3. Trafic',videoViews:'Vues Vidéo',vsYesterday:'vs Hier'},dashboard:{adSpend:'Dépenses Pub',avgOrder:'AOV',convRateLbl:'Taux de Conversion',grossRevenue:'Revenus Totaux',netROAS:'ROAS Net',totalOrders:'Commandes Totales'},dashPeriod:{today:"Aujourd'hui",'7d':'7 Jours','14d':'14 Jours','30d':'30 Jours','90d':'90 Jours',custom:'Personnalisé',customRange:'Plage Personnalisée',startDate:'Date Début',endDate:'Date Fin',apply:'Appliquer'}},
pt:{dash:{achvRate:'Realização',activeCh:'Canais Ativos',adRev:'Receita de Anúncios',adSpend:'Gasto com Anúncios',ageDist:'Distribuição por Idade',aiAdAnal:'🤖 Análise IA',allChSummary:'Resumo dos Canais',avgCtr:'CTR Médio',avgDuration:'Duração Média',avgRoas:'ROAS Combinado',avgViewTime:'Tempo Médio',blendedRoas:'ROAS Combinado',bounceRate:'Taxa de Rejeição',cartAdds:'Adições ao Carrinho',channelMix:'Mix de Receita',channelPerf:'📊 Desempenho',chCount:'Canais Ativos',chDetailTable:'Tabela de Canais',chIntelTitle:'Inteligência de Canal',chName:'Canal',chPerfSumm:'Resumo de Desempenho',chRoas:'ROAS por Canal',chTrend:'Tendência dos Canais',clickChannelHint:'Clique no cartão → análise 5 seções',clicks:'Cliques',connectChannels:'Conecte canais de anúncios',conv2:'4. Conversão',convCount:'Conversões',convFunnel:'Funil de Conversão',convRate:'Taxa de Conversão',dismiss:'Ignorar',engagement2:'2. Engajamento',fiveSectionAnalysis:'Análise 5 Seções',frequency:'Frequência',genderDist:'Distribuição Gênero/Idade',grossMargin:'Margem Bruta',impressions:'Impressões',liveActivity:'Atividade ao Vivo',netProfit:'Lucro Líquido',noChannelData:'Sem dados de canais',noTrendData:'Sem dados de tendência',orders:'Pedidos',purchaseCount:'Compras',reach:'Alcance',reachAwareness:'1. Alcance',realTimeBlendedRoas:'ROAS Combinado em Tempo Real',regDist:'Distribuição Regional',rev:'Receita',revRoi2:'5. Receita & ROI',securityAlert:'Alerta de Segurança',sessions:'Sessões',signups:'Cadastros',spendDistribution:'Distribuição de Gastos',threatsDetected:'ameaças detectadas',totalClicks:'Cliques Totais',totalRev:'Receita Total',totalSpend:'Gasto Total',traffic2:'3. Tráfego',videoViews:'Visualizações',vsYesterday:'vs Ontem'},dashboard:{adSpend:'Gasto com Anúncios',avgOrder:'AOV',convRateLbl:'Taxa de Conversão',grossRevenue:'Receita Total',netROAS:'ROAS Líquido',totalOrders:'Pedidos Totais'},dashPeriod:{today:'Hoje','7d':'7 Dias','14d':'14 Dias','30d':'30 Dias','90d':'90 Dias',custom:'Personalizado',customRange:'Intervalo Personalizado',startDate:'Data Início',endDate:'Data Fim',apply:'Aplicar'}},
};
function inject(lang,data){
  const fp=p.join(dir,lang+'.js');
  if(!fs.existsSync(fp))return;
  let src=fs.readFileSync(fp,'utf8'),count=0;
  for(const[ns,keys]of Object.entries(data)){
    const nsIdx=src.indexOf(`"${ns}"`);
    if(nsIdx<0){const ei=src.lastIndexOf('export default');if(ei>0){src=src.slice(0,ei)+`"${ns}":${JSON.stringify(keys,null,2)},\n`+src.slice(ei);count+=Object.keys(keys).length;}continue;}
    for(const[k,v]of Object.entries(keys)){
      const block=src.substring(nsIdx,Math.min(src.length,nsIdx+15000));
      const m=block.match(new RegExp(`"${k}"\\s*:\\s*"([^"]*)"`));
      if(m){const old=m[0],nw=`"${k}": ${JSON.stringify(v)}`;const pos=src.indexOf(old,nsIdx);if(pos>=0&&m[1]!==v){src=src.substring(0,pos)+nw+src.substring(pos+old.length);count++;}}
      else{const bi=src.indexOf('{',nsIdx);if(bi>0){src=src.substring(0,bi+1)+`\n    "${k}": ${JSON.stringify(v)},`+src.substring(bi+1);count++;}}
    }
  }
  fs.writeFileSync(fp,src,'utf8');
  console.log(`✅ ${lang}: ${count} keys`);
}
for(const[l,d]of Object.entries(D))inject(l,d);
console.log('Done!');
