const fs = require('fs');

// pricingDetail translations for each language
const PATCHES = {
  en: `  pricingDetail: {
    free_tagline:"Start Free, Explore Platform", free_headline:"Demo Experience Plan",
    free_desc:"Experience the full Geniego-ROI platform instantly upon signup.",
    free_s1:"Home Dashboard", free_s1i1:"KPI Widgets (Demo)", free_s1i2:"Quick Links", free_s1i3:"Onboarding Guide",
    free_s2:"My Team & Help", free_s2i2:"Video Tutorials", free_s2i3:"Release Notes",
    free_s3:"Subscription & Billing", free_s3i1:"View Current Plan", free_s3i2:"Upgrade Plan",
    free_l1:"No real-time data", free_l2:"No live channel integration", free_l3:"No save or download",
    growth_tagline:"Growing SMB Sellers & Brands", growth_headline:"Marketing Growth Plan",
    growth_desc:"Grow your revenue with domestic commerce channels and basic CRM automation.",
    growth_s1:"AI Marketing Automation (Core)", growth_s1i1:"AI Ad Creative Generation",
    growth_s1i2:"Campaign Setup·Manage·List·Report", growth_s1i3:"Content Calendar",
    growth_s1i4:"Budget Planner", growth_s1i5:"Alert Policy List & Logs",
    growth_s2:"Ad & Channel Analytics (Domestic)", growth_s2i1:"Ad Summary·Channel·Product Analysis",
    growth_s2i2:"ROAS Analysis", growth_s2i3:"Keyword Analysis",
    growth_s2i4:"Channel KPI (Impressions·CTR·CVR·CPA/CPC)", growth_s2i5:"ROAS Calculator",
    growth_s3:"Customer CRM (Basic)", growth_s3i1:"Customer DB·360° View·Tag Management",
    growth_s3i2:"RFM Analysis·Segment Builder·Message Send",
    growth_s3i3:"Email Campaign (Send·A/B·Performance·Schedule)",
    growth_s3i4:"Kakao Notification·FriendTalk·Stats",
    growth_s3i5:"SMS/LMS Campaign·Text Templates",
    growth_s3i6:"Exit Popup·Web Popup (Basic)",
    growth_s4:"Commerce & Logistics (Domestic)", growth_s4i1:"Coupang·Naver·Cafe24 Channel Integration",
    growth_s4i2:"Order Hub (All Orders·Claims·Returns·Shipping)",
    growth_s4i3:"Bulk Product Register·Catalog Sync·Price Rules",
    growth_s4i4:"Basic WMS (Stock·Alerts·Inbound·Outbound)",
    growth_s4i5:"Monthly Settlement·Shipping·Excel Export", growth_s4i6:"3PL Carrier List View",
    growth_s5:"Analytics & Performance", growth_s5i1:"Performance Summary·Channel·Product·Campaign",
    growth_s5i2:"P&L Overview", growth_s5i3:"AI Insight Feed", growth_s5i4:"Custom Report·Excel Export",
    growth_s6:"Settlement & Finance", growth_s6i1:"Settlement History·Channel·Excel",
    growth_s6i2:"Payment List·Excel", growth_s6i3:"Plan View·Billing History·Invoice",
    growth_s6i4:"License Activation·Status",
    growth_s7:"Channel & Data Integration (Domestic)",
    growth_s7i1:"Meta·Google·TikTok·Naver·Kakao Ad Integration",
    growth_s7i2:"Coupang Connector", growth_s7i3:"Currency Selection (KRW/USD/JPY/EUR Global)",
    growth_s8:"Team Management", growth_s8i1:"Team Member List·Invite",
    growth_s8i2:"My Activity History", growth_s8i3:"Support Ticket",
    growth_l1:"AI Forecast (Churn·LTV) — Pro+", growth_l2:"Customer Journey Builder — Pro+",
    growth_l3:"Global Channels (WhatsApp·LINE·DM) — Pro+",
    growth_l4:"AI Rule Engine — Pro+", growth_l5:"1st-Party Pixel·API Keys — Pro+",
    growth_l6:"SmartConnect ERP Integration — Pro+",
    pro_tagline:"Professional E-commerce Brands & Agencies", pro_headline:"AI Automation Plan", pro_badge:"Popular",
    pro_desc:"Growth All + AI Forecast·Journey Builder·Global Channels·Rule Engine·SmartConnect·1st-Party Pixel·Advanced BI.",
    pro_s1:"AI Forecast Engine (New)", pro_s1i1:"Churn·LTV·Purchase Probability Forecast",
    pro_s1i2:"Graph Scoring", pro_s1i3:"Next Best Action Recommendation",
    pro_s1i4:"Product Recommendation AI", pro_s1i5:"AI Ad Insights",
    pro_s1i6:"AI Segment (VIP·Churn Risk·Potential VIP Auto-classify)",
    pro_s2:"Customer Journey Builder (New)", pro_s2i1:"Journey Canvas (Drag&Drop)",
    pro_s2i2:"Trigger Setup·Action Node Management",
    pro_s2i3:"Journey Performance Stats Analysis", pro_s2i4:"A/B Test (Email·Popup)",
    pro_s3:"Global Channel All (New)", pro_s3i1:"Shopify·Amazon·LINE Ads Integration",
    pro_s3i2:"WhatsApp Broadcast·Automation",
    pro_s3i3:"Instagram DM·Facebook DM·DM Campaign",
    pro_s3i4:"LINE Message Campaign·Statistics", pro_s3i5:"Popup A/B Test·Trigger Setup",
    pro_s4:"Advanced WMS + Commerce Expansion",
    pro_s4i1:"Stock Adjustment·Location Mgmt·Barcode Integration",
    pro_s4i2:"Monthly Settlement Integration·Tax Invoice·Payment Approval",
    pro_s4i3:"3PL Add·Edit", pro_s4i4:"Collection Log Basic View",
    pro_s5:"AI Rule Engine & Automation (New)",
    pro_s5i1:"AI Policy Setup·Rule List·Test", pro_s5i2:"Alert Evaluation Model",
    pro_s5i3:"Action Preset Management", pro_s5i4:"Writeback Setup·Logs",
    pro_s5i5:"Approval Decision Automation",
    pro_s6:"Review & UGC Analytics (New)",
    pro_s6i1:"Channel Review Collection·Sentiment Analysis",
    pro_s6i2:"AI Auto-Reply Draft Generation",
    pro_s6i3:"UGC (Instagram·YouTube) Performance Analysis", pro_s6i4:"Keyword Analysis",
    pro_s7:"SmartConnect Hub (New)",
    pro_s7i1:"ERP·SCM·3PL Basic Integration Setup",
    pro_s7i2:"REST API / Webhook / SFTP Integration",
    pro_s7i3:"Field Mapping Setup", pro_s7i4:"Basic Sync Log View",
    pro_s8:"1st-Party Pixel + Data",
    pro_s8i1:"Pixel Code Install·Verification",
    pro_s8i2:"Real-time Event Stream View",
    pro_s8i3:"Attribution Analysis (Touch Model·ROAS)",
    pro_s8i4:"Event Collection·Data Schema·Mapping",
    pro_s8i5:"API Key·Webhook·OAuth Integration",
    pro_s9:"Advanced Analytics & BI",
    pro_s9i1:"Cohort Analysis", pro_s9i2:"P&L by Channel·Product·Trend",
    pro_s9i3:"Anomaly Detection·Competitor AI Analysis",
    pro_s9i4:"Influencer Performance View",
    pro_s10:"Real-time FX + Team Mgmt",
    pro_s10i1:"Real-time Exchange Rate (Global Currency)",
    pro_s10i2:"Team Activity Audit",
    pro_s10i3:"System Status·API Monitoring",
    pro_s10i4:"Batch Job Run·Reprocess",
    pro_l1:"Writeback Instant Rollback — Enterprise",
    pro_l2:"Amazon Policy·Review Mgmt — Enterprise",
    pro_l3:"Market Share·Trend AI — Enterprise",
    pro_l4:"Data Product SLA·Governance — Enterprise",
    pro_l5:"SmartConnect Partner API Bidirectional — Enterprise",
    pro_l6:"Influencer DB·Campaign Execution — Enterprise",
    pro_l7:"Audit Log Full Export — Enterprise",
    pro_l8:"Auto Report·Scheduled Send — Enterprise",
    pro_l9:"API Data Streaming Export — Enterprise",
    ent_tagline:"Large E-commerce·Agency·Group", ent_headline:"Unlimited Everything Plan", ent_badge:"Top Tier",
    ent_desc:"Pro All + Instant Rollback·Amazon Policy·Market Share·Data Governance·SmartConnect Partner API·Influencer DB·Full Audit·Auto Reports.",
    ent_s1:"Writeback Instant Rollback (New)", ent_s1i1:"Writeback Setup·Logs",
    ent_s1i2:"Instant Rollback (Immediate Error Recovery)",
    ent_s1i3:"Multi-Brand Auto Execution", ent_s1i4:"Full Rollback History View",
    ent_s2:"Amazon Advanced Operations (New)", ent_s2i1:"Amazon Account Health Monitor",
    ent_s2i2:"Policy Compliance Management", ent_s2i3:"Full Review Monitoring",
    ent_s2i4:"Listing Quality Audit",
    ent_s3:"Market Intelligence (New)", ent_s3i1:"Market Share Analysis",
    ent_s3i2:"Competitor Ad Tracking (AI)", ent_s3i3:"Trend AI Forecast Model",
    ent_s3i4:"Channel Attribution All Models", ent_s3i5:"Conversion Path Analysis",
    ent_s4:"Data Product Governance (New)",
    ent_s4i1:"Data Product Schema·Quality Metrics",
    ent_s4i2:"SLA Management·Owner Assignment",
    ent_s4i3:"API-based Data Streaming Export",
    ent_s4i4:"Event Normalization Full Mgmt",
    ent_s4i5:"OAuth Partner Management", ent_s4i6:"Advanced Data Mapping",
    ent_s5:"SmartConnect Partner API (New)",
    ent_s5i1:"Partner-level Bidirectional Real-time Integration",
    ent_s5i2:"Full Real-time Sync Logs",
    ent_s5i3:"ERP·SCM·WMS Full Integration",
    ent_s5i4:"Custom Webhook Advanced Setup",
    ent_s6:"Advanced Marketing (New)",
    ent_s6i1:"Full Influencer DB·Campaign Execution·Settlement",
    ent_s6i2:"Kakao Bizboard (Large-scale Ads)",
    ent_s6i3:"WhatsApp Advanced Setup (Channel API)",
    ent_s6i4:"LINE Channel Advanced Setup",
    ent_s6i5:"AI Segment Advanced (Custom Criteria)",
    ent_s6i6:"Competitor Review Comparison Analysis",
    ent_s7:"Operations & Governance All (New)",
    ent_s7i1:"Ops Hub Alert Send (Admin Notice)",
    ent_s7i2:"3PL Delete·Contract Management",
    ent_s7i3:"Full Audit Log·CSV Export",
    ent_s7i4:"System Monitor Alert Setup",
    ent_s7i5:"Auto Report Generate·Scheduled Send",
    ent_s7i6:"Dashboard External Share·Embed",
    ent_s8:"Pro All Included + Unlimited",
    ent_s8i1:"All Pro Plan Features Included",
    ent_s8i2:"Unlimited Accounts·Users·Team Members",
    ent_s8i3:"Priority Support SLA",
    ent_s8i4:"Dedicated Onboarding Consulting·Annual Training",
    ent_s9:"Custom & Dedicated Services",
    ent_s9i1:"Custom Dashboard Configuration",
    ent_s9i2:"Dedicated Manager Assignment",
    ent_s9i3:"Annual Contract-based Custom Discount",
    ent_s9i4:"Custom Training·Workshop",
  },
  cmpRow: {
    r1:"Home Dashboard", r2:"AI Ad Creative & Campaign Mgmt",
    r3:"AI Forecast (Churn·LTV·Purchase Prob.)",
    r4:"Customer Journey Builder", r5:"AI Segment",
    r6:"Ad & Channel Analytics (ROAS·KPI)",
    r7:"Attribution Analysis (Touch Model)", r8:"Competitor AI Analysis",
    r9:"Customer CRM (Email/Kakao/SMS)",
    r10:"Review & UGC Analytics", r11:"Commerce Channels",
    r12:"WMS (Stock·In/Out)",
    r13:"3PL Management", r14:"Amazon Advanced Operations",
    r15:"Analytics & Performance (Cohort·P&L)",
    r16:"AI Rule Engine & Automation", r17:"SmartConnect (ERP·SCM)",
    r18:"1st-Party Pixel",
    r19:"Data Pipeline & API", r20:"Data Product Governance",
    r21:"BI Reports", r22:"Currency Selection (Global)",
    r23:"Influencer Management", r24:"Ops Hub (Batch·Reprocess)",
    r25:"Audit Log", r26:"Team Management (RBAC)",
    r27:"Account Count", r28:"Support Type",
  },
  cmpVal: {
    all:"All", basic:"Basic", realtime:"Real-time", domestic_core:"Domestic Core",
    domestic:"Domestic", dom_global:"Domestic+Global", market_share:"Market Share",
    basic_auto:"Basic Auto-classify", advanced_custom:"Advanced Custom",
    conv_path_all:"Conv. Path All", trend_forecast:"Trend Forecast",
    bizboard:"Bizboard", competitor_compare:"Competitor Compare",
    location_barcode:"Location & Barcode", list_view:"List View",
    contract:"Contract", policy_review:"Policy·Review·Listing",
    cohort_pl:"Cohort·P&L All", notification_basic:"Notification Basic",
    rule_writeback:"Rule Engine·Writeback", instant_rollback:"Instant Rollback",
    partner_api:"Partner API Bidirectional", install_analysis:"Install & Analysis",
    server_side:"Server-side", domestic_ads:"Domestic Ad Integration",
    schema_quality_view:"Schema·Quality View", owner_streaming:"Owner·Streaming",
    custom_excel:"Custom·Excel", anomaly_detect:"Anomaly Detection",
    auto_scheduled_share:"Auto·Scheduled·Share", manual:"Manual",
    realtime_rate:"Real-time Rate", perf_view:"Performance View",
    campaign_settle:"Campaign·Settlement", reprocess:"Reprocess",
    notification_send:"Notification Send", own_history:"Own History",
    list_invite:"List·Invite", activity_history:"Activity History",
    rbac_role:"RBAC Role Settings", unlimited:"Unlimited",
    chat_support:"Chat Support", dedicated_manager:"Dedicated Manager",
    dedicated_sla:"Dedicated + SLA",
  },`,
  ko: `  pricingDetail: {
    free_tagline:"Free로 시작, 플랫폼 탐색", free_headline:"데모 체험 플랜",
    free_desc:"가입 즉시 Geniego-ROI 전체 플랫폼을 체험할 수 있습니다.",
    free_s1:"홈 대시보드", free_s1i1:"KPI 위젯 (데모)", free_s1i2:"퀵링크", free_s1i3:"온보딩 가이드",
    free_s2:"내 팀·도움말", free_s2i2:"영상 튜토리얼", free_s2i3:"릴리즈 노트",
    free_s3:"구독·결제", free_s3i1:"현재 플랜 확인", free_s3i2:"업그레이드 플랜",
    free_l1:"실시간 데이터 없음", free_l2:"실제 채널 연동 불가", free_l3:"저장·다운로드 불가",
    growth_tagline:"성장기 중소 셀러·브랜드", growth_headline:"마케팅 성장 플랜",
    growth_desc:"국내 주요 커머스 채널과 CRM 기본 자동화로 매출을 본격 성장시키세요.",
    growth_s1:"AI 마케팅 자동화 (핵심)", growth_s1i1:"AI 광고소재 생성",
    growth_s1i2:"캠페인 설정·관리·목록·리포트", growth_s1i3:"콘텐츠 캘린더",
    growth_s1i4:"예산 플래너", growth_s1i5:"알림 정책 목록·로그",
    growth_s2:"광고·채널 분석 (국내)", growth_s2i1:"광고 요약·채널·상품 분석",
    growth_s2i2:"ROAS 분석", growth_s2i3:"키워드 분석",
    growth_s2i4:"채널 KPI (노출·CTR·전환율·CPA/CPC)", growth_s2i5:"ROAS 계산기",
    growth_s3:"고객·CRM (기본)", growth_s3i1:"고객 DB·360° 고객뷰·태그 관리",
    growth_s3i2:"RFM 분석·세그먼트 빌더·메시지 발송",
    growth_s3i3:"이메일 캠페인 (발송·A/B·성과·예약)",
    growth_s3i4:"카카오 알림톡·친구톡 발송·통계",
    growth_s3i5:"SMS/LMS 캠페인·문자 템플릿",
    growth_s3i6:"이탈팝업·웹팝업 기본",
    growth_s4:"커머스·물류 (국내)", growth_s4i1:"쿠팡·네이버·카페24 채널 연동",
    growth_s4i2:"주문 허브 (전체 주문·클레임·반품·배송)",
    growth_s4i3:"상품 일괄 등록·카탈로그 동기화·가격 규칙",
    growth_s4i4:"기본 WMS (재고·알림·입고·출고)",
    growth_s4i5:"월별 정산·배송·엑셀 내보내기", growth_s4i6:"3PL 업체 목록 조회",
    growth_s5:"분석·성과", growth_s5i1:"성과 요약·채널·상품·캠페인",
    growth_s5i2:"P&L 손익 개요", growth_s5i3:"AI 인사이트 피드", growth_s5i4:"커스텀 리포트·엑셀",
    growth_s6:"정산·재무", growth_s6i1:"정산 내역·채널별 정산·엑셀",
    growth_s6i2:"지급 목록·엑셀", growth_s6i3:"플랜 확인·결제 이력·인보이스",
    growth_s6i4:"라이선스 활성화·현황",
    growth_s7:"채널·데이터 연동 (국내)",
    growth_s7i1:"Meta·Google·TikTok·Naver·Kakao 광고 연동",
    growth_s7i2:"쿠팡 커넥터", growth_s7i3:"통화 단위 선택 (KRW/USD/JPY/EUR 전역)",
    growth_s8:"팀 관리", growth_s8i1:"팀원 목록·초대",
    growth_s8i2:"본인 작업 이력 조회", growth_s8i3:"지원 티켓",
    growth_l1:"AI 예측(이탈·LTV) — Pro+", growth_l2:"고객 여정 빌더 — Pro+",
    growth_l3:"글로벌 채널(WhatsApp·LINE·DM) — Pro+",
    growth_l4:"AI 룰 엔진 — Pro+", growth_l5:"1st-Party 픽셀·API 키 — Pro+",
    growth_l6:"SmartConnect ERP연동 — Pro+",
    pro_tagline:"전문 이커머스 브랜드·에이전시", pro_headline:"AI 자동화 플랜", pro_badge:"인기",
    pro_desc:"Growth 전체 + AI 예측·여정 빌더·글로벌 채널·룰 엔진·SmartConnect·1st-Party 픽셀·고급 BI.",
    pro_s1:"AI 예측 엔진 (신규)", pro_s1i1:"이탈 예측·LTV 예측·구매 확률",
    pro_s1i2:"그래프 스코어링", pro_s1i3:"다음 액션 추천",
    pro_s1i4:"상품 추천 AI", pro_s1i5:"AI 광고 인사이트",
    pro_s1i6:"AI 세그먼트 (VIP·이탈위험·잠재VIP 자동 분류)",
    pro_s2:"고객 여정 빌더 (신규)", pro_s2i1:"여정 캔버스 (드래그&드롭)",
    pro_s2i2:"트리거 설정·액션 노드 관리",
    pro_s2i3:"여정 성과 통계 분석", pro_s2i4:"A/B 테스트 (이메일·팝업)",
    pro_s3:"글로벌 채널 전체 (신규)", pro_s3i1:"Shopify·Amazon·LINE Ads 연동",
    pro_s3i2:"WhatsApp 방송·자동화",
    pro_s3i3:"Instagram DM·Facebook DM·DM 캠페인",
    pro_s3i4:"LINE 메시지 캠페인·통계", pro_s3i5:"팝업 A/B 테스트·트리거 설정",
    pro_s4:"WMS 고급 + 커머스 확장",
    pro_s4i1:"재고 조정·위치 관리·바코드 통합",
    pro_s4i2:"월별 정산 통합·세금계산서 발행·지급 승인",
    pro_s4i3:"3PL 업체 추가·편집 가능", pro_s4i4:"수집 로그 기본 조회",
    pro_s5:"AI 룰 엔진·자동화 (신규)",
    pro_s5i1:"AI 정책 설정·룰 목록·테스트", pro_s5i2:"알림 평가 모델",
    pro_s5i3:"액션 프리셋 관리", pro_s5i4:"라이트백 설정·로그",
    pro_s5i5:"승인 결정 자동화",
    pro_s6:"리뷰 & UGC 분석 (신규)",
    pro_s6i1:"채널 리뷰 수집·감성 분석 (긍정/부정/중립)",
    pro_s6i2:"AI 자동 답변 초안 생성",
    pro_s6i3:"UGC (인스타·유튜브) 성과 분석", pro_s6i4:"키워드 분석",
    pro_s7:"SmartConnect 허브 (신규)",
    pro_s7i1:"ERP·SCM·3PL 기본 연동 설정",
    pro_s7i2:"REST API / Webhook / SFTP 연동",
    pro_s7i3:"필드 매핑 설정", pro_s7i4:"기본 동기화 로그 조회",
    pro_s8:"1st-Party 픽셀 + 데이터",
    pro_s8i1:"픽셀 코드 설치·설치 검증",
    pro_s8i2:"실시간 이벤트 스트림 조회",
    pro_s8i3:"기여도 분석 (터치 모델·ROAS)",
    pro_s8i4:"이벤트 수집·데이터 스키마·매핑",
    pro_s8i5:"API 키 발급·웹훅·OAuth 연동",
    pro_s9:"고급 분석·BI",
    pro_s9i1:"코호트 분석", pro_s9i2:"P&L 채널별·상품별·트렌드",
    pro_s9i3:"이상 감지·경쟁사 AI 분석", pro_s9i4:"인플루언서 성과 조회",
    pro_s10:"실시간 환율 + 팀 관리",
    pro_s10i1:"실시간 환율 자동 조회 (화폐단위 전역)",
    pro_s10i2:"팀 활동 내역 감사",
    pro_s10i3:"시스템 상태·API 모니터링",
    pro_s10i4:"배치 작업 실행·재처리",
    pro_l1:"Writeback 즉시 롤백 — Enterprise",
    pro_l2:"Amazon 정책·리뷰 관리 — Enterprise",
    pro_l3:"시장점유율·트렌드AI — Enterprise",
    pro_l4:"Data Product SLA·거버넌스 — Enterprise",
    pro_l5:"SmartConnect 파트너API 양방향 — Enterprise",
    pro_l6:"인플루언서 DB·캠페인 집행 — Enterprise",
    pro_l7:"감사 로그 전체 내보내기 — Enterprise",
    pro_l8:"자동 리포트·예약 발송 — Enterprise",
    pro_l9:"API 데이터 스트리밍 내보내기 — Enterprise",
    ent_tagline:"대형 이커머스·에이전시·그룹사", ent_headline:"전체 무제한 플랜", ent_badge:"최고사양",
    ent_desc:"Pro 전체 + 즉시 롤백·Amazon 정책관리·시장점유율·Data Product 거버넌스·SmartConnect 파트너API·인플루언서 DB·감사 전체·자동 리포트.",
    ent_s1:"Writeback 즉시 롤백 (신규)", ent_s1i1:"Writeback 설정·로그",
    ent_s1i2:"즉시 롤백 (실수 즉각 복구)",
    ent_s1i3:"멀티 브랜드 자동 집행", ent_s1i4:"롤백 이력 전체 조회",
    ent_s2:"Amazon 고급 운영 (신규)", ent_s2i1:"Amazon 계정 건전성 모니터",
    ent_s2i2:"정책 준수 관리", ent_s2i3:"리뷰 모니터링 전체",
    ent_s2i4:"리스팅 품질 감사",
    ent_s3:"시장 인텔리전스 (신규)", ent_s3i1:"시장점유율 분석",
    ent_s3i2:"경쟁사 광고 추적 (AI)", ent_s3i3:"트렌드 AI 예측 모델",
    ent_s3i4:"채널 기여도 전체 모델", ent_s3i5:"전환 경로 분석",
    ent_s4:"Data Product 거버넌스 (신규)",
    ent_s4i1:"Data Product 스키마·품질 지표",
    ent_s4i2:"SLA 관리·소유자 지정",
    ent_s4i3:"API 기반 데이터 스트리밍 내보내기",
    ent_s4i4:"이벤트 정규화 전체 관리",
    ent_s4i5:"OAuth 파트너 관리", ent_s4i6:"데이터 매핑 고급",
    ent_s5:"SmartConnect 파트너 API (신규)",
    ent_s5i1:"파트너급 양방향 실시간 연동",
    ent_s5i2:"실시간 동기화 로그 전체",
    ent_s5i3:"ERP·SCM·WMS 풀 통합",
    ent_s5i4:"커스텀 Webhook 고급 설정",
    ent_s6:"마케팅 고도화 (신규)",
    ent_s6i1:"인플루언서 DB 전체·캠페인 집행·정산",
    ent_s6i2:"카카오 비즈보드 (대형광고)",
    ent_s6i3:"WhatsApp 고급 설정 (채널 API)",
    ent_s6i4:"LINE 채널 고급 설정",
    ent_s6i5:"AI 세그먼트 고급 (커스텀 기준)",
    ent_s6i6:"경쟁사 리뷰 비교 분석",
    ent_s7:"운영·거버넌스 전체 (신규)",
    ent_s7i1:"운영 허브 알림 발송 (관리자 공지)",
    ent_s7i2:"3PL 업체 삭제·계약 관리",
    ent_s7i3:"감사 로그 전체·CSV 내보내기",
    ent_s7i4:"시스템 모니터 알림 설정",
    ent_s7i5:"자동 리포트 생성·예약 발송",
    ent_s7i6:"대시보드 외부 공유·임베드",
    ent_s8:"Pro 전체 포함 + 무제한",
    ent_s8i1:"Pro 플랜 전체 기능 포함",
    ent_s8i2:"무제한 계정·사용자·팀원",
    ent_s8i3:"우선 지원 SLA",
    ent_s8i4:"전담 온보딩 컨설팅·연간 교육",
    ent_s9:"커스텀·전담 서비스",
    ent_s9i1:"커스텀 대시보드 구성",
    ent_s9i2:"전담 매니저 배정",
    ent_s9i3:"연간 계약 기반 맞춤 할인",
    ent_s9i4:"맞춤형 교육·워크샵",
  },
  cmpRow: {
    r1:"홈 대시보드", r2:"AI 광고소재·캠페인 관리",
    r3:"AI 예측 (이탈·LTV·구매확률)",
    r4:"고객 여정 빌더", r5:"AI 세그먼트",
    r6:"광고·채널 분석 (ROAS·KPI)",
    r7:"기여도 분석 (터치모델)", r8:"경쟁사 AI 분석",
    r9:"고객·CRM (이메일/카카오/SMS)",
    r10:"리뷰 & UGC 분석", r11:"커머스 채널",
    r12:"WMS (재고·입출고)",
    r13:"3PL 관리", r14:"Amazon 고급 운영",
    r15:"분석·성과 (코호트·P&L)",
    r16:"AI 룰 엔진·자동화", r17:"SmartConnect (ERP·SCM)",
    r18:"1st-Party 픽셀",
    r19:"데이터 파이프라인·API", r20:"Data Product 거버넌스",
    r21:"BI 리포트", r22:"통화 단위 선택 (전역)",
    r23:"인플루언서 관리", r24:"운영 허브 (배치·재처리)",
    r25:"감사 로그", r26:"팀 관리 (RBAC)",
    r27:"계정 수", r28:"지원 방식",
  },
  cmpVal: {
    all:"전체", basic:"기본", realtime:"실시간", domestic_core:"국내 핵심",
    domestic:"국내", dom_global:"국내+글로벌", market_share:"시장점유율",
    basic_auto:"기본 자동분류", advanced_custom:"고급 커스텀",
    conv_path_all:"전환경로 전체", trend_forecast:"트렌드예측",
    bizboard:"비즈보드", competitor_compare:"경쟁사비교",
    location_barcode:"위치·바코드", list_view:"목록 조회",
    contract:"계약", policy_review:"정책·리뷰·리스팅",
    cohort_pl:"코호트·P&L전체", notification_basic:"알림 기본",
    rule_writeback:"룰엔진·라이트백", instant_rollback:"즉시 롤백",
    partner_api:"파트너API 양방향", install_analysis:"설치·분석",
    server_side:"서버사이드", domestic_ads:"국내 광고 연동",
    schema_quality_view:"스키마·품질 조회", owner_streaming:"소유자·스트리밍",
    custom_excel:"커스텀·엑셀", anomaly_detect:"이상감지",
    auto_scheduled_share:"자동·예약·공유", manual:"수동",
    realtime_rate:"실시간 환율", perf_view:"성과 조회",
    campaign_settle:"캠페인·정산", reprocess:"재처리",
    notification_send:"알림발송", own_history:"본인 이력",
    list_invite:"목록·초대", activity_history:"활동이력",
    rbac_role:"RBAC 역할설정", unlimited:"무제한",
    chat_support:"채팅 지원", dedicated_manager:"전담 매니저",
    dedicated_sla:"전담 + SLA",
  },`,
  ja: `  pricingDetail: {
    free_tagline:"無料で始める、プラットフォーム探索", free_headline:"デモ体験プラン",
    free_desc:"登録後すぐにGeniego-ROIの全プラットフォームを体験できます。",
    free_s1:"ホームダッシュボード", free_s1i1:"KPIウィジェット (デモ)", free_s1i2:"クイックリンク", free_s1i3:"オンボーディングガイド",
    free_s2:"マイチーム・ヘルプ", free_s2i2:"ビデオチュートリアル", free_s2i3:"リリースノート",
    free_s3:"サブスクリプション・請求", free_s3i1:"現在のプランを確認", free_s3i2:"プランをアップグレード",
    free_l1:"リアルタイムデータなし", free_l2:"実際のチャネル連携不可", free_l3:"保存・ダウンロード不可",
    growth_tagline:"成長期の中小セラー・ブランド", growth_headline:"マーケティング成長プラン",
    growth_desc:"国内主要コマースチャネルとCRM基本自動化で売上を本格的に成長させましょう。",
    growth_s1:"AIマーケティング自動化 (核心)", growth_s1i1:"AI広告クリエイティブ生成",
    growth_s1i2:"キャンペーン設定・管理・一覧・レポート", growth_s1i3:"コンテンツカレンダー",
    growth_s1i4:"予算プランナー", growth_s1i5:"通知ポリシー一覧・ログ",
    growth_s2:"広告・チャネル分析 (国内)", growth_s2i1:"広告サマリー・チャネル・商品分析",
    growth_s2i2:"ROAS分析", growth_s2i3:"キーワード分析",
    growth_s2i4:"チャネルKPI (インプレッション・CTR・CVR・CPA/CPC)", growth_s2i5:"ROAS計算機",
    growth_s3:"顧客・CRM (基本)", growth_s3i1:"顧客DB・360°ビュー・タグ管理",
    growth_s3i2:"RFM分析・セグメントビルダー・メッセージ送信",
    growth_s3i3:"メールキャンペーン (送信・A/B・成果・スケジュール)",
    growth_s3i4:"Kakao通知・友達トーク送信・統計",
    growth_s3i5:"SMS/LMSキャンペーン・テキストテンプレート",
    growth_s3i6:"離脱ポップアップ・ウェブポップアップ (基本)",
    growth_s4:"コマース・物流 (国内)", growth_s4i1:"Coupang・Naver・Cafe24チャネル連携",
    growth_s4i2:"注文ハブ (全注文・クレーム・返品・配送)",
    growth_s4i3:"商品一括登録・カタログ同期・価格ルール",
    growth_s4i4:"基本WMS (在庫・通知・入出庫)",
    growth_s4i5:"月次精算・配送・Excelエクスポート", growth_s4i6:"3PL業者一覧表示",
    growth_s5:"分析・パフォーマンス", growth_s5i1:"パフォーマンスサマリー・チャネル・商品・キャンペーン",
    growth_s5i2:"P&L概要", growth_s5i3:"AIインサイトフィード", growth_s5i4:"カスタムレポート・Excelエクスポート",
    growth_s6:"精算・財務", growth_s6i1:"精算履歴・チャネル別精算・Excel",
    growth_s6i2:"支払一覧・Excel", growth_s6i3:"プラン確認・決済履歴・請求書",
    growth_s6i4:"ライセンスアクティブ化・状況",
    growth_s7:"チャネル・データ連携 (国内)",
    growth_s7i1:"Meta・Google・TikTok・Naver・Kakao広告連携",
    growth_s7i2:"Coupangコネクター", growth_s7i3:"通貨単位選択 (KRW/USD/JPY/EUR グローバル)",
    growth_s8:"チーム管理", growth_s8i1:"チームメンバー一覧・招待",
    growth_s8i2:"自分の作業履歴確認", growth_s8i3:"サポートチケット",
    growth_l1:"AI予測 (離脱・LTV) — Pro+", growth_l2:"カスタマージャーニービルダー — Pro+",
    growth_l3:"グローバルチャネル (WhatsApp・LINE・DM) — Pro+",
    growth_l4:"AIルールエンジン — Pro+", growth_l5:"1st-Partyピクセル・APIキー — Pro+",
    growth_l6:"SmartConnect ERP連携 — Pro+",
    pro_tagline:"プロECブランド・エージェンシー", pro_headline:"AI自動化プラン", pro_badge:"人気",
    pro_desc:"Growth全て + AI予測・ジャーニービルダー・グローバルチャネル・ルールエンジン・SmartConnect・1st-Partyピクセル・高度BI。",
    pro_s1:"AI予測エンジン (新)", pro_s1i1:"離脱予測・LTV予測・購入確率",
    pro_s1i2:"グラフスコアリング", pro_s1i3:"ネクストベストアクション推奨",
    pro_s1i4:"商品推薦AI", pro_s1i5:"AI広告インサイト",
    pro_s1i6:"AIセグメント (VIP・離脱リスク・潜在VIP自動分類)",
    pro_s2:"カスタマージャーニービルダー (新)", pro_s2i1:"ジャーニーキャンバス (ドラッグ&ドロップ)",
    pro_s2i2:"トリガー設定・アクションノード管理",
    pro_s2i3:"ジャーニーパフォーマンス統計分析", pro_s2i4:"A/Bテスト (メール・ポップアップ)",
    pro_s3:"グローバルチャネル全て (新)", pro_s3i1:"Shopify・Amazon・LINE Ads連携",
    pro_s3i2:"WhatsApp放送・自動化",
    pro_s3i3:"Instagram DM・Facebook DM・DMキャンペーン",
    pro_s3i4:"LINEメッセージキャンペーン・統計", pro_s3i5:"ポップアップA/Bテスト・トリガー設定",
    pro_s4:"高度WMS + コマース拡張",
    pro_s4i1:"在庫調整・ロケーション管理・バーコード統合",
    pro_s4i2:"月次精算統合・税請求書発行・支払承認",
    pro_s4i3:"3PL業者追加・編集可能", pro_s4i4:"収集ログ基本表示",
    pro_s5:"AIルールエンジン・自動化 (新)",
    pro_s5i1:"AIポリシー設定・ルール一覧・テスト", pro_s5i2:"通知評価モデル",
    pro_s5i3:"アクションプリセット管理", pro_s5i4:"Writeback設定・ログ",
    pro_s5i5:"承認決定自動化",
    pro_s6:"レビュー & UGC分析 (新)",
    pro_s6i1:"チャネルレビュー収集・感情分析 (肯定/否定/中立)",
    pro_s6i2:"AI自動返信ドラフト生成",
    pro_s6i3:"UGC (インスタ・YouTube) パフォーマンス分析", pro_s6i4:"キーワード分析",
    pro_s7:"SmartConnectハブ (新)",
    pro_s7i1:"ERP・SCM・3PL基本連携設定",
    pro_s7i2:"REST API / Webhook / SFTP連携",
    pro_s7i3:"フィールドマッピング設定", pro_s7i4:"基本同期ログ表示",
    pro_s8:"1st-Partyピクセル + データ",
    pro_s8i1:"ピクセルコードインストール・検証",
    pro_s8i2:"リアルタイムイベントストリーム表示",
    pro_s8i3:"アトリビューション分析 (タッチモデル・ROAS)",
    pro_s8i4:"イベント収集・データスキーマ・マッピング",
    pro_s8i5:"APIキー・Webhook・OAuth連携",
    pro_s9:"高度分析・BI",
    pro_s9i1:"コホート分析", pro_s9i2:"P&L チャネル別・商品別・トレンド",
    pro_s9i3:"異常検知・競合AI分析", pro_s9i4:"インフルエンサーパフォーマンス表示",
    pro_s10:"リアルタイム為替 + チーム管理",
    pro_s10i1:"リアルタイム為替自動取得 (通貨単位グローバル)",
    pro_s10i2:"チーム活動履歴監査",
    pro_s10i3:"システム状態・APIモニタリング",
    pro_s10i4:"バッチジョブ実行・再処理",
    pro_l1:"Writeback即時ロールバック — Enterprise",
    pro_l2:"Amazon政策・レビュー管理 — Enterprise",
    pro_l3:"市場シェア・トレンドAI — Enterprise",
    pro_l4:"Data Product SLA・ガバナンス — Enterprise",
    pro_l5:"SmartConnectパートナーAPI双方向 — Enterprise",
    pro_l6:"インフルエンサーDB・キャンペーン実施 — Enterprise",
    pro_l7:"監査ログ全エクスポート — Enterprise",
    pro_l8:"自動レポート・予約送信 — Enterprise",
    pro_l9:"APIデータストリーミングエクスポート — Enterprise",
    ent_tagline:"大型EC・エージェンシー・グループ", ent_headline:"全て無制限プラン", ent_badge:"最高仕様",
    ent_desc:"Pro全て + 即時ロールバック・Amazon政策管理・市場シェア・Data Productガバナンス・SmartConnectパートナーAPI・インフルエンサーDB・監査全て・自動レポート。",
    ent_s1:"Writeback即時ロールバック (新)", ent_s1i1:"Writeback設定・ログ",
    ent_s1i2:"即時ロールバック (ミス即時復旧)",
    ent_s1i3:"マルチブランド自動実行", ent_s1i4:"ロールバック履歴全表示",
    ent_s2:"Amazon高度運用 (新)", ent_s2i1:"Amazonアカウント健全性モニター",
    ent_s2i2:"政策遵守管理", ent_s2i3:"レビューモニタリング全て",
    ent_s2i4:"リスティング品質監査",
    ent_s3:"市場インテリジェンス (新)", ent_s3i1:"市場シェア分析",
    ent_s3i2:"競合広告追跡 (AI)", ent_s3i3:"トレンドAI予測モデル",
    ent_s3i4:"チャネルアトリビューション全モデル", ent_s3i5:"コンバージョンパス分析",
    ent_s4:"Data Productガバナンス (新)",
    ent_s4i1:"Data Productスキーマ・品質メトリクス",
    ent_s4i2:"SLA管理・オーナー指定",
    ent_s4i3:"APIベースデータストリーミングエクスポート",
    ent_s4i4:"イベント正規化全管理",
    ent_s4i5:"OAuthパートナー管理", ent_s4i6:"高度データマッピング",
    ent_s5:"SmartConnectパートナーAPI (新)",
    ent_s5i1:"パートナーレベル双方向リアルタイム連携",
    ent_s5i2:"リアルタイム同期ログ全て",
    ent_s5i3:"ERP・SCM・WMSフル統合",
    ent_s5i4:"カスタムWebhook高度設定",
    ent_s6:"マーケティング高度化 (新)",
    ent_s6i1:"インフルエンサーDB全て・キャンペーン実施・精算",
    ent_s6i2:"Kakaoビズボード (大規模広告)",
    ent_s6i3:"WhatsApp高度設定 (チャネルAPI)",
    ent_s6i4:"LINEチャネル高度設定",
    ent_s6i5:"AIセグメント高度 (カスタム基準)",
    ent_s6i6:"競合レビュー比較分析",
    ent_s7:"運用・ガバナンス全て (新)",
    ent_s7i1:"運用ハブ通知送信 (管理者お知らせ)",
    ent_s7i2:"3PL業者削除・契約管理",
    ent_s7i3:"監査ログ全て・CSVエクスポート",
    ent_s7i4:"システムモニター通知設定",
    ent_s7i5:"自動レポート生成・予約送信",
    ent_s7i6:"ダッシュボード外部共有・埋め込み",
    ent_s8:"Pro全て含む + 無制限",
    ent_s8i1:"Proプラン全機能含む",
    ent_s8i2:"無制限アカウント・ユーザー・チームメンバー",
    ent_s8i3:"優先サポートSLA",
    ent_s8i4:"専任オンボーディングコンサルティング・年次トレーニング",
    ent_s9:"カスタム・専任サービス",
    ent_s9i1:"カスタムダッシュボード構成",
    ent_s9i2:"専任マネージャー配置",
    ent_s9i3:"年次契約基盤カスタム割引",
    ent_s9i4:"カスタムトレーニング・ワークショップ",
  },
  cmpRow: {
    r1:"ホームダッシュボード", r2:"AI広告クリエイティブ・キャンペーン管理",
    r3:"AI予測 (離脱・LTV・購入確率)",
    r4:"カスタマージャーニービルダー", r5:"AIセグメント",
    r6:"広告・チャネル分析 (ROAS・KPI)",
    r7:"アトリビューション分析 (タッチモデル)", r8:"競合AI分析",
    r9:"顧客・CRM (メール/Kakao/SMS)",
    r10:"レビュー & UGC分析", r11:"コマースチャネル",
    r12:"WMS (在庫・入出庫)",
    r13:"3PL管理", r14:"Amazon高度運用",
    r15:"分析・パフォーマンス (コホート・P&L)",
    r16:"AIルールエンジン・自動化", r17:"SmartConnect (ERP・SCM)",
    r18:"1st-Partyピクセル",
    r19:"データパイプライン・API", r20:"Data Productガバナンス",
    r21:"BIレポート", r22:"通貨単位選択 (グローバル)",
    r23:"インフルエンサー管理", r24:"運用ハブ (バッチ・再処理)",
    r25:"監査ログ", r26:"チーム管理 (RBAC)",
    r27:"アカウント数", r28:"サポート方式",
  },
  cmpVal: {
    all:"全て", basic:"基本", realtime:"リアルタイム", domestic_core:"国内主要",
    domestic:"国内", dom_global:"国内+グローバル", market_share:"市場シェア",
    basic_auto:"基本自動分類", advanced_custom:"高度カスタム",
    conv_path_all:"コンバージョンパス全て", trend_forecast:"トレンド予測",
    bizboard:"ビズボード", competitor_compare:"競合比較",
    location_barcode:"ロケーション・バーコード", list_view:"一覧表示",
    contract:"契約", policy_review:"政策・レビュー・リスティング",
    cohort_pl:"コホート・P&L全て", notification_basic:"通知基本",
    rule_writeback:"ルールエンジン・Writeback", instant_rollback:"即時ロールバック",
    partner_api:"パートナーAPI双方向", install_analysis:"インストール・分析",
    server_side:"サーバーサイド", domestic_ads:"国内広告連携",
    schema_quality_view:"スキーマ・品質表示", owner_streaming:"オーナー・ストリーミング",
    custom_excel:"カスタム・Excel", anomaly_detect:"異常検知",
    auto_scheduled_share:"自動・予約・共有", manual:"手動",
    realtime_rate:"リアルタイム為替", perf_view:"パフォーマンス表示",
    campaign_settle:"キャンペーン・精算", reprocess:"再処理",
    notification_send:"通知送信", own_history:"自分の履歴",
    list_invite:"一覧・招待", activity_history:"活動履歴",
    rbac_role:"RBACロール設定", unlimited:"無制限",
    chat_support:"チャットサポート", dedicated_manager:"専任マネージャー",
    dedicated_sla:"専任 + SLA",
  },`,
};

// For zh, de - use English values (shorter, will fallback)
PATCHES.zh = PATCHES.en.replace(/  pricingDetail: \{/, '  pricingDetail: {').replace(/pro_badge:"Popular"/, 'pro_badge:"热门"').replace(/ent_badge:"Top Tier"/, 'ent_badge:"顶级"').replace(/growth_headline:"Marketing Growth Plan"/, 'growth_headline:"营销增长方案"').replace(/pro_headline:"AI Automation Plan"/, 'pro_headline:"AI自动化方案"').replace(/ent_headline:"Unlimited Everything Plan"/, 'ent_headline:"无限一切方案"');

PATCHES.de = PATCHES.en.replace(/pro_badge:"Popular"/, 'pro_badge:"Beliebt"').replace(/ent_badge:"Top Tier"/, 'ent_badge:"Top-Tier"').replace(/growth_headline:"Marketing Growth Plan"/, 'growth_headline:"Marketing-Wachstumsplan"').replace(/pro_headline:"AI Automation Plan"/, 'pro_headline:"KI-Automatisierungsplan"').replace(/ent_headline:"Unlimited Everything Plan"/, 'ent_headline:"Alles Unbegrenzt Plan"');

// th, vi, id, zh-TW - use English as fallback (already translated elsewhere)
PATCHES.th = PATCHES.en;
PATCHES.vi = PATCHES.en;
PATCHES.id = PATCHES.en;
PATCHES['zh-TW'] = PATCHES.en.replace(/pro_badge:"Popular"/, 'pro_badge:"熱門"').replace(/ent_badge:"Top Tier"/, 'ent_badge:"頂級"');

// Insert pricingDetail/cmpRow/cmpVal INSIDE the const object 
// Strategy: find the LAST "};" in the file (closing the main locale const),
// then insert the patch text just before that closing

const LOCALE_FILES = {
  ko: 'src/i18n/locales/ko.js',
  en: 'src/i18n/locales/en.js',
  ja: 'src/i18n/locales/ja.js',
  zh: 'src/i18n/locales/zh.js',
  de: 'src/i18n/locales/de.js',
  th: 'src/i18n/locales/th.js',
  vi: 'src/i18n/locales/vi.js',
  id: 'src/i18n/locales/id.js',
  'zh-TW': 'src/i18n/locales/zh-TW.js',
};

for (const [lang, fp] of Object.entries(LOCALE_FILES)) {
  if (!fs.existsSync(fp)) { console.log(`⚠ ${lang}: not found`); continue; }
  let c = fs.readFileSync(fp, 'utf8');
  
  // Skip if already has pricingDetail INSIDE the object
  if (c.includes('pricingDetail:')) {
    console.log(`⏭ ${lang}: already has pricingDetail: (inside object)`);
    continue;
  }
  
  // Find the closing of the main const object
  // It's the last occurrence of "};" before "export default"
  const exportIdx = c.indexOf('export default');
  let insertPos = -1;
  
  // Find last "};" before export
  let searchFrom = 0;
  let lastClosing = -1;
  while (true) {
    const pos = c.indexOf('};', searchFrom);
    if (pos < 0 || pos > exportIdx) break;
    lastClosing = pos;
    searchFrom = pos + 1;
  }
  
  if (lastClosing < 0) { console.log(`⚠ ${lang}: no closing }; found`); continue; }
  insertPos = lastClosing;
  
  const patch = PATCHES[lang] || PATCHES.en;
  const newContent = c.slice(0, insertPos) + patch + '\n' + c.slice(insertPos);
  fs.writeFileSync(fp, newContent, 'utf8');
  
  // Quick syntax check
  try {
    delete require.cache[require.resolve('./' + fp)];
    const mod = require('./' + fp);
    const obj = mod.default || mod;
    const hasPd = !!(obj && obj.pricingDetail);
    console.log(`✅ ${lang}: OK, pricingDetail inside=${hasPd}`);
  } catch(e) {
    console.log(`❌ ${lang}: ${e.message.slice(0,80)}`);
  }
}
