const fs=require('fs'),path=require('path'),DIR=path.join(__dirname,'src','i18n','locales');
const G={
ko:{guideStep7Title:"API 보안 및 인증 관리",guideStep7Desc:"OAuth 토큰, API 키의 보안 관리 및 정기적 갱신 절차를 설정합니다.",guideStep8Title:"자동 동기화 스케줄 설정",guideStep8Desc:"채널별 상품/주문/재고 자동 동기화 주기를 설정합니다.",guideStep9Title:"매출 분석 및 리포트",guideStep9Desc:"채널별 매출, 전환율, ROI를 분석하고 리포트를 생성합니다.",guideStep10Title:"A/B 테스트 및 가격 최적화",guideStep10Desc:"채널별 가격 전략을 A/B 테스트하여 최적 가격을 도출합니다.",guideStep11Title:"알림 및 모니터링 설정",guideStep11Desc:"재고 부족, 주문 이상, 동기화 오류 시 실시간 알림을 설정합니다.",guideStep12Title:"글로벌 확장 전략",guideStep12Desc:"해외 마켓플레이스 진출을 위한 다국어/다통화 설정을 구성합니다.",guideStep13Title:"데이터 보호 및 격리",guideStep13Desc:"운영/데모 데이터 격리를 확인하고 보안 정책을 적용합니다.",guideStep14Title:"모바일 대응 최적화",guideStep14Desc:"모바일 환경에서의 관리 인터페이스 최적화를 설정합니다.",guideStep15Title:"운영 배포 및 최종 점검",guideStep15Desc:"모든 설정을 검증하고 운영 환경에 배포합니다.",guideTip6:"채널별 수수료율을 정기적으로 확인하세요.",guideTip7:"재고 부족 알림 임계값을 채널별로 다르게 설정할 수 있습니다.",guideTip8:"API 토큰은 만료 전에 갱신하여 동기화 중단을 방지하세요.",guideTip9:"데모 환경에서 충분히 테스트한 후 운영에 적용하세요.",guideTip10:"글로벌 확장 시 현지 세금(VAT) 규정을 반드시 확인하세요.",demoIsolation:"데모 환경 — 데이터가 운영 환경과 격리되어 있습니다"},
en:{guideStep7Title:"API Security & Auth Management",guideStep7Desc:"Manage OAuth tokens, API keys securely and set up periodic renewal procedures.",guideStep8Title:"Auto-Sync Schedule Setup",guideStep8Desc:"Configure automatic sync intervals for products, orders, and inventory per channel.",guideStep9Title:"Revenue Analytics & Reports",guideStep9Desc:"Analyze revenue, conversion rates, and ROI by channel and generate reports.",guideStep10Title:"A/B Testing & Price Optimization",guideStep10Desc:"A/B test pricing strategies per channel to determine optimal pricing.",guideStep11Title:"Alerts & Monitoring Setup",guideStep11Desc:"Set up real-time alerts for low stock, order anomalies, and sync errors.",guideStep12Title:"Global Expansion Strategy",guideStep12Desc:"Configure multi-language/multi-currency settings for international marketplace expansion.",guideStep13Title:"Data Protection & Isolation",guideStep13Desc:"Verify production/demo data isolation and apply security policies.",guideStep14Title:"Mobile Optimization",guideStep14Desc:"Optimize the management interface for mobile environments.",guideStep15Title:"Production Deploy & Final Check",guideStep15Desc:"Validate all settings and deploy to the production environment.",guideTip6:"Regularly check commission rates per channel.",guideTip7:"Set different low-stock alert thresholds per channel.",guideTip8:"Renew API tokens before expiry to prevent sync interruptions.",guideTip9:"Test thoroughly in demo before applying to production.",guideTip10:"Always verify local VAT regulations when expanding globally.",demoIsolation:"Demo environment — data isolated from production"},
ja:{guideStep7Title:"APIセキュリティと認証管理",guideStep7Desc:"OAuthトークン、APIキーのセキュリティ管理と定期更新手順を設定します。",guideStep8Title:"自動同期スケジュール設定",guideStep8Desc:"チャネルごとの商品/注文/在庫の自動同期間隔を設定します。",guideStep9Title:"売上分析とレポート",guideStep9Desc:"チャネル別の売上、コンバージョン率、ROIを分析しレポートを生成します。",guideStep10Title:"A/Bテストと価格最適化",guideStep10Desc:"チャネルごとの価格戦略をA/Bテストして最適価格を導出します。",guideStep11Title:"アラートとモニタリング設定",guideStep11Desc:"在庫不足、注文異常、同期エラー時のリアルタイムアラートを設定します。",guideStep12Title:"グローバル展開戦略",guideStep12Desc:"海外マーケットプレイス進出のための多言語/多通貨設定を構成します。",guideStep13Title:"データ保護と分離",guideStep13Desc:"本番/デモデータの分離を確認しセキュリティポリシーを適用します。",guideStep14Title:"モバイル対応最適化",guideStep14Desc:"モバイル環境での管理インターフェースを最適化します。",guideStep15Title:"本番デプロイと最終確認",guideStep15Desc:"すべての設定を検証し本番環境にデプロイします。",guideTip6:"チャネル別の手数料率を定期的に確認してください。",guideTip7:"在庫不足アラートのしきい値をチャネルごとに設定できます。",guideTip8:"APIトークンは期限前に更新して同期中断を防止してください。",guideTip9:"デモ環境で十分にテストしてから本番に適用してください。",guideTip10:"グローバル展開時は現地のVAT規制を必ず確認してください。",demoIsolation:"デモ環境 — データは本番環境から分離されています"},
zh:{guideStep7Title:"API安全与认证管理",guideStep7Desc:"管理OAuth令牌、API密钥的安全性并设置定期更新。",guideStep8Title:"自动同步计划设置",guideStep8Desc:"配置各渠道商品/订单/库存的自动同步间隔。",guideStep9Title:"收入分析与报告",guideStep9Desc:"按渠道分析收入、转化率和ROI并生成报告。",guideStep10Title:"A/B测试与价格优化",guideStep10Desc:"对各渠道定价策略进行A/B测试以确定最优价格。",guideStep11Title:"警报与监控设置",guideStep11Desc:"设置库存不足、订单异常和同步错误的实时警报。",guideStep12Title:"全球扩展策略",guideStep12Desc:"配置多语言/多币种设置以进入国际市场。",guideStep13Title:"数据保护与隔离",guideStep13Desc:"验证生产/演示数据隔离并应用安全策略。",guideStep14Title:"移动端优化",guideStep14Desc:"为移动环境优化管理界面。",guideStep15Title:"生产部署与最终检查",guideStep15Desc:"验证所有设置并部署到生产环境。",guideTip6:"定期检查各渠道佣金率。",guideTip7:"可为各渠道设置不同的低库存警报阈值。",guideTip8:"在API令牌过期前更新以防止同步中断。",guideTip9:"在演示环境充分测试后再应用到生产。",guideTip10:"全球扩展时务必确认当地增值税法规。",demoIsolation:"演示环境 — 数据与生产环境隔离"},
"zh-TW":{guideStep7Title:"API安全與認證管理",guideStep7Desc:"管理OAuth權杖、API金鑰的安全性並設定定期更新。",guideStep8Title:"自動同步排程設定",guideStep8Desc:"配置各頻道商品/訂單/庫存的自動同步間隔。",guideStep9Title:"營收分析與報告",guideStep9Desc:"按頻道分析營收、轉換率和ROI並產生報告。",guideStep10Title:"A/B測試與價格最佳化",guideStep10Desc:"對各頻道定價策略進行A/B測試以確定最佳價格。",guideStep11Title:"警報與監控設定",guideStep11Desc:"設定庫存不足、訂單異常和同步錯誤的即時警報。",guideStep12Title:"全球擴展策略",guideStep12Desc:"配置多語言/多幣種設定以進入國際市場。",guideStep13Title:"資料保護與隔離",guideStep13Desc:"驗證正式/展示資料隔離並套用安全策略。",guideStep14Title:"行動裝置最佳化",guideStep14Desc:"為行動環境最佳化管理介面。",guideStep15Title:"正式部署與最終檢查",guideStep15Desc:"驗證所有設定並部署到正式環境。",demoIsolation:"展示環境 — 資料與正式環境隔離"},
es:{guideStep7Title:"Seguridad de API y gestión de autenticación",guideStep7Desc:"Gestione tokens OAuth y claves API con renovación periódica.",guideStep8Title:"Configuración de sincronización automática",guideStep8Desc:"Configure intervalos de sincronización automática por canal.",guideStep9Title:"Análisis de ingresos e informes",guideStep9Desc:"Analice ingresos y ROI por canal y genere informes.",guideStep10Title:"Pruebas A/B y optimización de precios",guideStep10Desc:"Pruebe estrategias de precios A/B por canal.",guideStep11Title:"Alertas y monitoreo",guideStep11Desc:"Configure alertas en tiempo real para stock bajo y errores de sincronización.",guideStep12Title:"Estrategia de expansión global",guideStep12Desc:"Configure ajustes multiidioma/multimoneda para mercados internacionales.",guideStep13Title:"Protección y aislamiento de datos",guideStep13Desc:"Verifique el aislamiento de datos producción/demo.",guideStep14Title:"Optimización móvil",guideStep14Desc:"Optimice la interfaz para entornos móviles.",guideStep15Title:"Despliegue y verificación final",guideStep15Desc:"Valide todos los ajustes y despliegue a producción.",demoIsolation:"Entorno demo — datos aislados de producción"},
fr:{guideStep7Title:"Sécurité API et gestion de l'authentification",guideStep7Desc:"Gérez les tokens OAuth et les clés API avec un renouvellement périodique.",guideStep8Title:"Configuration de la synchronisation automatique",guideStep8Desc:"Configurez les intervalles de synchronisation par canal.",guideStep9Title:"Analyse des revenus et rapports",guideStep9Desc:"Analysez les revenus et le ROI par canal et générez des rapports.",guideStep10Title:"Tests A/B et optimisation des prix",guideStep10Desc:"Testez les stratégies de prix A/B par canal.",guideStep11Title:"Alertes et surveillance",guideStep11Desc:"Configurez des alertes en temps réel pour le stock bas et les erreurs.",guideStep12Title:"Stratégie d'expansion mondiale",guideStep12Desc:"Configurez les paramètres multilingues/multidevises.",guideStep13Title:"Protection et isolation des données",guideStep13Desc:"Vérifiez l'isolation des données production/démo.",guideStep14Title:"Optimisation mobile",guideStep14Desc:"Optimisez l'interface pour les environnements mobiles.",guideStep15Title:"Déploiement et vérification finale",guideStep15Desc:"Validez tous les paramètres et déployez en production.",demoIsolation:"Environnement démo — données isolées de la production"},
de:{guideStep7Title:"API-Sicherheit & Authentifizierungsverwaltung",guideStep7Desc:"Verwalten Sie OAuth-Tokens und API-Schlüssel mit regelmäßiger Erneuerung.",guideStep8Title:"Automatische Synchronisierung einrichten",guideStep8Desc:"Konfigurieren Sie die automatischen Synchronisierungsintervalle pro Kanal.",guideStep9Title:"Umsatzanalyse & Berichte",guideStep9Desc:"Analysieren Sie Umsatz und ROI pro Kanal und erstellen Sie Berichte.",guideStep10Title:"A/B-Tests & Preisoptimierung",guideStep10Desc:"Testen Sie Preisstrategien A/B pro Kanal.",guideStep11Title:"Warnungen & Überwachung",guideStep11Desc:"Richten Sie Echtzeitwarnungen für niedrigen Bestand und Fehler ein.",guideStep12Title:"Globale Expansionsstrategie",guideStep12Desc:"Konfigurieren Sie mehrsprachige/Mehrwährungseinstellungen.",guideStep13Title:"Datenschutz & Isolation",guideStep13Desc:"Überprüfen Sie die Produktion/Demo-Datenisolation.",guideStep14Title:"Mobile Optimierung",guideStep14Desc:"Optimieren Sie die Oberfläche für mobile Umgebungen.",guideStep15Title:"Produktions-Deployment & Endkontrolle",guideStep15Desc:"Validieren Sie alle Einstellungen und deployen Sie in die Produktion.",demoIsolation:"Demo-Umgebung — Daten von der Produktion isoliert"},
th:{guideStep7Title:"ความปลอดภัย API และการจัดการการรับรองความถูกต้อง",guideStep7Desc:"จัดการ OAuth token และ API key อย่างปลอดภัย",guideStep8Title:"ตั้งค่าการซิงค์อัตโนมัติ",guideStep8Desc:"กำหนดช่วงเวลาซิงค์อัตโนมัติต่อช่องทาง",guideStep9Title:"วิเคราะห์รายได้และรายงาน",guideStep9Desc:"วิเคราะห์รายได้และ ROI ต่อช่องทาง",guideStep10Title:"ทดสอบ A/B และปรับราคา",guideStep10Desc:"ทดสอบกลยุทธ์ราคา A/B ต่อช่องทาง",guideStep11Title:"การแจ้งเตือนและการตรวจสอบ",guideStep11Desc:"ตั้งค่าการแจ้งเตือนแบบเรียลไทม์",guideStep12Title:"กลยุทธ์การขยายทั่วโลก",guideStep12Desc:"กำหนดค่าหลายภาษา/หลายสกุลเงิน",guideStep13Title:"การปกป้องและแยกข้อมูล",guideStep13Desc:"ตรวจสอบการแยกข้อมูลผลิตภัณฑ์/สาธิต",guideStep14Title:"การเพิ่มประสิทธิภาพมือถือ",guideStep14Desc:"เพิ่มประสิทธิภาพอินเทอร์เฟซสำหรับมือถือ",guideStep15Title:"ปรับใช้และตรวจสอบขั้นสุดท้าย",guideStep15Desc:"ตรวจสอบการตั้งค่าทั้งหมดและปรับใช้ในการผลิต",demoIsolation:"สภาพแวดล้อมสาธิต — ข้อมูลแยกจากการผลิต"},
vi:{guideStep7Title:"Bảo mật API và quản lý xác thực",guideStep7Desc:"Quản lý token OAuth và API key một cách an toàn.",guideStep8Title:"Thiết lập đồng bộ tự động",guideStep8Desc:"Cấu hình khoảng thời gian đồng bộ tự động theo kênh.",guideStep9Title:"Phân tích doanh thu và báo cáo",guideStep9Desc:"Phân tích doanh thu và ROI theo kênh.",guideStep10Title:"Thử nghiệm A/B và tối ưu giá",guideStep10Desc:"Thử nghiệm chiến lược giá A/B theo kênh.",guideStep11Title:"Cảnh báo và giám sát",guideStep11Desc:"Thiết lập cảnh báo thời gian thực.",guideStep12Title:"Chiến lược mở rộng toàn cầu",guideStep12Desc:"Cấu hình đa ngôn ngữ/đa tiền tệ.",guideStep13Title:"Bảo vệ và cách ly dữ liệu",guideStep13Desc:"Xác minh cách ly dữ liệu sản xuất/demo.",guideStep14Title:"Tối ưu hóa di động",guideStep14Desc:"Tối ưu giao diện cho môi trường di động.",guideStep15Title:"Triển khai và kiểm tra cuối cùng",guideStep15Desc:"Xác nhận tất cả cài đặt và triển khai.",demoIsolation:"Môi trường demo — dữ liệu cách ly khỏi sản xuất"},
id:{guideStep7Title:"Keamanan API & manajemen autentikasi",guideStep7Desc:"Kelola token OAuth dan kunci API dengan aman.",guideStep8Title:"Pengaturan sinkronisasi otomatis",guideStep8Desc:"Konfigurasikan interval sinkronisasi otomatis per saluran.",guideStep9Title:"Analisis pendapatan & laporan",guideStep9Desc:"Analisis pendapatan dan ROI per saluran.",guideStep10Title:"Pengujian A/B & optimasi harga",guideStep10Desc:"Uji strategi harga A/B per saluran.",guideStep11Title:"Peringatan & pemantauan",guideStep11Desc:"Atur peringatan real-time.",guideStep12Title:"Strategi ekspansi global",guideStep12Desc:"Konfigurasikan pengaturan multi-bahasa/multi-mata uang.",guideStep13Title:"Perlindungan & isolasi data",guideStep13Desc:"Verifikasi isolasi data produksi/demo.",guideStep14Title:"Optimasi seluler",guideStep14Desc:"Optimalkan antarmuka untuk perangkat seluler.",guideStep15Title:"Deploy & pemeriksaan akhir",guideStep15Desc:"Validasi semua pengaturan dan deploy ke produksi.",demoIsolation:"Lingkungan demo — data terisolasi dari produksi"},
pt:{guideStep7Title:"Segurança de API e gestão de autenticação",guideStep7Desc:"Gerencie tokens OAuth e chaves de API com renovação periódica.",guideStep8Title:"Configuração de sincronização automática",guideStep8Desc:"Configure intervalos de sincronização automática por canal.",guideStep9Title:"Análise de receita e relatórios",guideStep9Desc:"Analise receita e ROI por canal e gere relatórios.",guideStep10Title:"Testes A/B e otimização de preços",guideStep10Desc:"Teste estratégias de preços A/B por canal.",guideStep11Title:"Alertas e monitoramento",guideStep11Desc:"Configure alertas em tempo real.",guideStep12Title:"Estratégia de expansão global",guideStep12Desc:"Configure definições multilíngues/multimoeda.",guideStep13Title:"Proteção e isolamento de dados",guideStep13Desc:"Verifique o isolamento de dados produção/demo.",guideStep14Title:"Otimização móvel",guideStep14Desc:"Otimize a interface para ambientes móveis.",guideStep15Title:"Deploy e verificação final",guideStep15Desc:"Valide todas as configurações e faça deploy em produção.",demoIsolation:"Ambiente demo — dados isolados da produção"},
ru:{guideStep7Title:"Безопасность API и управление аутентификацией",guideStep7Desc:"Управляйте токенами OAuth и API-ключами с периодическим обновлением.",guideStep8Title:"Настройка автоматической синхронизации",guideStep8Desc:"Настройте интервалы автоматической синхронизации по каналам.",guideStep9Title:"Анализ выручки и отчёты",guideStep9Desc:"Анализируйте выручку и ROI по каналам.",guideStep10Title:"A/B-тесты и оптимизация цен",guideStep10Desc:"Тестируйте ценовые стратегии A/B по каналам.",guideStep11Title:"Оповещения и мониторинг",guideStep11Desc:"Настройте оповещения в реальном времени.",guideStep12Title:"Стратегия глобального расширения",guideStep12Desc:"Настройте мультиязычные/мультивалютные параметры.",guideStep13Title:"Защита и изоляция данных",guideStep13Desc:"Проверьте изоляцию данных продакшн/демо.",guideStep14Title:"Мобильная оптимизация",guideStep14Desc:"Оптимизируйте интерфейс для мобильных устройств.",guideStep15Title:"Развёртывание и финальная проверка",guideStep15Desc:"Проверьте все настройки и разверните в продакшн.",demoIsolation:"Демо-среда — данные изолированы от продакшн"},
ar:{guideStep7Title:"أمان API وإدارة المصادقة",guideStep7Desc:"إدارة رموز OAuth ومفاتيح API بشكل آمن مع التجديد الدوري.",guideStep8Title:"إعداد المزامنة التلقائية",guideStep8Desc:"تكوين فترات المزامنة التلقائية لكل قناة.",guideStep9Title:"تحليل الإيرادات والتقارير",guideStep9Desc:"تحليل الإيرادات وعائد الاستثمار لكل قناة وإنشاء التقارير.",guideStep10Title:"اختبار A/B وتحسين الأسعار",guideStep10Desc:"اختبار استراتيجيات التسعير A/B لكل قناة.",guideStep11Title:"التنبيهات والمراقبة",guideStep11Desc:"إعداد تنبيهات فورية لانخفاض المخزون وأخطاء المزامنة.",guideStep12Title:"استراتيجية التوسع العالمي",guideStep12Desc:"تكوين إعدادات متعددة اللغات/العملات للأسواق الدولية.",guideStep13Title:"حماية البيانات والعزل",guideStep13Desc:"التحقق من عزل بيانات الإنتاج/العرض التوضيحي.",guideStep14Title:"تحسين الجوال",guideStep14Desc:"تحسين واجهة الإدارة لبيئات الجوال.",guideStep15Title:"النشر والفحص النهائي",guideStep15Desc:"التحقق من جميع الإعدادات والنشر في بيئة الإنتاج.",demoIsolation:"بيئة تجريبية — البيانات معزولة عن الإنتاج"},
hi:{guideStep7Title:"API सुरक्षा और प्रमाणीकरण प्रबंधन",guideStep7Desc:"OAuth टोकन और API कुंजियों को सुरक्षित रूप से प्रबंधित करें।",guideStep8Title:"स्वचालित सिंक शेड्यूल सेटअप",guideStep8Desc:"प्रत्येक चैनल के लिए स्वचालित सिंक अंतराल कॉन्फ़िगर करें।",guideStep9Title:"राजस्व विश्लेषण और रिपोर्ट",guideStep9Desc:"चैनल के अनुसार राजस्व और ROI का विश्लेषण करें।",guideStep10Title:"A/B परीक्षण और मूल्य अनुकूलन",guideStep10Desc:"प्रत्येक चैनल के लिए A/B मूल्य निर्धारण रणनीतियों का परीक्षण करें।",guideStep11Title:"अलर्ट और मॉनिटरिंग",guideStep11Desc:"रियल-टाइम अलर्ट सेट करें।",guideStep12Title:"वैश्विक विस्तार रणनीति",guideStep12Desc:"बहुभाषी/बहु-मुद्रा सेटिंग्स कॉन्फ़िगर करें।",guideStep13Title:"डेटा सुरक्षा और अलगाव",guideStep13Desc:"उत्पादन/डेमो डेटा अलगाव सत्यापित करें।",guideStep14Title:"मोबाइल अनुकूलन",guideStep14Desc:"मोबाइल वातावरण के लिए इंटरफ़ेस को अनुकूलित करें।",guideStep15Title:"तैनाती और अंतिम जाँच",guideStep15Desc:"सभी सेटिंग्स मान्य करें और उत्पादन में तैनात करें।",demoIsolation:"डेमो वातावरण — डेटा उत्पादन से अलग"},
};
let total=0;
Object.entries(G).forEach(([lang,keys])=>{
  const file=path.join(DIR,lang+'.js');
  if(!fs.existsSync(file))return;
  let src=fs.readFileSync(file,'utf8');
  const re=/"omniChannel"\s*:\s*\{/g;
  const matches=[];let m;while((m=re.exec(src))!==null)matches.push(m);
  if(matches.length===0){console.log('skip '+lang);return;}
  let cnt=0;
  for(let i=matches.length-1;i>=0;i--){
    const ins=matches[i].index+matches[i][0].length;
    let entries='';
    Object.entries(keys).forEach(([k,v])=>{
      if(!src.includes('"'+k+'"')){entries+='"'+k+'":"'+v.replace(/"/g,'\\"')+'",';cnt++;}
    });
    if(entries)src=src.slice(0,ins)+entries+src.slice(ins);
  }
  if(cnt>0){fs.writeFileSync(file,src,'utf8');console.log('✅ '+lang+': '+cnt);total+=cnt;}else console.log('⏭️  '+lang);
});
console.log('🎯 Total: '+total);
