// Patch poI18n.js: Add full translations for tab labels and main UI for 8 secondary languages
const fs=require('fs');
const src=fs.readFileSync('src/pages/poI18n.js','utf8');
// Parse the existing D object
const D=new Function(src.replace('export default D;','return D;'))();

// Full tab/page translations for each secondary language
const patches={
th:{tabSummary:"สรุป",tabProducts:"ลงทะเบียนสินค้า",tabOptimize:"เพิ่มประสิทธิภาพ",tabMix:"ช่องทางผสม",tabRepricer:"ราคาอัตโนมัติ",tabCompetitor:"คู่แข่ง",tabChannelFee:"ค่าธรรมเนียมช่องทาง",tabGuide:"คู่มือ",tabCalendar:"ปฏิทินโปรโมชั่น",tabScenario:"สถานการณ์",pageTitle:"เพิ่มประสิทธิภาพราคา",pageSub:"การเพิ่มประสิทธิภาพราคาแบบเรียลไทม์",regProduct:"สินค้า",items:"รายการ",avgMargin:"มาร์จิ้นเฉลี่ย",avgRecPrice:"ราคาแนะนำเฉลี่ย",channelResult:"ผลลัพธ์ช่องทาง",recentHistory:"ประวัติล่าสุด",currentPrice:"ราคาปัจจุบัน",optimalPrice:"ราคาที่เหมาะสม",expectedMargin:"มาร์จิ้นที่คาดหวัง",noAnalysis:"ไม่มีการวิเคราะห์",refresh:"รีเฟรช",productName:"ชื่อสินค้า",category:"หมวดหมู่",spec:"สเปค",unit:"หน่วย",purchaseCost:"ราคาซื้อ",ioFee:"ค่าขนส่งเข้า/ออก",storageFee:"ค่าจัดเก็บ",workFee:"ค่าดำเนินงาน",shippingFee:"ค่าจัดส่ง",productCostAuto:"ต้นทุนสินค้า(อัตโนมัติ)",targetMarginRate:"เป้าหมายมาร์จิ้น",baseSalePrice:"ราคาขายพื้นฐาน",qtyPerBox:"จำนวน/กล่อง",boxesPerPallet:"กล่อง/พาเลท",saveProduct:"บันทึกสินค้า",regProducts:"สินค้าที่ลงทะเบียน",noProducts:"ไม่มีสินค้า",calcParams:"พารามิเตอร์การคำนวณ",labelSku:"SKU",labelChannel:"ช่องทาง",allUnified:"ทั้งหมด",currentSalePrice:"ราคาขายปัจจุบัน",stockQty:"จำนวนสต็อก",calculating:"กำลังคำนวณ...",calcOptimal:"คำนวณราคาที่เหมาะสม",costPrice:"ราคาต้นทุน",totalProfit:"กำไรรวม",totalBudget:"งบประมาณรวม",register:"ลงทะเบียน",activeRules:"กฎที่ใช้งาน",autoRules:"กฎอัตโนมัติ",ruleActive:"ใช้งาน",ruleInactive:"ไม่ใช้งาน",channelFeeTitle:"ค่าธรรมเนียมช่องทาง",guideTitle:"คู่มือเพิ่มประสิทธิภาพราคา",guideSub:"คู่มือฉบับสมบูรณ์",guideStepsTitle:"ทีละขั้นตอน",badgeChannelUnit:"หน่วยช่องทาง",badgeRealtimeSync:"ซิงค์เรียลไทม์",badgeSecurityActive:"ความปลอดภัยเปิดใช้งาน",elasticityData:"ข้อมูลความยืดหยุ่น",optAdoption:"การนำไปใช้",excelBulkUpload:"อัปโหลด Excel จำนวนมาก",excelDownload:"ดาวน์โหลด Excel",excelTemplate:"เทมเพลต Excel",costBreakdown:"รายละเอียดต้นทุน",unitBox:"กล่อง",unitEach:"ชิ้น",unitPallet:"พาเลท",totalUnits:"จำนวนรวม",totalBoxes:"กล่องรวม",totalPallets:"พาเลทรวม",feeCommission:"ค่าคอมมิชชั่น",feeTax:"ภาษี",feeTotal:"รวม",changeHistory:"ประวัติการเปลี่ยนแปลง"},
vi:{tabSummary:"Tổng quan",tabProducts:"Đăng ký SP",tabOptimize:"Tối ưu",tabMix:"Kênh phối",tabRepricer:"Giá tự động",tabCompetitor:"Đối thủ",tabChannelFee:"Phí kênh",tabGuide:"Hướng dẫn",tabCalendar:"Lịch KM",tabScenario:"Kịch bản",pageTitle:"Tối ưu Giá",pageSub:"Tối ưu giá thời gian thực",regProduct:"Sản phẩm",items:"SP",avgMargin:"Biên LN TB",channelResult:"Kết quả kênh",currentPrice:"Giá hiện tại",optimalPrice:"Giá tối ưu",expectedMargin:"Biên LN dự kiến",refresh:"Làm mới",productName:"Tên SP",category:"Danh mục",purchaseCost:"Giá mua",shippingFee:"Phí vận chuyển",saveProduct:"Lưu SP",noProducts:"Không có SP",calcParams:"Tham số",labelChannel:"Kênh",allUnified:"Tất cả",currentSalePrice:"Giá bán hiện tại",stockQty:"SL tồn kho",calculating:"Đang tính...",calcOptimal:"Tính giá tối ưu",totalProfit:"Tổng lợi nhuận",register:"Đăng ký",activeRules:"Quy tắc đang dùng",autoRules:"Quy tắc tự động",channelFeeTitle:"Phí kênh",guideTitle:"Hướng dẫn Tối ưu Giá",badgeChannelUnit:"Đơn vị kênh",badgeRealtimeSync:"Đồng bộ RT",unitBox:"Hộp",unitEach:"Cái",unitPallet:"Pallet",costBreakdown:"Chi tiết chi phí"},
id:{tabSummary:"Ringkasan",tabProducts:"Daftar Produk",tabOptimize:"Optimasi",tabMix:"Campuran Saluran",tabRepricer:"Harga Otomatis",tabCompetitor:"Kompetitor",tabChannelFee:"Biaya Saluran",tabGuide:"Panduan",tabCalendar:"Kalender Promo",tabScenario:"Skenario",pageTitle:"Optimasi Harga",pageSub:"Optimasi harga real-time",regProduct:"Produk",items:"item",channelResult:"Hasil Saluran",currentPrice:"Harga Saat Ini",optimalPrice:"Harga Optimal",refresh:"Segarkan",productName:"Nama Produk",category:"Kategori",purchaseCost:"Harga Beli",shippingFee:"Biaya Pengiriman",saveProduct:"Simpan Produk",noProducts:"Tidak ada produk",calcParams:"Parameter",labelChannel:"Saluran",allUnified:"Semua",currentSalePrice:"Harga Jual Saat Ini",stockQty:"Jumlah Stok",calculating:"Menghitung...",calcOptimal:"Hitung Optimal",totalProfit:"Total Laba",register:"Daftar",activeRules:"Aturan Aktif",autoRules:"Aturan Otomatis",channelFeeTitle:"Biaya Saluran",guideTitle:"Panduan Optimasi Harga",unitBox:"Kotak",unitEach:"Buah",unitPallet:"Pallet",costBreakdown:"Rincian Biaya"},
es:{tabSummary:"Resumen",tabProducts:"Reg. Producto",tabOptimize:"Optimizar",tabMix:"Mix Canal",tabRepricer:"Precio Auto",tabCompetitor:"Competencia",tabChannelFee:"Tarifas Canal",tabGuide:"Guía",tabCalendar:"Calendario Promo",tabScenario:"Escenario",pageTitle:"Optimización de Precios",pageSub:"Optimización de precios en tiempo real",regProduct:"Productos",items:"artículos",channelResult:"Resultados Canal",currentPrice:"Precio Actual",optimalPrice:"Precio Óptimo",refresh:"Actualizar",productName:"Nombre Producto",category:"Categoría",purchaseCost:"Precio Compra",shippingFee:"Envío",saveProduct:"Guardar",noProducts:"Sin productos",calcParams:"Parámetros",labelChannel:"Canal",allUnified:"Todo Unificado",currentSalePrice:"Precio Venta Actual",stockQty:"Cantidad Stock",calculating:"Calculando...",calcOptimal:"Calcular Óptimo",totalProfit:"Ganancia Total",register:"Registrar",activeRules:"Reglas Activas",autoRules:"Reglas Auto",channelFeeTitle:"Tarifas Canal",guideTitle:"Guía Optimización Precios",unitBox:"Caja",unitEach:"Ud",unitPallet:"Palé",costBreakdown:"Desglose Costos"},
pt:{tabSummary:"Resumo",tabProducts:"Reg. Produto",tabOptimize:"Otimizar",tabMix:"Mix Canal",tabRepricer:"Preço Auto",tabCompetitor:"Concorrência",tabChannelFee:"Taxas Canal",tabGuide:"Guia",tabCalendar:"Calendário Promo",tabScenario:"Cenário",pageTitle:"Otimização de Preços",pageSub:"Otimização de preços em tempo real",regProduct:"Produtos",items:"itens",channelResult:"Resultados Canal",currentPrice:"Preço Atual",optimalPrice:"Preço Ótimo",refresh:"Atualizar",productName:"Nome Produto",category:"Categoria",purchaseCost:"Preço Compra",shippingFee:"Frete",saveProduct:"Salvar",noProducts:"Sem produtos",calcParams:"Parâmetros",labelChannel:"Canal",allUnified:"Todos Unificados",currentSalePrice:"Preço Venda Atual",stockQty:"Qtd Estoque",calculating:"Calculando...",calcOptimal:"Calcular Ótimo",totalProfit:"Lucro Total",register:"Registrar",activeRules:"Regras Ativas",autoRules:"Regras Auto",channelFeeTitle:"Taxas Canal",guideTitle:"Guia Otimização Preços",unitBox:"Caixa",unitEach:"Un",unitPallet:"Palete",costBreakdown:"Detalhes Custos"},
ru:{tabSummary:"Сводка",tabProducts:"Рег. товаров",tabOptimize:"Оптимизация",tabMix:"Микс каналов",tabRepricer:"Авто-цена",tabCompetitor:"Конкуренты",tabChannelFee:"Комиссии",tabGuide:"Руководство",tabCalendar:"Календарь акций",tabScenario:"Сценарий",pageTitle:"Оптимизация цен",pageSub:"Оптимизация цен в реальном времени",regProduct:"Товары",items:"шт",channelResult:"Результаты каналов",currentPrice:"Текущая цена",optimalPrice:"Оптимальная цена",refresh:"Обновить",productName:"Название товара",category:"Категория",purchaseCost:"Закупочная цена",shippingFee:"Доставка",saveProduct:"Сохранить",noProducts:"Нет товаров",calcParams:"Параметры",labelChannel:"Канал",allUnified:"Все",currentSalePrice:"Текущая цена продажи",stockQty:"Кол-во на складе",calculating:"Расчёт...",calcOptimal:"Рассчитать оптимум",totalProfit:"Общая прибыль",register:"Зарегистрировать",activeRules:"Активные правила",autoRules:"Авто-правила",channelFeeTitle:"Комиссии каналов",guideTitle:"Руководство по оптимизации цен",unitBox:"Коробка",unitEach:"Шт",unitPallet:"Паллет",costBreakdown:"Состав затрат"},
ar:{tabSummary:"ملخص",tabProducts:"تسجيل المنتجات",tabOptimize:"تحسين",tabMix:"مزيج القنوات",tabRepricer:"السعر التلقائي",tabCompetitor:"المنافسون",tabChannelFee:"رسوم القنوات",tabGuide:"الدليل",tabCalendar:"تقويم العروض",tabScenario:"سيناريو",pageTitle:"تحسين الأسعار",pageSub:"تحسين الأسعار في الوقت الفعلي",regProduct:"المنتجات",items:"عنصر",channelResult:"نتائج القنوات",currentPrice:"السعر الحالي",optimalPrice:"السعر الأمثل",refresh:"تحديث",productName:"اسم المنتج",category:"الفئة",purchaseCost:"سعر الشراء",shippingFee:"الشحن",saveProduct:"حفظ",noProducts:"لا توجد منتجات",calcParams:"المعلمات",labelChannel:"القناة",allUnified:"الكل",currentSalePrice:"سعر البيع الحالي",stockQty:"كمية المخزون",calculating:"جارٍ الحساب...",calcOptimal:"حساب الأمثل",totalProfit:"إجمالي الربح",register:"تسجيل",activeRules:"القواعد النشطة",autoRules:"القواعد التلقائية",channelFeeTitle:"رسوم القنوات",guideTitle:"دليل تحسين الأسعار",unitBox:"صندوق",unitEach:"قطعة",unitPallet:"منصة نقالة",costBreakdown:"تفاصيل التكلفة"},
hi:{tabSummary:"सारांश",tabProducts:"उत्पाद पंजीकरण",tabOptimize:"अनुकूलन",tabMix:"चैनल मिक्स",tabRepricer:"ऑटो मूल्य",tabCompetitor:"प्रतिस्पर्धी",tabChannelFee:"चैनल शुल्क",tabGuide:"गाइड",tabCalendar:"प्रोमो कैलेंडर",tabScenario:"परिदृश्य",pageTitle:"मूल्य अनुकूलन",pageSub:"वास्तविक समय मूल्य अनुकूलन",regProduct:"उत्पाद",items:"आइटम",channelResult:"चैनल परिणाम",currentPrice:"वर्तमान मूल्य",optimalPrice:"इष्टतम मूल्य",refresh:"रिफ़्रेश",productName:"उत्पाद का नाम",category:"श्रेणी",purchaseCost:"खरीद मूल्य",shippingFee:"शिपिंग",saveProduct:"सहेजें",noProducts:"कोई उत्पाद नहीं",calcParams:"पैरामीटर",labelChannel:"चैनल",allUnified:"सभी",currentSalePrice:"वर्तमान बिक्री मूल्य",stockQty:"स्टॉक मात्रा",calculating:"गणना हो रही है...",calcOptimal:"इष्टतम गणना",totalProfit:"कुल लाभ",register:"पंजीकरण",activeRules:"सक्रिय नियम",autoRules:"ऑटो नियम",channelFeeTitle:"चैनल शुल्क",guideTitle:"मूल्य अनुकूलन गाइड",unitBox:"बॉक्स",unitEach:"नग",unitPallet:"पैलेट",costBreakdown:"लागत विवरण"},
};
Object.entries(patches).forEach(([lang,p])=>{
  if(!D[lang])D[lang]={...D.en};
  Object.assign(D[lang],p);
});
let out='const D={\n';
Object.entries(D).forEach(([lang,obj])=>{
  out+=JSON.stringify(lang)+':{';
  const entries=Object.entries(obj);
  entries.forEach(([k,v],i)=>{out+=JSON.stringify(k)+':'+JSON.stringify(v);if(i<entries.length-1)out+=',';});
  out+='},\n';
});
out+='};\nexport default D;\n';
fs.writeFileSync('src/pages/poI18n.js',out);
console.log('poI18n.js patched: '+Object.keys(D).length+' langs');
