const fs=require('fs'),path=require('path'),dir=__dirname+'/src/i18n/locales/';
function inj(f,d){const p=path.join(dir,f);let s=fs.readFileSync(p,'utf8');const ei=s.indexOf('"sms":{');if(ei>0){let dd=0,i=s.indexOf('{',ei+5);for(;i<s.length;i++){if(s[i]==='{')dd++;else if(s[i]==='}'){dd--;if(dd===0){i++;break;}}}let c=ei;if(c>0&&s[c-1]===',')c--;s=s.substring(0,c)+s.substring(i);}const lb=s.lastIndexOf('}');s=s.substring(0,lb)+',"sms":'+JSON.stringify(d)+s.substring(lb);fs.writeFileSync(p,s);try{delete require.cache[require.resolve(p)];require(p);console.log('OK',f);}catch(e){console.log('ERR',f,e.message.slice(0,60));}}
const en=require('./src/i18n/locales/en.js');const enSms=(en.default||en).sms;const keys=Object.keys(enSms);
function build(vals){const o={};keys.forEach((k,i)=>o[k]=vals[i]||enSms[k]);return o;}

// Map of language -> overrides for key visible strings (heroTitle, tabs, guide titles etc.)
const overrides={
zh:{heroTitle:"短信营销",heroDesc:"编写·群发·模板·活动管理",tabCompose:"✏️ 编写",tabBroadcast:"📡 群发",tabTemplates:"📋 模板",tabCampaigns:"🚀 活动",tabHistory:"📜 历史",tabStats:"📊 统计",tabCreative:"🎨 创意",tabSettings:"⚙️ 设置",tabGuide:"📖 指南",noChannels:"未连接短信渠道",goHub:"前往中心",liveSyncStatus:"实时同步中",syncNow:"立即同步",composeTitle:"编写短信",send:"发送",broadcastTitle:"群发短信",cancel:"取消",save:"保存",edit:"编辑",delete:"删除",guideTitle:"短信营销指南",guideSub:"从编写到活动分析的详细指南",guideStepsTitle:"使用步骤",guideTabsTitle:"标签指南",guideTipsTitle:"专家提示",guideStep1Title:"选择短信服务",guideStep1Desc:"选择NHN Cloud/Aligo/CoolSMS",guideStep2Title:"API认证设置",guideStep2Desc:"注册密钥和发送号码",guideStep3Title:"注册发送号码",guideStep3Desc:"输入运营商预注册号码",guideStep4Title:"编写单条短信",guideStep4Desc:"输入收件号和消息发送",guideStep5Title:"群发",guideStep5Desc:"批量号码一键发送",guideStep6Title:"创建模板",guideStep6Desc:"保存常用消息为模板",guideStep7Title:"模板变量",guideStep7Desc:"使用变量个性化消息",guideStep8Title:"创建活动",guideStep8Desc:"设置名称模板和目标",guideStep9Title:"定时发送",guideStep9Desc:"设置计划自动发送",guideStep10Title:"查看历史",guideStep10Desc:"实时监控发送状态",guideStep11Title:"导出CSV",guideStep11Desc:"下载发送结果",guideStep12Title:"统计分析",guideStep12Desc:"查看月度发送量和成功率",guideStep13Title:"创意管理",guideStep13Desc:"管理设计资产",guideStep14Title:"优化分群",guideStep14Desc:"用CRM数据细分目标",guideStep15Title:"持续改进",guideStep15Desc:"通过A/B测试提升ROI"},
"zh-TW":{heroTitle:"簡訊行銷",heroDesc:"編寫·群發·範本·活動管理",tabCompose:"✏️ 編寫",tabBroadcast:"📡 群發",tabTemplates:"📋 範本",tabCampaigns:"🚀 活動",tabHistory:"📜 歷史",tabStats:"📊 統計",tabCreative:"🎨 創意",tabSettings:"⚙️ 設定",tabGuide:"📖 指南",noChannels:"未連接簡訊頻道",goHub:"前往中心",liveSyncStatus:"即時同步中",syncNow:"立即同步",composeTitle:"編寫簡訊",send:"發送",broadcastTitle:"群發簡訊",cancel:"取消",save:"儲存",edit:"編輯",delete:"刪除",guideTitle:"簡訊行銷指南",guideSub:"從編寫到活動分析的詳細指南",guideStepsTitle:"使用步驟",guideTabsTitle:"標籤指南",guideTipsTitle:"專家提示"},
de:{heroTitle:"SMS-Marketing",heroDesc:"Verfassen · Massenversand · Vorlagen · Kampagnen",tabCompose:"✏️ Verfassen",tabBroadcast:"📡 Massenversand",tabTemplates:"📋 Vorlagen",tabCampaigns:"🚀 Kampagnen",tabHistory:"📜 Verlauf",tabStats:"📊 Statistiken",tabCreative:"🎨 Kreativ",tabSettings:"⚙️ Einstellungen",tabGuide:"📖 Anleitung",noChannels:"Keine SMS-Kanäle verbunden",goHub:"Zum Hub",send:"Senden",cancel:"Abbrechen",save:"Speichern",edit:"Bearbeiten",delete:"Löschen",guideTitle:"SMS-Marketing Anleitung",guideSub:"Schritt-für-Schritt-Anleitung",guideStepsTitle:"Nutzungsschritte",guideTabsTitle:"Tab-Übersicht",guideTipsTitle:"Expertentipps"},
es:{heroTitle:"Marketing SMS",heroDesc:"Redactar · Difusión masiva · Plantillas · Campañas",tabCompose:"✏️ Redactar",tabBroadcast:"📡 Difusión",tabTemplates:"📋 Plantillas",tabCampaigns:"🚀 Campañas",tabHistory:"📜 Historial",tabStats:"📊 Estadísticas",tabCreative:"🎨 Creativo",tabSettings:"⚙️ Configuración",tabGuide:"📖 Guía",noChannels:"No hay canales SMS conectados",goHub:"Ir al Hub",send:"Enviar",cancel:"Cancelar",save:"Guardar",edit:"Editar",delete:"Eliminar",guideTitle:"Guía de Marketing SMS",guideSub:"Guía paso a paso",guideStepsTitle:"Pasos",guideTabsTitle:"Guía de pestañas",guideTipsTitle:"Consejos de experto"},
fr:{heroTitle:"Marketing SMS",heroDesc:"Rédiger · Envoi en masse · Modèles · Campagnes",tabCompose:"✏️ Rédiger",tabBroadcast:"📡 Envoi en masse",tabTemplates:"📋 Modèles",tabCampaigns:"🚀 Campagnes",tabHistory:"📜 Historique",tabStats:"📊 Statistiques",tabCreative:"🎨 Créatif",tabSettings:"⚙️ Paramètres",tabGuide:"📖 Guide",noChannels:"Aucun canal SMS connecté",goHub:"Aller au Hub",send:"Envoyer",cancel:"Annuler",save:"Enregistrer",edit:"Modifier",delete:"Supprimer",guideTitle:"Guide Marketing SMS",guideSub:"Guide étape par étape",guideStepsTitle:"Étapes",guideTabsTitle:"Guide des onglets",guideTipsTitle:"Conseils d'expert"},
pt:{heroTitle:"Marketing SMS",heroDesc:"Compor · Envio em massa · Modelos · Campanhas",tabCompose:"✏️ Compor",tabBroadcast:"📡 Envio em massa",tabTemplates:"📋 Modelos",tabCampaigns:"🚀 Campanhas",tabHistory:"📜 Histórico",tabStats:"📊 Estatísticas",tabCreative:"🎨 Criativo",tabSettings:"⚙️ Configurações",tabGuide:"📖 Guia",noChannels:"Nenhum canal SMS conectado",goHub:"Ir ao Hub",send:"Enviar",cancel:"Cancelar",save:"Salvar",edit:"Editar",delete:"Excluir",guideTitle:"Guia de Marketing SMS",guideSub:"Guia passo a passo",guideStepsTitle:"Etapas",guideTabsTitle:"Guia de abas",guideTipsTitle:"Dicas de especialista"},
ru:{heroTitle:"SMS-маркетинг",heroDesc:"Составление · Рассылка · Шаблоны · Кампании",tabCompose:"✏️ Составить",tabBroadcast:"📡 Рассылка",tabTemplates:"📋 Шаблоны",tabCampaigns:"🚀 Кампании",tabHistory:"📜 История",tabStats:"📊 Статистика",tabCreative:"🎨 Креатив",tabSettings:"⚙️ Настройки",tabGuide:"📖 Руководство",noChannels:"SMS-каналы не подключены",goHub:"Перейти в хаб",send:"Отправить",cancel:"Отмена",save:"Сохранить",edit:"Редактировать",delete:"Удалить",guideTitle:"Руководство по SMS",guideSub:"Пошаговое руководство",guideStepsTitle:"Шаги",guideTabsTitle:"По вкладкам",guideTipsTitle:"Советы экспертов"},
hi:{heroTitle:"SMS मार्केटिंग",heroDesc:"लिखें · बल्क भेजें · टेम्पलेट · अभियान",tabCompose:"✏️ लिखें",tabBroadcast:"📡 बल्क भेजें",tabTemplates:"📋 टेम्पलेट",tabCampaigns:"🚀 अभियान",tabHistory:"📜 इतिहास",tabStats:"📊 आंकड़े",tabCreative:"🎨 क्रिएटिव",tabSettings:"⚙️ सेटिंग्स",tabGuide:"📖 गाइड",noChannels:"कोई SMS चैनल नहीं",goHub:"हब पर जाएं",send:"भेजें",cancel:"रद्द करें",save:"सहेजें",edit:"संपादित करें",delete:"हटाएं",guideTitle:"SMS मार्केटिंग गाइड",guideSub:"चरण-दर-चरण गाइड",guideStepsTitle:"उपयोग चरण",guideTabsTitle:"टैब गाइड",guideTipsTitle:"विशेषज्ञ सुझाव"},
id:{heroTitle:"SMS Marketing",heroDesc:"Tulis · Kirim Massal · Template · Kampanye",tabCompose:"✏️ Tulis",tabBroadcast:"📡 Kirim Massal",tabTemplates:"📋 Template",tabCampaigns:"🚀 Kampanye",tabHistory:"📜 Riwayat",tabStats:"📊 Statistik",tabCreative:"🎨 Kreatif",tabSettings:"⚙️ Pengaturan",tabGuide:"📖 Panduan",noChannels:"Tidak ada saluran SMS",goHub:"Ke Hub",send:"Kirim",cancel:"Batal",save:"Simpan",edit:"Edit",delete:"Hapus",guideTitle:"Panduan SMS Marketing",guideSub:"Panduan langkah demi langkah",guideStepsTitle:"Langkah",guideTabsTitle:"Panduan tab",guideTipsTitle:"Tips ahli"},
th:{heroTitle:"การตลาด SMS",heroDesc:"เขียน · ส่งจำนวนมาก · เทมเพลต · แคมเปญ",tabCompose:"✏️ เขียน",tabBroadcast:"📡 ส่งจำนวนมาก",tabTemplates:"📋 เทมเพลต",tabCampaigns:"🚀 แคมเปญ",tabHistory:"📜 ประวัติ",tabStats:"📊 สถิติ",tabCreative:"🎨 ครีเอทีฟ",tabSettings:"⚙️ ตั้งค่า",tabGuide:"📖 คู่มือ",noChannels:"ไม่มีช่องทาง SMS",goHub:"ไปที่ฮับ",send:"ส่ง",cancel:"ยกเลิก",save:"บันทึก",edit:"แก้ไข",delete:"ลบ",guideTitle:"คู่มือการตลาด SMS",guideSub:"คู่มือทีละขั้นตอน",guideStepsTitle:"ขั้นตอน",guideTabsTitle:"คู่มือแท็บ",guideTipsTitle:"เคล็ดลับผู้เชี่ยวชาญ"},
vi:{heroTitle:"SMS Marketing",heroDesc:"Soạn · Gửi hàng loạt · Mẫu · Chiến dịch",tabCompose:"✏️ Soạn",tabBroadcast:"📡 Gửi hàng loạt",tabTemplates:"📋 Mẫu",tabCampaigns:"🚀 Chiến dịch",tabHistory:"📜 Lịch sử",tabStats:"📊 Thống kê",tabCreative:"🎨 Sáng tạo",tabSettings:"⚙️ Cài đặt",tabGuide:"📖 Hướng dẫn",noChannels:"Không có kênh SMS",goHub:"Đến Hub",send:"Gửi",cancel:"Hủy",save:"Lưu",edit:"Sửa",delete:"Xóa",guideTitle:"Hướng dẫn SMS Marketing",guideSub:"Hướng dẫn từng bước",guideStepsTitle:"Các bước",guideTabsTitle:"Hướng dẫn tab",guideTipsTitle:"Mẹo chuyên gia"}
};

for(const[lang,ov] of Object.entries(overrides)){
    // Merge: start with en values, override with localized ones
    const merged={...enSms,...ov};
    inj(lang+'.js',merged);
}
console.log('SMS i18n remaining 11 languages done');
