/**
 * translate_deep.cjs
 * Deep pass: handles compound Korean words and specific patterns
 */
const fs = require('fs');
const path = require('path');

// ─── Deep replacement map - single words and compound patterns ──────────────
const DEEP_MAP = [
  // Compound words and phrases (longer first)
  ['자동 생성', 'Auto Generate'],
  ['자동 연동', 'Auto Sync'],
  ['자동 발송', 'Auto Send'],
  ['자동 설정', 'Auto Settings'],
  ['자동 동기화', 'Auto Sync'],
  ['자동 추천', 'Auto Recommend'],
  ['자동 매핑', 'Auto Mapping'],
  ['자동 집계', 'Auto Aggregate'],
  ['자동 분류', 'Auto Classify'],
  ['자동 계산', 'Auto Calculate'],
  ['자동화 규칙', 'Automation Rule'],
  ['자동화 설정', 'Automation Settings'],
  ['자동화 실행', 'Automation Execute'],
  ['연동 설정', 'Integration Settings'],
  ['연동 관리', 'Integration Management'],
  ['연동 상태', 'Integration Status'],
  ['연동 테스트', 'Integration Test'],
  ['데이터 동기화', 'Data Sync'],
  ['데이터 수집', 'Data Collection'],
  ['데이터 내보내기', 'Data Export'],
  ['데이터 가져오기', 'Data Import'],
  ['데이터 변환', 'Data Transform'],
  ['데이터 관리', 'Data Management'],
  ['데이터 분석', 'Data Analytics'],
  ['데이터 시각화', 'Data Visualization'],
  ['데이터 품질', 'Data Quality'],
  ['데이터 파이프라인', 'Data Pipeline'],
  ['데이터 레이크', 'Data Lake'],
  ['데이터 웨어하우스', 'Data Warehouse'],
  ['데이터 마트', 'Data Mart'],
  ['데이터 모델', 'Data Model'],
  ['데이터 소스', 'Data Source'],
  ['데이터 필터', 'Data Filter'],
  ['광고 소재', 'Ad Creative'],
  ['광고 성과', 'Ad Performance'],
  ['광고 비용', 'Ad Spend'],
  ['광고 효율', 'Ad Efficiency'],
  ['광고 계정', 'Ad Account'],
  ['광고 그룹', 'Ad Group'],
  ['광고 네트워크', 'Ad Network'],
  ['광고 채널', 'Ad Channel'],
  ['광고 인사이트', 'Ad Insights'],
  ['정산 내역', 'Settlement History'],
  ['정산 기간', 'Settlement Period'],
  ['정산 금액', 'Settlement Amount'],
  ['정산 완료', 'Settlement Complete'],
  ['생성 중', 'Generating'],
  ['생성 완료', 'Created'],
  ['생성 실패', 'Create Failed'],
  ['생성 날짜', 'Created Date'],
  ['쿠폰 발급', 'Issue Coupon'],
  ['쿠폰 코드', 'Coupon Code'],
  ['쿠폰 사용', 'Coupon Use'],
  ['쿠폰 적용', 'Apply Coupon'],
  ['쿠폰 취소', 'Cancel Coupon'],
  ['쿠폰 만료', 'Coupon Expired'],
  ['이벤트 생성', 'Create Event'],
  ['이벤트 관리', 'Event Management'],
  ['이벤트 추적', 'Event Tracking'],
  ['이벤트 로그', 'Event Log'],
  ['이벤트 필터', 'Event Filter'],
  ['이벤트 유형', 'Event Type'],
  ['이벤트 데이터', 'Event Data'],
  ['이벤트 수집', 'Event Collection'],
  ['이벤트 정의', 'Event Definition'],
  ['캠페인 생성', 'Create Campaign'],
  ['캠페인 관리', 'Campaign Management'],
  ['캠페인 목록', 'Campaign List'],
  ['캠페인 성과', 'Campaign Performance'],
  ['캠페인 예산', 'Campaign Budget'],
  ['캠페인 기간', 'Campaign Period'],
  ['캠페인 상태', 'Campaign Status'],
  ['캠페인 채널', 'Campaign Channel'],
  ['캠페인 전환', 'Campaign Conversion'],
  ['고객 관리', 'Customer Management'],
  ['고객 데이터', 'Customer Data'],
  ['고객 세그먼트', 'Customer Segment'],
  ['고객 여정', 'Customer Journey'],
  ['고객 행동', 'Customer Behavior'],
  ['고객 지원', 'Customer Support'],
  ['고객 가치', 'Customer Value'],
  ['발송 설정', 'Send Settings'],
  ['발송 성과', 'Send Performance'],
  ['발송 이력', 'Send History'],
  ['발송 오류', 'Send Error'],
  ['발송 중', 'Sending'],
  ['가격 설정', 'Price Settings'],
  ['가격 변경', 'Price Change'],
  ['가격 최적화', 'Price Optimization'],
  ['가격 비교', 'Price Comparison'],
  ['가격 추천', 'Price Recommendation'],
  ['가격 시뮬레이션', 'Price Simulation'],
  ['국내 채널', 'Domestic Channel'],
  ['국내 마켓', 'Domestic Market'],
  ['국내 배송', 'Domestic Shipping'],
  ['유료 플랜', 'Paid Plan'],
  ['유료 구독', 'Paid Subscription'],
  ['유료 기능', 'Paid Feature'],
  ['픽셀 설정', 'Pixel Settings'],
  ['픽셀 연동', 'Pixel Integration'],
  ['픽셀 추적', 'Pixel Tracking'],
  ['픽셀 코드', 'Pixel Code'],
  ['픽셀 이벤트', 'Pixel Event'],
  ['통합 대시보드', 'Integrated Dashboard'],
  ['통합 관리', 'Integrated Management'],
  ['통합 설정', 'Integrated Settings'],
  ['통합 보고서', 'Integrated Report'],
  ['플랫폼 연동', 'Platform Integration'],
  ['플랫폼 설정', 'Platform Settings'],
  ['플랫폼 수수료', 'Platform Fee'],
  ['전환 추적', 'Conversion Tracking'],
  ['전환 목표', 'Conversion Goal'],
  ['전환 성과', 'Conversion Performance'],
  ['전환 率', 'Conversion Rate'],
  ['실시간 분석', 'Real-time Analytics'],
  ['실시간 데이터', 'Real-time Data'],
  ['실시간 현황', 'Real-time Status'],
  ['실시간 알림', 'Real-time Alert'],
  ['실제 데이터', 'Live Data'],
  ['권한 설정', 'Permission Settings'],
  ['권한 관리', 'Permission Management'],
  ['권한 변경', 'Permission Change'],
  ['액션 설정', 'Action Settings'],
  ['액션 실행', 'Execute Action'],
  ['액션 로그', 'Action Log'],
  ['글로벌 설정', 'Global Settings'],
  ['글로벌 마켓', 'Global Market'],
  ['글로벌 연동', 'Global Integration'],
  ['기능 설정', 'Feature Settings'],
  ['기능 관리', 'Feature Management'],
  ['기능 잠금', 'Feature Lock'],
  ['기능 미지원', 'Feature Not Supported'],
  ['팀 관리', 'Team Management'],
  ['팀 설정', 'Team Settings'],
  ['팀 멤버', 'Team Member'],
  ['팀 협업', 'Team Collaboration'],
  ['요금 설정', 'Pricing Settings'],
  ['요금 계획', 'Pricing Plan'],
  ['요금 비교', 'Pricing Comparison'],
  ['총 매출', 'Total Revenue'],
  ['총 비용', 'Total Cost'],
  ['총 이익', 'Total Profit'],
  ['총 주문', 'Total Orders'],
  ['총 고객', 'Total Customers'],
  ['총 광고비', 'Total Ad Spend'],
  ['룰 설정', 'Rule Settings'],
  ['룰 목록', 'Rule List'],
  ['룰 관리', 'Rule Management'],
  ['룰 실행', 'Rule Execute'],
  ['룰 테스트', 'Rule Test'],
  ['헤더 설정', 'Header Settings'],
  ['가능한', 'Available'],
  ['불가능한', 'Unavailable'],
  ['이상 감지', 'Anomaly Detection'],
  ['이상 없음', 'No Anomaly'],
  ['이상 있음', 'Anomaly Detected'],
  ['즉시 실행', 'Execute Now'],
  ['즉시 발송', 'Send Now'],
  ['즉시 동기화', 'Sync Now'],
  ['즉시 적용', 'Apply Now'],
  ['동기화 중', 'Syncing'],
  ['동기화 완료', 'Sync Complete'],
  ['동기화 실패', 'Sync Failed'],
  ['추천 설정', 'Recommendation Settings'],
  ['추천 목록', 'Recommendation List'],
  ['추천 상품', 'Recommended Products'],
  ['후 처리', 'Post Processing'],
  ['집계 설정', 'Aggregation Settings'],
  ['입력 오류', 'Input Error'],
  ['입력 확인', 'Confirm Input'],
  ['입력 값', 'Input Value'],
  ['입력 필드', 'Input Field'],
  ['플랜 변경', 'Plan Change'],
  ['플랜 업그레이드', 'Plan Upgrade'],
  ['플랜 다운그레이드', 'Plan Downgrade'],
  ['플랜 만료', 'Plan Expired'],
  ['픽셀', 'Pixel'],
  ['데모', 'Demo'],
  ['팀', 'Team'],

  // Single Korean compound/standalone words most frequently appearing
  ['자동', 'Auto'],
  ['연동', 'Integration'],
  ['생성', 'Create'],
  ['동기화', 'Sync'],
  ['발송', 'Send'],
  ['마케팅', 'Marketing'],
  ['고객', 'Customer'],
  ['승인', 'Approval'],
  ['추천', 'Recommend'],
  ['통합', 'Unified'],
  ['플랫폼', 'Platform'],
  ['전환', 'Conversion'],
  ['권한', 'Permission'],
  ['액션', 'Action'],
  ['실시간', 'Realtime'],
  ['글로벌', 'Global'],
  ['기능', 'Feature'],
  ['룰', 'Rule'],
  ['헤더', 'Header'],
  ['요금', 'Pricing'],
  ['총', 'Total'],
  ['쿠폰', 'Coupon'],
  ['캠페인', 'Campaign'],
  ['이벤트', 'Event'],
  ['광고', 'Ad'],
  ['탭', 'Tab'],
  ['가격', 'Price'],
  ['국내', 'Domestic'],
  ['유료', 'Paid'],
  ['픽셀', 'Pixel'],
  ['데모', 'Demo'],
  ['팀', 'Team'],
  ['중', 'in progress'],  // standalone
  ['별', 'per'],  // as suffix

  // Common suffix patterns
  ['관련', 'Related'],
  ['별도', 'Separate'],
  ['필수', 'Required'],
  ['선택', 'Optional'],
  ['기본', 'Default'],
  ['고급', 'Advanced'],
  ['최신', 'Latest'],
  ['이전', 'Previous'],
  ['다음', 'Next'],
  ['이후', 'After'],
  ['이전', 'Before'],
  ['전체', 'All'],
  ['부분', 'Partial'],
  ['개인', 'Personal'],
  ['공개', 'Public'],
  ['비공개', 'Private'],
  ['임시', 'Temporary'],
  ['영구', 'Permanent'],
  ['일반', 'General'],
  ['특별', 'Special'],
  ['사용자', 'User'],
  ['관리자', 'Admin'],
  ['이메일', 'Email'],
  ['메시지', 'Message'],
  ['알림', 'Alert'],
  ['노티피케이션', 'Notification'],
  ['결제', 'Payment'],
  ['구독', 'Subscription'],
  ['계획', 'Plan'],
  ['보고서', 'Report'],
  ['분석', 'Analytics'],
  ['성과', 'Performance'],
  ['수익', 'Revenue'],
  ['비용', 'Cost'],
  ['예산', 'Budget'],
  ['목표', 'Goal'],
  ['지표', 'Metric'],
  ['집계', 'Aggregate'],
  ['평균', 'Average'],
  ['합계', 'Total'],
  ['비율', 'Rate'],
  ['증가', 'Increase'],
  ['감소', 'Decrease'],
  ['변동', 'Change'],
  ['추세', 'Trend'],
  ['예측', 'Forecast'],
  ['비교', 'Compare'],
  ['순위', 'Rank'],
  ['점수', 'Score'],
  ['등급', 'Grade'],
  ['등록', 'Register'],
  ['수정', 'Edit'],
  ['삭제', 'Delete'],
  ['저장', 'Save'],
  ['취소', 'Cancel'],
  ['적용', 'Apply'],
  ['초기화', 'Reset'],
  ['새로고침', 'Refresh'],
  ['검색', 'Search'],
  ['필터', 'Filter'],
  ['정렬', 'Sort'],
  ['내보내기', 'Export'],
  ['가져오기', 'Import'],
  ['업로드', 'Upload'],
  ['다운로드', 'Download'],
  ['복사', 'Copy'],
  ['이동', 'Move'],
  ['공유', 'Share'],
  ['연결', 'Connect'],
  ['해제', 'Disconnect'],
  ['활성화', 'Activate'],
  ['비활성화', 'Deactivate'],
  ['차단', 'Block'],
  ['허용', 'Allow'],
  ['실행', 'Execute'],
  ['중지', 'Stop'],
  ['일시중지', 'Pause'],
  ['재시작', 'Restart'],
  ['종료', 'End'],
  ['시작', 'Start'],
  ['완료', 'Complete'],
  ['대기', 'Pending'],
  ['진행', 'In Progress'],
  ['실패', 'Failed'],
  ['성공', 'Success'],
  ['오류', 'Error'],
  ['경고', 'Warning'],
  ['정보', 'Info'],
  ['없음', 'None'],
  ['있음', 'Present'],
  ['다중', 'Multiple'],
  ['단일', 'Single'],
  ['무제한', 'Unlimited'],
  ['제한', 'Limit'],
  ['용량', 'Capacity'],
  ['저장소', 'Storage'],
  ['공간', 'Space'],
  ['크기', 'Size'],
  ['수량', 'Quantity'],
  ['개수', 'Count'],
  ['페이지', 'Page'],
  ['화면', 'Screen'],
  ['패널', 'Panel'],
  ['모달', 'Modal'],
  ['팝업', 'Popup'],
  ['드롭다운', 'Dropdown'],
  ['체크박스', 'Checkbox'],
  ['라디오', 'Radio'],
  ['토글', 'Toggle'],
  ['슬라이더', 'Slider'],
  ['아이콘', 'Icon'],
  ['이미지', 'Image'],
  ['배너', 'Banner'],
  ['카드', 'Card'],
  ['목록', 'List'],
  ['테이블', 'Table'],
  ['차트', 'Chart'],
  ['그래프', 'Graph'],
  ['대시보드', 'Dashboard'],
  ['위젯', 'Widget'],
  ['컴포넌트', 'Component'],
  ['레이아웃', 'Layout'],
  ['스타일', 'Style'],
  ['테마', 'Theme'],
  ['폰트', 'Font'],
  ['색상', 'Color'],
  ['크기', 'Size'],
  ['간격', 'Spacing'],
  ['여백', 'Margin'],
  ['패딩', 'Padding'],
  ['그림자', 'Shadow'],
  ['테두리', 'Border'],
  ['배경', 'Background'],
  ['앞면', 'Front'],
  ['뒷면', 'Back'],
  ['상단', 'Top'],
  ['하단', 'Bottom'],
  ['왼쪽', 'Left'],
  ['오른쪽', 'Right'],
  ['가운데', 'Center'],
  ['정렬', 'Align'],
  ['세로', 'Vertical'],
  ['가로', 'Horizontal'],
];

function applyReplacements(content, replacements) {
  let result = content;
  for (const [ko, en] of replacements) {
    result = result.split(ko).join(en);
  }
  return result;
}

const PAGES_DIR = path.join(__dirname, 'src/pages');
const allFiles = fs.readdirSync(PAGES_DIR).filter(f => f.endsWith('.jsx') || f.endsWith('.js'));

let totalChanged = 0;

for (const filename of allFiles) {
  const filepath = path.join(PAGES_DIR, filename);
  let content = fs.readFileSync(filepath, 'utf8');
  const before = content;
  content = applyReplacements(content, DEEP_MAP);
  if (content !== before) {
    fs.writeFileSync(filepath, content, 'utf8');
    console.log(`✓ ${filename}`);
    totalChanged++;
  }
}

console.log(`\nDone! ${totalChanged} files updated.`);
