/**
 * translate_all_files.cjs
 * Korean → English direct string replacement for ALL remaining JSX files
 */
const fs = require('fs');
const path = require('path');

// ─── Universal Korean→English replacement pairs ────────────────────────────
// Ordered longest-first to prevent partial replacements
const UNIVERSAL_MAP = [
  // Admin.jsx specific
  ['조회 Failed', 'Lookup Failed'],
  ['User 목록 조회 Failed (데모 데이터 표시)', 'Failed to load user list (showing demo data)'],
  ['Name, Email, Password를 모두 입력하세요.', 'Please enter Name, Email and Password.'],
  ['User가 Register되었습니다.', 'User has been registered.'],
  ['Plan이 변경되었습니다.', 'Plan has been updated.'],
  ['변경 Failed', 'Update Failed'],
  ['Account이 비Active화되었습니다.', 'Account has been deactivated.'],
  ['Account이 Active화되었습니다.', 'Account has been activated.'],
  ['Password를 Reset하시겠습니까? 임시 Password가 발급됩니다.', 'Reset password? A temporary password will be issued.'],
  ['임시 Password: ', 'Temporary password: '],
  ['(서버 Email 발송)', '(sent via server email)'],
  ['Reset Failed', 'Reset Failed'],
  ['신규 User Register', 'Register New User'],
  ['8자 이상', '8+ characters'],
  ['Plan·권한', 'Plan & Role'],
  ['Register 중...', 'Registering...'],
  ['✓ Register하기', '✓ Register'],
  ['User 목록 로드 중...', 'Loading user list...'],
  ['Register된 User가 없습니다.', 'No registered users.'],
  ['👥 User 목록 (', '👥 User List ('],
  ['비Active', 'Inactive'],
  ['Active화', 'Activate'],
  ['비Active화', 'Deactivate'],
  ['가입일', 'Join Date'],
  ['Plan 변경', 'Change Plan'],
  ['변경↗', 'Edit↗'],
  ['작업', 'Actions'],
  ['📭 Register된 User가 없습니다.', '📭 No registered users.'],
  ['Bearer key를 입력하세요', 'Enter Bearer key'],
  ['지금 바로 복사하세요 (다시 표시되지 않음)', 'Copy now — will not be shown again'],
  ['복사', 'Copy'],
  ['+ 🔑 API Key 발급', '+ 🔑 Issue API Key'],
  ['발급', 'Issue'],
  ['미사용', 'Unused'],
  ['폐기', 'Revoke'],
  ['API Key 없음 → 위에서 발급하세요', 'No API Keys → Issue one above'],
  ['마지막: ', 'Last used: '],
  ['미연결', 'Disconnected'],
  ['요청 중…', 'Requesting…'],
  ['Report 조회', 'Fetch Report'],
  ['Reports 조회', 'Fetch Reports'],
  ['개 리포트', ' Reports'],
  ['건\u003c/span\u003e', ' items</span>'],
  ['/* ── Admin User Management 패널 */', '/* ── Admin User Management Panel */'],
  ['/* ── API Key Panel */', '/* ── API Key Panel */'],
  ['/* ── Connector Test Panel */', '/* ── Connector Test Panel */'],
  ['/* ── Main Admin Page */', '/* ── Main Admin Page */'],
  ['/* ── 라이선스 키 발급 패널 */', '/* ── License Key Issuance Panel */'],
  ['/* ── 피드백 관리 패널 */', '/* ── Feedback Management Panel */'],
  ['/* ── Free 쿠폰 관리 패널 */', '/* ── Free Coupon Management Panel */'],
  ['라이선스 키 발급 Done: ', 'License key issued: '],
  ['(서버 발급)', '(issued by server)'],
  ['발급 Failed', 'Issue Failed'],
  ['🎫 라이선스 키 발급', '🎫 Issue License Key'],
  ['대상 User *', 'Target User *'],
  ['-- User 선택 --', '-- Select User --'],
  ['발급 Plan', 'Issue Plan'],
  ['유효기간 (일)', 'Valid Period (days)'],
  ['발급 중...', 'Issuing...'],
  ['📋 발급된 라이선스 목록', '📋 Issued License List'],
  ['발급된 라이선스 키가 없거나 조회할 수 없습니다.', 'No issued licenses or unable to retrieve.'],
  ['만료일', 'Expiry Date'],
  ['만료', 'Expired'],
  ['무기한', 'No Expiry'],
  ['불편사항·버그', 'Issue & Bug'],
  ['개선 의견', 'Improvement'],
  ['신규 기능 요청', 'Feature Request'],
  ['낙음', 'Low'],
  ['보통', 'Normal'],
  ['높음', 'High'],
  ['긴급', 'Urgent'],
  ['접수됨', 'Received'],
  ['검토 중', 'Reviewing'],
  ['개선 예정', 'Planned'],
  ['처리 Done', 'Completed'],
  ['미반영', 'Rejected'],
  ['신규 접수', 'New'],
  ['All 유형', 'All Types'],
  ['All 우선순위', 'All Priorities'],
  ['All Status', 'All Status'],
  ['User / 제목', 'User / Title'],
  ['우선순위', 'Priority'],
  ['❌ 피드백이 없습니다', '❌ No feedbacks'],
  ['Admin 답변 Register', 'Admin Reply Saved'],
  ['피드백에 Admin 답변이 Register되었습니다.', 'Admin reply has been saved for the feedback.'],
  ['답변이 Register되었습니다.', 'Reply has been saved.'],
  ['신규회원 가입 시', 'New Member Signup'],
  ['홍길동', 'John Doe'],
  ['제목· User Search', 'Search by Title or User'],
  ['건 표시 중', ' items displayed'],
  ['카테고리', 'Category'],
  ['담당자', 'Assignee'],

  // Common UI patterns
  ['조회', 'Search'],
  ['목록', 'List'],
  ['변경', 'Change'],
  ['관리', 'Management'],
  ['설정', 'Settings'],
  ['등록', 'Register'],
  ['삭제', 'Delete'],
  ['저장', 'Save'],
  ['취소', 'Cancel'],
  ['확인', 'Confirm'],
  ['닫기', 'Close'],
  ['추가', 'Add'],
  ['수정', 'Edit'],
  ['복사', 'Copy'],
  ['내보내기', 'Export'],
  ['가져오기', 'Import'],
  ['필터', 'Filter'],
  ['검색', 'Search'],
  ['새로고침', 'Refresh'],
  ['로딩', 'Loading'],
  ['업로드', 'Upload'],
  ['다운로드', 'Download'],

  // Status messages
  ['저장 중...', 'Saving...'],
  ['로드 중...', 'Loading...'],
  ['처리 중...', 'Processing...'],
  ['업로드 중...', 'Uploading...'],
  ['다운로드 중...', 'Downloading...'],
  ['연결 중...', 'Connecting...'],
  ['전송 중...', 'Sending...'],
  ['검증 중...', 'Validating...'],
  ['비교 중...', 'Comparing...'],
  ['분석 중...', 'Analyzing...'],
  ['생성 중...', 'Creating...'],
  ['업데이트 중...', 'Updating...'],
  ['가져오는 중...', 'Importing...'],
  ['내보내는 중...', 'Exporting...'],
  ['로그인 중...', 'Logging in...'],

  // Korean status text
  ['연결됨', 'Connected'],
  ['연결 안됨', 'Disconnected'],
  ['완료', 'Complete'],
  ['실패', 'Failed'],
  ['성공', 'Success'],
  ['진행 중', 'In Progress'],
  ['대기 중', 'Pending'],
  ['취소됨', 'Cancelled'],
  ['오류', 'Error'],
  ['경고', 'Warning'],
  ['정보', 'Info'],
  ['없음', 'None'],
  ['전체', 'All'],
  ['선택', 'Select'],
  ['선택됨', 'Selected'],

  // Date/time
  ['오늘', 'Today'],
  ['어제', 'Yesterday'],
  ['이번 주', 'This Week'],
  ['지난 주', 'Last Week'],
  ['이번 달', 'This Month'],
  ['지난 달', 'Last Month'],
  ['최근 7일', 'Last 7 Days'],
  ['최근 30일', 'Last 30 Days'],
  ['최근 90일', 'Last 90 Days'],
  ['일간', 'Daily'],
  ['주간', 'Weekly'],
  ['월간', 'Monthly'],
  ['연간', 'Yearly'],
  ['날짜', 'Date'],
  ['시간', 'Time'],
  ['기간', 'Period'],
  ['시작일', 'Start Date'],
  ['종료일', 'End Date'],
  ['등록일', 'Registration Date'],
  ['수정일', 'Modified Date'],
  ['만료일', 'Expiry Date'],

  // Common labels
  ['이름', 'Name'],
  ['이메일', 'Email'],
  ['비밀번호', 'Password'],
  ['전화번호', 'Phone'],
  ['주소', 'Address'],
  ['국가', 'Country'],
  ['언어', 'Language'],
  ['통화', 'Currency'],
  ['상태', 'Status'],
  ['유형', 'Type'],
  ['설명', 'Description'],
  ['메모', 'Note'],
  ['태그', 'Tag'],
  ['카테고리', 'Category'],
  ['이미지', 'Image'],
  ['파일', 'File'],
  ['링크', 'Link'],
  ['버튼', 'Button'],
  ['텍스트', 'Text'],
  ['값', 'Value'],
  ['단위', 'Unit'],
  ['합계', 'Total'],
  ['평균', 'Average'],
  ['최소', 'Min'],
  ['최대', 'Max'],
  ['수량', 'Quantity'],
  ['수', 'Count'],
  ['페이지', 'Page'],
  ['순서', 'Order'],
  ['순위', 'Rank'],
  ['점수', 'Score'],
  ['비율', 'Rate'],
  ['비중', 'Weight'],
];

// ─── File-specific patches ─────────────────────────────────────────────────
const FILE_PATCHES = {
  'Admin.jsx': [
    ['User를 선택하세요.', 'Please select a user.'],
    ['✓ 라이선스 키 발급 Done', '✓ License key issued'],
    ['대상 User *', 'Target User *'],
    ['발급 Plan', 'Plan to Issue'],
    ['유효기간 (일)', 'Validity (days)'],
    ['⏳ 발급 중...', '⏳ Issuing...'],
    ['🎫 라이선스 키 발급', '🎫 Issue License Key'],
    ['📋 발급된 라이선스 목록', '📋 Issued Licenses'],
    ['📭 발급된 라이선스 키가 없거나 조회할 수 없습니다.', '📭 No licenses issued or unable to retrieve.'],
    ['가입일', 'Joined'],
    ['Plan 변경', 'Change Plan'],
    ['작업', 'Actions'],
    ['🆕 신규 User Register', '🆕 Register New User'],
    ['8자 이상', '8+ characters'],
    ['Plan·권한', 'Plan & Role'],
    ['Register 중...', 'Registering...'],
    ['✓ Register하기', '✓ Register'],
    ['👥 User 목록 (', '👥 User List ('],
    ['명)', ' users)'],
    ['⏳ User 목록 로드 중...', '⏳ Loading user list...'],
    ['📭 Register된 User가 없습니다.', '📭 No registered users.'],
    ['복사\u003c/button\u003e', 'Copy</button>'],
    ['+ Admin·User Register', '+ Add User'],
    ['+ 🔑 API Key 발급', '+ 🔑 Issue API Key'],
    ['📊 Report 조회', '📊 Fetch Report'],
    ['📦 Reports 조회', '📦 Fetch Reports'],
    ['🎫 라이선스 키 발급', '🎫 Issue License Key'],
    ['Status가 ', 'Status changed to '],
    ['으로 변경되었습니다.', '.'],
    ['리뷰 감성 Analysis Excel Export', 'Review Sentiment Analysis Excel Export'],
    ['PnL Dashboard 모바일 화면 깨짐', 'PnL Dashboard Mobile Layout Issue'],
    ['사이드바 접기는 기능 Add', 'Request: Collapsible Sidebar Feature'],
    ['Operations Hub Product 일괄 업로드 기능 Add', 'Operations Hub: Batch Product Upload Feature'],
    ['Connectors TikTok 토큰 갱신 Error', 'Connectors TikTok Token Refresh Error'],
    ['현재 Product Register이 1건씩만 가능해 대량 Register 시 불편합니다. CSV 일괄 업로드를 Add해주세요.', 'Currently only one product can be registered at a time, which is inconvenient for bulk registration. Please add CSV batch upload.'],
    ['토큰 갱신 Clicks 시 간햗적으로 Error가 발생합니다.', 'Intermittent errors occur when clicking token refresh.'],
    ['Reviews & UGC의 감성 Analysis 결과를 Excel로 다운로드하고 싶습니다.', 'I would like to download the sentiment analysis results from Reviews & UGC as Excel.'],
    ['아이팬에서 접속 시 KPI 카드가 검친 화면 밖으로 덮침니다.', 'When accessed on iPad, KPI cards overflow outside the screen.'],
    ['사이드바를 완전히 접어 문서 영역을 확대할 수 있으면 좋겠습니다.', 'It would be great to fully collapse the sidebar to expand the document area.'],
    ['March 릴리즈에 CSV 업로드 반영 예정', 'CSV upload planned for March release'],
    ['Edit Done (v422.3.1 패치)', 'Fixed (v422.3.1 patch)'],
    ['첫 가입자 선물 30일', '30-day gift for new signups'],
    ['쿠폰 Test', 'Coupon Test'],
    ['한 이하', ' or less'],
    ['기타', 'Other'],
    ['답변을 입력하세요...', 'Enter reply...'],
    ['저장 중...', 'Saving...'],
    ['피드백 답변 등록', 'Submit Reply'],
    ['관리자 답변', 'Admin Reply'],
    ['미구현 시 무시', 'ignore if endpoint not implemented'],
    ['엔드포인트', 'endpoint'],
    ['접수된 피드백이 없습니다', 'No feedbacks received'],
    ['햸들링', 'Handling'],
    ['커다', 'Menu'],
    ['신규회원 가입 시', 'On New Signup'],
    ['김지체', 'James Kim'],
    ['이서점', 'Sarah Lee'],
    ['박민준', 'Min-jun Park'],
    ['최수현', 'Soo-hyun Choi'],
    ['정성화', 'Sung-hwa Jung'],
  ],
  'WmsManager.jsx': [
    ['창고', 'Warehouse'],
    ['입고', 'Inbound'],
    ['출고', 'Outbound'],
    ['재고', 'Inventory'],
    ['로케이션', 'Location'],
    ['바코드', 'Barcode'],
    ['발주', 'Purchase Order'],
    ['불량', 'Defective'],
    ['검수', 'Inspection'],
    ['적재', 'Loading'],
    ['하역', 'Unloading'],
    ['위치', 'Position'],
    ['현황', 'Status'],
    ['수정', 'Edit'],
    ['이동', 'Move'],
    ['복구', 'Restore'],
    ['서울', 'Seoul'],
    ['부산', 'Busan'],
    ['인천', 'Incheon'],
    ['대구', 'Daegu'],
    ['광주', 'Gwangju'],
    ['허브', 'Hub'],
    ['인천국제', 'Incheon International'],
    ['강서구', 'Gangseo-gu'],
  ],
  'AIRuleEngine.jsx': [
    ['룰 엔진', 'Rule Engine'],
    ['규칙', 'Rule'],
    ['조건', 'Condition'],
    ['액션', 'Action'],
    ['트리거', 'Trigger'],
    ['실행', 'Execute'],
    ['테스트', 'Test'],
    ['로그', 'Log'],
    ['정책', 'Policy'],
    ['자동화', 'Automaton'],
    ['인사이트', 'Insight'],
    ['예측', 'Prediction'],
    ['분류', 'Classification'],
    ['추천', 'Recommendation'],
    ['광고', 'Ad'],
  ],
  'OrderHub.jsx': [
    ['주문', 'Order'],
    ['배송', 'Shipping'],
    ['클레임', 'Claim'],
    ['반품', 'Return'],
    ['교환', 'Exchange'],
    ['취소', 'Cancel'],
    ['묶음', 'Bundle'],
    ['부분출고', 'Partial Ship'],
    ['전체출고', 'Full Ship'],
    ['부분취소', 'Partial Cancel'],
    ['창고분산', 'Split Warehouse'],
    ['수령인', 'Recipient'],
    ['수취인', 'Consignee'],
    ['출하', 'Shipment'],
    ['집하', 'Collection'],
    ['통관', 'Customs'],
    ['면세', 'Duty Free'],
    ['과세', 'Taxable'],
  ],
  'ApiKeys.jsx': [
    ['커머스', 'Commerce'],
    ['마켓플레이스', 'Marketplace'],
    ['테넌트', 'Tenant'],
    ['판매자', 'Seller'],
    ['공급자', 'Supplier'],
    ['파트너', 'Partner'],
    ['웹훅', 'Webhook'],
    ['인증', 'Auth'],
    ['권한', 'Permission'],
    ['역할', 'Role'],
    ['발급', 'Issue'],
    ['갱신', 'Renew'],
    ['만료', 'Expired'],
    ['활성', 'Active'],
    ['비활성', 'Inactive'],
  ],
};

function applyReplacements(content, replacements) {
  let result = content;
  for (const [ko, en] of replacements) {
    result = result.split(ko).join(en);
  }
  return result;
}

const PAGES_DIR = path.join(__dirname, 'src/pages');

// Get all JSX files
const allFiles = fs.readdirSync(PAGES_DIR).filter(f => f.endsWith('.jsx') || f.endsWith('.js'));

let totalChanged = 0;

for (const filename of allFiles) {
  const filepath = path.join(PAGES_DIR, filename);
  let content = fs.readFileSync(filepath, 'utf8');
  const before = content;
  
  // Apply file-specific patches first
  const filePatches = FILE_PATCHES[filename];
  if (filePatches) {
    content = applyReplacements(content, filePatches);
  }
  
  // Apply universal replacements
  content = applyReplacements(content, UNIVERSAL_MAP);
  
  if (content !== before) {
    fs.writeFileSync(filepath, content, 'utf8');
    console.log(`✓ ${filename} updated`);
    totalChanged++;
  }
}

console.log(`\nDone! ${totalChanged} files updated.`);
