const fs=require('fs'),path=require('path');
const DIR=path.join(__dirname,'src/i18n/locales');
function apply(locale,trans){
    const fp=path.join(DIR,locale+'.js');
    const c=fs.readFileSync(fp,'utf8');
    const m=c.match(/export\s+default\s+(\{[\s\S]*\})\s*;?\s*$/);
    const obj=eval('('+m[1]+')');
    if(!obj.wms)obj.wms={};
    Object.entries(trans).forEach(([k,v])=>{obj.wms[k]=v;});
    const out='export default '+JSON.stringify(obj)+'\n';
    fs.writeFileSync(fp,out);
    try{eval('('+JSON.stringify(obj)+')');console.log(locale+': '+Object.keys(trans).length+' keys OK');}
    catch(e){console.log(locale+': BROKEN');}
}

const ES={
securityBtn:'🛡️ Monitor de seguridad',securityTitle:'Monitor de detección de amenazas',securityDesc:'Detección y bloqueo de amenazas en tiempo real',securitySafe:'Estado: Seguro',securitySafeDesc:'No se han detectado amenazas de seguridad.',
permBtn:'🔑 Gestión de permisos',permTitle:'Permisos por almacén',permDesc:'Gestione los permisos de acceso por usuario. Los permisos varían según el rol.',permUserLabel:'Email',permRoleLabel:'Rol',permAddBtn:'Añadir permiso',permColUser:'Usuario',permColRole:'Rol',permColAction:'Gestión',permRoleAdmin:'Administrador',permRoleManager:'Gerente',permRoleOperator:'Operador',permRoleViewer:'Visor',permEmpty:'Sin permisos registrados. Añada usuarios.',
auditLogBtn:'📋 Historial',auditLogTitle:'📋 Historial de movimientos (Auditoría)',auditLogDesc:'Registro inmutable de todos los cambios de stock. Máx. 500 registros.',auditLogEmpty:'Sin historial de movimientos.',auditLogClearBtn:'🗑 Borrar historial',auditLogClearConfirm:'¿Borrar todo el historial? No se puede deshacer.',
exportCsvBtn:'📥 Exportar CSV',exportExcelBtn:'📋 Exportar Excel',
csvImportBtn:'📥 Importación CSV masiva',csvImportTitle:'Importación CSV masiva',csvImportDesc:'Registre SKU/inventario masivamente por archivo CSV. Columnas requeridas:',csvRowsDetected:'registros detectados',csvMoreRows:'Más filas',csvExecuteBtn:'Ejecutar registro masivo',csvImportDone:'registros importados',
scanBtn:'📷 Escanear código',scanTitle:'Escáner de códigos',scanScanning:'Alinee el código de barras en el área de escaneo...',scanDetected:'¡Código detectado!',scanApply:'Aplicar este SKU',scanCamError:'Acceso a cámara denegado. Verifique los permisos del navegador.',
whTitle:'📦 Lista de almacenes',whEmpty:'Sin almacenes registrados. Use el botón [+ Añadir almacén].',whAddBtn:'+ Añadir almacén',whFormTitle:'Información del almacén',whNameLabel:'Nombre',whCodeLabel:'Código',whAddrLabel:'Dirección',whTypeLabel:'Tipo',whAreaLabel:'Área(㎡)',whManagerLabel:'Responsable',whTypeNormal:'Ambiente',whTypeCold:'Refrigerado',whTypeFrozen:'Congelado',whSaveBtn:'Guardar',whCancelBtn:'Cancelar',whDeleteConfirm:'¿Eliminar este almacén?',
invTableTitle:'📦 Inventario por SKU y almacén',invColSku:'SKU',invColProduct:'Producto',invColTotal:'Total',invColSafe:'Stock seguridad',invColStatus:'Estado',invColCost:'Precio unit.',invColValue:'Valor',invColAdj:'Ajustar',invSearchPh:'Buscar por SKU o nombre',invLowOnly:'⚠️ Solo stock bajo',invTotalStock:'Stock total',invNoResult:'🔍 Sin resultados.',invOutOfStock:'Agotado',invLow:'Bajo',invNormal:'Normal',invAdjTitle:'Ajuste de inventario',invAdjQty:'Cantidad ajuste',invAdjApply:'Aplicar ajuste',invAdjBtn:'Ajustar',invDemoAdj:'Modo demo: ajuste no disponible.',
ioSearchPh:'Buscar por SKU·nombre·referencia',ioItems:'items',ioRegTitle:'📝 Registro entrada/salida',ioTypeLabel:'Tipo',ioWhLabel:'Almacén',ioTransferDest:'Almacén destino',ioSkuLabel:'SKU',ioProductLabel:'Producto',ioQtyLabel:'Cantidad',ioUnitLabel:'Precio unit.',ioRefLabel:'Referencia',ioRefPh:'PO-2024-001',ioMemoLabel:'Nota',ioReturnReason:'Motivo devolución',ioReturnReasonPh:'Ingrese motivo',ioSaveBtn:'✅ Registrar',ioColType:'Tipo',ioColWh:'Almacén',ioColSku:'SKU',ioColProduct:'Producto',ioColQty:'Cant.',ioColUnit:'P.Unit.',ioColRef:'Ref.',ioColBy:'Por',ioColDate:'Fecha',ioRegBtn:'+ Registrar',ioExportBtn:'📥 Descargar CSV',ioTypeInbound:'Entrada',ioTypeOutbound:'Salida',ioTypeReturnsIn:'Dev. entrada',ioTypeReturnsOut:'Dev. salida',ioTypeTransfer:'Transferencia',ioTypeAdjust:'Ajuste',ioTypeDisposal:'Descarte',ioEmpty:'Sin registros.',
recvTitle:'📋 Recepción',recvSearchPh:'Buscar por PO o SKU',recvPoNumber:'Nº PO',recvSku:'SKU',recvProduct:'Producto',recvExpected:'Esperado',recvActual:'Recibido',recvStatus:'Estado',recvAction:'Acción',recvBtnAccept:'Aceptar',recvBtnPartial:'Parcial',recvBtnReject:'Rechazar',recvStatusPending:'Pendiente',recvStatusAccepted:'Aceptado',recvStatusPartial:'Parcial',recvStatusRejected:'Rechazado',recvEmpty:'Sin recepciones pendientes.',
pickTitle:'📋 Picking/Packing',pickSearchPh:'Buscar por pedido o SKU',pickOrderNo:'Nº Pedido',pickSku:'SKU',pickProduct:'Producto',pickQty:'Cant.',pickStatus:'Estado',pickAction:'Acción',pickBtnPick:'Picking',pickBtnPack:'Packing',pickBtnShip:'Enviar',pickStatusReady:'Listo',pickStatusPicking:'En picking',pickStatusPacked:'Empacado',pickStatusShipped:'Enviado',pickEmpty:'Sin pedidos.',
lotTitle:'📋 Gestión de lotes/caducidad',lotSearchPh:'Buscar por lote o SKU',lotColLot:'Nº Lote',lotColSku:'SKU',lotColProduct:'Producto',lotColExpiry:'Caducidad',lotColQty:'Cant.',lotColStatus:'Estado',lotExpired:'Caducado',lotExpiringSoon:'Por caducar',lotActive:'Activo',lotEmpty:'Sin información de lotes.',
replTitle:'📋 Reposición automática',replSearchPh:'Buscar por SKU o nombre',replColSku:'SKU',replColProduct:'Producto',replColCurrent:'Stock actual',replColSafe:'Stock seg.',replColReorder:'Punto pedido',replColStatus:'Estado',replColAction:'Acción',replBtnOrder:'Pedir',replStatusAuto:'Auto',replStatusManual:'Manual',replEmpty:'Sin productos para reponer.',
combTitle:'📋 Gestión de empaques combinados',combSearchPh:'Buscar por pedido',combColOrder:'Pedido',combColItems:'Artículos',combColWeight:'Peso total',combColStatus:'Estado',combColAction:'Acción',combBtnCombine:'Combinar',combStatusReady:'Listo',combStatusCombined:'Combinado',combEmpty:'Sin empaques combinados.',combTracking:'📦 Seguimiento',
carrTitle:'📋 Gestión de transportistas',carrSearchPh:'Buscar por nombre',carrColName:'Transportista',carrColCode:'Código',carrColType:'Tipo',carrColApi:'API',carrColStatus:'Estado',carrBtnAdd:'+ Añadir',carrTypeDomestic:'Nacional',carrTypeInternational:'Internacional',carrApiConnected:'Conectado',carrApiDisconnected:'Desconectado',carrEmpty:'Sin transportistas.',
trackTitle:'📋 Seguimiento de envíos',trackSearchTitle:'🔍 Rastrear por nº envío',trackSearchPh:'Ingrese nº envío',trackSearchBtn:'Rastrear',trackSearching:'Buscando...',trackNumPh:'Nº de envío',trackNoResult:'Sin resultados.',trackCJ:'CJ Logistics',trackHJ:'Hanjin Express',trackLT:'Lotte Express',trackEMS:'Correo Postal',trackCPR:'Coupang Rocket',trackLZ:'Logen Express',trackStatusInTransit:'En tránsito',trackEtaToday:'Llegada: esta tarde',trackLoc1:'Centro Seúl Gangnam',trackDesc1:'Enviado',trackLoc2:'Hub Metropolitano',trackDesc2:'Clasificado',trackLoc3:'Centro Incheon',trackDesc3:'Llegada troncal',trackLoc4:'Centro Busan',trackDesc4:'Enviado',
invcTitle:'📋 Facturas comerciales',invcSearchPh:'Buscar por nº factura',invcColNo:'Nº',invcColDate:'Fecha',invcColBuyer:'Comprador',invcColTotal:'Total',invcColCurrency:'Moneda',invcColStatus:'Estado',invcBtnCreate:'+ Crear factura',invcStatusDraft:'Borrador',invcStatusIssued:'Emitida',invcStatusPaid:'Pagada',invcEmpty:'Sin facturas.',
bdlTitle:'📋 Gestión de bundles/BOM',bdlSearchPh:'Buscar por nombre',bdlColName:'Nombre',bdlColSku:'SKU',bdlColComponents:'Componentes',bdlColStock:'Stock',bdlColStatus:'Estado',bdlBtnAdd:'+ Añadir bundle',bdlEmpty:'Sin bundles.',bdlShipAlert:'Envío bundle:',bdlRegAlert:'Bundle registrado:',bdlNamePh:'Nombre del bundle',bdlQtyLabel:'Cantidad',
supTitle:'📋 Gestión de proveedores',supSearchPh:'Buscar por nombre',supColName:'Proveedor',supColContact:'Contacto',supColLeadTime:'Plazo',supColRating:'Calificación',supColAction:'Acción',supBtnAdd:'+ Añadir proveedor',supEmpty:'Sin proveedores.',
auditTitle:'📋 Auditoría de inventario',auditSearchPh:'Buscar por SKU o almacén',auditColSku:'SKU',auditColProduct:'Producto',auditColSystem:'Stock sistema',auditColPhysical:'Stock físico',auditColDiff:'Diferencia',auditColAction:'Acción',auditBtnCount:'Contar',auditBtnAdjust:'Ajustar',auditEmpty:'Sin auditorías.',auditAdjAlert:'Ajuste completado',auditAllSku:'Todos los SKU',
pageSub:'Gestión integrada de entradas, envíos, inventario, picking y devoluciones',totalStock:'Stock total',returnRate:'Tasa devolución',pendingReceive:'Recepción pendiente',pendingShip:'Envío pendiente',registerReceipt:'Registrar recepción',processShipment:'Procesar envío',adjustInventory:'Ajustar inventario',sku:'SKU',quantity:'Cantidad',location:'Ubicación',warehouse:'Almacén',status:'Estado',actions:'Acciones',bulkXlsxError:'Error al analizar el archivo Excel. Verifique el formato.'
};
apply('es',ES);

// French
const FR={
securityBtn:'🛡️ Moniteur sécurité',securityTitle:'Moniteur de détection des menaces',securityDesc:"Détection et blocage des menaces en temps réel",securitySafe:'État : Sécurisé',securitySafeDesc:'Aucune menace de sécurité détectée.',
permBtn:'🔑 Gestion des permissions',permTitle:'Permissions par entrepôt',permDesc:"Gérez les permissions d'accès par utilisateur. Les permissions varient selon le rôle.",permUserLabel:'Email',permRoleLabel:'Rôle',permAddBtn:'Ajouter permission',permColUser:'Utilisateur',permColRole:'Rôle',permColAction:'Gestion',permRoleAdmin:'Administrateur',permRoleManager:'Gestionnaire',permRoleOperator:'Opérateur',permRoleViewer:'Lecteur',permEmpty:"Aucune permission enregistrée. Ajoutez des utilisateurs.",
auditLogBtn:'📋 Historique',auditLogTitle:'📋 Historique des mouvements (Audit)',auditLogDesc:'Journal immuable de tous les changements de stock. Max 500 entrées.',auditLogEmpty:'Aucun historique.',auditLogClearBtn:'🗑 Supprimer',auditLogClearConfirm:'Supprimer tout ? Cette action est irréversible.',
exportCsvBtn:'📥 Exporter CSV',exportExcelBtn:'📋 Exporter Excel',
csvImportBtn:'📥 Import CSV en masse',csvImportTitle:'Import CSV en masse',csvImportDesc:'Enregistrez SKU/stock en masse via fichier CSV. Colonnes requises :',csvRowsDetected:'enregistrements détectés',csvMoreRows:'Plus de lignes',csvExecuteBtn:"Exécuter l'import",csvImportDone:'enregistrements importés !',
scanBtn:'📷 Scanner code-barres',scanTitle:'Scanner de codes-barres',scanScanning:'Alignez le code-barres dans la zone de scan...',scanDetected:'Code-barres détecté !',scanApply:'Appliquer ce SKU',scanCamError:"Accès caméra refusé. Vérifiez les permissions du navigateur.",
whTitle:'📦 Liste des entrepôts',whEmpty:"Aucun entrepôt enregistré. Utilisez le bouton [+ Ajouter].",whAddBtn:'+ Ajouter entrepôt',whFormTitle:"Informations de l'entrepôt",whNameLabel:'Nom',whCodeLabel:'Code',whAddrLabel:'Adresse',whTypeLabel:'Type',whAreaLabel:'Surface(㎡)',whManagerLabel:'Responsable',whTypeNormal:'Ambiant',whTypeCold:'Réfrigéré',whTypeFrozen:'Congelé',whSaveBtn:'Enregistrer',whCancelBtn:'Annuler',whDeleteConfirm:'Supprimer cet entrepôt ?',
invTableTitle:'📦 Inventaire par SKU et entrepôt',invColSku:'SKU',invColProduct:'Produit',invColTotal:'Total',invColSafe:'Stock sécurité',invColStatus:'Statut',invColCost:'Prix unit.',invColValue:'Valeur',invColAdj:'Ajuster',invSearchPh:'Rechercher par SKU ou nom',invLowOnly:'⚠️ Stock bas uniquement',invTotalStock:'Stock total',invNoResult:'🔍 Aucun résultat.',invOutOfStock:'Rupture',invLow:'Bas',invNormal:'Normal',invAdjTitle:'Ajustement stock',invAdjQty:'Quantité',invAdjApply:'Appliquer',invAdjBtn:'Ajuster',invDemoAdj:'Mode démo : ajustement non disponible.',
ioSearchPh:'Rechercher par SKU·nom·référence',ioItems:'articles',ioRegTitle:'📝 Enregistrement entrée/sortie',ioTypeLabel:'Type',ioWhLabel:'Entrepôt',ioTransferDest:'Entrepôt destination',ioSkuLabel:'SKU',ioProductLabel:'Produit',ioQtyLabel:'Quantité',ioUnitLabel:'Prix unit.',ioRefLabel:'Référence',ioRefPh:'PO-2024-001',ioMemoLabel:'Note',ioReturnReason:'Motif retour',ioReturnReasonPh:'Saisissez le motif',ioSaveBtn:'✅ Enregistrer',ioColType:'Type',ioColWh:'Entrepôt',ioColSku:'SKU',ioColProduct:'Produit',ioColQty:'Qté',ioColUnit:'P.U.',ioColRef:'Réf.',ioColBy:'Par',ioColDate:'Date',ioRegBtn:'+ Enregistrer',ioExportBtn:'📥 Télécharger CSV',ioTypeInbound:'Entrée',ioTypeOutbound:'Sortie',ioTypeReturnsIn:'Retour entrée',ioTypeReturnsOut:'Retour sortie',ioTypeTransfer:'Transfert',ioTypeAdjust:'Ajustement',ioTypeDisposal:'Mise au rebut',ioEmpty:'Aucun enregistrement.',
recvTitle:'📋 Réception',recvSearchPh:'Rechercher par PO ou SKU',recvPoNumber:'N° PO',recvSku:'SKU',recvProduct:'Produit',recvExpected:'Attendu',recvActual:'Reçu',recvStatus:'Statut',recvAction:'Action',recvBtnAccept:'Accepter',recvBtnPartial:'Partiel',recvBtnReject:'Rejeter',recvStatusPending:'En attente',recvStatusAccepted:'Accepté',recvStatusPartial:'Partiel',recvStatusRejected:'Rejeté',recvEmpty:'Aucune réception en attente.',
pickTitle:'📋 Picking/Packing',pickSearchPh:'Rechercher par commande ou SKU',pickOrderNo:'N° Commande',pickSku:'SKU',pickProduct:'Produit',pickQty:'Qté',pickStatus:'Statut',pickAction:'Action',pickBtnPick:'Picking',pickBtnPack:'Packing',pickBtnShip:'Expédier',pickStatusReady:'Prêt',pickStatusPicking:'En picking',pickStatusPacked:'Emballé',pickStatusShipped:'Expédié',pickEmpty:'Aucune commande.',
lotTitle:'📋 Gestion lots/péremption',lotSearchPh:'Rechercher par lot ou SKU',lotColLot:'N° Lot',lotColSku:'SKU',lotColProduct:'Produit',lotColExpiry:'Péremption',lotColQty:'Qté',lotColStatus:'Statut',lotExpired:'Périmé',lotExpiringSoon:'Bientôt périmé',lotActive:'Actif',lotEmpty:'Aucune information lot.',
replTitle:'📋 Réapprovisionnement auto',replSearchPh:'Rechercher par SKU ou nom',replColSku:'SKU',replColProduct:'Produit',replColCurrent:'Stock actuel',replColSafe:'Stock sécurité',replColReorder:'Point commande',replColStatus:'Statut',replColAction:'Action',replBtnOrder:'Commander',replStatusAuto:'Auto',replStatusManual:'Manuel',replEmpty:'Aucun produit à réapprovisionner.',
combTitle:'📋 Emballages combinés',combSearchPh:'Rechercher par commande',combColOrder:'Commande',combColItems:'Articles',combColWeight:'Poids total',combColStatus:'Statut',combColAction:'Action',combBtnCombine:'Combiner',combStatusReady:'Prêt',combStatusCombined:'Combiné',combEmpty:'Aucun emballage combiné.',combTracking:'📦 Suivi',
carrTitle:'📋 Gestion des transporteurs',carrSearchPh:'Rechercher par nom',carrColName:'Transporteur',carrColCode:'Code',carrColType:'Type',carrColApi:'API',carrColStatus:'Statut',carrBtnAdd:'+ Ajouter',carrTypeDomestic:'National',carrTypeInternational:'International',carrApiConnected:'Connecté',carrApiDisconnected:'Déconnecté',carrEmpty:'Aucun transporteur.',
trackTitle:'📋 Suivi des livraisons',trackSearchTitle:'🔍 Suivre par n° envoi',trackSearchPh:'Saisissez le n° de suivi',trackSearchBtn:'Suivre',trackSearching:'Recherche...',trackNumPh:'N° de suivi',trackNoResult:'Aucun résultat.',trackCJ:'CJ Logistics',trackHJ:'Hanjin Express',trackLT:'Lotte Express',trackEMS:'Poste Coréenne',trackCPR:'Coupang Rocket',trackLZ:'Logen Express',trackStatusInTransit:'En transit',trackEtaToday:"Arrivée : cet après-midi",trackLoc1:'Centre Séoul Gangnam',trackDesc1:'Expédié',trackLoc2:'Hub Métropolitain',trackDesc2:'Trié',trackLoc3:'Centre Incheon',trackDesc3:'Arrivée tronc',trackLoc4:'Centre Busan',trackDesc4:'Envoyé',
invcTitle:'📋 Factures commerciales',invcSearchPh:'Rechercher par n° facture',invcColNo:'N°',invcColDate:'Date',invcColBuyer:'Acheteur',invcColTotal:'Total',invcColCurrency:'Devise',invcColStatus:'Statut',invcBtnCreate:'+ Créer facture',invcStatusDraft:'Brouillon',invcStatusIssued:'Émise',invcStatusPaid:'Payée',invcEmpty:'Aucune facture.',
bdlTitle:'📋 Gestion bundles/BOM',bdlSearchPh:'Rechercher par nom',bdlColName:'Nom',bdlColSku:'SKU',bdlColComponents:'Composants',bdlColStock:'Stock',bdlColStatus:'Statut',bdlBtnAdd:'+ Ajouter bundle',bdlEmpty:'Aucun bundle.',bdlShipAlert:'Expédition bundle :',bdlRegAlert:'Bundle enregistré :',bdlNamePh:'Nom du bundle',bdlQtyLabel:'Quantité',
supTitle:'📋 Gestion des fournisseurs',supSearchPh:'Rechercher par nom',supColName:'Fournisseur',supColContact:'Contact',supColLeadTime:'Délai',supColRating:'Note',supColAction:'Action',supBtnAdd:'+ Ajouter fournisseur',supEmpty:'Aucun fournisseur.',
auditTitle:'📋 Inventaire physique',auditSearchPh:'Rechercher par SKU ou entrepôt',auditColSku:'SKU',auditColProduct:'Produit',auditColSystem:'Stock système',auditColPhysical:'Stock physique',auditColDiff:'Écart',auditColAction:'Action',auditBtnCount:'Compter',auditBtnAdjust:'Ajuster',auditEmpty:'Aucun inventaire.',auditAdjAlert:'Ajustement terminé',auditAllSku:'Tous les SKU',
pageSub:'Gestion intégrée des entrées, expéditions, stocks, picking et retours',totalStock:'Stock total',returnRate:'Taux retour',pendingReceive:'Réception en attente',pendingShip:'Expédition en attente',registerReceipt:'Enregistrer réception',processShipment:'Traiter expédition',adjustInventory:'Ajuster inventaire',sku:'SKU',quantity:'Quantité',location:'Emplacement',warehouse:'Entrepôt',status:'Statut',actions:'Actions',bulkXlsxError:"Échec de l'analyse du fichier Excel. Vérifiez le format."
};
apply('fr',FR);
console.log('Done ES+FR!');
