from __future__ import annotations
import os, time, json, pathlib
from typing import Dict, Any

BASE = pathlib.Path(__file__).resolve().parent / "reports_store"
BASE.mkdir(parents=True, exist_ok=True)

def _safe(s: str) -> str:
    return "".join([c for c in s if c.isalnum() or c in ("-","_")])[:64] or "demo"

def write_report(tenant_id: str, report_id: str, payload: Dict[str, Any]) -> str:
    t = _safe(tenant_id)
    d = BASE / t
    d.mkdir(parents=True, exist_ok=True)
    path = d / f"{report_id}.html"
    meta_path = d / "latest.json"
    html = _render_html(payload)
    path.write_text(html, encoding="utf-8")
    meta_path.write_text(json.dumps({"report_id": report_id, "path": str(path), "created_at": time.time()}, ensure_ascii=False, indent=2), encoding="utf-8")
    return str(path)

def read_latest(tenant_id: str) -> Dict[str, Any]:
    t = _safe(tenant_id)
    meta = BASE / t / "latest.json"
    if not meta.exists():
        return {"report_id": None}
    import json
    return json.loads(meta.read_text(encoding="utf-8"))

def read_report_html(tenant_id: str, report_id: str) -> str | None:
    t = _safe(tenant_id)
    p = BASE / t / f"{report_id}.html"
    if not p.exists():
        return None
    return p.read_text(encoding="utf-8")

def _render_html(payload: Dict[str, Any]) -> str:
    summary = payload.get("summary", {})
    artifacts = payload.get("artifacts", {})
    kpi = artifacts.get("kpi", {})
    forecast = artifacts.get("forecast", {})
    recs = artifacts.get("budget_recommendations", [])
    return f"""<!doctype html>
<html><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<script src="https://cdn.tailwindcss.com"></script>
<title>GENIE Report {summary.get('tenant_id','')}</title>
</head>
<body class="bg-slate-50">
<div class="max-w-5xl mx-auto p-6">
  <div class="flex items-start justify-between">
    <div>
      <div class="text-sm text-slate-500">GENIE Auto Report</div>
      <h1 class="text-2xl font-bold">Tenant: {summary.get('tenant_id','')}</h1>
      <div class="text-sm text-slate-600 mt-1">AUTO_EXECUTE={summary.get('runtime',{}).get('AUTO_EXECUTE')} • DRY_RUN={summary.get('runtime',{}).get('DRY_RUN')}</div>
    </div>
    <div class="text-xs font-mono bg-white border rounded-xl p-3">
      <div>report_id: {payload.get('report_id','')}</div>
      <div>created_at: {summary.get('timestamp','')}</div>
    </div>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6">
    <div class="bg-white rounded-2xl shadow p-4">
      <div class="text-xs text-slate-500">Spend</div>
      <div class="text-xl font-semibold">{(kpi.get('spend') or [0])[-1]}</div>
    </div>
    <div class="bg-white rounded-2xl shadow p-4">
      <div class="text-xs text-slate-500">Revenue</div>
      <div class="text-xl font-semibold">{(kpi.get('revenue') or [0])[-1]}</div>
    </div>
    <div class="bg-white rounded-2xl shadow p-4">
      <div class="text-xs text-slate-500">ROAS</div>
      <div class="text-xl font-semibold">{(kpi.get('roas') or [0])[-1]}</div>
    </div>
  </div>

  <div class="bg-white rounded-2xl shadow p-4 mt-4">
    <div class="font-semibold">Anomaly</div>
    <pre class="text-xs bg-slate-50 border rounded-xl p-3 mt-2 overflow-auto">{json.dumps(summary.get('anomaly',{}), ensure_ascii=False, indent=2)}</pre>
  </div>

  <div class="bg-white rounded-2xl shadow p-4 mt-4">
    <div class="font-semibold">KPI Forecast (7 days)</div>
    <pre class="text-xs bg-slate-50 border rounded-xl p-3 mt-2 overflow-auto">{json.dumps(forecast, ensure_ascii=False, indent=2)[:4000]}</pre>
  </div>

  <div class="bg-white rounded-2xl shadow p-4 mt-4">
    <div class="font-semibold">Budget Recommendations</div>
    <pre class="text-xs bg-slate-50 border rounded-xl p-3 mt-2 overflow-auto">{json.dumps(recs, ensure_ascii=False, indent=2)}</pre>
  </div>

  <div class="text-xs text-slate-500 mt-6">Generated by GENIE V253 pipeline.</div>
</div>
</body></html>"""
