// session148_c4_split_unmapped.mjs
// Top 500 제외한 잔여 unique unmapped를 10 batch로 분할
// 입력: ./latin_long_unique_unmapped.csv (1,876 unique, c2 산출)
// 출력:
//   ./latin_long_unmapped_batch_01.csv ~ batch_10.csv (잔여 1,376 unique 분배)
//   ./latin_long_unmapped_batch_01_raw.txt ~ batch_10_raw.txt (사용자 번역 양식)
//   ./latin_long_c4_log.txt
//
// 147차 B8a 패턴: 균등 분할, raw txt에 PATH/JA/EN/SUGGESTED_KO 양식

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const INPUT = resolve('./latin_long_unique_unmapped.csv');
const OUT_LOG = resolve('./latin_long_c4_log.txt');

const SKIP_TOP = 500;
const NUM_BATCHES = 10;

// ---------- CSV parser ----------
function parseCSV(text) {
  if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);
  const rows = [];
  let row = [], field = '', inQ = false, i = 0;
  const n = text.length;
  while (i < n) {
    const c = text[i];
    if (inQ) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; }
        else { inQ = false; i++; }
      } else { field += c; i++; }
    } else {
      if (c === '"') { inQ = true; i++; }
      else if (c === ',') { row.push(field); field = ''; i++; }
      else if (c === '\r') {
        row.push(field); rows.push(row); row = []; field = ''; i++;
        if (text[i] === '\n') i++;
      } else if (c === '\n') {
        row.push(field); rows.push(row); row = []; field = ''; i++;
      } else { field += c; i++; }
    }
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows;
}

function csvEscape(s) {
  if (s == null) return '';
  s = String(s);
  if (s.includes('"') || s.includes(',') || s.includes('\n') || s.includes('\r')) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}
function toCSV(rows) {
  return rows.map(r => r.map(csvEscape).join(',')).join('\n');
}

// ---------- 메인 ----------
console.log('[c4] Reading:', INPUT);
const text = readFileSync(INPUT, 'utf8');
const rows = parseCSV(text);
const header = rows[0];
const data = rows.slice(1).filter(r => r.length === header.length);
console.log(`[c4] Unique unmapped rows: ${data.length}`);

const idx = {
  ko_value: header.indexOf('ko_value'),
  count: header.indexOf('count'),
  sample_path: header.indexOf('sample_path'),
  sample_ja_value: header.indexOf('sample_ja_value'),
  sample_en_value: header.indexOf('sample_en_value'),
  suggested_ko: header.indexOf('suggested_ko'),
};

// Top 500 skip
const tail = data.slice(SKIP_TOP);
console.log(`[c4] Tail (after top ${SKIP_TOP}): ${tail.length}`);

// 균등 분할 (10 batches)
const batchSize = Math.ceil(tail.length / NUM_BATCHES);
console.log(`[c4] Batch size: ${batchSize} entries each`);

const batchSummary = [];

for (let b = 0; b < NUM_BATCHES; b++) {
  const start = b * batchSize;
  const end = Math.min(start + batchSize, tail.length);
  const batch = tail.slice(start, end);
  if (batch.length === 0) {
    console.log(`[c4] Batch ${String(b + 1).padStart(2, '0')}: empty, skipping`);
    continue;
  }

  const batchNum = String(b + 1).padStart(2, '0');
  const outCsv = resolve(`./latin_long_unmapped_batch_${batchNum}.csv`);
  const outRaw = resolve(`./latin_long_unmapped_batch_${batchNum}_raw.txt`);

  // CSV
  writeFileSync(outCsv, toCSV([header, ...batch]), 'utf8');

  // raw txt
  const totalOcc = batch.reduce((s, r) => s + parseInt(r[idx.count], 10), 0);
  let raw = `# LATIN_LONG Unmapped Batch ${batchNum} / ${NUM_BATCHES}
# Generated by session148_c4
# Entries: ${batch.length} (rank ${SKIP_TOP + start + 1} ~ ${SKIP_TOP + end} of unique unmapped)
# Total occurrences in ko.js: ${totalOcc}
#
# FORMAT (each block):
#   --- [INDEX] ko_value (count=N) ---
#   PATH: <sample path in ko.js>
#   JA: <Japanese reference>
#   EN: <English reference>
#   SUGGESTED_KO: <YOUR TRANSLATION HERE>
#
# RULES:
# - 외래어 영문 유지: CSV, API, ROAS, ROI, KPI 등
# - 마침표 보존 (원문 충실)
# - {{변수}} 보존
# - 이모지 보존
# - 빈 SUGGESTED_KO는 skip

`;

  batch.forEach((r, i) => {
    const ko = r[idx.ko_value];
    const cnt = r[idx.count];
    const path = r[idx.sample_path];
    const ja = r[idx.sample_ja_value];
    const en = r[idx.sample_en_value];
    raw += `--- [${String(i + 1).padStart(3, '0')}] ${ko} (count=${cnt}) ---\n`;
    raw += `PATH: ${path}\n`;
    raw += `JA: ${ja}\n`;
    raw += `EN: ${en}\n`;
    raw += `SUGGESTED_KO: \n`;
    raw += `\n`;
  });

  writeFileSync(outRaw, raw, 'utf8');

  batchSummary.push({
    batch: batchNum,
    entries: batch.length,
    occurrences: totalOcc,
    csv: outCsv,
    raw: outRaw,
  });

  console.log(`[c4] Batch ${batchNum}: ${batch.length} entries, ${totalOcc} occurrences`);
}

// 로그
const log = `# session148 c4 Batch Split Log

## Input
- File: ${INPUT}
- Unique unmapped total: ${data.length}
- Skipped (top ${SKIP_TOP}): ${SKIP_TOP}
- Tail to batch: ${tail.length}

## Batches (${NUM_BATCHES} files)
${batchSummary.map(b =>
  `- Batch ${b.batch}: ${b.entries} entries, ${b.occurrences} occurrences`
).join('\n')}

## Total tail occurrences
- ${batchSummary.reduce((s, b) => s + b.occurrences, 0)}

## Files
- CSV: latin_long_unmapped_batch_01.csv ~ batch_${NUM_BATCHES.toString().padStart(2, '0')}.csv
- RAW: latin_long_unmapped_batch_01_raw.txt ~ batch_${NUM_BATCHES.toString().padStart(2, '0')}_raw.txt

## Workflow
1. User translates SUGGESTED_KO in each raw.txt file
2. c5 parser converts raw.txt → mapped CSV
3. c6 merge + c7 apply patch to ko.js
`;
writeFileSync(OUT_LOG, log, 'utf8');

console.log('[c4] DONE');
