// session148_c3_top500_freq.mjs
// Top 500 빈도 unique unmapped 추출 (사용자 수동 번역 워크북)
// 입력: ./latin_long_unique_unmapped.csv (1,876 unique, c2 산출)
// 출력:
//   ./latin_long_top500_freq.csv (500 entries, 빈도 정렬)
//   ./latin_long_top500_raw.txt (사용자 번역 입력 양식, 147차 top500_raw.txt 패턴)
//   ./latin_long_c3_log.txt
//
// 사용 흐름:
//   1. 사용자가 latin_long_top500_raw.txt 열어 SUGGESTED_KO 컬럼에 번역 입력
//   2. c5 (parse_top500)이 raw txt → CSV 변환
//   3. ko.js 패치 적용

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const INPUT = resolve('./latin_long_unique_unmapped.csv');
const OUT_TOP500 = resolve('./latin_long_top500_freq.csv');
const OUT_RAW = resolve('./latin_long_top500_raw.txt');
const OUT_LOG = resolve('./latin_long_c3_log.txt');

const TOP_N = 500;

// ---------- CSV parser ----------
function parseCSV(text) {
  if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);
  const rows = [];
  let row = [], field = '', inQ = false, i = 0;
  const n = text.length;
  while (i < n) {
    const c = text[i];
    if (inQ) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; }
        else { inQ = false; i++; }
      } else { field += c; i++; }
    } else {
      if (c === '"') { inQ = true; i++; }
      else if (c === ',') { row.push(field); field = ''; i++; }
      else if (c === '\r') {
        row.push(field); rows.push(row); row = []; field = ''; i++;
        if (text[i] === '\n') i++;
      } else if (c === '\n') {
        row.push(field); rows.push(row); row = []; field = ''; i++;
      } else { field += c; i++; }
    }
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows;
}

function csvEscape(s) {
  if (s == null) return '';
  s = String(s);
  if (s.includes('"') || s.includes(',') || s.includes('\n') || s.includes('\r')) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}
function toCSV(rows) {
  return rows.map(r => r.map(csvEscape).join(',')).join('\n');
}

// ---------- 메인 ----------
console.log('[c3] Reading:', INPUT);
const text = readFileSync(INPUT, 'utf8');
const rows = parseCSV(text);
const header = rows[0];
const data = rows.slice(1).filter(r => r.length === header.length);
console.log(`[c3] Header: ${header.join(', ')}`);
console.log(`[c3] Unique unmapped rows: ${data.length}`);

const idx = {
  ko_value: header.indexOf('ko_value'),
  count: header.indexOf('count'),
  sample_path: header.indexOf('sample_path'),
  sample_ja_value: header.indexOf('sample_ja_value'),
  sample_en_value: header.indexOf('sample_en_value'),
  suggested_ko: header.indexOf('suggested_ko'),
};

// 이미 count 정렬됨 (c2 출력) — 상위 500 추출
const top500 = data.slice(0, TOP_N);
console.log(`[c3] Selected top ${top500.length} entries`);

// CSV 출력 (빈도 정렬 유지)
writeFileSync(OUT_TOP500, toCSV([header, ...top500]), 'utf8');

// ---------- raw txt 양식 (147차 top500_raw.txt 패턴) ----------
// 사용자가 SUGGESTED_KO 부분만 채우면 됨
let raw = `# LATIN_LONG Top 500 Translation Workbook
# Generated by session148_c3
# Total: ${top500.length} unique English values (covers ~${
  top500.reduce((s, r) => s + parseInt(r[idx.count], 10), 0)
} occurrences in ko.js)
#
# FORMAT (each block):
#   --- [INDEX] ko_value (count=N) ---
#   PATH: <sample path in ko.js>
#   JA: <Japanese reference>
#   EN: <English reference>
#   SUGGESTED_KO: <YOUR TRANSLATION HERE>
#
# RULES:
# - 외래어 영문 유지: CSV, API, ROAS, ROI, KPI, CPA, CPC, CPM, CTR, CVR, LTV, ACOS, SKU, CRM, P&L, BOM, SLA 등
# - 마침표 보존 (원문에 있으면 한국어에도)
# - {{변수}} 그대로 유지 (한국어 변수명도 가능: {{name}}→{{이름}})
# - 이모지/특수기호 보존
# - UI 라벨 마침표 제거 허용 (147차 batch_08 N-원칙)
# - 빈 SUGGESTED_KO는 c5에서 skip (다음 batch로 이월)

`;

top500.forEach((r, i) => {
  const ko = r[idx.ko_value];
  const cnt = r[idx.count];
  const path = r[idx.sample_path];
  const ja = r[idx.sample_ja_value];
  const en = r[idx.sample_en_value];
  raw += `--- [${String(i + 1).padStart(3, '0')}] ${ko} (count=${cnt}) ---\n`;
  raw += `PATH: ${path}\n`;
  raw += `JA: ${ja}\n`;
  raw += `EN: ${en}\n`;
  raw += `SUGGESTED_KO: \n`;
  raw += `\n`;
});

writeFileSync(OUT_RAW, raw, 'utf8');

// 로그
const totalOccurrences = top500.reduce((s, r) => s + parseInt(r[idx.count], 10), 0);
const allUnmappedOccurrences = data.reduce((s, r) => s + parseInt(r[idx.count], 10), 0);
const coverage = ((totalOccurrences / allUnmappedOccurrences) * 100).toFixed(1);

const log = `# session148 c3 Top 500 Frequency Extraction

## Input
- File: ${INPUT}
- Unique unmapped values: ${data.length}

## Output
- Top ${TOP_N} entries → ${OUT_TOP500}
- Raw workbook → ${OUT_RAW}

## Coverage
- Top ${TOP_N} entries cover ${totalOccurrences} occurrences
- Total unmapped occurrences: ${allUnmappedOccurrences}
- Coverage: ${coverage}%

## Frequency tiers (top 500)
- Position 1-50: ${top500.slice(0, 50).reduce((s, r) => s + parseInt(r[idx.count], 10), 0)} occurrences
- Position 51-200: ${top500.slice(50, 200).reduce((s, r) => s + parseInt(r[idx.count], 10), 0)} occurrences
- Position 201-500: ${top500.slice(200, 500).reduce((s, r) => s + parseInt(r[idx.count], 10), 0)} occurrences

## Remaining unmapped (NOT in Top 500)
- ${data.length - TOP_N} unique values (handled by c4 batch split)
`;
writeFileSync(OUT_LOG, log, 'utf8');

console.log('[c3] Top 500 occurrences:', totalOccurrences);
console.log('[c3] Coverage:', coverage + '%');
console.log('[c3] DONE');
