/* 197차 — 채널 KPI 이용가이드 15개국 현지 자연어 사전(자립형).
 * 키: tabGuide/guideTitle/guideSub/guideStepsTitle/guideStep1..6{Title,Desc}/guideTabsTitle/
 *     guide{Goal,Role,Setup,Sns,Content,Community,Target,Monitor}{Name,Desc}/guideTipsTitle/guideTip1..5  (CC 초안) */
const B = (tg, ti, su, st, S, tt, T, pt, P) => ({
  tabGuide: tg, guideTitle: ti, guideSub: su, guideStepsTitle: st,
  guideStep1Title: S[0][0], guideStep1Desc: S[0][1], guideStep2Title: S[1][0], guideStep2Desc: S[1][1],
  guideStep3Title: S[2][0], guideStep3Desc: S[2][1], guideStep4Title: S[3][0], guideStep4Desc: S[3][1],
  guideStep5Title: S[4][0], guideStep5Desc: S[4][1], guideStep6Title: S[5][0], guideStep6Desc: S[5][1],
  guideTabsTitle: tt,
  guideGoalName: T[0][0], guideGoalDesc: T[0][1], guideRoleName: T[1][0], guideRoleDesc: T[1][1],
  guideSetupName: T[2][0], guideSetupDesc: T[2][1], guideSnsName: T[3][0], guideSnsDesc: T[3][1],
  guideContentName: T[4][0], guideContentDesc: T[4][1], guideCommunityName: T[5][0], guideCommunityDesc: T[5][1],
  guideTargetName: T[6][0], guideTargetDesc: T[6][1], guideMonitorName: T[7][0], guideMonitorDesc: T[7][1],
  guideTipsTitle: pt, guideTip1: P[0], guideTip2: P[1], guideTip3: P[2], guideTip4: P[3], guideTip5: P[4],
});
const TB = {
  ko: [['목표','채널별 KPI 목표 설정'],['역할','채널 역할(인지·전환·리텐션)'],['설정','추적 지표·기간·세그먼트'],['SNS','소셜 채널 KPI'],['콘텐츠','콘텐츠 성과 지표'],['커뮤니티','커뮤니티 참여·반응'],['타겟','목표 대비 달성률'],['모니터링','실시간 KPI 추적']],
  en: [['Goals','Set per-channel KPI goals'],['Roles','Channel roles (awareness, conversion, retention)'],['Setup','Tracking metrics, period, segment'],['SNS','Social channel KPIs'],['Content','Content performance metrics'],['Community','Community engagement'],['Target','Achievement vs goal'],['Monitoring','Real-time KPI tracking']],
  ja: [['目標','チャネル別KPI目標設定'],['役割','チャネル役割(認知・転換・継続)'],['設定','追跡指標・期間・セグメント'],['SNS','ソーシャルチャネルKPI'],['コンテンツ','コンテンツ成果指標'],['コミュニティ','コミュニティ参加・反応'],['ターゲット','目標対比達成率'],['モニタリング','リアルタイムKPI追跡']],
  zh: [['目标','设定各渠道KPI目标'],['角色','渠道角色(认知·转化·留存)'],['设置','跟踪指标·周期·分群'],['社交','社交渠道KPI'],['内容','内容成效指标'],['社区','社区参与·反响'],['目标达成','目标对比达成率'],['监控','实时KPI追踪']],
  'zh-TW': [['目標','設定各通路KPI目標'],['角色','通路角色(認知·轉換·留存)'],['設定','追蹤指標·週期·分眾'],['社群','社群通路KPI'],['內容','內容成效指標'],['社區','社群參與·反響'],['目標達成','目標對比達成率'],['監控','即時KPI追蹤']],
  de: [['Ziele','KPI-Ziele je Kanal setzen'],['Rollen','Kanalrollen (Awareness, Conversion, Retention)'],['Setup','Tracking-Metriken, Zeitraum, Segment'],['SNS','Social-Kanal-KPIs'],['Content','Content-Performance-Metriken'],['Community','Community-Engagement'],['Ziel','Erreichung vs. Ziel'],['Monitoring','Echtzeit-KPI-Tracking']],
  th: [['เป้าหมาย','ตั้งเป้า KPI ต่อช่องทาง'],['บทบาท','บทบาทช่องทาง (รับรู้·แปลง·คงอยู่)'],['ตั้งค่า','ตัวชี้วัด ช่วงเวลา เซกเมนต์'],['โซเชียล','KPI ช่องทางโซเชียล'],['คอนเทนต์','ตัวชี้วัดผลคอนเทนต์'],['คอมมูนิตี้','การมีส่วนร่วมคอมมูนิตี้'],['เป้า','อัตราบรรลุเทียบเป้า'],['มอนิเตอร์','ติดตาม KPI เรียลไทม์']],
  vi: [['Mục tiêu','Đặt mục tiêu KPI theo kênh'],['Vai trò','Vai trò kênh (nhận biết·chuyển đổi·giữ chân)'],['Thiết lập','Chỉ số theo dõi, kỳ, phân khúc'],['SNS','KPI kênh mạng xã hội'],['Nội dung','Chỉ số hiệu suất nội dung'],['Cộng đồng','Tương tác cộng đồng'],['Mục tiêu','Tỉ lệ đạt vs mục tiêu'],['Giám sát','Theo dõi KPI thời gian thực']],
  id: [['Tujuan','Tetapkan target KPI per kanal'],['Peran','Peran kanal (awareness·konversi·retensi)'],['Pengaturan','Metrik pelacakan, periode, segmen'],['SNS','KPI kanal sosial'],['Konten','Metrik performa konten'],['Komunitas','Keterlibatan komunitas'],['Target','Pencapaian vs target'],['Pemantauan','Pelacakan KPI real-time']],
  es: [['Objetivos','Fija objetivos KPI por canal'],['Roles','Roles de canal (notoriedad·conversión·retención)'],['Configuración','Métricas, periodo, segmento'],['Redes','KPIs de canales sociales'],['Contenido','Métricas de rendimiento de contenido'],['Comunidad','Interacción de comunidad'],['Meta','Cumplimiento vs objetivo'],['Monitoreo','Seguimiento de KPI en tiempo real']],
  fr: [['Objectifs','Fixer des objectifs KPI par canal'],['Rôles','Rôles de canal (notoriété·conversion·rétention)'],['Réglages','Métriques, période, segment'],['Réseaux','KPI des canaux sociaux'],['Contenu','Métriques de performance contenu'],['Communauté','Engagement communautaire'],['Cible','Atteinte vs objectif'],['Suivi','Suivi KPI en temps réel']],
  pt: [['Metas','Defina metas de KPI por canal'],['Papéis','Papéis de canal (reconhecimento·conversão·retenção)'],['Configuração','Métricas, período, segmento'],['Redes','KPIs de canais sociais'],['Conteúdo','Métricas de desempenho de conteúdo'],['Comunidade','Engajamento da comunidade'],['Meta','Cumprimento vs meta'],['Monitoramento','Rastreamento de KPI em tempo real']],
  ru: [['Цели','Цели KPI по каналам'],['Роли','Роли каналов (узнаваемость·конверсия·удержание)'],['Настройка','Метрики, период, сегмент'],['Соцсети','KPI социальных каналов'],['Контент','Метрики эффективности контента'],['Сообщество','Вовлечённость сообщества'],['Цель','Достижение vs цель'],['Мониторинг','Отслеживание KPI в реальном времени']],
  ar: [['الأهداف','حدّد أهداف KPI لكل قناة'],['الأدوار','أدوار القناة (الوعي·التحويل·الاحتفاظ)'],['الإعداد','مقاييس التتبع والفترة والشريحة'],['السوشيال','مؤشرات القنوات الاجتماعية'],['المحتوى','مقاييس أداء المحتوى'],['المجتمع','تفاعل المجتمع'],['الهدف','التحقيق مقابل الهدف'],['المراقبة','تتبع KPI فوري']],
  hi: [['लक्ष्य','चैनल अनुसार KPI लक्ष्य सेट करें'],['भूमिका','चैनल भूमिका (जागरूकता·कन्वर्ज़न·रिटेंशन)'],['सेटअप','ट्रैकिंग मेट्रिक, अवधि, सेगमेंट'],['SNS','सोशल चैनल KPI'],['कंटेंट','कंटेंट प्रदर्शन मेट्रिक'],['कम्युनिटी','कम्युनिटी जुड़ाव'],['टारगेट','लक्ष्य बनाम उपलब्धि'],['मॉनिटरिंग','रियल-टाइम KPI ट्रैकिंग']],
};
const ST = {
  ko: [['채널 목표 설정','채널별 KPI 목표(노출·전환·매출)를 설정합니다.'],['채널 역할 정의','인지·전환·리텐션 등 채널의 역할을 정의합니다.'],['추적 설정','추적할 지표·기간·세그먼트를 설정합니다.'],['데이터 연동','채널 데이터를 연동해 실시간 KPI를 수집합니다.'],['성과 모니터링','목표 대비 달성률을 모니터링합니다.'],['개선·최적화','미달 채널을 진단하고 전략을 조정합니다.']],
  en: [['Set Channel Goals','Set per-channel KPI goals (impressions, conversion, revenue).'],['Define Channel Roles','Define each channel’s role: awareness, conversion, retention.'],['Configure Tracking','Set the metrics, period and segments to track.'],['Connect Data','Connect channel data to collect KPIs in real time.'],['Monitor Performance','Monitor achievement against goals.'],['Improve & Optimize','Diagnose underperforming channels and adjust strategy.']],
  ja: [['チャネル目標設定','チャネル別KPI目標(表示・転換・売上)を設定します。'],['チャネル役割定義','認知・転換・継続などチャネルの役割を定義します。'],['追跡設定','追跡する指標・期間・セグメントを設定します。'],['データ連携','チャネルデータを連携しリアルタイムKPIを収集します。'],['成果監視','目標対比の達成率を監視します。'],['改善・最適化','未達チャネルを診断し戦略を調整します。']],
  zh: [['设定渠道目标','设定各渠道KPI目标(曝光、转化、营收)。'],['定义渠道角色','定义各渠道角色:认知、转化、留存。'],['配置追踪','设定要追踪的指标、周期与分群。'],['连接数据','连接渠道数据以实时采集KPI。'],['监控成效','监控相对目标的达成率。'],['改进与优化','诊断未达渠道并调整策略。']],
  'zh-TW': [['設定通路目標','設定各通路KPI目標(曝光、轉換、營收)。'],['定義通路角色','定義各通路角色:認知、轉換、留存。'],['設定追蹤','設定要追蹤的指標、週期與分眾。'],['連接資料','連接通路資料以即時採集KPI。'],['監控成效','監控相對目標的達成率。'],['改進與最佳化','診斷未達通路並調整策略。']],
  de: [['Kanalziele setzen','KPI-Ziele je Kanal setzen (Impressionen, Conversion, Umsatz).'],['Kanalrollen definieren','Rolle jedes Kanals definieren: Awareness, Conversion, Retention.'],['Tracking konfigurieren','Metriken, Zeitraum und Segmente zum Tracken festlegen.'],['Daten verbinden','Kanaldaten verbinden, um KPIs in Echtzeit zu erfassen.'],['Leistung überwachen','Zielerreichung überwachen.'],['Verbessern & Optimieren','Schwache Kanäle diagnostizieren und Strategie anpassen.']],
  th: [['ตั้งเป้าช่องทาง','ตั้งเป้า KPI ต่อช่องทาง (การแสดง แปลง รายได้)'],['นิยามบทบาท','นิยามบทบาทแต่ละช่องทาง: รับรู้ แปลง คงอยู่'],['ตั้งค่าการติดตาม','ตั้งตัวชี้วัด ช่วงเวลา เซกเมนต์ที่จะติดตาม'],['เชื่อมข้อมูล','เชื่อมข้อมูลช่องทางเพื่อเก็บ KPI เรียลไทม์'],['ติดตามผล','ติดตามอัตราบรรลุเทียบเป้า'],['ปรับปรุง','วินิจฉัยช่องทางที่ไม่ถึงเป้าและปรับกลยุทธ์']],
  vi: [['Đặt mục tiêu kênh','Đặt mục tiêu KPI theo kênh (hiển thị, chuyển đổi, doanh thu).'],['Định nghĩa vai trò','Định nghĩa vai trò mỗi kênh: nhận biết, chuyển đổi, giữ chân.'],['Cấu hình theo dõi','Đặt chỉ số, kỳ và phân khúc để theo dõi.'],['Kết nối dữ liệu','Kết nối dữ liệu kênh để thu KPI thời gian thực.'],['Giám sát hiệu suất','Giám sát tỉ lệ đạt so với mục tiêu.'],['Cải thiện & tối ưu','Chẩn đoán kênh chưa đạt và điều chỉnh chiến lược.']],
  id: [['Tetapkan Tujuan','Tetapkan target KPI per kanal (tayang, konversi, pendapatan).'],['Definisikan Peran','Definisikan peran tiap kanal: awareness, konversi, retensi.'],['Konfigurasi Pelacakan','Tetapkan metrik, periode, dan segmen yang dilacak.'],['Hubungkan Data','Hubungkan data kanal untuk kumpulkan KPI real-time.'],['Pantau Performa','Pantau pencapaian terhadap target.'],['Perbaiki & Optimalkan','Diagnosis kanal kurang dan sesuaikan strategi.']],
  es: [['Fijar objetivos','Fija objetivos KPI por canal (impresiones, conversión, ingresos).'],['Definir roles','Define el rol de cada canal: notoriedad, conversión, retención.'],['Configurar seguimiento','Define métricas, periodo y segmentos a seguir.'],['Conectar datos','Conecta datos del canal para recopilar KPIs en tiempo real.'],['Monitorear','Monitorea el cumplimiento frente a los objetivos.'],['Mejorar y optimizar','Diagnostica canales bajos y ajusta la estrategia.']],
  fr: [['Fixer des objectifs','Fixez des objectifs KPI par canal (impressions, conversion, CA).'],['Définir les rôles','Définissez le rôle de chaque canal : notoriété, conversion, rétention.'],['Configurer le suivi','Définissez métriques, période et segments à suivre.'],['Connecter les données','Connectez les données du canal pour des KPI en temps réel.'],['Suivre la performance','Suivez l’atteinte des objectifs.'],['Améliorer et optimiser','Diagnostiquez les canaux faibles et ajustez la stratégie.']],
  pt: [['Definir metas','Defina metas de KPI por canal (impressões, conversão, receita).'],['Definir papéis','Defina o papel de cada canal: reconhecimento, conversão, retenção.'],['Configurar rastreamento','Defina métricas, período e segmentos a rastrear.'],['Conectar dados','Conecte dados do canal para coletar KPIs em tempo real.'],['Monitorar','Monitore o cumprimento das metas.'],['Melhorar e otimizar','Diagnostique canais fracos e ajuste a estratégia.']],
  ru: [['Цели каналов','Задайте цели KPI по каналам (показы, конверсия, выручка).'],['Роли каналов','Определите роль каждого канала: узнаваемость, конверсия, удержание.'],['Настройка трекинга','Задайте метрики, период и сегменты для отслеживания.'],['Подключение данных','Подключите данные каналов для KPI в реальном времени.'],['Мониторинг','Отслеживайте достижение целей.'],['Улучшение','Диагностируйте слабые каналы и корректируйте стратегию.']],
  ar: [['تحديد أهداف القنوات','حدّد أهداف KPI لكل قناة (الظهور، التحويل، الإيراد).'],['تعريف الأدوار','عرّف دور كل قناة: الوعي، التحويل، الاحتفاظ.'],['ضبط التتبع','حدّد المقاييس والفترة والشرائح للتتبع.'],['ربط البيانات','اربط بيانات القناة لجمع KPI فوريًا.'],['مراقبة الأداء','راقب تحقيق الأهداف.'],['التحسين','شخّص القنوات الضعيفة وعدّل الاستراتيجية.']],
  hi: [['चैनल लक्ष्य सेट','चैनल अनुसार KPI लक्ष्य (इम्प्रेशन, कन्वर्ज़न, राजस्व) सेट करें।'],['भूमिका तय करें','हर चैनल की भूमिका तय करें: जागरूकता, कन्वर्ज़न, रिटेंशन।'],['ट्रैकिंग कॉन्फ़िगर','ट्रैक करने हेतु मेट्रिक, अवधि, सेगमेंट सेट करें।'],['डेटा जोड़ें','चैनल डेटा जोड़कर रियल-टाइम KPI एकत्र करें।'],['प्रदर्शन मॉनिटर','लक्ष्य बनाम उपलब्धि मॉनिटर करें।'],['सुधार व अनुकूलन','कमज़ोर चैनल निदान कर रणनीति समायोजित करें।']],
};
const TP = {
  ko: ['모든 채널에 같은 목표를 두지 말고 채널 역할(인지/전환)에 맞는 KPI를 설정하세요.','목표 대비 달성률이 낮은 채널은 예산보다 소재·타겟을 먼저 점검하세요.','채널별 KPI는 주간 단위로 리뷰해 빠르게 전략을 조정하세요.','커뮤니티·SNS는 매출 외 참여·도달 지표도 함께 평가하세요.','달성 채널의 성공 요인을 다른 채널에 복제해 전체 성과를 끌어올리세요.'],
  en: ['Don’t set the same goal for every channel — set KPIs matching each channel’s role (awareness/conversion).','For channels with low achievement, check creatives and targeting before budget.','Review per-channel KPIs weekly to adjust strategy quickly.','For community and social, evaluate engagement and reach, not just revenue.','Replicate the success factors of top channels across others to lift overall performance.'],
  ja: ['全チャネルに同じ目標ではなく、役割(認知/転換)に合うKPIを設定します。','達成率が低いチャネルは予算より素材・ターゲットを先に点検します。','チャネル別KPIは週次でレビューし素早く戦略を調整します。','コミュニティ・SNSは売上以外に参加・到達指標も評価します。','達成チャネルの成功要因を他チャネルに複製し全体成果を高めます。'],
  zh: ['不要给所有渠道设相同目标——按渠道角色(认知/转化)设定KPI。','达成率低的渠道，先检查素材与定向，再看预算。','按周回顾各渠道KPI，快速调整策略。','社区与社交除营收外，也评估参与与触达指标。','将达标渠道的成功因素复制到其他渠道，提升整体成效。'],
  'zh-TW': ['不要給所有通路設相同目標——依通路角色(認知/轉換)設定KPI。','達成率低的通路，先檢查素材與鎖定，再看預算。','按週回顧各通路KPI，快速調整策略。','社群與社交除營收外，也評估參與與觸及指標。','將達標通路的成功因素複製到其他通路，提升整體成效。'],
  de: ['Nicht für jeden Kanal dasselbe Ziel — KPIs passend zur Kanalrolle (Awareness/Conversion) setzen.','Bei niedriger Zielerreichung zuerst Creatives und Targeting prüfen, nicht das Budget.','Kanal-KPIs wöchentlich prüfen, um die Strategie schnell anzupassen.','Bei Community und Social auch Engagement und Reichweite bewerten, nicht nur Umsatz.','Erfolgsfaktoren der Top-Kanäle auf andere übertragen, um die Gesamtleistung zu steigern.'],
  th: ['อย่าตั้งเป้าเดียวกันทุกช่องทาง — ตั้ง KPI ให้ตรงบทบาท (รับรู้/แปลง)','ช่องทางที่บรรลุต่ำ ให้ตรวจครีเอทีฟและการเจาะกลุ่มก่อนงบ','รีวิว KPI แต่ละช่องทางรายสัปดาห์เพื่อปรับกลยุทธ์เร็ว','คอมมูนิตี้และโซเชียล ประเมินการมีส่วนร่วมและการเข้าถึงด้วย ไม่ใช่แค่รายได้','คัดลอกปัจจัยสำเร็จของช่องทางที่ถึงเป้าไปยังช่องทางอื่นเพื่อยกผลรวม'],
  vi: ['Đừng đặt cùng mục tiêu cho mọi kênh — đặt KPI phù hợp vai trò (nhận biết/chuyển đổi).','Kênh đạt thấp, kiểm tra nội dung và nhắm mục tiêu trước ngân sách.','Xem KPI theo kênh hằng tuần để điều chỉnh chiến lược nhanh.','Với cộng đồng và mạng xã hội, đánh giá tương tác và tiếp cận, không chỉ doanh thu.','Nhân rộng yếu tố thành công của kênh top sang kênh khác để nâng hiệu suất tổng.'],
  id: ['Jangan beri tujuan sama ke semua kanal — tetapkan KPI sesuai peran (awareness/konversi).','Untuk kanal capaian rendah, cek kreatif dan targeting sebelum anggaran.','Tinjau KPI per kanal mingguan untuk menyesuaikan strategi cepat.','Untuk komunitas dan sosial, nilai engagement dan jangkauan, bukan hanya pendapatan.','Replikasi faktor sukses kanal teratas ke kanal lain untuk mengangkat performa total.'],
  es: ['No pongas el mismo objetivo a todos los canales: fija KPIs según el rol (notoriedad/conversión).','En canales con bajo cumplimiento, revisa creativos y segmentación antes que el presupuesto.','Revisa los KPIs por canal semanalmente para ajustar la estrategia rápido.','En comunidad y redes, evalúa interacción y alcance, no solo ingresos.','Replica los factores de éxito de los mejores canales en los demás para elevar el rendimiento.'],
  fr: ['Ne fixez pas le même objectif à tous les canaux — des KPI selon le rôle (notoriété/conversion).','Pour les canaux peu performants, vérifiez créas et ciblage avant le budget.','Revoyez les KPI par canal chaque semaine pour ajuster vite la stratégie.','Pour la communauté et le social, évaluez engagement et portée, pas seulement le CA.','Répliquez les facteurs de succès des meilleurs canaux sur les autres pour augmenter la performance.'],
  pt: ['Não defina a mesma meta para todos os canais — KPIs conforme o papel (reconhecimento/conversão).','Em canais com baixo cumprimento, verifique criativos e segmentação antes do orçamento.','Revise os KPIs por canal semanalmente para ajustar a estratégia rápido.','Em comunidade e redes, avalie engajamento e alcance, não só receita.','Replique os fatores de sucesso dos melhores canais nos demais para elevar o desempenho.'],
  ru: ['Не ставьте одну цель всем каналам — KPI под роль канала (узнаваемость/конверсия).','Для слабых каналов сначала проверьте креативы и таргетинг, а не бюджет.','Просматривайте KPI по каналам еженедельно, чтобы быстро менять стратегию.','Для сообщества и соцсетей оценивайте вовлечённость и охват, не только выручку.','Переносите факторы успеха топ-каналов на другие, чтобы поднять общий результат.'],
  ar: ['لا تضع هدفًا واحدًا لكل القنوات — حدّد KPI يناسب دور القناة (الوعي/التحويل).','للقنوات منخفضة التحقيق، افحص الإبداعات والاستهداف قبل الميزانية.','راجع KPI لكل قناة أسبوعيًا لتعديل الاستراتيجية بسرعة.','للمجتمع والسوشيال، قيّم التفاعل والوصول لا الإيراد فقط.','انسخ عوامل نجاح القنوات الأعلى إلى غيرها لرفع الأداء الكلي.'],
  hi: ['सभी चैनलों को एक लक्ष्य न दें — भूमिका (जागरूकता/कन्वर्ज़न) अनुसार KPI सेट करें।','कम उपलब्धि वाले चैनलों में बजट से पहले क्रिएटिव व टारगेटिंग जाँचें।','प्रति चैनल KPI साप्ताहिक रिव्यू कर रणनीति जल्दी समायोजित करें।','कम्युनिटी व सोशल में केवल राजस्व नहीं, जुड़ाव व पहुँच भी आँकें।','शीर्ष चैनलों के सफलता कारक अन्य चैनलों पर दोहराकर कुल प्रदर्शन बढ़ाएँ।'],
};
const TT = { ko:'탭 안내', en:'Tab Guide', ja:'タブ案内', zh:'分页指南', 'zh-TW':'分頁指南', de:'Tab-Leitfaden', th:'คู่มือแท็บ', vi:'Hướng dẫn tab', id:'Panduan Tab', es:'Guía por pestaña', fr:'Guide par onglet', pt:'Guia por aba', ru:'Гид по вкладкам', ar:'دليل التبويبات', hi:'टैब गाइड' };
const TGl = { ko:'이용가이드', en:'Guide', ja:'利用ガイド', zh:'使用指南', 'zh-TW':'使用指南', de:'Anleitung', th:'คู่มือ', vi:'Hướng dẫn', id:'Panduan', es:'Guía', fr:'Guide', pt:'Guia', ru:'Руководство', ar:'الدليل', hi:'गाइड' };
const ttl = { ko:'채널 KPI 이용 가이드', en:'Channel KPI Guide', ja:'チャネルKPI 利用ガイド', zh:'渠道KPI 使用指南', 'zh-TW':'通路KPI 使用指南', de:'Kanal-KPI-Leitfaden', th:'คู่มือ KPI ช่องทาง', vi:'Hướng dẫn KPI Kênh', id:'Panduan KPI Kanal', es:'Guía de KPI por Canal', fr:'Guide KPI Canal', pt:'Guia de KPI por Canal', ru:'Руководство по KPI каналов', ar:'دليل KPI القنوات', hi:'चैनल KPI गाइड' };
const sub = { ko:'채널별 KPI 목표 설정·역할 정의·추적·모니터링·최적화를 단계별로 안내합니다. 초보자도 이 가이드만 보고 시작할 수 있습니다.', en:'A step-by-step guide to setting per-channel KPI goals, defining roles, tracking, monitoring and optimizing. Beginners can start with this guide alone.', ja:'チャネル別KPIの目標設定・役割定義・追跡・監視・最適化を段階的に案内します。初心者もこのガイドだけで始められます。', zh:'分步指导各渠道KPI目标设定、角色定义、追踪、监控与优化。新手仅看本指南即可上手。', 'zh-TW':'分步指導各通路KPI目標設定、角色定義、追蹤、監控與最佳化。新手僅看本指南即可上手。', de:'Schritt-für-Schritt zu KPI-Zielen je Kanal, Rollen, Tracking, Monitoring und Optimierung. Auch Einsteiger starten allein damit.', th:'คู่มือทีละขั้นในการตั้งเป้า KPI ต่อช่องทาง นิยามบทบาท ติดตาม มอนิเตอร์ และปรับให้เหมาะ มือใหม่อ่านคู่มือนี้ก็เริ่มได้', vi:'Hướng dẫn từng bước đặt mục tiêu KPI theo kênh, định nghĩa vai trò, theo dõi, giám sát và tối ưu. Người mới có thể bắt đầu chỉ với hướng dẫn này.', id:'Panduan langkah demi langkah menetapkan target KPI per kanal, mendefinisikan peran, melacak, memantau, dan mengoptimalkan. Pemula bisa mulai hanya dengan panduan ini.', es:'Guía paso a paso para fijar objetivos KPI por canal, definir roles, seguir, monitorear y optimizar. Los principiantes pueden empezar solo con esta guía.', fr:'Guide pas à pas pour fixer des objectifs KPI par canal, définir les rôles, suivre, surveiller et optimiser. Les débutants démarrent avec ce seul guide.', pt:'Guia passo a passo para definir metas de KPI por canal, papéis, rastreamento, monitoramento e otimização. Iniciantes podem começar só com este guia.', ru:'Пошаговое руководство по целям KPI каналов, ролям, трекингу, мониторингу и оптимизации. Новичок начнёт по этому руководству.', ar:'دليل خطوة بخطوة لتحديد أهداف KPI لكل قناة وتعريف الأدوار والتتبع والمراقبة والتحسين. يمكن للمبتدئ البدء بهذا الدليل وحده.', hi:'चैनल अनुसार KPI लक्ष्य, भूमिका, ट्रैकिंग, मॉनिटरिंग व अनुकूलन की चरण-दर-चरण गाइड। नौसिखिए भी सिर्फ़ इसी से शुरू कर सकते हैं।' };
const stt = { ko:'시작 단계', en:'Getting Started', ja:'始める手順', zh:'开始步骤', 'zh-TW':'開始步驟', de:'Erste Schritte', th:'ขั้นตอนเริ่มต้น', vi:'Bắt đầu', id:'Memulai', es:'Primeros pasos', fr:'Premiers pas', pt:'Primeiros passos', ru:'Начало работы', ar:'البدء', hi:'शुरुआत' };
const tpt = { ko:'전문가 팁', en:'Expert Tips', ja:'専門家のヒント', zh:'专家提示', 'zh-TW':'專家提示', de:'Profi-Tipps', th:'เคล็ดลับผู้เชี่ยวชาญ', vi:'Mẹo chuyên gia', id:'Tips Pakar', es:'Consejos de experto', fr:'Conseils d’expert', pt:'Dicas de especialista', ru:'Советы эксперта', ar:'نصائح الخبراء', hi:'विशेषज्ञ सुझाव' };
const LANGS = Object.keys(TB);
export const CK_GUIDE = Object.fromEntries(LANGS.map(l => [l, B(TGl[l], ttl[l], sub[l], stt[l], ST[l], TT[l], TB[l], tpt[l], TP[l])]));
