<?php
declare(strict_types=1);
namespace Genie\Handlers;

/** 마케팅 인사이트 리포트 결정론적 폴백 템플릿 — 15개국(231차). ClaudeAI::deterministicInsight 소비. */
class MmmReportI18n {
  private const M = [
    "ko" => ['emptySummary'=>'아직 분석할 성과 데이터가 충분하지 않습니다. 채널을 연동·집행하면 자동으로 인사이트가 생성됩니다.', 'emptyRecommendation'=>'광고 채널 연동 및 데이터 수집을 먼저 진행하세요.', 'summaryHead'=>'최근 {days}일 총 광고비 {spend}, 매출 {revenue}, 종합 ROAS {roas}x. ', 'summaryBest'=>'최고 효율은 {ch}(ROAS {roas}x), ', 'summaryWorst'=>'최저는 {ch}(ROAS {roas}x) 입니다.', 'bullet'=>'{ch}: 광고비 {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'{worst} 등 저효율 채널 예산을 {best}(으)로 재배분 검토 (MMM 최적화 참고).', 'recommendationNoBest'=>'고효율 채널 증액 여지를 MMM 최적화로 확인하세요.', 'risk'=>'{worst} ROAS 1.5x 미만 — 손실 위험, 점검 필요', 'aiUnavailableNote'=>'AI 미가용 — 규칙 기반 요약 (관리자 Claude 키 설정 시 서술형 AI 활성)'],
    "en" => ['emptySummary'=>'There is not yet enough performance data to analyze. Once you connect and run channels, insights are generated automatically.', 'emptyRecommendation'=>'Connect your ad channels and collect data first.', 'summaryHead'=>'Over the last {days} days: total ad spend {spend}, revenue {revenue}, overall ROAS {roas}x. ', 'summaryBest'=>'Top performer is {ch} (ROAS {roas}x), ', 'summaryWorst'=>'the lowest is {ch} (ROAS {roas}x).', 'bullet'=>'{ch}: ad spend {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'Consider reallocating budget from low-efficiency channels such as {worst} to {best} (see MMM optimization).', 'recommendationNoBest'=>'Use MMM optimization to identify room for scaling up high-efficiency channels.', 'risk'=>'{worst} ROAS below 1.5x — risk of loss, review needed', 'aiUnavailableNote'=>'AI unavailable — rule-based summary (narrative AI activates once an admin sets a Claude key)'],
    "ja" => ['emptySummary'=>'分析するための成果データがまだ十分ではありません。チャネルを連携·実行すると、自動的にインサイトが生成されます。', 'emptyRecommendation'=>'まず広告チャネルの連携とデータ収集を進めてください。', 'summaryHead'=>'直近{days}日間の総広告費{spend}、売上{revenue}、総合ROAS {roas}x。 ', 'summaryBest'=>'最高効率は{ch}(ROAS {roas}x)、 ', 'summaryWorst'=>'最低は{ch}(ROAS {roas}x)です。', 'bullet'=>'{ch}: 広告費 {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'{worst}など低効率チャネルの予算を{best}へ再配分する検討を(MMM最適化を参照)。', 'recommendationNoBest'=>'高効率チャネルの増額余地をMMM最適化で確認してください。', 'risk'=>'{worst} ROAS 1.5x未満 — 損失リスク、点検が必要', 'aiUnavailableNote'=>'AI利用不可 — ルールベース要約(管理者がClaudeキーを設定すると記述型AIが有効化)'],
    "zh" => ['emptySummary'=>'尚无足够的绩效数据可供分析。连接并投放渠道后，将自动生成洞察。', 'emptyRecommendation'=>'请先连接广告渠道并收集数据。', 'summaryHead'=>'最近{days}天总广告费{spend}，销售额{revenue}，综合ROAS {roas}x。 ', 'summaryBest'=>'效率最高的是{ch}(ROAS {roas}x)， ', 'summaryWorst'=>'最低的是{ch}(ROAS {roas}x)。', 'bullet'=>'{ch}: 广告费 {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'考虑将{worst}等低效渠道的预算重新分配至{best}(参考MMM优化)。', 'recommendationNoBest'=>'请通过MMM优化确认高效渠道的增投空间。', 'risk'=>'{worst} ROAS 低于 1.5x — 存在亏损风险，需检查', 'aiUnavailableNote'=>'AI 不可用 — 基于规则的摘要(管理员设置 Claude 密钥后启用叙述式 AI)'],
    "zh-TW" => ['emptySummary'=>'尚無足夠的成效資料可供分析。連接並投放通路後，將自動產生洞察。', 'emptyRecommendation'=>'請先連接廣告通路並收集資料。', 'summaryHead'=>'最近{days}天總廣告費{spend}，營收{revenue}，綜合ROAS {roas}x。 ', 'summaryBest'=>'效率最高的是{ch}(ROAS {roas}x)， ', 'summaryWorst'=>'最低的是{ch}(ROAS {roas}x)。', 'bullet'=>'{ch}: 廣告費 {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'考慮將{worst}等低效通路的預算重新分配至{best}(參考MMM最佳化)。', 'recommendationNoBest'=>'請透過MMM最佳化確認高效通路的增投空間。', 'risk'=>'{worst} ROAS 低於 1.5x — 存在虧損風險，需檢查', 'aiUnavailableNote'=>'AI 不可用 — 基於規則的摘要(管理員設定 Claude 金鑰後啟用敘述式 AI)'],
    "de" => ['emptySummary'=>'Es liegen noch nicht genügend Leistungsdaten zur Analyse vor. Sobald Sie Kanäle verbinden und ausspielen, werden Insights automatisch generiert.', 'emptyRecommendation'=>'Verbinden Sie zunächst Ihre Werbekanäle und sammeln Sie Daten.', 'summaryHead'=>'In den letzten {days} Tagen: Gesamtwerbeausgaben {spend}, Umsatz {revenue}, Gesamt-ROAS {roas}x. ', 'summaryBest'=>'Der Spitzenreiter ist {ch} (ROAS {roas}x), ', 'summaryWorst'=>'der niedrigste ist {ch} (ROAS {roas}x).', 'bullet'=>'{ch}: Werbeausgaben {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'Erwägen Sie, das Budget von ineffizienten Kanälen wie {worst} auf {best} umzuverteilen (siehe MMM-Optimierung).', 'recommendationNoBest'=>'Nutzen Sie die MMM-Optimierung, um Spielraum für die Aufstockung effizienter Kanäle zu ermitteln.', 'risk'=>'{worst} ROAS unter 1,5x — Verlustrisiko, Überprüfung erforderlich', 'aiUnavailableNote'=>'KI nicht verfügbar — regelbasierte Zusammenfassung (narrative KI wird aktiviert, sobald ein Administrator einen Claude-Schlüssel festlegt)'],
    "th" => ['emptySummary'=>'ยังมีข้อมูลประสิทธิภาพไม่เพียงพอสำหรับการวิเคราะห์ เมื่อคุณเชื่อมต่อและดำเนินการช่องทาง ระบบจะสร้างข้อมูลเชิงลึกโดยอัตโนมัติ', 'emptyRecommendation'=>'โปรดเชื่อมต่อช่องทางโฆษณาและเก็บรวบรวมข้อมูลก่อน', 'summaryHead'=>'ในช่วง {days} วันล่าสุด ค่าโฆษณารวม {spend} รายได้ {revenue} ROAS รวม {roas}x ', 'summaryBest'=>'ที่มีประสิทธิภาพสูงสุดคือ {ch} (ROAS {roas}x) ', 'summaryWorst'=>'ที่ต่ำที่สุดคือ {ch} (ROAS {roas}x)', 'bullet'=>'{ch}: ค่าโฆษณา {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'พิจารณาจัดสรรงบประมาณจากช่องทางประสิทธิภาพต่ำ เช่น {worst} ไปยัง {best} (ดูการเพิ่มประสิทธิภาพ MMM)', 'recommendationNoBest'=>'ใช้การเพิ่มประสิทธิภาพ MMM เพื่อระบุช่องว่างในการเพิ่มงบให้ช่องทางที่มีประสิทธิภาพสูง', 'risk'=>'{worst} ROAS ต่ำกว่า 1.5x — เสี่ยงขาดทุน ต้องตรวจสอบ', 'aiUnavailableNote'=>'AI ไม่พร้อมใช้งาน — บทสรุปแบบอิงกฎ (AI เชิงบรรยายจะเปิดใช้งานเมื่อผู้ดูแลตั้งค่าคีย์ Claude)'],
    "vi" => ['emptySummary'=>'Chưa có đủ dữ liệu hiệu suất để phân tích. Khi bạn kết nối và chạy các kênh, thông tin chi tiết sẽ được tạo tự động.', 'emptyRecommendation'=>'Hãy kết nối các kênh quảng cáo và thu thập dữ liệu trước.', 'summaryHead'=>'Trong {days} ngày gần đây: tổng chi phí quảng cáo {spend}, doanh thu {revenue}, ROAS tổng thể {roas}x. ', 'summaryBest'=>'Hiệu quả nhất là {ch} (ROAS {roas}x), ', 'summaryWorst'=>'thấp nhất là {ch} (ROAS {roas}x).', 'bullet'=>'{ch}: chi phí quảng cáo {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'Cân nhắc phân bổ lại ngân sách từ các kênh hiệu quả thấp như {worst} sang {best} (xem tối ưu hóa MMM).', 'recommendationNoBest'=>'Sử dụng tối ưu hóa MMM để xác định dư địa tăng chi cho các kênh hiệu quả cao.', 'risk'=>'{worst} ROAS dưới 1.5x — nguy cơ thua lỗ, cần xem xét', 'aiUnavailableNote'=>'AI không khả dụng — tóm tắt dựa trên quy tắc (AI tường thuật kích hoạt khi quản trị viên thiết lập khóa Claude)'],
    "id" => ['emptySummary'=>'Belum ada cukup data kinerja untuk dianalisis. Setelah Anda menghubungkan dan menjalankan saluran, wawasan dihasilkan secara otomatis.', 'emptyRecommendation'=>'Hubungkan saluran iklan Anda dan kumpulkan data terlebih dahulu.', 'summaryHead'=>'Selama {days} hari terakhir: total belanja iklan {spend}, pendapatan {revenue}, ROAS keseluruhan {roas}x. ', 'summaryBest'=>'Performa terbaik adalah {ch} (ROAS {roas}x), ', 'summaryWorst'=>'yang terendah adalah {ch} (ROAS {roas}x).', 'bullet'=>'{ch}: belanja iklan {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'Pertimbangkan untuk mengalokasikan kembali anggaran dari saluran berefisiensi rendah seperti {worst} ke {best} (lihat optimasi MMM).', 'recommendationNoBest'=>'Gunakan optimasi MMM untuk mengidentifikasi ruang peningkatan saluran berefisiensi tinggi.', 'risk'=>'{worst} ROAS di bawah 1.5x — risiko kerugian, perlu ditinjau', 'aiUnavailableNote'=>'AI tidak tersedia — ringkasan berbasis aturan (AI naratif aktif setelah admin mengatur kunci Claude)'],
    "ar" => ['emptySummary'=>'لا توجد بيانات أداء كافية للتحليل بعد. بمجرد ربط القنوات وتشغيلها، يتم إنشاء الرؤى تلقائيًا.', 'emptyRecommendation'=>'اربط قنوات الإعلانات وجمّع البيانات أولاً.', 'summaryHead'=>'خلال آخر {days} يوم: إجمالي الإنفاق الإعلاني {spend}، الإيراد {revenue}، ROAS الإجمالي {roas}x. ', 'summaryBest'=>'الأعلى أداءً هو {ch} (ROAS {roas}x)، ', 'summaryWorst'=>'والأدنى هو {ch} (ROAS {roas}x).', 'bullet'=>'{ch}: الإنفاق الإعلاني {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'ضع في اعتبارك إعادة توزيع الميزانية من القنوات منخفضة الكفاءة مثل {worst} إلى {best} (راجع تحسين MMM).', 'recommendationNoBest'=>'استخدم تحسين MMM لتحديد إمكانية زيادة الإنفاق على القنوات عالية الكفاءة.', 'risk'=>'{worst} ROAS أقل من 1.5x — خطر الخسارة، يلزم المراجعة', 'aiUnavailableNote'=>'الذكاء الاصطناعي غير متاح — ملخص قائم على القواعد (يُفعَّل الذكاء الاصطناعي السردي عند ضبط المسؤول لمفتاح Claude)'],
    "es" => ['emptySummary'=>'Aún no hay suficientes datos de rendimiento para analizar. Una vez que conecte y ejecute los canales, los insights se generan automáticamente.', 'emptyRecommendation'=>'Conecte primero sus canales publicitarios y recopile datos.', 'summaryHead'=>'En los últimos {days} días: gasto publicitario total {spend}, ingresos {revenue}, ROAS general {roas}x. ', 'summaryBest'=>'El de mayor rendimiento es {ch} (ROAS {roas}x), ', 'summaryWorst'=>'el más bajo es {ch} (ROAS {roas}x).', 'bullet'=>'{ch}: gasto publicitario {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'Considere reasignar el presupuesto de canales de baja eficiencia como {worst} a {best} (consulte la optimización MMM).', 'recommendationNoBest'=>'Use la optimización MMM para identificar margen para escalar los canales de alta eficiencia.', 'risk'=>'{worst} ROAS por debajo de 1,5x — riesgo de pérdida, requiere revisión', 'aiUnavailableNote'=>'IA no disponible — resumen basado en reglas (la IA narrativa se activa cuando un administrador configura una clave de Claude)'],
    "fr" => ['emptySummary'=>'Les données de performance ne sont pas encore suffisantes pour l\x27analyse. Une fois les canaux connectés et diffusés, les insights sont générés automatiquement.', 'emptyRecommendation'=>'Connectez d\x27abord vos canaux publicitaires et collectez des données.', 'summaryHead'=>'Au cours des {days} derniers jours : dépenses publicitaires totales {spend}, revenu {revenue}, ROAS global {roas}x. ', 'summaryBest'=>'Le plus performant est {ch} (ROAS {roas}x), ', 'summaryWorst'=>'le plus faible est {ch} (ROAS {roas}x).', 'bullet'=>'{ch} : dépenses publicitaires {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'Envisagez de réaffecter le budget des canaux peu efficaces comme {worst} vers {best} (voir l\x27optimisation MMM).', 'recommendationNoBest'=>'Utilisez l\x27optimisation MMM pour repérer la marge d\x27augmentation des canaux à haute efficacité.', 'risk'=>'{worst} ROAS inférieur à 1,5x — risque de perte, examen nécessaire', 'aiUnavailableNote'=>'IA indisponible — résumé basé sur des règles (l\x27IA narrative s\x27active dès qu\x27un administrateur configure une clé Claude)'],
    "hi" => ['emptySummary'=>'विश्लेषण के लिए अभी पर्याप्त प्रदर्शन डेटा नहीं है। एक बार जब आप चैनल जोड़ते और चलाते हैं, तो इनसाइट्स स्वतः उत्पन्न होती हैं।', 'emptyRecommendation'=>'पहले अपने विज्ञापन चैनल जोड़ें और डेटा एकत्र करें।', 'summaryHead'=>'पिछले {days} दिनों में: कुल विज्ञापन व्यय {spend}, राजस्व {revenue}, समग्र ROAS {roas}x. ', 'summaryBest'=>'सर्वश्रेष्ठ प्रदर्शन {ch} (ROAS {roas}x) का है, ', 'summaryWorst'=>'सबसे कम {ch} (ROAS {roas}x) है।', 'bullet'=>'{ch}: विज्ञापन व्यय {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'{worst} जैसे कम दक्षता वाले चैनलों के बजट को {best} में पुनः आवंटित करने पर विचार करें (MMM अनुकूलन देखें)।', 'recommendationNoBest'=>'उच्च दक्षता वाले चैनलों को बढ़ाने की गुंजाइश पहचानने के लिए MMM अनुकूलन का उपयोग करें।', 'risk'=>'{worst} ROAS 1.5x से कम — हानि का जोखिम, समीक्षा आवश्यक', 'aiUnavailableNote'=>'AI अनुपलब्ध — नियम-आधारित सारांश (व्यवस्थापक द्वारा Claude कुंजी सेट करने पर वर्णनात्मक AI सक्रिय होता है)'],
    "pt" => ['emptySummary'=>'Ainda não há dados de desempenho suficientes para analisar. Assim que você conectar e executar os canais, os insights são gerados automaticamente.', 'emptyRecommendation'=>'Conecte seus canais de anúncios e colete dados primeiro.', 'summaryHead'=>'Nos últimos {days} dias: gasto total com anúncios {spend}, receita {revenue}, ROAS geral {roas}x. ', 'summaryBest'=>'O de melhor desempenho é {ch} (ROAS {roas}x), ', 'summaryWorst'=>'o mais baixo é {ch} (ROAS {roas}x).', 'bullet'=>'{ch}: gasto com anúncios {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'Considere realocar o orçamento de canais de baixa eficiência como {worst} para {best} (consulte a otimização MMM).', 'recommendationNoBest'=>'Use a otimização MMM para identificar margem para aumentar canais de alta eficiência.', 'risk'=>'{worst} ROAS abaixo de 1,5x — risco de prejuízo, revisão necessária', 'aiUnavailableNote'=>'IA indisponível — resumo baseado em regras (a IA narrativa é ativada quando um administrador define uma chave Claude)'],
    "ru" => ['emptySummary'=>'Пока недостаточно данных о результативности для анализа. Как только вы подключите и запустите каналы, аналитика будет сформирована автоматически.', 'emptyRecommendation'=>'Сначала подключите рекламные каналы и соберите данные.', 'summaryHead'=>'За последние {days} дн.: общие расходы на рекламу {spend}, выручка {revenue}, общий ROAS {roas}x. ', 'summaryBest'=>'Лучший результат у {ch} (ROAS {roas}x), ', 'summaryWorst'=>'самый низкий — у {ch} (ROAS {roas}x).', 'bullet'=>'{ch}: расходы на рекламу {spend} · ROAS {roas}x', 'bulletCpa'=>' · CPA {cpa}', 'recommendation'=>'Рассмотрите перераспределение бюджета с низкоэффективных каналов, таких как {worst}, на {best} (см. оптимизацию MMM).', 'recommendationNoBest'=>'Используйте оптимизацию MMM, чтобы определить возможности для увеличения вложений в высокоэффективные каналы.', 'risk'=>'{worst} ROAS ниже 1.5x — риск убытка, требуется проверка', 'aiUnavailableNote'=>'AI недоступен — сводка на основе правил (нарративный AI активируется, когда администратор задаёт ключ Claude)'],
  ];
  public static function tpl(string $lang, string $key): string {
    $m = self::M[$lang] ?? self::M['ko'];
    return $m[$key] ?? (self::M['ko'][$key] ?? '');
  }
}
