/**
 * billingI18n — 광고비 결제수단(카드 등록·관리형 지출 월렛) 공유 15개국 사전.
 * PaymentMethods 페이지 / CardRequiredBanner / 각 메뉴 이용가이드에서 단일 소스로 재사용.
 * 사용: import { bt } from '../utils/billingI18n'; bt('pageTitle', lang)
 */

const DICT = {
  pageTitle: { ko:"광고비 결제수단", en:"Ad Spend Payment Method", ja:"広告費の決済手段", zh:"广告费支付方式", "zh-TW":"廣告費付款方式", vi:"Phương thức thanh toán chi phí quảng cáo", th:"วิธีชำระค่าโฆษณา", id:"Metode Pembayaran Biaya Iklan", de:"Zahlungsmethode für Werbeausgaben", fr:"Moyen de paiement des dépenses publicitaires", es:"Método de pago de gasto publicitario", pt:"Método de pagamento de gastos com anúncios", ru:"Способ оплаты рекламных расходов", ar:"وسيلة دفع نفقات الإعلان", hi:"विज्ञापन व्यय भुगतान विधि" },
  pageDesc: { ko:"마케팅 자동화가 광고를 집행할 때 사용할 카드를 등록합니다. 등록한 카드는 [마케팅 자동화]에서 설정한 월 예산 한도 내에서만 청구됩니다.", en:"Register the card used when Marketing Automation runs your ads. It is only charged within the monthly budget cap you set in Marketing Automation.", ja:"マーケティング自動化が広告を実行する際に使うカードを登録します。登録したカードは[マーケティング自動化]で設定した月予算の上限内でのみ請求されます。", zh:"登记营销自动化投放广告时所用的卡。仅在您于[营销自动化]中设置的月度预算上限内扣款。", "zh-TW":"登記行銷自動化投放廣告時所用的卡。僅在您於[行銷自動化]中設定的月度預算上限內扣款。", vi:"Đăng ký thẻ dùng khi Tự động hóa Marketing chạy quảng cáo. Thẻ chỉ bị tính phí trong hạn mức ngân sách hằng tháng bạn đặt ở Tự động hóa Marketing.", th:"ลงทะเบียนบัตรที่ใช้เมื่อระบบการตลาดอัตโนมัติรันโฆษณา จะถูกเรียกเก็บภายในเพดานงบรายเดือนที่คุณตั้งไว้เท่านั้น", id:"Daftarkan kartu yang dipakai saat Otomasi Pemasaran menjalankan iklan. Hanya ditagih dalam batas anggaran bulanan yang Anda tetapkan.", de:"Registrieren Sie die Karte, die die Marketing-Automatisierung für Ihre Anzeigen nutzt. Sie wird nur innerhalb des in der Marketing-Automatisierung festgelegten Monatsbudgets belastet.", fr:"Enregistrez la carte utilisée lorsque l'automatisation marketing diffuse vos publicités. Elle n'est débitée que dans la limite du budget mensuel défini.", es:"Registre la tarjeta que usará la Automatización de Marketing al ejecutar sus anuncios. Solo se cobra dentro del límite de presupuesto mensual que establezca.", pt:"Registe o cartão usado quando a Automação de Marketing executa os seus anúncios. Só é cobrado dentro do limite de orçamento mensal definido.", ru:"Зарегистрируйте карту, используемую при запуске рекламы автоматизацией маркетинга. Списания только в пределах месячного лимита, заданного вами.", ar:"سجّل البطاقة المستخدمة عند تشغيل الأتمتة التسويقية لإعلاناتك. لا يتم الخصم إلا ضمن سقف الميزانية الشهرية الذي تحدده.", hi:"मार्केटिंग ऑटोमेशन द्वारा विज्ञापन चलाते समय उपयोग होने वाला कार्ड पंजीकृत करें। यह केवल आपके द्वारा निर्धारित मासिक बजट सीमा के भीतर ही चार्ज होगा।" },
  registerBtn: { ko:"카드 등록하기", en:"Register Card", ja:"カードを登録", zh:"登记卡片", "zh-TW":"登記卡片", vi:"Đăng ký thẻ", th:"ลงทะเบียนบัตร", id:"Daftarkan Kartu", de:"Karte registrieren", fr:"Enregistrer la carte", es:"Registrar tarjeta", pt:"Registar cartão", ru:"Привязать карту", ar:"تسجيل البطاقة", hi:"कार्ड पंजीकृत करें" },
  noCard: { ko:"등록된 결제수단이 없습니다.", en:"No payment method registered.", ja:"登録された決済手段がありません。", zh:"尚未登记支付方式。", "zh-TW":"尚未登記付款方式。", vi:"Chưa có phương thức thanh toán nào.", th:"ยังไม่มีวิธีชำระเงินที่ลงทะเบียน", id:"Belum ada metode pembayaran terdaftar.", de:"Keine Zahlungsmethode registriert.", fr:"Aucun moyen de paiement enregistré.", es:"No hay método de pago registrado.", pt:"Nenhum método de pagamento registado.", ru:"Способ оплаты не привязан.", ar:"لا توجد وسيلة دفع مسجّلة.", hi:"कोई भुगतान विधि पंजीकृत नहीं।" },
  defaultBadge: { ko:"기본", en:"Default", ja:"既定", zh:"默认", "zh-TW":"預設", vi:"Mặc định", th:"ค่าเริ่มต้น", id:"Default", de:"Standard", fr:"Par défaut", es:"Predeterminada", pt:"Predefinida", ru:"Основная", ar:"افتراضية", hi:"डिफ़ॉल्ट" },
  setDefaultBtn: { ko:"기본으로 설정", en:"Set as default", ja:"既定に設定", zh:"设为默认", "zh-TW":"設為預設", vi:"Đặt làm mặc định", th:"ตั้งเป็นค่าเริ่มต้น", id:"Jadikan default", de:"Als Standard", fr:"Définir par défaut", es:"Predeterminar", pt:"Tornar predefinida", ru:"Сделать основной", ar:"تعيين كافتراضية", hi:"डिफ़ॉल्ट बनाएं" },
  deleteBtn: { ko:"삭제", en:"Delete", ja:"削除", zh:"删除", "zh-TW":"刪除", vi:"Xóa", th:"ลบ", id:"Hapus", de:"Löschen", fr:"Supprimer", es:"Eliminar", pt:"Eliminar", ru:"Удалить", ar:"حذف", hi:"हटाएं" },
  demoMsg: { ko:"체험 데모 모드에서는 결제수단을 등록할 수 없습니다. 실제 구독 플랜으로 가입 후 이용해 주세요.", en:"Payment methods cannot be registered in demo mode. Please sign up for a paid plan first.", ja:"体験デモモードでは決済手段を登録できません。実際の有料プランにご登録のうえご利用ください。", zh:"体验演示模式无法登记支付方式。请先注册付费方案。", "zh-TW":"體驗示範模式無法登記付款方式。請先註冊付費方案。", vi:"Không thể đăng ký phương thức thanh toán ở chế độ demo. Vui lòng đăng ký gói trả phí trước.", th:"ไม่สามารถลงทะเบียนวิธีชำระเงินในโหมดทดลองได้ กรุณาสมัครแพ็กเกจแบบชำระเงินก่อน", id:"Metode pembayaran tidak dapat didaftarkan di mode demo. Silakan berlangganan paket berbayar dulu.", de:"Im Demo-Modus können keine Zahlungsmethoden registriert werden. Bitte zuerst einen kostenpflichtigen Plan abschließen.", fr:"Les moyens de paiement ne peuvent pas être enregistrés en mode démo. Veuillez d'abord souscrire un forfait payant.", es:"No se pueden registrar métodos de pago en modo demo. Suscríbase primero a un plan de pago.", pt:"Não é possível registar métodos de pagamento no modo demo. Subscreva primeiro um plano pago.", ru:"В демо-режиме нельзя привязать способ оплаты. Сначала оформите платный тариф.", ar:"لا يمكن تسجيل وسائل الدفع في وضع التجربة. يرجى الاشتراك في خطة مدفوعة أولاً.", hi:"डेमो मोड में भुगतान विधि पंजीकृत नहीं की जा सकती। कृपया पहले सशुल्क प्लान लें।" },
  notConfigured: { ko:"결제 게이트웨이가 아직 설정되지 않았습니다. 관리자에게 문의해 주세요.", en:"The payment gateway is not configured yet. Please contact your administrator.", ja:"決済ゲートウェイがまだ設定されていません。管理者にお問い合わせください。", zh:"支付网关尚未配置。请联系管理员。", "zh-TW":"支付閘道尚未設定。請聯絡管理員。", vi:"Cổng thanh toán chưa được cấu hình. Vui lòng liên hệ quản trị viên.", th:"ยังไม่ได้ตั้งค่าเกตเวย์การชำระเงิน กรุณาติดต่อผู้ดูแลระบบ", id:"Gateway pembayaran belum dikonfigurasi. Hubungi administrator.", de:"Das Zahlungs-Gateway ist noch nicht konfiguriert. Bitte wenden Sie sich an Ihren Administrator.", fr:"La passerelle de paiement n'est pas encore configurée. Veuillez contacter votre administrateur.", es:"La pasarela de pago aún no está configurada. Contacte con su administrador.", pt:"O gateway de pagamento ainda não está configurado. Contacte o administrador.", ru:"Платёжный шлюз ещё не настроен. Обратитесь к администратору.", ar:"لم يتم إعداد بوابة الدفع بعد. يرجى التواصل مع المسؤول.", hi:"पेमेंट गेटवे अभी कॉन्फ़िगर नहीं हुआ है। कृपया व्यवस्थापक से संपर्क करें।" },
  secureNote: { ko:"PCI-DSS 안전 · 카드번호 비저장(토큰화) · 은행급 암호화", en:"PCI-DSS safe · card number not stored (tokenized) · bank-grade encryption", ja:"PCI-DSS安全・カード番号は非保存（トークン化）・銀行級暗号化", zh:"PCI-DSS 安全 · 不存储卡号（令牌化）· 银行级加密", "zh-TW":"PCI-DSS 安全 · 不儲存卡號（代碼化）· 銀行級加密", vi:"An toàn PCI-DSS · không lưu số thẻ (token hóa) · mã hóa cấp ngân hàng", th:"ปลอดภัยตาม PCI-DSS · ไม่เก็บเลขบัตร (โทเค็น) · เข้ารหัสระดับธนาคาร", id:"Aman PCI-DSS · nomor kartu tidak disimpan (tokenisasi) · enkripsi setara bank", de:"PCI-DSS-sicher · Kartennummer nicht gespeichert (tokenisiert) · Verschlüsselung auf Bankniveau", fr:"Conforme PCI-DSS · numéro de carte non stocké (tokenisé) · chiffrement bancaire", es:"Seguro PCI-DSS · número de tarjeta no almacenado (tokenizado) · cifrado bancario", pt:"Seguro PCI-DSS · número do cartão não armazenado (tokenizado) · encriptação bancária", ru:"Безопасно по PCI-DSS · номер карты не хранится (токенизация) · шифрование банковского уровня", ar:"آمن وفق PCI-DSS · لا يُخزَّن رقم البطاقة (ترميز) · تشفير بمستوى البنوك", hi:"PCI-DSS सुरक्षित · कार्ड नंबर संग्रहीत नहीं (टोकनयुक्त) · बैंक-स्तरीय एन्क्रिप्शन" },
  budgetTitle: { ko:"이번 달 광고비 청구 현황", en:"This month's ad spend billing", ja:"今月の広告費請求状況", zh:"本月广告费扣款情况", "zh-TW":"本月廣告費扣款狀況", vi:"Thanh toán chi phí quảng cáo tháng này", th:"สถานะการเรียกเก็บค่าโฆษณาเดือนนี้", id:"Penagihan biaya iklan bulan ini", de:"Werbeabrechnung dieses Monats", fr:"Facturation publicitaire du mois", es:"Facturación publicitaria de este mes", pt:"Faturação de anúncios deste mês", ru:"Списания за рекламу в этом месяце", ar:"فوترة نفقات الإعلان لهذا الشهر", hi:"इस माह का विज्ञापन बिलिंग" },
  budgetCap: { ko:"월 예산 한도", en:"Monthly budget cap", ja:"月予算の上限", zh:"月度预算上限", "zh-TW":"月度預算上限", vi:"Hạn mức ngân sách tháng", th:"เพดานงบรายเดือน", id:"Batas anggaran bulanan", de:"Monatliches Budgetlimit", fr:"Plafond de budget mensuel", es:"Límite de presupuesto mensual", pt:"Limite de orçamento mensal", ru:"Месячный лимит бюджета", ar:"سقف الميزانية الشهرية", hi:"मासिक बजट सीमा" },
  budgetCharged: { ko:"당월 청구", en:"Charged this month", ja:"当月請求", zh:"本月已扣", "zh-TW":"本月已扣", vi:"Đã tính phí tháng này", th:"เรียกเก็บเดือนนี้", id:"Ditagih bulan ini", de:"Diesen Monat belastet", fr:"Débité ce mois", es:"Cobrado este mes", pt:"Cobrado este mês", ru:"Списано в этом месяце", ar:"المحصّل هذا الشهر", hi:"इस माह चार्ज" },
  budgetRemaining: { ko:"잔여 한도", en:"Remaining", ja:"残り限度", zh:"剩余额度", "zh-TW":"剩餘額度", vi:"Còn lại", th:"คงเหลือ", id:"Sisa", de:"Verbleibend", fr:"Restant", es:"Restante", pt:"Restante", ru:"Остаток", ar:"المتبقي", hi:"शेष" },
  capHit: { ko:"월 예산 한도에 도달해 추가 집행·청구가 자동으로 중지되었습니다.", en:"Monthly budget cap reached — further execution and billing have been automatically stopped.", ja:"月予算の上限に達したため、追加の実行・請求は自動的に停止されました。", zh:"已达月度预算上限——后续投放与扣款已自动停止。", "zh-TW":"已達月度預算上限——後續投放與扣款已自動停止。", vi:"Đã đạt hạn mức ngân sách tháng — việc chạy và tính phí tiếp theo đã tự động dừng.", th:"ถึงเพดานงบรายเดือนแล้ว — การดำเนินการและเรียกเก็บเพิ่มเติมถูกหยุดอัตโนมัติ", id:"Batas anggaran bulanan tercapai — eksekusi dan penagihan berikutnya dihentikan otomatis.", de:"Monatslimit erreicht — weitere Ausführung und Abrechnung wurden automatisch gestoppt.", fr:"Plafond mensuel atteint — l'exécution et la facturation ultérieures ont été automatiquement arrêtées.", es:"Se alcanzó el límite mensual: la ejecución y facturación posteriores se detuvieron automáticamente.", pt:"Limite mensal atingido — execução e faturação seguintes foram paradas automaticamente.", ru:"Достигнут месячный лимит — дальнейшее исполнение и списания автоматически остановлены.", ar:"تم بلوغ سقف الميزانية الشهرية — تم إيقاف التنفيذ والفوترة الإضافية تلقائيًا.", hi:"मासिक बजट सीमा पूरी — आगे का निष्पादन और बिलिंग स्वतः रोक दी गई।" },
  howTitle: { ko:"어떻게 작동하나요", en:"How it works", ja:"仕組み", zh:"如何运作", "zh-TW":"如何運作", vi:"Cách hoạt động", th:"ทำงานอย่างไร", id:"Cara kerja", de:"So funktioniert es", fr:"Comment ça marche", es:"Cómo funciona", pt:"Como funciona", ru:"Как это работает", ar:"كيف يعمل", hi:"यह कैसे काम करता है" },
  how1: { ko:"카드를 안전하게 토큰화(빌링키)하여 등록합니다 — 카드번호는 저장하지 않습니다.", en:"Your card is securely tokenized (billing key) — the card number is never stored.", ja:"カードを安全にトークン化（ビリングキー）して登録します。カード番号は保存しません。", zh:"将卡片安全令牌化（计费密钥）登记——不存储卡号。", "zh-TW":"將卡片安全代碼化（計費金鑰）登記——不儲存卡號。", vi:"Thẻ được token hóa an toàn (billing key) — không bao giờ lưu số thẻ.", th:"บัตรถูกแปลงเป็นโทเค็น (billing key) อย่างปลอดภัย — ไม่เก็บเลขบัตร", id:"Kartu di-tokenisasi aman (billing key) — nomor kartu tidak pernah disimpan.", de:"Ihre Karte wird sicher tokenisiert (Billing Key) — die Kartennummer wird nie gespeichert.", fr:"Votre carte est tokenisée en toute sécurité (clé de facturation) — le numéro n'est jamais stocké.", es:"Su tarjeta se tokeniza de forma segura (clave de facturación); el número nunca se almacena.", pt:"O seu cartão é tokenizado com segurança (chave de faturação) — o número nunca é armazenado.", ru:"Карта безопасно токенизируется (billing key) — номер карты не хранится.", ar:"يتم ترميز بطاقتك بأمان (مفتاح فوترة) — لا يُخزَّن رقم البطاقة أبدًا.", hi:"आपका कार्ड सुरक्षित रूप से टोकनयुक्त (बिलिंग की) होता है — कार्ड नंबर कभी संग्रहीत नहीं होता।" },
  how2: { ko:"마케팅 자동화가 광고를 집행하면, 집행된 광고비가 이 카드로 청구됩니다.", en:"When Marketing Automation runs your ads, the executed ad spend is charged to this card.", ja:"マーケティング自動化が広告を実行すると、実行された広告費がこのカードに請求されます。", zh:"营销自动化投放广告时，已投放的广告费会从此卡扣款。", "zh-TW":"行銷自動化投放廣告時，已投放的廣告費會從此卡扣款。", vi:"Khi Tự động hóa Marketing chạy quảng cáo, chi phí quảng cáo đã chạy sẽ được tính vào thẻ này.", th:"เมื่อการตลาดอัตโนมัติรันโฆษณา ค่าโฆษณาที่ใช้จะถูกเรียกเก็บจากบัตรนี้", id:"Saat Otomasi Pemasaran menjalankan iklan, biaya iklan yang dijalankan ditagih ke kartu ini.", de:"Wenn die Marketing-Automatisierung Anzeigen schaltet, werden die Werbeausgaben dieser Karte belastet.", fr:"Lorsque l'automatisation marketing diffuse vos publicités, les dépenses engagées sont débitées sur cette carte.", es:"Cuando la Automatización de Marketing ejecuta sus anuncios, el gasto realizado se cobra a esta tarjeta.", pt:"Quando a Automação de Marketing executa os anúncios, o gasto realizado é cobrado a este cartão.", ru:"Когда автоматизация маркетинга запускает рекламу, израсходованные средства списываются с этой карты.", ar:"عندما تشغّل الأتمتة التسويقية إعلاناتك، يُحصَّل الإنفاق الإعلاني من هذه البطاقة.", hi:"जब मार्केटिंग ऑटोमेशन विज्ञापन चलाता है, खर्च हुआ विज्ञापन व्यय इस कार्ड से चार्ज होता है।" },
  how3: { ko:"당월 누적 청구는 [마케팅 자동화]에서 설정한 월 예산을 절대 넘지 않습니다.", en:"Cumulative charges this month never exceed the monthly budget set in Marketing Automation.", ja:"当月の累計請求は[マーケティング自動化]で設定した月予算を決して超えません。", zh:"本月累计扣款绝不超过在[营销自动化]中设置的月度预算。", "zh-TW":"本月累計扣款絕不超過在[行銷自動化]中設定的月度預算。", vi:"Tổng phí trong tháng không bao giờ vượt ngân sách hằng tháng đặt ở Tự động hóa Marketing.", th:"ยอดเรียกเก็บสะสมของเดือนนี้ไม่เกินงบรายเดือนที่ตั้งไว้ในการตลาดอัตโนมัติ", id:"Total tagihan bulan ini tidak akan melebihi anggaran bulanan di Otomasi Pemasaran.", de:"Die kumulierten Belastungen dieses Monats überschreiten nie das in der Marketing-Automatisierung festgelegte Budget.", fr:"Le cumul des débits du mois ne dépasse jamais le budget mensuel défini dans l'automatisation marketing.", es:"Los cargos acumulados del mes nunca superan el presupuesto mensual definido en Automatización de Marketing.", pt:"As cobranças acumuladas do mês nunca excedem o orçamento mensal definido na Automação de Marketing.", ru:"Совокупные списания за месяц никогда не превышают бюджет, заданный в автоматизации маркетинга.", ar:"لا تتجاوز المبالغ التراكمية لهذا الشهر الميزانية الشهرية المحددة في الأتمتة التسويقية أبدًا.", hi:"इस माह का संचयी शुल्क मार्केटिंग ऑटोमेशन में निर्धारित मासिक बजट से कभी अधिक नहीं होता।" },
  how4: { ko:"은행급 암호화와 테넌트 격리로 결제 정보를 안전하게 보호합니다.", en:"Bank-grade encryption and tenant isolation keep your payment data safe.", ja:"銀行級の暗号化とテナント分離で決済情報を安全に保護します。", zh:"以银行级加密与租户隔离保护您的支付信息。", "zh-TW":"以銀行級加密與租戶隔離保護您的付款資訊。", vi:"Mã hóa cấp ngân hàng và cách ly tenant bảo vệ thông tin thanh toán của bạn.", th:"การเข้ารหัสระดับธนาคารและการแยก tenant ปกป้องข้อมูลการชำระเงินของคุณ", id:"Enkripsi setara bank dan isolasi tenant menjaga keamanan data pembayaran Anda.", de:"Verschlüsselung auf Bankniveau und Mandantentrennung schützen Ihre Zahlungsdaten.", fr:"Le chiffrement de niveau bancaire et l'isolation des locataires protègent vos données de paiement.", es:"El cifrado bancario y el aislamiento de inquilinos protegen sus datos de pago.", pt:"A encriptação de nível bancário e o isolamento de inquilinos protegem os seus dados de pagamento.", ru:"Шифрование банковского уровня и изоляция арендаторов защищают платёжные данные.", ar:"يحمي التشفير بمستوى البنوك وعزل المستأجرين بيانات الدفع الخاصة بك.", hi:"बैंक-स्तरीय एन्क्रिप्शन और टेनेंट आइसोलेशन आपके भुगतान डेटा को सुरक्षित रखते हैं।" },
  regSuccess: { ko:"카드가 등록되었습니다.", en:"Card registered.", ja:"カードが登録されました。", zh:"卡片已登记。", "zh-TW":"卡片已登記。", vi:"Đã đăng ký thẻ.", th:"ลงทะเบียนบัตรแล้ว", id:"Kartu terdaftar.", de:"Karte registriert.", fr:"Carte enregistrée.", es:"Tarjeta registrada.", pt:"Cartão registado.", ru:"Карта привязана.", ar:"تم تسجيل البطاقة.", hi:"कार्ड पंजीकृत।" },
  regFail: { ko:"카드 등록에 실패했습니다.", en:"Card registration failed.", ja:"カード登録に失敗しました。", zh:"卡片登记失败。", "zh-TW":"卡片登記失敗。", vi:"Đăng ký thẻ thất bại.", th:"ลงทะเบียนบัตรไม่สำเร็จ", id:"Pendaftaran kartu gagal.", de:"Kartenregistrierung fehlgeschlagen.", fr:"Échec de l'enregistrement de la carte.", es:"Error al registrar la tarjeta.", pt:"Falha ao registar o cartão.", ru:"Не удалось привязать карту.", ar:"فشل تسجيل البطاقة.", hi:"कार्ड पंजीकरण विफल।" },
  delDone: { ko:"결제수단이 삭제되었습니다.", en:"Payment method deleted.", ja:"決済手段を削除しました。", zh:"已删除支付方式。", "zh-TW":"已刪除付款方式。", vi:"Đã xóa phương thức thanh toán.", th:"ลบวิธีชำระเงินแล้ว", id:"Metode pembayaran dihapus.", de:"Zahlungsmethode gelöscht.", fr:"Moyen de paiement supprimé.", es:"Método de pago eliminado.", pt:"Método de pagamento eliminado.", ru:"Способ оплаты удалён.", ar:"تم حذف وسيلة الدفع.", hi:"भुगतान विधि हटाई गई।" },
  defDone: { ko:"기본 결제수단으로 설정되었습니다.", en:"Set as default payment method.", ja:"既定の決済手段に設定しました。", zh:"已设为默认支付方式。", "zh-TW":"已設為預設付款方式。", vi:"Đã đặt làm phương thức mặc định.", th:"ตั้งเป็นวิธีชำระเงินเริ่มต้นแล้ว", id:"Dijadikan metode pembayaran default.", de:"Als Standard-Zahlungsmethode festgelegt.", fr:"Défini comme moyen de paiement par défaut.", es:"Establecido como método de pago predeterminado.", pt:"Definido como método de pagamento predefinido.", ru:"Установлено как основной способ оплаты.", ar:"تم التعيين كوسيلة دفع افتراضية.", hi:"डिफ़ॉल्ट भुगतान विधि के रूप में सेट।" },
  gotoMarketing: { ko:"마케팅 자동화로 이동", en:"Go to Marketing Automation", ja:"マーケティング自動化へ", zh:"前往营销自动化", "zh-TW":"前往行銷自動化", vi:"Đến Tự động hóa Marketing", th:"ไปที่การตลาดอัตโนมัติ", id:"Ke Otomasi Pemasaran", de:"Zur Marketing-Automatisierung", fr:"Aller à l'automatisation marketing", es:"Ir a Automatización de Marketing", pt:"Ir para Automação de Marketing", ru:"К автоматизации маркетинга", ar:"إلى الأتمتة التسويقية", hi:"मार्केटिंग ऑटोमेशन पर जाएं" },
  registeredAt: { ko:"등록일", en:"Registered", ja:"登録日", zh:"登记日期", "zh-TW":"登記日期", vi:"Ngày đăng ký", th:"วันที่ลงทะเบียน", id:"Terdaftar", de:"Registriert", fr:"Enregistré le", es:"Registrada", pt:"Registado", ru:"Привязана", ar:"تاريخ التسجيل", hi:"पंजीकृत" },
  processing: { ko:"처리 중...", en:"Processing...", ja:"処理中...", zh:"处理中...", "zh-TW":"處理中...", vi:"Đang xử lý...", th:"กำลังดำเนินการ...", id:"Memproses...", de:"Wird verarbeitet...", fr:"Traitement...", es:"Procesando...", pt:"A processar...", ru:"Обработка...", ar:"جارٍ المعالجة...", hi:"प्रसंस्करण..." },
  card: { ko:"카드", en:"Card", ja:"カード", zh:"卡片", "zh-TW":"卡片", vi:"Thẻ", th:"บัตร", id:"Kartu", de:"Karte", fr:"Carte", es:"Tarjeta", pt:"Cartão", ru:"Карта", ar:"بطاقة", hi:"कार्ड" },

  // ── CardRequiredBanner (유료 메뉴 공통 안내) ──
  bannerTitle: { ko:"광고비 결제카드가 등록되지 않았습니다", en:"No ad-spend payment card registered", ja:"広告費の決済カードが未登録です", zh:"尚未登记广告费支付卡", "zh-TW":"尚未登記廣告費付款卡", vi:"Chưa đăng ký thẻ thanh toán chi phí quảng cáo", th:"ยังไม่ได้ลงทะเบียนบัตรชำระค่าโฆษณา", id:"Kartu pembayaran biaya iklan belum terdaftar", de:"Keine Zahlungskarte für Werbeausgaben registriert", fr:"Aucune carte de paiement des dépenses publicitaires enregistrée", es:"No hay tarjeta de pago de gasto publicitario registrada", pt:"Nenhum cartão de pagamento de anúncios registado", ru:"Карта для оплаты рекламы не привязана", ar:"لم تُسجَّل بطاقة دفع نفقات الإعلان", hi:"विज्ञापन व्यय भुगतान कार्ड पंजीकृत नहीं" },
  bannerDesc: { ko:"광고를 실제로 집행하려면 결제카드 등록이 필요합니다. 등록한 카드는 설정한 월 예산 한도 내에서만 청구됩니다.", en:"A payment card is required to actually run ads. It is only charged within your monthly budget cap.", ja:"広告を実際に実行するには決済カードの登録が必要です。登録したカードは設定した月予算の上限内でのみ請求されます。", zh:"实际投放广告需登记支付卡。仅在设定的月度预算上限内扣款。", "zh-TW":"實際投放廣告需登記付款卡。僅在設定的月度預算上限內扣款。", vi:"Cần đăng ký thẻ thanh toán để thực sự chạy quảng cáo. Chỉ bị tính phí trong hạn mức ngân sách tháng.", th:"ต้องลงทะเบียนบัตรเพื่อรันโฆษณาจริง จะถูกเรียกเก็บภายในเพดานงบรายเดือนเท่านั้น", id:"Kartu pembayaran diperlukan untuk benar-benar menjalankan iklan. Hanya ditagih dalam batas anggaran bulanan.", de:"Zum tatsächlichen Schalten von Anzeigen ist eine Zahlungskarte erforderlich. Belastung nur innerhalb Ihres Monatsbudgets.", fr:"Une carte de paiement est requise pour diffuser réellement des publicités. Débit uniquement dans la limite du budget mensuel.", es:"Se requiere una tarjeta para ejecutar anuncios realmente. Solo se cobra dentro de su límite mensual.", pt:"É necessário um cartão para executar anúncios de facto. Só é cobrado dentro do limite mensal.", ru:"Для реального запуска рекламы нужна платёжная карта. Списания только в пределах месячного лимита.", ar:"يلزم وجود بطاقة دفع لتشغيل الإعلانات فعليًا. لا يتم الخصم إلا ضمن سقف ميزانيتك الشهرية.", hi:"विज्ञापन वास्तव में चलाने के लिए भुगतान कार्ड आवश्यक है। यह केवल मासिक बजट सीमा के भीतर चार्ज होता है।" },
  bannerBtn: { ko:"결제카드 등록하기", en:"Register payment card", ja:"決済カードを登録", zh:"登记支付卡", "zh-TW":"登記付款卡", vi:"Đăng ký thẻ thanh toán", th:"ลงทะเบียนบัตรชำระเงิน", id:"Daftarkan kartu pembayaran", de:"Zahlungskarte registrieren", fr:"Enregistrer une carte", es:"Registrar tarjeta de pago", pt:"Registar cartão de pagamento", ru:"Привязать карту", ar:"تسجيل بطاقة الدفع", hi:"भुगतान कार्ड पंजीकृत करें" },
  bannerOk: { ko:"광고비 결제카드 등록 완료 — 월 예산 한도 내 자동 집행 준비됨", en:"Ad-spend card registered — ready for automatic execution within your monthly cap", ja:"広告費カード登録済み — 月予算の上限内で自動実行の準備完了", zh:"广告费支付卡已登记——已可在月度预算上限内自动投放", "zh-TW":"廣告費付款卡已登記——已可在月度預算上限內自動投放", vi:"Đã đăng ký thẻ chi phí quảng cáo — sẵn sàng chạy tự động trong hạn mức tháng", th:"ลงทะเบียนบัตรค่าโฆษณาแล้ว — พร้อมรันอัตโนมัติภายในเพดานงบรายเดือน", id:"Kartu biaya iklan terdaftar — siap dijalankan otomatis dalam batas bulanan", de:"Werbekosten-Karte registriert — bereit zur automatischen Ausführung innerhalb des Monatslimits", fr:"Carte des dépenses publicitaires enregistrée — prête pour l'exécution automatique dans la limite mensuelle", es:"Tarjeta de gasto publicitario registrada: lista para ejecución automática dentro del límite mensual", pt:"Cartão de gastos com anúncios registado — pronto para execução automática dentro do limite mensal", ru:"Карта для рекламы привязана — готово к автоматическому запуску в пределах месячного лимита", ar:"تم تسجيل بطاقة نفقات الإعلان — جاهزة للتنفيذ التلقائي ضمن الحد الشهري", hi:"विज्ञापन व्यय कार्ड पंजीकृत — मासिक सीमा के भीतर स्वतः निष्पादन के लिए तैयार" },

  // ── 신규 회원 20일 무료 체험 안내(가입) ──
  trialTitle: { ko:"20일 무료 체험", en:"20-Day Free Trial", ja:"20日間無料体験", zh:"20天免费试用", "zh-TW":"20天免費試用", vi:"Dùng thử miễn phí 20 ngày", th:"ทดลองใช้ฟรี 20 วัน", id:"Uji Coba Gratis 20 Hari", de:"20 Tage kostenlos testen", fr:"Essai gratuit de 20 jours", es:"Prueba gratis de 20 días", pt:"Teste grátis de 20 dias", ru:"20 дней бесплатно", ar:"تجربة مجانية 20 يومًا", hi:"20-दिन नि:शुल्क परीक्षण" },
  trialDesc: { ko:"가입 즉시 선택한 플랜의 모든 기능을 20일간 무료로 체험하세요. 마음에 들면 그때 결제하고 계속 이용하면 됩니다 — 20일간은 무조건 무료이며, 지금 결제 정보를 입력할 필요가 없습니다.", en:"Use every feature of your selected plan free for 20 days, starting now. If you love it, pay then to keep going — the 20 days are unconditionally free and no payment details are required up front.", ja:"登録後すぐ、選択したプランの全機能を20日間無料で体験できます。気に入ったら、その時に決済して継続利用。20日間は無条件で無料で、今すぐ決済情報を入力する必要はありません。", zh:"注册后立即免费体验所选方案的全部功能，为期20天。满意后再付款继续使用——20天无条件免费，且无需预先填写支付信息。", "zh-TW":"註冊後立即免費體驗所選方案的全部功能，為期20天。滿意後再付款繼續使用——20天無條件免費，且無需預先填寫付款資訊。", vi:"Dùng miễn phí mọi tính năng của gói đã chọn trong 20 ngày kể từ bây giờ. Nếu thích, hãy thanh toán để tiếp tục — 20 ngày miễn phí vô điều kiện và không cần nhập thông tin thanh toán trước.", th:"ใช้ทุกฟีเจอร์ของแพ็กเกจที่เลือกฟรี 20 วันตั้งแต่ตอนนี้ ถ้าชอบค่อยชำระเงินเพื่อใช้ต่อ — 20 วันฟรีแบบไม่มีเงื่อนไข และไม่ต้องกรอกข้อมูลการชำระเงินล่วงหน้า", id:"Gunakan semua fitur paket pilihan Anda gratis selama 20 hari mulai sekarang. Jika suka, bayar nanti untuk lanjut — 20 hari gratis tanpa syarat dan tanpa perlu memasukkan info pembayaran di awal.", de:"Nutzen Sie ab sofort alle Funktionen Ihres gewählten Plans 20 Tage kostenlos. Gefällt es Ihnen, zahlen Sie danach zum Weitermachen — die 20 Tage sind bedingungslos gratis, ohne vorherige Zahlungsdaten.", fr:"Profitez gratuitement de toutes les fonctionnalités de votre forfait pendant 20 jours, dès maintenant. Si cela vous plaît, payez ensuite pour continuer — les 20 jours sont gratuits sans condition et aucune information de paiement n'est requise au départ.", es:"Use todas las funciones de su plan gratis durante 20 días, desde ahora. Si le gusta, pague después para continuar: los 20 días son gratis sin condiciones y no se requieren datos de pago por adelantado.", pt:"Use todas as funcionalidades do seu plano grátis durante 20 dias, já. Se gostar, pague depois para continuar — os 20 dias são gratuitos sem condições e não exigem dados de pagamento à partida.", ru:"Пользуйтесь всеми функциями выбранного тарифа бесплатно 20 дней — прямо сейчас. Понравится — оплатите позже, чтобы продолжить. 20 дней бесплатны безусловно, платёжные данные заранее не нужны.", ar:"استخدم كل ميزات الباقة المختارة مجانًا لمدة 20 يومًا بدءًا من الآن. إن أعجبتك، ادفع بعدها للمتابعة — الـ20 يومًا مجانية دون شروط ولا حاجة لإدخال بيانات الدفع مسبقًا.", hi:"अभी से 20 दिनों तक अपने चुने हुए प्लान की सभी सुविधाएं नि:शुल्क उपयोग करें। पसंद आए तो जारी रखने के लिए तब भुगतान करें — 20 दिन बिना शर्त नि:शुल्क हैं और पहले से भुगतान विवरण की आवश्यकता नहीं।" },
  trialBadge: { ko:"20일간 무료 · 지금 결제 불필요", en:"20 days free · no payment now", ja:"20日間無料・今すぐ決済不要", zh:"20天免费 · 现在无需付款", "zh-TW":"20天免費 · 現在無需付款", vi:"Miễn phí 20 ngày · chưa cần thanh toán", th:"ฟรี 20 วัน · ยังไม่ต้องชำระเงิน", id:"Gratis 20 hari · belum perlu bayar", de:"20 Tage gratis · keine Zahlung jetzt", fr:"20 jours gratuits · sans paiement maintenant", es:"20 días gratis · sin pago ahora", pt:"20 dias grátis · sem pagamento agora", ru:"20 дней бесплатно · без оплаты сейчас", ar:"20 يومًا مجانًا · لا دفع الآن", hi:"20 दिन नि:शुल्क · अभी भुगतान नहीं" },
};

export function bt(key, lang) {
  const row = DICT[key];
  if (!row) return key;
  return row[lang] || row.en || key;
}

export default DICT;
