/**
 * sidebarMenuLabels — 172차 PHASE 2-D 분리.
 *
 * menuKey → 한글 라벨/설명 매핑 + 페이지별 서브탭 정의.
 * PlanPricing (메뉴 접근 권한) + AdminMenuManager (메뉴 가시성) 양쪽에서 SSOT 로 사용.
 */

/** menuKey → { title, desc } 한글 매핑 (대메뉴 + 중메뉴) */
export const MENU_KEY_LABEL = {
  // 홈
  'home||dashboard':              { title: '홈 - 대시보드',        desc: 'KPI 요약 + 채널별 실시간 매출/광고비/ROAS' },
  'home||rollup':                 { title: '홈 - 롤업 뷰',          desc: '판매·광고·재고 통합 실시간 모니터링' },
  // 통합 그룹 (다수 페이지 함께 제어)
  'marketing':                    { title: '마케팅 / 광고 / CRM 통합', desc: '자동마케팅·캠페인·여정·광고분석·CRM·카카오·이메일·SMS·인플루언서·UGC 등 17개 페이지 함께 제어' },
  'ops':                          { title: '커머스 / 물류 통합',     desc: '옴니채널·카탈로그·주문허브·WMS·가격최적화·공급망·반품 등 7개 페이지 함께 제어' },
  'billing':                      { title: '재무 / 결산 통합',       desc: '정산·대사·요금제·감사로그 등 4개 페이지 함께 제어' },
  // 인사이트
  'analytics||performance_hub':   { title: '인사이트 - 성과 허브',   desc: '광고 성과 8차원 분석 + 채널/캠페인 비교' },
  'analytics||report_builder':    { title: '인사이트 - 리포트 빌더', desc: '커스텀 리포트 + 자동 발송 스케줄' },
  'analytics||pnl_analytics':     { title: '인사이트 - 통합 손익(P&L)', desc: 'SKU·채널·캠페인·크리에이터별 실시간 손익 + 이상 감지' },
  'analytics||ai_insights':       { title: '인사이트 - AI 인사이트', desc: 'GPT 기반 자동 인사이트 + 액션 추천' },
  'analytics||data_product':      { title: '인사이트 - 데이터 프로덕트', desc: '데이터 마트 + 쿼리 워크스페이스' },
  // 자동화
  'automation||ai_rule_engine':   { title: '자동화 - AI 룰 엔진',    desc: '임계값 기반 자동 액션 + GPT 제안' },
  'automation||approvals':        { title: '자동화 - 승인 큐',       desc: 'AI 제안 검토 + 원클릭 승인/반려' },
  'automation||writeback':        { title: '자동화 - 채널 라이트백', desc: '룰 결과를 광고 플랫폼에 자동 반영' },
  'automation||onboarding':       { title: '자동화 - 온보딩',        desc: '신규 고객 가이드 + 초기 설정 자동화' },
  // 데이터
  'data||integration_hub':        { title: '데이터 - 연동 허브',     desc: 'OAuth 커넥터 + 30+ 채널 API 관리' },
  'data||data_schema':            { title: '데이터 - 데이터 스키마', desc: '표준 이벤트 매핑 + 스키마 거버넌스' },
  'data||data_trust':             { title: '데이터 - 데이터 신뢰',   desc: '품질 검증 + 변화 감지 + 리니지' },
  // 운영 & 지원
  'system||workspace':            { title: '시스템 - 워크스페이스',  desc: '팀 멤버 / 권한 / 알림 설정' },
  'system||operations':           { title: '시스템 - 오퍼레이션',    desc: '백그라운드 작업 / 실패 큐 모니터링' },
  'system||case_study':           { title: '시스템 - 케이스 스터디', desc: '벤치마크 + 베스트 프랙티스 라이브러리' },
  'system||help_center':          { title: '시스템 - 도움말 센터',   desc: 'FAQ + 가이드 + 영상 튜토리얼' },
  'system||feedback':             { title: '시스템 - 피드백',        desc: '버그 신고 + 기능 제안' },
  'system||developer_hub':        { title: '시스템 - 개발자 허브',   desc: 'API 키 + 웹훅 + Webhook 로그' },
  // 관리자 전용
  'system||admin':                { title: '관리자 - 플랫폼 환경',   desc: '운영 환경 / 시스템 설정 (admin 전용)' },
  'system||plan_pricing':         { title: '관리자 - 플랜·요금',     desc: '구독 플랜 / 기간별 가격 / 메뉴 권한 관리' },
  'system||menu_tree':            { title: '관리자 - 메뉴 트리',     desc: 'sidebar 메뉴 정의 / 가시성 / 권한 매핑' },
  'system||db_admin':             { title: '관리자 - DB 스키마',     desc: '테이블 / 마이그레이션 / 통계' },
  'system||pg_config':            { title: '관리자 - 결제 PG',       desc: 'Paddle 환경설정 / 구독 통계' },
};

/** 페이지별 서브탭 정의 (route → [{ id, label }]). [현 차수] 사이드바 전 페이지 전수 매핑 —
 *  각 페이지 실제 탭 배열에서 id/label 추출(런타임 게이팅 키 route::tabId 정합). 메뉴접근 매트릭스에서
 *  모든 서브탭을 플랜별 선택 가능. (탭 없는 단일화면 페이지: /pm·/ad-channels·/settlements·/app-pricing·/audit·/team-members) */
export const SUB_TABS_BY_PATH = {
  // ── admin ──
  '/admin/plan-pricing': [
    { id: 'plan',        label: '플랜 & 요금' },
    { id: 'permissions', label: '메뉴 접근 권한' },
    { id: 'coupons',     label: '쿠폰 관리' },
  ],
  '/db-admin': [
    { id: 'overview', label: '데이터베이스 현황' },
    { id: 'tables',   label: '테이블 관리' },
    { id: 'query',    label: '쿼리 실행기' },
    { id: 'backup',   label: '백업/복구' },
  ],
  '/admin': [
    { id: 'environment', label: '환경 설정' },
    { id: 'accounts',    label: '계정 관리' },
    { id: 'audit',       label: '감사 로그' },
    { id: 'maintenance', label: '유지보수' },
  ],
  // ── home ──
  '/dashboard': [
    { id: 'overview',   label: '종합 현황' },
    { id: 'marketing',  label: '마케팅 성과' },
    { id: 'channel',    label: '채널 KPI' },
    { id: 'commerce',   label: '커머스' },
    { id: 'sales',      label: '글로벌 매출' },
    { id: 'influencer', label: '인플루언서' },
    { id: 'system',     label: '시스템' },
    { id: 'guide',      label: '이용 가이드' },
  ],
  '/rollup': [
    { id: 'summary',  label: '요약' },
    { id: 'sku',      label: 'SKU' },
    { id: 'campaign', label: '캠페인' },
    { id: 'creator',  label: '크리에이터' },
    { id: 'platform', label: '플랫폼' },
    { id: 'guide',    label: '이용 가이드' },
  ],
  // ── ai_marketing ──
  '/auto-marketing': [
    { id: 'creative', label: '크리에이티브 스튜디오' },
    { id: 'setup',    label: '캠페인 설정' },
    { id: 'preview',  label: 'AI 전략 미리보기' },
    { id: 'guide',    label: '이용 가이드' },
  ],
  '/campaign-manager': [
    { id: 'overview',  label: '종합 현황' },
    { id: 'list',      label: '캠페인 목록' },
    { id: 'analytics', label: '분석' },
    { id: 'abtest',    label: 'A/B 테스트' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  '/journey-builder': [
    { id: 'builder',   label: '여정 빌더' },
    { id: 'list',      label: '여정 목록' },
    { id: 'logs',      label: '실행 로그' },
    { id: 'analytics', label: '분석' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  // ── ad_analytics ──
  '/marketing': [
    { id: 'overview',  label: '종합 현황' },
    { id: 'ad_status', label: '광고 현황' },
    { id: 'creative',  label: '크리에이티브' },
    { id: 'compare',   label: '비교 분석' },
    { id: 'ai_design', label: 'AI 디자인' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  '/budget-tracker': [
    { id: 'overview',   label: '종합 현황' },
    { id: 'allocation', label: '예산 배분' },
    { id: 'burnrate',   label: '소진율' },
    { id: 'alerts',     label: '알림' },
    { id: 'guide',      label: '이용 가이드' },
  ],
  '/account-performance': [
    { id: 'dashboard', label: '시각화 대시보드' },
    { id: 'drilldown', label: '트리구조 계층 분석' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  '/attribution': [
    { id: 'mta',      label: '멀티터치 MTA' },
    { id: 'shapley',  label: '정밀 Shapley' },
    { id: 'mmm',      label: '베이지안 MMM' },
    { id: 'markov',   label: '마르코프+업리프트' },
    { id: 'bayesian', label: '베이지안 A/B' },
    { id: 'cohort',   label: '코호트 분석' },
    { id: 'ltvcac',   label: 'LTV vs CAC' },
    { id: 'anomaly',  label: '이상감지' },
    { id: 'compare',  label: '모델 비교' },
    { id: 'guide',    label: '이용 가이드' },
  ],
  '/channel-kpi': [
    { id: 'goal',      label: '목표 및 역할' },
    { id: 'role',      label: '역할 할당' },
    { id: 'kpi',       label: '목표 설정' },
    { id: 'sns',       label: 'SNS 성과' },
    { id: 'content',   label: '콘텐츠 성과' },
    { id: 'community', label: '커뮤니티' },
    { id: 'target',    label: '목표 달성률' },
    { id: 'monitor',   label: '성과 모니터링' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  '/graph-score': [
    { id: 'summary',    label: '요약 스코어' },
    { id: 'browser',    label: '그래프 브라우저' },
    { id: 'influencer', label: '인플루언서 스코어' },
    { id: 'sku',        label: 'SKU 스코어' },
    { id: 'creative',   label: '크리에이티브 스코어' },
    { id: 'guide',      label: '이용 가이드' },
  ],
  // ── crm ──
  '/crm': [
    { id: 'customers',   label: '고객 목록' },
    { id: 'ai_segments', label: 'AI 세그먼트' },
    { id: 'segments',    label: '수동 세그먼트' },
    { id: 'rfm',         label: 'RFM 분석' },
    { id: 'guide',       label: '이용 가이드' },
  ],
  '/kakao-channel': [
    { id: 'campaigns', label: '캠페인' },
    { id: 'templates', label: '알림톡 템플릿' },
    { id: 'creative',  label: '크리에이티브' },
    { id: 'settings',  label: '채널 설정' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  '/email-marketing': [
    { id: 'campaigns', label: '캠페인' },
    { id: 'templates', label: '템플릿' },
    { id: 'analytics', label: '분석' },
    { id: 'creative',  label: '크리에이티브' },
    { id: 'settings',  label: '설정' },
    { id: 'guide',     label: '가이드' },
  ],
  '/sms-marketing': [
    { id: 'compose',   label: 'SMS 작성' },
    { id: 'broadcast', label: '일괄 발송' },
    { id: 'templates', label: '템플릿 관리' },
    { id: 'campaigns', label: '캠페인' },
    { id: 'history',   label: '발송 이력' },
    { id: 'stats',     label: '통계' },
    { id: 'creative',  label: '크리에이티브' },
    { id: 'settings',  label: '인증 설정' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  '/influencer': [
    { id: 'identity', label: '크리에이터 통합' },
    { id: 'contract', label: '계약 & 화이트리스트' },
    { id: 'settle',   label: '정산 & 검증' },
    { id: 'roi',      label: 'ROI 랭킹' },
    { id: 'ugc',      label: 'UGC 리뷰' },
    { id: 'ai_eval',  label: 'AI 평가 분석' },
    { id: 'guide',    label: '이용 가이드' },
  ],
  '/content-calendar': [
    { id: 'calendar', label: '캘린더' },
    { id: 'list',     label: '리스트' },
    { id: 'ai',       label: 'AI 분석' },
    { id: 'guide',    label: '이용 가이드' },
  ],
  '/reviews-ugc': [
    { id: 'dashboard', label: '대시보드' },
    { id: 'feed',      label: '리뷰 관리' },
    { id: 'trend',     label: '트렌드' },
    { id: 'settings',  label: '설정' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  '/web-popup': [
    { id: 'tabOverview', label: '성과 분석' },
    { id: 'tabManage',   label: '팝업 관리' },
    { id: 'tabLive',     label: '라이브 미리보기' },
    { id: 'tabAB',       label: 'A/B 테스트' },
    { id: 'tabSettings', label: '설정' },
    { id: 'tabGuide',    label: '이용 가이드' },
  ],
  // ── commerce ──
  '/omni-channel': [
    { id: 'channels',  label: '채널 연동' },
    { id: 'products',  label: '상품 관리' },
    { id: 'orders',    label: '주문 관리' },
    { id: 'inventory', label: '재고 현황' },
    { id: 'overview',  label: '통합 현황' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  '/catalog-sync': [
    { id: 'catalog',   label: '카탈로그' },
    { id: 'sync',      label: '동기화 실행' },
    { id: 'catmap',    label: '카테고리 매핑' },
    { id: 'price',     label: '가격 규칙' },
    { id: 'inventory', label: '재고 정책' },
    { id: 'history',   label: '이력' },
    { id: 'guide',     label: '이용 가이드' },
  ],
  '/live-commerce': [
    { id: 'studio',       label: '방송 스튜디오' },
    { id: 'dashboard',    label: '실시간 대시보드' },
    { id: 'lineup',       label: '상품 편성' },
    { id: 'sessions',     label: '방송 관리' },
    { id: 'integrations', label: '연동 현황' },
    { id: 'aihost',       label: 'AI 쇼호스트' },
    { id: 'buyer',        label: '구매하기(시청자)' },
    { id: 'guide',        label: '이용 가이드' },
  ],
  '/order-hub': [
    { id: 'overview',   label: '개요' },
    { id: 'orders',     label: '주문 관리' },
    { id: 'claims',     label: '클레임/반품' },
    { id: 'delivery',   label: '배송 추적' },
    { id: 'settlement', label: '정산' },
    { id: 'intl',       label: '국제 주문' },
    { id: 'b2b',        label: 'B2B 도매' },
    { id: 'settings',   label: '수집 설정' },
    { id: 'routing',    label: '자동 라우팅' },
    { id: 'guide',      label: '이용 가이드' },
  ],
  '/wms-manager': [
    { id: 'warehouse',     label: 'WMS 창고' },
    { id: 'inout',         label: '입출고' },
    { id: 'inventory',     label: '재고현황' },
    { id: 'receiving',     label: '입고검수' },
    { id: 'picking',       label: '피킹/패킹' },
    { id: 'lot',           label: '로트/유통기한' },
    { id: 'replenishment', label: '자동발주' },
    { id: 'combine',       label: '합포장' },
    { id: 'carrier',       label: '운송사' },
    { id: 'tracking',      label: '배송추적' },
    { id: 'invoice',       label: '인보이스' },
    { id: 'bundle',        label: '번들/BOM' },
    { id: 'supplier',      label: '거래처' },
    { id: 'audit',         label: '재고실사' },
    { id: 'guide',         label: '이용 가이드' },
  ],
  '/price-opt': [
    { id: 'summary',    label: '요약 대시보드' },
    { id: 'products',   label: '상품 관리' },
    { id: 'optimize',   label: '최적가 산정' },
    { id: 'scenario',   label: '시나리오 시뮬레이션' },
    { id: 'mix',        label: '채널 믹스' },
    { id: 'repricer',   label: '다이나믹 리프라이서' },
    { id: 'competitor', label: '경쟁가 모니터링' },
    { id: 'calendar',   label: '프로모션 캘린더' },
    { id: 'channelFee', label: '채널 수수료' },
    { id: 'guide',      label: '가이드' },
  ],
  '/supply-chain': [
    { id: 'timeline',   label: '공급 타임라인' },
    { id: 'suppliers',  label: '공급사 관리' },
    { id: 'inventory',  label: '재고 가시성' },
    { id: 'po',         label: '발주 관리' },
    { id: 'leadtime',   label: '리드타임 분석' },
    { id: 'risk',       label: '위험 감지' },
    { id: 'landedcost', label: '원가 분석' },
    { id: 'guide',      label: '이용 가이드' },
  ],
  '/returns-portal': [
    { id: 'tabOverview',   label: '개요' },
    { id: 'tabRequests',   label: '반품 요청' },
    { id: 'tabInspection', label: '검수' },
    { id: 'tabRefunds',    label: '환불' },
    { id: 'tabRestock',    label: '재입고' },
    { id: 'tabAnalytics',  label: '분석' },
    { id: 'tabPolicies',   label: '정책' },
    { id: 'tabGuide',      label: '가이드' },
  ],
  // ── analytics ──
  '/performance': [
    { id: 'performance', label: '성과' },
    { id: 'settlement',  label: '정산' },
    { id: 'creator',     label: '크리에이터' },
    { id: 'sku_profit',  label: 'SKU 손익' },
    { id: 'cohort',      label: '코호트' },
    { id: 'esg',         label: 'ESG' },
    { id: 'guide',       label: '이용 가이드' },
  ],
  '/pnl': [
    { id: 'overview', label: '손익 개요' },
    { id: 'pnl',      label: '단위 손익' },
    { id: 'anomaly',  label: '이상 탐지' },
    { id: 'action',   label: '실행 계획' },
    { id: 'forecast', label: '손익 예측' },
    { id: 'guide',    label: '이용 가이드' },
  ],
  '/ai-insights': [
    { id: 'trends',  label: '예측' },
    { id: 'cards',   label: '운영 가드레일' },
    { id: 'chat',    label: 'AI 에이전트' },
    { id: 'history', label: '감사 이력' },
    { id: 'guide',   label: '이용 가이드' },
  ],
  '/data-product': [
    { id: 'overview', label: '개요 & 파이프라인' },
    { id: 'schema',   label: '표준 Event Schema' },
    { id: 'platform', label: '플랫폼 매핑' },
    { id: 'metrics',  label: 'Metric 카탈로그' },
    { id: 'rules',    label: '알림 / 추천 규칙' },
    { id: 'guide',    label: '이용 가이드' },
  ],
  // ── automation ──
  '/ai-rule-engine': [
    { id: 'rules',    label: '규칙' },
    { id: 'create',   label: '규칙 생성' },
    { id: 'execlog',  label: '실행 로그' },
    { id: 'learning', label: '학습 상태' },
  ],
  '/approvals': [
    { id: 'queue',    label: '승인 대기열' },
    { id: 'audit',    label: '감사 이력' },
    { id: 'settings', label: '설정' },
    { id: 'guide',    label: '가이드' },
  ],
  '/writeback': [
    { id: 'console',  label: '콘솔' },
    { id: 'jobs',     label: '작업 이력' },
    { id: 'settings', label: '설정' },
    { id: 'guide',    label: '가이드' },
  ],
  '/onboarding': [
    { id: 'steps', label: '진행 단계' },
    { id: 'roles', label: '역할별 경로' },
    { id: 'help',  label: '도움말' },
  ],
  // ── data ──
  '/integration-hub': [
    { id: 'overview', label: '개요' },
    { id: 'active',   label: '활성 키' },
    { id: 'history',  label: '테스트 이력' },
    { id: 'settings', label: '설정' },
    { id: 'guide',    label: '이용 가이드' },
  ],
  '/data-schema': [
    { id: 'schema',   label: '이벤트 스키마' },
    { id: 'pipeline', label: '수집→정규화 파이프라인' },
    { id: 'metrics',  label: '메트릭 카탈로그' },
    { id: 'alerts',   label: '추천/알림 규칙' },
    { id: 'guide',    label: '가이드' },
  ],
  '/data-trust': [
    { id: 'score',      label: '신뢰도 개요' },
    { id: 'lineage',    label: '데이터 계보' },
    { id: 'rules',      label: '품질 규칙' },
    { id: 'compliance', label: '컴플라이언스' },
  ],
  '/pixel-tracking': [
    { id: 'dashboard', label: '대시보드' },
    { id: 'pixels',    label: '픽셀 설정' },
    { id: 'events',    label: '이벤트 스트림' },
  ],
  // ── finance ──
  '/reconciliation': [
    { id: 'upload',  label: '데이터 업로드' },
    { id: 'recon',   label: '대사 실행' },
    { id: 'reports', label: '리포트' },
    { id: 'tickets', label: '티켓 대응' },
    { id: 'guide',   label: '이용 가이드' },
  ],
  // ── member_tools ──
  '/workspace': [
    { id: 'activity', label: '활동 피드' },
    { id: 'members',  label: '구성원' },
    { id: 'tasks',    label: '태스크' },
  ],
  '/operations': [
    { id: 'promotions', label: '쿠폰/프로모션' },
    { id: 'creative',   label: '크리에이티브' },
  ],
  '/case-study': [
    { id: 'all',      label: '전체 사례' },
    { id: 'industry', label: '업종별' },
    { id: 'roi',      label: 'ROI순' },
    { id: 'bookmark', label: '북마크' },
  ],
  '/help': [
    { id: 'menus',   label: '메뉴별 설명' },
    { id: 'faq',     label: 'Q&A' },
    { id: 'apikeys', label: '인증키 등록 가이드' },
    { id: 'roles',   label: '권한별 업무 안내' },
  ],
  '/feedback': [
    { id: 'dashboard', label: '대시보드' },
    { id: 'recent',    label: '최근 피드백' },
    { id: 'sentiment', label: '감성 분석' },
    { id: 'actions',   label: '액션' },
  ],
  '/developer-hub': [
    { id: 'apikeys', label: 'API 키' },
    { id: 'ref',     label: 'API 레퍼런스' },
    { id: 'sdk',     label: 'SDK' },
    { id: 'webhook', label: '웹훅' },
    { id: 'sandbox', label: '샌드박스' },
  ],
};
