#!/usr/bin/env node
/** 254차 i18n — AutoMarketing "채널 효과 분석" 탭(marketing.eff*) 21키 15개국 주입.
 *  acorn splice, 멱등(기존키 skip), 최상위 marketing ns '마지막 occurrence'(shadowing)에 주입, 재파싱 검증. */
const fs = require('fs');
const path = require('path');
const { parse } = require('acorn');
const LOCDIR = path.join(__dirname, '..', 'frontend', 'src', 'i18n', 'locales');

const EFF = {
  ko: { autoTabEff:'④ 채널 효과 분석', effScaleUp:'예산 증액', effMaintain:'유지', effOptimize:'최적화 필요', effCut:'회수·정지', effCollecting:'데이터 수집', effTitle:'채널 효과 전수 분석', effSubtitle:'실측 전수 데이터(진실 ROAS·CAC·전환·추세)를 종합한 효과점수입니다. 최고=예산 증액 후보, 최저=회수·정지 후보. 자가학습 prior 반영.', effRefresh:'새로고침', effLoading:'분석 중…', effEmpty:'아직 집행/성과 데이터가 없습니다. 캠페인 집행 후 채널별 효과가 분석됩니다.', effBest:'최고 효과 채널', effScore:'효과점수', effWorst:'최저 효과 채널', effColChannel:'채널', effColScore:'효과점수', effColConv:'전환', effColSpend:'지출', effColVerdict:'액션', effLearned:'자가학습 반영', effTruth:'진실 ROAS 보정' },
  en: {"autoTabEff":"④ Channel Effectiveness","effScaleUp":"Scale Up","effMaintain":"Maintain","effOptimize":"Needs Optimization","effCut":"Cut / Pause","effCollecting":"Collecting Data","effTitle":"Full Channel Effectiveness Analysis","effSubtitle":"An effectiveness score combining full measured data (true ROAS, CAC, conversions, trend). Highest = budget scale-up candidate, lowest = cut/pause candidate. Reflects self-learning prior.","effRefresh":"Refresh","effLoading":"Analyzing…","effEmpty":"No execution/performance data yet. Channel effectiveness will be analyzed after campaigns run.","effBest":"Top-Performing Channel","effScore":"Effectiveness Score","effWorst":"Lowest-Performing Channel","effColChannel":"Channel","effColScore":"Score","effColConv":"Conversions","effColSpend":"Spend","effColVerdict":"Action","effLearned":"Self-Learning Applied","effTruth":"True-ROAS Adjusted"},
  ja: {"autoTabEff":"④ チャネル効果分析","effScaleUp":"予算増額","effMaintain":"維持","effOptimize":"最適化が必要","effCut":"回収・停止","effCollecting":"データ収集中","effTitle":"チャネル効果の全数分析","effSubtitle":"実測の全数データ(真のROAS・CAC・コンバージョン・トレンド)を総合した効果スコアです。最高=予算増額候補、最低=回収・停止候補。自己学習priorを反映。","effRefresh":"更新","effLoading":"分析中…","effEmpty":"まだ配信・成果データがありません。キャンペーン配信後にチャネル別の効果が分析されます。","effBest":"最高効果チャネル","effScore":"効果スコア","effWorst":"最低効果チャネル","effColChannel":"チャネル","effColScore":"スコア","effColConv":"コンバージョン","effColSpend":"支出","effColVerdict":"アクション","effLearned":"自己学習を反映","effTruth":"真のROAS補正"},
  zh: {"autoTabEff":"④ 渠道效果分析","effScaleUp":"增加预算","effMaintain":"维持","effOptimize":"需优化","effCut":"收回·停止","effCollecting":"数据采集中","effTitle":"渠道效果全量分析","effSubtitle":"综合实测全量数据(真实ROAS·CAC·转化·趋势)得出的效果评分。最高=增加预算候选,最低=收回·停止候选。已纳入自学习先验。","effRefresh":"刷新","effLoading":"分析中…","effEmpty":"暂无投放/成效数据。投放活动后将分析各渠道效果。","effBest":"最佳效果渠道","effScore":"效果评分","effWorst":"最差效果渠道","effColChannel":"渠道","effColScore":"评分","effColConv":"转化","effColSpend":"支出","effColVerdict":"操作","effLearned":"已纳入自学习","effTruth":"真实ROAS校正"},
  'zh-TW': {"autoTabEff":"④ 渠道效果分析","effScaleUp":"增加預算","effMaintain":"維持","effOptimize":"需優化","effCut":"回收·停止","effCollecting":"資料蒐集中","effTitle":"渠道效果全量分析","effSubtitle":"綜合實測全量資料(真實ROAS·CAC·轉換·趨勢)得出的效果評分。最高=增加預算候選,最低=回收·停止候選。已納入自學習先驗。","effRefresh":"重新整理","effLoading":"分析中…","effEmpty":"尚無投放/成效資料。投放活動後將分析各渠道效果。","effBest":"最佳效果渠道","effScore":"效果評分","effWorst":"最差效果渠道","effColChannel":"渠道","effColScore":"評分","effColConv":"轉換","effColSpend":"支出","effColVerdict":"動作","effLearned":"已納入自學習","effTruth":"真實ROAS校正"},
  de: {"autoTabEff":"④ Kanal-Effektivität","effScaleUp":"Budget erhöhen","effMaintain":"Beibehalten","effOptimize":"Optimierung nötig","effCut":"Kürzen / Stoppen","effCollecting":"Daten sammeln","effTitle":"Vollständige Kanal-Effektivitätsanalyse","effSubtitle":"Ein Effektivitäts-Score, der vollständige Messdaten (echter ROAS, CAC, Conversions, Trend) zusammenfasst. Höchster = Kandidat für Budgeterhöhung, niedrigster = Kandidat zum Kürzen/Stoppen. Berücksichtigt selbstlernenden Prior.","effRefresh":"Aktualisieren","effLoading":"Analysiere…","effEmpty":"Noch keine Auslieferungs-/Leistungsdaten. Die Kanal-Effektivität wird nach dem Kampagnenstart analysiert.","effBest":"Bester Kanal","effScore":"Effektivitäts-Score","effWorst":"Schwächster Kanal","effColChannel":"Kanal","effColScore":"Score","effColConv":"Conversions","effColSpend":"Ausgaben","effColVerdict":"Aktion","effLearned":"Selbstlernen angewandt","effTruth":"Echter ROAS korrigiert"},
  th: {"autoTabEff":"④ วิเคราะห์ประสิทธิภาพช่องทาง","effScaleUp":"เพิ่มงบประมาณ","effMaintain":"คงไว้","effOptimize":"ต้องปรับให้เหมาะสม","effCut":"ถอน·หยุด","effCollecting":"กำลังเก็บข้อมูล","effTitle":"วิเคราะห์ประสิทธิภาพช่องทางแบบครบถ้วน","effSubtitle":"คะแนนประสิทธิภาพที่รวมข้อมูลที่วัดได้ทั้งหมด (ROAS จริง·CAC·คอนเวอร์ชัน·แนวโน้ม) สูงสุด=ผู้สมัครเพิ่มงบประมาณ, ต่ำสุด=ผู้สมัครถอน·หยุด สะท้อน prior การเรียนรู้ด้วยตนเอง","effRefresh":"รีเฟรช","effLoading":"กำลังวิเคราะห์…","effEmpty":"ยังไม่มีข้อมูลการยิงโฆษณา/ผลลัพธ์ ประสิทธิภาพแต่ละช่องทางจะถูกวิเคราะห์หลังจากรันแคมเปญ","effBest":"ช่องทางประสิทธิภาพสูงสุด","effScore":"คะแนนประสิทธิภาพ","effWorst":"ช่องทางประสิทธิภาพต่ำสุด","effColChannel":"ช่องทาง","effColScore":"คะแนน","effColConv":"คอนเวอร์ชัน","effColSpend":"ค่าใช้จ่าย","effColVerdict":"การดำเนินการ","effLearned":"ใช้การเรียนรู้ด้วยตนเอง","effTruth":"ปรับด้วย ROAS จริง"},
  vi: {"autoTabEff":"④ Phân tích hiệu quả kênh","effScaleUp":"Tăng ngân sách","effMaintain":"Duy trì","effOptimize":"Cần tối ưu","effCut":"Thu hồi·Dừng","effCollecting":"Đang thu thập dữ liệu","effTitle":"Phân tích hiệu quả kênh toàn diện","effSubtitle":"Điểm hiệu quả tổng hợp toàn bộ dữ liệu đo lường thực tế (ROAS thật·CAC·chuyển đổi·xu hướng). Cao nhất = ứng viên tăng ngân sách, thấp nhất = ứng viên thu hồi·dừng. Đã phản ánh prior tự học.","effRefresh":"Làm mới","effLoading":"Đang phân tích…","effEmpty":"Chưa có dữ liệu triển khai/hiệu suất. Hiệu quả từng kênh sẽ được phân tích sau khi chạy chiến dịch.","effBest":"Kênh hiệu quả nhất","effScore":"Điểm hiệu quả","effWorst":"Kênh hiệu quả thấp nhất","effColChannel":"Kênh","effColScore":"Điểm","effColConv":"Chuyển đổi","effColSpend":"Chi tiêu","effColVerdict":"Hành động","effLearned":"Áp dụng tự học","effTruth":"Hiệu chỉnh ROAS thật"},
  id: {"autoTabEff":"④ Analisis Efektivitas Kanal","effScaleUp":"Tingkatkan Anggaran","effMaintain":"Pertahankan","effOptimize":"Perlu Optimasi","effCut":"Tarik·Hentikan","effCollecting":"Mengumpulkan Data","effTitle":"Analisis Efektivitas Kanal Menyeluruh","effSubtitle":"Skor efektivitas yang menggabungkan seluruh data terukur (ROAS sebenarnya·CAC·konversi·tren). Tertinggi = kandidat penambahan anggaran, terendah = kandidat tarik·hentikan. Mencerminkan prior pembelajaran mandiri.","effRefresh":"Segarkan","effLoading":"Menganalisis…","effEmpty":"Belum ada data penayangan/performa. Efektivitas tiap kanal akan dianalisis setelah kampanye berjalan.","effBest":"Kanal Berkinerja Terbaik","effScore":"Skor Efektivitas","effWorst":"Kanal Berkinerja Terendah","effColChannel":"Kanal","effColScore":"Skor","effColConv":"Konversi","effColSpend":"Pengeluaran","effColVerdict":"Tindakan","effLearned":"Pembelajaran Mandiri Diterapkan","effTruth":"Disesuaikan ROAS Sebenarnya"},
  ar: {"autoTabEff":"④ تحليل فعالية القنوات","effScaleUp":"زيادة الميزانية","effMaintain":"الحفاظ","effOptimize":"بحاجة لتحسين","effCut":"سحب·إيقاف","effCollecting":"جمع البيانات","effTitle":"تحليل شامل لفعالية القنوات","effSubtitle":"درجة فعالية تجمع البيانات المقاسة بالكامل (ROAS الحقيقي·CAC·التحويلات·الاتجاه). الأعلى = مرشح لزيادة الميزانية، الأدنى = مرشح للسحب·الإيقاف. يعكس مُسبق التعلم الذاتي.","effRefresh":"تحديث","effLoading":"جارٍ التحليل…","effEmpty":"لا توجد بيانات تشغيل/أداء بعد. سيتم تحليل فعالية كل قناة بعد تشغيل الحملات.","effBest":"القناة الأعلى أداءً","effScore":"درجة الفعالية","effWorst":"القناة الأدنى أداءً","effColChannel":"القناة","effColScore":"الدرجة","effColConv":"التحويلات","effColSpend":"الإنفاق","effColVerdict":"الإجراء","effLearned":"تم تطبيق التعلم الذاتي","effTruth":"معدّل بـ ROAS الحقيقي"},
  es: {"autoTabEff":"④ Análisis de Efectividad de Canales","effScaleUp":"Aumentar Presupuesto","effMaintain":"Mantener","effOptimize":"Requiere Optimización","effCut":"Recortar / Pausar","effCollecting":"Recopilando Datos","effTitle":"Análisis Completo de Efectividad de Canales","effSubtitle":"Una puntuación de efectividad que combina todos los datos medidos (ROAS real, CAC, conversiones, tendencia). Mayor = candidato a aumento de presupuesto, menor = candidato a recortar/pausar. Refleja prior de autoaprendizaje.","effRefresh":"Actualizar","effLoading":"Analizando…","effEmpty":"Aún no hay datos de ejecución/rendimiento. La efectividad por canal se analizará tras ejecutar las campañas.","effBest":"Canal de Mejor Rendimiento","effScore":"Puntuación de Efectividad","effWorst":"Canal de Menor Rendimiento","effColChannel":"Canal","effColScore":"Puntuación","effColConv":"Conversiones","effColSpend":"Gasto","effColVerdict":"Acción","effLearned":"Autoaprendizaje Aplicado","effTruth":"Ajustado por ROAS Real"},
  fr: {"autoTabEff":"④ Analyse d'Efficacité des Canaux","effScaleUp":"Augmenter le Budget","effMaintain":"Maintenir","effOptimize":"Optimisation Requise","effCut":"Réduire / Suspendre","effCollecting":"Collecte de Données","effTitle":"Analyse Complète de l'Efficacité des Canaux","effSubtitle":"Un score d'efficacité combinant l'ensemble des données mesurées (ROAS réel, CAC, conversions, tendance). Le plus élevé = candidat à l'augmentation du budget, le plus bas = candidat à la réduction/suspension. Reflète le prior d'auto-apprentissage.","effRefresh":"Actualiser","effLoading":"Analyse en cours…","effEmpty":"Aucune donnée de diffusion/performance pour l'instant. L'efficacité par canal sera analysée après l'exécution des campagnes.","effBest":"Canal le Plus Performant","effScore":"Score d'Efficacité","effWorst":"Canal le Moins Performant","effColChannel":"Canal","effColScore":"Score","effColConv":"Conversions","effColSpend":"Dépenses","effColVerdict":"Action","effLearned":"Auto-apprentissage Appliqué","effTruth":"Ajusté au ROAS Réel"},
  hi: {"autoTabEff":"④ चैनल प्रभावशीलता विश्लेषण","effScaleUp":"बजट बढ़ाएं","effMaintain":"बनाए रखें","effOptimize":"अनुकूलन आवश्यक","effCut":"वापस लें·रोकें","effCollecting":"डेटा एकत्र हो रहा है","effTitle":"संपूर्ण चैनल प्रभावशीलता विश्लेषण","effSubtitle":"संपूर्ण मापे गए डेटा (वास्तविक ROAS·CAC·रूपांतरण·रुझान) को संयोजित करने वाला प्रभावशीलता स्कोर। उच्चतम = बजट बढ़ाने का उम्मीदवार, निम्नतम = वापस लेने·रोकने का उम्मीदवार। स्व-शिक्षण prior को दर्शाता है।","effRefresh":"रिफ्रेश","effLoading":"विश्लेषण हो रहा है…","effEmpty":"अभी तक कोई निष्पादन/प्रदर्शन डेटा नहीं है। अभियान चलाने के बाद प्रत्येक चैनल की प्रभावशीलता का विश्लेषण किया जाएगा।","effBest":"सर्वश्रेष्ठ प्रदर्शन वाला चैनल","effScore":"प्रभावशीलता स्कोर","effWorst":"न्यूनतम प्रदर्शन वाला चैनल","effColChannel":"चैनल","effColScore":"स्कोर","effColConv":"रूपांतरण","effColSpend":"व्यय","effColVerdict":"कार्रवाई","effLearned":"स्व-शिक्षण लागू","effTruth":"वास्तविक ROAS समायोजित"},
  pt: {"autoTabEff":"④ Análise de Eficácia de Canais","effScaleUp":"Aumentar Orçamento","effMaintain":"Manter","effOptimize":"Requer Otimização","effCut":"Cortar / Pausar","effCollecting":"Coletando Dados","effTitle":"Análise Completa de Eficácia de Canais","effSubtitle":"Uma pontuação de eficácia que combina todos os dados medidos (ROAS real, CAC, conversões, tendência). Maior = candidato a aumento de orçamento, menor = candidato a cortar/pausar. Reflete prior de autoaprendizagem.","effRefresh":"Atualizar","effLoading":"Analisando…","effEmpty":"Ainda não há dados de veiculação/desempenho. A eficácia por canal será analisada após a execução das campanhas.","effBest":"Canal de Melhor Desempenho","effScore":"Pontuação de Eficácia","effWorst":"Canal de Menor Desempenho","effColChannel":"Canal","effColScore":"Pontuação","effColConv":"Conversões","effColSpend":"Gasto","effColVerdict":"Ação","effLearned":"Autoaprendizagem Aplicada","effTruth":"Ajustado por ROAS Real"},
  ru: {"autoTabEff":"④ Анализ эффективности каналов","effScaleUp":"Увеличить бюджет","effMaintain":"Сохранить","effOptimize":"Требует оптимизации","effCut":"Сократить·Остановить","effCollecting":"Сбор данных","effTitle":"Полный анализ эффективности каналов","effSubtitle":"Оценка эффективности, объединяющая все измеренные данные (истинный ROAS·CAC·конверсии·тренд). Наивысшая = кандидат на увеличение бюджета, наименьшая = кандидат на сокращение·остановку. Учитывает prior самообучения.","effRefresh":"Обновить","effLoading":"Анализ…","effEmpty":"Пока нет данных о показах/результатах. Эффективность каждого канала будет проанализирована после запуска кампаний.","effBest":"Самый эффективный канал","effScore":"Оценка эффективности","effWorst":"Наименее эффективный канал","effColChannel":"Канал","effColScore":"Оценка","effColConv":"Конверсии","effColSpend":"Расходы","effColVerdict":"Действие","effLearned":"Применено самообучение","effTruth":"Скорректировано по истинному ROAS"},
};

function findLastTopProp(o, name) { let found = null; for (const p of o.properties) { if (p.type !== 'Property') continue; const k = p.key.type === 'Identifier' ? p.key.name : p.key.value; if (k === name) found = p; } return found; }
function existing(o) { const s = new Set(); for (const p of o.properties) { if (p.type !== 'Property') continue; s.add(p.key.type === 'Identifier' ? p.key.name : p.key.value); } return s; }

const LANGS = ['ko','en','ja','zh','zh-TW','de','th','vi','id','ar','es','fr','hi','pt','ru'];
const summary = [];
for (const lang of LANGS) {
  const file = path.join(LOCDIR, lang + '.js');
  let src = fs.readFileSync(file, 'utf8');
  const tr = EFF[lang]; if (!tr) { console.error(`${lang}: no table`); process.exit(2); }
  const ast = parse(src, { ecmaVersion: 'latest', sourceType: 'module' });
  let root = null; for (const b of ast.body) if (b.type === 'ExportDefaultDeclaration') root = b.declaration;
  const ns = findLastTopProp(root, 'marketing');
  if (!ns || ns.value.type !== 'ObjectExpression') { console.error(`${lang}: no top-level marketing ns`); process.exit(2); }
  const have = existing(ns.value);
  const toAdd = Object.keys(tr).filter(k => !have.has(k));
  if (!toAdd.length) { summary.push(`${lang}: +0 (skip)`); continue; }
  const props = ns.value.properties; const last = props[props.length - 1];
  let ins = ''; for (const k of toAdd) ins += `, ${JSON.stringify(k)}: ${JSON.stringify(tr[k])}`;
  src = src.slice(0, last.end) + ins + src.slice(last.end);
  parse(src, { ecmaVersion: 'latest', sourceType: 'module' }); // 재파싱 검증
  fs.writeFileSync(file, src, 'utf8');
  summary.push(`${lang}: +${toAdd.length}`);
}
console.log(summary.join('\n'));
