#!/usr/bin/env node
/** P4 i18n — Attribution 증분성·홀드아웃 탭 attrData.incr/tabIncr 키 33개 15개국 주입. acorn splice, 멱등. */
const fs = require('fs');
const path = require('path');
const { parse } = require('acorn');
const LOCDIR = path.join(__dirname, '..', 'frontend', 'src', 'i18n', 'locales');
const NS = 'attrData';
const KEYS = ['tabIncrLabel','tabIncrDesc','incrIntro','incrSpend','incrRevenue','incrBlended','incrConv','incrColSpend','incrColReported','incrColIncRoas','incrColOver','incrColCpa','incrColHoldout','incrDays','incrInsufficient','incrLoading','incrLiftTitle','incrLiftDesc','incrCtrlConv','incrCtrlSize','incrTrtConv','incrTrtSize','incrRpc','incrAnalyzing','incrRun','incrLiftErr','incrRelLift','incrPval','incrZscore','incrIncConv','incrIncVal','incrCvrCompare','incrTrtCvr','incrInsufficient2'];
// (incrInsufficient2 미사용 placeholder 제거)
KEYS.pop();

const T = {
  ko: { tabIncrLabel:'📊 증분성·홀드아웃', tabIncrDesc:'리프트 테스트', incrIntro:'데이터기반 증분 기여도(마르코프 제거효과)를 last-touch 보고치와 비교해 채널별 증분 ROAS·과대귀속을 산출하고, 실제 홀드아웃 실험에 필요한 검정력(최소검출효과·필요기간)을 안내합니다.', incrSpend:'총 광고비', incrRevenue:'총 매출', incrBlended:'블렌드 ROAS', incrConv:'전환수', incrColSpend:'광고비', incrColReported:'보고 ROAS', incrColIncRoas:'증분 ROAS', incrColOver:'과대귀속', incrColCpa:'증분 CPA', incrColHoldout:'홀드아웃(10%리프트)', incrDays:'일', incrInsufficient:'데이터 부족', incrLoading:'불러오는 중...', incrLiftTitle:'홀드아웃 리프트 테스트', incrLiftDesc:'대조군(노출 제외)과 실험군(노출)의 전환 결과를 입력하면 증분 리프트·통계적 유의성(p값)을 검정합니다.', incrCtrlConv:'대조군 전환수', incrCtrlSize:'대조군 규모', incrTrtConv:'실험군 전환수', incrTrtSize:'실험군 규모', incrRpc:'전환당 매출(선택)', incrAnalyzing:'분석 중...', incrRun:'리프트 검정 실행', incrLiftErr:'분석에 실패했습니다.', incrRelLift:'상대 리프트', incrPval:'p값', incrZscore:'z-score', incrIncConv:'증분 전환', incrIncVal:'증분 매출', incrCvrCompare:'대조군 CVR', incrTrtCvr:'실험군 CVR' },
  en: { tabIncrLabel:'📊 Incrementality·Holdout', tabIncrDesc:'Lift test', incrIntro:'Compares data-driven incremental credit (Markov removal effect) against last-touch reported figures to derive per-channel incremental ROAS and over-attribution, and guides the statistical power (minimum detectable effect, required duration) needed for a real holdout experiment.', incrSpend:'Total spend', incrRevenue:'Total revenue', incrBlended:'Blended ROAS', incrConv:'Conversions', incrColSpend:'Spend', incrColReported:'Reported ROAS', incrColIncRoas:'Incremental ROAS', incrColOver:'Over-attribution', incrColCpa:'Incremental CPA', incrColHoldout:'Holdout (10% lift)', incrDays:'d', incrInsufficient:'Insufficient data', incrLoading:'Loading...', incrLiftTitle:'Holdout lift test', incrLiftDesc:'Enter the conversion results of the control (no exposure) and treatment (exposed) groups to test incremental lift and statistical significance (p-value).', incrCtrlConv:'Control conversions', incrCtrlSize:'Control size', incrTrtConv:'Treatment conversions', incrTrtSize:'Treatment size', incrRpc:'Revenue per conversion (optional)', incrAnalyzing:'Analyzing...', incrRun:'Run lift test', incrLiftErr:'Analysis failed.', incrRelLift:'Relative lift', incrPval:'p-value', incrZscore:'z-score', incrIncConv:'Incremental conv.', incrIncVal:'Incremental value', incrCvrCompare:'Control CVR', incrTrtCvr:'Treatment CVR' },
  ja: { tabIncrLabel:'📊 増分性・ホールドアウト', tabIncrDesc:'リフトテスト', incrIntro:'データドリブンの増分貢献度（マルコフ除外効果）をラストタッチ報告値と比較してチャネル別の増分ROAS・過大帰属を算出し、実際のホールドアウト実験に必要な検出力（最小検出効果・必要期間）を案内します。', incrSpend:'総広告費', incrRevenue:'総売上', incrBlended:'ブレンドROAS', incrConv:'コンバージョン数', incrColSpend:'広告費', incrColReported:'報告ROAS', incrColIncRoas:'増分ROAS', incrColOver:'過大帰属', incrColCpa:'増分CPA', incrColHoldout:'ホールドアウト(10%リフト)', incrDays:'日', incrInsufficient:'データ不足', incrLoading:'読み込み中...', incrLiftTitle:'ホールドアウトリフトテスト', incrLiftDesc:'対照群（非露出）と実験群（露出）のコンバージョン結果を入力すると、増分リフト・統計的有意性（p値）を検定します。', incrCtrlConv:'対照群CV数', incrCtrlSize:'対照群規模', incrTrtConv:'実験群CV数', incrTrtSize:'実験群規模', incrRpc:'CV単価売上（任意）', incrAnalyzing:'分析中...', incrRun:'リフト検定を実行', incrLiftErr:'分析に失敗しました。', incrRelLift:'相対リフト', incrPval:'p値', incrZscore:'z値', incrIncConv:'増分CV', incrIncVal:'増分売上', incrCvrCompare:'対照群CVR', incrTrtCvr:'実験群CVR' },
  zh: { tabIncrLabel:'📊 增量·留出', tabIncrDesc:'提升测试', incrIntro:'将数据驱动的增量贡献（马尔可夫移除效应）与末次触点报告值对比，得出各渠道的增量ROAS与过度归因，并指导真实留出实验所需的统计功效（最小可检测效应·所需周期）。', incrSpend:'总广告花费', incrRevenue:'总营收', incrBlended:'混合ROAS', incrConv:'转化数', incrColSpend:'花费', incrColReported:'报告ROAS', incrColIncRoas:'增量ROAS', incrColOver:'过度归因', incrColCpa:'增量CPA', incrColHoldout:'留出(10%提升)', incrDays:'天', incrInsufficient:'数据不足', incrLoading:'加载中...', incrLiftTitle:'留出提升测试', incrLiftDesc:'输入对照组(未曝光)与实验组(曝光)的转化结果，检验增量提升与统计显著性(p值)。', incrCtrlConv:'对照组转化', incrCtrlSize:'对照组规模', incrTrtConv:'实验组转化', incrTrtSize:'实验组规模', incrRpc:'每转化营收(可选)', incrAnalyzing:'分析中...', incrRun:'运行提升检验', incrLiftErr:'分析失败。', incrRelLift:'相对提升', incrPval:'p值', incrZscore:'z值', incrIncConv:'增量转化', incrIncVal:'增量价值', incrCvrCompare:'对照组CVR', incrTrtCvr:'实验组CVR' },
  'zh-TW': { tabIncrLabel:'📊 增量·保留組', tabIncrDesc:'提升測試', incrIntro:'將資料驅動的增量貢獻（馬可夫移除效應）與最後接觸報告值比較，得出各通路的增量ROAS與過度歸因，並指導真實保留組實驗所需的統計檢定力（最小可偵測效應·所需期間）。', incrSpend:'總廣告花費', incrRevenue:'總營收', incrBlended:'混合ROAS', incrConv:'轉換數', incrColSpend:'花費', incrColReported:'報告ROAS', incrColIncRoas:'增量ROAS', incrColOver:'過度歸因', incrColCpa:'增量CPA', incrColHoldout:'保留組(10%提升)', incrDays:'天', incrInsufficient:'資料不足', incrLoading:'載入中...', incrLiftTitle:'保留組提升測試', incrLiftDesc:'輸入對照組(未曝光)與實驗組(曝光)的轉換結果，檢定增量提升與統計顯著性(p值)。', incrCtrlConv:'對照組轉換', incrCtrlSize:'對照組規模', incrTrtConv:'實驗組轉換', incrTrtSize:'實驗組規模', incrRpc:'每轉換營收(選填)', incrAnalyzing:'分析中...', incrRun:'執行提升檢定', incrLiftErr:'分析失敗。', incrRelLift:'相對提升', incrPval:'p值', incrZscore:'z值', incrIncConv:'增量轉換', incrIncVal:'增量價值', incrCvrCompare:'對照組CVR', incrTrtCvr:'實驗組CVR' },
  de: { tabIncrLabel:'📊 Inkrementalität·Holdout', tabIncrDesc:'Lift-Test', incrIntro:'Vergleicht den datengetriebenen inkrementellen Beitrag (Markov-Removal-Effekt) mit den Last-Touch-Werten, um inkrementellen ROAS und Über-Attribution je Kanal abzuleiten, und gibt die nötige statistische Power (minimal erkennbarer Effekt, erforderliche Dauer) für ein echtes Holdout-Experiment an.', incrSpend:'Gesamtausgaben', incrRevenue:'Gesamtumsatz', incrBlended:'Blended ROAS', incrConv:'Conversions', incrColSpend:'Ausgaben', incrColReported:'Berichteter ROAS', incrColIncRoas:'Inkrementeller ROAS', incrColOver:'Über-Attribution', incrColCpa:'Inkrementeller CPA', incrColHoldout:'Holdout (10% Lift)', incrDays:'T', incrInsufficient:'Unzureichende Daten', incrLoading:'Wird geladen...', incrLiftTitle:'Holdout-Lift-Test', incrLiftDesc:'Geben Sie die Conversion-Ergebnisse der Kontroll- (keine Auslieferung) und Testgruppe (ausgeliefert) ein, um inkrementellen Lift und statistische Signifikanz (p-Wert) zu prüfen.', incrCtrlConv:'Kontroll-Conversions', incrCtrlSize:'Kontrollgröße', incrTrtConv:'Test-Conversions', incrTrtSize:'Testgröße', incrRpc:'Umsatz pro Conversion (optional)', incrAnalyzing:'Analyse läuft...', incrRun:'Lift-Test starten', incrLiftErr:'Analyse fehlgeschlagen.', incrRelLift:'Relativer Lift', incrPval:'p-Wert', incrZscore:'z-Wert', incrIncConv:'Inkrement. Conv.', incrIncVal:'Inkrement. Wert', incrCvrCompare:'Kontroll-CVR', incrTrtCvr:'Test-CVR' },
  th: { tabIncrLabel:'📊 ส่วนเพิ่ม·โฮลด์เอาต์', tabIncrDesc:'ทดสอบลิฟต์', incrIntro:'เปรียบเทียบเครดิตส่วนเพิ่มที่ขับเคลื่อนด้วยข้อมูล (Markov removal effect) กับค่ารายงานแบบ last-touch เพื่อหาค่า ROAS ส่วนเพิ่มและการระบุเกินจริงต่อช่องทาง พร้อมแนะนำกำลังการทดสอบ (ผลกระทบต่ำสุดที่ตรวจจับได้·ระยะเวลาที่ต้องใช้) สำหรับการทดลองโฮลด์เอาต์จริง', incrSpend:'ค่าโฆษณารวม', incrRevenue:'รายได้รวม', incrBlended:'ROAS รวม', incrConv:'จำนวนคอนเวอร์ชัน', incrColSpend:'ค่าโฆษณา', incrColReported:'ROAS ที่รายงาน', incrColIncRoas:'ROAS ส่วนเพิ่ม', incrColOver:'ระบุเกินจริง', incrColCpa:'CPA ส่วนเพิ่ม', incrColHoldout:'โฮลด์เอาต์(ลิฟต์10%)', incrDays:'วัน', incrInsufficient:'ข้อมูลไม่พอ', incrLoading:'กำลังโหลด...', incrLiftTitle:'การทดสอบลิฟต์โฮลด์เอาต์', incrLiftDesc:'กรอกผลคอนเวอร์ชันของกลุ่มควบคุม (ไม่แสดงโฆษณา) และกลุ่มทดลอง (แสดงโฆษณา) เพื่อทดสอบลิฟต์ส่วนเพิ่มและนัยสำคัญทางสถิติ (ค่า p)', incrCtrlConv:'คอนเวอร์ชันกลุ่มควบคุม', incrCtrlSize:'ขนาดกลุ่มควบคุม', incrTrtConv:'คอนเวอร์ชันกลุ่มทดลอง', incrTrtSize:'ขนาดกลุ่มทดลอง', incrRpc:'รายได้ต่อคอนเวอร์ชัน (ไม่บังคับ)', incrAnalyzing:'กำลังวิเคราะห์...', incrRun:'รันการทดสอบลิฟต์', incrLiftErr:'การวิเคราะห์ล้มเหลว', incrRelLift:'ลิฟต์สัมพัทธ์', incrPval:'ค่า p', incrZscore:'ค่า z', incrIncConv:'คอนเวอร์ชันส่วนเพิ่ม', incrIncVal:'มูลค่าส่วนเพิ่ม', incrCvrCompare:'CVR กลุ่มควบคุม', incrTrtCvr:'CVR กลุ่มทดลอง' },
  vi: { tabIncrLabel:'📊 Gia tăng·Holdout', tabIncrDesc:'Kiểm định lift', incrIntro:'So sánh đóng góp gia tăng dựa trên dữ liệu (hiệu ứng loại bỏ Markov) với số liệu báo cáo last-touch để tính ROAS gia tăng và quy gán quá mức theo kênh, đồng thời hướng dẫn năng lực thống kê (hiệu ứng tối thiểu phát hiện được·thời lượng cần thiết) cho thử nghiệm holdout thực tế.', incrSpend:'Tổng chi tiêu', incrRevenue:'Tổng doanh thu', incrBlended:'ROAS pha trộn', incrConv:'Chuyển đổi', incrColSpend:'Chi tiêu', incrColReported:'ROAS báo cáo', incrColIncRoas:'ROAS gia tăng', incrColOver:'Quy gán quá mức', incrColCpa:'CPA gia tăng', incrColHoldout:'Holdout (lift 10%)', incrDays:'ngày', incrInsufficient:'Thiếu dữ liệu', incrLoading:'Đang tải...', incrLiftTitle:'Kiểm định lift holdout', incrLiftDesc:'Nhập kết quả chuyển đổi của nhóm đối chứng (không hiển thị) và nhóm thử nghiệm (có hiển thị) để kiểm định lift gia tăng và ý nghĩa thống kê (giá trị p).', incrCtrlConv:'Chuyển đổi đối chứng', incrCtrlSize:'Quy mô đối chứng', incrTrtConv:'Chuyển đổi thử nghiệm', incrTrtSize:'Quy mô thử nghiệm', incrRpc:'Doanh thu mỗi chuyển đổi (tùy chọn)', incrAnalyzing:'Đang phân tích...', incrRun:'Chạy kiểm định lift', incrLiftErr:'Phân tích thất bại.', incrRelLift:'Lift tương đối', incrPval:'giá trị p', incrZscore:'điểm z', incrIncConv:'CĐ gia tăng', incrIncVal:'Giá trị gia tăng', incrCvrCompare:'CVR đối chứng', incrTrtCvr:'CVR thử nghiệm' },
  id: { tabIncrLabel:'📊 Inkrementalitas·Holdout', tabIncrDesc:'Uji lift', incrIntro:'Membandingkan kontribusi inkremental berbasis data (efek penghapusan Markov) dengan angka laporan last-touch untuk menurunkan ROAS inkremental dan over-atribusi per kanal, serta memandu daya statistik (efek minimum terdeteksi·durasi yang diperlukan) untuk eksperimen holdout nyata.', incrSpend:'Total belanja', incrRevenue:'Total pendapatan', incrBlended:'ROAS gabungan', incrConv:'Konversi', incrColSpend:'Belanja', incrColReported:'ROAS dilaporkan', incrColIncRoas:'ROAS inkremental', incrColOver:'Over-atribusi', incrColCpa:'CPA inkremental', incrColHoldout:'Holdout (lift 10%)', incrDays:'hr', incrInsufficient:'Data kurang', incrLoading:'Memuat...', incrLiftTitle:'Uji lift holdout', incrLiftDesc:'Masukkan hasil konversi grup kontrol (tanpa tayangan) dan perlakuan (ditayangkan) untuk menguji lift inkremental dan signifikansi statistik (nilai p).', incrCtrlConv:'Konversi kontrol', incrCtrlSize:'Ukuran kontrol', incrTrtConv:'Konversi perlakuan', incrTrtSize:'Ukuran perlakuan', incrRpc:'Pendapatan per konversi (opsional)', incrAnalyzing:'Menganalisis...', incrRun:'Jalankan uji lift', incrLiftErr:'Analisis gagal.', incrRelLift:'Lift relatif', incrPval:'nilai p', incrZscore:'skor z', incrIncConv:'Konv. inkremental', incrIncVal:'Nilai inkremental', incrCvrCompare:'CVR kontrol', incrTrtCvr:'CVR perlakuan' },
  ar: { tabIncrLabel:'📊 الأثر الإضافي·الاحتجاز', tabIncrDesc:'اختبار الرفع', incrIntro:'يقارن المساهمة الإضافية المعتمدة على البيانات (تأثير الإزالة ماركوف) بقيم اللمسة الأخيرة لاشتقاق ROAS الإضافي والإسناد المفرط لكل قناة، ويرشد القوة الإحصائية (أدنى تأثير قابل للكشف·المدة المطلوبة) لتجربة احتجاز حقيقية.', incrSpend:'إجمالي الإنفاق', incrRevenue:'إجمالي الإيرادات', incrBlended:'ROAS مدمج', incrConv:'التحويلات', incrColSpend:'الإنفاق', incrColReported:'ROAS المبلّغ', incrColIncRoas:'ROAS الإضافي', incrColOver:'إسناد مفرط', incrColCpa:'CPA الإضافي', incrColHoldout:'الاحتجاز (رفع 10%)', incrDays:'يوم', incrInsufficient:'بيانات غير كافية', incrLoading:'جارٍ التحميل...', incrLiftTitle:'اختبار رفع الاحتجاز', incrLiftDesc:'أدخل نتائج التحويل لمجموعة الضبط (دون عرض) ومجموعة المعالجة (مع عرض) لاختبار الرفع الإضافي والدلالة الإحصائية (قيمة p).', incrCtrlConv:'تحويلات الضبط', incrCtrlSize:'حجم الضبط', incrTrtConv:'تحويلات المعالجة', incrTrtSize:'حجم المعالجة', incrRpc:'الإيراد لكل تحويل (اختياري)', incrAnalyzing:'جارٍ التحليل...', incrRun:'تشغيل اختبار الرفع', incrLiftErr:'فشل التحليل.', incrRelLift:'الرفع النسبي', incrPval:'قيمة p', incrZscore:'درجة z', incrIncConv:'تحويلات إضافية', incrIncVal:'قيمة إضافية', incrCvrCompare:'CVR الضبط', incrTrtCvr:'CVR المعالجة' },
  es: { tabIncrLabel:'📊 Incrementalidad·Holdout', tabIncrDesc:'Test de lift', incrIntro:'Compara la contribución incremental basada en datos (efecto de eliminación de Markov) con las cifras reportadas de último toque para derivar el ROAS incremental y la sobreatribución por canal, y orienta la potencia estadística (efecto mínimo detectable·duración necesaria) para un experimento de holdout real.', incrSpend:'Inversión total', incrRevenue:'Ingresos totales', incrBlended:'ROAS combinado', incrConv:'Conversiones', incrColSpend:'Inversión', incrColReported:'ROAS reportado', incrColIncRoas:'ROAS incremental', incrColOver:'Sobreatribución', incrColCpa:'CPA incremental', incrColHoldout:'Holdout (lift 10%)', incrDays:'d', incrInsufficient:'Datos insuficientes', incrLoading:'Cargando...', incrLiftTitle:'Test de lift con holdout', incrLiftDesc:'Introduce los resultados de conversión del grupo de control (sin exposición) y de tratamiento (expuesto) para probar el lift incremental y la significancia estadística (valor p).', incrCtrlConv:'Conversiones control', incrCtrlSize:'Tamaño control', incrTrtConv:'Conversiones tratamiento', incrTrtSize:'Tamaño tratamiento', incrRpc:'Ingreso por conversión (opcional)', incrAnalyzing:'Analizando...', incrRun:'Ejecutar test de lift', incrLiftErr:'Error en el análisis.', incrRelLift:'Lift relativo', incrPval:'valor p', incrZscore:'puntuación z', incrIncConv:'Conv. incremental', incrIncVal:'Valor incremental', incrCvrCompare:'CVR control', incrTrtCvr:'CVR tratamiento' },
  fr: { tabIncrLabel:'📊 Incrémentalité·Holdout', tabIncrDesc:'Test de lift', incrIntro:'Compare la contribution incrémentale fondée sur les données (effet de retrait de Markov) aux valeurs déclarées au dernier contact pour dériver le ROAS incrémental et la sur-attribution par canal, et indique la puissance statistique (effet minimal détectable·durée requise) pour une vraie expérience de holdout.', incrSpend:'Dépense totale', incrRevenue:'Revenu total', incrBlended:'ROAS combiné', incrConv:'Conversions', incrColSpend:'Dépense', incrColReported:'ROAS déclaré', incrColIncRoas:'ROAS incrémental', incrColOver:'Sur-attribution', incrColCpa:'CPA incrémental', incrColHoldout:'Holdout (lift 10%)', incrDays:'j', incrInsufficient:'Données insuffisantes', incrLoading:'Chargement...', incrLiftTitle:'Test de lift holdout', incrLiftDesc:'Saisissez les résultats de conversion des groupes témoin (sans exposition) et test (exposé) pour évaluer le lift incrémental et la significativité statistique (valeur p).', incrCtrlConv:'Conversions témoin', incrCtrlSize:'Taille témoin', incrTrtConv:'Conversions test', incrTrtSize:'Taille test', incrRpc:'Revenu par conversion (facultatif)', incrAnalyzing:'Analyse...', incrRun:'Lancer le test de lift', incrLiftErr:'Échec de l’analyse.', incrRelLift:'Lift relatif', incrPval:'valeur p', incrZscore:'score z', incrIncConv:'Conv. incrémentale', incrIncVal:'Valeur incrémentale', incrCvrCompare:'CVR témoin', incrTrtCvr:'CVR test' },
  hi: { tabIncrLabel:'📊 वृद्धिशीलता·होल्डआउट', tabIncrDesc:'लिफ्ट परीक्षण', incrIntro:'डेटा-आधारित वृद्धिशील योगदान (मार्कोव रिमूवल प्रभाव) की तुलना last-touch रिपोर्ट मानों से कर प्रति-चैनल वृद्धिशील ROAS और अति-एट्रिब्यूशन निकालता है, और वास्तविक होल्डआउट प्रयोग हेतु सांख्यिकीय शक्ति (न्यूनतम पहचान योग्य प्रभाव·आवश्यक अवधि) बताता है।', incrSpend:'कुल खर्च', incrRevenue:'कुल राजस्व', incrBlended:'ब्लेंडेड ROAS', incrConv:'रूपांतरण', incrColSpend:'खर्च', incrColReported:'रिपोर्टेड ROAS', incrColIncRoas:'वृद्धिशील ROAS', incrColOver:'अति-एट्रिब्यूशन', incrColCpa:'वृद्धिशील CPA', incrColHoldout:'होल्डआउट (10% लिफ्ट)', incrDays:'दिन', incrInsufficient:'अपर्याप्त डेटा', incrLoading:'लोड हो रहा है...', incrLiftTitle:'होल्डआउट लिफ्ट परीक्षण', incrLiftDesc:'नियंत्रण समूह (बिना प्रदर्शन) और उपचार समूह (प्रदर्शित) के रूपांतरण परिणाम दर्ज कर वृद्धिशील लिफ्ट और सांख्यिकीय महत्व (p-मान) की जाँच करें।', incrCtrlConv:'नियंत्रण रूपांतरण', incrCtrlSize:'नियंत्रण आकार', incrTrtConv:'उपचार रूपांतरण', incrTrtSize:'उपचार आकार', incrRpc:'प्रति रूपांतरण राजस्व (वैकल्पिक)', incrAnalyzing:'विश्लेषण हो रहा है...', incrRun:'लिफ्ट परीक्षण चलाएँ', incrLiftErr:'विश्लेषण विफल।', incrRelLift:'सापेक्ष लिफ्ट', incrPval:'p-मान', incrZscore:'z-स्कोर', incrIncConv:'वृद्धिशील रूपां.', incrIncVal:'वृद्धिशील मूल्य', incrCvrCompare:'नियंत्रण CVR', incrTrtCvr:'उपचार CVR' },
  pt: { tabIncrLabel:'📊 Incrementalidade·Holdout', tabIncrDesc:'Teste de lift', incrIntro:'Compara a contribuição incremental baseada em dados (efeito de remoção de Markov) com os valores reportados de último toque para derivar o ROAS incremental e a sobreatribuição por canal, e orienta o poder estatístico (efeito mínimo detectável·duração necessária) para um experimento de holdout real.', incrSpend:'Investimento total', incrRevenue:'Receita total', incrBlended:'ROAS combinado', incrConv:'Conversões', incrColSpend:'Investimento', incrColReported:'ROAS reportado', incrColIncRoas:'ROAS incremental', incrColOver:'Sobreatribuição', incrColCpa:'CPA incremental', incrColHoldout:'Holdout (lift 10%)', incrDays:'d', incrInsufficient:'Dados insuficientes', incrLoading:'Carregando...', incrLiftTitle:'Teste de lift com holdout', incrLiftDesc:'Insira os resultados de conversão dos grupos de controle (sem exibição) e tratamento (exibido) para testar o lift incremental e a significância estatística (valor p).', incrCtrlConv:'Conversões controle', incrCtrlSize:'Tamanho controle', incrTrtConv:'Conversões tratamento', incrTrtSize:'Tamanho tratamento', incrRpc:'Receita por conversão (opcional)', incrAnalyzing:'Analisando...', incrRun:'Executar teste de lift', incrLiftErr:'Falha na análise.', incrRelLift:'Lift relativo', incrPval:'valor p', incrZscore:'escore z', incrIncConv:'Conv. incremental', incrIncVal:'Valor incremental', incrCvrCompare:'CVR controle', incrTrtCvr:'CVR tratamento' },
  ru: { tabIncrLabel:'📊 Инкрементальность·Холдаут', tabIncrDesc:'Тест на прирост', incrIntro:'Сравнивает основанный на данных инкрементальный вклад (эффект удаления Маркова) с отчётными значениями last-touch для расчёта инкрементального ROAS и переатрибуции по каналам, а также определяет статистическую мощность (минимально обнаружимый эффект·необходимую длительность) для реального холдаут-эксперимента.', incrSpend:'Общие расходы', incrRevenue:'Общая выручка', incrBlended:'Смешанный ROAS', incrConv:'Конверсии', incrColSpend:'Расходы', incrColReported:'Отчётный ROAS', incrColIncRoas:'Инкрем. ROAS', incrColOver:'Переатрибуция', incrColCpa:'Инкрем. CPA', incrColHoldout:'Холдаут (прирост 10%)', incrDays:'дн', incrInsufficient:'Недостаточно данных', incrLoading:'Загрузка...', incrLiftTitle:'Холдаут-тест на прирост', incrLiftDesc:'Введите результаты конверсии контрольной (без показа) и тестовой (с показом) групп для проверки инкрементального прироста и статистической значимости (p-значение).', incrCtrlConv:'Конверсии контроля', incrCtrlSize:'Размер контроля', incrTrtConv:'Конверсии теста', incrTrtSize:'Размер теста', incrRpc:'Выручка на конверсию (необяз.)', incrAnalyzing:'Анализ...', incrRun:'Запустить тест', incrLiftErr:'Ошибка анализа.', incrRelLift:'Относит. прирост', incrPval:'p-значение', incrZscore:'z-оценка', incrIncConv:'Инкрем. конв.', incrIncVal:'Инкрем. ценность', incrCvrCompare:'CVR контроля', incrTrtCvr:'CVR теста' },
};

function findTopProp(o, name) { for (const p of o.properties) { if (p.type !== 'Property') continue; const k = p.key.type === 'Identifier' ? p.key.name : p.key.value; if (k === name) return p; } return null; }
function existing(o) { const s = new Set(); for (const p of o.properties) { if (p.type !== 'Property') continue; s.add(p.key.type === 'Identifier' ? p.key.name : p.key.value); } return s; }

let summary = [];
for (const [lang, tr] of Object.entries(T)) {
  const file = path.join(LOCDIR, lang + '.js');
  let src = fs.readFileSync(file, 'utf8');
  const ast = parse(src, { ecmaVersion: 'latest', sourceType: 'module' });
  let root = null; for (const b of ast.body) if (b.type === 'ExportDefaultDeclaration') root = b.declaration;
  const ns = findTopProp(root, NS);
  if (!ns || ns.value.type !== 'ObjectExpression') { console.error(`${lang}: no ${NS}`); process.exit(2); }
  const have = existing(ns.value);
  const toAdd = KEYS.filter(k => !have.has(k));
  if (!toAdd.length) { summary.push(`${lang}: 0`); continue; }
  const props = ns.value.properties; const last = props[props.length - 1];
  let ins = ''; for (const k of toAdd) ins += `, ${JSON.stringify(k)}: ${JSON.stringify(tr[k])}`;
  src = src.slice(0, last.end) + ins + src.slice(last.end);
  parse(src, { ecmaVersion: 'latest', sourceType: 'module' });
  fs.writeFileSync(file, src, 'utf8');
  summary.push(`${lang}: +${toAdd.length}`);
}
console.log(summary.join('\n'));
