#!/usr/bin/env node
/** 255차 i18n — CRM 옴니채널 탭(crm.omni* + crm.tabOmni) 36키 15개국. acorn splice·멱등·최상위 crm ns 마지막 occurrence·재파싱검증. */
const fs = require('fs');
const path = require('path');
const { parse } = require('acorn');
const LOCDIR = path.join(__dirname, '..', 'frontend', 'src', 'i18n', 'locales');

const KO = {
  tabOmni:'옴니채널', omniNeedName:'캠페인 이름을 입력하세요', omniNeedCh:'채널을 1개 이상 선택하세요',
  omniCreated:'옴니채널 캠페인이 생성되었습니다', omniCreateFail:'생성 실패', omniQueued:'발송 큐 적재',
  omniFirstBatch:'즉시처리', omniSendFail:'발송 실패', omniChTitle:'연결 채널 상태',
  omniChSub:'자격을 등록하면 즉시 해당 채널로 실발송됩니다(미설정 채널은 다음 채널로 자동 폴백).',
  omniLive:'라이브', omniFallback:'폴백 가능', omniUnset:'미설정', omniNew:'새 옴니채널 캠페인',
  omniName:'캠페인 이름', omniNamePh:'예) 6월 VIP 재구매 유도', omniSeg:'대상 세그먼트', omniAllCust:'전체 고객',
  omniWaterfall:'채널 우선순위(위 채널 미도달/미설정 시 다음 채널로 폴백)', omniEmailSubj:'이메일 제목',
  omniEmailSubjPh:'예) {{name}}님께 드리는 특별 혜택', omniKakaoTpl:'카카오 템플릿 코드',
  omniKakaoTplPh:'승인된 알림톡 템플릿 코드', omniBody:'메시지 본문(전 채널 공통 · {{name}} 치환)',
  omniBodyPh:'{{name}}님, 이번 주만 특별 할인 진행 중입니다!', omniAlsoPush:'웹 푸시 동시 발송(구독자 전체)',
  omniCreate:'캠페인 생성', omniList:'옴니채널 캠페인', omniEmpty:'생성된 캠페인이 없습니다',
  omniTotal:'대상', omniSent:'발송', omniSkipped:'건너뜀', omniFailed:'실패', omniProgress:'진행률',
  omniByCh:'채널별', omniSend:'발송',
};

const TR = {
  en:{tabOmni:'Omnichannel',omniNeedName:'Enter a campaign name',omniNeedCh:'Select at least one channel',omniCreated:'Omnichannel campaign created',omniCreateFail:'Creation failed',omniQueued:'Queued for delivery',omniFirstBatch:'instant',omniSendFail:'Send failed',omniChTitle:'Connected channel status',omniChSub:'Once credentials are registered, delivery starts immediately on that channel (unset channels auto-fall back to the next one).',omniLive:'Live',omniFallback:'Fallback ready',omniUnset:'Not set',omniNew:'New omnichannel campaign',omniName:'Campaign name',omniNamePh:'e.g. June VIP repurchase push',omniSeg:'Target segment',omniAllCust:'All customers',omniWaterfall:'Channel priority (falls back to next channel if unreachable/unset)',omniEmailSubj:'Email subject',omniEmailSubjPh:'e.g. {{name}}, a special offer for you',omniKakaoTpl:'Kakao template code',omniKakaoTplPh:'Approved AlimTalk template code',omniBody:'Message body (shared across channels · {{name}} merge)',omniBodyPh:'{{name}}, special discount this week only!',omniAlsoPush:'Also send web push (all subscribers)',omniCreate:'Create campaign',omniList:'Omnichannel campaigns',omniEmpty:'No campaigns yet',omniTotal:'Target',omniSent:'Sent',omniSkipped:'Skipped',omniFailed:'Failed',omniProgress:'Progress',omniByCh:'By channel',omniSend:'Send'},
  ja:{tabOmni:'オムニチャネル',omniNeedName:'キャンペーン名を入力してください',omniNeedCh:'チャネルを1つ以上選択してください',omniCreated:'オムニチャネルキャンペーンを作成しました',omniCreateFail:'作成に失敗しました',omniQueued:'配信キューに登録',omniFirstBatch:'即時処理',omniSendFail:'送信に失敗しました',omniChTitle:'連携チャネルの状態',omniChSub:'認証情報を登録すると、そのチャネルで即時に実配信されます（未設定チャネルは次のチャネルへ自動フォールバック）。',omniLive:'ライブ',omniFallback:'フォールバック可',omniUnset:'未設定',omniNew:'新規オムニチャネルキャンペーン',omniName:'キャンペーン名',omniNamePh:'例）6月VIP再購入促進',omniSeg:'対象セグメント',omniAllCust:'全顧客',omniWaterfall:'チャネル優先順位（上位が未到達/未設定なら次のチャネルへフォールバック）',omniEmailSubj:'メール件名',omniEmailSubjPh:'例）{{name}}様への特別オファー',omniKakaoTpl:'カカオテンプレートコード',omniKakaoTplPh:'承認済みアラームトークのテンプレートコード',omniBody:'メッセージ本文（全チャネル共通・{{name}}置換）',omniBodyPh:'{{name}}様、今週だけの特別割引中です！',omniAlsoPush:'Webプッシュ同時送信（購読者全員）',omniCreate:'キャンペーン作成',omniList:'オムニチャネルキャンペーン',omniEmpty:'作成されたキャンペーンはありません',omniTotal:'対象',omniSent:'送信',omniSkipped:'スキップ',omniFailed:'失敗',omniProgress:'進捗',omniByCh:'チャネル別',omniSend:'送信'},
  zh:{tabOmni:'全渠道',omniNeedName:'请输入活动名称',omniNeedCh:'请至少选择一个渠道',omniCreated:'已创建全渠道活动',omniCreateFail:'创建失败',omniQueued:'已加入发送队列',omniFirstBatch:'即时处理',omniSendFail:'发送失败',omniChTitle:'已连接渠道状态',omniChSub:'注册凭证后将立即通过该渠道实际发送（未设置的渠道会自动回退到下一个渠道）。',omniLive:'已上线',omniFallback:'可回退',omniUnset:'未设置',omniNew:'新建全渠道活动',omniName:'活动名称',omniNamePh:'例）6月VIP复购促进',omniSeg:'目标分群',omniAllCust:'全部客户',omniWaterfall:'渠道优先级（上层渠道无法触达/未设置时回退到下一渠道）',omniEmailSubj:'邮件主题',omniEmailSubjPh:'例）{{name}}，为您准备的专属优惠',omniKakaoTpl:'Kakao模板代码',omniKakaoTplPh:'已审核的AlimTalk模板代码',omniBody:'消息正文（全渠道通用·{{name}}替换）',omniBodyPh:'{{name}}，仅限本周的特别折扣进行中！',omniAlsoPush:'同时发送网页推送（全部订阅者）',omniCreate:'创建活动',omniList:'全渠道活动',omniEmpty:'暂无活动',omniTotal:'目标',omniSent:'已发送',omniSkipped:'已跳过',omniFailed:'失败',omniProgress:'进度',omniByCh:'按渠道',omniSend:'发送'},
  'zh-TW':{tabOmni:'全通路',omniNeedName:'請輸入活動名稱',omniNeedCh:'請至少選擇一個通路',omniCreated:'已建立全通路活動',omniCreateFail:'建立失敗',omniQueued:'已加入發送佇列',omniFirstBatch:'即時處理',omniSendFail:'發送失敗',omniChTitle:'已連接通路狀態',omniChSub:'註冊憑證後將立即透過該通路實際發送（未設定的通路會自動回退到下一個通路）。',omniLive:'已上線',omniFallback:'可回退',omniUnset:'未設定',omniNew:'新增全通路活動',omniName:'活動名稱',omniNamePh:'例）6月VIP回購促進',omniSeg:'目標分眾',omniAllCust:'全部客戶',omniWaterfall:'通路優先順序（上層通路無法觸及/未設定時回退到下一通路）',omniEmailSubj:'郵件主旨',omniEmailSubjPh:'例）{{name}}，為您準備的專屬優惠',omniKakaoTpl:'Kakao範本代碼',omniKakaoTplPh:'已審核的AlimTalk範本代碼',omniBody:'訊息內文（全通路通用·{{name}}替換）',omniBodyPh:'{{name}}，僅限本週的特別折扣進行中！',omniAlsoPush:'同時發送網頁推播（全部訂閱者）',omniCreate:'建立活動',omniList:'全通路活動',omniEmpty:'尚無活動',omniTotal:'目標',omniSent:'已發送',omniSkipped:'已略過',omniFailed:'失敗',omniProgress:'進度',omniByCh:'依通路',omniSend:'發送'},
  de:{tabOmni:'Omnichannel',omniNeedName:'Kampagnennamen eingeben',omniNeedCh:'Mindestens einen Kanal auswählen',omniCreated:'Omnichannel-Kampagne erstellt',omniCreateFail:'Erstellung fehlgeschlagen',omniQueued:'Zur Zustellung eingereiht',omniFirstBatch:'sofort',omniSendFail:'Senden fehlgeschlagen',omniChTitle:'Status verbundener Kanäle',omniChSub:'Sobald die Zugangsdaten registriert sind, erfolgt der Versand sofort über diesen Kanal (nicht eingerichtete Kanäle fallen automatisch auf den nächsten zurück).',omniLive:'Live',omniFallback:'Fallback bereit',omniUnset:'Nicht gesetzt',omniNew:'Neue Omnichannel-Kampagne',omniName:'Kampagnenname',omniNamePh:'z. B. Juni-VIP-Wiederkauf',omniSeg:'Zielsegment',omniAllCust:'Alle Kunden',omniWaterfall:'Kanalpriorität (fällt auf den nächsten Kanal zurück, wenn nicht erreichbar/nicht gesetzt)',omniEmailSubj:'E-Mail-Betreff',omniEmailSubjPh:'z. B. {{name}}, ein besonderes Angebot für Sie',omniKakaoTpl:'Kakao-Vorlagencode',omniKakaoTplPh:'Genehmigter AlimTalk-Vorlagencode',omniBody:'Nachrichtentext (kanalübergreifend · {{name}}-Ersetzung)',omniBodyPh:'{{name}}, nur diese Woche Sonderrabatt!',omniAlsoPush:'Auch Web-Push senden (alle Abonnenten)',omniCreate:'Kampagne erstellen',omniList:'Omnichannel-Kampagnen',omniEmpty:'Noch keine Kampagnen',omniTotal:'Ziel',omniSent:'Gesendet',omniSkipped:'Übersprungen',omniFailed:'Fehlgeschlagen',omniProgress:'Fortschritt',omniByCh:'Nach Kanal',omniSend:'Senden'},
  th:{tabOmni:'ออมนิแชนเนล',omniNeedName:'กรุณากรอกชื่อแคมเปญ',omniNeedCh:'เลือกอย่างน้อยหนึ่งช่องทาง',omniCreated:'สร้างแคมเปญออมนิแชนเนลแล้ว',omniCreateFail:'สร้างไม่สำเร็จ',omniQueued:'เข้าคิวส่งแล้ว',omniFirstBatch:'ประมวลผลทันที',omniSendFail:'ส่งไม่สำเร็จ',omniChTitle:'สถานะช่องทางที่เชื่อมต่อ',omniChSub:'เมื่อลงทะเบียนข้อมูลรับรองแล้ว จะส่งจริงผ่านช่องทางนั้นทันที (ช่องทางที่ยังไม่ตั้งค่าจะถอยไปช่องทางถัดไปอัตโนมัติ)',omniLive:'พร้อมใช้งาน',omniFallback:'สำรองได้',omniUnset:'ยังไม่ตั้งค่า',omniNew:'แคมเปญออมนิแชนเนลใหม่',omniName:'ชื่อแคมเปญ',omniNamePh:'เช่น กระตุ้นการซื้อซ้ำ VIP เดือนมิ.ย.',omniSeg:'กลุ่มเป้าหมาย',omniAllCust:'ลูกค้าทั้งหมด',omniWaterfall:'ลำดับช่องทาง (ถอยไปช่องทางถัดไปเมื่อเข้าถึงไม่ได้/ยังไม่ตั้งค่า)',omniEmailSubj:'หัวข้ออีเมล',omniEmailSubjPh:'เช่น {{name}} ข้อเสนอพิเศษสำหรับคุณ',omniKakaoTpl:'รหัสเทมเพลต Kakao',omniKakaoTplPh:'รหัสเทมเพลต AlimTalk ที่อนุมัติแล้ว',omniBody:'เนื้อหาข้อความ (ใช้ร่วมทุกช่องทาง · แทนที่ {{name}})',omniBodyPh:'{{name}} ส่วนลดพิเศษเฉพาะสัปดาห์นี้เท่านั้น!',omniAlsoPush:'ส่งเว็บพุชพร้อมกัน (ผู้ติดตามทั้งหมด)',omniCreate:'สร้างแคมเปญ',omniList:'แคมเปญออมนิแชนเนล',omniEmpty:'ยังไม่มีแคมเปญ',omniTotal:'เป้าหมาย',omniSent:'ส่งแล้ว',omniSkipped:'ข้าม',omniFailed:'ล้มเหลว',omniProgress:'ความคืบหน้า',omniByCh:'ตามช่องทาง',omniSend:'ส่ง'},
  vi:{tabOmni:'Đa kênh',omniNeedName:'Nhập tên chiến dịch',omniNeedCh:'Chọn ít nhất một kênh',omniCreated:'Đã tạo chiến dịch đa kênh',omniCreateFail:'Tạo thất bại',omniQueued:'Đã đưa vào hàng đợi gửi',omniFirstBatch:'xử lý ngay',omniSendFail:'Gửi thất bại',omniChTitle:'Trạng thái kênh đã kết nối',omniChSub:'Sau khi đăng ký thông tin xác thực, việc gửi sẽ diễn ra ngay trên kênh đó (kênh chưa thiết lập sẽ tự động chuyển sang kênh tiếp theo).',omniLive:'Hoạt động',omniFallback:'Sẵn sàng dự phòng',omniUnset:'Chưa thiết lập',omniNew:'Chiến dịch đa kênh mới',omniName:'Tên chiến dịch',omniNamePh:'VD) Thúc đẩy mua lại VIP tháng 6',omniSeg:'Phân khúc mục tiêu',omniAllCust:'Tất cả khách hàng',omniWaterfall:'Ưu tiên kênh (chuyển sang kênh kế tiếp nếu không tiếp cận được/chưa thiết lập)',omniEmailSubj:'Tiêu đề email',omniEmailSubjPh:'VD) {{name}}, ưu đãi đặc biệt dành cho bạn',omniKakaoTpl:'Mã mẫu Kakao',omniKakaoTplPh:'Mã mẫu AlimTalk đã được duyệt',omniBody:'Nội dung tin nhắn (dùng chung mọi kênh · thay {{name}})',omniBodyPh:'{{name}}, giảm giá đặc biệt chỉ trong tuần này!',omniAlsoPush:'Đồng thời gửi web push (tất cả người đăng ký)',omniCreate:'Tạo chiến dịch',omniList:'Chiến dịch đa kênh',omniEmpty:'Chưa có chiến dịch',omniTotal:'Mục tiêu',omniSent:'Đã gửi',omniSkipped:'Đã bỏ qua',omniFailed:'Thất bại',omniProgress:'Tiến độ',omniByCh:'Theo kênh',omniSend:'Gửi'},
  id:{tabOmni:'Omnichannel',omniNeedName:'Masukkan nama kampanye',omniNeedCh:'Pilih minimal satu saluran',omniCreated:'Kampanye omnichannel dibuat',omniCreateFail:'Gagal membuat',omniQueued:'Masuk antrean pengiriman',omniFirstBatch:'instan',omniSendFail:'Gagal mengirim',omniChTitle:'Status saluran terhubung',omniChSub:'Setelah kredensial didaftarkan, pengiriman langsung berjalan di saluran itu (saluran yang belum diatur otomatis beralih ke saluran berikutnya).',omniLive:'Aktif',omniFallback:'Siap fallback',omniUnset:'Belum diatur',omniNew:'Kampanye omnichannel baru',omniName:'Nama kampanye',omniNamePh:'mis. Dorongan pembelian ulang VIP Juni',omniSeg:'Segmen target',omniAllCust:'Semua pelanggan',omniWaterfall:'Prioritas saluran (beralih ke saluran berikutnya jika tak terjangkau/belum diatur)',omniEmailSubj:'Subjek email',omniEmailSubjPh:'mis. {{name}}, penawaran khusus untuk Anda',omniKakaoTpl:'Kode templat Kakao',omniKakaoTplPh:'Kode templat AlimTalk yang disetujui',omniBody:'Isi pesan (umum lintas saluran · ganti {{name}})',omniBodyPh:'{{name}}, diskon khusus minggu ini saja!',omniAlsoPush:'Kirim juga web push (semua pelanggan)',omniCreate:'Buat kampanye',omniList:'Kampanye omnichannel',omniEmpty:'Belum ada kampanye',omniTotal:'Target',omniSent:'Terkirim',omniSkipped:'Dilewati',omniFailed:'Gagal',omniProgress:'Progres',omniByCh:'Per saluran',omniSend:'Kirim'},
  ar:{tabOmni:'القنوات الشاملة',omniNeedName:'أدخل اسم الحملة',omniNeedCh:'اختر قناة واحدة على الأقل',omniCreated:'تم إنشاء حملة القنوات الشاملة',omniCreateFail:'فشل الإنشاء',omniQueued:'في قائمة انتظار الإرسال',omniFirstBatch:'فوري',omniSendFail:'فشل الإرسال',omniChTitle:'حالة القنوات المتصلة',omniChSub:'بمجرد تسجيل بيانات الاعتماد، يبدأ الإرسال فورًا عبر تلك القناة (تنتقل القنوات غير المُعدّة تلقائيًا إلى القناة التالية).',omniLive:'نشط',omniFallback:'احتياطي جاهز',omniUnset:'غير مُعد',omniNew:'حملة قنوات شاملة جديدة',omniName:'اسم الحملة',omniNamePh:'مثال) تحفيز إعادة شراء VIP في يونيو',omniSeg:'الشريحة المستهدفة',omniAllCust:'جميع العملاء',omniWaterfall:'أولوية القنوات (تنتقل إلى القناة التالية إذا تعذّر الوصول/غير مُعدّة)',omniEmailSubj:'موضوع البريد',omniEmailSubjPh:'مثال) {{name}}، عرض خاص لك',omniKakaoTpl:'رمز قالب كاكاو',omniKakaoTplPh:'رمز قالب AlimTalk المعتمد',omniBody:'نص الرسالة (مشترك بين القنوات · استبدال {{name}})',omniBodyPh:'{{name}}، خصم خاص هذا الأسبوع فقط!',omniAlsoPush:'إرسال إشعار ويب أيضًا (جميع المشتركين)',omniCreate:'إنشاء حملة',omniList:'حملات القنوات الشاملة',omniEmpty:'لا توجد حملات بعد',omniTotal:'المستهدف',omniSent:'مُرسل',omniSkipped:'متخطّى',omniFailed:'فشل',omniProgress:'التقدم',omniByCh:'حسب القناة',omniSend:'إرسال'},
  es:{tabOmni:'Omnicanal',omniNeedName:'Introduce un nombre de campaña',omniNeedCh:'Selecciona al menos un canal',omniCreated:'Campaña omnicanal creada',omniCreateFail:'Error al crear',omniQueued:'En cola para envío',omniFirstBatch:'instantáneo',omniSendFail:'Error al enviar',omniChTitle:'Estado de canales conectados',omniChSub:'Una vez registradas las credenciales, el envío comienza de inmediato en ese canal (los canales sin configurar pasan automáticamente al siguiente).',omniLive:'Activo',omniFallback:'Respaldo listo',omniUnset:'Sin configurar',omniNew:'Nueva campaña omnicanal',omniName:'Nombre de campaña',omniNamePh:'p. ej. Recompra VIP de junio',omniSeg:'Segmento objetivo',omniAllCust:'Todos los clientes',omniWaterfall:'Prioridad de canal (pasa al siguiente canal si no es alcanzable/sin configurar)',omniEmailSubj:'Asunto del correo',omniEmailSubjPh:'p. ej. {{name}}, una oferta especial para ti',omniKakaoTpl:'Código de plantilla Kakao',omniKakaoTplPh:'Código de plantilla AlimTalk aprobado',omniBody:'Cuerpo del mensaje (común a todos los canales · sustituye {{name}})',omniBodyPh:'{{name}}, ¡descuento especial solo esta semana!',omniAlsoPush:'Enviar también push web (todos los suscriptores)',omniCreate:'Crear campaña',omniList:'Campañas omnicanal',omniEmpty:'Aún no hay campañas',omniTotal:'Objetivo',omniSent:'Enviado',omniSkipped:'Omitido',omniFailed:'Fallido',omniProgress:'Progreso',omniByCh:'Por canal',omniSend:'Enviar'},
  fr:{tabOmni:'Omnicanal',omniNeedName:'Saisissez un nom de campagne',omniNeedCh:'Sélectionnez au moins un canal',omniCreated:'Campagne omnicanale créée',omniCreateFail:'Échec de la création',omniQueued:'En file d\'attente d\'envoi',omniFirstBatch:'instantané',omniSendFail:'Échec de l\'envoi',omniChTitle:'État des canaux connectés',omniChSub:'Une fois les identifiants enregistrés, l\'envoi démarre immédiatement sur ce canal (les canaux non configurés basculent automatiquement vers le suivant).',omniLive:'Actif',omniFallback:'Repli prêt',omniUnset:'Non configuré',omniNew:'Nouvelle campagne omnicanale',omniName:'Nom de la campagne',omniNamePh:'ex. Relance rachat VIP de juin',omniSeg:'Segment cible',omniAllCust:'Tous les clients',omniWaterfall:'Priorité des canaux (bascule vers le canal suivant si injoignable/non configuré)',omniEmailSubj:'Objet de l\'e-mail',omniEmailSubjPh:'ex. {{name}}, une offre spéciale pour vous',omniKakaoTpl:'Code de modèle Kakao',omniKakaoTplPh:'Code de modèle AlimTalk approuvé',omniBody:'Corps du message (commun à tous les canaux · remplacement {{name}})',omniBodyPh:'{{name}}, remise spéciale cette semaine seulement !',omniAlsoPush:'Envoyer aussi une notification web (tous les abonnés)',omniCreate:'Créer la campagne',omniList:'Campagnes omnicanales',omniEmpty:'Aucune campagne pour le moment',omniTotal:'Cible',omniSent:'Envoyé',omniSkipped:'Ignoré',omniFailed:'Échec',omniProgress:'Progression',omniByCh:'Par canal',omniSend:'Envoyer'},
  hi:{tabOmni:'ऑम्नीचैनल',omniNeedName:'अभियान का नाम दर्ज करें',omniNeedCh:'कम से कम एक चैनल चुनें',omniCreated:'ऑम्नीचैनल अभियान बनाया गया',omniCreateFail:'बनाने में विफल',omniQueued:'भेजने के लिए कतार में',omniFirstBatch:'तत्काल',omniSendFail:'भेजने में विफल',omniChTitle:'कनेक्टेड चैनल स्थिति',omniChSub:'क्रेडेंशियल पंजीकृत करते ही उस चैनल पर तुरंत वास्तविक भेजना शुरू हो जाता है (बिना सेट किए चैनल स्वतः अगले चैनल पर चले जाते हैं)।',omniLive:'लाइव',omniFallback:'फ़ॉलबैक तैयार',omniUnset:'सेट नहीं',omniNew:'नया ऑम्नीचैनल अभियान',omniName:'अभियान का नाम',omniNamePh:'उदा. जून VIP पुनः खरीद प्रोत्साहन',omniSeg:'लक्ष्य सेगमेंट',omniAllCust:'सभी ग्राहक',omniWaterfall:'चैनल प्राथमिकता (पहुँच न होने/सेट न होने पर अगले चैनल पर फ़ॉलबैक)',omniEmailSubj:'ईमेल विषय',omniEmailSubjPh:'उदा. {{name}}, आपके लिए विशेष ऑफ़र',omniKakaoTpl:'काकाओ टेम्पलेट कोड',omniKakaoTplPh:'अनुमोदित AlimTalk टेम्पलेट कोड',omniBody:'संदेश मुख्य भाग (सभी चैनलों में समान · {{name}} प्रतिस्थापन)',omniBodyPh:'{{name}}, केवल इस सप्ताह विशेष छूट!',omniAlsoPush:'वेब पुश भी भेजें (सभी सब्सक्राइबर)',omniCreate:'अभियान बनाएँ',omniList:'ऑम्नीचैनल अभियान',omniEmpty:'अभी कोई अभियान नहीं',omniTotal:'लक्ष्य',omniSent:'भेजा गया',omniSkipped:'छोड़ा गया',omniFailed:'विफल',omniProgress:'प्रगति',omniByCh:'चैनल अनुसार',omniSend:'भेजें'},
  pt:{tabOmni:'Omnicanal',omniNeedName:'Insira um nome de campanha',omniNeedCh:'Selecione pelo menos um canal',omniCreated:'Campanha omnicanal criada',omniCreateFail:'Falha ao criar',omniQueued:'Na fila para envio',omniFirstBatch:'instantâneo',omniSendFail:'Falha ao enviar',omniChTitle:'Status dos canais conectados',omniChSub:'Após registrar as credenciais, o envio começa imediatamente nesse canal (canais não configurados recorrem automaticamente ao próximo).',omniLive:'Ativo',omniFallback:'Fallback pronto',omniUnset:'Não configurado',omniNew:'Nova campanha omnicanal',omniName:'Nome da campanha',omniNamePh:'ex. Recompra VIP de junho',omniSeg:'Segmento-alvo',omniAllCust:'Todos os clientes',omniWaterfall:'Prioridade de canal (recorre ao próximo canal se inacessível/não configurado)',omniEmailSubj:'Assunto do e-mail',omniEmailSubjPh:'ex. {{name}}, uma oferta especial para você',omniKakaoTpl:'Código de modelo Kakao',omniKakaoTplPh:'Código de modelo AlimTalk aprovado',omniBody:'Corpo da mensagem (comum a todos os canais · substituição {{name}})',omniBodyPh:'{{name}}, desconto especial só esta semana!',omniAlsoPush:'Enviar também push web (todos os assinantes)',omniCreate:'Criar campanha',omniList:'Campanhas omnicanais',omniEmpty:'Nenhuma campanha ainda',omniTotal:'Alvo',omniSent:'Enviado',omniSkipped:'Ignorado',omniFailed:'Falhou',omniProgress:'Progresso',omniByCh:'Por canal',omniSend:'Enviar'},
  ru:{tabOmni:'Омниканальность',omniNeedName:'Введите название кампании',omniNeedCh:'Выберите хотя бы один канал',omniCreated:'Омниканальная кампания создана',omniCreateFail:'Ошибка создания',omniQueued:'В очереди на отправку',omniFirstBatch:'мгновенно',omniSendFail:'Ошибка отправки',omniChTitle:'Статус подключённых каналов',omniChSub:'После регистрации учётных данных отправка начинается немедленно по этому каналу (ненастроенные каналы автоматически переходят к следующему).',omniLive:'Активен',omniFallback:'Резерв готов',omniUnset:'Не задан',omniNew:'Новая омниканальная кампания',omniName:'Название кампании',omniNamePh:'напр. Стимулирование повторных покупок VIP в июне',omniSeg:'Целевой сегмент',omniAllCust:'Все клиенты',omniWaterfall:'Приоритет каналов (переход к следующему каналу, если недоступен/не настроен)',omniEmailSubj:'Тема письма',omniEmailSubjPh:'напр. {{name}}, специальное предложение для вас',omniKakaoTpl:'Код шаблона Kakao',omniKakaoTplPh:'Утверждённый код шаблона AlimTalk',omniBody:'Текст сообщения (общий для всех каналов · подстановка {{name}})',omniBodyPh:'{{name}}, специальная скидка только на этой неделе!',omniAlsoPush:'Также отправить веб-push (всем подписчикам)',omniCreate:'Создать кампанию',omniList:'Омниканальные кампании',omniEmpty:'Кампаний пока нет',omniTotal:'Цель',omniSent:'Отправлено',omniSkipped:'Пропущено',omniFailed:'Ошибка',omniProgress:'Прогресс',omniByCh:'По каналам',omniSend:'Отправить'},
};

const ALL = Object.assign({ ko: KO }, TR);
function findLastTopProp(o, name) { let f = null; for (const p of o.properties) { if (p.type !== 'Property') continue; const k = p.key.type === 'Identifier' ? p.key.name : p.key.value; if (k === name) f = p; } return f; }
function existing(o) { const s = new Set(); for (const p of o.properties) { if (p.type !== 'Property') continue; s.add(p.key.type === 'Identifier' ? p.key.name : p.key.value); } return s; }

const LANGS = ['ko','en','ja','zh','zh-TW','de','th','vi','id','ar','es','fr','hi','pt','ru'];
const summary = [];
for (const lang of LANGS) {
  const file = path.join(LOCDIR, lang + '.js');
  let src = fs.readFileSync(file, 'utf8');
  const tr = ALL[lang]; if (!tr) { console.error(`${lang}: no table`); process.exit(2); }
  const ast = parse(src, { ecmaVersion: 'latest', sourceType: 'module' });
  let root = null; for (const b of ast.body) if (b.type === 'ExportDefaultDeclaration') root = b.declaration;
  const ns = findLastTopProp(root, 'crm');
  if (!ns || ns.value.type !== 'ObjectExpression') { console.error(`${lang}: no top-level crm ns`); process.exit(2); }
  const have = existing(ns.value);
  const toAdd = Object.keys(tr).filter(k => !have.has(k));
  if (!toAdd.length) { summary.push(`${lang}: +0 (skip)`); continue; }
  const props = ns.value.properties; const last = props[props.length - 1];
  let ins = ''; for (const k of toAdd) ins += `, ${JSON.stringify(k)}: ${JSON.stringify(tr[k])}`;
  src = src.slice(0, last.end) + ins + src.slice(last.end);
  parse(src, { ecmaVersion: 'latest', sourceType: 'module' });
  fs.writeFileSync(file, src, 'utf8');
  summary.push(`${lang}: +${toAdd.length}`);
}
console.log(summary.join('\n'));
