#!/usr/bin/env node
/** 홀드아웃 실험 레지스트리 라벨 attrData.exp 9키 15개국 주입. acorn splice, 멱등. */
const fs = require('fs'); const path = require('path'); const { parse } = require('acorn');
const LOCDIR = path.join(__dirname, '..', 'frontend', 'src', 'i18n', 'locales');
const NS = 'attrData';
const KEYS = ['expTitle','expDesc','expName','expChannel','expHypo','expCreate','expNone','expConclude','expDelConfirm'];
const T = {
  ko: { expTitle:'홀드아웃 실험 관리', expDesc:'플랫폼측 conversion-lift 실험(Meta Conversion Lift·Google 지역실험 등)을 등록하고, 결과 입력 시 통계 검정으로 증분성을 자동 검증·추적합니다.', expName:'실험명', expChannel:'채널(예: meta)', expHypo:'가설(선택)', expCreate:'실험 등록', expNone:'등록된 실험이 없습니다.', expConclude:'결과 입력·검정', expDelConfirm:'이 실험을 삭제하시겠습니까?' },
  en: { expTitle:'Holdout experiments', expDesc:'Register platform-side conversion-lift experiments (Meta Conversion Lift, Google geo experiments, etc.); on entering results, incrementality is auto-validated and tracked via statistical testing.', expName:'Experiment name', expChannel:'Channel (e.g. meta)', expHypo:'Hypothesis (optional)', expCreate:'Register experiment', expNone:'No experiments registered.', expConclude:'Enter results · test', expDelConfirm:'Delete this experiment?' },
  ja: { expTitle:'ホールドアウト実験管理', expDesc:'プラットフォーム側のコンバージョンリフト実験（Meta Conversion Lift・Google地域実験など）を登録し、結果入力時に統計検定で増分性を自動検証・追跡します。', expName:'実験名', expChannel:'チャネル（例: meta）', expHypo:'仮説（任意）', expCreate:'実験を登録', expNone:'登録された実験がありません。', expConclude:'結果入力・検定', expDelConfirm:'この実験を削除しますか？' },
  zh: { expTitle:'留出实验管理', expDesc:'登记平台侧转化提升实验（Meta Conversion Lift·Google地区实验等），输入结果后通过统计检验自动验证并追踪增量性。', expName:'实验名称', expChannel:'渠道(如 meta)', expHypo:'假设(可选)', expCreate:'登记实验', expNone:'暂无已登记实验。', expConclude:'输入结果·检验', expDelConfirm:'确定删除此实验吗？' },
  'zh-TW': { expTitle:'保留組實驗管理', expDesc:'登記平台側轉換提升實驗（Meta Conversion Lift·Google地區實驗等），輸入結果後透過統計檢定自動驗證並追蹤增量性。', expName:'實驗名稱', expChannel:'通路(如 meta)', expHypo:'假設(選填)', expCreate:'登記實驗', expNone:'尚無已登記實驗。', expConclude:'輸入結果·檢定', expDelConfirm:'確定刪除此實驗嗎？' },
  de: { expTitle:'Holdout-Experimente', expDesc:'Registrieren Sie plattformseitige Conversion-Lift-Experimente (Meta Conversion Lift, Google-Geo-Experimente usw.); bei Ergebniseingabe wird die Inkrementalität per statistischem Test automatisch validiert und verfolgt.', expName:'Experimentname', expChannel:'Kanal (z. B. meta)', expHypo:'Hypothese (optional)', expCreate:'Experiment registrieren', expNone:'Keine Experimente registriert.', expConclude:'Ergebnisse eingeben · testen', expDelConfirm:'Dieses Experiment löschen?' },
  th: { expTitle:'จัดการการทดลองโฮลด์เอาต์', expDesc:'ลงทะเบียนการทดลอง conversion-lift ฝั่งแพลตฟอร์ม (Meta Conversion Lift·การทดลองตามภูมิภาคของ Google ฯลฯ) เมื่อกรอกผลจะตรวจสอบและติดตามส่วนเพิ่มอัตโนมัติด้วยการทดสอบทางสถิติ', expName:'ชื่อการทดลอง', expChannel:'ช่องทาง (เช่น meta)', expHypo:'สมมติฐาน (ไม่บังคับ)', expCreate:'ลงทะเบียนการทดลอง', expNone:'ยังไม่มีการทดลองที่ลงทะเบียน', expConclude:'กรอกผล·ทดสอบ', expDelConfirm:'ลบการทดลองนี้หรือไม่?' },
  vi: { expTitle:'Quản lý thử nghiệm holdout', expDesc:'Đăng ký các thử nghiệm conversion-lift phía nền tảng (Meta Conversion Lift, thử nghiệm theo vùng của Google, v.v.); khi nhập kết quả, tính gia tăng được tự động kiểm định và theo dõi bằng kiểm định thống kê.', expName:'Tên thử nghiệm', expChannel:'Kênh (vd: meta)', expHypo:'Giả thuyết (tùy chọn)', expCreate:'Đăng ký thử nghiệm', expNone:'Chưa có thử nghiệm nào.', expConclude:'Nhập kết quả · kiểm định', expDelConfirm:'Xóa thử nghiệm này?' },
  id: { expTitle:'Manajemen eksperimen holdout', expDesc:'Daftarkan eksperimen conversion-lift sisi platform (Meta Conversion Lift, eksperimen geo Google, dll.); saat memasukkan hasil, inkrementalitas otomatis divalidasi dan dilacak melalui uji statistik.', expName:'Nama eksperimen', expChannel:'Kanal (mis. meta)', expHypo:'Hipotesis (opsional)', expCreate:'Daftarkan eksperimen', expNone:'Belum ada eksperimen.', expConclude:'Masukkan hasil · uji', expDelConfirm:'Hapus eksperimen ini?' },
  ar: { expTitle:'إدارة تجارب الاحتجاز', expDesc:'سجّل تجارب رفع التحويل على مستوى المنصة (Meta Conversion Lift·تجارب Google الجغرافية وغيرها)؛ وعند إدخال النتائج يتم التحقق من الأثر الإضافي وتتبعه تلقائيًا عبر الاختبار الإحصائي.', expName:'اسم التجربة', expChannel:'القناة (مثل meta)', expHypo:'الفرضية (اختياري)', expCreate:'تسجيل التجربة', expNone:'لا توجد تجارب مسجلة.', expConclude:'إدخال النتائج · اختبار', expDelConfirm:'حذف هذه التجربة؟' },
  es: { expTitle:'Gestión de experimentos holdout', expDesc:'Registra experimentos de conversion-lift del lado de la plataforma (Meta Conversion Lift, experimentos geográficos de Google, etc.); al introducir resultados, la incrementalidad se valida y rastrea automáticamente mediante pruebas estadísticas.', expName:'Nombre del experimento', expChannel:'Canal (p. ej. meta)', expHypo:'Hipótesis (opcional)', expCreate:'Registrar experimento', expNone:'No hay experimentos registrados.', expConclude:'Introducir resultados · probar', expDelConfirm:'¿Eliminar este experimento?' },
  fr: { expTitle:'Gestion des expériences holdout', expDesc:'Enregistrez des expériences de conversion-lift côté plateforme (Meta Conversion Lift, expériences géographiques Google, etc.) ; à la saisie des résultats, l’incrémentalité est validée et suivie automatiquement via un test statistique.', expName:'Nom de l’expérience', expChannel:'Canal (ex. meta)', expHypo:'Hypothèse (facultatif)', expCreate:'Enregistrer l’expérience', expNone:'Aucune expérience enregistrée.', expConclude:'Saisir les résultats · tester', expDelConfirm:'Supprimer cette expérience ?' },
  hi: { expTitle:'होल्डआउट प्रयोग प्रबंधन', expDesc:'प्लेटफ़ॉर्म-साइड conversion-lift प्रयोग (Meta Conversion Lift·Google भौगोलिक प्रयोग आदि) पंजीकृत करें; परिणाम दर्ज करने पर सांख्यिकीय परीक्षण द्वारा वृद्धिशीलता स्वतः सत्यापित व ट्रैक होती है।', expName:'प्रयोग नाम', expChannel:'चैनल (जैसे meta)', expHypo:'परिकल्पना (वैकल्पिक)', expCreate:'प्रयोग पंजीकृत करें', expNone:'कोई प्रयोग पंजीकृत नहीं।', expConclude:'परिणाम दर्ज·परीक्षण', expDelConfirm:'क्या यह प्रयोग हटाएँ?' },
  pt: { expTitle:'Gestão de experimentos holdout', expDesc:'Registre experimentos de conversion-lift do lado da plataforma (Meta Conversion Lift, experimentos geográficos do Google, etc.); ao inserir resultados, a incrementalidade é validada e acompanhada automaticamente por teste estatístico.', expName:'Nome do experimento', expChannel:'Canal (ex.: meta)', expHypo:'Hipótese (opcional)', expCreate:'Registrar experimento', expNone:'Nenhum experimento registrado.', expConclude:'Inserir resultados · testar', expDelConfirm:'Excluir este experimento?' },
  ru: { expTitle:'Управление холдаут-экспериментами', expDesc:'Регистрируйте эксперименты conversion-lift на стороне платформы (Meta Conversion Lift, гео-эксперименты Google и др.); при вводе результатов инкрементальность автоматически проверяется и отслеживается статистическим тестом.', expName:'Название эксперимента', expChannel:'Канал (напр. meta)', expHypo:'Гипотеза (необязательно)', expCreate:'Зарегистрировать эксперимент', expNone:'Нет зарегистрированных экспериментов.', expConclude:'Ввести результаты · тест', expDelConfirm:'Удалить этот эксперимент?' },
};
function findTop(o,n){for(const p of o.properties){if(p.type!=='Property')continue;const k=p.key.type==='Identifier'?p.key.name:p.key.value;if(k===n)return p;}return null;}
function ex(o){const s=new Set();for(const p of o.properties){if(p.type!=='Property')continue;s.add(p.key.type==='Identifier'?p.key.name:p.key.value);}return s;}
let sum=[];
for(const [lang,tr] of Object.entries(T)){
  const file=path.join(LOCDIR,lang+'.js'); let src=fs.readFileSync(file,'utf8');
  const ast=parse(src,{ecmaVersion:'latest',sourceType:'module'}); let root=null;
  for(const b of ast.body)if(b.type==='ExportDefaultDeclaration')root=b.declaration;
  const ns=findTop(root,NS); if(!ns||ns.value.type!=='ObjectExpression'){console.error(lang+': no '+NS);process.exit(2);}
  const have=ex(ns.value); const toAdd=KEYS.filter(k=>!have.has(k));
  if(!toAdd.length){sum.push(lang+': 0');continue;}
  const props=ns.value.properties; const last=props[props.length-1];
  let ins=''; for(const k of toAdd) ins+=`, ${JSON.stringify(k)}: ${JSON.stringify(tr[k])}`;
  src=src.slice(0,last.end)+ins+src.slice(last.end);
  parse(src,{ecmaVersion:'latest',sourceType:'module'}); fs.writeFileSync(file,src,'utf8');
  sum.push(lang+': +'+toAdd.length);
}
console.log(sum.join('\n'));
