#!/usr/bin/env node
/** 244차 i18n — aiRuleEngine 신규키 + liveCommerce guest 키 15개국 주입. acorn splice, 멱등(기존키 skip). */
const fs = require('fs');
const path = require('path');
const { parse } = require('acorn');
const LOCDIR = path.join(__dirname, '..', 'frontend', 'src', 'i18n', 'locales');

// ── aiRuleEngine 신규 키 ──
const AI = {
  ko: { delConfirm:'이 규칙을 삭제하시겠습니까?', detail:'상세', errName:'규칙 이름을 입력하세요.', evaluated:'평가', kpiTotalRules:'전체 규칙', logsHint:'규칙이 트리거되면 실행 내역이 여기에 기록됩니다.', metric:'메트릭', observed:'관측값', operator:'연산자', ranNow:'평가 완료', ruleNamePh:'예: 저ROAS 채널 알림', target:'대상(채널/SKU)', targetPh:'예: meta, 또는 SKU', threshold:'임계값', triggerCount:'트리거 횟수', triggered:'트리거', createHint:"'규칙 생성' 탭에서 첫 자동화 규칙을 만드세요.", saved:'✅ 규칙이 저장되었습니다.', metric_channel_roas:'채널 ROAS', metric_channel_spend:'채널 지출', metric_channel_conversions:'채널 전환', metric_sku_stock:'SKU 재고', metric_low_stock_count:'저재고 SKU 수', action_alert:'알림', action_webhook:'웹훅 발송', action_pause_channel:'채널 정지', action_reorder:'발주 신호' },
  en: { delConfirm:'Delete this rule?', detail:'Detail', errName:'Enter a rule name.', evaluated:'Evaluated', kpiTotalRules:'Total rules', logsHint:'When a rule triggers, its execution history appears here.', metric:'Metric', observed:'Observed', operator:'Operator', ranNow:'Evaluation complete', ruleNamePh:'e.g. Low-ROAS channel alert', target:'Target (channel/SKU)', targetPh:'e.g. meta, or SKU', threshold:'Threshold', triggerCount:'Trigger count', triggered:'Triggered', createHint:"Create your first automation rule in the 'Create Rule' tab.", saved:'✅ Rule saved.', metric_channel_roas:'Channel ROAS', metric_channel_spend:'Channel spend', metric_channel_conversions:'Channel conversions', metric_sku_stock:'SKU stock', metric_low_stock_count:'Low-stock SKU count', action_alert:'Alert', action_webhook:'Send webhook', action_pause_channel:'Pause channel', action_reorder:'Reorder signal' },
  ja: { delConfirm:'このルールを削除しますか？', detail:'詳細', errName:'ルール名を入力してください。', evaluated:'評価', kpiTotalRules:'全ルール', logsHint:'ルールがトリガーされると実行履歴がここに表示されます。', metric:'メトリクス', observed:'観測値', operator:'演算子', ranNow:'評価完了', ruleNamePh:'例: 低ROASチャネル通知', target:'対象(チャネル/SKU)', targetPh:'例: meta、またはSKU', threshold:'しきい値', triggerCount:'トリガー回数', triggered:'トリガー', createHint:"「ルール作成」タブで最初の自動化ルールを作成しましょう。", saved:'✅ ルールを保存しました。', metric_channel_roas:'チャネルROAS', metric_channel_spend:'チャネル支出', metric_channel_conversions:'チャネルCV', metric_sku_stock:'SKU在庫', metric_low_stock_count:'低在庫SKU数', action_alert:'通知', action_webhook:'Webhook送信', action_pause_channel:'チャネル停止', action_reorder:'発注シグナル' },
  zh: { delConfirm:'确定删除此规则？', detail:'详情', errName:'请输入规则名称。', evaluated:'已评估', kpiTotalRules:'全部规则', logsHint:'规则触发后，执行记录将显示在此。', metric:'指标', observed:'观测值', operator:'运算符', ranNow:'评估完成', ruleNamePh:'例: 低ROAS渠道告警', target:'对象(渠道/SKU)', targetPh:'例: meta，或SKU', threshold:'阈值', triggerCount:'触发次数', triggered:'触发', createHint:"在“创建规则”标签页创建首条自动化规则。", saved:'✅ 规则已保存。', metric_channel_roas:'渠道ROAS', metric_channel_spend:'渠道花费', metric_channel_conversions:'渠道转化', metric_sku_stock:'SKU库存', metric_low_stock_count:'低库存SKU数', action_alert:'告警', action_webhook:'发送Webhook', action_pause_channel:'暂停渠道', action_reorder:'补货信号' },
  'zh-TW': { delConfirm:'確定刪除此規則？', detail:'詳情', errName:'請輸入規則名稱。', evaluated:'已評估', kpiTotalRules:'全部規則', logsHint:'規則觸發後，執行紀錄將顯示於此。', metric:'指標', observed:'觀測值', operator:'運算子', ranNow:'評估完成', ruleNamePh:'例: 低ROAS通路告警', target:'對象(通路/SKU)', targetPh:'例: meta，或SKU', threshold:'閾值', triggerCount:'觸發次數', triggered:'觸發', createHint:"在「建立規則」分頁建立第一條自動化規則。", saved:'✅ 規則已儲存。', metric_channel_roas:'通路ROAS', metric_channel_spend:'通路花費', metric_channel_conversions:'通路轉換', metric_sku_stock:'SKU庫存', metric_low_stock_count:'低庫存SKU數', action_alert:'告警', action_webhook:'發送Webhook', action_pause_channel:'暫停通路', action_reorder:'補貨訊號' },
  de: { delConfirm:'Diese Regel löschen?', detail:'Detail', errName:'Regelnamen eingeben.', evaluated:'Ausgewertet', kpiTotalRules:'Regeln gesamt', logsHint:'Wenn eine Regel auslöst, erscheint hier ihr Ausführungsverlauf.', metric:'Metrik', observed:'Beobachtet', operator:'Operator', ranNow:'Auswertung abgeschlossen', ruleNamePh:'z. B. Niedrig-ROAS-Kanalalarm', target:'Ziel (Kanal/SKU)', targetPh:'z. B. meta oder SKU', threshold:'Schwellenwert', triggerCount:'Auslösungen', triggered:'Ausgelöst', createHint:"Erstellen Sie Ihre erste Automatisierungsregel im Tab „Regel erstellen“.", saved:'✅ Regel gespeichert.', metric_channel_roas:'Kanal-ROAS', metric_channel_spend:'Kanalausgaben', metric_channel_conversions:'Kanal-Conversions', metric_sku_stock:'SKU-Bestand', metric_low_stock_count:'SKUs mit niedrigem Bestand', action_alert:'Alarm', action_webhook:'Webhook senden', action_pause_channel:'Kanal pausieren', action_reorder:'Nachbestell-Signal' },
  th: { delConfirm:'ลบกฎนี้หรือไม่?', detail:'รายละเอียด', errName:'กรุณากรอกชื่อกฎ', evaluated:'ประเมินแล้ว', kpiTotalRules:'กฎทั้งหมด', logsHint:'เมื่อกฎถูกทริกเกอร์ ประวัติการทำงานจะแสดงที่นี่', metric:'เมตริก', observed:'ค่าที่สังเกต', operator:'ตัวดำเนินการ', ranNow:'ประเมินเสร็จสิ้น', ruleNamePh:'เช่น แจ้งเตือนช่องทาง ROAS ต่ำ', target:'เป้าหมาย (ช่องทาง/SKU)', targetPh:'เช่น meta หรือ SKU', threshold:'เกณฑ์', triggerCount:'จำนวนทริกเกอร์', triggered:'ทริกเกอร์', createHint:"สร้างกฎอัตโนมัติแรกของคุณในแท็บ 'สร้างกฎ'", saved:'✅ บันทึกกฎแล้ว', metric_channel_roas:'ROAS ช่องทาง', metric_channel_spend:'ค่าใช้จ่ายช่องทาง', metric_channel_conversions:'คอนเวอร์ชันช่องทาง', metric_sku_stock:'สต็อก SKU', metric_low_stock_count:'จำนวน SKU สต็อกต่ำ', action_alert:'แจ้งเตือน', action_webhook:'ส่ง Webhook', action_pause_channel:'หยุดช่องทาง', action_reorder:'สัญญาณสั่งซื้อ' },
  vi: { delConfirm:'Xóa quy tắc này?', detail:'Chi tiết', errName:'Nhập tên quy tắc.', evaluated:'Đã đánh giá', kpiTotalRules:'Tổng quy tắc', logsHint:'Khi quy tắc kích hoạt, lịch sử thực thi sẽ hiển thị ở đây.', metric:'Chỉ số', observed:'Giá trị quan sát', operator:'Toán tử', ranNow:'Đánh giá hoàn tất', ruleNamePh:'vd: Cảnh báo kênh ROAS thấp', target:'Đối tượng (kênh/SKU)', targetPh:'vd: meta, hoặc SKU', threshold:'Ngưỡng', triggerCount:'Số lần kích hoạt', triggered:'Đã kích hoạt', createHint:"Tạo quy tắc tự động đầu tiên trong tab 'Tạo quy tắc'.", saved:'✅ Đã lưu quy tắc.', metric_channel_roas:'ROAS kênh', metric_channel_spend:'Chi tiêu kênh', metric_channel_conversions:'Chuyển đổi kênh', metric_sku_stock:'Tồn kho SKU', metric_low_stock_count:'Số SKU tồn thấp', action_alert:'Cảnh báo', action_webhook:'Gửi webhook', action_pause_channel:'Tạm dừng kênh', action_reorder:'Tín hiệu đặt hàng' },
  id: { delConfirm:'Hapus aturan ini?', detail:'Detail', errName:'Masukkan nama aturan.', evaluated:'Dievaluasi', kpiTotalRules:'Total aturan', logsHint:'Saat aturan terpicu, riwayat eksekusi muncul di sini.', metric:'Metrik', observed:'Teramati', operator:'Operator', ranNow:'Evaluasi selesai', ruleNamePh:'mis. Peringatan kanal ROAS rendah', target:'Target (kanal/SKU)', targetPh:'mis. meta, atau SKU', threshold:'Ambang', triggerCount:'Jumlah pemicu', triggered:'Terpicu', createHint:"Buat aturan otomatisasi pertama Anda di tab 'Buat Aturan'.", saved:'✅ Aturan disimpan.', metric_channel_roas:'ROAS kanal', metric_channel_spend:'Belanja kanal', metric_channel_conversions:'Konversi kanal', metric_sku_stock:'Stok SKU', metric_low_stock_count:'Jumlah SKU stok rendah', action_alert:'Peringatan', action_webhook:'Kirim webhook', action_pause_channel:'Jeda kanal', action_reorder:'Sinyal pemesanan ulang' },
  ar: { delConfirm:'حذف هذه القاعدة؟', detail:'التفاصيل', errName:'أدخل اسم القاعدة.', evaluated:'تم التقييم', kpiTotalRules:'إجمالي القواعد', logsHint:'عند تشغيل القاعدة، يظهر سجل تنفيذها هنا.', metric:'المقياس', observed:'القيمة المرصودة', operator:'العامل', ranNow:'اكتمل التقييم', ruleNamePh:'مثال: تنبيه قناة منخفضة ROAS', target:'الهدف (قناة/SKU)', targetPh:'مثال: meta أو SKU', threshold:'العتبة', triggerCount:'عدد مرات التشغيل', triggered:'تم التشغيل', createHint:"أنشئ أول قاعدة أتمتة في تبويب «إنشاء قاعدة».", saved:'✅ تم حفظ القاعدة.', metric_channel_roas:'ROAS القناة', metric_channel_spend:'إنفاق القناة', metric_channel_conversions:'تحويلات القناة', metric_sku_stock:'مخزون SKU', metric_low_stock_count:'عدد SKU منخفضة المخزون', action_alert:'تنبيه', action_webhook:'إرسال Webhook', action_pause_channel:'إيقاف القناة', action_reorder:'إشارة إعادة الطلب' },
  es: { delConfirm:'¿Eliminar esta regla?', detail:'Detalle', errName:'Introduce un nombre de regla.', evaluated:'Evaluado', kpiTotalRules:'Reglas totales', logsHint:'Cuando una regla se activa, su historial de ejecución aparece aquí.', metric:'Métrica', observed:'Observado', operator:'Operador', ranNow:'Evaluación completada', ruleNamePh:'ej. Alerta de canal con ROAS bajo', target:'Objetivo (canal/SKU)', targetPh:'ej. meta, o SKU', threshold:'Umbral', triggerCount:'N.º de activaciones', triggered:'Activado', createHint:"Crea tu primera regla de automatización en la pestaña 'Crear regla'.", saved:'✅ Regla guardada.', metric_channel_roas:'ROAS de canal', metric_channel_spend:'Inversión de canal', metric_channel_conversions:'Conversiones de canal', metric_sku_stock:'Stock de SKU', metric_low_stock_count:'N.º de SKU con stock bajo', action_alert:'Alerta', action_webhook:'Enviar webhook', action_pause_channel:'Pausar canal', action_reorder:'Señal de reposición' },
  fr: { delConfirm:'Supprimer cette règle ?', detail:'Détail', errName:'Saisissez un nom de règle.', evaluated:'Évalué', kpiTotalRules:'Total des règles', logsHint:'Lorsqu’une règle se déclenche, son historique d’exécution apparaît ici.', metric:'Métrique', observed:'Observé', operator:'Opérateur', ranNow:'Évaluation terminée', ruleNamePh:'ex. Alerte canal à faible ROAS', target:'Cible (canal/SKU)', targetPh:'ex. meta, ou SKU', threshold:'Seuil', triggerCount:'Nb de déclenchements', triggered:'Déclenché', createHint:"Créez votre première règle d’automatisation dans l’onglet « Créer une règle ».", saved:'✅ Règle enregistrée.', metric_channel_roas:'ROAS du canal', metric_channel_spend:'Dépense du canal', metric_channel_conversions:'Conversions du canal', metric_sku_stock:'Stock SKU', metric_low_stock_count:'Nb de SKU à faible stock', action_alert:'Alerte', action_webhook:'Envoyer un webhook', action_pause_channel:'Mettre le canal en pause', action_reorder:'Signal de réappro' },
  hi: { delConfirm:'इस नियम को हटाएँ?', detail:'विवरण', errName:'नियम का नाम दर्ज करें।', evaluated:'मूल्यांकित', kpiTotalRules:'कुल नियम', logsHint:'जब नियम ट्रिगर होता है, उसका निष्पादन इतिहास यहाँ दिखता है।', metric:'मेट्रिक', observed:'प्रेक्षित', operator:'ऑपरेटर', ranNow:'मूल्यांकन पूर्ण', ruleNamePh:'उदा. कम ROAS चैनल अलर्ट', target:'लक्ष्य (चैनल/SKU)', targetPh:'उदा. meta, या SKU', threshold:'सीमा', triggerCount:'ट्रिगर संख्या', triggered:'ट्रिगर', createHint:"'नियम बनाएँ' टैब में अपना पहला स्वचालन नियम बनाएँ।", saved:'✅ नियम सहेजा गया।', metric_channel_roas:'चैनल ROAS', metric_channel_spend:'चैनल खर्च', metric_channel_conversions:'चैनल रूपांतरण', metric_sku_stock:'SKU स्टॉक', metric_low_stock_count:'कम स्टॉक SKU संख्या', action_alert:'अलर्ट', action_webhook:'वेबहुक भेजें', action_pause_channel:'चैनल रोकें', action_reorder:'पुनः ऑर्डर संकेत' },
  pt: { delConfirm:'Excluir esta regra?', detail:'Detalhe', errName:'Insira um nome de regra.', evaluated:'Avaliado', kpiTotalRules:'Total de regras', logsHint:'Quando uma regra é acionada, seu histórico de execução aparece aqui.', metric:'Métrica', observed:'Observado', operator:'Operador', ranNow:'Avaliação concluída', ruleNamePh:'ex. Alerta de canal com ROAS baixo', target:'Alvo (canal/SKU)', targetPh:'ex. meta, ou SKU', threshold:'Limiar', triggerCount:'Nº de acionamentos', triggered:'Acionado', createHint:"Crie sua primeira regra de automação na aba 'Criar regra'.", saved:'✅ Regra salva.', metric_channel_roas:'ROAS do canal', metric_channel_spend:'Investimento do canal', metric_channel_conversions:'Conversões do canal', metric_sku_stock:'Estoque de SKU', metric_low_stock_count:'Nº de SKU com estoque baixo', action_alert:'Alerta', action_webhook:'Enviar webhook', action_pause_channel:'Pausar canal', action_reorder:'Sinal de reposição' },
  ru: { delConfirm:'Удалить это правило?', detail:'Детали', errName:'Введите название правила.', evaluated:'Оценено', kpiTotalRules:'Всего правил', logsHint:'При срабатывании правила здесь появляется история выполнения.', metric:'Метрика', observed:'Наблюдаемое', operator:'Оператор', ranNow:'Оценка завершена', ruleNamePh:'напр. Оповещение о канале с низким ROAS', target:'Цель (канал/SKU)', targetPh:'напр. meta или SKU', threshold:'Порог', triggerCount:'Число срабатываний', triggered:'Сработало', createHint:"Создайте первое правило автоматизации на вкладке «Создать правило».", saved:'✅ Правило сохранено.', metric_channel_roas:'ROAS канала', metric_channel_spend:'Расходы канала', metric_channel_conversions:'Конверсии канала', metric_sku_stock:'Запас SKU', metric_low_stock_count:'Число SKU с низким запасом', action_alert:'Оповещение', action_webhook:'Отправить вебхук', action_pause_channel:'Приостановить канал', action_reorder:'Сигнал дозаказа' },
};

// ── liveCommerce guest 키 ──
const LC = {
  ko: { tabGuests:'게스트/코호스트', guestCohost:'코호스트', guestDelConfirm:'이 게스트를 삭제하시겠습니까?', guestDesc:'한 방송에 다중 진행자를 초대합니다. 게스트는 발급된 링크로 참여(계정 불요)하고, 발급된 송출키로 외부 미디어서버에 영상을 송출하면 방송에 합성됩니다.', guestGuest:'게스트', guestInvite:'초대', guestInvited:'초대 링크 생성됨 — 게스트에게 공유하세요', guestKick:'퇴장', guestList:'참여 진행자', guestMute:'음소거', guestNamePh:'게스트 이름', guestNone:'초대된 게스트가 없습니다.', guestNoSession:'먼저 방송 세션을 선택하세요.', guestStreamKey:'송출키', guestTitle:'게스트/코호스트 초대', guestUnmute:'해제' },
  en: { tabGuests:'Guests/Co-hosts', guestCohost:'Co-host', guestDelConfirm:'Delete this guest?', guestDesc:'Invite multiple hosts to one broadcast. Guests join via the issued link (no account needed); streaming their video to the external media server with the issued stream key composites them into the broadcast.', guestGuest:'Guest', guestInvite:'Invite', guestInvited:'Invite link created — share it with the guest', guestKick:'Remove', guestList:'Active hosts', guestMute:'Mute', guestNamePh:'Guest name', guestNone:'No guests invited.', guestNoSession:'Select a broadcast session first.', guestStreamKey:'Stream key', guestTitle:'Invite guest/co-host', guestUnmute:'Unmute' },
  ja: { tabGuests:'ゲスト/共同ホスト', guestCohost:'共同ホスト', guestDelConfirm:'このゲストを削除しますか？', guestDesc:'1つの配信に複数の進行役を招待します。ゲストは発行されたリンクで参加でき(アカウント不要)、発行された配信キーで外部メディアサーバーに映像を送ると配信に合成されます。', guestGuest:'ゲスト', guestInvite:'招待', guestInvited:'招待リンクを作成しました — ゲストに共有してください', guestKick:'退出', guestList:'参加中の進行役', guestMute:'ミュート', guestNamePh:'ゲスト名', guestNone:'招待されたゲストはいません。', guestNoSession:'まず配信セッションを選択してください。', guestStreamKey:'配信キー', guestTitle:'ゲスト/共同ホストを招待', guestUnmute:'解除' },
  zh: { tabGuests:'嘉宾/联合主播', guestCohost:'联合主播', guestDelConfirm:'确定删除此嘉宾？', guestDesc:'在一场直播中邀请多位主播。嘉宾通过生成的链接加入(无需账号)，用生成的推流密钥向外部媒体服务器推流即可合成进直播。', guestGuest:'嘉宾', guestInvite:'邀请', guestInvited:'已生成邀请链接 — 请分享给嘉宾', guestKick:'移除', guestList:'在线主播', guestMute:'静音', guestNamePh:'嘉宾姓名', guestNone:'尚未邀请嘉宾。', guestNoSession:'请先选择直播场次。', guestStreamKey:'推流密钥', guestTitle:'邀请嘉宾/联合主播', guestUnmute:'取消静音' },
  'zh-TW': { tabGuests:'來賓/共同主持', guestCohost:'共同主持', guestDelConfirm:'確定刪除此來賓？', guestDesc:'在一場直播中邀請多位主持。來賓透過產生的連結加入(免帳號)，用產生的推流金鑰向外部媒體伺服器推流即可合成進直播。', guestGuest:'來賓', guestInvite:'邀請', guestInvited:'已產生邀請連結 — 請分享給來賓', guestKick:'移除', guestList:'線上主持', guestMute:'靜音', guestNamePh:'來賓名稱', guestNone:'尚未邀請來賓。', guestNoSession:'請先選擇直播場次。', guestStreamKey:'推流金鑰', guestTitle:'邀請來賓/共同主持', guestUnmute:'取消靜音' },
  de: { tabGuests:'Gäste/Co-Hosts', guestCohost:'Co-Host', guestDelConfirm:'Diesen Gast entfernen?', guestDesc:'Laden Sie mehrere Moderatoren zu einer Übertragung ein. Gäste treten über den erstellten Link bei (kein Konto nötig); per ausgegebenem Stream-Key an den externen Medienserver gesendetes Video wird in die Übertragung eingefügt.', guestGuest:'Gast', guestInvite:'Einladen', guestInvited:'Einladungslink erstellt — an den Gast weitergeben', guestKick:'Entfernen', guestList:'Aktive Moderatoren', guestMute:'Stummschalten', guestNamePh:'Gastname', guestNone:'Keine Gäste eingeladen.', guestNoSession:'Wählen Sie zuerst eine Übertragungssitzung.', guestStreamKey:'Stream-Key', guestTitle:'Gast/Co-Host einladen', guestUnmute:'Stummschaltung aufheben' },
  th: { tabGuests:'แขก/ผู้ดำเนินรายการร่วม', guestCohost:'ผู้ดำเนินรายการร่วม', guestDelConfirm:'ลบแขกคนนี้หรือไม่?', guestDesc:'เชิญผู้ดำเนินรายการหลายคนในไลฟ์เดียว แขกเข้าร่วมผ่านลิงก์ที่ออกให้ (ไม่ต้องมีบัญชี) และเมื่อส่งวิดีโอไปยังมีเดียเซิร์ฟเวอร์ภายนอกด้วยคีย์สตรีมที่ออกให้ ก็จะถูกรวมเข้ากับไลฟ์', guestGuest:'แขก', guestInvite:'เชิญ', guestInvited:'สร้างลิงก์เชิญแล้ว — แชร์ให้แขก', guestKick:'นำออก', guestList:'ผู้ดำเนินรายการที่ใช้งาน', guestMute:'ปิดเสียง', guestNamePh:'ชื่อแขก', guestNone:'ยังไม่มีแขกที่เชิญ', guestNoSession:'กรุณาเลือกเซสชันไลฟ์ก่อน', guestStreamKey:'คีย์สตรีม', guestTitle:'เชิญแขก/ผู้ดำเนินรายการร่วม', guestUnmute:'เปิดเสียง' },
  vi: { tabGuests:'Khách/Đồng dẫn', guestCohost:'Đồng dẫn', guestDelConfirm:'Xóa khách này?', guestDesc:'Mời nhiều người dẫn vào một buổi phát. Khách tham gia qua liên kết được cấp (không cần tài khoản); phát video tới máy chủ media bên ngoài bằng khóa luồng được cấp sẽ ghép họ vào buổi phát.', guestGuest:'Khách', guestInvite:'Mời', guestInvited:'Đã tạo liên kết mời — chia sẻ cho khách', guestKick:'Xóa', guestList:'Người dẫn đang hoạt động', guestMute:'Tắt tiếng', guestNamePh:'Tên khách', guestNone:'Chưa mời khách nào.', guestNoSession:'Hãy chọn phiên phát trước.', guestStreamKey:'Khóa luồng', guestTitle:'Mời khách/đồng dẫn', guestUnmute:'Bật tiếng' },
  id: { tabGuests:'Tamu/Co-host', guestCohost:'Co-host', guestDelConfirm:'Hapus tamu ini?', guestDesc:'Undang beberapa pembawa acara dalam satu siaran. Tamu bergabung lewat tautan yang dibuat (tanpa akun); mengalirkan video mereka ke media server eksternal dengan stream key yang dibuat akan menggabungkan mereka ke siaran.', guestGuest:'Tamu', guestInvite:'Undang', guestInvited:'Tautan undangan dibuat — bagikan ke tamu', guestKick:'Hapus', guestList:'Pembawa acara aktif', guestMute:'Bisukan', guestNamePh:'Nama tamu', guestNone:'Belum ada tamu diundang.', guestNoSession:'Pilih sesi siaran dahulu.', guestStreamKey:'Stream key', guestTitle:'Undang tamu/co-host', guestUnmute:'Suarakan' },
  ar: { tabGuests:'ضيوف/مضيفون مشاركون', guestCohost:'مضيف مشارك', guestDelConfirm:'حذف هذا الضيف؟', guestDesc:'ادعُ عدة مقدّمين إلى بث واحد. ينضم الضيوف عبر الرابط الصادر (دون حساب)؛ وعند بث الفيديو إلى خادم الوسائط الخارجي بمفتاح البث الصادر يُدمجون في البث.', guestGuest:'ضيف', guestInvite:'دعوة', guestInvited:'تم إنشاء رابط الدعوة — شاركه مع الضيف', guestKick:'إزالة', guestList:'المقدّمون النشطون', guestMute:'كتم', guestNamePh:'اسم الضيف', guestNone:'لا ضيوف مدعوون.', guestNoSession:'اختر جلسة بث أولاً.', guestStreamKey:'مفتاح البث', guestTitle:'دعوة ضيف/مضيف مشارك', guestUnmute:'إلغاء الكتم' },
  es: { tabGuests:'Invitados/Coanfitriones', guestCohost:'Coanfitrión', guestDelConfirm:'¿Eliminar a este invitado?', guestDesc:'Invita a varios presentadores a una emisión. Los invitados se unen mediante el enlace generado (sin cuenta); al transmitir su vídeo al servidor de medios externo con la clave de stream generada se integran en la emisión.', guestGuest:'Invitado', guestInvite:'Invitar', guestInvited:'Enlace de invitación creado — compártelo con el invitado', guestKick:'Quitar', guestList:'Presentadores activos', guestMute:'Silenciar', guestNamePh:'Nombre del invitado', guestNone:'No hay invitados.', guestNoSession:'Selecciona primero una sesión de emisión.', guestStreamKey:'Clave de stream', guestTitle:'Invitar invitado/coanfitrión', guestUnmute:'Activar sonido' },
  fr: { tabGuests:'Invités/Co-animateurs', guestCohost:'Co-animateur', guestDelConfirm:'Supprimer cet invité ?', guestDesc:'Invitez plusieurs animateurs à une diffusion. Les invités rejoignent via le lien généré (sans compte) ; en diffusant leur vidéo vers le serveur média externe avec la clé de flux générée, ils sont intégrés à la diffusion.', guestGuest:'Invité', guestInvite:'Inviter', guestInvited:'Lien d’invitation créé — partagez-le avec l’invité', guestKick:'Retirer', guestList:'Animateurs actifs', guestMute:'Couper le son', guestNamePh:'Nom de l’invité', guestNone:'Aucun invité.', guestNoSession:'Sélectionnez d’abord une session de diffusion.', guestStreamKey:'Clé de flux', guestTitle:'Inviter un invité/co-animateur', guestUnmute:'Réactiver le son' },
  hi: { tabGuests:'अतिथि/सह-होस्ट', guestCohost:'सह-होस्ट', guestDelConfirm:'इस अतिथि को हटाएँ?', guestDesc:'एक प्रसारण में कई होस्ट आमंत्रित करें। अतिथि जारी लिंक से जुड़ते हैं (खाता आवश्यक नहीं); जारी स्ट्रीम कुंजी से बाहरी मीडिया सर्वर को वीडियो भेजने पर वे प्रसारण में संयोजित हो जाते हैं।', guestGuest:'अतिथि', guestInvite:'आमंत्रित करें', guestInvited:'आमंत्रण लिंक बना — अतिथि के साथ साझा करें', guestKick:'हटाएँ', guestList:'सक्रिय होस्ट', guestMute:'म्यूट', guestNamePh:'अतिथि का नाम', guestNone:'कोई अतिथि आमंत्रित नहीं।', guestNoSession:'पहले प्रसारण सत्र चुनें।', guestStreamKey:'स्ट्रीम कुंजी', guestTitle:'अतिथि/सह-होस्ट आमंत्रित करें', guestUnmute:'अनम्यूट' },
  pt: { tabGuests:'Convidados/Coanfitriões', guestCohost:'Coanfitrião', guestDelConfirm:'Excluir este convidado?', guestDesc:'Convide vários apresentadores para uma transmissão. Os convidados entram pelo link gerado (sem conta); transmitir o vídeo deles ao servidor de mídia externo com a chave de stream gerada os integra à transmissão.', guestGuest:'Convidado', guestInvite:'Convidar', guestInvited:'Link de convite criado — compartilhe com o convidado', guestKick:'Remover', guestList:'Apresentadores ativos', guestMute:'Silenciar', guestNamePh:'Nome do convidado', guestNone:'Nenhum convidado.', guestNoSession:'Selecione primeiro uma sessão de transmissão.', guestStreamKey:'Chave de stream', guestTitle:'Convidar convidado/coanfitrião', guestUnmute:'Reativar som' },
  ru: { tabGuests:'Гости/Соведущие', guestCohost:'Соведущий', guestDelConfirm:'Удалить этого гостя?', guestDesc:'Пригласите нескольких ведущих в одну трансляцию. Гости подключаются по выданной ссылке (аккаунт не нужен); при отправке их видео на внешний медиасервер с выданным ключом потока они встраиваются в трансляцию.', guestGuest:'Гость', guestInvite:'Пригласить', guestInvited:'Ссылка-приглашение создана — поделитесь с гостем', guestKick:'Удалить', guestList:'Активные ведущие', guestMute:'Заглушить', guestNamePh:'Имя гостя', guestNone:'Гости не приглашены.', guestNoSession:'Сначала выберите сессию трансляции.', guestStreamKey:'Ключ потока', guestTitle:'Пригласить гостя/соведущего', guestUnmute:'Включить звук' },
};

function findTopProp(o, name) { for (const p of o.properties) { if (p.type !== 'Property') continue; const k = p.key.type === 'Identifier' ? p.key.name : p.key.value; if (k === name) return p; } return null; }
function existing(o) { const s = new Set(); for (const p of o.properties) { if (p.type !== 'Property') continue; s.add(p.key.type === 'Identifier' ? p.key.name : p.key.value); } return s; }

const LANGS = ['ko','en','ja','zh','zh-TW','de','th','vi','id','ar','es','fr','hi','pt','ru'];
let summary = [];
for (const lang of LANGS) {
  const file = path.join(LOCDIR, lang + '.js');
  let src = fs.readFileSync(file, 'utf8');
  let added = 0;
  for (const [NS, TBL] of [['aiRuleEngine', AI], ['liveCommerce', LC]]) {
    const tr = TBL[lang]; if (!tr) { console.error(`${lang}: no table for ${NS}`); process.exit(2); }
    const ast = parse(src, { ecmaVersion: 'latest', sourceType: 'module' });
    let root = null; for (const b of ast.body) if (b.type === 'ExportDefaultDeclaration') root = b.declaration;
    const ns = findTopProp(root, NS);
    if (!ns || ns.value.type !== 'ObjectExpression') { console.error(`${lang}: no ${NS} namespace`); process.exit(2); }
    const have = existing(ns.value);
    const toAdd = Object.keys(tr).filter(k => !have.has(k));
    if (!toAdd.length) continue;
    const props = ns.value.properties; const last = props[props.length - 1];
    let ins = ''; for (const k of toAdd) ins += `, ${JSON.stringify(k)}: ${JSON.stringify(tr[k])}`;
    src = src.slice(0, last.end) + ins + src.slice(last.end);
    parse(src, { ecmaVersion: 'latest', sourceType: 'module' }); // 재파싱 검증
    added += toAdd.length;
  }
  fs.writeFileSync(file, src, 'utf8');
  summary.push(`${lang}: +${added}`);
}
console.log(summary.join('\n'));
