#!/usr/bin/env node
/**
 * P1 i18n — DeveloperHub 웹훅 실관리 패널 신규 라벨(devHub.wh*) 29키 15개국 주입.
 * acorn 위치탐색 + 문자열 splice(포맷 보존). 멱등(기존 키 skip).
 */
const fs = require('fs');
const path = require('path');
const { parse } = require('acorn');

const LOCDIR = path.join(__dirname, '..', 'frontend', 'src', 'i18n', 'locales');
const NS = 'devHub';

const KEYS = ['whUrlInvalid','whPickEvent','whCreateFail','whTestOk','whTestFail','whUpdateFail','whDeleteConfirm','whDeleted','whDeleteFail','whSecretOnce','whRegister','whDescPh','whSubscribeEvents','whNoCatalog','whRegistering','whRegisterBtn','whEndpoints','whNone','whActive','whPaused','whLast','whFails','whTest','whPause','whResume','whDelete','whDeliveries','whAttempts','whVerifyTitle'];

const T = {
  ko: { whUrlInvalid:'URL은 https:// 로 시작해야 합니다.', whPickEvent:'구독할 이벤트를 1개 이상 선택하세요.', whCreateFail:'등록에 실패했습니다.', whTestOk:'테스트 이벤트가 전달되었습니다.', whTestFail:'전달 실패', whUpdateFail:'변경 실패', whDeleteConfirm:'이 웹훅 구독을 삭제하시겠습니까?', whDeleted:'삭제되었습니다.', whDeleteFail:'삭제 실패', whSecretOnce:'이 서명 시크릿은 다시 표시되지 않습니다.', whRegister:'웹훅 엔드포인트 등록', whDescPh:'설명(선택)', whSubscribeEvents:'구독 이벤트', whNoCatalog:'이벤트 카탈로그를 불러오지 못했습니다.', whRegistering:'등록 중...', whRegisterBtn:'구독 등록', whEndpoints:'등록된 엔드포인트', whNone:'등록된 웹훅 구독이 없습니다.', whActive:'활성', whPaused:'일시중지', whLast:'최근', whFails:'실패', whTest:'테스트', whPause:'중지', whResume:'재개', whDelete:'삭제', whDeliveries:'최근 전달 로그', whAttempts:'회 시도', whVerifyTitle:'서명 검증 (수신 측)' },
  en: { whUrlInvalid:'URL must start with https://.', whPickEvent:'Select at least one event to subscribe.', whCreateFail:'Registration failed.', whTestOk:'Test event delivered.', whTestFail:'Delivery failed', whUpdateFail:'Update failed', whDeleteConfirm:'Delete this webhook subscription?', whDeleted:'Deleted.', whDeleteFail:'Delete failed', whSecretOnce:'This signing secret will not be shown again.', whRegister:'Register webhook endpoint', whDescPh:'Description (optional)', whSubscribeEvents:'Subscribed events', whNoCatalog:'Failed to load event catalog.', whRegistering:'Registering...', whRegisterBtn:'Register subscription', whEndpoints:'Registered endpoints', whNone:'No webhook subscriptions registered.', whActive:'Active', whPaused:'Paused', whLast:'Last', whFails:'Failures', whTest:'Test', whPause:'Pause', whResume:'Resume', whDelete:'Delete', whDeliveries:'Recent delivery log', whAttempts:' attempts', whVerifyTitle:'Signature verification (receiver side)' },
  ja: { whUrlInvalid:'URL は https:// で始める必要があります。', whPickEvent:'購読するイベントを1つ以上選択してください。', whCreateFail:'登録に失敗しました。', whTestOk:'テストイベントを送信しました。', whTestFail:'送信失敗', whUpdateFail:'変更失敗', whDeleteConfirm:'このウェブフック購読を削除しますか？', whDeleted:'削除しました。', whDeleteFail:'削除失敗', whSecretOnce:'この署名シークレットは再表示されません。', whRegister:'ウェブフックエンドポイント登録', whDescPh:'説明（任意）', whSubscribeEvents:'購読イベント', whNoCatalog:'イベントカタログを読み込めませんでした。', whRegistering:'登録中...', whRegisterBtn:'購読登録', whEndpoints:'登録済みエンドポイント', whNone:'登録されたウェブフック購読がありません。', whActive:'有効', whPaused:'一時停止', whLast:'最近', whFails:'失敗', whTest:'テスト', whPause:'停止', whResume:'再開', whDelete:'削除', whDeliveries:'最近の送信ログ', whAttempts:'回試行', whVerifyTitle:'署名検証（受信側）' },
  zh: { whUrlInvalid:'URL 必须以 https:// 开头。', whPickEvent:'请至少选择一个要订阅的事件。', whCreateFail:'注册失败。', whTestOk:'测试事件已送达。', whTestFail:'送达失败', whUpdateFail:'更新失败', whDeleteConfirm:'确定删除此 Webhook 订阅吗？', whDeleted:'已删除。', whDeleteFail:'删除失败', whSecretOnce:'此签名密钥不会再次显示。', whRegister:'注册 Webhook 端点', whDescPh:'说明（可选）', whSubscribeEvents:'订阅事件', whNoCatalog:'无法加载事件目录。', whRegistering:'注册中...', whRegisterBtn:'注册订阅', whEndpoints:'已注册端点', whNone:'尚无 Webhook 订阅。', whActive:'启用', whPaused:'已暂停', whLast:'最近', whFails:'失败', whTest:'测试', whPause:'暂停', whResume:'恢复', whDelete:'删除', whDeliveries:'最近送达日志', whAttempts:'次尝试', whVerifyTitle:'签名验证（接收方）' },
  'zh-TW': { whUrlInvalid:'URL 必須以 https:// 開頭。', whPickEvent:'請至少選擇一個要訂閱的事件。', whCreateFail:'註冊失敗。', whTestOk:'測試事件已送達。', whTestFail:'送達失敗', whUpdateFail:'更新失敗', whDeleteConfirm:'確定刪除此 Webhook 訂閱嗎？', whDeleted:'已刪除。', whDeleteFail:'刪除失敗', whSecretOnce:'此簽章密鑰不會再次顯示。', whRegister:'註冊 Webhook 端點', whDescPh:'說明（選填）', whSubscribeEvents:'訂閱事件', whNoCatalog:'無法載入事件目錄。', whRegistering:'註冊中...', whRegisterBtn:'註冊訂閱', whEndpoints:'已註冊端點', whNone:'尚無 Webhook 訂閱。', whActive:'啟用', whPaused:'已暫停', whLast:'最近', whFails:'失敗', whTest:'測試', whPause:'暫停', whResume:'恢復', whDelete:'刪除', whDeliveries:'最近送達紀錄', whAttempts:'次嘗試', whVerifyTitle:'簽章驗證（接收方）' },
  de: { whUrlInvalid:'URL muss mit https:// beginnen.', whPickEvent:'Wählen Sie mindestens ein Event zum Abonnieren.', whCreateFail:'Registrierung fehlgeschlagen.', whTestOk:'Test-Event zugestellt.', whTestFail:'Zustellung fehlgeschlagen', whUpdateFail:'Aktualisierung fehlgeschlagen', whDeleteConfirm:'Dieses Webhook-Abonnement löschen?', whDeleted:'Gelöscht.', whDeleteFail:'Löschen fehlgeschlagen', whSecretOnce:'Dieses Signatur-Secret wird nicht erneut angezeigt.', whRegister:'Webhook-Endpunkt registrieren', whDescPh:'Beschreibung (optional)', whSubscribeEvents:'Abonnierte Events', whNoCatalog:'Event-Katalog konnte nicht geladen werden.', whRegistering:'Wird registriert...', whRegisterBtn:'Abonnement registrieren', whEndpoints:'Registrierte Endpunkte', whNone:'Keine Webhook-Abonnements registriert.', whActive:'Aktiv', whPaused:'Pausiert', whLast:'Zuletzt', whFails:'Fehler', whTest:'Test', whPause:'Pausieren', whResume:'Fortsetzen', whDelete:'Löschen', whDeliveries:'Letztes Zustellprotokoll', whAttempts:' Versuche', whVerifyTitle:'Signaturprüfung (Empfängerseite)' },
  th: { whUrlInvalid:'URL ต้องขึ้นต้นด้วย https://', whPickEvent:'เลือกอย่างน้อยหนึ่งเหตุการณ์เพื่อสมัครรับ', whCreateFail:'ลงทะเบียนไม่สำเร็จ', whTestOk:'ส่งเหตุการณ์ทดสอบแล้ว', whTestFail:'ส่งไม่สำเร็จ', whUpdateFail:'อัปเดตไม่สำเร็จ', whDeleteConfirm:'ลบการสมัครรับ Webhook นี้หรือไม่?', whDeleted:'ลบแล้ว', whDeleteFail:'ลบไม่สำเร็จ', whSecretOnce:'คีย์ลายเซ็นนี้จะไม่แสดงอีก', whRegister:'ลงทะเบียนปลายทาง Webhook', whDescPh:'คำอธิบาย (ไม่บังคับ)', whSubscribeEvents:'เหตุการณ์ที่สมัครรับ', whNoCatalog:'โหลดแคตตาล็อกเหตุการณ์ไม่สำเร็จ', whRegistering:'กำลังลงทะเบียน...', whRegisterBtn:'ลงทะเบียนการสมัครรับ', whEndpoints:'ปลายทางที่ลงทะเบียน', whNone:'ยังไม่มีการสมัครรับ Webhook', whActive:'ใช้งาน', whPaused:'หยุดชั่วคราว', whLast:'ล่าสุด', whFails:'ล้มเหลว', whTest:'ทดสอบ', whPause:'หยุด', whResume:'ดำเนินต่อ', whDelete:'ลบ', whDeliveries:'บันทึกการส่งล่าสุด', whAttempts:' ครั้งที่พยายาม', whVerifyTitle:'การตรวจสอบลายเซ็น (ฝั่งผู้รับ)' },
  vi: { whUrlInvalid:'URL phải bắt đầu bằng https://.', whPickEvent:'Chọn ít nhất một sự kiện để đăng ký.', whCreateFail:'Đăng ký thất bại.', whTestOk:'Đã gửi sự kiện thử nghiệm.', whTestFail:'Gửi thất bại', whUpdateFail:'Cập nhật thất bại', whDeleteConfirm:'Xóa đăng ký webhook này?', whDeleted:'Đã xóa.', whDeleteFail:'Xóa thất bại', whSecretOnce:'Khóa ký này sẽ không hiển thị lại.', whRegister:'Đăng ký điểm cuối webhook', whDescPh:'Mô tả (tùy chọn)', whSubscribeEvents:'Sự kiện đã đăng ký', whNoCatalog:'Không tải được danh mục sự kiện.', whRegistering:'Đang đăng ký...', whRegisterBtn:'Đăng ký', whEndpoints:'Điểm cuối đã đăng ký', whNone:'Chưa có đăng ký webhook nào.', whActive:'Hoạt động', whPaused:'Tạm dừng', whLast:'Gần nhất', whFails:'Lỗi', whTest:'Thử', whPause:'Tạm dừng', whResume:'Tiếp tục', whDelete:'Xóa', whDeliveries:'Nhật ký gửi gần đây', whAttempts:' lần thử', whVerifyTitle:'Xác minh chữ ký (phía nhận)' },
  id: { whUrlInvalid:'URL harus diawali https://.', whPickEvent:'Pilih minimal satu event untuk berlangganan.', whCreateFail:'Pendaftaran gagal.', whTestOk:'Event uji terkirim.', whTestFail:'Pengiriman gagal', whUpdateFail:'Pembaruan gagal', whDeleteConfirm:'Hapus langganan webhook ini?', whDeleted:'Dihapus.', whDeleteFail:'Hapus gagal', whSecretOnce:'Secret penandatanganan ini tidak akan ditampilkan lagi.', whRegister:'Daftarkan endpoint webhook', whDescPh:'Deskripsi (opsional)', whSubscribeEvents:'Event berlangganan', whNoCatalog:'Gagal memuat katalog event.', whRegistering:'Mendaftar...', whRegisterBtn:'Daftarkan langganan', whEndpoints:'Endpoint terdaftar', whNone:'Belum ada langganan webhook.', whActive:'Aktif', whPaused:'Dijeda', whLast:'Terakhir', whFails:'Gagal', whTest:'Uji', whPause:'Jeda', whResume:'Lanjutkan', whDelete:'Hapus', whDeliveries:'Log pengiriman terbaru', whAttempts:' percobaan', whVerifyTitle:'Verifikasi tanda tangan (sisi penerima)' },
  ar: { whUrlInvalid:'يجب أن يبدأ الرابط بـ https://.', whPickEvent:'اختر حدثًا واحدًا على الأقل للاشتراك.', whCreateFail:'فشل التسجيل.', whTestOk:'تم تسليم حدث الاختبار.', whTestFail:'فشل التسليم', whUpdateFail:'فشل التحديث', whDeleteConfirm:'حذف اشتراك الويب هوك هذا؟', whDeleted:'تم الحذف.', whDeleteFail:'فشل الحذف', whSecretOnce:'لن يظهر مفتاح التوقيع هذا مرة أخرى.', whRegister:'تسجيل نقطة نهاية الويب هوك', whDescPh:'الوصف (اختياري)', whSubscribeEvents:'الأحداث المشترَك بها', whNoCatalog:'تعذر تحميل كتالوج الأحداث.', whRegistering:'جارٍ التسجيل...', whRegisterBtn:'تسجيل الاشتراك', whEndpoints:'نقاط النهاية المسجلة', whNone:'لا توجد اشتراكات ويب هوك مسجلة.', whActive:'نشط', whPaused:'متوقف مؤقتًا', whLast:'الأخير', whFails:'إخفاقات', whTest:'اختبار', whPause:'إيقاف', whResume:'استئناف', whDelete:'حذف', whDeliveries:'سجل التسليم الأخير', whAttempts:' محاولات', whVerifyTitle:'التحقق من التوقيع (جهة الاستقبال)' },
  es: { whUrlInvalid:'La URL debe comenzar con https://.', whPickEvent:'Selecciona al menos un evento para suscribirte.', whCreateFail:'Error al registrar.', whTestOk:'Evento de prueba entregado.', whTestFail:'Error de entrega', whUpdateFail:'Error al actualizar', whDeleteConfirm:'¿Eliminar esta suscripción de webhook?', whDeleted:'Eliminado.', whDeleteFail:'Error al eliminar', whSecretOnce:'Este secreto de firma no se mostrará de nuevo.', whRegister:'Registrar endpoint de webhook', whDescPh:'Descripción (opcional)', whSubscribeEvents:'Eventos suscritos', whNoCatalog:'No se pudo cargar el catálogo de eventos.', whRegistering:'Registrando...', whRegisterBtn:'Registrar suscripción', whEndpoints:'Endpoints registrados', whNone:'No hay suscripciones de webhook registradas.', whActive:'Activo', whPaused:'En pausa', whLast:'Último', whFails:'Fallos', whTest:'Probar', whPause:'Pausar', whResume:'Reanudar', whDelete:'Eliminar', whDeliveries:'Registro de entregas reciente', whAttempts:' intentos', whVerifyTitle:'Verificación de firma (lado receptor)' },
  fr: { whUrlInvalid:'L’URL doit commencer par https://.', whPickEvent:'Sélectionnez au moins un événement à abonner.', whCreateFail:'Échec de l’enregistrement.', whTestOk:'Événement de test livré.', whTestFail:'Échec de la livraison', whUpdateFail:'Échec de la mise à jour', whDeleteConfirm:'Supprimer cet abonnement webhook ?', whDeleted:'Supprimé.', whDeleteFail:'Échec de la suppression', whSecretOnce:'Ce secret de signature ne sera plus affiché.', whRegister:'Enregistrer le point de terminaison webhook', whDescPh:'Description (facultatif)', whSubscribeEvents:'Événements abonnés', whNoCatalog:'Échec du chargement du catalogue d’événements.', whRegistering:'Enregistrement...', whRegisterBtn:'Enregistrer l’abonnement', whEndpoints:'Points de terminaison enregistrés', whNone:'Aucun abonnement webhook enregistré.', whActive:'Actif', whPaused:'En pause', whLast:'Dernier', whFails:'Échecs', whTest:'Tester', whPause:'Pause', whResume:'Reprendre', whDelete:'Supprimer', whDeliveries:'Journal de livraison récent', whAttempts:' tentatives', whVerifyTitle:'Vérification de signature (côté récepteur)' },
  hi: { whUrlInvalid:'URL https:// से शुरू होना चाहिए।', whPickEvent:'सदस्यता के लिए कम से कम एक इवेंट चुनें।', whCreateFail:'पंजीकरण विफल।', whTestOk:'परीक्षण इवेंट भेज दिया गया।', whTestFail:'डिलीवरी विफल', whUpdateFail:'अपडेट विफल', whDeleteConfirm:'क्या यह वेबहुक सदस्यता हटाएँ?', whDeleted:'हटा दिया गया।', whDeleteFail:'हटाना विफल', whSecretOnce:'यह साइनिंग सीक्रेट दोबारा नहीं दिखेगा।', whRegister:'वेबहुक एंडपॉइंट पंजीकृत करें', whDescPh:'विवरण (वैकल्पिक)', whSubscribeEvents:'सब्सक्राइब्ड इवेंट', whNoCatalog:'इवेंट कैटलॉग लोड नहीं हो सका।', whRegistering:'पंजीकरण हो रहा है...', whRegisterBtn:'सदस्यता पंजीकृत करें', whEndpoints:'पंजीकृत एंडपॉइंट', whNone:'कोई वेबहुक सदस्यता पंजीकृत नहीं।', whActive:'सक्रिय', whPaused:'रोका गया', whLast:'अंतिम', whFails:'विफलताएँ', whTest:'परीक्षण', whPause:'रोकें', whResume:'फिर शुरू', whDelete:'हटाएँ', whDeliveries:'हाल का डिलीवरी लॉग', whAttempts:' प्रयास', whVerifyTitle:'हस्ताक्षर सत्यापन (प्राप्तकर्ता पक्ष)' },
  pt: { whUrlInvalid:'A URL deve começar com https://.', whPickEvent:'Selecione pelo menos um evento para assinar.', whCreateFail:'Falha no registro.', whTestOk:'Evento de teste entregue.', whTestFail:'Falha na entrega', whUpdateFail:'Falha na atualização', whDeleteConfirm:'Excluir esta assinatura de webhook?', whDeleted:'Excluído.', whDeleteFail:'Falha ao excluir', whSecretOnce:'Este segredo de assinatura não será exibido novamente.', whRegister:'Registrar endpoint de webhook', whDescPh:'Descrição (opcional)', whSubscribeEvents:'Eventos assinados', whNoCatalog:'Falha ao carregar o catálogo de eventos.', whRegistering:'Registrando...', whRegisterBtn:'Registrar assinatura', whEndpoints:'Endpoints registrados', whNone:'Nenhuma assinatura de webhook registrada.', whActive:'Ativo', whPaused:'Pausado', whLast:'Último', whFails:'Falhas', whTest:'Testar', whPause:'Pausar', whResume:'Retomar', whDelete:'Excluir', whDeliveries:'Registro de entregas recente', whAttempts:' tentativas', whVerifyTitle:'Verificação de assinatura (lado receptor)' },
  ru: { whUrlInvalid:'URL должен начинаться с https://.', whPickEvent:'Выберите хотя бы одно событие для подписки.', whCreateFail:'Ошибка регистрации.', whTestOk:'Тестовое событие доставлено.', whTestFail:'Ошибка доставки', whUpdateFail:'Ошибка обновления', whDeleteConfirm:'Удалить эту подписку на вебхук?', whDeleted:'Удалено.', whDeleteFail:'Ошибка удаления', whSecretOnce:'Этот секрет подписи больше не будет показан.', whRegister:'Зарегистрировать эндпоинт вебхука', whDescPh:'Описание (необязательно)', whSubscribeEvents:'Подписанные события', whNoCatalog:'Не удалось загрузить каталог событий.', whRegistering:'Регистрация...', whRegisterBtn:'Зарегистрировать подписку', whEndpoints:'Зарегистрированные эндпоинты', whNone:'Подписок на вебхуки нет.', whActive:'Активен', whPaused:'Приостановлен', whLast:'Последний', whFails:'Сбои', whTest:'Тест', whPause:'Пауза', whResume:'Возобновить', whDelete:'Удалить', whDeliveries:'Журнал доставки', whAttempts:' попыток', whVerifyTitle:'Проверка подписи (на стороне получателя)' },
};

function findTopProp(objExpr, name) {
  for (const p of objExpr.properties) {
    if (p.type !== 'Property') continue;
    const k = p.key.type === 'Identifier' ? p.key.name : p.key.value;
    if (k === name) return p;
  }
  return null;
}
function existingKeys(objExpr) {
  const s = new Set();
  for (const p of objExpr.properties) { if (p.type !== 'Property') continue; s.add(p.key.type === 'Identifier' ? p.key.name : p.key.value); }
  return s;
}

let summary = [];
for (const [lang, tr] of Object.entries(T)) {
  const file = path.join(LOCDIR, lang + '.js');
  let src = fs.readFileSync(file, 'utf8');
  const ast = parse(src, { ecmaVersion: 'latest', sourceType: 'module' });
  let rootObj = null;
  for (const b of ast.body) if (b.type === 'ExportDefaultDeclaration') rootObj = b.declaration;
  if (!rootObj || rootObj.type !== 'ObjectExpression') { console.error(`${lang}: no export default object`); process.exit(2); }
  const nsProp = findTopProp(rootObj, NS);
  if (!nsProp || nsProp.value.type !== 'ObjectExpression') { console.error(`${lang}: no ${NS} object`); process.exit(2); }
  const nsObj = nsProp.value;
  const have = existingKeys(nsObj);
  const toAdd = KEYS.filter(k => !have.has(k));
  if (toAdd.length === 0) { summary.push(`${lang}: 0 (already present)`); continue; }
  const props = nsObj.properties;
  const last = props[props.length - 1];
  const insPos = last.end;
  let ins = '';
  for (const k of toAdd) ins += `, ${JSON.stringify(k)}: ${JSON.stringify(tr[k])}`;
  src = src.slice(0, insPos) + ins + src.slice(insPos);
  parse(src, { ecmaVersion: 'latest', sourceType: 'module' });   // 검증
  fs.writeFileSync(file, src, 'utf8');
  summary.push(`${lang}: +${toAdd.length}`);
}
console.log(summary.join('\n'));
